### ISSUE TITLE
Filtros de Facturas y Contratos

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#10]
Mejorar el estilo de los filtros de las facturas y los contratos, hacerlos ColorCoded y mejorar la experiencia del usuario

**Comment by santiagomachacon** [comment]
En filtros CONTRATOS y filtros FACTURAS parece correcto. 1 click aparece, otro click desaparece (el seleccionado. De todos modos cuando tienes un filtro visible, yo cambiaría el color del nombre de azul a naranja).

**Comment by bpesquero** [comment]
Hacer propuestas a Eric de mejora

**Comment by bpesquero** [comment]
Haría lo que proponías de pintar de otro color los filtros usuados. El tema de fecha inicio y fecha fin no queda muy claro. Quizá podríamos poner fecha factura desde y fecha factura hasta

**Comment by bpesquero** [comment]
Adjunto documento con especificación de  la pantalla de listado de facturas. El funcionamiento de que la etiqueta de filtro cambie de aspecto habría que replicarlo en la lista de contratos.

[Listado de facturas.docx](https://github.com/geoatlanter/webProxima/files/420276/Listado.de.facturas.docx)

**Comment by bpesquero** [comment]
ok
