### ISSUE TITLE
NAV - Indicativo de dirección fiscal OCSUM

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#102]
EL indicativo por defecto de dirección fiscal cuando se crea el contrato debe ser "S" en vez de "F". Además en el caso de que sea "F", hay que informar de la dirección fiscal del titular.

**Comment by PKFEric** [comment]
En hidroelectrica el carmen siempre poner S y en geo también,  si es F en el caso del A3  entonces hay que rellenar la direccion fiscal el en fichero A3_01

**Comment by PKFEric** [comment]
Esto esta corregido ya. Hay que probarlo para el caso de que tengamos un A3 en el que no coincida la dirección de suministro con la fiscal

**Comment by bpesquero** [comment]
Probado y ok
