### ISSUE TITLE
WEB - error potencia para la 3.1A

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#103]
Al dar de alta en la web un contrato de la 3.1A al meter la potencia da error "Potencia <= 450 kW"
 La 3.1A es para potencias entre 0 y 450 kW. Envío po r mail la tabla de limitaciones de potencia y un pantallazo con el error.

**Comment by PKFEric** [comment]
Corregido. Estaba mal relleno el limite inferior que era 10 ahora esta a 0.

PROBAR

**Comment by bpesquero** [comment]
Probado y ok
