### ISSUE TITLE
NAV-HECEN-DErechos de enganche milenial con A3

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1046]
Actualmente cuando tenemos un contrato que pasa de otra tarifa a milenial no se le facturan los derechos de enganche, sin enmargo hay que tener en cuenta que cuando proviene de un A3, si debemos facturar este concepto. Son facturas que venimos controlando y haciendo a mano, pero creo que lo ideal es cambiar el control para que salieran estas facturas.
Pongo como ejemplo el contrato HECEN/13319.

Gracias

**Comment by JMunoz17** [comment]
Belén, una duda.

Nos serviría simplemente con consultar el histórico de acciones asociado a este contrato y buscar un registro con:
- Código de Proceso: A3
- Código de Paso: 05

Con esto sería suficiente verdad? O podría darse algún caso diferente?

**Comment by bpesquero** [comment]
Si, efectivamente

**Comment by JMunoz17** [comment]
Factura de venta generada para el HECEN/13319.

Subido a PRE y PROD.

**Comment by bpesquero** [comment]
La factura de venta FV/2021010144 no ha facturado los derechos de engache, procediento el contato de un A3.
DEjo la factura abierta para que la veais

**Comment by JMunoz17** [comment]
Nos faltaba otro sitio donde añadir la condición, factura generada: FV/2021010158

Subido a PRE y PROD.
