### ISSUE TITLE
NAV-Facturas de Enganche

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#105]
Ajustar el XML Port para que lea bien la información de las facturas de enganche.

Verificar que la informacion se rellena correctamente en la tabla de peajes.

Verificar que salen bien tanto la factura de compra como la de venta.

Verificar que sale correcto el PDF de la factura en Venta.

**Comment by PKFEric** [comment]
Quitar del report:

De Datos de la factura de electricidad -> Periodo de consumo
Apartado INFORMACIÓN DEL CONSUMO ELÉCTRICO.
DESTINO DEL IMPORTE  DE LA FACTURA
ORIGEN E IMPACTO AMBIENTAL DE LA ENERGÍA Y LA IMAGEN.

**Comment by jorgereal** [comment]
SUBIDO -> PROBAR

**Comment by bpesquero** [comment]
Probado y ok
