### ISSUE TITLE
NAv - error control potencia facturada peaje  vs venta

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#106]
Al realizar la factura de venta del contrato HECEN/07944, da el siguiente error La potencia facturada 3,464 del peaje en el periodo 1 es diferente de la potencia facturada 3,464.

**Comment by PKFEric** [comment]
YA ESTA LA FACTURA GENERADA EN NAV

**Comment by PKFEric** [comment]
Y EL PROBLEMA RESUELTO, le habíamos metido un redondeo a 2 decimales, que entiendo que no tiene sentido ya que la potencia viene en W y la transformamos al KW por lo tanto los decimales de comparación deberían de ser 3. No se si estoy en lo correcto?

**Comment by bpesquero** [comment]
Así es
