### ISSUE TITLE
Incidencias Autoconsumo

### ISSUE THREAD

**Issue by JMunoz17** [PKFEric/webProxima#1067]
1.- El   COM/00827 tiene como primera fecha de detalle el 29/10/2019 y sin embargo le hemos empezado a pasar financiación el 30/09/2020. ESto nos pasó con muchas y pasamos un proceso para "quitar los registros anteriores a 30/09/2020 y ponerlos la cola y alargar la financiación" Te acuerdas? Lo podemos hacer con este?

2.- Aunque esto ya lo hemos cambiado y ahora al generar una nueva financiación se actualiza el campo fecha fin de renting, antes no era así, y tenemos algunas fichas con este campo incorrecto, ¿podríamos pasar un proceso para corregirlo?

3.- Hemos borrado la ficha AT00141 del contrato COM/01896 y proyecto 136. Pasamos el proceso de importación de fichas para volver a generar la misma, y nos da el siguiente error
 
![image](https://user-images.githubusercontent.com/26869276/107770563-e657a880-6d39-11eb-987d-a57695937ea6.png)

He mirado el PA y está devolviendo correctamente los valores de este registro. Le puedes echar un vistazo?

**Comment by bpesquero** [comment]
Cuando SAbrina intenta importar le da este error (ha instalado la dll) 
![image](https://user-images.githubusercontent.com/20299071/108216665-040a8080-7133-11eb-808a-f7d674669291.png)

Al hacerlo yo me da el siguiente error

![image](https://user-images.githubusercontent.com/20299071/108216533-e3422b00-7132-11eb-842b-00cf21f6f2bd.png)

**Comment by JMunoz17** [comment]
Puntos 1 y 2 realizados, hemos pasado los procesos correspondientes.

Punto 3 pendiente de que nos confirméis que funciona (contestado ayer por email).
