### ISSUE TITLE
NAv-GAC-factura de compra M6008N00000991

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1069]
La factura de compra M6008N00000991 coorespondiente al contrato COM/04184 está cargada en toll measures y ha generado factura de venta, pero no tiene factura de compra asociada.
Habría que faturarla y aprovechar para revisar más registros en la tabla de toll measures sin factura de compra. Es algo que pasa de vez en cuando.

**Comment by jorgereal** [comment]
El F1 correspondiente a la factura de compra M6008N00000991 es el 0359_0587_F1_01_M6008N00000991_ES0359000000005744QS0F.xml

No lo encontramos en la carpeta de F1s ni en ninguna subcarpeta.
¿Vosotros lo tenéis? Lo necesitamos para volver a simular la importación y comprobar qué ha pasado con la compra.

**Comment by bpesquero** [comment]
Te lo envío por email

**Comment by jorgereal** [comment]
Se ha vuelto a cargar el F1 y se ha generado la prefactura de compra FC/2021003130.

Hemos eliminado la nueva entrada generada en toll measures y hemos rellenado el número de factura de compra en la antigua.

Tras revisar los registros de toll measures sin factura/abono de compra del 2019 en adelante  hemos encontrado los correspondientes a los siguientes ficheros:

0021_0587_F1_01_03201214030341768_ES0021000005678805RX0P.xml
0021_0587_F1_01_03201223030199093_ES0021000001430350ET0P.xml
0022_0587_F1_01_5020123007135_ES0022000007273477HJ1P.xml
0022_0587_F1_01_J820007414463_ES0022000007962240HH1P.xml
20200607021635-F1-ES0031300081763001DB0F_0006.xml
SCTDE_F1_01_0022_0587_20191031124930077_(812027699).xml
0023_0587_F1_01_S8002N00127938_ES0031104820427001QA0F.xml
0400_0587_F1_01_2020N00054570_ES0400134961175184ST0F.xml

Hemos localizado todos los xml salvo estos 3:
SCTDE_F1_01_0022_0587_20191031124930077_(812027699).xml 
0023_0587_F1_01_S8002N00127938_ES0031104820427001QA0F.xml 
0400_0587_F1_01_2020N00054570_ES0400134961175184ST0F.xml 

Vamos a intentar ir importando los que tenemos.

**Comment by bpesquero** [comment]
Para localizar los tres que faltan me podéis pasar CUPS, fechas y nº de factura de acceso?
Sería interesante entender por qué pasa, no podemos estar cada cierto tiempo con esto.
Gracias

**Comment by jorgereal** [comment]
Hemos podido cargar los ficheros:

0021_0587_F1_01_03201214030341768_ES0021000005678805RX0P.xml -> Prefactura compra FC/2021003310
0021_0587_F1_01_03201223030199093_ES0021000001430350ET0P.xml -> Prefactura compra FC/2021003311
0022_0587_F1_01_5020123007135_ES0022000007273477HJ1P.xml -> Prefactura compra FC/2021003312
0022_0587_F1_01_J820007414463_ES0022000007962240HH1P.xml -> Prefactura compra FC/2021003309
20200607021635-F1-ES0031300081763001DB0F_0006.xml -> Preabono compra ABC/202100017

La información sobre los faltantes

SCTDE_F1_01_0022_0587_20191031124930077_(812027699).xml
Cups: ES0022000008865940AW | Nº Factura: A118000000995 (No tenemos periodo de fechas)

0023_0587_F1_01_S8002N00127938_ES0031104820427001QA0F.xml
Cups: ES0031104820427001QA0F |Nº Factura:  S8002N00127938 | Fecha desde: 09/11/2020 | Fecha hasta: 10/11/2020

0400_0587_F1_01_2020N00054570_ES0400134961175184ST0F.xml 
Cups: ES0400134961175184ST0F | Nº Factura: 2020N00054570 (No tenemos periodo de fechas)

Los ficheros que se han importado no han dado errores (salvo los previsibles de que ya se había importado el fichero y derivados), por lo que no es un error en la importación de los F1s.

La importación consta de dos pasos:
-Importación del fichero, generando peajes y cierres.
-Creación del documento de compra

Al completarse el primer paso se realiza un guardado en BBDD (esto no se puede cambiar).
Si el segundo paso falla no se genera el documento pero los peajes y cierres ya han sido importados.
Tenemos controlados los posibles fallos que puede dar la generación del documento de compra, para en ese caso borrar los peajes y cierres ya importados y notificar el error.
El problema viene cuando la creación del documento de compra no finaliza por un motivo ajeno, ya sea que el usuario termina el proceso, alguna de las tablas en las que se escribe está bloqueada, se pierde la conexión con el sql...

No tenemos forma de controlar este tipo de errores, pero lo que no puede ocurrir es que el fichero se mueva a procesados si no ha concluido correctamente la generación del documento.

**Comment by bpesquero** [comment]
Envío por email los 3 ficheros que nos faltaban

**Comment by jorgereal** [comment]
Se han cargado los 3 ficheros restantes:
SCTDE_F1_01_0022_0587_20191031124930077_(812027699).xml -> Preabono compra ABC/202100018
0023_0587_F1_01_S8002N00127938_ES0031104820427001QA0F.xml -> Prefactura compra FC/2021003526
0400_0587_F1_01_2020N00054570_ES0400134961175184ST0F.xml -> Prefactura compra FC/2021003525

**Comment by bpesquero** [comment]
Entiendo que has relacionado con la factura de venta que ya teníamos, verdad?
