### ISSUE TITLE
NAV - problema validación de tarifa con M1_05

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#107]

**Comment by jorgereal** [comment]
Solucionado.
SUBIDO -> PROBAR

**Comment by bpesquero** [comment]
Solucionada la validación de la tarifa, pero da error con la validación de la potencia, exactamente por el mismo motivo. La compara con la potencia anterior en vez de con la nueva.

**Comment by PKFEric** [comment]
Ya esta arreglado e Importado el M1_05

**Comment by PKFEric** [comment]
Faltaria procesarlo.
