### ISSUE TITLE
NAV-GAC- Informe de IMU

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1076]
Al sacarme el informe de IMU para la población GABIA GRANDE con CP 18110 para el año 2020 me sale el informe vacío cuando realmente sí tiene facturas asociadas al contrato COM/02786
He probado a sacarlo por CP, por población, por contrato y de cualquier forma me sale el informe vacío.

**Comment by JMunoz17** [comment]
El problema era que en el contrato, en el campo Población de suministro ponía "GABIA GRANDE", mientras que en la población asociada a ese C.P. en la tabla de códigos postales ponía "GABIAS, LAS".

He asignado "GABIAS, LAS" al contrato y ya sale el informe correcto.

Por que puede haberse dado esta diferencia el un nombre y otro? 
Deberíamos añadir algún tipo de comprobación? O pasar algún proceso que revise si tenéis todos los contratos con el dato bien informado?

**Comment by bpesquero** [comment]
Pues la cuestión es que parece que hay CP que corresponden a más de una población, así que no sé cómo habría que solucionar esto.
¿Y por qué también falla cuando filtramos por CP, o por contrato?

**Comment by JMunoz17** [comment]
El filtro que manda es el de Código Postal.

Cogemos todos los códigos postales dentro del filtro que hayáis indicado y para cada uno de esos códigos postales buscamos los contratos asociados teniendo en cuenta CP Suministro y Población Suministro (aquí añadimos los filtros de contrato que hayáis indicado al lanzar el informe, pero siempre se sigue filtrando por CP Suministro y Población Suministro).

Quieres que pasemos un proceso para consultar si tenemos mas casos erróneos?

He consultado con los compañeros y en la api se comprueba que la combinación de Código Postal y Provincia de suministro existan en la tabla de códigos postales. Si quieres añadimos un control también en NAV al rellenar la Población de suministro en la ficha del contrato (no sé si eso soléis modificarlo a mano). 

Y lo único que tendríais que evitar es modificar en la tabla de códigos postales el nombre de una población sin cambiarlo en todos los contratos correspondientes.

**Comment by dgarciageo** [comment]
@JMunoz17, @bpesquero

Se hizo una limpieza de la tabla Post Code porque había filas duplicadas y algunas combinaciones incorrectas
Puede que el problema se deba a eso. (Tengo la versión antes del cambio por si lo necesitamos)

¿No podemos usar el Código de Municipio en lugar del Nombre del Municipio para sacar el informe IMU?

> Y lo único que tendríais que evitar es modificar en la tabla de códigos postales el nombre de una población sin cambiarlo en todos los contratos correspondientes.

Así, si se cambia un nombre de municipio en la tabla Post Code, algo que podría pasar, no afectaría a este informe. Cómo lo veis?


![image](https://user-images.githubusercontent.com/47117960/108352771-9f5d2d80-71e7-11eb-9eca-560180f3df72.png)

**Comment by bpesquero** [comment]
Perfecto. Pasemos entonces un proceso e impongamos la integridad en NAV
Gracias

**Comment by dgarciageo** [comment]
En Atulado es posible que ocurra lo mismo si existen informes similares.

**Comment by JMunoz17** [comment]
Os he mandado los listados de contratos por Excel.

Hemos puesto no editable la población de suministro desde la ficha de contrato.

En la Api está controlado, en las webs antiguas habría que actualizar los datos de las tablas de los códigos postales tanto en Geo como en Hecen, de lo contrario seguirán bajando mal los datos.

Dani, te encargas tu o hablo con Jorge Laguna?

**Comment by dgarciageo** [comment]
@JMunoz17 coméntaselo por favor a @jorgereal. muchas gracias!!

**Comment by JMunoz17** [comment]
Ya tiene Jorge Laguna actualizados los datos en las tablas de códigos postales que se usan en las webs antiguas.

Hemos vuelto a consultar que contratos tienen mal la población de suministro.
Faltarían por revisar los siguientes:

**GEO**
![image](https://user-images.githubusercontent.com/26869276/108727718-27fe0580-7529-11eb-8856-9f5fe3b57692.png)

**HECEN**
![image](https://user-images.githubusercontent.com/26869276/108727834-42d07a00-7529-11eb-8683-38439bbd5a03.png)

**Comment by bpesquero** [comment]
Arreglado todo excepto un contrato de Geo que no tiene CP porque debió ser una prueba o similar.
