### ISSUE TITLE
NAV - link erroneo en historico de acciones OCSUM

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#108]
COM/00060       ES0021000005517261SH0F           AGALINDEZ        Aceptado ATR   Procesado          C2           02           Aceptado                0021      0021      0587      No                                                                                                                                       004         0             0                0             0             0             0                \192.168.100.105\Esios\OCSUM\GAC\Importados\C1\2016\10\C102\GRCW_IBERDROLA DISTRIBUCION_GeoAtlanter, S.L._C2_02_0.xml              17/10/16 15:57  17/10/16 15:57                                 17/10/16                01/01/9999                                        000000006001   03           17/10/16 15:57

**Comment by PKFEric** [comment]
Solucionado, el problema era que el fichero tiene el mismo nombre tanto para un contrato como para otro. Ahora a la hora de dejarlo en la misma carpeta lo versiono para que no se sobreescriba.

**Comment by bpesquero** [comment]
Complicado de probar. Lo doy por ok.
