### ISSUE TITLE
Navision: Cups medidas Oracle

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#11]
Añadir al proceso de carga de medidas de Oracle los CUPS y hacer un proceso de carga de los CUPS en las medidas

**Comment by PKFEric** [comment]
Pendiente de Probar

**Comment by PKFEric** [comment]
He añadido el CUPS tambien a las medidas que vienen del PERFILADO en el proceso de facturacion. Ahora todas las medidas deberian de tener CUPS.

PROBAR

**Comment by bpesquero** [comment]
Probado y ok. EL fichero se carga correctamente en la web de la cnmc

**Comment by PKFEric** [comment]
YUHUU!!
