### ISSUE TITLE
NAV - replicar proceso C2_05 para C2_07

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#111]

**Comment by jorgereal** [comment]
Ya está el desarrollo, no hemos podido realizar todas las pruebas pertinentes dado que el fichero que nos enviaste: 
GRCW_CIA.SEVILLANA ELECTRICIDAD, S.A._GEOATLANTER_C2_07_ES0031103114862025FG0F_0.xml
no era un 07 realmente, era un 05, ¿podrías mandarnos un 07?

**Comment by PKFEric** [comment]
Ya esta cargado para el contrato COM/00067 y lo he procesado para que rellene la fecha de activación del contrato

**Comment by bpesquero** [comment]
Ok. Comprobado
