### ISSUE TITLE
NAV - Problema al liquidar documentos

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#1132]
Damaris tiene problemas al liquidar movimientos. 

Pudo hacer la primera liquidación, pero al intentar liquidar este (F11) le da el siguiente fallo:

![image](https://user-images.githubusercontent.com/47117960/113559531-d8b7f400-9601-11eb-93d0-d92d86ef574e.png)

**Comment by JMunoz17** [comment]
Tiene instalada la dll de envío de mails?
He estado revisando y creo que es la única que se usa en ese proceso.
Prueba a instalársela, cerrar, abrir y volver a lanzar el proceso.

**Comment by bpesquero** [comment]
ok. Gracias
