### ISSUE TITLE
Control potencia facturada venta

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#117]
En el control de potencia facturada en venta = potencia facturada peaje en F1 (toll measures) localizar en la tabla de toll measures por el Nº factura de proveedor
Además, poner un campo en la ficha de contrato que sea "permitir dif potencia peaje vs potencia suministro". En caso de que este marcado, el control no devolverá un error, sino que escribirá directamente en el log y continuará con la generación de la factura.

**Comment by jorgereal** [comment]
SUBIDO -> PROBAR

**Comment by PKFEric** [comment]
FALTA ESCRIBIR EN EL LOG

**Comment by jorgereal** [comment]
SUBIDO
