### ISSUE TITLE
NAV - nombre ficheros intercambio OCSUM

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#118]
Iberdrola emite todos los ficheros con el mismo nombre, indicando únicamente proceso y paso. Al cargar en NAV da problemas. Tenemos que ir cambiando el nombre manualmente. Se me ocurre, en el proceso de carga desde NAV, antes de cargar el fichero, abrirlo, leer el CUPS y añadírselo al nombre de forma automática.

**Comment by PKFEric** [comment]
HECHO PROBAR. Ya lo he probado yo con el fichero C2 02 que habia para el contrato COM/00086

**Comment by bpesquero** [comment]
Probado y ok
