### ISSUE TITLE
Pb con dirección contrato

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#119]
El contrato COM/00091 está en Web Created, al cliente no le ha llegado el mail de confirmación. Del viernes hay muchos emails de Próxima con  Error referentes a este contrato como este :
 
Excepcion controlada web: No existen direcciones de envio para este clienteCL00191 STACK-> en WebDefinitivaGeoatlanter.clsNavision.rellenaClientePorCustomerCodeNav(clsCliente& cliente) 04/11/2016 8:31:49
 
Sin embargo, en su ficha sí que tiene dirección de envío asociada.

**Comment by PKFEric** [comment]
MODIFICADO TESTEADO Y ARREGLADO
