### ISSUE TITLE
problema hueco de facturación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#120]
Al lanzar la facturación desde GeoAtlanter, hay dos contratos que dan hueco de facturación. En realidad no existe hueco, es la primera factura. Lo único que se nos ocurre es que ambos tienen una factura previa registrada de derechos de enganche.

ES0021000005517261SH
ES0021000006043533NG

**Comment by PKFEric** [comment]
Ya esta solucionado y las dos facturas estan en Pre Venta
