### ISSUE TITLE
Informes OCSUM

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#128]

**Comment by jorgereal** [comment]
Corregidos y subidos -> PROBAR

**Comment by bpesquero** [comment]
Hemos probado con el informe de GAC y HECEN de octubre de 2016 y hemos encontrado algunas cosas. Para poder analizar exactamente que es lo que pasa sería muy interesante que nos indicarías para cada informe que fecha es la que estáis teniendo en cuenta:

-pendientes de aceptación: aparecen solicitudes que no deberían aparecer porque parece que está cogiendo algunas solicitudes que no tienen paso 2 y tenemos directamente el 5. 
-pendientes de activación: el de HECEN sale vacío y debería aparecer la solicitud correspondiente al CUPS ES0306000000350517ZL0F. Depende por supuesto, de qué fecha se esté considerando, como decía más arriba, de ahí la importancia de que nos enviéis un breve documento con ese detalles.

**Comment by bpesquero** [comment]
Está todo ok excepto que la provincia sale en algunos casos sin rellenar. (Mail de Ainhoa)

**Comment by jorgereal** [comment]
Se ha corregido el error de la provincia sin rellenar para los informes de sol. realizadas, aceptadas y activadas.

**Comment by bpesquero** [comment]
Comprobado y ok
