### ISSUE TITLE
TASK - Permitir cambiar el campo del DNI en NAV

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#1285]
Permitir en NAV que se puedan meter DNIs extranjeros y números de pasaporte a clientes.

**Comment by JMunoz17** [comment]
Hemos estado revisando la funcionalidad y no deberíais tener ningún problema para validar cualquier NIF en los clientes, con independencia del país de origen.

Lo importante es que indiquéis de forma correcta el código de país en el cliente (ES, IT, FR...)
Seguramente os daba error porque teníais informado el código país ES.

Además, podéis configurar restricciones para el formato del NIF de cada país.

Desde el listado de países:
![image](https://user-images.githubusercontent.com/26869276/139866652-820ead02-cae9-4af3-b686-7845e335a1d3.png)

Teniendo seleccionado el país, abajo a la derecha:
![image](https://user-images.githubusercontent.com/26869276/139866694-4c06200b-68f9-4077-9c3e-c06875cc1005.png)

Ejemplo de España:
almohadilla -> Letras
arroba -> Números
![image](https://user-images.githubusercontent.com/26869276/139866737-02382b20-53cb-44fd-9e88-2f6362cac9b6.png)

**Importante:
Si por ejemplo vais a meter un NIF para Italia, no pongáis IT+número, si no que solo tenéis que poner el número e informar en el código de país IT.
De lo contrario, tendríais problemas con el modelo 349.**

Cualquier duda me decís.

**Comment by dgarciageo** [comment]
Estupendo @JMunoz17 , lo probamos y te decimos, 
muchísimas gracias.
