### ISSUE TITLE
NAV-GAC-autoconsumo al 10%

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1290]
Para controlar la cuota de financiación de los proyectos de autoconsumo ofertados al 10% necesitaríamos

1.- Identificar en la ficha de autoconsumo lo que tiene iva reducido. TEnemos dos opciones, la primera es añadir un campo si/no que se llame IVA reducido y otra es traer el campo de grupo iva de producto que ya tenemos en pre de cara al módulo de proyectos

2.- AL hacer una factura de suminsitros que tenga marcado el check de iva reducido y si tiene algoritmo de facturación SF/NF sacar un aviso de "Cambiar tipo de IVA en cuota de financiación"

**Comment by JMunoz17** [comment]
En las que tienen algoritmo F habría que hacerlo?

**Comment by bpesquero** [comment]
Creo que ya no tenemos ninguna, pero si

**Comment by JMunoz17** [comment]
Lo tengo programado y subido a Producción.
Tenéis algún caso identificado? Para marcar el check en el contrato de ACSM y probar que salga el aviso correctamente.

**Comment by JMunoz17** [comment]
Pendiente revisar Belén.
