### ISSUE TITLE
pb cargas medidas F5D

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#131]
AL cargar los ficheros F5D sólo se carga el primer registro para cada CUPS. Ha pasado tanto con HECEN como con Geo. 
En algunos casos escribe en el log, pero en otros no. Cuando escribe dice : "El CUPS ES0021000010991510EZ   no tiene los registros necesarios."

Los ficheros cargados los teneis en 

\\ni\Esios\F5DCCH HECEN\Procesados
y
\\ni\Esios\F5DCCH Geo\Procesados

con fecha de hoy.

**Comment by jorgereal** [comment]
Arreglado.
He importado correctamente el fichero F5D_0031_0587_20161118.0
Ya se pueden volver a procesar el resto.

**Comment by bpesquero** [comment]
Se cargan las medidas correctamente, pero sigue saliendo el mismo error en el log. 
 
Ruta fichero	CUPS	Error/Aviso	Fecha-Hora
F5D_0021_0587_20161116.0	ES0021000010991510EZ  	El CUPS ES0021000010991510EZ   no tiene los registros necesarios.	21/11/2016 
F5D_0021_0587_20161116.0	ES0021000011248364NG  	El CUPS ES0021000011248364NG   no tiene los registros necesarios.	21/11/2016
F5D_0021_0587_20161117.0	ES0021000005279551FJ  	El CUPS ES0021000005279551FJ   no tiene los registros necesarios.	21/11/2016

**Comment by jorgereal** [comment]
El error del log se daba al importar el fichero sin haber eliminado la línea que se registró la primera vez que se procesó.
No se debería producir en sucesivas importaciones.
