### ISSUE TITLE
NAV-GAC-Abonos calidad de suministro

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1323]
TEnemos dos facturas N negativas, se ha generado un abono negativo en compra y en venta no se genera nada.
<html>
<body>
<div ccp_infra_version='3' ccp_infra_timestamp='1638272268298' ccp_infra_user_hash='4145170661' ccp_infra_copy_id='818052df-937b-4cc2-894b-bf85d3a0fd5a' data-ccp-timestamp='1638272268298'><html>

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<style>
table
	{mso-displayed-decimal-separator:"\,";
	mso-displayed-thousand-separator:"\.";}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
td
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	text-align:general;
	vertical-align:bottom;
	border:none;
	white-space:nowrap;
	mso-rotate:0;}
</style>
</head>

<body link="#0563C1" vlink="#954F72">

COM/09914 | ES0021000012311272HJ | Abono 03211109080000888
-- | -- | --
COM/09915 | ES0021000019937772ZN | Abono 03211109080001132

</body>

</html>
</div>
</body>
</html>

**Comment by JMunoz17** [comment]
Por qué vienen con el check de otras facturas marcado?
Entiendo que deberían ser facturas normales.
Todos los registros anteriores (no hay de BOMP), con el concepto 17, son facturas normales.
Aqui, al ser de Otras Facturas (derechos de enganche, etc.. ), hace la compra y bloquea la venta.

Mi sensación es que el problema es al cargar el xml en Bomp. No puedo certificarlo porque no he conseguido acceder al xml de la factura desde Informes Bomp.

**Comment by bpesquero** [comment]
Y cómo podemos solucionarlo, se te ocurre algo?
Gracias

**Comment by JMunoz17** [comment]
He podido acceder al xml, pone que es de Otras Facturas, por lo que está bien cargado.
Así que tu me dirás como quieres que lo solucionemos.
Ahora mismo, para una factura de Otras Facturas si es abono generamos compra y bloquemos el peaje, para no generar venta.
Podemos excluir los Concept Type = 17.
Pero no sé si es correcto que este concepto venga como Otras Facturas.

**Comment by JMunoz17** [comment]
Estas dos las he desbloqueado a mano y he generado los abonos de venta.
Las tenéis abiertas en los contratos:
COM/09914
COM/09915

**Comment by JMunoz17** [comment]
Como no veo mucha mas opción que lo propuesto anteriormente, lo he implementado y subido a PRE y PROD.
Si te chirria me dices y lo deshacemos en un momento.

**Comment by bpesquero** [comment]
Perfecto

**Comment by bpesquero** [comment]
Jaime, las ventas están ok, sin embargo en compra hace un abono negativo. El xml que nos envían es una N negativa, que habría que transformar en un abono positivo.
Lo hemos cambiado a mano para no dejarlo parado, pero habría que mirarlo porque por estas fechas no suelen enviar estas facturas.
Gracias

**Comment by JMunoz17** [comment]
La compra no la revisé, pensé que estaba bien. Que datos habéis cambiado a mano?
Y ese xml es correcto? Porque según lo que vi el otro día es la primera vez que tenemos el concepto '17' en una N negativa.
Siempre ha venido como Otras Facturas.
No sé a estas alturas hasta que punto nos interesa contemplarlo y añadir una casuística especial, tu me dirás.

**Comment by bpesquero** [comment]
Jaime, el 17 es correcto, es abono por calidad de sumisitro
Lo que hemos hecho a mano es quitarle "el signo menos". Estas facturas tienen una única línea
El concepto 17 es correcto, de hecho, el incorrecot sería el de "Otros"
Podemos dejarlo así y si aparecen de forma masiva lo hacemos. te parece?

**Comment by JMunoz17** [comment]
Ok, me parece bien.
A lo que me refería con el código de concepto es que hasta ahora siempre había venido en OtrasFacturas (tipo derechos de enganche), nunca en una factura normal.

**Comment by JMunoz17** [comment]
Revisar si ya se gestionan en FACT y si no poner un aviso al generar la compra.
