### ISSUE TITLE
Generación de efectos ACSM

### ISSUE THREAD

**Issue by JMunoz17** [PKFEric/webProxima#1325]
En vez de generar los efectos al registrar el pedido, generarlos desde un botón.

**Comment by JMunoz17** [comment]
Poner mensaje de confirmación en caso de que se registre el pedido y no se hayan generado los efectos previamente.
Registro automático.

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

Belén, importante que lo lea quien se encargue de esto. Si algo no les queda claro pueden trastear en PRE y me pueden llamar para comentarme cualquier tema.

Hemos deshabilitado la generación de efectos de ACSM en el registro de las recepciones de compra.
Tenéis un nuevo botón en la ficha de los pedidos de compra, en el botón de Acciones, "Generar efectos ACSM" (el segundo empezando por arriba).

Cuando lancéis el proceso desde aquí se tendrán en cuenta los importes pendientes de todas las líneas del pedido.
Una vez se registre el diario (será automático en el proceso), se marcará un nuevo check en el pedido, "Efectos ACSM generados". 

Si volvéis a lanzar el proceso y este campo ya está marcado, se os pedirá confirmación. Además, en este caso, no se registrará automáticamente, si no que se generará el diario y tendréis que registrarlo manualmente (previamente será necesario que modifiquéis el nº de documento en dicho diario, porque antes usábamos el nº de albarán como nº de documento, pero ahora usaremos el nº de pedido en el primer registro automático y luego será necesario que lo modifiquéis en cada registro).

Si tratáis de registrar el pedido y este campo no está marcado, se os pedirá confirmación.
El proceso se puede lanzar tantas veces como queráis, siempre cogerá los importes pendientes (Ojo, los importes no dejan de estar pendientes por lanzar este proceso).

Recordaros que cuando creamos los pedidos de ACSM, los criterios de agrupación de las líneas procedentes del PA son los siguientes: Proveedor, Fecha (el día actual) y si genera efectos o no. 

Es decir, si a las 10 de la mañana traéis líneas del PA y se crea un pedido, a las 12 lanzáis este procesito para ese pedido y a las 14 volvéis a traer líneas del PA, se puede dar la circunstancia de que estás líneas se agrupen en el mismo pedido y que esté ya tenga marcado el campo de "Efectos ACSM generados"). Lo cual significa que tendríais que registrar parcialmente el pedido para tener solo pendientes los importes correspondientes a estas nuevas líneas y volver a lanzar el proceso (en ningún momento se os va a alertar de esta circunstancia).

Yo entiendo que esta caso no se va a dar (ya que implica lanzar el PA dos veces en el mismo día, que haya líneas pendientes del mismo proveedor en ambas ejecuciones y que entre medias hayáis lanzado el proceso de generación de efectos) pero no sé si queréis que tratemos de controlarlo de alguna forma.

No sé si me he explicado muy bien, si no me dais un toque y lo comentamos.

**Comment by JMunoz17** [comment]
Modificar el proceso para no agrupar líneas de distintas importaciones en el mismo pedido.

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

**Comment by bpesquero** [comment]
Aclaración: en el caso de que el grupo registro producto es SERV RECI se hacen dos efectos.
El primero de ellos lleva el % configurado en configuración de compras, y el segundo el 100% - primer efecto. Actualmente el primer efecto es un 30%
La fecha en que se genera el segundo efecto es una fecha alejada en el tiempo. Cuando llega el momento de hacer el pago hay que cambiar la fecha de vencimiento del efecto. La fecha para la que se genera aparece también en configuración de compras (Fecha Vto. Fin de Obra)
