### ISSUE TITLE
API-Modificación del modelo 560

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1333]
Se ha modificado el modelo 560. Se obtendrán dos ficheros, uno con la información de la liquidación y otro con el desglose de exenciones y reduccicones

<html>
<body>
<div data-pm-slice="1 1 []" data-en-clipboard="true"><b>Liquidación</b></div><div><br></div><div>(1)-Base imponible: será&nbsp; la suma de la base imponible de las facturas a las que no  se les haya aplicado el límite mínimo de ISE (0,5 o 1 €/MWh). Para calcularlo se tomará el campo [importe línea] de  las líneas de las factruras con energy=true a las que no se les haya aplicado el límite de ISE siempre que las líneas cumplan las siguientes condiciones:</div><div><br></div><div style="padding-left:80px;">margen=false</div><div style="padding-left:80px;">gestion de la medida=false</div><div style="padding-left:80px;">impuesto de electricidad=false</div><div style="padding-left:80px;">energia excedentaria=false</div><div style="padding-left:80px;">otros conceptos=false</div><div style="padding-left:80px;">factura no electronica=false</div><div style="padding-left:80px;">campaña=false</div><div style="padding-left:80px;">gestion de excedentes=false</div><div style="padding-left:80px;">renting (amortización)=false</div><div style="padding-left:80px;">renting (intereses)=false</div><div style="padding-left:80px;">descuento renting=false</div><div style="padding-left:80px;">mantenimiento=false</div><div style="padding-left:80px;">seguro=false</div><div style="padding-left:40px;"><br></div><div style="padding-left:40px;">No es necesario desglosar por ISE RED(0,5% o ISE estándar (5,11%)</div><div style="padding-left:40px;"><br></div><div>(2)-Base liquidable: será la suma de la base liquidable de todos los movimientos obtenidas de los movimientos de retención sumando el campo [base retención] de las facturas seleccionadas en el punto (1)</div><div>(3)-Cuota integra: será la suma del campo [importe retencion] de los movimientos de retención de las facturas seleccionadas en el punto (1)</div><div>(4)-Cantidad: para las facturas a las que se ha aplicado el limite mínimo (<span style="font-size: 16px;">NAV-FActuración ISE - RDL 17/2021#1281)&nbsp; se sumará el campo cantidad de las líneas con [termino de energia]=true</span></div><div><span style="font-size: 16px;">(5)-Cuota íntegra mínima: cantidad por límite mínimo (NAV-FActuración ISE - RDL 17/2021#1281).  Se calculará con el campo [importe retencion] de los movimientos de retención de las facturas a las que se aplica el límite.</span></div><div><span style="font-size: 16px;">(6)-Cuota a ingresar: cuota íntegra + íntegra mínima (3)+(5)</span></div><div><span style="font-size: 16px;"><span data-markholder="true"></span></span></div><div><span style="font-size: 16px;">NOTA: En los puntos (1), (2) y (3) es necesario excluir las facturas que no llegaban el mínimo de importe de ISE y por tanto les han aplicado los límites de 0,5 y 1 €/MWh. Sin embargo, en los puntos (4) y (5) sólo se tendrán en cuenta estas facturas a las que se les ha aplicado el límite.</span></div><div><br></div><div><b>Desglose de cuotas</b></div><div><span style="font-size: 16px;"><span data-markholder="true"></span></span></div><div><span style="font-size: 16px;">Para aquellas facturas cuyos contratos tengan marcado un calor distinto de cero en el campo [contract extension].[regimen fiscal]  hay que hacer un desglose a nivel de NIF con la siguiente información</span></div><div><span style="font-size: 16px;"><span data-markholder="true"></span></span></div>

DESGLOSE DE CUOTAS | CIE | Base imponible | Reducción | Base liquidable | Cantidad | Destinatario NIF | Destinatario CIE | Tensión | Concepto |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Exento artículo 94.1 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | NO | NO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.1 (Relaciones diplomáticas)
Exento artículo 94.2 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | NO | NO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.2 (Organizaciones internacionales)
Exento artículo 94.3 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | NO | NO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.3 (Fuerzas armadas)
Exento artículo 94.4 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | NO | NO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.4 (Acuerdos países terceros)
Exento artículo 94.5 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | SÍ | LO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.5 (Titulares de instalaciones<50 MW)
Exento artículo 94.6 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | SÍ | LP | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.6 (Pilas de combustible)
Exento artículo 94.7 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | SÍ | L1 o L7 | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.7 (Instalaciones de generación)
Exento artículo 94.8 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | SÍ | NO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.8 (Embarcaciones)
Exento artículo 94.9 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | SÍ | NO | NO | SI O NO |   |  
Con reducción art. 98.1a) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LQ | NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1a) (Reducción química y procesos electrolíticos)
Con reducción art. 98.1b) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LM | NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1b) (Procesos mineralógicos)
Con reducción art. 98.1c) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LE | NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1c) (Procesos metalúrgicos)
Con reducción art. 98.1d) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LI | NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1d) (Industrica coste eléctrico>50%)
Con reducción art. 98.1e) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LA | SI O NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1e) (Riesgos agrícolas)
Con reducción art. 98.1f) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LV | SI O NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1f) (Industrica coste elétrico>5% valor de producción)
Con reducción art. 98.2 LIE | SI O NO | SÍ | 100% Base Imponible | 0 euros | SÍ | SÍ | NO | NO | SI O NO | No contemplado en NAV | LIE-Reducción 100%: 98.2) (Embarcaciones no privadas de recreo)
Con reducción art. 98.3 LIE | SI O NO | SÍ | 100% Base Imponible | 0 euros | SÍ | SÍ | NO | NO | SI O NO | No contemplado en NAV | LIE-Reducción 100%: 98.3) (Transporte de ferrocarril)

</body>
</html>

**Comment by jorgereal** [comment]
Belén creo que no se copió el texto completo de la nota, falta el detalle del punto 94.9 del desglose.

¿Queréis que saque una línea de cabecera tanto en el fichero de liquidación como en el de desglose?
Según la documentación cuando se envíe el fichero de desglose debe ir sin cabecera, pero creo que os sería útil para comprobar los datos.

**Comment by bpesquero** [comment]
<html>
<body>
<div data-pm-slice="0 0 []" data-en-clipboard="true"><b>NOTA- Facturas con valoración de excedentes y compensación simplificada.</b> En estos casos la línea de valoración de excedentes está exenta de ISE. Por este motivo, las líneas de facturas con energia excedentaria=true no se han tenido en cuenta.&nbsp; DE esta forma el campo base imponible no deducirá la valoración de excedentes, sin embargo, el campo base liquidable si lo hará al&nbsp; tomar el valor de los movimientos de retención. La diferencia entre base imponible y base liquidable tendrá que quedar reflejada en el desglose, por ello hay que incluir en el desglose balo el epígrafe LIE-Exención: 94.9. Las facturas a tener en cuenta son aquellas que tengan línea con [energia excedentaria]=true e [importe de línea]&lt;&gt;0</div><div><br></div>

Exento artículo 94.9 LIE | CIE de info empresa | BI-se calcula tomando el campo [importe línea] de la línea de excedentes | Vacío | 100% Base imponible | Cantidad: campo [cantidad] de la línea de excedentes | NIF | Vacío | Vacío | Vacío
-- | -- | -- | -- | -- | -- | -- | -- | -- | --



</body>
</html>

**Comment by jorgereal** [comment]
Apuntes:
-Solo incluir en la base imponible el importe de las facturas con movimiento de retención.
-Para el cálculo de la base imponible tomar todas las líneas anteriores a la línea de IE.

**Comment by bpesquero** [comment]
En la línea del comentario anterior, la definición del punto (1) Base imponible queda como sigue:

(1)-Base imponible: será  la suma de la base imponible de las facturas a las que no  se les haya aplicado el límite mínimo de ISE (0,5 o 1 €/MWh). Para calcularlo  se seleccionarán las facturas con energy=true, que generen movimiento de retención, y se se tomará el campo [importe línea] de  las líneas de las factura con nº línea <nº línea de la línea correspondiente a ISE, es decir, de la línea con impuesto de electricidad=true

**Comment by bpesquero** [comment]
Finalmente se vuelve a cambiar el cálculo del punto (1) se hace como sigue

(1)-Base imponible: será  la suma de la base imponible de las facturas a las que no  se les haya aplicado el límite mínimo de ISE (0,5 o 1 €/MWh). Para calcularlo  se seleccionarán las facturas con energy=true, que generen movimiento de retención, y se se tomará el campo [importe línea] de  las líneas de las factura cuyo concepto no sea 

-  Gestión de la medida
- Margen
- Otros conceptos
- Factura no electrónica
-  Campaña
- Gestión excedentes
- Renting (amortización)
- Renting (intereses)
-  Descuento renting
- Mantenimiento
-  Seguro
- Energía excedentaria
- Impuesto eléctrico
- Bateria virtual

**Comment by jorgereal** [comment]
Definición modelo 560 con las últimas correcciones:

Se generarán 3 ficheros (uno de ellos meramente informativo para cuadrar datos):

**Liquidación**: incluirá dos líneas con los siguientes campos:

(1) Base imponible: será la suma de la base imponible de las facturas a las que no se les haya aplicado el límite mínimo de ISE (0,5 o 1 €/MWh). Para calcularlo se seleccionarán las facturas con energy=true, con línea de impuesto eléctrico o sin ella pero con el check ExentoImpuestoElectrico = true, y se se tomará el campo [importe línea] de las líneas de las factura cuyo concepto no sea

- Gestión de la medida
- Margen
- Otros conceptos
- Factura no electrónica
- Campaña
- Gestión excedentes
- Renting (amortización)
- Renting (intereses)
- Descuento renting
- Mantenimiento
- Seguro
- Energía excedentaria
- Impuesto eléctrico
- Bateria virtual


(2)-Base liquidable: será la suma de la base liquidable de todos los movimientos de retención, sumando el campo [base retención] de los documentos seleccionados en el punto (1).
(3)-Cuota integra: será la suma del campo [importe retención] de los movimientos de retención de las facturas seleccionadas en el punto (1)
(4)-Cantidad: para los documentos a los que se ha aplicado el limite mínimo (NAV-FActuración ISE - RDL 17/2021#1281)  se sumará el campo cantidad de las líneas con [termino de energia]=true
(5)-Cuota íntegra mínima: cantidad por límite mínimo (NAV-FActuración ISE - RDL 17/2021#1281). Se calculará con el campo [importe retención] de los movimientos de retención de los documentos a los que se aplica el límite.
(6)-Cuota a ingresar: cuota íntegra + íntegra mínima (3)+(5)
NOTA: En los puntos (1), (2) y (3) es necesario excluir los documentos que no llegaban el mínimo de importe de ISE y por tanto les han aplicado los límites de 0,5 y 1 €/MWh. Sin embargo, en los puntos (4) y (5) sólo se tendrán en cuenta estas facturas a las que se les ha aplicado el límite.

La segunda línea será similar a la primera, con la única diferencia de que en ésta se excluyen los abonos que se habían identificado como que no se les había aplicado límite mínimo ISE pero su línea de impuesto eléctrico tiene una clave de percepción distinta a C_ISE_R10B|C_ISE_REDB|C_ISE10B|C_ISEB. En principio estos casos serían los de abonos que corrigen facturas anteriores a la subida del desarrollo del límite mínimo ISE.

**Desglose liquidación**:
Desglose de los distintos documentos con los que se hace el cálculo de los campos (1), (2) y (3) del fichero anterior. Vendrán informados en este mismo orden los siguientes valores: Tipo documento, Nº Documento, Base imponible, Base liquidable, Cuota integra.
Este fichero sirve para localizar descuadres.

**Desglose de cuotas**:
Para aquellos documentos cuyos contratos tengan marcado un valor distinto de cero en el campo [contract extension].[regimen fiscal] hay que hacer un desglose a nivel de NIF con la siguiente información:

DESGLOSE DE CUOTAS | CIE | Base imponible | Reducción | Base liquidable | Cantidad | Destinatario NIF | Destinatario CIE | Tensión | Concepto |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Exento artículo 94.1 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | NO | NO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.1 (Relaciones diplomáticas)
Exento artículo 94.2 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | NO | NO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.2 (Organizaciones internacionales)
Exento artículo 94.3 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | NO | NO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.3 (Fuerzas armadas)
Exento artículo 94.4 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | NO | NO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.4 (Acuerdos países terceros)
Exento artículo 94.5 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | SÍ | LO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.5 (Titulares de instalaciones<50 MW)
Exento artículo 94.6 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | SÍ | LP | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.6 (Pilas de combustible)
Exento artículo 94.7 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | SÍ | L1 o L7 | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.7 (Instalaciones de generación)
Exento artículo 94.8 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | SÍ | NO | NO | SI O NO | Contrato marcado exención impuesto eléctrico | LIE-Exención: 94.8 (Embarcaciones)
Exento artículo 94.9 LIE | SI O NO | SÍ | NO | 100% Base imponible | SÍ | SÍ | NO | NO | SI O NO |   |  
Con reducción art. 98.1a) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LQ | NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1a) (Reducción química y procesos electrolíticos)
Con reducción art. 98.1b) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LM | NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1b) (Procesos mineralógicos)
Con reducción art. 98.1c) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LE | NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1c) (Procesos metalúrgicos)
Con reducción art. 98.1d) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LI | NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1d) (Industrica coste eléctrico>50%)
Con reducción art. 98.1e) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LA | SI O NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1e) (Riesgos agrícolas)
Con reducción art. 98.1f) LIE | SI O NO | SÍ | 85% Base imponible | 15% Base imponible | SÍ | SÍ | LV | SI O NO | SI O NO | Contrato marcado con reducción impuesto eléctrico | LIE-Reducción 85%: 98.1f) (Industrica coste elétrico>5% valor de producción)
Con reducción art. 98.2 LIE | SI O NO | SÍ | 100% Base Imponible | 0 euros | SÍ | SÍ | NO | NO | SI O NO | No contemplado en NAV | LIE-Reducción 100%: 98.2) (Embarcaciones no privadas de recreo)
Con reducción art. 98.3 LIE | SI O NO | SÍ | 100% Base Imponible | 0 euros | SÍ | SÍ | NO | NO | SI O NO | No contemplado en NAV | LIE-Reducción 100%: 98.3) (Transporte de ferrocarril)

Se tendrán en cuenta aquellos documentos sin línea de IE si el contrato tiene marcado el check ExentoImpuestoElectrico o aquellos documentos con línea de impuesto eléctrico si la clave de percepción de la misma es C_ISE_R10|C_ISE_R10B|C_ISE_RED|C_ISE_REDB.

Para el tipo 94.9 se mirarán aquellos documentos de autoconsumo, de contratos con CodContratoAutoconsumo distinto de vacío y se sumará el importe de las líneas marcadas con el check EnergiaExcedentaria.

**Comment by jorgereal** [comment]
Se ha añadido el filtro de "Facturación Externa" = false en la obtención de las facturas y abonos antes de la realización de los cálculos.

Subido a PRO

**Comment by bpesquero** [comment]
Vamos a quitar de manera temporal el filtro de FActuracion externa=false. Los datos de ISE se guardan en FACT desde 8 de marzo, por tanto las declaraciones de febrero y marzo habrá que hacerlas con la información de NAV. A partir de ese momento volvemos a habilitar el filtro.
