### ISSUE TITLE
Revisar proceso de liquidación automática

### ISSUE THREAD

**Issue by JMunoz17** [PKFEric/webProxima#1337]
Revisar todas las casuísticas.

**Comment by bpesquero** [comment]
En el proceso de liqiudación habría que tener en cuenta el campo de situación de recobro. 
Pendiente justificante de pago --> no liquidar
Pendiente (--> liquidar
Gestionado --> liquidar
No gestionar --> no liquidar
Gestión externa--> liquidar
Vencido--> liquidar
Moroso baja unliateral--> liquidar

**Comment by JMunoz17** [comment]
Cambios realizados:
Aplicar a todas las liquidaciones los filtros que indiquéis al ejecutar el proceso
Permitir elegir los criterios que se van a aplicar al buscar con que documentos liquidar.
Añadir filtro por situación recobro indicado en el comentario de arriba.

Subido a PRE y PROD.
