### ISSUE TITLE
NAV-GAC- gestión de impagos-reclamación formal de deuda 

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1346]
En los emails de reclamación formal de deuda, para menos de 10 kW persona física o para más de 10 kW persona física o persona jurídica, se está informando sólo la factura sobre la que se envía el email. Realmente esto no es así, es raro porque funcionaba correctamente históricamente y se recogían en ese email el importe de toda la deuda pendiente y se numeraban las fechas de todas las facturas.

**Comment by JMunoz17** [comment]
Geo o Hecen?

**Comment by JMunoz17** [comment]
Si estamos hablando de GEO, que supongo que si, para la reclamación formal de deuda no esta implementado el envío agrupado.

Para resolución de contrato en GEO si que se hizo hace poco, puedes ver los detalles en esta tarea: https://github.com/PKFEric/webProxima/issues/1310

Es importante distinguir entre GEO y HECEN porque en HECEN se hicieron muchísimas modificaciones que no se hicieron para GEO, por lo que tenéis que tener en cuenta que funcionan de forma diferente.

**Comment by bpesquero** [comment]
Si, es Geo. Siempre trato de ponerlo en el nombre de la incidencia

**Comment by JMunoz17** [comment]
Pues no lo tenemos implementado Belén, vamos que es normal que no agrupe.. habría que hacerlo si queréis.

**Comment by bpesquero** [comment]
Llevaría mucho tiempo?

**Comment by JMunoz17** [comment]
Tenemos que modificar los formatos de los mails, los procesos correspondientes a los botones de marcar y enviar, y hacer las pruebas.
Calculo que unas 4 horas.

El de impagos de Geo que se envía automáticamente cuando nos viene una devolución tampoco agrupa, si hay que hacer ese también serían 2-3 horas más.

**Comment by bpesquero** [comment]
ok. Adelante, En el de devolución no hay que hacerlo.
gRacias

**Comment by JMunoz17** [comment]
Subido a PRE. 
Información en la tarea #1349

**Comment by JMunoz17** [comment]
Subido a PROD. Cerrad y volver a abrir NAV para los cambios.
