### ISSUE TITLE
NAV-GAC-IVA reducido en ficha de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1347]
Quería saber si este campo se está utilizando para algo o actualmente sólo se usa el campo de  grupo registro iva producto

**Comment by JMunoz17** [comment]
Se usa para esta tarea que tenéis pendiente de probar: https://github.com/PKFEric/webProxima/issues/1290

**Comment by bpesquero** [comment]
Teníamos dos opciones hacerlo con el check o con el campo de grupo registro iva producto. como ya tenemos este dato, sería mejor, no?
En cualquier caso, en cuanto dejemos de facturar por NAV ya no lo necesitaríamos para nada, verdad?
Gracias

**Comment by JMunoz17** [comment]
Se podría cambiar, lo hicimos así porque en ese momento no lo teníamos.
Efectivamente, cuando se facture por fuera no se usará.
