### ISSUE TITLE
Gestión de cobros - Situación de recobro

### ISSUE THREAD

**Issue by JMunoz17** [PKFEric/webProxima#1349]
Crear dos valores nuevos para el campo de situación de recobro que sean "Pendiente con justificante de pago" y "Moroso-baja unilateral".

Calculo fecha de corte:
_Perdona que no me he explicado, la fecha de devolución del aviso 2 no es relevante, lo que dice la norma es que una vez que mandas el segundo aviso empiezan a contar los plazos, ya no es necesario que reciba ni que te lo devuelva. El cálculo se haría en base a la fecha de recepción del aviso 1 o a la fecha de envío del aviso 2._

**Comment by JMunoz17** [comment]
Subido a PRE.

Tanto esta tarea como la #1346 

Si lo vais a probar en PRE avísame y os configuro el email con el que queráis hacer las pruebas y el SMTP.
Si no, lo subimos a Producción el lunes a primera hora si te parece.

**Comment by bpesquero** [comment]
Subimos a PRO ambas

**Comment by JMunoz17** [comment]
Lunes 08:30 la subida, ok?

**Comment by JMunoz17** [comment]
Subido a PROD. Cerrad y volver a abrir NAV para los cambios.
