### ISSUE TITLE
NAV-FAC-Nuevo campo "no registrar automaticamente"

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1350]
Necesitamos un campo nuevo en la ficha de contrato que sea un booleano "no registrar automaticamente" que usaremos desde FAC

**Comment by JMunoz17** [comment]
Subido a PRE y PROD. salir y entrar para que se actualicen los cambios.

Nombre del campo: "Not Automatic Post" en la tabla Contract Extension
