### ISSUE TITLE
NAV-GAC-HECEN-Gestión de impagados

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1353]

**Comment by bpesquero** [comment]
Añadir (si se puede)

- teléfono de cliente
- FEcha de emisión
- Periodo de consumo

**Comment by JMunoz17** [comment]
**Punto 1**
Revisar que esto se está haciendo bien--> Cuando se haga efectiva la rescisión de contrato C1/C2_06 (activación como comercializadora saliente) , que esté precedido por un B1_02 (fin de contrato) , no debe avisar al cliente de la activación de la baja. 
**Revisado. Lo estamos haciendo bien.**

**Punto 2**
Añadir en la pantalla de gestión de cobros, como variables, sin poder filtrar.
•	Teléfono de cliente
•	Fecha de emisión de la factura
•	Fecha inicio y fin de la factura
**Añadido a la pantalla de gestión de impagos. También hemos limpiado esta pantalla, si queréis que quitemos mas columnas nos decís.**

**Punto 3**
Envío de mails desde pantalla de gestión de cobros.
[MailsGestionCobros.docx](https://github.com/PKFEric/webProxima/files/8160206/MailsGestionCobros.docx)
**Funcionalidad modificada en base a lo definido. 
Tendremos 4 botones, que sirven tanto para Geo como Hecen. La única diferencia es que si lo ejecutas desde Hecen te pide que selecciones un área de reclamación.**

**Punto 4**
Envío de mails al importar devoluciones.
[DevolucionesImpagos.docx](https://github.com/PKFEric/webProxima/files/8160126/DevolucionesImpagos.docx)
**Funcionalidad modificada en base a lo definido.**

**Punto 5**
_Cuerpo y asunto emails:_
[FormatoEmails.docx](https://github.com/PKFEric/webProxima/files/8160024/FormatoEmails.docx)
Hoja 1 -> Email enviado a partir de recibir una devolución.
Hoja 2 -> Reclamación formal de deuda.
Hoja 3 -> Resolución de contrato para no morosos.
Hoja 4 -> Resolución de contratos para morosos.
**Funcionalidad modificada en base a lo definido.**

**Punto 6**<
Calculamos fecha prevista de corte -> 20 días naturales. 
Se calcula al hacer el envío del aviso de baja de unilateral desde la pantalla de gestión de cobros o al importar una devolución.
**Modificado**

**Punto 7**
Mapeo de campos:
FechaEnvioMail                           _Fecha Envio Mail Aviso 1 --->Fecha envío aviso baja unilateral
FechaEnvioMail2                         _Fecha Envio Mail Aviso 2--> Fecha envío recordatorio baja unliateral
FechaEnvioMail20Dias                _Fecha Envio Mail 20 Dias -->Fecha envio mail comunicación amistosa
FechaEnvioMailAvisoImpago      _Fecha Envio Mail Aviso Impago--> Fecha envío email amistoso
FechaPrevistaCorte                      _Fecha Prevista Corte -->Fecha prevista baja
FechaRecepcionAviso1                _Fecha Recepcion Aviso 1 --> Fecha recepción  aviso baja unilateral
FechaRecepcionAviso2                _Fecha Recepcion Aviso 2 -->Fecha recepción recordatorio baja unliateral
Barcode first shipping                 _Código de barras - 1º envío_ 
Barcode second shipping            _Código de barras - 2º envío_ 
FechaDevolucionAviso1               _Fecha 1º Devolución Reclamación formal de deuda_
FechaDevolucionAviso2               _Fecha 2º Devolución Reclamación formal de deuda_ 
Barcode contract resolution        _Código de barras - baja unliateral_ 
FechaDevolucionResContrato     _Fecha Devolución baja unliateral_ 
**Modificado**

**Punto 8**
Se deja de utilizar tanto cartas como la pantalla resumen de Hecen.
**Modificado para que al abrir Hecen no te pregunte si quiere abrir la pantalla de resumen.**

**Punto 9**
Quitar de todos los sitios el filtro "Acuerdo de pago".
**Modificado**

**Punto 10**
Enviar todas las comunicaciones al email configurado en Información de empresa como "Email impagos" excepto la comunicación amistosa al importar la devolución (cuando el cliente tenga email informado, si no lo tiene lo enviamos al Email configurado como "Email impagos"). 
Irá en copia al email configurado como "Email copia" en Información de Empresa. 
Irá en copia oculta al email configurado como "Email copia oculta" en Información de Empresa. 
Se utiliza como remitente el email configurado en "Correo electrónico att. cliente" en Información de empresa.
Se utiliza como nombre del remitente el valor configurado en "Nombre Envío Mails" en Información de empresa.
