### ISSUE TITLE
NAV-Procesar B1_07

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1357]
Al procesar el fichero B1_07, que ya se está haciendo, deberíamos 

- cambiar el estado del contrato a BAja
- rellenar la fecha de fin de facturación del contrato

**Comment by JMunoz17** [comment]
Belén, para el B1 únicamente tenemos implementado el procesamiento del paso 02 y del paso 05.
Del paso 07 nada.

Es el B1 seguro?

**Comment by bpesquero** [comment]
Si, tenemos un montón de B1_07

![image](https://user-images.githubusercontent.com/20299071/157271306-69a753ca-37b7-49f5-98ed-5495e516439e.png)

**Comment by JMunoz17** [comment]
Se cargan pero no hace nada al procesarlos.

**Comment by bpesquero** [comment]
Eso es. Por eso la tarea, para que al procesarlo rellena la fecha fin y cambie el estado.

**Comment by JMunoz17** [comment]
Actualmente, cuando se importa un B1_07, se importa como si fuese un B1_02 rechazado (por lo que no sé si se importan todos los datos que vienen en el xml).
Al procesar, no hace nada, solo marcarlo como procesado.

Para rellenar fecha fin y cambiar el estado tengo las siguientes dudas:
Que fecha utilizo como fecha de fin? Solo tengo "fecha de rechazo". No sé si tendríamos que implementar la lectura del xml B1_07.

En el paso B1_05, envía mail avisando de la baja (solo si viene de un B1_01 con razón de cancelación 01).
En este paso tendríamos que enviar mail? Siempre? O teniendo en cuenta la razón de cancelación?

**Comment by bpesquero** [comment]
La fecha fin deber ser la fecha de rechazo. 
No hay que enviar email con el B1_07

**Comment by JMunoz17** [comment]
Modificado y subido a pre y prod.
Cerrar y abrir NAV para que se apliquen los cambios.

**Comment by bpesquero** [comment]
Probado y ok
