### ISSUE TITLE
NAV-IMU

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1358]
REvisar informe de IMU para cambiar la forma de obtenerlo y que no tenga en cuenta las plantillas de NAV sino los conceptos de las líneas.

**Comment by JMunoz17** [comment]
Belén, necesito que me confirmes desde donde lanzas estos informes, para saber cuales usas, ya que tenemos varios.
En principio solo hay uno que se ha actualizado de 2019 en adelante así que entiendo que es el único que usáis.
Pero hay otro que es para "facturas pagadas". Confírmame si lo usáis.


Filtros:
     - Códigos postales.
     - Contratos.
     - Fecha de registro.

Cálculos:
**Tipo I y Tipo V:**
- Facturas registradas:
  - No Enganche.
  - No Depósito.
  - Venta:
     - Coge los importes de las líneas con nº de línea menor a la línea de impuesto de electricidad en función de la plantilla asociada a ese contrato. Excluye las que tengan tipo vacío y la línea de suplemento territorial.
  - Compras:
     - Busca los cierres asociados a cada factura. De ahí obtiene el nº de factura. Coge los importes de las siguientes líneas:
         - Términos Potencia.
         - Términos Energía.
         - Energía Reactiva
         - Energía Reactiva Inductiva.
         - Recargo por exceso de potencia.
    - Si no encuentra cierres (_Closing Measures_), busca peajes (_Toll Measures_) y hace lo mismo.

- Abonos registrados:
  - Hace lo mismo que para las facturas, tanto venta como compra, pero restando los importes.

**Tipo VI:**
Solo coge la línea de Tasa Municipal, en facturas y abonos de venta. En compra no hace nada.

**Comment by bpesquero** [comment]
Se usan ambos informes.
Lo que estoy viendo es que en todas las facturas que vienen de FACT no tenemos la relación entre la factura de compra y la factura de venta. En cualquier caso, no hay un error en lo que me has mandado? Yo creo que que sólo el tipo I se hace buscando en la compra y en la venta y el tipo V y VI se hace con la línea de tasa municipal de la venta.

**Comment by JMunoz17** [comment]
No, esta hecho tal y como te he pasado.
Cuando quieras comentamos como podemos hacerlo.

**Comment by bpesquero** [comment]
Lo ideal sería excluir las facturas que provienen de FACT del informe, y tratar sólo las facturas de NAV. La información de las facturas realizadas por FACT la obtendremos del propio FACT
Quizá sería bueno dejar el informe actual y duplicarlo, al haber realizado declaraciones obteniendo datos de esta forma es probable que se nos requiera a informar del detalle presentado y si lo eliminamos no tendríamos acceso a ello.

**Comment by JMunoz17** [comment]
Me parece bien la solución que propones.

Tenemos que buscar objetos libres para hacer esto, voy a revisar los reports que están en licencia para ver si hay alguno que no se utilice. Necesitamos 2, uno para esto y otro para un confirming nuevo, según me han comentado desde soporte.

Confirmame Belén que el report del IMU que usais es el 50051 IMU por localidad, o dime donde lo tienes en el menú y lo miro yo.

**Comment by JMunoz17** [comment]
Estos 4 reports no están sacados en el menú y tienen fechas de modificación muy antiguas (2010, 2013..).

Report 50005 Mov banco por centro coste
Report 50006 Ventas - Fact. Mercado mayoris
Report 50008 Purchase - Invoice 2
Report 50009 Abono compra

Salvo que los ejecutéis manualmente, que supongo que no, podemos utilizar esa numeración para licenciar los nuevos procesos.

**Comment by bpesquero** [comment]
Ok, perfecto. 
El que usamos efectivamnete es el de IMU por localidad

**Comment by JMunoz17** [comment]
Ok, confírmame un par de reports cuando puedas.

**Comment by bpesquero** [comment]
Report 50005 Mov banco por centro coste
Report 50006 Ventas - Fact. Mercado mayoris

**Comment by bpesquero** [comment]
Jaime, cambio de planes. Finalmente vamos a sacar los informes de NAV tanto de las facturas de FACT como de las facturas de NAV. La cuestión es que vamos a cambiar la forma de hacerlo. LA idea es considerar todas las facturas de venta y de compra registraras en el periodo considerado en el informe (sin relacionar unas con otras). Los conceptos a tener en cuenta son los que te indico a continuación

La empresa 1 es Geo y la empresa 2 HECEN
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/BPESQU~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/BPESQU~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



1 |  
-- | --
BonoSocial | SI
Campaign | NO
Consumo_mercado | SI
Descuento_Cargos | SI
Descuento_Renting | NO
Diferencias | NO
Energia_Excedentaria | SI
Energía_Reactiva | SI
Energy_Efficiency | SI
Factura_No_Electronica | NO
Gestión_de_la_Medida | NO
Gestion_Excedentes | NO
Impuesto_de_Electricidad | NO
Mantenimiento | NO
Margen | NO
Other_Concepts | NO
Recargo_Por_Exceso_de_Potencia | SI
Renting | NO
Renting_Aux | NO
Seguro | NO
Suplemento_Territorial | SI
Tasa_Municipal | NO
Terminos_Energia | SI
Terminos_Potencia | SI
(en blanco) |  
2 |  
Campaign | NO
Descuento_Cargos | SI
Diferencias | NO
Energía_Reactiva | SI
Gestión_de_la_Medida | NO
Impuesto_de_Electricidad | NO
Other_Concepts | NO
Recargo_Por_Exceso_de_Potencia | SI
Suplemento_Territorial | SI
Terminos_Energia | SI
Terminos_Potencia | SI



</body>

</html>

**Comment by JMunoz17** [comment]
Y esto sería para los tipo V y tipo I no?
Para los tipo VI no cambia no?

**Comment by bpesquero** [comment]
Sería para todos, incluidos los tipo VI.

**Comment by JMunoz17** [comment]
El criterio de los conceptos, igual para venta que para compra?

**Comment by bpesquero** [comment]
Si, eso es.

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
Pendiente de probar.

![image](https://user-images.githubusercontent.com/26869276/157866874-6a1e7933-ce04-4831-89bf-4be00dfe4744.png)
