### ISSUE TITLE
NAV (VBAT) - PASOS C1/C2 (cambio de comercializador)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#1360]
Al procesar un C1/C2 paso 05 de activación, previa importación en el histórico de acciones, identificará si el  nodo <TipoAutoconsumo> es distinto de 00. Si es así, vendrá informado como tipo 41 (compensación simplificada) y, por tanto, tendrá que realizar las siguientes acciones automáticas:

![image](https://user-images.githubusercontent.com/47117960/159695188-c306c903-79df-441b-ab94-9a0e23a75cf2.png)

a. Marcar el check  “autoconsumo” de la pestaña “autoconsumo” del contrato NAV.

![image](https://user-images.githubusercontent.com/47117960/159695274-b8caad86-cca2-491b-bd2f-f79b601ae659.png)

b. Deberá replicar la fecha de activación del cambio de comercializadora, informado en el paso 05 del xml , nodo<DatosActivacion>/Fecha, que también se vuelca sobre el campo del histórico de acciones “Fecha de activación”, y que es además la fecha inicio facturación del contrato en el campo “Fecha inicio vigencia” de la ficha de autoconsumo NAV. 

Ej: Histórico de acciones
![image](https://user-images.githubusercontent.com/47117960/159695723-3675aca8-4c1e-4b33-8a8b-e19af57c05e1.png)

Ej. Fichero paso 05 
![image](https://user-images.githubusercontent.com/47117960/159695753-2398a43b-2b81-425f-92c8-d0b9447a854a.png)

Ej. Ficha autoconsumo NAV 
![image](https://user-images.githubusercontent.com/47117960/159695785-fcbceb86-a2a7-4b78-99e1-9c1e859a2720.png)

**Comment by JMunoz17** [comment]
Tengo dudas con esto, os cuento como lo haría yo y me decís si os cuadra:

Será al **procesar** un C1_05 o un C2_05.
Solo será si el histórico de acciones tiene marcado el check de HayCambioAutoconsumo (este check se marca si al importar el xml viene un tipo autoconsumo diferente al informado en la ficha de autoconsumo, **ojo a esto**, confirmadme que nos sirva este criterio).
Solo será si el Tipo Autoconsumo informado en el histórico de acciones es diferente a '00' Y diferente a '' (vacío).

Si se cumplen esas tres circunstancias:
- Marcamos el check de Autoconsumo en la ficha del contrato de suministro.
- Rellenamos "Tipo Autoconsumo Contrato" en la ficha de autoconsumo.
- Rellenamos la fecha de inicio de vigencia en la ficha de autoconsumo, utilizando la fecha de activación informada en el contrato de autoconsumo.

**Dudas:**
1. Que criterio utilizamos para buscar la ficha de autoconsumo correspondiente al C1/C2 05 que estamos procesando.
    Por código contrato de suministro y por algo más? por fechas a partir de la fecha de activación??
2. Es correcto el criterio arriba explicado de solo realizar esto si en el xml viene un "Tipo Autoconsumo" diferente al informado    
    en la ficha de autoconsumo? O puede existir una ficha con valor '41' y que este sin fecha de vigencia y sin marcar el check 
    de autoconsumo, y nos venga un xml con valor '41' y tengamos que marcarlo?
3. Si no encontramos ficha de autoconsumo dejamos algo en el log? Ya se deja un aviso al importar los XML. Deberíamos volver a hacerlo?

**Comment by dgarciageo** [comment]
Tengo dudas con esto, os cuento como lo haría yo y me decís si os cuadra:

> Será al procesar un C1_05 o un C2_05.

Correcto

> Solo será si el histórico de acciones tiene marcado el check de HayCambioAutoconsumo (este check se marca si al importar el xml viene un tipo autoconsumo diferente al informado en la ficha de autoconsumo, ojo a esto, confirmadme que nos sirva este criterio).

No es correcto,  esta comprobación no es necesaria

> Solo será si el Tipo Autoconsumo informado en el histórico de acciones es diferente a '00' Y diferente a '' (vacío).

No es necesario consultar el histórico de acciones. La comprobación se realizará contra la ficha de autoconsuo

> Si se cumplen esas tres circunstancias:

Sólo se tiene que comprobar que exista previamente la ficha de autoconsumo, que el tipo de autoconsumo coincida con el informado en el XML y que la fecha de inicio de vigencia de la ficha de autoconsumo sea 3000/01/01.

> Marcamos el check de Autoconsumo en la ficha del contrato de suministro.
> Rellenamos "Tipo Autoconsumo Contrato" en la ficha de autoconsumo.
> Rellenamos la fecha de inicio de vigencia en la ficha de autoconsumo, utilizando la fecha de activación informada en el contrato de autoconsumo.

Hay que marcar check de Autoconsumo y rellenar fecha inicio de vigencia. El tipo de autoconsumo no es necesario informarlo ya que debería de coincidir con el del XML

> Dudas:
> 
> Que criterio utilizamos para buscar la ficha de autoconsumo correspondiente al C1/C2 05 que estamos procesando.
> Por código contrato de suministro y por algo más? por fechas a partir de la fecha de activación??

Sólo por código contrato de suministro

> Es correcto el criterio arriba explicado de solo realizar esto si en el xml viene un "Tipo Autoconsumo" diferente al informado
> en la ficha de autoconsumo? O puede existir una ficha con valor '41' y que este sin fecha de vigencia y sin marcar el check
> de autoconsumo, y nos venga un xml con valor '41' y tengamos que marcarlo?

No es correcto, el tipo de autoconsumo de la ficha y el del XML deben de coincidir. 

> Si no encontramos ficha de autoconsumo dejamos algo en el log? Ya se deja un aviso al importar los XML. Deberíamos volver a hacerlo?

Se pueden dar las siguientes circunstancias:
-	Que el tipo de autoconsumo coincida pero que sea un 42, 51 o 52 -> que no se importe y deje entrada en el log
-	Que no haya ficha autoconsumo creada para el código de contrato de suministro correspondiente -> que no se importe y deje log
-	Que los tipos de autoconsumo del XML y cabecera autoconsumo no coincidan ->, que no se importe y deje log

**Comment by JMunoz17** [comment]
Tras revisarlo con Ainhoa subimos a PROD.
