### ISSUE TITLE
NAV (VBAT) - PASOS M1_05 (modificación técnica “compensación de excedentes”)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#1361]
Hay que tener en cuenta que el fichero M1 comprende tramitaciones de modificación administrativas (cambio titularidad); técnicas (cambio potencia /tarifa); y/o ambas. A día de hoy, al importar/procesar cualquier paso 05 se envían los emails correspondientes y se realizan las actualizaciones/cambios oportunos, salvo cuando el M1_05  es de activación de compensación de excedentes.
 
Creo que ya que nos ponemos con ello, no supondría mucho problema, y evitaríamos errores “humanos” si se escapa algún log.
 
Importante: para diferenciar este tipo de M1_05 del resto, tienen que venir precedidos siempre por un D1_01 y su correspondiente D1_02 (aceptación) en el histórico de acciones .
 
Os muestro una cadena de tramitaciones como ejemplo:
![image](https://user-images.githubusercontent.com/47117960/159696300-a40ce53c-b0a5-4055-be9a-287c7da9182c.png)

En este caso, habría que realizar las siguientes acciones:
 
1.	Al procesar el M1_05 de activación, se debe identificar  si viene precedido por un D1_01/D1_02 y considerar la fecha de activación (nodo <DactosActivacion>/Fecha), que también se traslada al histórico de acciones el campo “Fecha activación”, como **fecha inicio vigencia del autoconsumo** (en la ficha NAV de autoconsumo). En este caso no hace check del contrato, porque ya lo hice yo previamente al cargar el D1.  

![image](https://user-images.githubusercontent.com/47117960/159696447-8c16684b-5620-41dd-9c82-10d58e887497.png)

![image](https://user-images.githubusercontent.com/47117960/159697715-17d28131-1cfd-4b78-a1da-80bbc02afa6b.png)

2.	Debe enviar un email al cliente indicando la fecha de activación. Os paso más abajo el modelo que utilizamos como macro en Zendesk.

> Comunicación cliente:
>  
> Asunto: Activación compensación de excedentes XXXXX
> 
> 
> Hola  {{ticket.requester.first_name}}:
>  
> Nos complace comunicarte que ya hemos finalizado los trámites con la distribuidora y nos ha confirmado que ya estás compensando tus excedentes de energía solar desde el pasado XX/XX/XXXX.
>  
> Gracias por tu confianza.

3. Para el caso 2 (“PASOS M1_05 (modificación técnica “compensación de excedentes”) es importante que, al procesar el paso M1_05, salte un log o que llegue un email informativo,  en los casos en los que se active un autoconsumo con proyecto asociado, para que pueda cambiar el estado en la BBDD así como para poder cerrar la tarea de “activación distribuidora”.

Si necesitáis cualquier otro detalle me decís.
 
Os dejo los dos xml de ejemplo en la siguiente ruta de red por si hay que hacer pruebas:

\\ni\EsiosPre\Jaime\BateriaVirtual
 
Gracias,

**Comment by JMunoz17** [comment]
Misma duda que en la otra tarea sobre como identificar la ficha de autoconsumo.
Buscando por contrato de suministro y por algo más?

Enviaríamos únicamente un mail al cliente informado en la ficha de autoconsumo (a nivel estilos usaremos formato como el de impagos). Solo lo implementaremos para GEO.

Para el paso 3 vosotros diréis si queréis log o mail.
Log es más sencillo.
Si queréis mail indicadme la dirección a la que debe llegar (si está en alguna configuración, mejor) y cual debe ser el texto y formato.
A lo mejor os sirve con incluir en copia del mail del paso 2 la dirección que me digáis.

**Comment by dgarciageo** [comment]
> Misma duda que en la otra tarea sobre como identificar la ficha de autoconsumo.
> Buscando por contrato de suministro y por algo más?

Sólo por contrato de suministro

> Enviaríamos únicamente un mail al cliente informado en la ficha de autoconsumo (a nivel estilos usaremos formato como el de impagos). Solo lo implementaremos para GEO.

En este caso, las acciones que se tiene que realizar son,  machacar la fecha de inicio de vigencia de la cabecera de autoconsumo y enviar mail al cliente.

La condiciones para que se procese el M1_05, es que debe de estar precedido de los siguientes pasos en el histórico de acciones, D1_01, D1_02, M1_01, M1_02 -> Llega M1_05. Además, en la cabecera de autoconsumo, la fecha de inicio de vigencia ficha autoconsumo debe ser igual a 3000/01/01

En el caso de que no se cumplan estas condiciones, que no se importe el XML y deje log

> Para el paso 3 vosotros diréis si queréis log o mail.

Ainhoa prefiere mail.
Si hay un código de proyecto informado en la ficha de autoconsumo, hay que mandar un correo a administracion@proximaenergia.com y en CC a agalinde@geoatlanter.com que incluya el siguiente mensaje:

Se ha activado el contrato de autoconsumo Nº **AUT0009999** con código de proyecto asociado **999**

**Comment by JMunoz17** [comment]
Subido a PRE.

A nivel de configuración solo es necesario informar los mails [administracion@proximaenergia.com](mailto:administracion@proximaenergia.com) y en CC a [agalindez@geoatlanter.com](mailto:agalinde@geoatlanter.com) en Información de Empresa (cuando lo suba a producción lo dejaré yo configurado).

Los dos campos de abajo:
![image](https://user-images.githubusercontent.com/26869276/160600946-71ae6ec6-ac9d-4a39-af38-411397f8dcb7.png)

De momento en GEOPRE he desactivado el SMTP (__ en la pass) y todos los clientes tienen mi email asociado, por si hacéis pruebas.

La tarea #1360 también esta en PRE.

Cuando me deis el Ok subimos a PROD.

**Comment by JMunoz17** [comment]
Tras revisarlo con Ainhoa subimos a PROD.

**Comment by JMunoz17** [comment]
Hay que crear un formato del estilo del resto de las comunicaciones existentes en NAV para el mail que enviamos al cliente.

**Comment by JMunoz17** [comment]
Formato incluido, subido a PROD.
