### ISSUE TITLE
NAV-GAC-COM/06251-Problema financiación autoconsumo- Proyecto 52

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1363]
El cliente ha amortizado la financiación. Hemos duplicado la ficha de autoconsumo y hemos eliminado el detalle, entendiendo qeu se eliminaba para la nueva ficha, sin embargo, al estar asociado al contrato COM/06251 se ha eliminado el detalle de la tabla. 
no sé cómo debemos hacer para mantener el detalle de financiación.
Antes de eliminarlo lo exporté a un excel que adjunto para poder hacer de nuevo el insert
[AUT000123 - Ficha Contrato Autoconsumo.xlsx](https://github.com/PKFEric/webProxima/files/8363293/AUT000123.-.Ficha.Contrato.Autoconsumo.xlsx)
l

**Comment by JMunoz17** [comment]
Y como lo has eliminado Belén? Ilegalmente no? jeje Porque como usuario no te deja..

El detalle de financiación va asociado al contrato de suministro, esto es necesario porque un mismo detalle puede ir asociado a varias fichas. Que problema hay en que siga asociado una vez ha sido amortizado?

Entiendo que lo que necesitaréis es un proceso que marque esa financiación como amortizada no? Para que no sigan incluyéndose las líneas en las facturas no?

**Comment by bpesquero** [comment]
Jeje, con lo legal que yo soy. Te prometo que el borrado de la financiación lo he hecho de forma legal desde la ficha duplicada con el botón eliminar financiación.
No sé si lo que hemos hecho otras veces es borrar las líneas que no tienen factura asociada y dejar sólo las líneas de financiación con factura asociada.

**Comment by JMunoz17** [comment]
Tal y como hemos comentado:

- Hemos arreglado el proyecto al que hace referencia la tarea, cargando su detalle de financiación y desasignándolo del contrato de ACSM con algoritmo SC.
- Hemos incorporado un control para que, una vez replicado el contrato de ACSM, no permita cambiar el algoritmo de ACSM de un contrato con detalle ya facturado (y no abonado).
- Para cambiarlo habrá que primero emplear una funcionalidad nueva (nuevo botón en la ficha de ACSM, "Desasignar financiación), que desasignará la financiación solo del contrato de ACSM correspondiente, sin eliminarlo y permaneciendo asignado al resto de contratos de ACSM en caso de que existan.

Subido a PRE y PROD.
