### ISSUE TITLE
NAV - Quitar nodo ModoControlDePotencia de los C1, C2 y M1

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#1368]
Ainhoa pide que eliminemos este nodo de los ficheros de switching para evitar problemas con la distribuidora ya que no es obligatorio.

**Comment by JMunoz17** [comment]
De que pasos?

Con quitarlo entiendo que os referís a que no salga el nodo en ningún caso.

**Comment by dgarciageo** [comment]
De los pasos 01. 

Correcto, que no salga en ningún caso.

Muchas gracias!!

**Comment by bpesquero** [comment]
Aclaración, se trata de eliminar efectivamente el nodo MOdoControldePotencia de los pasos 01 de 
C2, M1 y A3

**Comment by JMunoz17** [comment]
Hecho.
Subida a PRE y PROD.
Volver a abrir NAV para que se apliquen los cambios.
