### ISSUE TITLE
NAV- Campos en tablas productos

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1369]
Necesitamos dos campos nuevos en la tabla de productos

1.- Campo tinyint [usado]
2.- Campo texto largo [Descripcion larga],tendría que ser una especie de campo de comentarios para poder introducir descripciones suficientemente largas

**Comment by JMunoz17** [comment]
Existe una funcionalidad estándar para introducir comentarios asociados a diferentes entidades, entre ellas la de productos.
Entiendo que esto os serviría.
Es para introducir los datos desde NAV o desde SQL? Para explicarlos como va.

**Comment by bpesquero** [comment]
Si, ya le comenté a Jorge cómo funcionan los comentarios en NAV, y me dice que no le vale

**Comment by JMunoz17** [comment]
Es decir, campo nuevo en la tabla de productos de 250 caracteres, que es lo máximo. No?

**Comment by bpesquero** [comment]
Nada, entonces lo dejamos. 250 no son suficientes, Lo haremos a través de ACSM
Así que sólo el primer campo de los indicados

**Comment by JMunoz17** [comment]
Creado el campo "Used". Mostrado en la ficha y lista de productos, editable, sin funcionalidad asociada.
Subido a PRE y PROD.
