### ISSUE TITLE
NAV - Error exportación remesa de confirming

### ISSUE THREAD

**Issue by omartinesc** [PKFEric/webProxima#1374]
Buenas,

La usuaria mgomez ha intentado exportar una remesa de confirming y al seleccionar la ruta de exportado le da el siguiente fallo:
![46ac67f0-de72-4d86-ac43-75957d39c987](https://user-images.githubusercontent.com/106239730/177938409-8f993719-b7fd-477e-9ffd-6d5f91583480.jpg)

¿Podéis echarnos una mano?

Muchas gracias y un saludo.

**Comment by JMunoz17** [comment]
Hola Belén,

Este error viene derivado de que Navision no ha sido instalado de forma correcta en el nuevo equipo de Mónica.

Ayer, mi compañera Eunate intentó instalarle el ocx que le falta, pero no tenemos ningún usuario con los permisos necesarios para poder hacerlo. 

O bien nos dais un usuario administrador para instalarlo, o, le pedís a quien os lleve los sistemas ahora mismo que vuelva a instalarle NAV, porque está mal instalado y hoy le ha fallado este proceso pero mañana le puede fallar cualquier otro.

Yo os recomiendo esta segunda opción, pero como queráis.

**Comment by omartinesc** [comment]
Buenas Jaime,
Hemos reinstalado Navision, pero ahora no nos deja entrar directamente.
¿Podéis volver a contactar con Mónica para revisarlo?
El usuario administrador es [ admgeo ] con pass [ !"·ERT&/(Geo21 ].
Os dejo también el correo y numero de mi compañero Juanfe por si necesitáis contactar con el para realizar alguna modificación en el equipo.

jgonzalez@proximaenergia.com
690 14 72 73

Muchas gracias y un saludo.

**Comment by JMunoz17** [comment]
Lo hemos derivado al departamento de sistemas.
Contactarán con Juanfe o Mónica para conectarse al equipo y revisar la instalación.

**Comment by JMunoz17** [comment]
La incidencia quedó solucionada por el departamento de sistemas.
Se reinstalo NAV en el equipo de Mónica y se explicó a Juan Felipe como instalar correctamente NAV (el problema venía de no estar instalados los pre-requisitos) y como instalar las DLLs implementadas por Attest.
