### ISSUE TITLE
NAV-GAC-reganecu C5_202109

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1378]
Al facturar el reganecu de la C5 de 202109 la factura de compra es correcta, pero se genera una factura de venta que no corresponde. No debe haber factura de venta. La factura de venta que se ha generado la hemos dejado abierta. Se puede ver que la factura de venta se corresponde con los términos de reganecu de la factura de venta pero no se han restado las facturas anteriores. 
He mirado y veo todo correcto en los movimientos de reganecu de meses anteriores así que no se por qué ocurre esto.

**Comment by JMunoz17** [comment]
En principio todo se esta haciendo de forma correcta en base a lo programado:

**Canarias:**
La factura de venta tiene 1.988,82.

Si buscamos en los movimientos de reganecu, nos sale lo siguiente.

Versión C5:
![image](https://user-images.githubusercontent.com/26869276/189640836-763fac3b-0fc1-44f3-b9c7-929059b1d394.png)

Versión C4:
![image](https://user-images.githubusercontent.com/26869276/189641133-7aebfd8d-f36a-47e6-bcef-27a4574c59ba.png)

Para Amount Sign -1 si que coincide lo facturado en la C4 y en la C5 pero para Amount Sign 1 no coincide.
Si buscamos sin filtrar por lo facturado (Invoiced) si que coincide, por lo que en este caso el problema es que no se ha facturado la versión C4 para ese periodo de fechas. 

**Baleares:**
La factura de venta tiene 1.405,76.

Versión C5:
![image](https://user-images.githubusercontent.com/26869276/189641955-65a1613a-5394-456d-9970-eef3c6e45968.png)

Versión C4:
![image](https://user-images.githubusercontent.com/26869276/189642083-541324c3-9c55-42a5-a49f-cbce3f2aad63.png)

Pasa lo mismo, para Amount Sign -1 si que coincide lo facturado en la C4 y en la C5 pero para Amount Sign 1 no coincide.


El problema por lo tanto es que los registros de Amount Sign 1 para la versión C4 de ese periodo de fechas no fueron facturados.

**Comment by JMunoz17** [comment]
En principio están todos los datos de forma correcta en los movimientos de reganecu: números de facturas, check de facturado, etc..

Achacamos el error a que se facturó la versión C4 mientras el código no estaba OK, provocando que no se marcasen los registros como facturados si tenian Sign Amount a 1. Con los datos que había, era imposible detectar el error al facturar la versión C4 y el error saltaba con la C5, ya que en la C4 salian bien las facturas.

Las facturas erróneas de la C5 las he eliminado.
