### ISSUE TITLE
Ciclo de impagados

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#138]
Hemos simulado un ciclo de impagados desde GeoAtlanter y hemos tenido los siguientes problemas

1.- Al cargar el fichero de devolución no se envía el correspondiente mail 
2.- No podemos insertar comentarios desde la pantalla de gestión de cobros
3.- EL asunto del mail 1 que se envía desde Gestión de cobros debería ser "Aviso baja unilateral del contrato"
4.-Tanto el mail1 como el mail 2 no ha llegado al pagador. cierto es que el contrato con el que hemos probado (el mío) tenía el mismo cliente pagador y titualr, así que hemos cambiado el pagador en el contrato, y quizá coja el pagador de la factura.
5.-EL mail pdf 1 y 2 tienen un aspecto un poco feo:
      - En los datos de envío de la factura aparece el nombre del cliente titular, pero la dirección es la del cliente pagador, además aparece el nombre de la calle pero no el número ni el resto de parámetros de la dirección. El Código Postal es el de la dirección de cliente titular. Vamos que está todo un poco mezclado
      -  Los datos de envío de la factura yo no los encuadraría
      -  Falta la firma debajo de "un saludo"
          Próxima Energía
          GeoAtlanter, SL

      -  Bajar la dirección
     -  Bajar todo el texto y separar más de la dirección
     -  Poner la letra más grande
     -  Justificar el texto

**Comment by jorgereal** [comment]
¿Puedes enviarnos un fichero de devolución de ejemplo para hacer las pruebas?
Los puntos del 2-5 están resueltos.
En los mails pdf 1 y 2 no es posible justificar el texto, el diseñador no lo permite, tan solo alinearlo a la izquierda o a la derecha.
Si quieres algún cambio más en el formato comentanoslo.

**Comment by jorgereal** [comment]
Ya se envía el mail de impago al registrar una devolución importada.
