### ISSUE TITLE
NAV- Nuevo valor en el campo situación de recobro

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#1380]
Buenas, me gustaría meter un nuevo valor en el campo "situación de recobro" que sea "pendiente monitorio". A la hora de lanzar los procesos de gestión de deuda debería tener el mismo tratamiento que "pendiente".
No hay que pasar ningún proceso para actualizar valores, lo hacemos de forma manual.

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
