### ISSUE TITLE
comprobación medida cierre y peaje

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#146]
El fichero F del contrato COM/00057 contiene medidas para la parte de facturación, pero no para la de cierre. No ha dado ningún error en el log, ni al hacer la factura de compra ni al hacer la factura de venta. Tendría que haber saltado la comprobación de que la energía de cierre sea igual a la energía de peaje, para que no hubiéramos registrado la compra.

**Comment by PKFEric** [comment]
He replicado la importacion en la empresa de pruebas y en el log me sale
COM/0057	ES0022000008732920SZ	No coinciden los datos de cierre 0 y peaje 181 en Energía Activa.	SCTDE_F1_01_0022_0587_20161128170103299_(466717036).xml	15/12/16 08:48
