### ISSUE TITLE
error medidas horaria 3,4 y 5

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#151]
Al sacar el informe de medidas horarias 3, 4 y 5 da un error de "El sistema operativo devolvió el error 131. Se ha intentado mover el puntero del archivo más allá del inicio del archivo"

Mando pantallazo por mail

**Comment by jorgereal** [comment]
El error se debe a la magnitud de los datos, yo logré ejecutar el proceso pero tardó 9 horas.
Hemos realizado algunos cambios, ahora el informe se exporta en varios ficheros, el número de contratos que se exportarán en cada fichero es configurable.
Es probable que algunos de estos ficheros salgan en blanco, debido a que habrá contratos sin medidas horarias asociadas al periodo indicado.

**Comment by bpesquero** [comment]
¿donde se configura el nº de contratos?

**Comment by jorgereal** [comment]
En las opciones del informe, junto a donde se selecciona el periodo, por defecto tiene un valor de 100.
