### ISSUE TITLE
Problema carga fichero F

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#154]
El fichero GRCW_13-02-2017_FECSA_GEOATLANTER_F1_01_ES0031405271381001GS0F_1.xml no se carga ni por el método convencional ni por el mejorado. En ambos casos da el mismo error
Error,el calendario de Medidas del contrato COM/00066 es 6p y el numero de medidas es 20

**Comment by PKFEric** [comment]
Si vienen todos los periodos y el totalizador, entonces obviamos el totalizador.

**Comment by jorgereal** [comment]
Hemos modificado el proceso de carga para los casos en los que vengan todos los periodos y además el totalizador, ya no debería dar problema  el fichero GRCW_13-02-2017_FECSA_GEOATLANTER_F1_01_ES0031405271381001GS0F_1.xml
