### ISSUE TITLE
Problema con medidas horarias cuando hay un cambio de contrato

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#155]
El CUPS ES0022000008379200TB tiene dos contratos, uno termina el día 27/01 y el otro empieza el día 28/01. Se carga fichero F5D para el primer contrato, pero en la tabla de medidas horarias el día 27 lo asigna al otro contrato, de tal forma que al cagar el peaje da mensaje en el log de que las medidas de cierre no coinciden con las medidas horarias. Al hacer la factura de venta da el mismo error.

**Comment by jorgereal** [comment]
Los únicos contratos que hemos encontrado que cumplen esas fechas son el COM/00108 y COM/00142, con CUPS ES0022000008379200TB.
Hemos eliminado las medidas horarias del último fichero importado y hemos vuelto a procesarlo, en esta ocasión se lo ha hecho correctamente, asignando a todas el contrato COM/00108, incluidas las del día 27.
