### ISSUE TITLE
Problema con cliente no localizado

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#156]
Tenemos dos clientes que debieron intentar darse de alta pero al parecer hubo algún problema. En NAV no aparecen, y lo único que tenemos es el DNI. Tenemos en la web guardada alguna otra información que nos permita ponernos en contacto con ellos?

30211606W
50076160P

**Comment by PKFEric** [comment]
Crear tabla en MySQL que almacene  Email, NIF/CIF, Nombre , Telefono...

**Comment by PKFEric** [comment]
Se ha creado un log en una tabla y se ha testeado, a partir de ahora antes de hacer ningun contacto con navision, se insertara primero toda la informacion del cliente y del contrato en esta tabla de MYSQL.

**Comment by bpesquero** [comment]
No has podido localizar ningún dato de estos clientes, verdad?
