### ISSUE TITLE
Problema usuario titular no pagador

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#157]
En la web, cuando un usuario es titular pero no pagador no ve las facturas, si los contratos. Probar con el usuario de Ainhoa

**Comment by PKFEric** [comment]
Solo el usuario pagador tiene acceso a las facturas de sus contratos. El titular si no es pagador no tiene acceso a las facturas que paga el pagador. 
Esto se estableció así desde el principio.

**Comment by PKFEric** [comment]
El titular puede ver las facturas de los contratos de los que es titular aunque no sea pagador.
