### ISSUE TITLE
Activación C2 con DH Unión Fenosa

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#160]
EL fichero de activación C2  de da error al cargar ya que en el fichero se informa de la potencia del P1 y P2 para una DH. Para _Unión FEnosa. Ejmeplo COM/00110 y COM/00113

**Comment by jorgereal** [comment]
Hemos probado a importar el fichero C2_05 de los Contratos COM/00110 y COM/00113 y ambos los ha procesado correctamente (ya habían sido cargados previamente).
¿Hay algún otro fichero que de error?

**Comment by bpesquero** [comment]
SEguramente el fichero que habéis cargado  es el que modificamos a mano para poder cargar... Si necesitais el original decidnoslo

**Comment by jorgereal** [comment]
El error obtenido viene de un control que compara las potencias contratadas con las que vienen en el fichero.
Tratándose de una DH debería venir solo una, por lo que entendemos que el error está en el fichero de Unión Fenosa y no en el código.

**Comment by bpesquero** [comment]
Por supuesto, esto lo tenemos claro, pero habrá que poner un control que cuando se trate de una DH, y así venga identificada en el propio fichero C2, si se informa de la potencia en P2, no hacerle caso

**Comment by jorgereal** [comment]
Hemos añadido el código para contemplar ese caso en el control, ya se pueden importar los dos ficheros sin necesidad de modificarlos.

**Comment by bpesquero** [comment]
comprobado y ok

**Comment by bpesquero** [comment]
Hemos tenido el mismo problema con un C1, sólo se ha cambiado para el C2? Envío fichero por correo

**Comment by PKFEric** [comment]
Ya esta solucionado para las C1_05
