### ISSUE TITLE
Factura electrónica - varios

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#163]
Al dar de alta en la web un contrato con factura electrónica en el resumen final, en la  pantalla de confirmación, tiene que aparecer el precio correcto. Aparece siempre el de con factura electrónica.

Cuando accedes a la parte cliente de la web, al dar a ver detalle del contrato, que se ve el detalle del contrato en la pantalla, el precio tiene que aparecer el correcto. Aparece el de con factura electronica.

Al exportar desde la web el contrato a pdf lo mismo.

En Roles, al imprimir las facturas necesitamos poder distinguir los que tienen factura electronica de los que no, para saber a cuales tenemos que enviar el mail y a cuales tenemos que enviar la factura en papel.

**## En la ficha del contrato al cambiar el valor de factura electrónica debe avisar de que va a cambiar el margen, para tenerlo en cuenta cuando tenemos contratos con margenes especiales.**

**Comment by PKFEric** [comment]
Llevar campo de Factura Electronica de Contrato a Factura Venta y Abono Venta

**Comment by PKFEric** [comment]
Se han realizado todas las modificaciones.

**Comment by bpesquero** [comment]
Al dar de alta en la web un contrato con factura electrónica en el resumen final, en la pantalla de confirmación, sigue sin aparecerme el precio correcto.

Desde roles no localizo el campo para poder filtrar a la hora de hacer la facturación. Me puedes indicar cual es?

**Comment by PKFEric** [comment]
Se ha modificado en la creacion de contrato interna para que aparezcan bien los importes

**Comment by bpesquero** [comment]
Pues sigue saliendome mal....

**Comment by bpesquero** [comment]
hemos detectado que cuando se hace un nuevo contrato para un titular ya existente y es de factura electrónica, si bien en el pantallazo aparecen los 3€ tanto en Navision como en el contrato que se descarga posteriormente aparecen 2€.
Por otra parte, para un contrato que se ha generado adecuadamente con los 3€ de no facutra electrónica, cuando se envia a historico de acciones un fichero de cambio de comercializador (C1 o C2) para el contrato recién dado de alta, se actualiza en la ficha del contrato el precio, apareciendo los 2€ y se desmarca el check de factura electrónica.
