### ISSUE TITLE
Problema con contrato ES0031105211929001WM

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#164]
EL contrato ES0031105211929001WM tiene una factura de peaje con curva asociada, en la que tanto la fecha de inicio como la de fin son días no completos. El problema viene en que la factura anterior no tiene curva de carga asociada y por tanto no se detectó que no era por días completos. Al facturar ahora sale hueco de facturación.
Sinceramente no se como solucionar este caso, lo damos una vuelta y lo comentamos. Llevamos con ellos parado mucho tiempo, a ver si conseguimos darle una solución mañana.

**Comment by PKFEric** [comment]
Ya esta arreglado y cargado el peaje para el  contrato COM/00100 Revisar la factura de compra ya generada  y la posterior de venta pendiente de generar.

**Comment by bpesquero** [comment]
La factura de venta está mal. No ha considerado las medidas horarias del día 5, del primer día de la factura. Si bien la cabecera debe ir desde el día 6 las medidas horarias a facturar deben ser todas las incluidas en la factura de compra

**Comment by bpesquero** [comment]
Comprobado y ok

**Comment by bpesquero** [comment]
Estaba mal la parte de financiación del bono social. Hemos abonado la factura. Hemos quitado de las tablas toll y closing el nº de factura de venta registrada y el nº de prefactura de venta. AL hacer de nuevo la factura salen las lineas a cero.

**Comment by bpesquero** [comment]
El problema está en que también hay que quitarlo de la tabla de medidas horarias (el nº de factura de venta y el nº de prefactura de venta), lo he empezado a hacer a mano, pero me voy a eternizar. Podéis hacer vosotros un update a la BBDD. Lo podría hacer yo, pero luego me echais la bronca...
