### ISSUE TITLE
problema ruta generación de C2

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#166]
Hemos generado un C2 desde el equipo de Ainhoa y nuevamente ha dado error, lo que ocurre es que no se ha cambiado el estado del contrato.

Se trata del contrato COM/00162

**Comment by bpesquero** [comment]
También para el COM/00164

**Comment by bpesquero** [comment]
SEguimos teniendo problemas. Envío mail explicativo

**Comment by PKFEric** [comment]
Corregido con ainhoa

**Comment by bpesquero** [comment]
Comprobado y ok
