### ISSUE TITLE
log chequeo peajes incorrecto

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#168]
Al generar la factura de compra FC/2017007184 del contrato HECEN/00242 da el siguiente error en el log: 
No coinciden los datos de cierre 3 y peaje 3,12 en Potencia demandada.
EStá mal, los datos si que coinciden, lo que ocurre es que en el cierre no está teniendo en cuenta el ajuste de integrador.

Mal hecha también la comprobación con la factura FC/2017007198 del contrato HECEN/02250

**Comment by jorgereal** [comment]
Hemos hecho la comprobación y nos hemos dado cuenta de los siguiente:
Cuando existen medidas de cierre de tipo potencia para 6 periodos y medidas de peaje de tipo potencia solo para 3, la comparación que se realiza es la siguiente:
se coge el (consumo+ajust.integrador) del periodo 1 y el (consumo+ajust.integrador) del periodo 4 (medidas de cierre), el mayor de ellos es el que se compara con el periodo 1 de de las medidas de peaje.
igual para: 
  los periodos 2 y 5 de medidas de cierre con el periodo 2 de medidas de peaje
  los periodos 3 y 6 de medidas de cierre con el periodo 3 de medidas de peaje
Para la factura FC/2017007184 el mayor de los periodos 3 y 6 de las medidas de cierre vale 3 y el periodo 3 de las medidas de peaje vale 3,12, por lo que no coincide y registra el error en el log.

¿Es correcta esta validación?

**Comment by bpesquero** [comment]
No, esto ya lo hemos comentado más veces. Cuando tenemos equipo de medida en 6p y facturación en 3p, y además hay ajuste de integrador, la potencia en 3 periodos se obtiene como:

P1=max(P1,P4)+ ajuste integrador1
P2=max(P2,P5)+ ajuste integrador2
P3=max(P3,P6)+ ajuste integrador3

o lo que es lo mismo

P1=max(P1+ajuste integrador1, P2+ajuste integrador1)....

Si tienes duda lo comentamos.

**Comment by jorgereal** [comment]
Hemos corregido la validación, y hemos generado la factura FC/2017013939 para el contrato HECEN/00242, eliminando previamente la FC/2017007184.
La importación ya no registra errores en el log.

**Comment by bpesquero** [comment]
Comprobado ok
