### ISSUE TITLE
Informes OCSUM febrero 2017

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#169]
·         En GAC, de Pendientes de activación, según ROLES hay 3, pero según he mirado en NAV Histórico de Acciones sólo tendría que aparecer uno, el COM/00163, que se activa en marzo.
 
·         De HECEN, en Pendientes de Respuesta, aparece el 1 cuando no debería haber ninguno. Yo creo que contabiliza el HECEN/08158, un A3 con varios pasos 01 ( tres en concreto), de los cuales sólo uno tiene respuesta de aceptación y activación.

**Comment by jorgereal** [comment]
Para GAC - Pdtes.Activación ahora muestra 2, correspondientes a los contratos COM/00162 Y COM/00163,
el COM/00162 se activó el 1 de marzo, por lo que para el mes de febrero estaba pendiente.

Para HECEN - Pdtes de Respuesta está contabilizando el HECEN/08180, para el que solo existe un paso A3 01.
