### ISSUE TITLE
Bono Social

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#170]
- En la tasa municipal se incluye el bono social
-Impresión
 -Detalle la financiación del bono social esta mal indentado, tiene que estar como el resto de cosas.
 - Hay que poner las unidades (Dias) * (€/Dia) 
 - Sale una linea de energía Reactiva a 0.
 - Donde pone Remuneración Geoatlanter la palabra "dia" sale con "D" mayusula y tiene que ser minuscula.
 -Resumen de la factura, en el cuadro suma el Bono Social + Remuneracion de Geoatlanter y Pone Financiación del Bono social -> Separarlo. Cada cosa por su lado.

 -Financiación del Bono social tiene que ir debajo de la Eficiencia Energética.

**Comment by bpesquero** [comment]
Todo ok. Sólo un par de detalles. En el reverso de la factura donde viene el cálculo de la financiación del bono social poner 37,000 día x 0,016€/día, habría que quitar los decimales del nº de días y poner en una "s" para que quede 37 dias x .... Idem en la línea de remuneración de GeoAtlanter

**Comment by jorgereal** [comment]
Ya está arreglado.

**Comment by bpesquero** [comment]
Comprobado y ok
