### ISSUE TITLE
Pb carga fichero M con DH

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#174]
Los fichero de activación del proceso M de Unión Fenosa, al igual que lo que ocurría con los ficheros C2 de activación, tienen informada la potencia 1 y la 2 y dan problema.
Lo mismo ocurrirá con los C1, aunque no hayamos tenido el caso, así que habría igualmente que solucionarlo.

**Comment by PKFEric** [comment]
Realizado y corregido

**Comment by bpesquero** [comment]
Me dice Ainhoa que sigue dando error.Ha probado con xml del COM/00110 y también sigue dando error. Está el fichero en \\NI\Esios\OCSUM\GAC\Importados, aunque ya se cargó en su día (luego habrá que borrarlo del histórico).

**Comment by PKFEric** [comment]
Solucionado con Ainhoa.
