### ISSUE TITLE
Informe 583 -representación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#180]

**Comment by bpesquero** [comment]
hemos comprobado que el informe sale bien si se lanza desde el menú de administración, si se hace desde el menú de gestión de mi planta (que es donde acceden los clientes) sigue saliendo mal. Entiendo que no tira exactamente del mismo sitio y hay que modificar los dos.

**Comment by PKFEric** [comment]
Ya esta igual que el de administracion.

**Comment by bpesquero** [comment]
probado y ok
