### ISSUE TITLE
Problema  impresión factura - costes regulados

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#184]
Al imprimir algunas facturas, por ejemplo H/2017020620, en el reverso de la factura, donde aparece el importe total correspondiente a peajes y su desglose, aparecen todos los datos a 0.

**Comment by jorgereal** [comment]
El cálculo de los peajes y su desglose se realiza a partir de la factura de compra registrada. La factura H/2017020620 tiene asociada la factura de compra FC/2017020870, pero no ha sido registrada aún.
Si registráis la factura de compra deberían salir ya los importes, la impresión de la factura de venta debe ser posterior al registro de la factura de compra.
