### ISSUE TITLE
informes OCSUM

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#190]
AL ejecutar el informe de mayo de solicitudes aceptadas y activadas hemos encontrado un error. Aparecen dos líneas para el distruidor con nº ministerio R1-229. Esto es por que en realidad en la tabla son dos distribuidores, 0022 y 0024 (creo), aunque ambos son para el ministerio el mismo distribuidor. Yo creo que la cosa está en que al agregar los datos en vez de hacer el group by por cod Os del distribuidor hay que hacerlo por Nº registro del ministerio

**Comment by jorgereal** [comment]
Hemos modificado la clave de agrupación para todos los informes OCSUM, ahora en lugar de agrupar por "Cod. Ministerio distribuidor" lo hace por "Nº Ministerio".
En las aceptadas y activadas de mayo ya sale una única línea para el ministerio R1-299.

**Comment by bpesquero** [comment]
Lo hemos probado y nos sigue apareciendo en dos lineas.

**Comment by jorgereal** [comment]
Acabamos de reiniciar el servicio para que se refresquen los cambios, ¿podéis probar ahora?

**Comment by bpesquero** [comment]
probado y ok
