### ISSUE TITLE
Error prueba C1 a fecha fija

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#193]
Da error al validar las fechas. Creo que puede ser porque tiene rellena la fecha prevista de accion, quizá porque viene de un contrato anterior....

**Comment by JMunoz17** [comment]
Se debe a que le hemos puesto un control que te muestra ese mensaje en caso de que el Indicativo de Activación sea F y el Tiempo Previsto Acción (en días) sea menor de 30, es lo que hemos entendido a partir de lo que pone en el Excel correspondiente al C1_01.

![image](https://user-images.githubusercontent.com/26869276/27338725-450bff2c-55d6-11e7-96e2-009c50e68b64.png)

**Comment by bpesquero** [comment]
Si, pero por que salta ese control? Nosotros estamos poniendo fecha fija y en tiempo previsto acción en días estamos poniendo 5, así que no entiendo porque salta el mensaje diciendo que es mayor de 30

**Comment by JMunoz17** [comment]
Efectivamente estaba poniendo el control al revés, ya esta solucionado, también para M1_01, C2_01 Y A3_01.

**Comment by bpesquero** [comment]
Ahora da error, no puede hacer un calculo de fechas en base a una fecha indefinada.

**Comment by JMunoz17** [comment]
Solucionado.

**Comment by bpesquero** [comment]
Ahora da otro error, de validación con el esquema. Por favor, validad todo bien, antes de volvernos a confirmar que una incidencia está solucionada. gracias

**Comment by JMunoz17** [comment]
Nos hemos dado cuenta que es necesario que este relleno el campo Tipo Persona para saber si hay que sacar nombre+apellidos o razón social, hemos modificado el contrato para que al validar el titular lo rellene automáticamente, pero para los contratos que no lo tenían hay que tenerlo en cuenta y rellenarlo en la ficha del contrato en la pestaña de ocsum.

**Comment by bpesquero** [comment]
Probado y ok
