### ISSUE TITLE
Error C2 con cambio contractual y administrativo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#195]
Da error al validar el tipo de contrato de ATR

**Comment by JMunoz17** [comment]
Había dos fallos, por un lado el campo FechaFinalizacion estaba marcado como obligatorio y no lo es (ya esta cambiado) y por otro lado es necesario rellenar el campo Tipo Autoconsumo en el contrato.

Un saludo.

**Comment by bpesquero** [comment]
El campo tipo autoconsumo estaba marcado e informado el xml

**Comment by JMunoz17** [comment]
Ok era por si acaso no lo habíais marcado, entonces solo fallaba lo referente al campo FechaFinalizacion.

**Comment by bpesquero** [comment]
Probado y ok
