### ISSUE TITLE
Prueba A3_01 COM/00206

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#196]
FAllo en validación tarifa ATR

**Comment by JMunoz17** [comment]
Solucionado, hemos cambiado en la tabla Ocsum Value que para la tabla 017 (Tarifa ATR o Integral) tome el valor del campo en formato 001 y para la tabla 009 (Tipo de Contrato ATR) tome el valor en formato 01.

**Comment by bpesquero** [comment]
Comprobado y ok
