### ISSUE TITLE
error importar A3_05

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#198]
Nos da error la importación de la activación del A3.

Log Ocsum:
El valor Min Occurs especifica la aparición del elemento <TipoDHEdM>: Once. Se recibió el elemento: <ModoMedidaPotencia>. 
SCTDE_A3_05_0022_0587_20170623112902050_(549100716).xml
El valor Min Occurs especifica la aparición del elemento <TipoDHEdM>: Once. Se recibió el elemento: <ModoMedidaPotencia>. 
SCTDE_A3_05_0022_0587_20170623112902257_(549100718).xml

**Comment by JMunoz17** [comment]
Ya esta corregido el error, ahora hemos visto que para el contrato del fichero SCTDE_A3_05_0022_0587_20170623112902050_(549100716).xml se envio potencia en el periodo 1 y devuelve potencia en el periodo 1 y 2. Contrato  COM/00236.


Para el fichero SCTDE_A3_05_0022_0587_20170623112902257_(549100718).xml pasa lo mismo en el contrato hay una sola potencia y en el XML 05 vienen 2 informadas, el contrato es COM/00241

**Comment by bpesquero** [comment]
Si, esto ya nos pasaba con la real en unión fenosa. Cuando el contrato tiene DH nosotros informamos de una potencia y ellos nos devuelven dos. Las dos deben ser necesariamente iguales (habría que mirarlo) y por tanto, lo único que ha que hacer es despreciar la de periodo 2.

**Comment by JMunoz17** [comment]
Ya funciona correctamente, el código estaba añadido en los C1_05 Y C2_05, pero no para el A3_05.

**Comment by bpesquero** [comment]
comprobado y ok
