### ISSUE TITLE
Validacion de la potencia en funcion de la tarifa

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#2]
La potencia ha de validarse en función del máximo de las potencias para las tarifas 3.0 y 3.1

Ejemplo:

Potencia 1-2-15  se validaría para una 3.0 como potencia minima > 15 max(1,2,15)

**Comment by bpesquero** [comment]
No está solucionado. Sigue haciendolo para la suma. Además cada vez que se cambia la tarifa debería o borrar los campos de potencia, o volver a validarlos

**Comment by PKFEric** [comment]
PROBAR-> AÑADIDO EL EJEMPLO

**Comment by bpesquero** [comment]
Probado y ok
