### ISSUE TITLE
error carga c1 paso 011

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#201]
Nos da error la carga del C1_011, se trata de aceptación a la comercializadora saliente. Creo que no lo tenemos programado en NAv.
Lo comentamos para ver si vale la pena programarlo.

**Comment by JMunoz17** [comment]
Hemos programado en NAV la carga del C1_11 y del C2_11 para rellenar la fecha de baja prevista (nuevo campo) en el contrato.

**Comment by bpesquero** [comment]
Probado y ok
