### ISSUE TITLE
error tipo de identificador

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#206]
El tipo de identificador se rellena automáticamente con en función de que se trate de una persona física o jurídica, pero no se ha actualizado a los nuevos valores que tiene ahora esta tabla, así que lo tenemos que cambiar a mano.

**Comment by JMunoz17** [comment]
Los nuevos valores para el campo tipo de identificador son: NIF|N.I.V.A|Otro|Pasaporte|NIE. En caso de que sea persona física se le asigna tipo de identificador NIF, pero para persona jurídica antes se le asignaba CIF pero ese valor ya no esta disponible, cual le asignamos?

**Comment by bpesquero** [comment]
N.I.V.A --NV

**Comment by bpesquero** [comment]
Hay qeu cambiarlo tanto en cliente, como en cliente saliente como en nuevo titular, para que salga bien en todos los sitios

**Comment by JMunoz17** [comment]
Solucionado, hemos pasado un proceso que rellena el campo tipo persona y el campo tipo identificador (este con los valores nuevos) en los casos en los que sea necesario.

**Comment by bpesquero** [comment]
comprobado y ok
