### ISSUE TITLE
Modificar textos web cambio de contratos

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#21]
Modificar los textos que aparecen las pantallas de cambio de potencia, cambio de titular,... por los enviados a Eric

**Comment by bpesquero** [comment]
Probar por Belén

**Comment by bpesquero** [comment]
En el cambio de titular no está bien, tiene que poner sólo "Quiero cambiar el titular del contrato:", la frase "Selecciona a continuación el contrato del que desea cambiar el titular:" sobra. Además en vez de "Adjunte el titulo (contrato de compra, alquiler o similar) que lo acredite." hay que poner "Adjunta el titulo(contrato de compra, alquiler o similar) que acredite la titularidad."
En el cambio de pagador yo quitaría el texto "CONTRATO" y subiría la caja con el desplegable a continuación de la frase de quiero cambiar el pagador del contrato:
En el cambio de cuenta bancaria lo mismo, el deplegaba de contrato debe estar inmediatamente a continuación de "Quiero cambiar la cuenta bancaria del contrato:". Hay que quitar el texto "CONTRATO"
En vez de "Indica, por favor, el código IBAN de la cuenta bancaria en la que desea domiciliar los recibos a partir de ahora así como el contrato afectado." hay qeu poner "El IBAN de la cuenta bancaria donde quiero domiciliar mis pagos es:". Hay que quitar el texto "IBAN".
En la frase  "Quiero cambiar la cuenta bancaria del contrato:" hay una errata pone  "Quiero cambiar a cuenta bancaria del contrato:"
En el cambio de potencia igual, hay q ue poner el desplegable de contrato a continuación de "Quiero hacer un cambio de potencia del contrato:" y quitar el texto "CONTRATO"

**Comment by PKFEric** [comment]
CORREGIDO-> EN CUANTO SUBA LA WEB PROBAR.

**Comment by PKFEric** [comment]
WEB SUBIDA->PROBAR

**Comment by bpesquero** [comment]
Porbado y ok
