### ISSUE TITLE
Error carga peajes

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#212]
AL generar dos facturas de venta de energyda el siguiente error. Lo miramos y no encontramos ningún problema de fechas

Ya existe una factura dentro de estas fechas FV/201701346.--> COM/00120
Ya existe una factura dentro de estas fechas FV/201701347.--> COM/00125

**Comment by PKFEric** [comment]
Hemos borrado las facturas y las hemos vuelto a generar y no ha dado ningun error. El unico error lo daba si ya estaban generadas y se intentaba volver a gernerarlas.

Estan en borradores.
