### ISSUE TITLE
Error al cargar F1

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#214]
Al cargar el F1 del contrato COM/00273 , da error de No hay datos de Pci. El fichero lo carga, pero escribe en el log.
Se trata de un contrato con DHS y por tanto término de potencia en 1 periodo y término de energía en 3.

**Comment by jorgereal** [comment]
Ese error se debe a un control en la creación de la factura de compra, no existen precios de contrato para el COM/00273

**Comment by bpesquero** [comment]
Perdon, entendia que era por un problema de potencias, no me he dado cuenta de lo de los precios
