### ISSUE TITLE
Error carga C2_02 de rechazo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#215]
Al cargar el fichero C2_02 de rechazo del COM/00285 da el siguiente error
No existe el/la Valor Ocsum.   Campos y valores identificativos:  Nº tabla='027',Valor campo='03'  Nº tabla: 027, Valor campo: 03
Envío por mail el fichero

**Comment by jorgereal** [comment]
Había un error en los valores Ocsum cargados en la tabla, se ha corregido y se ha procesado el fichero correctamente.

**Comment by bpesquero** [comment]
ok
