### ISSUE TITLE
prorrata IVA

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#217]
He probado en PRE y la facutra me sale con IVA deducible de 0, cuando tenía una prorrata del 50%.
Es la factura FCR/20171093

**Comment by PKFEric** [comment]
Ya hemos modificado el proceso de la prorrata, queda pendiente de probar en PRE.

**Comment by bpesquero** [comment]
probado y ok. Avisadnos cuando esté en producción

**Comment by PKFEric** [comment]
Ya estan cargados los objetos en produccion, es necesario configurar las cuentas y los libros de registro en la configuracion de compras, sino dara error al registrar cualquier factura.
