### ISSUE TITLE
Error importación A3 de CIDE

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#219]
Mando detalle por mail

**Comment by JMunoz17** [comment]
Para los A3_05:
Para el contrato con CUPS ES0300000000507048WA0F y tarifa ATR 006 ya está solucionado el problema, para el CUPS ES0300000000504408WP0F y tarifa ATR 004 el problema es que el xml viene informado con dos potencias y el contrato tiene 3 potencias, lo cual no es posible para esta tarifa.
Para el A3_02 de rechazo ya está solucionado el problema.

**Comment by bpesquero** [comment]
probado y ok
