### ISSUE TITLE
error carga ficheros F1

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#220]
Al cargar dos ficheros F1 dan el siguiente error. Envío los ficheros por mail
Log medidas y facturas
Ruta fichero
Error/Aviso
Fecha-Hora
F1_0300_201700020420_27074072.xml
El atributo requerido <AgenteSolicitante> no coincide con el atributo <>.
20/07/2017
F1_0300_201700020421_27074073.xml
El atributo requerido <AgenteSolicitante> no coincide con el atributo <>.
20/07/2017

**Comment by JMunoz17** [comment]
Solucionados ambos. En el caso del F1_0300_201700020420_27074072.xml hemos tenido que editarlo y poner los importes en positivo ya que venían en negativo y el xml nos indica que se trata de una factura normal (tipo factura = N), por lo que los importes no pueden estar en negativo.

**Comment by bpesquero** [comment]
La factura tipo N negativa es un abono
Además, hay que considerar 2 tipos de factura más, la A, que llevando importe positivo es un abono, y la factura R que anula y hace una nueva factura de otro importe.

En el caso de la factura N no se informa en el fichero F de la factura a la que anula, así que se indicará en en log.
En el caso de facturas tipo G o C, no se cargarán y escribirá en log.

Por otra parte, no se localizan los conceptos facturados porque en la tabla están cargados como enteros y en el fichero F se informan como campos de texto de dos caracteres, con un "0" delante para el caso de números de 1 dígito.
