### ISSUE TITLE
Otro error F1

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#222]
al cargar de "Error de fecha". Reportado por mail

**Comment by JMunoz17** [comment]
SCTDE_F1_01_0022_0587_20170714091900142_(549104477)_2 (002).xml

En esta factura no viene la parte de medida, no tenemos contemplados F que vengan sin medidas. Da error de fecha porque compara las fechas de peaje y medida, dando error al estar vacias las de medida. Tenemos que contemplar ficheros F que vengan sin medidas?

**Comment by bpesquero** [comment]
No, todos tienen que ir acompañados de su cierre
