### ISSUE TITLE
Error carga fichero A3 20DH

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#223]
No nos carga un fichero de activación de A3 de la tarifa 20DH porque están las dos potencias informadas.  ESto hay que cambiarlo en todos los procesos, ya sabéis que hay distribuidores que informan las dos potencias.
ES0022000004001586VX1P (COM/00225).
EL fichero está en \\NI\Esios\OCSUM PRE\Importados

**Comment by PKFEric** [comment]
El error que daba al importar era que existia diferencia entre la Tarifa ATR o integal 011 con 004 que es la que venia en el XML del paso 05 del A3.

Hemos cambiado el valor del contrato, y lo hemos puesto como 004 y se ha importado y tramitado correctamente.

**Comment by bpesquero** [comment]
ok
