### ISSUE TITLE
nº  solicitud ocsum

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#224]
EL nº de solicitud deberia aumentar despues de un rechazo.

**Comment by PKFEric** [comment]
Esto se traduciria en que cada vez que se envia un paso 01 aumenta la solicitud. Ya esta modificado. en PRE

**Comment by bpesquero** [comment]
Qué ocurre si hago un paso 01 y no  se puede cargar en el stma del distribuidor y tengo que volver a hacer otro, Aumenta el nº de solicitud? no debería hacerlo. Unicamente debería aumentar si el nº de solicitud tiene un rechazo.

**Comment by PKFEric** [comment]
Lo hemos modificado para que se incremente en el caso en el que el paso _01 se encuentre en estado Rechazado.

Se ha modificado para los M1_01, C1_01, A3_01, C2_01 y B1_01

**Comment by bpesquero** [comment]
probado y ok
