### ISSUE TITLE
error SII factura de venta

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#225]
Me da error al enviar una factura de venta (C/20171000). dice "Las operaciones podrán tener parte sujeta y parte no sujeta. Por tanto, puede aparecer solo un bloque o ambos, pero al menos debe aparecer uno (Sujeta y/o No sujeta)"

Se trata de una factura de comercialización

**Comment by PKFEric** [comment]
Te lo he vuelto a regenerar, por lo que parecia no habia movimientos en las lineas para ese documento,algo extraño la verdad, he vuelto a lanzar el proceso de generacion de Documentos SII para esa factura y ya se han generado las lineas correspondientes.

Mira a ver si ahora ya entra bien, desde luego el XML tiene buena  pinta.

**Comment by bpesquero** [comment]
ESta está bien, pero ahora pasa lo mismo con esta otra C/20171010, también de comercialización.

**Comment by PKFEric** [comment]
Ya tienes la factura regenerada, voy a revisar el proceso.
