### ISSUE TITLE
informar de dos potencias en tarifa 20DH

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#228]
Según conversación de hace unos días, habría que dar la opción para cada distribuidor, de en los ficheros de solicitud informar de 1 o de 2 potencias en los casos de las tarifas 20DH y 21DH

**Comment by JMunoz17** [comment]
Solucionado. 
Si el contrato tiene Tarifa 20DH o 21DH  y en la tabla de Ocsum Value (nº tabla = 001)  el registro correspondiente al CUPS de ese contrato tiene marcado el campo "Informar DH Dos Potencias", entonces a la hora de generar C2_01, M1_01 y A3_01 aparecerá informada también la potencia 2.

**Comment by bpesquero** [comment]
Habría que hacer lo mismo para los M

**Comment by bpesquero** [comment]
Perdón, no me di cuenta de que estaba el M

**Comment by bpesquero** [comment]
Por favor, cambiar el nombre del campo en la tabla de distribuidores. No puede llamarse "distirbuidor unión Fenosa". Es cierto que el unico que lo ha pedido hasta la fecha es unión fenosa, pero pueden ser otros.
El nombre del campo debe indicar lo que hace, debe ser algo así como "informar 2 periodos DH"

Gracias

**Comment by bpesquero** [comment]
probado y ok

**Comment by bpesquero** [comment]
Hemos marcado el check en otro distirbuidor y al hacerlo  no ha completado las dos potencias.
