### ISSUE TITLE
Error impresión factura

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#236]
Al imprimir la factura, en el pdf, cuando hay depósito de garantía, tanto en el resumen con el reverso en el detalle sale mal "garantía", en vez de "í" (i con tilde) aparece "¡" (signo de admiración)

**Comment by jorgereal** [comment]
Había un error en la tabla de valores OCSUM, se ha corregido y se ha pasado un proceso para corregir la descripción de las líneas de facturas de compra y venta con el carácter erróneo.

**Comment by bpesquero** [comment]
Probado y ok
