### ISSUE TITLE
cambio de estado de contrato

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#237]
Nos ha pasado con un par de contratos, en el proceso M, que cargamos el paso de aceptación de aceptación ( paso 02) ,por modificaciones contractuales técnicas, que no cambian el estado a “aceptado”, sino que siguen quedándose en “Tramitación ATR”, una vez procesados. En concreto ha pasado con los COM/00270 y COM/00284.

**Comment by PKFEric** [comment]
esta quedo resuelta en el Redmine
