### ISSUE TITLE
Gestion de Cobros HECEN - 17/09/2018

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#242]

**Comment by PKFEric** [comment]
pasar proceso para rellenar mail al de belen, para que todos los mails vayan contra ella

**Comment by PKFEric** [comment]
Ya he pasado el proceso ahora todos los clientes de HECEN PRE tienen relleno el correo electronico con el de belen.

**Comment by PKFEric** [comment]
la paso a on hold hasta que este probado

**Comment by bpesquero** [comment]
Paso comentarios después de hacer algunas pruebas:

1.- Sería posible ver en la pantalla de gestión de cobros el nº de contrato?
2.- En el listado de tareas pendientes aparecen como pendientes de envío de mail de 20 días todos los movimientos de devoluciones, sólo deberían aparecer los de por caja, y el resto deberían aparecer como de devoluciones.
3.- Cuando se pasa el proceso de marcar envío carta 20 días se marcan también los de domiciliación
4.- Deberíamos habilitar un proceso para poder envíar cartas de devoluciones ya cargadas antes de que se implementase esta funcionalidad
5.- Envío mail 20 días
    5.1- no se genera la carta
    5.2 - en el mail sale mal el logo
    5.3.- sal el texto de envío de carga aunque sea una devolución. Como he comentado antes, realmente 
           las devoluciones no tendrían que estar incluidas en este proceso
6.- Envíar mail aviso 1
    6.1- No general la carta
    6.2- El mail no tiene asunto
    6.3- Cuando se relacionan las fechas de las facturas impagadas se pone todo el rato la fecha de la 
           factura para la que se está haciendo el envío. Ejemplo movimiento DEV_H/2017051579. Este CUPS 
            tiene 9 facturas impagadas, tendrían que aparecer las fechas de registro de las 9 facturas; sin 
            embargo, aparece 9 veces la fecha de la factura correspondiente a la DEV que está generando la 
            carta. Las facturas que tiene impagadas son H/2016067948, H/2017001942, H/2017008600, 
            H/2017015908, H/2017022783, H/2017030147, H/2017037244, H/2017044306, H/2017051579.

    6.4- El importe total de la deuda reclamada no es correcta, aparece unicamente el importe de la devolución que da objeto a la reclamación, pero no incluye el del resto de las facturas impagadas. Mismo ejemplo.
7.- Mail aviso 2
    7.1- mismo problema con las fechas de las facturas que en el mail aviso 1
    7.2- mismo problema con el total de la deuda que en el mail aviso 1
    7.3-fecha corte incorrecta, aparece la fecha de envio del primer aviso, en vez de la fecha de corte 
        prevista
8.- mail 20 días para contrato con más de 10 kW de potencia--> no aparece el nombre del titular. Ejemplo DEV_H/2017053510
9.- Mail aviso 1 para contrato con más de 10 kW de potencia-->
    9.1- Sale el modelo de carta de menos de 10 kW
    9.2-No tiene asunto el mail
    9.3- No aparece el nombre 
    9.4 - No acumula el importe de todos los impagos
10.- Fecha de recepción de mail aviso 1 para cotnrato con más de 10 kW de potencia--> al rellenarla no calcula bien la fecha de corte. Le suma 2 meses cuando en este caso tienen que ser 2 días
11.- Marcar mail aviso 2 para contrato con más de 10 kW de potencia,--> lo hace mal, hace el cálculo como si se tratase de un contrato de menos de 10 kW
12.- Envío mail aviso 2 para contrato de más de 10 kW
   12.1 - Sale el modelo de carta de menos de 10 kW
   12.2- No aparece el nombre
   12.3-No acumula el importe total de todos los impagos
13.- Habría que añadir un campo con la fecha de recepción del envío 2
14.- Generación de cartas en roles
   14.1-Tarda casi 20 minutos en hacer 7 cartas
   14.2-Yo había hecho las pruebas con los documentos DEV_H/2017051579 y DEV_H/2017053510 y no se han generado las cartas.
   14.3- Se han generado una carta del documento DEV_H/2015020701. No sé en qué situación estaba 
    pero por lo que veo en gestión de cobros se deberián haber generado 2. La que se ha generado no se 
    puede abrir, dice que el documento está dañado
  14.4.- Se han generado 6 cartas del documento DEV_H/2017043070. Curiosamente tiene la carta de norma 19 y la de 20 días, Parece que igual hicisteis pruebas y pusisteis fecha  a las dos. Como no sé exactamente en qué situación estaba no puedo valorarlo.

**Comment by jorgereal** [comment]
Hemos revisado todos los puntos solicitados, corrigiendo los errores y realizando pruebas para cada caso.

Algunas de las pruebas realizadas con resultados correctos:

20DIAS | <10 KW
H/2015000990 | HECEN/01035
H/2015008955 | HECEN/01035
H/2015000299 | HECEN/00237
H/2015006332 | HECEN/07396

20DIAS | >10 KW
H/2015024034 | HECEN/00242
H/2016010899 | HECEN/00242
H/2016010927 | HECEN/00242
H/2016021832 | HECEN/00242
H/2016021851 | HECEN/00242
H/2016033527 | HECEN/00242
H/2016033535 | HECEN/00242
H/2016046590 | HECEN/00242
H/2016046599 | HECEN/00242
H/2016052168 | HECEN/00242
H/2016059500 | HECEN/00242
H/2016059770 | HECEN/00242
H/2016065969 | HECEN/00242

N19 | <10 KW
DEV_H/2017053510 | HECEN/04739
DEV_H/2017051579 | HECEN/02483


N19 | >10 KW
DEV_H/2017053510 | HECEN/04739
DEV_H/2017020939 | HECEN/00360
DEV_H/2016034081 | HECEN/00360

Se ha comprobado que se envían los mails y se generan las cartas tanto para titular como pagador siempre que sean distintos.
También que todos los datos (importes, fechas, datos de contacto...) sean correctos.

Después de dos días de testeos sobre la BBDD de PRE creemos que ya está todo corregido.

Si encontráis algún otro error comunicádnoslo.

**Comment by bpesquero** [comment]
Hemos retomado las pruebas y encontramos lo siguiente:

1.- Habéis añadido en gestión de cobros el contrato pero cuando cargo nuevas devoluciones no se carga el valor del contrato
2.- Cargo una devolución nueva y no sale el mail
3.- Envío mail 20 días
3.1 - en el mail sale mal el logo (gmail)
3.2.- falta el nombre
4.-Carta 20 días
4.1-Mala calidad del logo
4.2-Falta nombre
4.3-Falta "." detrás de EUR
4.4-Aparece la dirección y nombre del titular en vez de la del pagador
4.5-Sale la de transferencia independientemente que sea por transferencia o domiciliación
5.-Mal aviso 1
5.1 - en el mail sale mal el logo (gmail)
5.2.- falta el nombre
5.3-Para + de 10 kW hay una errata pone "ademís"
6.-Carta aviso 1
6.1-Mala calidad del logo
6.2-Falta nombre
6.3-Para menos de 10 kW hace las dos cartas con el nombre y dirección de titular, en vez de una al titular y otra al pagador
7.-Mail aviso 2
7.1 - en el mail sale mal el logo (gmail)
7.2.- falta el nombre
8.-Carta aviso 2
8.1-Mala calidad del logo
8.2-Falta nombre
8.3-Para menos de 10 kW hace las dos cartas con el nombre y dirección de titular, en vez de una al titular y otra al pagador
9.- Habría que añadir un campo con la fecha de recepción del envío 2
10.- Queremos cambiar los nombres tanto en la pantalla de tareas pendientes como en la de gestión de cobros para que sean "entendibles" por la persona que lo va a realizar, serían las siguientes:
-Vía amistosa devolución de recibos - email
-Vía amistosa transferencia - email
-Vía amistosa - carta
-Reclamación formal de deuda domiciliación - email
-Reclamación formal de deuda transferencia - email
-Reclamación formal de deuda  - carta
-Resolución de contrato - email
-Resolución de contrato - carta

11.- Queremos hacer alguna modificación en los textos de las cartas y los mails, cuál es la mejor forma para transmitiroslo? Si tenéis una plantilla quizá la pueda cambiar directamente

12.- Queremos cambiar los asuntos de los mensajes. Serían
-aviso 0--> Incidencia en el pago
-aviso 1 más de 10kW-->Aviso de baja de contrato y corte de suministro de electricidad
-aviso1 no más de 10 kW-->Aviso de baja de contrato de electricidad
-aviso 2 más de 10kW-->Confirmación de baja de contrato de electricidad
-aviso 2 no más de 10 kW-->Aviso de corte de suministro de electricidad


Gracias

**Comment by bpesquero** [comment]
Algunos temas adicionales:


-Ahora mismo sólo se están agrupando las facturas, es decir, se están informando de todas las facturas impagadas, en la comunicación 1 y 2 para menos de 10 kW. La idea es que en todas las comunicaciones se incluyan todos los impagos que cumplan con los criterios de envío de la comunicación. Voy a cambiar los formatos de las comunicaciones para indicaros de qué forma informarlos en cada comunicación
-En los casos en que ya se están agrupando (comunicación 1 y 2 de menos de 10 kW) en la tabla sólo se queda marcada la fecha desde el impago que se ha lanzado. Me explico, tengo dos impagos para un cliente y marco sólo uno de ellos para el envío de carta1. Envía la carta e incluye el importe de los dos impagos. En gestión de cobros sólo se marca como enviado desde el que se ha lanzado el proceso. En realidad habría que marcar todos los impagos tenidos en cuenta en la carta, que son todos los de ese cliente que cumplan con el criterio de fechas para la carta que se esté enviando.
-En el campo "situación de recobro" quiero añadir dos valores más: "Gestión Externa" y "No gestionar"
-En todos los procesos de envío de cartas, marcar los impagos para envíos de carta y demás, hay que excluir los impagos que tomen esos dos valores "gestión externa" y "No gestionar".

**Comment by bpesquero** [comment]
Envio por mail documento con el texto modificado de las comunicaciones.

**Comment by bpesquero** [comment]
Resultado de las pruebas. He hecho todo el ciclo con un cliente con domiciliación y de menos de 10 kW. Prefiero que se solucionen antes estas incidencias que se van a repetir en todos los casos, para después seguir probando con todos los tipos de clientes.

CLIENTE DOMICILIADO MENOS DE 10 kW (CL03787 - HECEN/07209 -H/2017055607)

1.- Mail amistoso-el importe total no coincide con el total de la deuda del cliente, no se considera el movimiento DEV-14375200001
2.- Carta amistosa-el importe total no coincide con el total de la deuda del cliente, no se considera el movimiento DEV-14375200001
3.- Mail reclamación formal de deuda
3.1- El importe del mail es incorrecto, no se considera el movimiento DEV-14375200001
3.2-En el documento que ha generado el mail marca la fecha correcto de envío de reclamación formal de deuda, pero en el resto de movimientos incluidos en vez de rellenar ahí la fecha rellena la de fecha envío vía amistosa transferencia. Con excepción del documento DEV-14375200001 que no rellena nada porque no lo está considerando

![image](https://user-images.githubusercontent.com/20299071/41035228-4d90feb6-698c-11e8-987e-bd5e2af14c79.png)

4 Carta reclamación formal de deuda
4.1-el importe es incorrecto por el mismo motivo
4.2 Las etiquetas en la pantalla de gestión de cobros de ruta mail pagador reclamación formal de deuda y ruta mail titular reclamación formal de deuda son incorrectas, debe ser ruta _carta_ pagador....
5.- Mail aviso de corte
5.1-el importe está mal
5.2 Si al rellenar la fecha de recepción de la carta de reclamación formal de deuda sólo se rellena en el documento que está generando la situación y no en los anteriores, la fecha de envío del mail sólo se rellena en ese. ¿Sería posible que al rellenar la fecha de recepción se rellenen todos los anteriores siempre que la tengan vacía?
6.- CArta de aviso de cortes
6.1 El importe es incorrecto
6.2 Al rellenar la ruta de carta machaca las de los registros anteriores aunque ya tuvieran una ruta, yo creo que ha que rellenarla sólo si está vacío si no se deja la anterior, porque así perdemos el htco de lo que se ha hecho. Esto debe pasar también en los casos anteriores, pero sólo lo he probado en este. Esto debería ser así con la fecha y con las rutas, tiene que rellenar las anteriores siempre que estén vacías.
6.3 Para sacar el mail he marcado a mano el check de marcado envío resolución, sin embargo no cumplía el criterio de fechas, y no ha dado ningún error. Creo que si no cumple el criterio de fechas (en este caso 15 días antes de la fecha de corte previst) no debería sacarlo para evitar la posibilidad de marcar por error y que salga
6.4-FEcha de recepción--> lo mismo que en el caso del aviso de reclamación formal de deuda, ver la posiblidad de rellenar automáticamente.
6.5 Las etiquetas Ruta mail pagador resolución de contrato y ruta mail titular pagador del contrato son incorrectas debería poner ruta "carta" pagador....

**Comment by JMunoz17** [comment]
Contestado vía mail.

**Comment by bpesquero** [comment]
He vuelto a hacer pruebas para devoluciones de menos de 10 kW
He cogido los siguientes datos para probar que todo se hace bien


pagador | factura | contrato | titular | fecha devolución
-- | -- | -- | -- | --
CL06302 | H/2017053827 | HECEN/05122 | CL06290 | 15/08/2017
CL06302 | H/2017046462 | HECEN/05227 | CL06290 | 15/08/2017
CL06302 | H/2017053912 | HECEN/05227 | CL06290 | 15/09/2017
CL06302 | H/2017053765 | HECEN/05046 | CL06290 | 15/09/2017
CL05526 | H/2017046463 | HECEN/05228 | CL05526 | 15/09/2017


He cargado primero las de 15/08/2017 y he visto lo siguiente, tenía que haber unido toda la deuda del CUPS y pagador, las dos devoluciones eran del mismo CUPS y pagador, pero de diferentes contratos, y en cada uno ha enviado como importe total el de su contrato. La agregación de deuda tiene que ser por CUPS y pagador. Sólo tiene sentido que salgan los importes que salen si es que el CUPS se coge de la factura en vez de del contrato, yo lo que he hecho es cambiarlo en el contrato.
En el mail del documento H/2017053827 aparecen 191,31 euros, que es la deuda total de su contrato, y el del documento H/2017046462 aparecen 47,96, ya que el contrato no tiene más deuda pendiente. Insisto en que debería haber agrupado por CUPS y pagador.

A continuación cargo la devoluciones de 15/09/2017 y veo la misma situación, vuelve a agrupar por contrato, no por CUPS y pagador. Además, en la devolución correspondiente al contrato HECEN/05227 en la que si agrupa con la devolución de 15/08/2017 del mismo contrato machaca la ruta de la carta que tenía antes con la nueva. Esta incidencia ya apareció en las pruebas anteriores.
Los mails salen bien, pero en las cartas el importe no es correcto. En el modelo de carta primero se indica el importe del efecto devuelto que origina la comunicación y a continuación el importe total agregado. Pues bien, cuando el contrato (insisto que realmente tendría que ser la combinación de CUPS&pagador) tiene otras deudas anteriores, el importe que muestra es el del primer documento que integra la deuda, y luego el total.
A continuación marco todos para hacer al reclamación formal de deuda. Los mails salen bien con la salvedad de que sigue agrupando por contrato en vez de por CUPS y pagador.
No ha salido la carta correspondiente al documento H/2017046463 del contrato HECEN/05228.
En este caso no he podido comprobar existe un documento anterior que ya tenga una carta si se machaca la ruta y la fecha de envío y recepción o no. 
He rellenado las fechas de recepción y cuando intento marcar para el envío de resolución de contrato me da un error de no se puede hacer el cálculo para 0D.. si lo hago a mano me da el error de que los registros no cumplen los requisitos de fechas. DEspués de dos horas lo he vuelto a intentar y me ha dejado...
He enviado los mails y he generado las cartas. Mismo problema de agrupar por contrato en vez de CUPS y pagador. Sale la carta correspondiente al envío1 de reclamación formal de deuda que no había salido antes....
Del contato HECEN/05227 marco sólo el documento DEV_H/2017046462 y hago el envio. En el otro documento del mismo contrato, el correspondiente al documento DEV_H/2017053912 marca la ruta de la carta pero no la fecha de envio.
En el correspondiente al contrato HECEN/05228 a la factura H/2017046463, que es el que no había sacado la primera carta, deja marcada la fecha de envío pero no la ruta porque no genera la carta.

Todas la cartas están en Ni por si las queréis ver.




--

**Comment by bpesquero** [comment]
Finalmente se decide que la deuda se envíe agregada por CUPS al titular y al pagador actual sin tener en cuenta si ese CUPS tiene deuda anterior que corresponde a otro pagador o titular.

**Comment by JMunoz17** [comment]
Hemos corregido el código para que al realizar la comunicación utilice el movimiento con mayor fecha de registro como el que origina la comunicación para que el primer importe que muestra en las comunicaciones no sea de un documento anterior (Este problema pasaba al generar las cartas y en algunos casos (en función de los movimientos que estuviesen marcados) en el envío de mails). 

El problema que había respecto a que en algún caso machacaba la ruta era un error derivado de esto, por lo que ya no debe de machacar la ruta en ninguna situación (salvo que el importe con mayor fecha de registro (el que origina la comunicación) tenga la ruta rellena (esta circunstancia entiendo que no se debe producir)).

Respecto al error que me indicas de "no se puede hacer el calculo para 0D..", no he conseguido replicarlo. Por el momento en el que dices que tiene lugar lo único que veo que puede provocar un fallo así es que no este relleno el campo de fecha prevista de corte, aunque por lo que pones entiendo que si lo tenías relleno. Si te vuelve a suceder nos dices.

He estado haciendo pruebas con los mismos movimientos que indicas y creo que salen bien teniendo en cuenta que lo que hacemos es a partir de un movimiento origen (el cual tiene relleno el CUPS) buscamos por un lado todos los movimientos que cumplan las condiciones y tengan asociado ese CUPS, y por otro lado buscamos los contratos que tengan asignado ese CUPS y para cada uno de esos contratos buscamos los movimientos que cumplan las condiciones y que tengan el CUPS vacío (para poder agrupar los movimientos de SALDO_INICIAL y DEV* que no tienen relleno el campo CUPS).

Con cualquier cosa nos decís.

**Comment by bpesquero** [comment]
Pruebas hechas y todo ok.
Cuestiones adicionales:

-la diferenciación que se venía haciendo hasta el momento con clientes de menos de 10 kW de potencia y más de 10 kW deberia ser en realidad: clientes personas físicas con menos de 10 kW de potencia y por otra parte clientes personas jurídicas y clientes personas físicas con no menos de 10 kW de potencia

-al campo situación de recobro he visto que habéis añadido valores nuevos, perfecto. sería posible que los movimientos que no vengan de devoluciones también "nazcan" con el estado "pendiente"

-en este sentido necesitamos un cambio más. Necesitaremos una marca a nivel de contrato que sea un booleano "gestión externa de contrato" de tal forma que todo movimiento de cliente que aparezca(devolución, factura,...) nazca en estado "gestión externa"

-en el momento de subir a producción (tengo que negociar la fecha con la oficina de Guadalajara) habrá que pasar todos los movimientos de cliente a estado no gestionar

-hay una errata (cometida por nuestra parte) en la notificación de reclamación formal de deuda de clientes de más de 10 kW. Donde dice "compañía suministradora" debería decir "compañía distribuidora"

**Comment by JMunoz17** [comment]
Hemos realizado las modificaciones indicadas. El campo creado en los contratos lo he sacado en la sección "Otros", si lo queréis en otro sitio me decís. Por confirmar, entiendo que si importamos una devolución asociada a un contrato que tiene el check de gestión externa marcado no se debe mandar el mail no?

**Comment by bpesquero** [comment]
Efectivamente, si se importa una devolución no se envía mail. En términos generales los movimientos de contratos con esta marca no deben "entrar" en ninguno de los procesos (marcado para envío, envío, ...)

Revisamos las modificaciones y os decimos.

**Comment by bpesquero** [comment]
He hecho las pruebas de las nuevas modificaciones:

-diferenciación de clientes en función de persona física o jurídica-->OK
-los movimientos de facturas por transferencia nacen con estado pendiente--> OK
-marca gestión externa de contrato-->ok. Sería posible cambiar la etiqueta y poner "gestión externa de deuda", me lié (sory)
-errata-->OK
-La subida a producción está prevista para el día 17 de septiembre, ahora mismo está casi todo el mundo de vacaciones. Lo dejamos pendiente para esa fecha. Lo retomamos las primeras semanas de septiembre para coordinar la subida a producción.

**Comment by JMunoz17** [comment]
Ok, ya esta cambiado el nombre.

**Comment by bpesquero** [comment]
He revisado la subida a producción y tengo las siguientes cuestiones

1.- Hay una serie de movimientos con situación de recobro pendiente, por qué?
2.- AL hacer las pruebas he visto que en el mail que recibo pone Pruebas Impagos HECEN , esto está modificado en producción
3.- He visto que se han cambiado los asuntos de mensajes en Geo. AL subir a producción lo de HECEN ha podido afectar a Geo?

**Comment by JMunoz17** [comment]
-Son movimientos que se han generado después de pasar el proceso (lo pasamos ayer por la tarde antes de enviarte el mail). 

-Esto se puede configurar en la información de empresa. Actualmente en producción está puesto Impagos HECEN.

-En su día entendí de manera errónea que tenía que cambiar también los asuntos en GEO. He vuelto a poner los que tenían. 
     - Impago (devoluciones): "Impago". 
     - Aviso 1 (Reclamación formal de deuda)  y Aviso 2 (Resolución de contrato): "Aviso baja unilateral del contrato".

**Comment by bpesquero** [comment]
- Creo que son movimientos anteriores
- Ok. Lo miro
- Efectiamente estaba bien cambiado, sólo quería asegurarme que no afectaba al resto de cosas. Lo siento por el trabajo originado, pero efectivamente hay que dejar los mismos que en HECEN

**Comment by JMunoz17** [comment]
- Todos los movimientos que tienen situación recobro pendiente son pagos, que aunque algunos tienen fecha de registro anterior, tienen los últimos nº de movimiento. Si quieres, vuelvo a pasar el proceso y dejamos estos movimientos con situacion recobro no gestionar.

- Ok, lo he vuelto a modificar.

**Comment by bpesquero** [comment]
ok. Dejalo así. Lo vemos.

Gracias

**Comment by bpesquero** [comment]
En la pantalla de resumen de gestión de impagos, no deberían tenerse en cuenta los movimientos que estén en estado no gestionar, ni los de gestión externa.
Ahora mismo aparecen más de 3000 pendientes de email de transferencia y realmente todos están en no gestionar

**Comment by JMunoz17** [comment]
Lo he modificado y subido a PROD.

**Comment by JMunoz17** [comment]
Hemos añadido un control para que si el cliente no tiene el mail relleno no se envíe el email.

**Comment by bpesquero** [comment]
Hemos cargado las primeras devouciones. En la pantalla de cosas pendientes aparecen  pendientes 14 cartas.
AL lanzar el proceso desde roles (que por cierto cuelga del menú de Geo) no hace nada

**Comment by JMunoz17** [comment]
Al ir a mirarlo he visto que no estaba sacado el botón de generar las cartas, lo he sacado en Hidroeléctrica El Carmen Energ/Departamentos/Energy/Hidroelectrica el Carmen/Gestión de Cobros  

A que botón habíais dado?

Le he dado a generar cartas impagos, podéis verlas en la carpeta \\ni\esios\Mail Baja HECEN

**Comment by bpesquero** [comment]
Si, como os decía en la incidencia lo estábamos lanzando desde el menú de Geo y ese debía ser el pb, no?

Gracias!!!

**Comment by bpesquero** [comment]
Por error mío os dije que en todos los procesos de envío de cartas, marcar los impagos para envíos de carta y demás, hay que excluir los impagos que tomen esos dos valores "gestión externa" y "No gestionar".
Realmente no es exactamente así. Cuando en una carta se indica la deuda total o se hace referencia a toda la deuda pendiente, si que habría que incluir los movimientos de "gestión externa"
Particular urgencia tenemos con la carta de amistosa de domiciliación que estamos sacando ahora.

**Comment by JMunoz17** [comment]
Varias preguntas:
   - Esto afecta a las comunicaciones via email o solo a las cartas?
   - A la hora de tenerlos en cuenta en el apartado de las cartas, solo tenemos que tenerlo en cuenta a la hora de hacer referencia a la deuda total agregada? O tenemos que tenerlos en cuenta como cualquier otro movimiento, es decir, pueden ser el movimiento origen de una comunicación?

**Comment by bpesquero** [comment]
- afecta a cartas y emial. lo que ocurre que lo que ahora nos urge más son las cartas, ya que mails no enviamos todavía desde HECEN
-sólo a la hora de hacer referencia al total de la deuda, no pueden ser el origen de una comunicación

**Comment by JMunoz17** [comment]
Vale para incluirlo en los importes totales agregados no hay problema, queréis que los movimientos con gestión externa aparezcan en las pantallas de gestión de cobros?

**Comment by bpesquero** [comment]
Si, que aparezcan. Ya nos encargamos nosotros de filtrar cuando no queramos verlos.

**Comment by JMunoz17** [comment]
Ok, ahora mismo en la pantalla de tareas pendientes que aparece al abrir la empresa no se van a contabilizar los movimientos de gestión externa. Si queréis que se contabilicen me lo decís.

He subido las modificaciones a PRE, queréis probarlo allí primero o lo subo a PROD?

**Comment by bpesquero** [comment]
Subelo mejor directamente a PROD. Me avisas?

Gracias

**Comment by JMunoz17** [comment]
Ya esta subido, con cualquier cosa me dices.

**Comment by bpesquero** [comment]
¿cómo hacemos con las cartas que se imprimieron ayer que no estaba bien? ¿Cómo las puedo reimprimir?

**Comment by JMunoz17** [comment]
Solo hay que limpiar el valor del campo de la ruta de la carta en los movimientos (esto ya lo he hecho). Al darle a generar las cartas deberían volver a crearse. He eliminado los pdf que estaban mal de la carpeta (me los he guardado por si los necesitas). Iba a darle yo a generar, pero no tengo licencia, así que si podéis ejecutarlo.

**Comment by JMunoz17** [comment]
He conseguido licencia, ya las he generado. Se han generado muchas, las que teníais pendientes.

Las que decías que no se habían generado correctamente son alguna de las 14 que generamos el otro día? Si me puedes decir un caso para comprobarlo.

**Comment by bpesquero** [comment]
Queremos cambiar el texto de la comunicación amistosa, tanto email como carta, tanto devolución de remesa como transferencia

Donde dice

"Además, le informamos de que la deuda total con nuestra compañía asciende a x euros."

Poner

"Además, le informamos de que la deuda total con nuestra compañía para el punto de suministro de referencia asciende a x euros."

**Comment by JMunoz17** [comment]
Hemos modificado las comunicaciones y regenerado las cartas.
