### ISSUE TITLE
Carga F5D HECEN PRUEBAS

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#245]
Lanzada la carga de un fichero grande (350MB) por los apuntes de junio, la suma total de las medidas es correcta.

Sin embargo, 
- el Log me aparece vacío
- No ha habido ninguna carga en la tabla antigua y eso que cambiamos un par de contratos para que se facturara con medida horaria
- Hicimos unos cambios de titularidad en dos contratos a mitad del mes y la asignación de medidas está bien para el CUPS, pero no para los nuevos contratos. El 07405 pasa al 08490 el día 14 y el 01753 al 08491 y los segundos no tienen medidas asignadas.

**Comment by JMunoz17** [comment]
Si nos puedes indicar la ubicación y el nombre del fichero para probar a importarlo.

**Comment by fmsanudo** [comment]
Se procede a la carga desde mi equipo de tres ficheros grandes a ver cómo responde el sistema.
HECEN PRE

**Comment by JMunoz17** [comment]
Fernando la carga se realizó correctamente? En caso contrario si nos puedes indicar los ficheros que utilizaste para probarlo.

**Comment by bpesquero** [comment]
Hemos visto que sólo se carga un CUPS del fichero. Lo hace en la tabla  de medidas horarias antigua. En realidad este punto tiene modo de facturación indexado por tanto debería haberse cargado tanto en la antigua como en la nueva, y sólo lo ha hecho en la antigua. Además, el resto de puntos deberían haberse cargado en la nueva y no lo han hecho.

**Comment by fmsanudo** [comment]
Las cargas se realizan correctamente.
Ahora bien, la carga es mucho más ágil en los ficheros grandes cuando se parten en trozos más pequeños. Quizás sea debido a la utilización de algún bucle en la carga.
