### ISSUE TITLE
Error de carga F1

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#246]
En GeoAtlanter PRE
COM/00183
Detalles enviados por correo 
Error detallado
División por cero.  0 / 0

**Comment by fmsanudo** [comment]
Persistencia del error una vez solventado el error de división de resultado indeterminado:

«Cargo F1 si error, más que log de hueco de facturación, es obvio porque me falta cargar un F1 anterior que como es de formato antiguo no puedo cargar. Cuando genero la venta el único error que me da el log es el mismo de hueco de facturación, pero, en  cambio, no factura energia ni la de TE del F1 ni la perfilada. La única diferencia que hay respecto la BBDD de producción es que en este caso estoy forzando facturación de venta por el hueco.»

**Comment by PKFEric** [comment]
Dime que fechas has introducido para forzar la facturacion para este contrato.
