### ISSUE TITLE
Configuración Regional (muy poco importante)

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#247]
En los procesos de carga desde el Esios y la ejecución del Perfil Usuario los datos son incorrectos si no se ha cambiado anteriormente la configuración regional.

Como digo, es una mejora muy poco importante.

**Comment by JMunoz17** [comment]
Hemos probado a importar ficheros F5D cambiando el lenguaje del sistema operativo al Inglés, lo cual hace que Navision este en Inglés,  y se importan sin problemas.

La fecha y los valores decimales te los muestra en el formato correspondiente al Inglés, pero si vuelves a cambiar el idioma al Español estos datos previamente importados en Inglés se muestran con los formatos correspondientes al Español. 

Probablemente el problema sea que tienes el Excel y Navision en idiomas diferentes.

**Comment by fmsanudo** [comment]
Solución no satisfactoria

**Comment by bpesquero** [comment]
El problema es que el sistema operativo está configurado en español pero cambiando el "." y la "," de los separadores de miles y decimales. AL hacer la carga se carga mal. Esto lo hemos detectado en facturación al aparecer precios multiplicados por "1.000".

**Comment by JMunoz17** [comment]
Desde Navision no tenemos manera de identificar las personalizaciones de formato del equipo desde el que se ejecuta cada proceso. 

La única manera que tenemos de solucionar esto es modificar cada uno de los procesos de importación afectados, introduciendo un control que consista en que si el usuario es el de Fernando se interpreten las comas como puntos y viceversa a la hora de introducir los datos en NAV.  Si nos dais el OK nos ponemos con ello.

**Comment by bpesquero** [comment]
No me gusta la solución. Estoy pensando en dos cosas:
1-poner un menú al lanzar la carga en el que indiques si tu sepador decimal es el "." y la "," y así que el usuario lo ponga en función de su configuración. En vez de meterlo por código para un usuario concreto.
2-la segunda, adicional a la anterior, no para sustituirla, sería incluir en el log donde se controlan que los precios no son 0, un control de que los precios no sean superiores a 1000. Así se detectarían cargas anómalas.

¿qué os parece?

**Comment by JMunoz17** [comment]
Ok, nos parece correcto. 
Estos son los procesos de importación que se verían afectados:
  - F5D
  - P1D
  - ESIOS
  - Perfil Usuario

Se nos pasa alguno?

**Comment by bpesquero** [comment]
No. Muchas gracias

**Comment by JMunoz17** [comment]
Finalmente, para la importación de F5D y P1D no es necesario realizar modificaciones puesto que se importan de manera correcta independientemente de si tenemos el punto o la coma como separador decimal en nuestra configuración.

Hemos modificado el procesamiento de los ficheros de ESIOS y la importación de los perfiles finales, que eran los dos procesos donde se producía el fallo. Para que se use el punto como separador decimal solo hay que marcar el check que aparece al ejecutar estos procesos.

Hay otro check (Verificar descarga esios | Verificar perfiles) que si lo marcamos antes de lanzar el proceso nos escribirá en el log si se ha producido alguna carga anómala (valor >1000). Hemos usado el mismo formulario para ambos, esta sacado en el menú en Gestión de la Medida con el nombre Log Esios.

**Comment by fmsanudo** [comment]
Comprobado y correcto.
