### ISSUE TITLE
Problema fechas M1 con cambio de titular

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#248]
AL hacer un cambio de titular, la fecha de incio del contrato nuevo coincide con la fecha de fin del contrato antiguo. Se solapan un día. ejemplo: HECEN/01486 contrato viejo fecha final 01/12/17, HECEN/08587 contrato nuevo fecha inicial 01/12/17.
Sin embargo cuando es M1 de cambio de tarifa si lo hace bien. ejemplo: HECEN/04291 contrato viejo fecha final 30/11/17, HECEN/08589 contrato nuevo fecha inicial 01/12/17.

**Comment by jorgereal** [comment]
Se ha corregido el código de cambio de titular para que no se solapen las fechas de los contratos.

Subido a PRE y PRO.
