### ISSUE TITLE
Error facturación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#249]
Hemos detectado varios problemas al facturar al CUPS ES0021000005522364FS. Detallo lo que hemos ido haciendo:

1.- Hemos facturado el contrato y ha generado una factura de 06/11/2017 a 04/12/2017 y ha dado el siguiente log: La potencia facturada 14,72 del peaje en el periodo 1 es diferente de la potencia facturada 14,723.
2.- La factura no tenía energía pero no ha dado ningún error de energía.  Mirando en la tabla de medidas horarias se había perfilado correctamente, pero no se asocia al nº de factura de accecso. Entiendo que no ha saltado el log de energia porque al comparar la CCH con el cierre son iguales. Lo que no sé es por qué no ha metido la energía en la factura, parece que al hacer este control se sale.
3.- Borramos la factura de venta. Al hacer esto vemos que no se borraron las medidas perfiladas asociadas a la factura de venta, debería hacerlo.
4.- Marcamos en el contrato  la opción de permitir diferencia de potencia
5.- Volvemos a facturar y se genera de nuevo la factura de venta, esta vez con energía. En el log sale lo siguiente:

La potencia   facturada14,72del peaje en el periodo 1 es diferente de la potencia facturada   14,723.
La potencia facturada14,72del peaje en el   periodo 2 es diferente de la potencia facturada 14,723.
La potencia facturada14,72del peaje en el   periodo 3 es diferente de la potencia facturada 14,723.

6.- Aunque en el log no sale nade sobre la energia comprobamos que la energía facturada no coincide con el cierre. Vemos que en medidas horarias tenemos dos registros para cada hora, ya que al no haberse borrado la curva anterior, se vuelven a generar registros nuevos. Quizá antes de generar registros nuevos habría que verificar que no exista una curva perfilada previa. Los nuevos registros no se asocian al nº de factura de acceso (compra). Al perfilar, como tiene 2 registros para cada hora, realmente asigna en cada hora la mitad de la energía. Al sumar todos los registros horarios el resultado coincide con el cierre, por ese motivo no salta el log. Quizá habría que comprobar también el nº de registros, no sólo la suma de la energía. Al facturar la venta, considera un solo registro por hora, y por ese motivo la energía facturada no coincide con el cierre. Quizá debería haber otro control que comparara la energía realmente considerada en la factura con el cierre. 

7.- Adicionalmente se comprueba que la energía facturada no es exactamente la mitad, como correspondería al haber dos registros de cada hora. Al comparar las curvas perfiladas se observa en que los sábados y domingos no se aplica el mismo periodo a los registros horarios que se generaron al hacer la factura de venta 1 y al hacer la factura de venta 2. De esto si que no encuentro lógica ninguna.

Envío por mail excel con la primera curva de carga generada al generar la factura de venta 1, y con las generadas al lanzar la factura de venta 2.

**Comment by PKFEric** [comment]
Esto quedo solucionado al arreglar el proceso de facturacion para que no se cortara en medio y que acabara escribiendo todos los problemas en el LOG.
