### ISSUE TITLE
Cambio estado incorrecto al procesar M1_02

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#251]
Cuando se procesa un registro M1_02 el estado de contrato se mantiene en Tramitación ATR cuando debería pasar a rechazado. No sé si ocurre lo mismo con lo C1_02 y C2_02. Habría que revisarlo.

Ejemplo COM/00194 y COM/00332

**Comment by jorgereal** [comment]
Se ha corregido y se ha subido a PRE y PRO.
Para el C1_02 Y C2_02 si se cambiaba el estado del contrato correctamente.
