### ISSUE TITLE
Historico de medidas

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#253]
Estoy revisando la tabla de histórico de medidas de facturación para unos informes que quiero sacar, y he encontrado que hay veces que se guarda energía 0 cuando realmente si tiene energía. 
Por ejemplo COM/00003 en el registro de 01/04/2017 a 02/04/2017

**Comment by PKFEric** [comment]
Esta factura del COM/00003 es la factura de fin de mes en la que aparece el peaje. El peaje va desde el 01/03/17 al 31/03/17. Por eso no hay energia en los dos dias posteriores del periodo de Facturacion que va desde el 27/03/17 al 02/04/17. Este contrato es del TIPOVI

**Comment by bpesquero** [comment]
Eric está mal. Los 81.000 kWh hay que repartirlos entre los días de marzo y los de abril, y no asignarlos todos a abril

**Comment by geoatlanter** [comment]
Relacionado tarea #269 
Esta la cerramos
