### ISSUE TITLE
Error abriendo Medidas Horarias

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#254]
En GeoAtlanter PRE, Gestión de la Medida, al intentar acceder a Medidas Horarias da el error
«No existe Contrato Código Contrato 'HECEN/08491'»

**Comment by JMunoz17** [comment]
El problema era que se guardaba el filtro que se había utilizado previamente en HECEN PRE, y al no existir dicho contrato en GEO PRE daba ese fallo. Hemos modificado el formulario para que se limpien los filtros al abrirlo.
