### ISSUE TITLE
Error Perfilado Tabla Nueva

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#255]
En GeoAtlanter PRE, el COM/00194, en el periodo de agosto, se factura y perfila correctamente. Pero no aparece medida alguna en la tabla nueva.

**Comment by PKFEric** [comment]
Ya esta solucionado. Con la modificacion que se realizo para que el proceso de facturacion no se parara en el caso en el que hubiera errores. 

Ahora se factura pero muestra los errores en el log. Las medidas aparecen en ambas tablas.

Los errores que aparecen en el log son los siguientes:

La potencia facturada   4,675 del peaje en el periodo 1 es diferente de la potencia facturada 2,933.
La potencia facturada 4,675 del peaje en   el periodo 2 es diferente de la potencia facturada 5,1.
La potencia facturada 23,478 del peaje en   el periodo 3 es diferente de la potencia facturada 22,428.
