### ISSUE TITLE
Ficheros F1 con facturación por tramos

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#257]
En algunos casos, tipicamente por cambios en los precios de los peajes, se facturan los términos de potencia en dos tramos, esto implica que tenemos dos nodos de término de potencia y/o dos nodos de término de enregía , aunque el cierre sea único. La factura tiene por tanto dos líneas para cada periodo de término de energía y/o de término de potencia. Da error en la compra "Las fechas no son iguales".
Ejemplo: COM/00178 y COM/00066

**Comment by PKFEric** [comment]
Necesito hablar contigo para establecer los controles de criterios de fechas.
