### ISSUE TITLE
Fichero F1 sin medidas y con máximetro

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#258]
Cuando se factura una punto con máxímetro para el que no hay medidas, en el nodo de potencia en PotenciaMaxDemandada se pone la potencia demandada. En el nodo de medidas en el integrador de potencia máxima aparecerá en lectura desde un cero y en lectura hasta la potencia contratada. Sin embargo, a la hora de facturar se factura el 85% de la potencia contratada. Esto se controla porque la <Procedencia> de la lectura es 99.
Da error en la venta, ya que no coincide lo facturado con el peaje
Ejemplo COM/00213

**Comment by PKFEric** [comment]
Esto para el contrato  COM/00213 esta arreglado ya, he vuelto a regenerar la venta y sale correcto. 
El calculo que se hace es:

Si el codigo de procedencia es 99 entonces:
 Potencia por periodo= Pci - ( Pci *0.15)

Siendo Pci (Potencia contratada del periodo) y 0,15 (hardcodeado), podria cambiar el hardcodeo por el inverso del margen inferior de la configuracion de energia para maximetro que es 0.85 pero no se si es correcto.

¿No se si controlar también, que no tenga TE esa factura como condición para aplicar este calculo?

**Comment by PKFEric** [comment]
Ya esta modificado. Entiendo que se puede dar por cerrada esta tarea.
