### ISSUE TITLE
Problema compra F1 suministro eventual

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#259]
AL cargar el fichero F1 da error de fecha no valida. La única casuistica es que se está facturando un sólo día y además es de una fecha posterior a la fecha de emisión.
Es el contrato eventual.

**Comment by PKFEric** [comment]
Ya esta creada la compra, habia que meter un cierre manual en el XML

**Comment by PKFEric** [comment]
Esto ya lo hicimos la ultima vez.

**Comment by bpesquero** [comment]
no sale bien la de venta. Solo le factura los derechos de enganche Dejo abierta tanto la compra como la venta

**Comment by PKFEric** [comment]
Estan las dos facturas de venta en pre factura
