### ISSUE TITLE
NAV-Envío de mails desde Gestion de Cobros

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#26]

**Comment by PKFEric** [comment]
Pendiente de probar.

**Comment by bpesquero** [comment]
No he podido aún comprobar todo, tengo que replicar todos los casos, pero de entrada lo que no veo es desde gestión de cobro todos los relativos a impago, rescisición unilateral del contrato fase 1 y fase 2..

**Comment by bpesquero** [comment]
Me he generado una factura en NAV y no me ha llegado el correo de nueva factura

**Comment by bpesquero** [comment]
Pendiente trasladar acciones a gestión de cobros

**Comment by bpesquero** [comment]
Veo que no se ha traslado al formulario correspondiente. HAy uno en tesorería avanzada que es donde se ha puesto, y hay otro en facturación HECEN, que tiene otras funcionalidades que hemos desarrollado, debería ser el mismo, pero veo que no.

Al intentar enviar un mail me dice : No existe histórico cabecera factura

**Comment by PKFEric** [comment]
Ya lo he trasladado a su sitio. Un nuevo boton que se llama Envio Mails

**Comment by bpesquero** [comment]
Eric, he probado desde el equipo de Mónica, desde el mío no se pueden enviar mails. Al dar a envío mail impago 1 da un error que te envío por correo electrónico. 
Al dar a envío mail impago 2 no hace nada

**Comment by PKFEric** [comment]
Probar con Fernando, mirar lo siguiente:

1- Se envía el primer mail impago baja 1 con el importe relleno
2- Solo aparece el nombre de la persona en el mail, sin apellidos.
3- Se rellena la fecha de envio de primer mail.

1- Envio segundo mail.
2 - Aparece solo el nombre  y no los apellidos.
3- Se rellena la segunda fecha.
