### ISSUE TITLE
Errro calendario ficheros F

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#260]
Al cargar algunos ficheros F1 da error de el calendario del TP del contrato COM/00303 es 1p y el número de medidas es 7

COM/00303
COM/00239
COM/00204

**Comment by PKFEric** [comment]
Se ha modificado el XML para quitar la parte duplicada del TE y TP por cambio de año y funciona correctamente, se ha hecho para el peaje del contrato COM/00204. Para los demas habria que hacer lo mismo hasta que subamos la modificacion de las fechas.
