### ISSUE TITLE
Error importe en fichero F

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#261]
Al cargar el fichero F1 da error por el importe no coincide con las unidades  x el precio. 

SE trata del concepto 02 y el problema es que la potencia viene en W. Yo en este caso comprobaría si el importe coincide dividiendo por 1000 y si es así asumiría que es ese el problema y facturaría.
Es el fichero ID_GeoAtlanter, S.L._03180104030044591_F1_0121_20.xml

**Comment by jorgereal** [comment]
Existe un control por si la potencia viene W.
El problema se debe a que nosotros controlamos un margen de error de +- 0,02.
Pero existe un concepto repercutible en el que:
UnidadesConceptoRepercutible = 6900.00
PrecioUnidadConceptoRepercutible = 17,37
ImporteTotalConceptoRepercutible = 119,89

6900 * 17,37 / 1000 = 119,853

¿Aumentamos el margen de error a +- 0,04?

**Comment by bpesquero** [comment]
Si, subelo a 5 centimos

**Comment by PKFEric** [comment]
Modificado
