### ISSUE TITLE
Problema al forzar facturación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#262]
Al forzar la facturación para un periodo ya facturado hace abono y factura pero sale sin energía.

COM/00212 - Agricola Roda

**Comment by PKFEric** [comment]
¿que periodo se esta forzando Fecha Inicio y Fecha Fin???

**Comment by bpesquero** [comment]
La tienes en prefactura y preabono de compra. No lo hemos borrado. En cualquier caso es de 06/06/2017 a 07/07/2017

**Comment by PKFEric** [comment]
Ya esta generada la factura y el abono, para el periodo 1 el cierre es 0 por lo tanto como las medias estan en 6 periodos y la facturacion en 3. Agrupa Periodo 1 y 4. Por lo tanto el TE para el Periodo 1 es 0 no se si esto es correcto. Esta generada  la factura y el abono. Ambos en predocumentos.

**Comment by bpesquero** [comment]
Ok. En realidad no es correcto porque el problema que tenemos es que si que habría que sumar el P4 porque Iberdrola utilizar otro calendario,.,. Después de dar muchas vueltas a esto y hablarlo con la CNMC hemos visto que pueden hacerlo. Damos esta incidencia por cerrada y cambio los cierres a mano para facturar o vemos como solucionar este problema definitivamente?

**Comment by PKFEric** [comment]
Si quieres podemos ver como solucionar el problema, si nos van a aparecer mas casos entiendo que seria lo correcto.

**Comment by bpesquero** [comment]
Si, Abro una incidencia con esto

**Comment by PKFEric** [comment]
relacionado con #269 

Cerramos esta tarea

**Comment by PKFEric** [comment]
Ya esta solucionado, lo he probado con el contrato que teniamos COM/00212, esta en prefactura de venta
Lo he hecho FORZANDO FACTURACION. como ponia en la tarea #269 

Estos son los errores que ha dado el log.


Existe la factura   C/20170959 Registrada con las mismas fechas que la prefctura   FV/201800366  para el contrato   COM/00212
--

Existe un error de   solapamiento para la factura de venta FV/201800366 con fecha inicio 06/06/17   y fecha fin 07/07/17 para el contrato COM/00212
--
