### ISSUE TITLE
Problema al factura el COM/00145

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#263]
Al facturar este contrato, además de salir la factura actual sale una factura anterior y su correspondiente abono. 
Parece que el problema es que la factura de venta original no está asociada al peaje, y por eso lo vuelve a facturar. Además la factura que sale es diferente a la inicial. Se trata de un peaje con un F5D que no tiene medidas completas para el último día. Lo que hace es que obvia todas las medidas del último día,
COM/00145

**Comment by jorgereal** [comment]
Efectivamente el problema estaba en que se había perdido la asociación entre el peaje, los cierres y la factura de venta registrada original.
Los hemos reasociado y hemos eliminado la prefactura y preabono generados incorrectamente.

**Comment by bpesquero** [comment]
Y habéis detectado por qué motivo en la factura nueva no se cogían todas las medidas? Me da miedo que en alguna circunstancia se queden medidas sin facturar.
Gracis

**Comment by PKFEric** [comment]
En la nueva factura generada no se esta contabilizando las medidas hasta el ultimo dia aunque la fecha final sea dia -1

**Comment by PKFEric** [comment]
Me he sacado la factura de venta y la energía facturada es de 327,219. En el F5D la suma de toda la energía Entrante CCH suma 327,219. Se esta facturando toda la energía.

Ademas hay un control en la facturacion de venta que dice que si la suma de toda la energia CCH del F5D asociado al nº factura de acceso correspondiente en el fichero F no coincide con la energia facturada en el TE da ERROR.

**Comment by PKFEric** [comment]
He vuelto a revisarlo, igual estoy confundido pero para la factura C/20180018 la energia de la factura sumando ambos periodos es de 327,22, la fecha ini de la factura es 16/11/17 y la final es 25/12/17.

En cambio en el fichero F5D la fecha final es 26/12/2017, me he sacado el F5D desde NAV a un excel y he sumado toda la energia me da 327,219 que es la misma que aparece en la factura. Entonces yo entiendo que si esta toda la energia facturada, incluidas las horas del dia 26.

**Comment by bpesquero** [comment]
Eric, el problema no está en la factura registrada. Está en la factura que se hizo sin motivo porque la factura registrada no estaba asociada con el peaje. Habría que replicar esa circunstancia para verlo.

**Comment by PKFEric** [comment]
He utilzado en GEOATLANTER PRE la factura que estaba registrada C/20170687, la he desvinculado el peaje, el cierre y las medidas.

He vuelto a facturar y se ha creado la prefactura FV/201701153..

El error que ha dado ha sido: Existe la factura C/20170687 Registrada con las mismas fechas que la prefctura FV/201701153  para el contrato COM/00145

La energia esta bien en la nueva prefactura, coincide con la energia de la factura que ya estaba registrada. 116.665 kWh

Le faltaban horas al ultimo dia.

La suma de las medidas del F5D incluidas las 6 horas del dia 25/05/2017 es de 166.665 kWh y la factura va hasta el dia 24/05/17


Tienes en GEO PRE para verificarlo.

**Comment by bpesquero** [comment]
Lo estoy mirando, pero en PRE no veo que haya medidas horarias.

**Comment by PKFEric** [comment]
En la tabla Hour Measure o accediendo desde la factura FV/201701153 -> Factura -> Horarias, aparecen marcadas con el numero de prefactura las medidas F5D de la prefactura que se ha creado FV/201701153

**Comment by PKFEric** [comment]
Que eran las medidas que desasocie de la factura Registrada
