### ISSUE TITLE
Problema al facturar permitiendo diferencia de potencia

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#265]
Cuando se factura permitiendo diferencia de potencia luego añade una linea para ajustar la potencia, Con lo cual realmente no está permitiendo diferencia de potencia.

Ejemplo: 

COM/00213
--

**Comment by geoatlanter** [comment]
Esta tarea esta relacionada con la tarea #258

**Comment by bpesquero** [comment]
Yo creo que no Eric, esto nos pasaba antes...

**Comment by PKFEric** [comment]
En el caso en el que el contrato tenga marcado permitir diferencia de potencia, no ha de hacer un ajuste de potencia.

**Comment by PKFEric** [comment]
Lo que he hecho es, si el contrato tiene marcado perimitir diferencia de potencia, entonces no hara ajuste de potencia, me queda la duda de si el contrato es con maximetro y tiene ajuste de potencia entonces se deberia de hacer el ajuste de potencia?

**Comment by bpesquero** [comment]
Eric, si es con máximetro tiene que hacer el cálculo correspondiente de la potencia a facturar en función de los valores del máximetro. Lo que no tiene que hacer es meter una línea adicional para conseguir que el importe del término de potencia cuadre.

**Comment by PKFEric** [comment]
Vale, entonces esto queda pendiente de probar. El codigo esta modificado, necesitamos realizar una prueba en el que se de ambos casos. 
Caso 1- > Permitir Diferencia de Potencia Normal.
Caso 2- > Permitir Diferencia de Potencia y que el contrato este marcado como Diferencia de Potencia Para Hacer el Ajuste.

Si es posible que me pases dos contratos con estas situaciones seria perfecto. Yo me encargo de hacer las pruebas en TEST y enseñartelas para ver si se realiza bien.

**Comment by bpesquero** [comment]
No te entiendo Eric. A ver si podemos hablar el lunes por la mañana y lo vemos juntos

**Comment by bpesquero** [comment]
CAmbiados en configuración los "check" de tipos de contratos

**Comment by PKFEric** [comment]
He metido un control en el Ajuste de potencia de tal manera que si el contrato tiene Ajuste de potencia y Permite diferencia de potencia escriba en el LOG.

**Comment by bpesquero** [comment]
ES una situación que en ppio no se debe dar, con lo cual la realizacion de pruebas es complicada. La damos por cerrada.
