### ISSUE TITLE
Problema informes de switching - FEcha tope 20 de enero

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#268]
Salen vacíos los campos de los informes Switching tanto de GAC como de HECEN, en el de tiempos medios

**Comment by PKFEric** [comment]
El problema es el siguiente:
El tiempo medio de Switching se divide en dos:
Activación Con Fecha de Alta y Activación Sin fecha de alta.
El criterio que se utilizaba para saber si cuando se solicita el C1 esa solicitud tiene fecha de alta o no era el valor del campo "Indicativo de Activacion con Ciclo de Lectura" que tomaba los siguientes valores:

S -> La activación se debe producir con próxima lectura del   ciclo -> TIENE FECHA DE ALTA
N -> La activación se producirá cuando venza plazo legal (15   días) -> NO TIENE FECHA DE ALTA

Con el cambio de verano los valores que se toman ahora son :

A ->La activación se debe producir cuanto antes
F -> La activación se producirá según la fecha fija solicitada
L -> La activación se debe producir con próxima lectura del ciclo

Por eso no esta haciendo nada.

¿Entonces que criterio debemos seguir ahora?

**Comment by bpesquero** [comment]
A ->La activación se debe producir cuanto antes--> Sin fecha informada
F -> La activación se producirá según la fecha fija solicitada-->con fecha
informada
L -> La activación se debe producir con próxima lectura del ciclo-->sin
fecha informada

Belén Pesquero Fernández
GeoAtlanter, S.L.
bpesquero@geoatlanter.com
Tlf. +34 91 7378443
Avda. de Europa, 34-B Esc. Dcha. 3º
28023 - Madrid

AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener
información confidencial sometida a secreto social. No está permitida su
reproducción o distribución sin la autorización expresa de GEOATLANTER SL.* *Si
usted no es el destinatario final por favor elimínelo e infórmenos por esta
vía.*

*De acuerdo con lo establecido por la Ley Orgánica 15/1999, de 13 de
diciembre, de Protección de Datos de Carácter Personal (LOPD), le
informamos que sus datos están incorporados en un fichero del que es
titular GEOATLANTER SL* *con la finalidad de realizar la gestión
administrativa, contable y fiscal, así como enviarle comunicaciones
comerciales sobre nuestros productos y/o servicios.*

*Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, cancelación y oposición de sus datos en el domicilio
de GEOATLANTER SL*
*sito en: Avda. de Europa 34B
<https://maps.google.com/?q=Avda.+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha. 3º,  28023 Madrid.*
