### ISSUE TITLE
Aplicación calendario de Iberdrola sumando P4

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#269]
Iberdrola utiliza un calendario diferente para la tarifa 31A, de tal forma que si que hay que sumar el P4, ya que el P4 considera que es el P1 en los meses de invierno....

**Comment by bpesquero** [comment]
Ejemplo 

ES0021000012865289WY
--

**Comment by PKFEric** [comment]
Ya esta solucionado, lo he probado con el contrato que teniamos COM/00212, esta en prefactura de venta
Lo he hecho FORZANDO FACTURACION. como ponia en la tarea #269

Estos son los errores que ha dado el log.

Existe la factura C/20170959 Registrada con las mismas fechas que la prefctura FV/201800366  para el contrato COM/00212
Existe un error de solapamiento para la factura de venta FV/201800366 con fecha inicio 06/06/17 y fecha fin 07/07/17 para el contrato COM/00212
