### ISSUE TITLE
Pontecia con simbolo decimal ","

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#27]
Dar un mensaje de error, o poner en la caja de texto que el simbolo debe ser el "."

**Comment by PKFEric** [comment]
Poner ejemplo con un punto para que se sepa que es decimal con '.'

**Comment by PKFEric** [comment]
PROBAR-> AÑADIDO EL EJEMPLO

**Comment by bpesquero** [comment]
Ok. EStá bien, pero creo que se te ha colado una comilla se ve  '0.0

**Comment by PKFEric** [comment]
Cierto es :) Ya esta corregido
