### ISSUE TITLE
factura regularizadora y rectificadora

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#270]
Al importar el F1 de una factura G (regularizadora) hace abono pero no factura, cuando en realidad debería hacer factura pero no abono. El abono debe hacerse con las facturas rectificadoras. ESto es algo que teníamos mal y se ha aclarado en los grupos de trabajo.

COM/00301
SCTDE_F1_01_0022_0587_20180110115619801_(627855272).xml

**Comment by PKFEric** [comment]
Tipo G solo tiene que hacer Factura

**Comment by PKFEric** [comment]
He generado la compra y ya sale factura. El problema es que esta factura esta facturando el TE del peaje anterior que venia sin TE.
Por lo tanto se importa bien, pero la fecha desde y hasta de la factura entiendo que no son correctas.
El error que da en compra es:

Existe un error de   solapamiento para la factura de peaje 5118011013254 con fecha inicio 07/11/17   y fecha fin 02/01/18 para el contrato COM/00301
--

Igual he generado la venta y pasa lo mismo factura un periodo que ya esta facturado no se si esto y ha pasado y hay que hacer algo o como funciona.
En venta da este error:

Existe un error de   solapamiento para la factura de venta FV/201800365 con fecha inicio 07/11/17   y fecha fin 02/01/18 para el contrato COM/00301
--



Ambas facturas estan en Pre- FACTURA

**Comment by bpesquero** [comment]
Ok. Entonces ahora habrá que esperar a tener todo el proceso arreglado, en que se considera este caso de que las fechas del TE no sean iguales a las fechas del TP

**Comment by bpesquero** [comment]
Aclaración:

el tipo G sólo hace factura
el tipo R hace factura y abono
