### ISSUE TITLE
Pregunta: Cargas Oracle NAV PRE

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#271]
Repetidas la carga de medidas en Pruebas, veo que únicamente se cargan medidas de un único contrato.
¿Es eso correcto?
Entiendo, tal como está la tabla de contratos deberían cargarse de todos ellos.

**Comment by JMunoz17** [comment]
Según los datos que hay en GEOATLANTER PRE, hay 13 contratos a partir de los cuales se llamará a los procedimientos almacenados de Oracle ya que tienen el campo "Origen Medidas Contador" de la tabla Contrato relleno. 

Hemos visto que desde Navision se realiza la llamada de manera correcta el procedimiento almacenado correspondiente de Oracle (PA_MEDIDAS_CONTADOR_NI) y que este devuelve en todos los casos (a excepción del contrato COM/00012) un valor = 9 que indica que no hay datos de medidas que devolver. 

Hemos consultado en las tablas de Oracle y hemos visto que no hay ningún registro para los CUPS de todos estos contratos (menos para el correspondiente al COM/00012 que si que tiene datos) en la tabla COMUN.D_PUNTOS_FRONTERA. 

De modo que solo devuelve datos para el COM/00012 porque es el único que tiene datos relacionados en las tablas de oracle.

**Comment by fmsanudo** [comment]
Dice Belén "que no puede ser", que en la BD de Producción nos estamos trayendo todos los datos de estos puntos de forma sistemática.

Pásanos, por favor, los parámetros con los que llamáis al PA para simularlo en Oracle.

Por otra parte, nosotros hemos visto que si que hay 4 de los 13 puntos que comentas dados de alta en la tabla de Oracle. EL resto es verdad que no tienen medidas en Oracle, que son pruebas raras.
Estos 4 puntos tienen además datos previos cargados anteriormente.

![image](https://user-images.githubusercontent.com/20299071/35975064-bb9b4370-0cdb-11e8-8b77-8e7b93fe5f70.png)

**Comment by JMunoz17** [comment]
Por cada contrato al procedimiento almacenado se le envía:
   - CUPS
   - Fecha Inicio Contrato
   - Fecha Final Contrato
   - Tipo Medida
   - Fecha ultima consulta a Oracle para ese contrato

En los tres casos (COM/00001, COM/00002 y COM/00243) se trata de contratos con fecha final en el 2017 y ya están importadas en Navision (en GEOATLANTER PRE) las medidas de Oracle hasta dicha fecha de final de contrato.  El procedimiento almacenado filtra las medidas por fecha inicio de contrato y fecha final de contrato y solo busca a partir de la fecha de la ultima consulta que se realizó para ese contrato.

**Comment by fmsanudo** [comment]
Perfecto. Testadas las inserciones de medidas con cambios en las fechas, procedo al cierre.
