### ISSUE TITLE
Perfil gestor  - 01/11/2018

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#274]
Habría que incluir un perfil gestor en la web que le permitiriera ver un conjunto de contratos de diferentes clientes.

**Comment by PKFEric** [comment]
Un gesto lleva varios contratos, cada gestor tiene asociado un codigo promocional. Si un contrato se da de alta a traves del codigo promocional se le relaciona el gestor asociado a este.

Se enviaran mails en copia de todas las incidencias del contrato..alta facturacion, nueva factura..baja.. al gestor.

**Comment by PKFEric** [comment]
Vendedor-> Codigo Promocional de 7 Caracteres -> Campo correo electronico -> BOoleano recibir copia pmail clientes. -> Fecha hasta de validez

Cuando se introduzca en la web el codigo promocional se asociara el vendedor relacionacionado a ese codigo en el contrato que secrea.

**Comment by PKFEric** [comment]
Todos los gestores son vendedores-> hay vendedores que pueden ser campañas. 

Al crear en la web un usuario gestor hay que asociarle el codigo de vendedor y permitirle visualizar que no tocar toda la informacion asociada a sus contratos...facturas...contratos...

**Comment by PKFEric** [comment]
El desarrollo de esto aplica a proxima energia y a A tu lado.

**Comment by bpesquero** [comment]
Hemos realizado las pruebas y hemos encontrado lo siguiente

1.- Creamos el usuario gestor en la web y al crearlo en NAV al meter el codigo pormocional pone "0000" no el aleatorio que acordamos ayer
2.- No puedo entrar  a la web con el usuario y pwd que me he creado. TAmpoco puedo entrar con el que tú me has facilitado. Me he ido a la parte de administración/usuarios y no los veo...
3.-He sacado en el listado de contratos el campo cod_vendedor, para que no nos pisemos.

**Comment by bpesquero** [comment]
Todo perfecto, salvo que cuando doy a exportar contrato se queda pensando, pensando, pensando... y no llega nunca a sacarlo

**Comment by jlagunapkf** [comment]
Esto lo vemos por teamviewer porque a mi me funciona correctamente.

**Comment by jlagunapkf** [comment]
Ahora debería de funcionar correctamente.
