### ISSUE TITLE
Informes gestión de cobros

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#277]
Necesitamos dos informes nuevos de gestión de cobros. Envío por mail documento explicativo.

**Comment by PKFEric** [comment]
Informanos de los documentos iniciales de 2014

**Comment by bpesquero** [comment]
Los saldos inicales se cargaron con fecha 31/12/2014. Por una parte hay movimiento con Nº documento= "SALDO_INICIAL" y por otra parte hay un movimiento tipo efecto que se corresponde con la última facturación remesada que se cobra en el banco en enero de 2015.
Como ejemplo el cliente CL00307 que tiene ambos movimientos.

**Comment by JMunoz17** [comment]
Hemos modificado el informe para que calcule a fecha 31/12/2014 el saldo inicial de los clientes como la suma del movimiento de saldo inicial mas el efecto que se había cargado.

**Comment by bpesquero** [comment]
El efecto inicial cargado sólo hay que sumarlo si no está pagado, como cualquier otro efecto.
¿Lo habéis hecho así?

**Comment by PKFEric** [comment]
Ya esta modificado. Ahora la deuda hasta 31/12/14 solo coge el mov de saldo inicial.

**Comment by bpesquero** [comment]
He hecho las comprobaciones y he encontrado lo siguiente:
-Informe deuda agregada: la deuda a 31/12/2014 sale 0. Yo veo que tenemos realmente un saldo inicial en PRE de 1.864.225,26. La deuda entre dos meses y años del informe suma 757.599 y de más de un año 1.055.743. Sólo la parte correspondiente al saldo inicial que aún no está pagada es de 1.263.000 por tanto los datos no son correctos. Aún suponiendo que no está considerando el saldo inicial la deuda total del informe suma 1.813.000. Si yo miro el saldo pendiente de clientes en la fecha actual es de 2.609.966 que restando la parte correspondiente a saldo inicial, entendiendo que no se ha tenido en cuenta (1.263.000) da un resultado de 1.364.000 que no coincide tampoco con 1.813.000
-Informe de deuda detallada: la suma total de la deuda es de 1.809.000 que es casi igual pero no igual a la deuda que aparece en el agregado, pero que no coincide con el resto de comprobaciones. He estado revisando algunos clientes y salen bien, excepto cuando tienen saldo inicial con importe pendiente, que directamente ni salen en el informe. Ejemplo CL00017

**Comment by jorgereal** [comment]
Se ha corregido el informe y ahora ya saca datos para la deuda a 31/12/2014.

El motivo por el que los datos no se corresponden con los tuyos es porque nosotros el cálculo de la deuda lo hacemos solo para los clientes titulares de contratos, en el caso del CL00004 por ejemplo, que no es titular de ningún contrato (es pagador), no se está teniendo en cuenta su deuda.

¿Los informes deben tener en cuenta todos los clientes del sistema, los clientes pagadores de contratos o los clientes titulares?

**Comment by bpesquero** [comment]
Los informes tienen que tener en cuenta toda la deuda, pero asignarla al cliente titular. Pero la deuda hay que tenerla en cuenta.

**Comment by jorgereal** [comment]
Hemos pasado un proceso para rellenar el No. Contrato en los movimientos de cliente, Natalia solo lo había pasado para el 2017.

Se han modificado los informes para tener en cuenta tanto a clientes titulares como pagadores (la deuda de los pagadores se le asigna a los titulares, por lo que no aparecerán en el informe detallado, caso del cliente CL00017), ahora los resultados se aproximan más a lo esperado.

El informe de deuda agrupada tiene en cuenta movimientos pendientes y saldos iniciales, el informe detallado tan solo movimientos pendientes.

A pesar de pasar el proceso para rellenar los Nos. de contrato en los movimientos sigue habiendo movimientos pendientes sin una referencia de contrato, esto se debe a que el campo "No documento" no contiene el código del documento del que obtener la información del contrato. Estos movimientos no se tienen en cuenta en los informes.

Subido a PRE.

**Comment by bpesquero** [comment]
-En el informe de detalle también hay que incluir el saldo inicial
-¿cómo se va a ir rellenando a partir de ahora el nº de contrato?¿Se va a ir haciendo automáticamente?
-¿cómo puedo identificar los movimientos pendientes que no tienen asignado un nº de contrato?

**Comment by bpesquero** [comment]
Reclamamos a Fenosa para que nos indiquen a corresponden realmente los consumos registrados en P4, para saber a qué periodo se lo tenemos que asignar.

**Comment by jorgereal** [comment]
Se ha modificado el informe de detalle para incluir el saldo inicial.

Natalia dejó hecho el desarrollo para que el nº de contrato se rellene automáticamente en los nuevos movimientos.

Para identificar los movimientos pendientes sin contrato te vale con filtrar en la tabla de movimientos de cliente por:
Contract No. = ''
Pendiente = Sí
No Documento <> SALDO_INICIAL
Situación Documento = ''|Cartera

**Comment by bpesquero** [comment]
He revisado los movimientos pendientes que me comentas que no tienen contrato. Muchos no tienen relevancia pero hay otros que hay que tener en cuenta, son los que empiezan por DEV. Son 395 movimientos, no sé si podríamos asignarles un contrato en el que el cliente constase como con titular, ya sé que puede haber algún error, pero al menos nos aparecerá la deuda

Por otra parte, también hay movimientos de SALDO_INICIAL que no tienen asociados contratos, entiendo que con estos pasará lo mismo, que no se están teniendo en cuenta, no? Son 858, podríamos hacer algo parecido?

**Comment by PKFEric** [comment]
Belen nos pasa la relacion de contratos con movimientos en un excel

**Comment by bpesquero** [comment]
Enviado por mail

**Comment by JMunoz17** [comment]
Hemos pasado, tanto en PRE como PROD, un proceso para rellenar el número de contrato en los movimientos de cliente en función de la relación que nos pasaste. 

Hemos modificado los informes para que cuando se trate de movimientos de SALDO_INICIAL muestre la deuda buscando en los movimientos de cliente por Nº de contrato. 

En el informe de deuda agregada hemos puesto que la deuda > de 1 año se calcule a partir de 1 día después de la carga del SALDO_INICIAL, es decir, desde el 01/01/2015 hasta la fecha actual menos 1 año.

**Comment by bpesquero** [comment]
He probado a ejecutar el informe de deuda agregada y lleva 3 horas y no ha terminado. Me temo que existe algún problema

**Comment by bpesquero** [comment]
He comprobado el informe de deuda y sigue saliendo mal. sólo he mirado el informe de deuda agregada, para no perder más tiempo

El importe de deuda a 31/12/2014 no coincide con la realidad. Hay un montón de movimientos sin contrato asociado, entiendo que es por eso. Muchos de ellos no tienen importe pendiente. Independientemente de que no tengan importe tienen que salir en la deuda a 31/12/2014 porque en ese momento si eran deuda.
Hay que tener en cuenta que el informe muestra
-deuda a 31/12/2014: la deuda que había a 31/12/2014
-deuda actual: la deuda en el momento de ejecutar el informe dividida por antigüedad: más de un año, entre dos meses y un año y menos de dos meses. Por tanto, el importe correspondiente a saldo inicial que sigue pendiente a día de hoy, SI hay que meterlo en la deuda a más de un año. No es lo mismo que lo mostrado en la primera columna que es la deuda que había a 31/12/2014.
-Deuda actual mayor de dos meses y menor de un año. El informe devuelve 384.582€. Si yo me cojo los movimientos de cliente pendientes registrados desde hace un año y hasta hace dos meses me da 460.298 euros
-Deuda actual mayor de un año:El informe devuelve 1.635.067 euros. Si yo cojo los movimientos de cliente pendientes registrados hace más de un año tengo 2.149.668 euros, si quito los movimientos de saldo inicial tengo 813.000 euros. Es decir, en ningún caso coincide con el importe del informe.

**Comment by bpesquero** [comment]
Lo podéis pasar a producción?

**Comment by JMunoz17** [comment]
Hemos rellenado los contratos en los movimientos de cliente en HECEN, hemos subido los objetos y hemos sacado los informes en el menú (Energy -> Hidroeléctrica El Carmen Energía -> Gestión de Cobros).

Te mando por correo los movimientos de cliente de SALDO_INICIAL que no tienen contrato asociado en HECEN PROD para que nos indiques el contrato que les tenemos que asignar.
