### ISSUE TITLE
Informe de inventario MEDIDAS

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#279]
El informe de invertario sale vacio.

**Comment by jorgereal** [comment]
El problema se debía a que no había ninguna empresa de PRE con el check "Intercompany" marcado.
Se ha marcado para GEOATLANTER.

Se ha añadido un control para detectar si no hay ninguna empresa intercompany y mostrar un mensaje de error.

También se ha corregido un fallo por el que las líneas de cabecera del informe no aparecían.
