### ISSUE TITLE
WEB-No permitir hacer contratos en extrapeninsulares

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#28]

**Comment by PKFEric** [comment]
No se pueden hacer contratos ceuta melilla y baleares, y canarias

**Comment by bpesquero** [comment]
EStaría bien que cuando haga la validación, y vea que es este caso, además de poner CP incorrecto, ponga debajo, "lo sentimos, sólo comercializamos en la Península"

**Comment by PKFEric** [comment]
MODIFICADO->PROBAR

**Comment by bpesquero** [comment]
No lo veo modificado, sólo me pone CP incorrecto

**Comment by PKFEric** [comment]
MODIFICADO->PROBAR

**Comment by bpesquero** [comment]
Ok. EStá correcto pero Solo es con acento "Sólo"

**Comment by bpesquero** [comment]
Lo he mirado pero a mi me parece que no está correcto. He borrado la caché y me pone

"Código Postal incorrecto Solo comercializamos puntos de suministro peninsulares."

Le falta un punto detrás de correcto y una tilde en Solo. Debería ser

"Código Postal incorrecto. Sólo comercializamos puntos de suministro peninsulares."

**Comment by PKFEric** [comment]
Aun no he subido la web. Ahora te digo

**Comment by PKFEric** [comment]
YA ESTA PROBRAR

**Comment by PKFEric** [comment]
PROBAR AHORA

**Comment by bpesquero** [comment]
Falta el "." después de incorrecto.

**Comment by bpesquero** [comment]
Probado y ok
