### ISSUE TITLE
Modificaciones nuevos formatos OCSUM - 8/04/2018

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#281]
Hay que acometer las modificaciones impuestas con los nuevos formatos de intercambio de ficheros. 
Entran en vigor el 08/04/2018

**Comment by PKFEric** [comment]
Como te comentamos en el mail, ya estan modificados los cambios, estaria bien disponer de ficheros nuevos para poder probar los cambios y ver que van entrando bien en NAV.

**Comment by bpesquero** [comment]
No se dispone de ficheros de pruebas. Habrá que esperar a que entren en funcionamiento . No hay otra opción. 
Habéis revisado todos los cambios que aparecen en el documento de control de cambios de la CNMC?

**Comment by JMunoz17** [comment]
Hemos subido los objetos a producción.

**Comment by bpesquero** [comment]
Nos están diciendo las distribuidores que no hemos implementado la url de documentos tal y como se estableció. He escrito un mail incluyendo de nuevo el documento para vuestra revisión.
La cuestión que nos indican básicamente es que en el nuevo modelo no sería  necesario meter usuario y contraseña en la descarga de cada documento y nosotros seguimos solicitándola.
