### ISSUE TITLE
Campaña "amigo" - 01/11/2018

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#282]
Queremos poner en marcha una campaña de tal forma que cada cliente de comercialización que nos traiga un nuevo contrato reciba 5 euros de descuento.
Las implicaciones que tendría a nivel de WEB y NAV serían:

1.- Asignar a cada cliente un codigo con sus iniciales (nombre y 2 apellidos) y en caso de estar repetidos se irá asignando un número correlativo
2.- Añadir en los mail de nueva factura y en la web una imagen explicativa de la campaña proporcionada por GeoAtlanter
3.- Incluir en todas las facturas una imagen de la campaña y su código "amigo", que se corresponderá con el  código amigo del cliente pagador
4.- Añadir en la web en la parte privada una imagen de la campaña y su código "amigo", que se corresponderá con el  código amigo del cliente pagador
5.- Añadir dos nuevos campos en la tabla de contratos: [código amigo] (varchar) y [código amigo utilizado] (booleano).
6.- Modificar la pantalla de alta en la web y añadir campo de código amigo y una validación de que el código existe
7.- Al insertar en NAV los datos del contrato desde la web se añadirá el [código amigo] introducido y se marcará el booleano de [código amigo utilizado] a No.
8.- Cada vez que se haga una factura de venta se comprobará el número de contratos activos que tengan el código amigo correspondiente al pagador del contrato y además tengan el [código amigo utilizado] a No. En la factura de venta se añadirá una línea de descuento después del margen comercial cuya cantidad será el nº de contratos localizados y el precio será -5 euros. Se usará el mismo producto utilizado en la línea de comisión. 
8.- Una vez registrada la factura de venta correspondiente se marcará el campo [código amigo utilizado] a sí, en todos aquellos contratos que tuvieran el campo [código amigo]= [cod cliente pagador] y [código amigo utilizado]=No.
9.- Al hacer la primera factura de venta de cada contrato se comprobará si es tiene código amigo y en caso afirmativo se introducirá una línea de descuento después del margen comercial cuya cantidad sera 1 y el precio será -5 euros. Se usará el mismo producto que se utiliza en la línea de comisión.

**Comment by PKFEric** [comment]
Relacionada con la #274

**Comment by jlagunapkf** [comment]
Realizado y subido a producción. Quedán realizar las pruebas correspondientes por vuestra parte.
