### ISSUE TITLE
error factura de venta ES0021000021455045HK

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#283]
Al facturar la venta da el error: las medidas Perfil 2.709,00000000000001, de la factura FV/201800495 para el contrato COM/00332 no se corresponden con las medidas de cierre 2.874. 
No llega  a escribir la medida perfilada así que no sé que le pasa. Además la diferencia no coincide con la energía de ninguno de los periodos, así que no sé que está pasando.

**Comment by PKFEric** [comment]
Ya esta arreglado, hay que rellenar los festivos en el calendario para 2018. Esto se hace desde Energy -> Carga de Datos -> Carga de Perfiles -> Calendario Base

Yo he rellenado hasta febrero de 2018 hay que rellenar el año entero y cada año hay que hacer lo propio para que al calcularse el perfil si es festivo rellene el periodo correspondiente.

**Comment by PKFEric** [comment]
La factura esta en prefactura.

**Comment by bpesquero** [comment]
ok. Gracias
