### ISSUE TITLE
Automatización envío SII

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#284]
Para poder implementar la automatización del envío del SII, necesitamos un control de que los envíos no se realizan fuera de plazo.

**Comment by NataliaNNK** [comment]
Esta modificado el proceso de envío para tener control.

**Comment by bpesquero** [comment]
EStá pendiente de probarse con el ceritificado

**Comment by NataliaNNK** [comment]
Esta comprobado y funciona. Se envía correctamente desde la cola de proyectos.

**Comment by bpesquero** [comment]
Se envía ya? Lo tengo configurado? Qué tengo que hacer para que empiece a funcionar?
Gracias

**Comment by bpesquero** [comment]
Acabo de comprobar que se están haciendo los envíos, y con ello he comprobado que el iva de caja asociado a los pagos siguen trayendo mal la fecha. pone la fecha de registro de la factura y no la de la remesa.
Ejemplo OPS_20180043, fecha registro orden de pago 22/03/2018, fecha SII 13/03/2018. Lo he dejado en SII pendiente de enviar para que lo podáis ver antes de cambiarlo. el lunes o martes lo cambiaré para enviarlo.

**Comment by bpesquero** [comment]
Natalia, por lo que veo se están considerando días naturales y tienen que ser días laborables. Además, me puedes poner editable la fecha de SII en documentos emitidos, igual que hiciste con los recibidos?

**Comment by gvalverdePKF** [comment]
Ya hemos corregido los días naturales por días laborables, también hemos puesto editable el campo fecha en los documentos emitidos.

**Comment by bpesquero** [comment]
Lleva unos días sin enviarse de forma automática, puede ser por lo que estabais haciendo?

**Comment by gvalverdePKF** [comment]
Vamos a monitorizar esta tarde el proceso de envío para ver que ocurre.
La mantenemos informada.

**Comment by dgarciageo** [comment]
La semana pasada ha estado sin funcionar la cola de proyectos por el tema del certificado...

Gracias

-----------------------------------------

Estado	Id. usuario	Tipo objeto para ejecutar	Id. objeto para ejecutar	Nombre objeto para ejecutar	Fecha/hora inicio	Fecha/hora finalización	Mensaje de error
Correcto	Attest	Informe	88201	Procesar Movs. IVA SII	15/04/19 18:00	15/04/19 18:00	
Error	Attest	Informe	88204	Enviar documentos SII	15/04/19 18:10	15/04/19 18:10	This message is for C/AL programmers:

The call to member Send failed. WinHttp.WinHttpRequest returned the following message:
Se requiere de un certificado para completar la autenticación de cliente


Correcto	Attest	Informe	88201	Procesar Movs. IVA SII	16/04/19 18:00	16/04/19 18:00	
Error	Attest	Informe	88204	Enviar documentos SII	16/04/19 18:10	16/04/19 18:10	This message is for C/AL programmers:

The call to member Send failed. WinHttp.WinHttpRequest returned the following message:
Se requiere de un certificado para completar la autenticación de cliente


Correcto	Attest	Informe	88201	Procesar Movs. IVA SII	17/04/19 18:00	17/04/19 18:00	
Correcto	Attest	Informe	88201	Procesar Movs. IVA SII	18/04/19 18:00	18/04/19 18:00	
Correcto	Attest	Informe	88201	Procesar Movs. IVA SII	19/04/19 18:00	19/04/19 18:00

**Comment by PKFEric** [comment]
Ya esta solucionado este problema.

Ahora ya se ha generado.

Estado	Id. usuario	Tipo objeto para ejecutar	Id. objeto para ejecutar	Nombre objeto para ejecutar	Fecha/hora inicio	Fecha/hora finalización	Mensaje de error
Correcto	Attest	Informe	88201	Procesar Movs. IVA SII	22/04/19 18:00	22/04/19 18:00	
Correcto	Attest	Informe	88201	Procesar Movs. IVA SII	23/04/19 18:00	23/04/19 18:00	
Correcto	Attest	Informe	88204	Enviar documentos SII	24/04/19 15:45	24/04/19 15:48

**Comment by dgarciageo** [comment]
se han enviado los documentos con el certificado de forma correcta. se cierra incidencia

![image](https://user-images.githubusercontent.com/47117960/56669394-5e5e6580-66b1-11e9-94ec-db81959c255b.png)

**Comment by bpesquero** [comment]
He mirado y realmente no se han enviado los documentos recibidos. Los estoy enviando yo manualmente, y he comprobaré si hoy se hacen los envíos.

**Comment by dgarciageo** [comment]
Hay mvtos pendientes de enviar y durante el fin de semana no se han enviado. Se procesan pero no se envían.

**Comment by dgarciageo** [comment]
Sigue dando problemas el envío, el procesamiento se realiza correctamente

![image](https://user-images.githubusercontent.com/47117960/57218826-9a20f580-6ff6-11e9-81da-e71df272b81b.png)
