### ISSUE TITLE
IVA de caja en informe de IVA

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#285]
Las operaciones sujetas a IVA de caja no aparecen correctamente informadas en el informe de IVA para la presentación de impuestos

**Comment by bpesquero** [comment]
Parece que sigue saliendo mal. En el informe de resumen el importe coincide con el IVA deducible y no puede ser porque hay movimientos con prorrata.
![image](https://user-images.githubusercontent.com/20299071/37786602-61a00f8e-2dfd-11e8-860a-02bf189004cd.png)

Si miramos el detalle de los movimientos efectivamente se ve que hay movimientos con prorrata donde el IVA deducible no coincide con el importe
![image](https://user-images.githubusercontent.com/20299071/37786644-772ef72a-2dfd-11e8-9c4e-26fadeda9c6f.png)

Pero sin embargo en el totalizador sale lo mismo en ambas columnas
![image](https://user-images.githubusercontent.com/20299071/37786671-871d6fcc-2dfd-11e8-96ff-b695fa7bf45b.png)

**Comment by PKFEric** [comment]
Esto esta cerrado entre Mónica y Natalia.
