### ISSUE TITLE
Asiento liquidación de IVA

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#287]
El asiento de liqudación de IVA no se hace correcto cuando hay prorrata, no se liquidan todas los movimientos.

Ejemplo:
movimiento de contabilidad:

Fecha registro | Nº documento | Descripción | Importe debe | Importe haber | Nº cuenta
-- | -- | -- | -- | -- | --
01/01/2018 | FCR/20180153 | Renting |   | 135,42 | 7400002
01/01/2018 | FCR/20180153 | Renting | 293,66 |   | 6210000
01/01/2018 | FCR/20180153 | Renting | 293,66 |   | 6290998
01/01/2018 | FCR/20180153 | 50 % de I.V.A. NO DEDUCIBLE | 30,84 |   | 6310100
01/01/2018 | FCR/20180153 | 50 % de I.V.A. NO DEDUCIBLE | 30,84 |   | 6310100
01/01/2018 | FCR/20180153 | Renting | 61,67 |   | 4720004
01/01/2018 | FCR/20180153 | Renting | 61,67 |   | 4720004
01/01/2018 | FCR/20180153 | 50 % de I.V.A. NO DEDUCIBLE |   | 30,84 | 4720000
01/01/2018 | FCR/20180153 | 50 % de I.V.A. NO DEDUCIBLE |   | 30,84 | 4720000
01/01/2018 | FCR/20180153 | Renting |   | 575,24 | 4100001

Pues bien, en el asiento de liquidación sólo se liquidan los movimientos de la cuenta 4720004 y no los de la cuenta 4720000. Pensé que quizá es que hubiese que configurar algo en esa cuenta, pero vemos que hay movimientos de esa cuenta que si se liquidan, pero los que vienen de prorrata, no.

**Comment by PKFEric** [comment]
Ya esta realizado y subido a pro
