### ISSUE TITLE
El detalle de la factura no es correcto

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#288]
He visto que el Excel de detalle de la factura no es correcto, en todos los que he comprobado hay un conjunto de horas en que todos los precios salen a cero.
Ejemplos: C/20180326, C/20180006

**Comment by JMunoz17** [comment]
Hemos visto que para la factura C/20180006 los datos de los precios salen a cero a partir del día 22/12/2017. Hemos comprobado que los valores coincidan con los de la tabla Pool Energy Prices a partir de la cual se muestran los datos en el Excel. 

En la tabla de ESIOS OMIE, a partir de cuyos valores se rellena la tabla de Pool Energy Prices, no están rellenos los datos correspondientes a la versión C1 a partir del día 22/12/2017.
El motivo de que no estén rellenos estos datos es que el fichero a partir del cual se rellena esta tabla no trae informado ningún valor a partir del día 22/12/2017.

Este fichero puedes encontrarlo en la carpeta de procesados de Descargas Esios. El nombre del fichero es: C1_prmdiari_20171201_20171231

**Comment by bpesquero** [comment]
En el momento en que se hace la factura los datos existen, porque si te das cuenta la columna de importe mercado es correcta, por tanto, en el momento de cálculo si se tuvieron en cuenta todos los datos. Si en el momento en que se calcula una factura no hay precios para todos los días debería saltar una alarma. Comprobad que esto es así, es importante. Insisto, cuando se calculó la factura había precios 
porque el valor de importe mercado para esas horas es distinto de cero.

**Comment by PKFEric** [comment]
Los precios pool a partir del dia 22/12/2017 a las 00:00:00 estan vacios, lo puedes ver en el detalle de la factura en NAV. El fichero C1 no venia con los precios Pool a partir de ese dia. Cuando se facturo no se aplico ese coste de mercado bien por que no venia informado en el fichero del OS. Efectivamente habra que poner un control que revise todos los precios pool que no esten vacios pero entiendo que habra que hacerlo para todos los conceptos que aplican el el calculo del coste del TE. No obstante es posible que un precio Pool Sea 0 por lo tanto el control no se muy bien como hacerlo. Igual pasa en los demas conceptos.

**Comment by PKFEric** [comment]
Te hablo de la factura C/20180006

**Comment by PKFEric** [comment]
Esta tarea esta asociada a los errores que han sucedido en la carga de esios.
