### ISSUE TITLE
error FV/201800541

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#289]
AL generar la factura de compra del contrato COM/00057 da un error de que las medidas de cierre no son iguales que la de peaje.

Se trata de una alta medido en baja con una 31A. Al calcular las pérdidas debe haber alguna diferencia y por eso no sale bien. Es poca diferencia. Se trata de un suministro de Iberdrola, y por tanto hay que tener en cuenta el P4, quizá hay algún problema con el calendario utilzado y por eso sale una pequeña diferencia. 
Además de esto, cuando se hace la venta (FV/201800541) sale mal. No se tiene en cuenta el P4.
DEjamos tanto la compra como la venta en prefactura

**Comment by PKFEric** [comment]
Ver mail adjunto

**Comment by bpesquero** [comment]
Eric, creo que hay un problema con el calendario que estamos utilizando para calcular el nº de horas de cada periodo y así calcular las pérdidas. 

Independientemente, en la venta no se está teniendo en cuenta el P4.

**Comment by PKFEric** [comment]
Y cual es el problema? Viste que te adjunte en una de las hojas del excel el calendario. Lo saque de las descargas de ESIOS. lo unico que hice fue sumar +3 al periodo si era festivo.

**Comment by bpesquero** [comment]
Reclamamos a Fenosa para que nos indiquen a corresponden realmente los consumos registrados en P4, para saber a qué periodo se lo tenemos que asignar.
