### ISSUE TITLE
Orden de domiciliación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#29]
Al crear la orden de domiciliación del banco de cliente no se le pone fecha de alta, debe ser la actual en el momento de creación, se crea como cargo único, debe ser recurrente, nº de debe esperado pone 1, debe ser 10.000

**Comment by PKFEric** [comment]
No se creaba, he añadido el codigo al rellenar el SWIFT.

HAY QUE PROBARLO

**Comment by PKFEric** [comment]
PROBAR

**Comment by bpesquero** [comment]
Probado y ok
