### ISSUE TITLE
Cambio orden de prelacion de las liquidaciones consideradas en la facturacion

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#292]
Orden de prelación | Liquidación
-- | --
1 | C6
2 | A6
3 | C5
4 | A5
5 | C4
6 | A4
7 | C3
8 | A3
9 | C2
10 | A2
11 | C1
12 | A1

**Comment by bpesquero** [comment]
cada liquidación se identifica por el estado "E" (avance-A o cierre-C) y el nº de liquidación "L" (del 1 al 6). De esta forma el nombre del fichero empieza con el codigo alfanumérico EL_. Lo que habrá que hacer es para cada registro horario ver cual es el máximo nº de liquidación (max "L"). Una vez seleccionado el nº de liquidación, tendrá prioridad los cierres (C) a los avances (A).

**Comment by bpesquero** [comment]
según lo que hemos hablado y con la idea de meter un campo de prelación en la tabla de descargas esios, lo suyo seria que la prelación tuviera orden inverso, es decir "la mejor" liquidación tuviera la mayor prelación (aunque esto vaya en contra del significado de prelación) pero de esta manera nos aseguramos que no haya problema si en el futuro aparecen más liquidaciones, por encima de la 6, y nos permite también calcular la prelación a través de la fórmula

prelación = liquidación * 2 + si(estado=A;1;0)

de esta forma la tabla anterior quedaría


Orden de   prelación | Liquidación
-- | --
12 | C6
11 | A6
10 | C5
9 | A5
8 | C4
7 | A4
6 | C3
5 | A3
4 | C2
3 | A2
2 | C1
1 | A1

**Comment by fmsanudo** [comment]
Realizadas las comprobaciones, de los datos anteriormente cargados y de los nuevos por cargar, y estando todas ok, procedo al cierre
