### ISSUE TITLE
controles de existencia de precios (descargas esios) en facturas de venta

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#293]
Los controles a implementar son:

- para cada hora el precio de mercado diario es distinto de 0
- para cada hora la suma de sobrecostes es distinta de cero. La suma de sobrecoste será: banda de secundario + restricciones en PBF + restricciones en tiempo real + reserva de potencia subir + control de FP + saldo desvíos sistema + ingreso excedente de desvíos + fallos de nominación + incumplimiento de energía del balance + intercambio de apoyo con precio 
-para cada hora el pago por capacidad (PxC) es distinto de 0 siempre que el periodo sea distinto de 3 o 6
-para cada hora la retribución de los operadores es distinto de 0
-para cada hora el servicio de interrumpibilidad es distinto de 0

**Comment by bpesquero** [comment]
Hemos detectado que en ocasiones parece producirse un corte en la conexión con el servidor NI y por tanto hay registros horarios para los que no se rellena el precio y se queda a cero. Sería posible controlarlo de alguna forma?

**Comment by fmsanudo** [comment]
Hemos detectado que se ha implementado el control de que el término de energía sea igual a 0 en una o determinadas horas.
Esto hace que haya un número elevado de errores en el log con poca operatividad.

**Comment by PKFEric** [comment]
Ya esta arreglado, solamente comprobara que la suma de sobrecostes de TE es > 0 siempre que la Energia Consumida para esa hora sea > 0

**Comment by bpesquero** [comment]
En el algunos casos sale en el log que la suma de los TE para un determinada hora es 0. Mirando el detalle de la factura no es 0. ES cierto que para esa hora existe una versión de esios que suma 0, pero no es la de mayor prelación, y por tanto no es la que debe usarse en  facturación, y  parece que efectivamente no se ha utilizado. Así que no sé por qué sale en log. 
Ejemplo: 

COM/00196 | ES0022000006617857XP |   |   | Error, la suma de sobrecostes del TE es 0 para el día 15/02/18 hora 15:00:00

**Comment by PKFEric** [comment]
enviado excel por E-Mail

**Comment by bpesquero** [comment]
Eric, lo que habría que controlar son los precios, no los importes. Si pones el control sobre los importes lo que va a ocurrir es que siempre que la energía sea muy baja el importe va a ser próximo a cero. Esto va a pasar en todas las facturas en las horas nocturas. A mi lo que me interesa saber es si los precios que estoy utilizando son 0.

**Comment by PKFEric** [comment]
Ya esta modificado, ahora controlo los precios en vez de los importes.
