### ISSUE TITLE
Errores en carga de datos esios

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#294]
He comprobado que, de las últimas cargas, que detallo a continuación, los datos del Pool son cero cuando el fichero de REE no lo es.
C5_201702
A5_201703
C4_201705
C3_201703

**Comment by PKFEric** [comment]
Al reimportar esto se arregla hemos tiene pinta de ser un problema de conexion con NI.

**Comment by PKFEric** [comment]
Estamos creando un control para verificar esto.

**Comment by PKFEric** [comment]
Ya esta creado el control. En el mail explico como funciona.

**Comment by bpesquero** [comment]
Necesitaríamos añadir en el log la prelación y la prelación máxima para ese periodo.

**Comment by PKFEric** [comment]
Ya estan añadidos esos dos campos.
