### ISSUE TITLE
Campo "d" erroneo en liquidación descargada de la web

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#297]
Al descargar de la web de representación las liquidaciones asociadas a una factura el campo D que se muestra es incorrecto. Parece que se redondease a entero sin decimales.
Ejemplo:
factura SOLBA/2018003
CIL ES0021000013402825MD1F001
La de tiene el valor 0,576 y en el excel de liquidaciones se descarga 1

**Comment by aparras** [comment]
Ya hemos modificado y realizado la prueba que comentas acerca de esta tarea.

**Comment by bpesquero** [comment]
Comprobado y ok
