### ISSUE TITLE
Informe de Previsión: Matriz de Consumo

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#298]
Plan de pruebas de comprobación de Informes

**Comment by JMunoz17** [comment]
Pruebas enviadas.

**Comment by fmsanudo** [comment]
Cambiados los criterios de selección de los periodos, queda pendiente la comprobación de los resultados

**Comment by fmsanudo** [comment]
Resultados comprobados sin considerar el filtro de cartera activa en cada fecha de la medida.
