### ISSUE TITLE
Informe de Previsión: Inventario

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#299]
Plan de prueba de comprobación de informes

**Comment by fmsanudo** [comment]
Tras confirmar la exactitud de los datos ofrecidos por el informe de partida se analizará la sensibilidad del informe ante:
- Cambios de potencia
- Cambios de titularidad y fechas en contratos
- Incorporación de medidas
- Cambio de check en punto con equipo de medida
- Tiempo de ejecución ante intervalo largo

Posteriormente, se incorporarán los datos de HECEN

**Comment by JMunoz17** [comment]
Pruebas enviadas.

**Comment by fmsanudo** [comment]
Se reactiva.

En el entorno de producción y para HECEN, nos hemos dado cuenta de que en la agrupación de los datos del informe se tiene en cuenta el período del equipo de medidas cuando todas las agregaciones se tendrían que realizar atendiendo a los periodos tarifarios.
