### ISSUE TITLE
dirección en factura

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#30]
La dirección en la factura no aparece correcta, sólo coge el campo dirección, ni el de número ni portal...

**Comment by bpesquero** [comment]
llevar la dirección correcta a prefactura e histórico de facturas. Controlar que aparezca el portal en mayúsculas en todas las direcciones.

**Comment by PKFEric** [comment]
MODIFICADO-> PROBAR-AL SUBIR WEB
