### ISSUE TITLE
Informe de Previsión: Detalle medidas

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#300]
Plan de prueba de comprobación de informes

**Comment by JMunoz17** [comment]
Pruebas enviadas.

**Comment by fmsanudo** [comment]
Situación actual 08.05.18

. Valores iniciales para las pruebas comprobados, queda pendiente la revisión de pruebas
. Se han planteado una serie de preguntas sobre el funcionamiento de las tablas que se van resolviendo progresivamente. Entre otras:
- Funcionamiento de los comandos de Cálculo de Tipo de Medida y Actualización de Período y Coef de Pérdidas.
- Consideración de la prelación en los datos esios.
- Relación entre las tablas para consultas SQL

. Comprobados que los tiempos son asumibles, se modifica el informe para que aparezca la información en vertical y no en matriz, añadiendo el periodo

**Comment by JMunoz17** [comment]
Situación actual 14.05.18

Modificado el informe para que la distribución aparezca de forma que las tarifas sean las columnas y la fecha/hora las filas. Añadida la columna que mostrará el valor del periodo por tarifa, fecha y hora.

Resueltas las dudas vía mail.

**Comment by fmsanudo** [comment]
Realizadas las primeras comprobaciones del informe, los datos iniciales son consistentes con la información disponible en la base de datos y las pruebas realizadas se han validado.

Se solicita:
- Modificación del orden de las tarifas presentadas de tal forma que el orden sea:
2.0A / 2.0DHA / 2.0DHS / 2.1A / 2.1DHA / 2.1DHS / 3.0A / 3.1A / 6.1A / 6.1B y demás 6 tal como aparecen ahora
- Cuestión de redondeo en la elevación a BC. Redondeo de cada hora y punto a nivel de watio. La aplicación del mismo coeficiente para cada punto debería generar un valor más próximo al publicado por el OS. Por ejemplo, 2.0A en fecha 01.11.2017 hora 0 debería ser más próximo a 7,40 en vez de a 7,39.

- Ampliar las pruebas con un cambio de tarifa en contrato.
- Valoración de tiempos con lecturas de HECEN.

**Comment by fmsanudo** [comment]
Se actualiza la situación en el entorno de producción.

+ Se requiere, al igual que en otros informes, un combo de selección para poder discriminar GEO, HECEN o Ambas
+ Los períodos que aparecen en el informe y sobre los que se realizan las agregaciones deben ser los tarifarios, no los del equipo de medida

**Comment by fmsanudo** [comment]
Actualización a 11.09

Los resultados obtenidos en el informe son correctos, si bien se ha detectado un posible problema derivado del perfilado y la carga de los F5D que se encuentra en análisis por ATTEST
