### ISSUE TITLE
Eliminar del pdf de la factura el destino de importe de la factura para >=15kW

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#303]
En el pdf  de factura el destino de importe de factura sólo debe aparecer para suministros con menos de 15 kW de potencia contratada. Es decir, para tarifas 20Am 20DHA, 20DHA, 31A, 21DHA, 21DHS.

**Comment by jorgereal** [comment]
¿Esta modificación aplica tanto a GEOATLANTER como a HECEN?

**Comment by bpesquero** [comment]
Si, a  las dos empresas

**Comment by jorgereal** [comment]
Se han modificado los formatos de factura en GEOATLANTER y HECEN para que no se muestre el cuadro de "destino de importe" siempre que:
el Pci de los precios de contrato para el contrato y fecha inicio del documento no supere 15kW en ninguno de sus periodos.

Se ha subido a PRE.

**Comment by bpesquero** [comment]
Jorge, es exactamente a revés, no tiene que mostrarse cuando algunas de las potencias supere los 15 kW.
En cualquier caso es mejor hacerlo a través de la tarifa de acceso como proponía en la descipción de la incidencia porque puede que haya potencias por debajo de 15, pero tarifa 31A y en ese caso tampoco hay que mostrarlo. 
Creo que es más facil mostrarlo cuando las tarifas sean: 20A, 20DHA, 20DHS, 21A, 21HA, 21DHS

**Comment by jorgereal** [comment]
Se han modificado los formatos de factura en GEOATLANTER y HECEN para mostrar el cuadro de "destino de importe" en función de la tarifa según el criterio especificado.

Subido a PRE.

**Comment by bpesquero** [comment]
He hecho pruebas pero tengo dudas. Con las facturas antiguas me tendría que salir bien? Quiero decir, es algo que se pinta en el aire o que que queda como información de la factura registrada.
Lo digo porque al hacer la prueba con facturas antiguas veo que sale en todos los casos


20A | COM/00021 | C/20160363
-- | -- | --
2.0DHA | COM/00048 | C/20180557
2.1A | COM/00074 | C/20180407
2.1DHA | COM/00073 | C/20170711
3.0A | COM/00066 | C/20180448
3.1A | COM/00062 | C/20180625
6.1A | COM/00012 | C/20180659

**Comment by jorgereal** [comment]
Solo habíamos subido el desarrollo al entorno de PRE, lo hemos subido a PROD para que puedas hacer las pruebas con esas facturas.

**Comment by bpesquero** [comment]
Conmprobado y ok
