### ISSUE TITLE
Calculo de pérdidas con constante de lectura

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#304]
Cuando un punto de suministro es de alta medido en baja y además tiene constante de lectura, no se realiza bien el cálculo. Ahora mismo se hace lo siguiente

Consumo facturar= (consumo calculado + perdidas) * constante de lectura= (consumo calculado+ consumo calculado *0.04+ Nºhoras*VAStrafo*0.01)*constante de lectura

en realidad lo que debería hacerse es lo siguiente

Consumo facturar= consumo calculado*constante de lectura + pérdidas= consumo calculado*constante de lectura + consumo calculado*constante de lectura * 0.04+ Nº horas*VAStrafo*0.01

Es decir, las perdidas no se multiplican por la constante de lectura, y lo que si que hay que tener en cuenta es que cuando calculamos las pérdidas, el consumo al que hay que aplicar el 4% es el consumo calculado por la constante de lectura

Un ejemplo es el ES0306000000060062JP, aunque lo que he hecho para facturar correctamente es cambiar en el cierre las pérdidas de forma manual.

**Comment by jorgereal** [comment]
Se ha modificado el cálculo de las pérdidas y el cálculo del consumo a facturar para adaptarse a las nuevas fórmulas.

Subido a PRE y PRO.

**Comment by bpesquero** [comment]
He probado en PRE cargando el peaje y se siguen calculando mal las pérdidas. Se puede ver en la tabla de medidas de peaje, para el nº de solictud 201800012529. Lo que hay en PRE es lo que se ha calculado y lo que hay en PRO es lo que calculé yo a mano que es el valor correcto

**Comment by jorgereal** [comment]
Hemos revisado el caso que nos mencionas, para la AE el valor de las perdidas es 749 en PROD y 1498 en PRE.

Para nuestro calculo aplicamos la siguiente fórmula:
Perdidas = (0.04 * ConsumoCalculado * cteLectura)+(0.01 * (VasTrafo/1000)* horas)

ConsumoCalculado = 1024
cteLectura = 2
VasTrafo = 100000
Horas = 1416 (59 días)

Con estos valores el resultado obtenido nos parece correcto, ¿hay algún error en la fórmula?

**Comment by bpesquero** [comment]
Hola, está bien en PRE, lo que ocurre es que en PROD yo metí también ese valor a mano para facturar, de hecho si veis la energía de la factura de venta se ve que se hizo con ese valor, pero ahora vuelve a aparecer el valor calculado inicialmente, no sé si habéis hecho alguna prueba que se haya cambiado por eso. Por ese motivo me ha llevado a error, porque lo que hice fue comparar el valor el PRE con el de PROD entendiendo que en PROD seguía el valor que yo había metido a mano.
En cualquier caso, me podéis confirmar si lo habéis cambiado vosotros en PROD? Habría que volver a poner en el cierre en el campo pérdidas el valor correcto.

**Comment by jorgereal** [comment]
En PROD no hemos cambiado nada, si quieres ponemos el valor de las perdidas del cierre correctas, las que hay en PRE.

**Comment by bpesquero** [comment]
Ok.

**Comment by jorgereal** [comment]
Hemos corregido el dato en PROD, marcamos la tarea como realizada.
