### ISSUE TITLE
Nuevo criterio de facturación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#305]
Incluye  las tareas: #230 , #270, #278, #257, #256. Se cierran al abrir esta.
Fichero F con dos cierres
factura regularizadora y rectificadora
ambio pdf factura Geo y HECEN
Ficheros F1 con facturación por tramos
Ficheros F con fechas del TE diferentes a las fechas de la factura

**Comment by bpesquero** [comment]
EStamos viendo facturas de abono de distribuidores que le ponen importe negativo, en vez de positivo al tratarse ya en si mismo de un abono. No tengo la seguridad de que sea en todos. Habría que poner un control que si tenemos un abono con importe negativo escriba en el log, al menos para que podamos mirarlo y ver si realmente el importe es negativo o no.

--MODIFICADO

**Comment by bpesquero** [comment]
Otra cuestión de las facturas regularizadoras (G). El consumo tiene que tomarlo por diferencias con le consumo de las anteriores facturas de peaje regularizadas. Una factura regularizadora puede regularizar a varias facturas, por tanto hay que buscar a todas las que regulariza por fechas. Lo que hay que hacer es coger el consumo calculado del cierre de todas las regularizadas y restarselo al consumo calculado que aparezca en la regularizadora. El consumo podría llegar a ser negativo.
--MODIFICADO

**Comment by bpesquero** [comment]
Envío por mail detalle de ficheros F1 que dan problema en la carga con motivo de las nuevas comprobaciones

**Comment by bpesquero** [comment]
REvisar control de fechas en TP (ejemplo :ID_GeoAtlanter,   S.L._03180516030327040_F1_013_2.xml
ID_GeoAtlanter,   S.L._03180510030089941_F1_011_0.xml)
Revisar factura regularizadora el cierre de la factura anterior es distnto de cero. Ejemplo contrato 

COM/00134
--MODIFICADO

**Comment by bpesquero** [comment]
Envío por mail de detalle de ficheros F1 que dan problemas en la carga con motivo de las nuevas comprobaciones

**Comment by bpesquero** [comment]
Error de venta en facturas HECEN. Enviado mail con detalla
Venta HECEN HECEN/08675 y HECEN/07875

HECEN/08675 | ES0022000005434069SF | Error, una o ambas fechas del Término de Potencia es vacia.
-- | -- | --
HECEN/07875 | ES0022000005443785TV | Error, una o ambas fechas del Término de Potencia es vacia.

--MODIFCADO

**Comment by PKFEric** [comment]
Esta tarea ya la podemos cerrar para abrir incidencias aisladas, todo lo que se pedia aqui ya esta realizado
