### ISSUE TITLE
Error informe IMU HECEN

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#307]
Enviado por mail

**Comment by PKFEric** [comment]
Ya esta arreglado, existia un problema con el Nº de Linea del Impuesto electrico, el de Geo no es el mismo que el de HECEN, por lo tanto cogía la suma de los conceptos mal.

Te envío el detalle de las facturas que se han contabilizado para ARANZUEQUE.

El importe de la factura menos el IE y menos el Alquiler y menos el Supl territorial tiene que coincidir con el resultado del informe.

En el excel que nos has enviado el Suplemento territorial no esta bien, ejemplo H/2017042663, esta factura no tiene suplemento pero en el exel aparece.

Por otro lado, ya sabes que para sacar el IMU me hice una tabla con desglose de todas las facturas, si necesitas tener ese desglose para alguna localidad mas me lo tienes que avisar para que lance yo el informe con mi licencia que sino no se puede.

**Comment by bpesquero** [comment]
ERic, me puedes pasar el detalle de ARanzueque?

Gracias

Belén Pesquero Fernández
GeoAtlanter, S.L.
bpesquero@geoatlanter.com
Tlf. +34 91 7378443
Avda. de Europa, 34-B Esc. Dcha. 3º
28023 - Madrid

AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener
información confidencial sometida a secreto social. No está permitida su
reproducción o distribución sin la autorización expresa de GEOATLANTER SL.* *Si
usted no es el destinatario final por favor elimínelo e infórmenos por esta
vía.*

*De acuerdo con lo establecido por la Ley Orgánica 15/1999, de 13 de
diciembre, de Protección de Datos de Carácter Personal (LOPD), le
informamos que sus datos están incorporados en un fichero del que es
titular GEOATLANTER SL* *con la finalidad de realizar la gestión
administrativa, contable y fiscal, así como enviarle comunicaciones
comerciales sobre nuestros productos y/o servicios.*

*Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, cancelación y oposición de sus datos en el domicilio
de GEOATLANTER SL*
*sito en: Avda. de Europa 34B
<https://maps.google.com/?q=Avda.+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha. 3º,  28023 Madrid.*

**Comment by bpesquero** [comment]
Se detecta el problema y se propone un cambio en el informe. EL problema básicamente consiste en que el suplemento territorial en unas facturas está por encima y en otras por debajo del impuesto eléctrico
Envío documento corregido por mail

Se propone además cambiar el informe de exportación de facturas, ya que en el alquiler de equipo de medida de la compra está incluyendo el suplemento territorial. Se propone separar los dos conceptos

**Comment by JMunoz17** [comment]
Hemos corregido el informe del IMU para evitar el problema con el suplemento territorial y hemos cambiado el informe de exportación de facturas para que la columna "Alquier de Equipo de Medida" no incluya el valor del suplemento territorial.

**Comment by bpesquero** [comment]
No puedo ejecutar el informe de IMU, Me da el siguiente error
![image](https://user-images.githubusercontent.com/20299071/37704679-c7be911e-2cf9-11e8-8465-ea6196045904.png)

**Comment by JMunoz17** [comment]
Puedes probar ahora Belén.
