### ISSUE TITLE
contrato en pdf

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#31]
En el contrato en pdf la dirección apare incorrecta. EL portal debe ir a continuación del número no al final.

Por otra parte el contrato aparece cortado en el margen derecho y no se lee entero. Te lo envío por correo

**Comment by PKFEric** [comment]
CORREGIDO PORTAL->PROBAR
APARECE CORTADO-> AUN NO CORREGIDO

**Comment by PKFEric** [comment]
CORREGIDO APARECE CORTADO-> PROBAR

**Comment by bpesquero** [comment]
Probado y OK
