### ISSUE TITLE
problema mail comunicación impago

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#310]
No están saliendo los mails con las comunicaciones de impago cuando hay una devolución.
Ejemplo COM/00066

**Comment by PKFEric** [comment]
Enviar primer mail impago. desde Gestion de Cobros. Mail menos 10 se envia bien.

Al generar la carta en Roles de menos de 10 es la de mas de 10.

Cuando genera la carta en Roles en la parte de arriba de la carta tiene que poner la direccion de envio / para el contrato 267 mezclo la calle de suministro con la de envio. 

Plura y no plural dependiendo de facturas si es una o varias.

**Comment by bpesquero** [comment]
Ahora da este error
![image](https://user-images.githubusercontent.com/20299071/39120666-5dbe47f4-46ef-11e8-9b04-f595b302ae66.png)

**Comment by bpesquero** [comment]
Al envíar el primer mail de impago da este error

![image](https://user-images.githubusercontent.com/20299071/40916907-cc40c02a-6801-11e8-93fd-fc356a58adc9.png)

**Comment by bpesquero** [comment]
Se pasa al proyecto de modificar toda la gestión de cobros
