### ISSUE TITLE
Error al hacer factura de venta

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#312]
TEnemos varias facturas que dan error al hacer la venta

Nº contrato | CUPS | Fecha desde | Fecha hasta | Error/Aviso
-- | -- | -- | -- | --
COM/00264 | ES0021000011250664CG | 20/01/18 | 21/03/18 | Error, Las medidas Perfil 332,999999999999986, de la factura FV/201801474 para el contrato COM/00264 no se corresponden con el termino de Energia 332,999999999999986
COM/00337 | ES0021000004254895PF | 24/01/18 | 20/03/18 | Error, Las medidas Perfil 338,999999999999989, de la factura FV/201801490 para el contrato COM/00337 no se corresponden con el termino de Energia 338,999999999999989
COM/00378 | ES0021000016489925EA | 17/02/18 | 19/03/18 | Error, Las medidas Perfil 9.135,00000000000018, de la factura FV/201801494 para el contrato COM/00378 no se corresponden con el termino de Energia 9.135,0000000000001

**Comment by PKFEric** [comment]
Ya esta corregido, el unico error que da es en el  COM/00378

Nº contrato | CUPS | Fecha desde | Fecha hasta | Error/Aviso
-- | -- | -- | -- | --
COM/00378 | ES0021000016489925EA |   | ERROR,La potencia facturada 37,1 del peaje en el periodo 1 es diferente   de la potencia facturada 37,101 y el contrato NO permite DIFERENCIA DE   POTENCIA
COM/00378 | ES0021000016489925EA |   | ERROR,La potencia facturada 37,1 del peaje en el periodo 2 es diferente   de la potencia facturada 37,101 y el contrato NO permite DIFERENCIA DE   POTENCIA
COM/00378 | ES0021000016489925EA |   | ERROR,La potencia facturada 70,34 del peaje en el periodo 3 es diferente   de la potencia facturada 70,339 y el contrato NO permite DIFERENCIA DE   POTENCIA

**Comment by PKFEric** [comment]
Esta redondeada la comparacion a 3 decimales

**Comment by PKFEric** [comment]
Estan las 3 facturas en prefactura de venta
