### ISSUE TITLE
Facturación Venta HECEN

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#314]
Todos los contratos facturados en el día de hoy están dando este error

Nº contrato | CUPS | Fecha desde | Fecha hasta | Error/Aviso
-- | -- | -- | -- | --
HECEN/07768 | ES0021000004988396KS | 17/02/18 | 24/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 108
HECEN/07874 | ES0021000004988400KL | 21/01/18 | 24/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 403
HECEN/07885 | ES0021000017475920LB | 27/02/18 | 26/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 102
HECEN/07893 | ES0031103016311001BR | 01/03/18 | 31/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 17.247
HECEN/07922 | ES0021000002572752BS | 05/03/18 | 27/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 311
HECEN/07941 | ES0021000011314911FN | 28/02/18 | 28/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 19
HECEN/08118 | ES0022000005643715EP | 16/02/18 | 20/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 326
HECEN/08176 | ES0022000009067292VN | 27/02/18 | 18/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 535
HECEN/08177 | ES0022000009067323HC | 27/02/18 | 18/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 772
HECEN/08317 | ES0022000007534341KB | 20/02/18 | 18/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 16
HECEN/08318 | ES0022000008472885WV | 27/02/18 | 18/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 1.235
HECEN/08359 | ES0021000016455991HV | 27/02/18 | 27/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 148
HECEN/08418 | ES0022000009072597HG | 28/02/18 | 18/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 9
HECEN/08473 | ES0021000004407889JM | 23/02/18 | 25/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 23
HECEN/08509 | ES0021000015964601CE | 27/02/18 | 27/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 151
HECEN/08628 | ES0021000003088409YN | 27/02/18 | 27/03/18 | Error, La suma de la energia del detalle 0 es diferente de la Energia de Termino de potencia 22

**Comment by PKFEric** [comment]
Es un control nuevo que he metido, que no aplica a los tipos 1. Mañana a primera hora lo arreglo.

**Comment by PKFEric** [comment]
Ya esta solucionado el tema de los controles que he añadido de los comento en la tarea #253
