### ISSUE TITLE
aceptación y activacion de C2

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#315]
Al procesar el fichero de aceptación y/o de activación de un C2 con sólo cambios administrativos no se comprueba que la tarifa aceptada sea la misma que la del contrato.
Ejemplo COM/00439

**Comment by PKFEric** [comment]
Se ha modificado, tanto en el C2 02 Aceptacion como en el C2 05 Activacion, no obstante en el C2 05 Activacion existia un control que comprobaba el codigo de ATR del fichero con el del contrato, se ha modificado para que lo compruebe solo en el caso en el que el Cambio sea administrativo 'S'.

**Comment by PKFEric** [comment]
La validacion estaba hecha en los 05 ahora tambien en los 02 tanto de ATR como de Potencia.
