### ISSUE TITLE
Control de Potencia Facturada en Venta

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#316]
No está saltando el control de potencia en el contrato COM/00256. La potencia facturada en venta no coincide con la potencia facturada en compra. No ha saltado nunca el error. Lleva pasando desde el inicio de contrato (01/08/17)

**Comment by PKFEric** [comment]
Este contrato deberia de tener maximetro, y el tipo de contrato 005 no tiene Maximetro, por lo tanto se comprueba la potencia facturada en venta con la potencia contratada del peaje, y no con la potencia a facturar.

**Comment by bpesquero** [comment]
Añadir un control al cargar el fichero F1 de tal forma que si el campo modocontrolpotencia toma el valor 2 (maxímetro) el tipo de contrato asociado al contrato para esa fecha debe tener marcado el check de maxímetro.

**Comment by PKFEric** [comment]
Se ha añadido un control en la importacion de los F1 de tal manera que:

Si el ModoControlPotencia = 1 -> El contrato tiene que ser "Sin Maximetro"
Si el ModoControlPotencia = 2 -> El contrato tiene que ser "Con Maximetro"

En caso de que no se cumpla esto dara un error en la importacion del XML
