### ISSUE TITLE
error factura de compra FCR/20180938 - COM/00424

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#318]
Factura de compra FCR/20180938 del contrato COM/00424, Tiene dos cierres, se carga sin problema, se factura sin problemas. después se ve que tiene dos cierres  y que en NAV sólo se cargó uno, y por tanto se ha facturado mal.

**Comment by bpesquero** [comment]
Vuelve a pasar lo mismo con la factura FC/20181550, aún no registrada. 
el único error que da es 

COM/00424 | ES0021000005425100XH | No coinciden los datos de cierre 117 y peaje 78 en Potencia demandada.
-- | -- | --
COM/00424 | ES0021000005425100XH | No coinciden los datos de cierre 132 y peaje 86 en Potencia demandada.

**Comment by PKFEric** [comment]
Hola Belen, lo he estado mirando, el cierre esta bien, cuando vienen dos cierres se agrupan en uno solo. la suma de los dos cierres coincide ambos desglosados, el problema viene en que lo que se factua en el peaje en el periodo 1 no coincide con lo que viene en el cierre en el perido 1+4. Si mañana tienes tiempo pegame un toque y lo miramos juntos.

**Comment by bpesquero** [comment]
Hola Eric, te he llamado pero no te he localizado. A las 11.00 me marcho de
la ofi y no sé a qué hora volveré, así que te cuento por mail.

Dos cuestiones:

1.- Los máximetros de dos cierres no pueden sumarse, hay que calcular el
maximo. En energia activa el total consumido es la suma de lo que
consumiste con el contador1 y lo que consumiste con el contador2, pero si
hablamos de potencia máxima, la potencia máxima será el máximo entre la
potencia máxima con el contador 1 y la potencia máxima con el contador 2.
Me he explicado?
2.- El siguiente problema que tu comentabas es que el contador anterior
parece que estaba mal programado y guardaba en periodo 6 lo que debería
guardar en 3, por eso que no te cuadra. Pero bueno, eso es un problema
particular de este contrato. Lo que no sé es por qué no saltó el control de
la energía facturada para algoritmo VI coincide con el cierre. Lo podrías
mirar?

Gracias

Belén Pesquero Fernández
GeoAtlanter, S.L.
bpesquero@geoatlanter.com
Tlf. +34 91 7378443
Avda. de Europa, 34-B Esc. Dcha. 3º
28023 - Madrid

AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener
información confidencial sometida a secreto social. No está permitida su
reproducción o distribución sin la autorización expresa de GEOATLANTER SL.* *Si
usted no es el destinatario final por favor elimínelo e infórmenos por esta
vía.*

*De acuerdo con lo establecido por la Ley Orgánica 15/1999, de 13 de
diciembre, de Protección de Datos de Carácter Personal (LOPD), le
informamos que sus datos están incorporados en un fichero del que es
titular GEOATLANTER SL* *con la finalidad de realizar la gestión
administrativa, contable y fiscal, así como enviarle comunicaciones
comerciales sobre nuestros productos y/o servicios.*

*Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, cancelación y oposición de sus datos en el domicilio
de GEOATLANTER SL*
*sito en: Avda. de Europa 34B
<https://maps.google.com/?q=Avda.+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha. 3º,  28023 Madrid.*

**Comment by bpesquero** [comment]
Dos cuestiones:

1.- Los máximetros de dos cierres no pueden sumarse, hay que calcular el maximo. En energia activa el total consumido es la suma de lo que consumiste con el contador1 y lo que consumiste con el contador2, pero si hablamos de potencia máxima, la potencia máxima será el máximo entre la potencia máxima con el contador 1 y la potencia máxima con el contador 2. Me he explicado?
2.- El siguiente problema que tu comentabas es que el contador anterior parece que estaba mal programado y guardaba en periodo 6 lo que debería guardar en 3, por eso que no te cuadra. Pero bueno, eso es un problema particular de este contrato. Lo que no sé es por qué no saltó el control de la energía facturada para algoritmo VI coincide con el cierre. Lo podrías mirar?

**Comment by PKFEric** [comment]
Para el punto 1 ya lo he corregido y lo que hago es si hay cambio de contador.

1. Para Potencia

Si ModoControlPotencia = 2 (Maximetro) => se coge el maximo de cada contador para cada periodo.
Si ModoControlPotencia = 1 (Sin Maximetro) => se suman las potencias de cada periodo

2. Para energia

Tanto en un caso como en otro se suman las energías de cada periodo de cada contador.
Energia Periodo(n) = Energia Periodo(n) Contador 1 + Energia Periodo (n) Contador 2

     

Esta es la energia del peaje y la suma de las energias del cierre por el periodo

  | PEAJE | CIERRE
-- | -- | --
P1 | 19203 | 19.203
P2 | 30348 | 30.348
P3 | 17037 | 240
P4 |   | 0
P5 |   | 0
P6 |   | 16.797
TOTAL | 66588 | 66.588

La energia esta bien por eso no salto el control y la energia que facturas en venta es la energia de la medida no la del peaje.

**Comment by PKFEric** [comment]
Creo que eso es lo que me preguntabas no se si te respondi bien :)

**Comment by bpesquero** [comment]
PErfecto, pero lo del tema de potencia se hace con el máximo independientemente de si se factura con maxímetro o no. La magnitud es potencia máxima, y por tanto la agregación de dos cierres siempre tiene que calcularse con el máximo de ambos cierres, la forma en que después se facture el contrato es otra cosa.

**Comment by PKFEric** [comment]
Ya esta modificado para que en caso de que haya dos contadores la potencia se calcule como el maximo de las potencias de cada periodo de cada contador.
Independientemente de si es con o sin maximetro
