### ISSUE TITLE
dirección

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#32]
La dirección aparece mal finalmente en casi todos los sitios donde miro. 
En la pantalla de contratos aparece mal, sólo aparece la calle, nada más, En detalles de contrato aparece mal, el portal debe ir a continuación del nº no al final.
Como he comentado en los anteriores aparece tb mal en el contrato en pdf y en la factura
También es incorrecta en la pantalla de facturas, sólo aparece la calle no el resto de campos

**Comment by PKFEric** [comment]
CORREGIDO EN TODO MENOS EN LA TABLA DE FACTURAS-> PROBAR

**Comment by PKFEric** [comment]
CORREGIDO EN TABLA DE FACTURAS-> REGISTRAR UNA FACTURA PARA QUE SE LLEVE LA DIRECCION.
PROBAR
