### ISSUE TITLE
Error al generar A3

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#320]
Al generar un A3 da error de que no se ha indicado el CNAE. ¿De qué forma podemos indicarlo en la ficha de contrato?

gracias

**Comment by JMunoz17** [comment]
El error se produjo debido a que no estaban actualizados los ficheros de los esquemas contra los que se validan los XML generados desde Navision. Esto se solventó a través de otra incidencia y posteriormente el usuario pudo generar A3 sin problemas.
