### ISSUE TITLE
sacar campo CUPS o contrato en los movimientos de proveedores

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#321]

**Comment by jorgereal** [comment]
Se ha creado el campo "No. Contrato" en los movimientos de proveedor.
Se ha añadido el código para que se vaya rellenando automáticamente y se ha pasado un proceso en PRE para rellenarlo en los movimientos de 2017.

Subido a PRE.

**Comment by bpesquero** [comment]
Lo puedes subir a producción, por favor?

**Comment by jorgereal** [comment]
Se ha subido a PROD y se ha pasado un proceso para rellenar el campo "No. Contrato"  en los movs de proveedor existentes en las empresas de GEOATLANTER y HECEN.

**Comment by bpesquero** [comment]
No lo veo ni en prod ni en pre, ni sacado en el informe ni entrando en el designer. EStá en la tabla de movimientos?

**Comment by jorgereal** [comment]
Está en la tabla 25, movimientos de proveedor, lo acabamos de sacar también en el formulario.
