### ISSUE TITLE
error potencia factura de venta FV/201801770

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#323]
AL facturar la venta del contrato COM/00122, genera una factura(FV/201801770) en la que las potencias facturas no se corresponden con el cierre.
Yo he estado revisando y no entiendo lo que hace la venta

 Además da el siguiente error

Nº contrato

CUPS

Error/Aviso

COM/00122

ES0022000008397502ZM

ERROR,La potencia facturada 15,443 del peaje en el periodo 1 es diferente de la potencia facturada 11,778 y el contrato NO permite DIFERENCIA DE POTENCIA

COM/00122

ES0022000008397502ZM

ERROR,La potencia facturada 27,67 del peaje en el periodo 2 es diferente de la potencia facturada 14,723 y el contrato NO permite DIFERENCIA DE POTENCIA

**Comment by PKFEric** [comment]
Esta tarea esta aplicando lo que desarrollamos en #258 la procedencia desde de la medida de potencia es 99

**Comment by PKFEric** [comment]
La historia es que en lectura desde es 99 pero en lectura hasta es 30 entonces. No se como aplica esto. si solo deberia de hacerse en caso de que ambas sean 99?

**Comment by bpesquero** [comment]
Para la magnitud potencia máxima, que es la que nos importa, la procedencia que nos importa es la de lectura hasta. Pero en cualquier caso, yo abro el fichero y veo la procdencia 30 tanto en la lectura desde como en la lectura hasta.

**Comment by PKFEric** [comment]
En el fichero SCTDE_F1_01_0022_0587_20180412135903743_(653191672).xml la procedencia desde de la potencia (PM) es 99 lo voy a cambiar en el codigo para que solo verifique que el valor a tener en cuenta para hacer el calculo sea la procedencia Hasta.

**Comment by bpesquero** [comment]
ok

**Comment by PKFEric** [comment]
Modificado y creada la factura estoy pendiente de hablar con MONICA.
