### ISSUE TITLE
Enlaces a redes sociales en web próxima

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#324]
Incluir los iconos de redes sociales en la web, en el Footer (Facebook, Twitter y Google+)

Facebook: https://www.facebook.com/proximaenergia/

Twitter: https://twitter.com/proximaenergia

Google+: https://plus.google.com/114547235710296874519

**Comment by PKFEric** [comment]
Ya esta añadido podeis verlo en la web. Las imágenes son de 32x32 pixeles, se pueden cambiar, si nos pasáis unas imágenes vosotros las ponemos.
