### ISSUE TITLE
error calculo ajuste de potencia COM/00424

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#326]
Al forzar facturación del contrato COM/00424 del 20/02/2018 al 28/02/2018 el ajuste de potencia no se calcula bien.
Los maxímetros son:

  | Maximetros | Potencia contratada | Potencia a facturar | Ajuste
-- | -- | -- | -- | --
P1 | 117 | 50 | 129 | 79
P2 | 132 | 50 | 153 | 103
P3 | 53 | 50 | 54 | 4

Los ajustes de la factura son 79,79 y 103

**Comment by PKFEric** [comment]
Esto ya esta solucionado, la factura en venta es FV/201802033 que ya deberia de salir con los valores correctos y coge el peaje Rectificativo.

Para ello, lo que se ha hecho es lo siguiente:

Si llega un F1 de tipo R rectificando a un F1 ya insertado en NAV y ademas las fechas de la factura rectificativa coinciden con las fechas del F1 que se esta rectificando, se marcara el F1 rectificado como Bloqueado. 

De esta manera no se utilizara el F1 rectificado en la facturacion
