### ISSUE TITLE
Forzar facturación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#327]
Al forzar la facturación de una serie de contratos para el mes de diciembre de 2017 están saliendo los siguientes errores

Nº contrato | Fecha desde | Fecha hasta | Log |  
-- | -- | -- | -- | --
COM/00212 | 09/11/2017 | 11/12/2017 | Ya existe el/la Hour Measure Header Origen Datos='Perfil',CUPS='ES0021000000378776WD',Nº Contrato='COM/00212',Fecha='09/11/17',Nº factura acceso CCH='20171212030152076'. | Origen Datos='Perfil',CUPS='ES00210000003786
COM/00212 | 12/12/2017 | 08/01/2018 | Ya existe el/la Hour Measure Header Origen Datos='Perfil',CUPS='ES0021000000378776WD',Nº Contrato='COM/00212',Fecha='12/12/17',Nº factura acceso CCH='03180109030122217'. | Origen Datos='Perfil',CUPS='ES00210000003786
COM/00213 | 09/11/2017 | 11/12/2017 | Ya existe el/la Hour Measure Header Origen Datos='Perfil',CUPS='ES0021000000378777WX',Nº Contrato='COM/00213',Fecha='09/11/17',Nº factura acceso CCH='20171212030152075'. | Origen Datos='Perfil',CUPS='ES00210000003787
COM/00213 | 12/12/2017 | 08/01/2018 | Ya existe el/la Hour Measure Header Origen Datos='Perfil',CUPS='ES0021000000378777WX',Nº Contrato='COM/00213',Fecha='12/12/17',Nº factura acceso CCH='03180109030122216'. | Origen Datos='Perfil',CUPS='ES00210000003787
COM/00214 | 15/11/2017 | 14/12/2017 | Ya existe el/la Hour Measure Header Origen Datos='Perfil',CUPS='ES0021000002928194DS',Nº Contrato='COM/00214',Fecha='15/11/17',Nº factura acceso CCH='20171215030393067'. | Origen Datos='Perfil',CUPS='ES00210000029281
COM/00214 | 15/12/2017 | 11/01/2018 | Ya existe el/la Hour Measure Header Origen Datos='Perfil',CUPS='ES0021000002928194DS',Nº Contrato='COM/00214',Fecha='15/12/17',Nº factura acceso CCH='03180112030407988'. | Origen Datos='Perfil',CUPS='ES00210000029281
COM/00215 | 15/11/2017 | 14/12/2017 | Ya existe el/la Hour Measure Header Origen Datos='Perfil',CUPS='ES0021000002928170PZ',Nº Contrato='COM/00215',Fecha='15/11/17',Nº factura acceso CCH='20171215030311704'. | Origen Datos='Perfil',CUPS='ES00210000029281
COM/00215 | 15/12/2017 | 11/01/2018 | Ya existe el/la Hour Measure Header Origen Datos='Perfil',CUPS='ES0021000002928170PZ',Nº Contrato='COM/00215',Fecha='15/12/17',Nº factura acceso CCH='03180112030317988'. | Origen Datos='Perfil',CUPS='ES00210000029281

**Comment by jorgereal** [comment]
Existían medidas de tipo perfil en la nueva tabla de medidas para los contratos y fechas indicadas sin número de factura registrada, mientras que en la tabla antigua no había, esto producía el error al intentar calcular el perfilado.

Se han eliminado estas medidas y se ha forzado facturación para el contrato COM/00212, periodo 09/11/2017 -11/12/2017

**Comment by bpesquero** [comment]
Pero las nuevas tablas de medidas están en produccion?

**Comment by jorgereal** [comment]
Las nuevas tablas de medidas están en producción simplemente para ir almacenando datos, no se utilizan para ningún cálculo.

**Comment by bpesquero** [comment]
Por eso que no entiendo entonces lo que pasó?


Belén Pesquero Fernández
GeoAtlanter, S.L.
bpesquero@geoatlanter.com
Tlf. +34 91 7378443
Avda. de Europa, 34-B Esc. Dcha. 3º
28023 - Madrid

AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener
información confidencial sometida a secreto social. No está permitida su
reproducción o distribución sin la autorización expresa de GEOATLANTER SL.* *Si
usted no es el destinatario final por favor elimínelo e infórmenos por esta
vía.*

*De acuerdo con lo establecido por la Ley Orgánica 15/1999, de 13 de
diciembre, de Protección de Datos de Carácter Personal (LOPD), le
informamos que sus datos están incorporados en un fichero del que es
titular GEOATLANTER SL* *con la finalidad de realizar la gestión
administrativa, contable y fiscal, así como enviarle comunicaciones
comerciales sobre nuestros productos y/o servicios.*

*Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, cancelación y oposición de sus datos en el domicilio
de GEOATLANTER SL*
*sito en: Avda. de Europa 34B
<https://maps.google.com/?q=Avda.+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha. 3º,  28023 Madrid.*

2018-04-25 10:22 GMT+02:00 jorgereal <notifications@github.com>:
