### ISSUE TITLE
Error dirección envío de las facturas Próxima

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#328]
Después de que un cliente (COM/00477) nos haya llamado para indicarnos que en la factura que le hemos emitido, la dirección de envío no venía completa ( sólo la calle, sin nº ni piso), he detectado que hay fichas de contrato que en la pestaña dirección de envío, no enlazan con la dirección de envío que ha metido el cliente durante el proceso de alta. Pensando que sería un caso aislado, he ido comprobando uno por uno y he detectado que ha pasado lo mismo con los siguientes contratos ( que ya he modificado):

 

COM/00493; COM/00471; COM/00465; COM/00464; COM/00461 y su baja COM/00454;

 

Aparecen así (te adjunto pantallazo)  con el campo vacío. Si haces clic, y selecciones la dirección 1, ya te lo enlaza. Como tengo que ir uno por uno, por favor dime si quieres que continúe comprobando  los 400 contratos o si hay alguna forma más rápida de hacerlo

![image](https://user-images.githubusercontent.com/20299071/39237015-9cc23640-487a-11e8-83b5-c8c890b1f158.png)

**Comment by JMunoz17** [comment]
Estuvimos probando a darnos de alta desde la web teniendo en cuenta los diferentes casos posibles y en todos ellos el contrato se creaba con la dirección de envío asociada. 

Creemos que el problema estaba en que si accedíamos a la ficha del cliente desde la pestaña de cliente pagador en la ficha del contrato y al volver a la ficha de contrato lo hacíamos dando a aceptar desde la lista de clientes, se valida el cliente pagador en la ficha de contrato (aunque no haya cambiado) y esto hacia que nos validara como dirección de envío del contrato la dirección de envío genérica del cliente, que esta en casi todos los clientes vacía (todos menos 5).

Por lo que la dirección de envío del contrato quedaba vacía y la mayoría de los campos de envío se rellenaban a partir de los campos de la ficha del cliente (por eso piso, portal, escalera y número no estaban rellenos en estos casos).

Vamos a modificar la web para que al crear el cliente, se rellene como dirección de envío genérica la dirección de envío que se haya asociado al contrato y pasaremos un proceso para rellenar las direcciones de envío genéricas en los clientes que las tengan vacías.

Hemos pasado un proceso para rellenar en los contratos la dirección de envío asociada a su cliente.

Estos tres contratos no tienen ninguna dirección de envío asociada al cliente pagador, por lo que no tienen dirección de envío asociada.
COM/00009
COM/00057
COM/00256

Estos dos contratos tienen el mismo cliente pagador, el cual tiene dos direcciones de envío creadas. Si podéis revisarlo y asignar a cada contrato la dirección de envío que le corresponda.
COM/00270
COM/00301

**Comment by bpesquero** [comment]
Ok. Hemos revisado y corregidos los que faltaban.
