### ISSUE TITLE
Error al generar M1 con cambio de titular

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#329]
Creamos un M1 con cambio de titular, al dar a generar da el siguiente error
![image](https://user-images.githubusercontent.com/20299071/39422472-c402e172-4c6d-11e8-85b6-8b2b7d6ff9a3.png)

AL mirar el xml
<Cliente>
                        <IdCliente>
                                <TipoIdentificador>CI</TipoIdentificador>

Cuando debería ser CI

**Comment by JMunoz17** [comment]
Hemos estado mirándolo y el problema está en que cuando enviamos un M1 a acciones, si marcamos el check de cambio de titular y el cliente que seleccionamos es persona jurídica ponemos como identificador CI, mientras que en caso de que sea persona física ponemos NI.

![image](https://user-images.githubusercontent.com/26869276/39705034-7ead1250-520d-11e8-91e1-3d1f566f58a5.png)

Actualizaron los valores de la tabla de Ocsum correspondiente, eliminando varios (CI entre ellos). Estos son los valores que podemos utilizar. Necesitaría saber que valor asignar en caso de que se trate de persona jurídica.

![image](https://user-images.githubusercontent.com/26869276/39705240-18f6db48-520e-11e8-82e8-e67905662ea5.png)

**Comment by bpesquero** [comment]
NV

**Comment by JMunoz17** [comment]
Modificado en PRE y PROD.
