### ISSUE TITLE
Problema altas manuales

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#330]
para los casos en los que hay que crear un contrato a mano, y también el usuario web, nos pusistéis dos apartados en administración de gestión de usuarios en (www.proximaenergia.com/Administracion/LogIn), un checkbox para que en el momento de crear el usuario le enviemos un email al cliente detallándole sus datos de acceso ( usuario y clave) y dándole la bienvenida a la web; y uno para enviar el email de Registro de Usuario con el enlace de activación (una vez creado).

Ya ha ocurrido un par de veces, al crear un contrato a mano, y generar el usuario, hemos dado al checkbox de enviar email al usuario (Bienvenido , esta es tu clave y contraseña) y también el de enviar email de activación, para que haga clic en el enlace y me aparezca en el estado de la ficha como firmado, y no cambia, se mantiene como Pendiente de Firma.

En concreto el último, COM/00504, el cliente dice que ya hizo clic en el enlace y que ha entrado ya en la web logueándose , pero a mí me aparece el estado “Pendiente de firma” en su ficha. Cuando vuelve a hacer clic en el enlace, le dice que ya está activo, pero no cambia el estado del contrato a pendiente de firma.

**Comment by PKFEric** [comment]
Se ha modificado para que cuando se de de alta desde la zona privada un cliente no se active el cliente, que sea el mail de activacion el que active el usuario y modifique el contrato a firmado cliente

**Comment by bpesquero** [comment]
No entiendo, y cómo se hacía entonces antes?
Siempre la lógica fue esa, no? Con el mail de activación, mejor dicho cuando el usuario sigue la ruta de ese mail, se pasa el contrato a firmado cliente.
