### ISSUE TITLE
Error factura información del consumo eléctrico

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#333]
En el cuadro de información del contrato eléctrico de las facturas de HECEN las unidades del maxímetro no son kW, si no W. Se está cogiendo directamente el valor de consumo calculado del cierre, que es en W.
No he verificado si en Geo pasa lo mismo, pero supongo que sí.

**Comment by jorgereal** [comment]
Se han corregido las unidades del maxímetro para los formatos de factura y abono de GEO y HECEN.

Subido a PRE y PRO.
