### ISSUE TITLE
Factura por abono de calidad de suministro

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#334]
Tenemos un fichero F en el que se incluye una linea negativa por calidad de suministro. La factura queda en negativo, así NAV la trata como un abono. La primera cuestión es que de manera incorrecta hace un abono negativo, al tratarse de abono debería ser positivo, debería cambiar el signo a todas las líneas.
Por otra parte, tanto peaje como cierre aparecen bloquedos, al considerarlo un abono, en realidad es una factura con una línea negativa, así que lo tenemos que facturar. He desbloqueado el cierre y el peaje, pero sigue sin salir la factura ¿Cómo podemos hacerlo?

COM/00261
ABC/20180013
ID_GeoAtlanter, S.L._03180509030048057_F1_016_5.xml

**Comment by bpesquero** [comment]
La factura de venta se registra por error sin la línea de abono por calidad de suministro.
La factura ya está enviada al cliente y pasada al cobro. Decidimos no abonarla y facturar en factura independiente el abono por calidad de suministro

**Comment by bpesquero** [comment]
REvisar las facturas de abono por calidad de suministro. Hay dos opciones
-abono por calidad (Ejemplo:ABCR/20180001..ABCR/20180008)
-factura con linea negativa por abono por calidad que puede hacer que la factura se convierta en un abono (ejemplo explicado más arriba)

**Comment by dgarciageo** [comment]
Tenemos 18 abonos pendientes de cargar. 

Hay dos casuísticas:

1) Nos lo meten en el propio F1 de medidas y ahí si se carga la compra sin problemas y luego la venta se hace en dos facturas una por el consumo y otra con el abono (que realmente es una factura de venta negativa pero que puedo liquidar haciendo movimiento por diario)

2) Nos publican un solo F1 con el concepto 018 abono calidad suministro y ahí simplemente se procesa pero no genera ni factura ni abono de compra ni da error en el log, de manera que si no es porque cuento los F1 que cargo y las compras que me salen, ni me entero. Los localizo por la tabla de peajes porque son los que no tienen asociado ningún numero de factura ni abono


\\NI\Esios\F1\WAIT ERIC\ID_HIDROELECTRICA EL CARMEN ENERGIA, S.L._03190321080178003_F1_012_1.xml


\\NI\Esios\F1\WAIT ERIC\ID_HIDROELECTRICA EL CARMEN ENERGIA, S.L._03190321080027841_F1_013_2.xml

**Comment by jorgereal** [comment]
Se ha corregido el proceso de importación de ficheros F1_OTROS.
Ahora las facturas de tipo N, cuyo importe total es negativo, se transforman en abono y se invierten los importes de las líneas.

Se han importado los dos ficheros indicados en el comentario anterior, generándose los abonos AB/2019000058 y AB/2019000059 en HECEN PROD

**Comment by jorgereal** [comment]
Aún falta corregir la facturación de venta.

**Comment by jorgereal** [comment]
Finalmente se ha optado por modificar el proceso de la siguiente forma:

Los peajes se cargan con el Tipo Documento = Factura, pues se tratan de facturas tipo N a pesar de ser negativas.
A su vez se genera un preabono de compra positivo, pero con número de serie de prefactura. Se marca el peaje en el campo Nº preasignado abono de compra.

En la facturación de venta se genera un preabono de venta positivo, con número de serie de prefactura y se marca el peaje en el campo Nº preasignado de abono de venta.

Para los ficheros indicados se han generado los preabonos de compra: FC/2019021366 y FC/2019021367 y los preabonos de venta: FV/2019021232 y FV/2019021233

**Comment by bpesquero** [comment]
Reabrimos la incidencia por las siguientes cuestiones.
1.- ¿por qué se genera el abono con nº de prefactura en vez de nº de preabono? Es solo para saberlo.
2.- Tenemos una factura que al cargarla no se mueve a procesados, se carga en la tabla de Peajes como Abono y no genera ni prefactura ni preabono. En el F1 viene informada como tipo de factura A
3.- El resto de facturas las hemos generado ok, pero al intentar registrar las facturas de venta correspondientes da el siguiente error
![image](https://user-images.githubusercontent.com/20299071/64114421-31bc0800-cd8d-11e9-8658-a37cd29ec998.png)

**Comment by JMunoz17** [comment]
Necesito el F1 que no lo localizo.

**Comment by JMunoz17** [comment]
1- No se hace por nada en especial, originalmente es una factura y posteriormente cambiamos el tipo de documento convirtiéndolo en abono pero mantenemos el nº del documento siendo este de factura. No es necesario buscar el nº de abono que corresponda y cambiarlo pero si lo queréis se puede hacer.
2 - Pasadme el F1 cuando podáis. El problema viene porque el tipo de factura es 'A' y no 'N' que es el caso que esta contemplado pero necesito el F1 para ver como solucionarlo.
3 - Decidme algún ejemplo para debugearlo.

**Comment by JMunoz17** [comment]
Para el punto 2, efectivamente se están cargando los peajes como abono y no se genera ningún documento. Este es el fallo:
![image](https://user-images.githubusercontent.com/26869276/64704765-16e54400-d4af-11e9-8592-07e9e8b7d4cd.png)
El Nº de factura rectificativa que viene en el F1 no esta asociado como Nº Factura Proveedor a ninguna factura de compra existente en NAV.

**Comment by bpesquero** [comment]
Para el punto 3 estos ejemplos

Fecha registro | Fecha SII | Nº | Contract No. | Venta a-Nº cliente | CUPS | Venta a-Nombre
-- | -- | -- | -- | -- | -- | --
17/08/2019 | 17/08/2019 | FV/201908787 | COM/00132 | CL00220 | ES0021000004671282BW | Galán  Abellán Luis Jorge
17/08/2019 | 17/08/2019 | FV/201908788 | COM/00296 | CL00344 | ES0021000005142619BT | Felix Viana Molina
17/08/2019 | 17/08/2019 | FV/201908789 | COM/00498 | CL00453 | ES0031406097392008SQ | Apolonia Borrego Cano
17/08/2019 | 17/08/2019 | FV/201908790 | COM/00504 | CL00507 | ES0021000005151413WP | Borja Escorial Santa Marina
17/08/2019 | 17/08/2019 | FV/201908791 | COM/00505 | CL00759 | ES0021000004197620WW | FILM SYMPHONY ORCHESTRA S.L
17/08/2019 | 17/08/2019 | FV/201908792 | COM/00506 | CL00509 | ES0031408347371002WP | Lucia Solis Millan
17/08/2019 | 17/08/2019 | FV/201908793 | COM/00553 | CL00542 | ES0031405133643001CE | Comunitat Propietaris Maragda
17/08/2019 | 17/08/2019 | FV/201908794 | COM/00553 | CL00542 | ES0031405133643001CE | Comunitat Propietaris Maragda
17/08/2019 | 17/08/2019 | FV/201908795 | COM/00752 | CL00709 | ES0031405267240001MG | Juan De La Cuesta Pardo
17/08/2019 | 17/08/2019 | FV/201908796 | COM/00752 | CL00709 | ES0031405267240001MG | Juan De La Cuesta Pardo
17/08/2019 | 17/08/2019 | FV/201908797 | COM/01020 | CL00908 | ES0031408113029004NL | Olga Villà Gomà
17/08/2019 | 17/08/2019 | FV/201908798 | COM/01020 | CL00908 | ES0031408113029004NL | Olga Villà Gomà
17/08/2019 | 17/08/2019 | FV/201908799 | COM/01197 | CL01019 | ES0031102988614024MS | MARIA JESUS PEREZ JAIME
17/08/2019 | 17/08/2019 | FV/201908800 | COM/01319 | CL01113 | ES0021000005804959ND | Antonio Carrasco Sánchez
17/08/2019 | 17/08/2019 | FV/201908801 | COM/01335 | CL01123 | ES0031405530535002FK | JOAN BUSQUE MALET
17/08/2019 | 17/08/2019 | FV/201908802 | COM/01351 | CL00441 | ES0031102725450001QZ | Antonio  Cordero Pinedo

**Comment by JMunoz17** [comment]
No veo ninguna de estas facturas de venta, las eliminasteis?

**Comment by bpesquero** [comment]
Si, se borraron. Hemos vuelto a generar una

FV/201909556 asociada al abono de compra FC/20199556

**Comment by JMunoz17** [comment]
Hemos vuelto a generar la factura FV/201909562, revisad que este ok y probad a registrar de nuevo. Nos vais contando.

**Comment by bpesquero** [comment]
AL intentar registrar da este error

![image](https://user-images.githubusercontent.com/20299071/64948745-fedb3f00-d877-11e9-990a-c5c1bdaf8eb3.png)

**Comment by JMunoz17** [comment]
Probad de nuevo que con nuestra licencia no puedo finalizar el registro, me decís con lo que sea.

**Comment by JMunoz17** [comment]
Nº Abono = FV/201909661

**Comment by bpesquero** [comment]
REgistrada ok- ESo si. ha tardado casi 10 minutos

**Comment by JMunoz17** [comment]
Ok, si veis que tarda tanto para todos los casos avisadme (no sé si ha sido algo ocasional que a mi hoy también me iba un poco lento NAV en vuestro servidor).
