### ISSUE TITLE
Problema carga Ficheros M1_05

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#335]
Envío por mail los ficheros, son de Hidroeléctrica El Carmen Energía.

**Comment by PKFEric** [comment]
En los nuevos formatos OCSUM el <ModoControlPotencia> es obligatorio, y no viene informado en estos M1_05 entiendo que son de los antiguos o estan mal. 

¿Modifico el XML Port para que se puedan importar y luego lo dejo como deberia?

**Comment by bpesquero** [comment]
Cuanto tiempo lleva el cambio?

**Comment by PKFEric** [comment]
Ya estan cargados, han fallado dos cosas:
1. ModoControlPotencia deberia aparecer, es obligatorio en el nuevo formato 
2. TipoMovimiento que se corresponde con la tabla 37 de ocsum que puede tomar los valores A = Alta, B = Baja y M = Modificacion.  En la importacion del M1_05 esta controlado que sea del tipo M, en estos fichero venia A. 

Estas son las dos cosas que hemos detectado en estos ficheros, ya estan importados.
