### ISSUE TITLE
revisar reactiva en facturas de compra y venta

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#336]
REvisar cómo se repercute la reactiva en las facturas de venta, aunque el importe final coincide los datos no parecen muy correctos
Además, en el pdf se escribe el precio con muchísimos decimales....

Ejemplo: factura H/2018023557

**Comment by bpesquero** [comment]
Cuando la factura viene informada en varios periodos da error al hacer la factura del venta del tipo:
"Error, el importe de la reactiva de la factura 325,35 no coincide con el del peaje 0 por un margen superior a 0,02"
Ejemplos:

GeoATlanter: 


Contrato | CUPS | Fichero
-- | -- | --
COM/00424 | ES0021000005425100XH | ID_GeoAtlanter, S.L._03180802030241342_F1_012_1.xml
COM/00122 | ES0022000008397502ZM | SCTDE_F1_01_0022_0587_20180802150535823_(684675830)_mg.xml

Hidroeléctrica El Carmen Energía


Contrato | CUPS | Fichero
-- | -- | --
HECEN/08835 | ES0306000027000313FZ | F1_0306_201800055860_32828869.xml

**Comment by jorgereal** [comment]
Había un error en el control que calcula la diferencia de importes entre la reactiva de la factura y la del peaje.

Además, en el fichero F1_0306_201800055860_32828869.xml el ImporteTotalEnergiaReactiva no se corresponde con la suma de  ValorEnergiaReactiva * PrecioEnergiaReactiva de todos los periodos, tan solo comprende el importe del primer periodo, de ahí que fallara en ese caso.

Se ha modificado el control para que el cálculo del importe de la reactiva del peaje se haga a partir de los campos ValorEnergiaReactiva  y PrecioEnergiaReactiva.

Se han generado las prefacturas de venta para los contratos COM/00424 y HECEN/08835.

El contrato COM/00122 no tiene medidas cargadas.

**Comment by bpesquero** [comment]
COM/00424 --> OK
COM/00122 --> Da ese error, de que no tiene medidas cargadas, pero no tiene sentido, en el F1 ya se indica que no tiene curva de carga, y por tanto se tendría que perfilar. Puedes mirar en qué comprobación da eses error?
HECEN/08835--> No es correcto, nunca se puede repercutir un importe diferente al de la factura de compra. ESto es una comprobación que habría que añadir. Que el importe total de reactiva en la venta coincida con el importe total de reactiva en la compra. Hablo con el distribuidor para ver por qué se ha metido reactiva en P2 y no se ha facturado.

**Comment by bpesquero** [comment]
HECEN/08835-> reclamada al distribuidor que reconoce que está mal el fichero. CAmbio a mano la factura de venta para que salga bien. Importantísimo poner el control

**Comment by jorgereal** [comment]
Se ha añadido un control en la generación de la prefactura de venta para confirmar que el importe total de la reactiva en la venta coincide con el importe total de la reactiva en la compra.

Se ha forzado la facturación para el contrato COM/00122 y se ha generado el perfilado y la prefactura de venta FV/201804518 sin errores salvo el aviso de que existen huecos en la facturación.

**Comment by bpesquero** [comment]
Revisado y ok

**Comment by bpesquero** [comment]
Vuelvo a tener problema con este tema. En particular con el contrato COM/00690, con la factura J5803N00020891. Al hacer la venta da el error

“Error, el importe de la reactiva de la factura de venta 5,61 no coincide con el de la factura de compra 0 por un margen superior a 0,02”

En realidad la factura de compra tiene importe 5,61 euros. Está hecha la prefactura de compra sin registrar y la venta no sale.

**Comment by bpesquero** [comment]
Otro problema con reactiva
el contrato COM/00122, la factura FC/20184674, no incluye la reactiva.

**Comment by JMunoz17** [comment]
Para el COM/00690 ya esta solucionado, había un error en el control.
Para el COM/00122 el fichero viene sin cierre. 
SCTDE_F1_01_0022_0587_20180801080026108(ZGPSE_0022_0587_F1_01_201807311916230932310232).xml

**Comment by bpesquero** [comment]
COM/00690 ok
COM/00122 reclamamos al distribuidor
