### ISSUE TITLE
añadir firma orden SEPA en cambio de cuenta bancaria área clientes próxima - a tu lado

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#337]
En el cambio de cuenta bancaria hay que añadir  la firma de la nueva orden SEPA.

**Comment by bpesquero** [comment]
Hemos probado a hacer un cambio de IBAN y no nos ha salido lo de la orden SEPA

**Comment by bpesquero** [comment]
Estamos guardando la IP  la fecha en la que no lo firma, igual que hacemos en la firma de contrato,  verdad?

**Comment by PKFEric** [comment]
ya esta añadida la IP y la fecha de firma y probado.
