### ISSUE TITLE
informes deuda HECEN

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#339]
Necesitamos duplicar los informes de impagos de HECEN, tanto el agregado como el de detalle, sin incluir los movimientos identificados como "SALDO_INICIAL"

**Comment by PKFEric** [comment]
Ya estan publicados los dos informes nuevos en el mismo lugar donde se encontraban los anteriores.

Lo unico que se ha hecho ha sido filtrar en todos los movimientos que en Nº Documento sea distinto de SALDO_INICIAL

**Comment by bpesquero** [comment]
He estado revisando y no me cuadran los informes de deuda agregada. 
He sacado los 4 informes a fecha de hoy
EL informe agregado con saldos iniciales es el siguiente


  | Deuda a 31/12/2014 | Deuda < 2 meses | Deuda entre 2 meses y 1 anio | Deuda > 1 anio
-- | -- | -- | -- | --
Administracion Publica | 431.737,01 | 42.044,68 | 80.184,69 | 410.582,32
Cliente Privado | 859.717,23 | 19.423,29 | 137.935,55 | 1.092.624,66


El saldo a 31/12/2014 coincide con los moviminetos SALDO_INICIAL con contrato asignado. Hasta ahí todo bien. En este mismo informe, la deuda de más de un año, debería ser el SALDO_INICIAL  + los movimientos pendientes de más de un año. ESto no cuadra, por que como se puede ver en administración publica la deuda de más de un año es menor que el saldo inicial. 

El informe sin saldo inicial es el siguiente


  | Deuda a 31/12/2014 | Deuda < 2 meses | Deuda entre 2 meses y 1 anio | Deuda > 1 anio
-- | -- | -- | -- | --
Administracion Publica | 0 | 42.044,68 | 80.184,69 | 194.477,82
Cliente Privado | 0 | 19.423,29 | 137.935,55 | 557.332,24

La deuda a 31/12/2014 es 0, hasta ahí también bien. La deuda de menos de dos meses y entre dos meses y un año coincide con el anterior, esto también correcto. Pero la deuda de más de un año, debería ser la misma que la del informe anterior menos el saldo_inicial, y esto no es así,

Salvo error por mi parte, creo que el problema está en el cálculo de la deuda a más de un año.

**Comment by jorgereal** [comment]
Efectivamente la deuda > 1 año en el informe agregado con saldo inicial no era correcta.
No se estaba acumulando todo el importe del saldo inicial, tan solo el importe pendiente de los movimientos con el campo Pendiente = Si.

Ahora la deuda >1 año con saldo inicial si supera la deuda a 31/12/2014 y se cumple que:
Deuda de más de un año =  SALDO_INICIAL + los movimientos pendientes de más de un año.

Subido a PRE y PRO.

**Comment by bpesquero** [comment]
Ay, me vas a matar. Soy medio .... 
Efectivamente estaba bien. El saldo a 31/12/2014 coge todos los movimientos de saldo inicial, estén pendientes o no, pero la deuda de más de un año sólo coge los movimientos que estén a día de la ejecución del informe pendientes.

Lo siento, si se puede volver a cambiar.. Es culpa mía.

**Comment by jorgereal** [comment]
Se han deshecho los cambios en el informe de la deuda agregada con saldo inicial.

Subido a PRE y PRO.
