### ISSUE TITLE
cambio de pagador en contrato- pb con dirección de envío

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#343]
Al cambiar el pagado de un contrato en NAV no asigna el código de la dirección de envío.

**Comment by JMunoz17** [comment]
Esto esta relacionado con la tarea #328.

Actualmente esta hecho para que se asigne como dirección de envío la dirección de envío genérica establecida en la pestaña de envíos de la ficha del cliente. Todos los clientes menos 5 tienen vacía esta dirección de envío genérica, por eso no se habrá modificado.

Lo que hemos hecho ha sido que la primera vez que se cree una dirección de envío para un cliente, se asignará esta dirección de envío como genérica para ese cliente. 

Si queréis podemos pasar un proceso para rellenar la dirección de envío genérica en todos los clientes que la tienen vacía siguiendo los criterios que nos digáis (La mayoría de clientes solo tienen una dirección de envío pero alguno tiene varias).

**Comment by bpesquero** [comment]
Si, lo suyo sería pasar un proceso. nos podríais indicar los clientes que tienen varias? Quizá podamos asignarla manualmente si no son muchos.

Gracias

**Comment by JMunoz17** [comment]
Estos son los clientes con 2 direcciones de envío:
CL00146
CL00160
CL00186
CL00197
CL00407
CL00461
CL00524

**Comment by bpesquero** [comment]
ok. SE la asignamos manualmente.
