### ISSUE TITLE
problema informe medidas horarias por agregacion tipo 3,4 y 5

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#344]
Al ejecutar el informe de medidas horarias por agregación tipo 3,4 y 5 para el mes de septiembre da el siguiente error

![image](https://user-images.githubusercontent.com/20299071/40710704-a80aef7a-63f9-11e8-9497-48195e524904.png)

**Comment by bpesquero** [comment]
Otro error
![image](https://user-images.githubusercontent.com/20299071/41673228-8bb70d1c-74bc-11e8-9973-df202eb9c09e.png)

**Comment by JMunoz17** [comment]
Podéis probar a ejecutarlos.
