### ISSUE TITLE
Mails con caracteres extraños

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#346]
Vuelven a salir mails con caracteres extraños
Ej:

Hola MÂªJosé Bueno González:

Hemos terminado los trámites correspondientes y celebramos confirmarte que desde el día 25/05/18 ya te estamos suministrando electricidad.

**Comment by JMunoz17** [comment]
He probado a enviarme el mail de activación correspondiente al contrato de Mª José Bueno González (COM/00536) tanto a una cuenta de outlook como a una cuenta de gmail y en ambos casos me llega sin ningún carácter extraño.

Outlook:
![image](https://user-images.githubusercontent.com/26869276/41023122-c497125a-696b-11e8-8337-b21fe6bb5774.png)

Gmail:
![image](https://user-images.githubusercontent.com/26869276/41023145-d4a606ec-696b-11e8-8e0d-af1449affc10.png)

Desde la cuenta desde la que se envían aparece como enviado de manera correcta:
![image](https://user-images.githubusercontent.com/26869276/41023461-cc9e0a8e-696c-11e8-9f8e-7ba0e5cb45db.png)

Por lo que parece que no hay ningún problema con este caracter, desde donde visteis que se enviaba con el caracter extraño?

**Comment by bpesquero** [comment]
No entiendo, a nosotros en la bandeja de salida nos aparece mal. Os lo
reenvío


<http://www.geoatlanter.com>

*Síguenos en:  <https://www.facebook.com/proximaenergia/>*
<https://twitter.com/proximaenergia>*
<https://plus.google.com/114547235710296874519>*

*AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener información
*confidencial *sometida a secreto profesional. No está permitida su
reproducción o distribución sin la autorización expresa de *GEOATLANTER SL.*

Si usted no es el destinatario final por favor elimínelo e infórmenos por
esta vía.



De acuerdo con lo establecido por el Reglamento General de Protección de
Datos (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de
2016, le informamos que sus datos serán tratados con la finalidad de
realizar la gestión administrativa, contable y fiscal, así como el envío de
comunicaciones comerciales  sobre nuestros servicios y/o productos.


Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, oposición, supresión, limitación y portabilidad de
sus datos en el domicilio de *GEOATLANTER SL *sito en: Avda de Europa 34B
<https://maps.google.com/?q=Avda+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha 3º,  28023 Madrid o enviando un correo electrónico a la siguiente
dirección : *contacto@geoatlanter.com <contacto@geoatlanter.com>*

Si usted no desea recibir nuestra información, póngase en contacto con
nosotros enviando un correo electrónico a la dirección:
*contacto@geoatlanter.com
<contacto@geoatlanter.com>*

**Comment by JMunoz17** [comment]
He cambiado una cosa para ver si así os aparece ya bien sin caracteres extraños, si lo podéis comprobar ya que a mi en todo momento me ha salido de manera correcta. Son los últimos mails enviados ayer con destinatario jaime.munoz@pkf-attest.es y jmunozap17@gmail.com
