### ISSUE TITLE
Error factura R

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#347]
Tenemos una factura R que no está haciendo abono. Como ya os comenté esto lo teníamos mal, pero ya os dije que lo correcto es que la R haga factura y abono y la G sólo factura.

**Comment by PKFEric** [comment]
Se ha realizado la modificacion, estamos a la espera de tener una factura de tipo R para porbarlo ya que la que teniamos de HECEN esta registrada tanto en compra como en venta.

**Comment by bpesquero** [comment]
Acabamos de detectar una factura R que se registró en agosto y para la que no se generó abono de compra ni de venta. Era una factura de derechos de enganche, no sé si puede estar ahí el problema.
Se trata del COM/00266, factura C/20182995.

**Comment by bpesquero** [comment]
Perdón, la factura C/2018299

**Comment by JMunoz17** [comment]
Hemos generado el abono de venta, esta en NI\Esios\facturas Geo\AC_20180095.pdf

**Comment by JMunoz17** [comment]
Hemos generado el abono, esta en \\NI\Esios\facturas Geo\AC_20180095.pdf

**Comment by jorgereal** [comment]
Existía un error en la generación del abono de compra para las facturas de enganche tipo R.
Se ha corregido.

Además, no estaba contemplada la creación de los abonos de venta para las facturas de enganche tipo R en la facturación.
Se ha añadido este caso y se ha subido a PRO.

¿Generamos los preabonos de venta y compra para el contrato COM/00266 que se tenían que haber creado al importar y facturar la factura R o ya los habéis generado vosotros a mano?

**Comment by bpesquero** [comment]
Lo hemos hecho nosotros.
