### ISSUE TITLE
Problema al forzar facturación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#348]
Cuando tenemos una fichero F1 reclamado el siguiente fichero que se recibe da error porque hay un hueco de facturación. De forma general lo que hemos hecho en estos  casos es forzar la facturación. 
Cuando en este caso forzamos ahora la facturación nos encontramos con el siguiente error:

"Error,   una o ambas fechas del Término de Potencia es vacia."

Entiendo que es algún control que quizá no debiera estar en forzar facturación.

Ejemplo: HECEN - HECEN/07875 - SCTDE_F1_01_0022_0713_20180516202114005_(663549690).xml
La factura de compra está en prefactura.
-

**Comment by PKFEric** [comment]
Resuelto se ha creado factura de compra y de venta.
