### ISSUE TITLE
Mensaje de contacto

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#35]
Pone Gracias por contactar con Próxima, pronto tendra noticias nuestras.

tiene que ser Gracias por contactar con Próxima, pronto tendras noticias nuestras.

Siempre hablamos de tú

**Comment by PKFEric** [comment]
CORREGIDO-> EN CUANTO SUBA LA WEB PROBAR

**Comment by PKFEric** [comment]
WEB SUBIDA->PROBAR

**Comment by bpesquero** [comment]
Probado y ok
