### ISSUE TITLE
Error firma contrato

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#350]
Hemos tenido que meter a mano el contrato COM/00583 y COM/00584, porque el cliente JAIMJOS SL   ya existía en base de datos,por otro servicio que le dimos en su día, no de comercialización. Al enviarle el email de usuario y contraseña, y el de enlace de activación, perfecto, ha hecho clic en el mismo y se ha firmado el COM/00583, pero el COM/00584 , a nombre del mismo titular, se ha quedado como pendiente de firma. Al tratar de hacerlo a mano en acciones/Firmar contrato, da el siguiente error

![image](https://user-images.githubusercontent.com/20299071/41583884-17feb404-73a6-11e8-8695-1f98beb9d414.png)

**Comment by PKFEric** [comment]
Hay que rellenar el mail en el vendedor que se asocia al cliente de venta, ya lo he comentado con Ainhoa.
