### ISSUE TITLE
Cambio de Tarifa

### ISSUE THREAD

**Issue by jlagunapkf** [PKFEric/webProxima#352]
Qué proceso se va a llevar a cabo para realizar el cambio de tarifa?

Por un lado realizar el cambio de tarifa y en el caso de que proceda, realizar un modificación de potencias indicando el cambio realizado mediante el envio de un email.

O bien, indicar el cambio de tarifa aportando un fichero M1_01.

**Comment by bpesquero** [comment]
No entiendo bien la pregunta. Os referís a qué se va a hacer si desde la zona privada eligen la opción de cambio de tarifa? Sería exactamente lo mismo que en Geo. Se envía un mail con los datos y nosotros nos encargamos de gestionarlo.
