### ISSUE TITLE
errata web

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#353]
He localizado una errata en la web de Próxima. En el apartado tiene buena pinta pero

Dice

Una vez emitidas las facturas las ponemos al cobro mediante domiciliación bancaria a partir del séptimo día.

Y debiera ser

Una vez emitidas las facturas las ponemos al cobro mediante domiciliación bancaria a partir del tercer día.

**Comment by PKFEric** [comment]
Modificado
