### ISSUE TITLE
pdf factura con distintas fechas de energía y de facutra

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#363]
Las facturas regularizadoras (tipo G o N con diferentes fechas en el término de energía y en la factura) no sacan bien el pdf. Da la impresión que no se ha subido la modificación que se hizo a este respecto

**Comment by PKFEric** [comment]
Ya esta modificado pendiente de probar

**Comment by bpesquero** [comment]
En el caso en que el las fechas del término de energia coinciden con las de la factura en la tabla de lecturas añade un día a la fecha fin o fecha lectura posterior (ejemplo factura C/20182492), en el caso en el que no coinciden no suma un día (ejemplo factura C/20181850). Debería sumarlo en ambos casos.

**Comment by PKFEric** [comment]
Modificaciones a añadir para las factuas R y G:

Debajo de fecha de vencimiento:
Si la factura es R: Poner Factura Rectificativa
Si la factura es G : Poner Factura Regularizadora y indicar las fechas que regulariza, fecha desde y hasta.

Ademas si la factura es G en el detalle poner las fechas desde y hasta de las lineas de la factura de venta.

**Comment by PKFEric** [comment]
ya esta modificado tenemos que probarlo cuando haya licencia

**Comment by bpesquero** [comment]
Factura R: ok,, pero se está informando junto con el texto de factura rectificativa de las fechas desde y hasta y no tiene sentido, porque son las mismas que las de la factura. Poner sólo texto
Factura G: Ok, pero no pone las fechas desde y hasta. Creo que os habéis liado y por error se ha puesto en la R las fechas cuando yo pedí ponerlo en la G

Adicionalmente habría que revisar el abono que se crea junto con una R, ya que en la parte de detalle, no pone el detalle de cálculo en ninguna de las líneas.

**Comment by jorgereal** [comment]
Efectivamente se estaban informando las fechas desde y hasta con el criterio contrario, se han modificado los formatos para mostrarlas solo en las facturas de tipo G.

Subido a PRO.

**Comment by bpesquero** [comment]
Pefecto.

Faltaría ver el pdf de los abonos que os comentaba.

**Comment by JMunoz17** [comment]
Hemos generado el abono, está en \\NI\Esios\facturas Geo\AC_20180095.pdf

**Comment by bpesquero** [comment]
Perfecto. Habéis clicado para que se suba al ftp y se envíe el correo o lo hacemos nosotros?

**Comment by JMunoz17** [comment]
No, solo hemos generado el abono, revisad que este correcto y ya marcáis el resto de checks.

**Comment by bpesquero** [comment]
Acabo de verificar, que cuando se trata de una factura  informada por el distribuidor como N pero que realmente es una G, porque el periodo de energía es diferente al periodo de potencia no se indican las fechas de la energía. Este tipo de facturas tendría que tener el mismo tratamiento que una factura G.
Ejemplo: factura C/20184214

**Comment by jorgereal** [comment]
Se han modificado los formatos de factura de GEO y HECEN para que también se muestren las fechas de energía en la línea cuando se trata de una factura N con:
(fecha hasta cabecera- fecha desde cabecera +2) < (fecha hasta linea - fecha desde linea)

Se puede comprobar con la factura C/20184214.

Subido a PROD.

**Comment by bpesquero** [comment]
probado y ok
