### ISSUE TITLE
Mensaje alerta factura no electronica en web de próxima

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#364]

**Comment by PKFEric** [comment]
Al pasar al siguiente paso del registro si esta marcado factura electronica a NO, mostrar un pop up con el texto que se nos envia, y dos botones, uno de continuar y otro de cambiar facturacion

**Comment by PKFEric** [comment]
Ya esta modificado y subido.

**Comment by bpesquero** [comment]
Sale el mensaje correcto. El problema es que si pones cambiar selección, no se cambia a electrónica, ni te deja avanzar. 
Si le doy a continuar con factura en papel, se genera correctamente

**Comment by bpesquero** [comment]
Probado y ok
