### ISSUE TITLE
Carga fichero xml M1

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#366]
El campo modocontrolpotencia ha pasado a ser no obligatorio

**Comment by JMunoz17** [comment]
Ok, lo he modificado en el M1_05, el elemento modocontrolpotencia también aparece en el M1_01 y el M1_02(Aceptación) como obligatorio. Para estos casos es necesario modificarlo?

**Comment by bpesquero** [comment]
Efectivamente, también en el paso 01 y en el paso 02 dejan de ser obligatorios.

Gracias

**Comment by JMunoz17** [comment]
Modificado.
