### ISSUE TITLE
Error carga F1 - ES0021000004578867HR0P

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#367]
Error al cargar el F1 del CUPS ES0021000004578867HR0P
![image](https://user-images.githubusercontent.com/20299071/42625124-4fdf31b8-85c7-11e8-9dac-dada3f9ba444.png)
ID_GeoAtlanter, S.L._03180703030013251_F1_0117_16

**Comment by PKFEric** [comment]
Ya esta corregido y cargada la factura, era un error de programacion al filtrar para encontrar las facturas correspondientes  a la factura G
