### ISSUE TITLE
Gestión de potencia y peaje anterior - Registro

### ISSUE THREAD

**Issue by jlagunapkf** [PKFEric/webProxima#369]
Estan creados los campos en la web pero no se almacenan de Navision, queda almacenarlo. Y decidir si se va a mostrar o gestionar en alguna otra pantalla.

FALTA REALIZAR LAS PRUEBAS

**Comment by bpesquero** [comment]
Creo  que ya que tenemos la información lo suyo es guardarlo en NAV en dos campos en la ficha de contrato y hay que pensar de qué forma identificar, cuando se lanza el proceso de generación de fichero C masivo en NAV, si se trata de un C1 o un C2
