### ISSUE TITLE
NAV-Añadir pdf para mail desde NAV

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#37]
Añadir generación de pdf idéntico al mail pero añadiendo la dirección de envio y el nombre para el caso de baja unilateral del contrato fase 1,  baja unilateral del contrato fase 2.

**Comment by jorgereal** [comment]
Desarrollo realizado.
La tarea se ejecuta desde el cliente de roles en Energy/Geoatlanter/Generar Mails Impagos
Se generan los pdfs de los impagos para los que ya ha sido enviado el mail de aviso (tienen el campo fecha envío mail 1 y/o 2 informado) 
Se guardan en la ruta que indique el campo 'Ruta Mail Baja' de Configuración BBDD
PROBAR.
