### ISSUE TITLE
campaña traspaso clientes HECEN- 01/10/2018

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#372]
Hay que establecer la forma en que identificar a cada cliente con un código
Importante: ver si es posible introducir una línea con 1 euro de descuento a todo aquel cliente que decida pasar a facturación electrónica.

**Comment by bpesquero** [comment]
Al hacer la prueba con el contrato HECEN/08908 he hecho todo, he metido el nif del pagador y parecía haberse hecho bien. 
Me ha salido un mensaje de "ha terminado...." y no he podido leer más por que me ha salido este mensaje de error

![image](https://user-images.githubusercontent.com/20299071/46131556-3eaab000-c23c-11e8-8e45-c45120b09dc5.png)

Si intento entrar, me dice usuario o pwd incorrecto

**Comment by bpesquero** [comment]
Si preferís conectaros para verlo, dadme un toque

**Comment by jlagunapkf** [comment]
¿Esta tarea es de atulado no?
