### ISSUE TITLE
Factura electrónica (NO) - Texto

### ISSUE THREAD

**Issue by jlagunapkf** [PKFEric/webProxima#373]
Cambiar el texto que aparece en el pop up cuando se selecciona factura electrónica = No.

Actualmente aparece el texto que se ha generado para próximaenergia.

**Comment by bpesquero** [comment]
Recuerda que con esta opción recibirás tu factura en papel y por tanto no podrás disfrutar de la promoción de 1€ menos al mes hasta 2020.

**Comment by jlagunapkf** [comment]
Este Popup se encuentra en el proceso de dar de alta un usuario normal, no desde "yasoycliente".

Actualmente teníamos puesto este texto. 

                        Esto significa que te enviaremos tu factura en papel por correo ordinario. Al tener que asumir los costes de impresión, ensobrado y envío nos vemos obligados a incrementar nuestro ajustado cargo por gestión que pasara a ser de 3€/mes para clientes de menos de 10 kW de potencia y a 0,75 c€/kWh para clientes de más de 10 kW.
Indicanos si quieres continuar con factura NO electrónica o quieres cambiar tu selección.


¿Lo cambio?

**Comment by bpesquero** [comment]
Lo vamos a cambiar, pero vamos a poner algo más parecido a lo de Geo, sería:

Esto significa que te enviaremos tu factura en papel por correo ordinario. Al tener que asumir los costes de impresión, ensobrado y envío nos podemos ofrecerte nuestra promoción de 1€ de descuento al mes hasta 2020.
Indicanos si quieres continuar con factura NO electrónica o quieres cambiar tu selección.
