### ISSUE TITLE
margen ficha de contrato

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#38]
Hay que discriminar correctamente si se trata de empresa o persona para asignar el margen que corresponda en la ficha del contrato

**Comment by PKFEric** [comment]
ARREGLADO  WEB->PROBAR

**Comment by bpesquero** [comment]
He creado un contrato de empresa y no le ha asignado ni el margen fijo ni el margen variable

**Comment by PKFEric** [comment]
SE ME OLVIDO SUBIR ESA PARTE AYER-> YA LA HE SUBIDO Y ME HE CREADO UN CONTRATO COMO EMPRESA 2.0A Y ME LO HA RELLENADO BIEN. PRUEBALO PORFI

**Comment by bpesquero** [comment]
Probado y ok
