### ISSUE TITLE
Incidencia FV se factura 1 día más de potencia

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#381]
TEnemos una serie de contratos para los que se ha hecho la factura, no ha dado ningún error en el log, sin embargo para el término de potencia se factura un día de más. Se trata de facturas que no están facturando días naturales completos.
He dejado tanto la factura de compra como la de venta en prefactura

COM/00402 | ES0031405789370001XN
-- | --
COM/00411 | ES0031408048521006YY
COM/00412 | ES0031405847580001YW
COM/00455 | ES0031405978607032DN
COM/00483 | ES0031405847580014YS
COM/00484 | ES0031405847580004YM
COM/00311 | ES0031408024132003YL
COM/00394 | ES0031406180500008ST
COM/00398 | ES0031408251118001PY
COM/00425 | ES0031405945572001FL
COM/00466 | ES0031408514470007MB
COM/00469 | ES0031406290237012TW
COM/00356 | ES0031405847580003YG

**Comment by jorgereal** [comment]
Existía un error en el control de los peajes importados antes del arreglo del cambio de facturación.
Se sumaba un día al cálculo del Término de potencia a todas las facturas posteriores, en lugar de solo a la siguiente.

Se ha corregido y se han vuelto a generar todas las prefacturas de venta para los contratos solicitados.

**Comment by bpesquero** [comment]
SEguimos teniendo problemas con este tema. Sigue restando un día aunque no sea la primera factura después del cambio.

Ejemplo 
COM/00194 - FV/201804663

**Comment by JMunoz17** [comment]
Lo hemos corregido y hemos vuelto a generar la factura de venta.

**Comment by bpesquero** [comment]
Probado y ok
