### ISSUE TITLE
CAmbio puntos por comas en factura de venta en TP

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#382]
Al hacer la factura de venta se cambian puntos por comas en el precio del Término de Potencia y el importe por tanto aparece multiplicado por 1000. Pasa siempre que las fechas de PM del cierre son diferentes a las de TP de la factura.

Ejemplos:

GEOATLANTER

Contrato | CUPS | Fichero | Factura de venta
-- | -- | -- | --
COM/00256 | ES0022000008865940AW | SCTDE_F1_01_0022_0587_20180804151132028_(685088093).xml | Prefactura

HIDROELÉCTRICA EL CARMEN ENERGIA

Contrato | CUPS | Fichero | Factura de venta
-- | -- | -- | --
HECEN/07950 | ES0022000007332393GA | SCTDE_F1_01_0022_0713_20180804151721095_(685151489).xml | Prefactura

**Comment by jorgereal** [comment]
Había un error en el cálculo del precio del término de potencia con máximetro para facturas de tipo N rectificativas con fechas TP de peaje diferentes de fechas PM  de cierre.

Se ha corregido y se han vuelto a generar las prefacturas de venta de los contratos indicados.
