### ISSUE TITLE
Factura de venta COM/00178

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#383]
En relación al COM/00178 (ES0031300013009061VV) se registró mal la factura de compra (con fichero 
F1-ES0031300013009061VV0F.xml), la fecha de inicio es un día después de lo que debiera ser.

Al tratar de hacer la factura de venta  me da error, no consigo sacarla, he probado lo siguiente:
1.- FActuro el contrato. Me da error "Hay huecos en la facturación." Lógico. Ya digo que la fecha de incio de la factura de compra era incorrecta, era un día superior a lo que tenía que ser.
2.- FActura las fechas que correctos en la venta y obviamente me da el siguiente error porque no encuentra un cierre que coincida para esas fechas: El contrato COM/00178 del tipo V no se puede facturar porque no tiene medidas horarias F5D o P1D
3.- Fuerzo la facturación y facturo con las fechas del peaje. Me da el siguiente error: "Error, Las medidas F5D 225, de la factura FV/201804325 para el contrato COM/00178 no se corresponden con las medidas de cierre 229". Es normal, ya que no está considerando un día de medidas de la curva
4.- CAmbio las fechas en el peaje, tanto en la tabla de toll como en la de closing para poner las fechas correctas, fuerzo la facturación y me da el siguiente error: "Error, Las medidas F5D 230, de la factura FV/201804325 para el contrato COM/00178 no se corresponden con el termino de Energia 224,656" Este error es el que no entiendo porque las medidas realmente si que coinciden.

**Comment by jorgereal** [comment]
He revisado el caso y he probado a forzar facturación con las fechas del peaje: 06/07/17-03/08/17
Obteniendo el siguiente error:
Error, Las medidas F5D 225, de la factura FV/201804520 para el contrato COM/00178 no se corresponden con las medidas de cierre 229.

Observando las medidas horarias para el  COM/00178 en las fechas solicitadas he visto que existen medidas repetidas para cada hora del día 06/07/17. Las primeras medidas cargadas para ese día suman 8,409 mientras que las segundas suman 4,239.
La suma del resto de días excluyendo este asciende a 220,417.

Con estos datos entiendo que el proceso está utilizando las últimas medidas cargadas para el día 06/07/17, si se usaran las primeras no existiría diferencia respecto a las de cierre.

En principio eliminando las últimas medidas cargadas para el día 6 (entradas de la 2803562 a la 2803585) la facturación pasaría los controles sin problemas.

¿Eliminamos estas medidas y facturamos nosotros o preferís hacerlo vosotros?

**Comment by bpesquero** [comment]
He estado mirando.
No existen dos cargas para el día 6/07, o mejor dicho, si existen pero para facturas de acceso diferentes. Unas se corresponden con la factura J1701N05188115 que es la que nos interesa y las otras se corresponden con la factura J1701N04815237, por tanto no se puede borrar nada.
En realidad, si sumas todas las medidas correspondientes a la factura J1701N05188115 suman lo mismo que el cierre, y lo mismo que lo facturado en peaje (compra) el problema son las fechas.
El caso que tiene que funcionar es cambiar en el cierre asociado las fechas y poner un día antes de lo que aparece. Lo que no entiendo es por qué al hacer eso me da el error
 "Error, Las medidas F5D 230, de la factura FV/201804325 para el contrato COM/00178 no se corresponden con el termino de Energia 224,656" 
Las medidas del F5D suman 228,82 y las del termino de energía 229, así que no sé por qué da eso en el log. 
¿pordemos cambiar de nuevo las fechas y debuggeas a ver por qué está dando esas cantidades? ¿para ver que es lo que está sumando?

**Comment by jorgereal** [comment]
Existía un error en los filtros que se aplicaban sobre la tabla de medidas horarias cuando se forzaba la facturación.
Se ha corregido y se ha cambiado la fecha desde a 05/07/17 tanto para las medidas de cierre como para las de peaje.

Se ha facturado y se ha generado la prefactura de venta FV/201804595.

**Comment by bpesquero** [comment]
Comprobado y ok
