### ISSUE TITLE
Mail de activación de fichero M con cambio de tarifa

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#384]
Cuando se procesa un mail de activación de un M se envía un correo automático al cliente indicando que se ha procedido a modificar las características del contrato. 
Al indicar la tarifa nueva se está indicando el código ATR, en lugar del nombre de la tarifa, que es lo que da información real al cliente. 
Habría que modificarlo.

**Comment by jorgereal** [comment]
Se ha modificado la información correspondiente a la tarifa en el envío de mails de activación de fichero M para informar el nombre de ésta.

**Comment by bpesquero** [comment]
Probado y ok
