### ISSUE TITLE
Cambio de estado al procesar fichero M1_04

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#385]
Al procesar el paso M1_04 de rechazo, se procesa ok, sin embargo no cambia el estado del contrato, permanece en estado anterior. Habría que pasarlo a estado activado.

**Comment by JMunoz17** [comment]
En NAV se estaba procesando como si se recibiese un M1_02 de rechazo ya que no estaba implementado el caso del M1_04, hemos añadido este caso cuyo comportamiento es igual que el M1_02 de rechazo pero modificando el estado del contrato a activado.

Lo tenéis en PRE para que lo podáis probar y cuando este nos decís para subirlo a PROD.

**Comment by bpesquero** [comment]
Probado  y ok. Subir a producción

**Comment by JMunoz17** [comment]
Subido a producción.
