### ISSUE TITLE
Cambio de cuenta desde la web

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#386]
Cuando se hace un cambio de cuenta corriente desde la web, se crea el banco 2. Sin  embargo, en el caso en que ya exista el banco 2, se machaca con el nuevo IBAN. En cualquier caso habría que crear un nuevo banco para el cliente.

**Comment by PKFEric** [comment]
Hemos modificado el codigo en NAV para que cree una cuenta nueva y se la asocie al contrato. En vez de pisar la que existia.

**Comment by bpesquero** [comment]
Hemos probado y persiste el problema. Cuando existen dos bancos para el cliente, se machaca el banco 2.

Gracias

**Comment by PKFEric** [comment]
Envio mail adjunto con la prueba.

**Comment by bpesquero** [comment]
Ahora si, no se debía haber actualizado el navegador.

Probado y ok
