### ISSUE TITLE
texto base de IVA erroneo en pdf de factura C/20183093

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#387]
En el pdf de la factura C/20183093 el texto de la base del IVA es erroneo. La base de IVA que coincide con el subtotal es de 109,83 y sin embargo pone  IVA (21% s/ 109,79 €). TEngo la sensacion de que no está cogiendo la reactiva.
Pasa tanto en la pagina 1 en el resumen como en la página 2 en el detalle

![image](https://user-images.githubusercontent.com/20299071/44780725-e0c67200-ab82-11e8-9c41-5fd00ec4f16d.png)

**Comment by jorgereal** [comment]
Se ha corregido el cálculo de la base del IVA que aparece en los textos del resumen y del detalle.

**Comment by bpesquero** [comment]
Revisado y ok
