### ISSUE TITLE
WEB - Opción de contrato a fecha fija (para el caso de permanencias)

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#389]
Añadir la opción de que el cliente pueda seleccionar la fecha a partir de la que comenzar a prestar los servicios. Muy útil para el caso de permanencia

Hay que añadirlo en la web, y en la creación de contratos de NAV, y por tanto en la generación de C1 de forma automática.

**Comment by dgarciageo** [comment]
implementado en nueva web/api
