### ISSUE TITLE
Contrato - representante legal y titular

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#39]
Al dar de alta los usuarios de los contratos que ya están funcionando en NAV Geo a todos los particulares no les aparece el representante legal ni el titular a la hora de exportar a pdf el contrato ni al ver los detalles.
En los de tipo empresa si aparece el representante legal pero no aparece la denominación social, ni en el contrato en pdf ni en lo detalles por pantalla. En el caso de empresa no aparece tampoco la tarifa de acceso contratada.

**Comment by bpesquero** [comment]
Lo veo igual, tengo que volver a generar los usuarios?

**Comment by PKFEric** [comment]
CORREGIDO-> HABIA QUE VALIDAR EN NAV LOS NOMBRES Y RELLENAR NOMBRE Y APELLIDO BIEN EN LA FICHA DEL CLIENTE DE NAV

**Comment by bpesquero** [comment]
Probado y ok
