### ISSUE TITLE
Informes de Medidas por CUPS tipos 1 y 2

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#390]
Se ha detectado que no aparece como tipo 2 un contrato cuya potencia contratada varió el 01.02.18

**Comment by JMunoz17** [comment]
En este caso las medidas no aparecen ya que el contrato al que están asociadas está en estado de baja. Actualmente solo se muestran las medidas asociadas a contratos con estado activado. No sé si queréis que los informes muestren las medidas asociadas a contratos que tienen estado baja.

Este es el caso en concreto del que hablamos:
CUPS ES0021000005425100XH1F
COM/00002 -> Estado = Baja | Tipo Punto de medida = 2
COM/00424 -> Estado = Activado | Tipo Punto de media = 4

**Comment by fmsanudo** [comment]
Sí, necesitamos que los contratos que se muestren sean los que estuvieran activos en la fecha de la medida del informe.

**Comment by JMunoz17** [comment]
Entiendo que este cambio es aplicable a los cuatro informes no? Supondría eliminar los filtros referentes al estado del contrato y a las fechas de inicio y fin de este.

**Comment by fmsanudo** [comment]
Sí, se trata de poder reproducir fielmente la cartera activa en cada fecha de la medida.

El filtro que hay que obtener es que la medida se encuentre entre la fecha de inicio y fin de facturación del contrato.

**Comment by JMunoz17** [comment]
He eliminado en los cuatro informes el filtro que implicaba que los contratos tuviesen estado activado para ser mostrados en el informe. Está subido a PROD.

**Comment by fmsanudo** [comment]
Gracias.
Entonces, para antes de hacer las pruebas. ¿Con la eliminación de este filtro nos aseguramos que tenemos todas las medidas en la base de datos de los contratos activos para cada una de las fechas de la medida?

**Comment by JMunoz17** [comment]
Tal y como hemos hablado por telefono, he modificado los filtros de fechas en los 4 informes para que se use el campo de fecha inicio facturacion en lugar del campo fecha inicio.

**Comment by bpesquero** [comment]
Perdón Jaime pero a mi no me queda claro, el filtro que debe hacerse es

fecha inicio facturación<=fecha medida<=fecha fin de facturación

Es asi?

**Comment by JMunoz17** [comment]
Al ejecutar el informe seleccionamos un mes, estableciendo como Fecha inicio filtro el primer día de mes y como Fecha fin filtro el último día de mes.

Tenemos en cuenta los contratos en los que:
                - Fecha inicio facturación (contrato) <= Fecha inicio filtro.
                - (Fecha fin (contrato) >= Fecha fin filtro) o (Fecha fin (contrato) vacía).

Posteriormente para cada contrato buscamos las medidas cuya fecha este comprendida entre la Fecha inicio filtro y Fecha fin filtro.

A mi lo único que me chirría de esto es que si por ejemplo sacamos el informe para febrero de 2018 y tenemos un contrato con fecha fin = 15 de febrero de 2018, pero sí que tenemos medidas entre el día 1 de febrero y el día 15 de febrero, estas medidas no aparecerían en el informe. (Podría pasar algo parecido con la fecha de inicio de facturación).

Creo que este caso es el único que se nos escaparía, pero es cierto que los informes que tiraban de la tabla antigua hacían esto mismo con la única diferencia que en vez de la fecha de inicio de facturación del contrato usaban la fecha de inicio del contrato. No sé si queréis que modifique los informes para controlar este caso.

**Comment by fmsanudo** [comment]
Efectivamente esto sería chirriante y erróneo.

Para el ejemplo de febrero, para el caso de un contrato con fecha de fin de facturación el día 15, deben aparecer sus medidas hasta el día.
