### ISSUE TITLE
Informes de Medidas tipos 3, 4 y 5

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#391]
- Añadir columna CUPS en Informe de medidas horarias
- No aparecen todos los puntos

**Comment by JMunoz17** [comment]
Actualmente el informe no agrupa los resultados por CUPS, de ahí que no lo estemos mostrando. Si me dais el OK lo modifico para que aparezca el CUPS, lo cual implica que los resultados aparezcan agrupados también por CUPS.

**Comment by fmsanudo** [comment]
Perdón por el cambio de opinión. Mantengamos el informe horario sin el CUPS.

Aún queda pendiente la otra cuestión de los puntos que aparezcan.

**Comment by fmsanudo** [comment]
Las pruebas finales quedan pendientes de la migración completa de los datos procedentes de las tablas viejas
