### ISSUE TITLE
Agregar campo de autoconsumo en la web de representación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#392]

**Comment by bpesquero** [comment]
El campo se ha añadido en la tabla servicios de SQL y de Oracle. Actualmente falta por incluirse en el script que sirve para sincronizar ambas BBDD.

**Comment by dgarciageo** [comment]
se comprueba que el campo de auto consumo se esta volcando correctamente en el script de sincronizacion entre la web y el servidor
