### ISSUE TITLE
Auto-Consumo en NAV energy

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#393]

**Comment by dgarciageo** [comment]
* Es necesario crear un campo check de auto-consumo en la ficha del contrato.
Este check se rellenará cuando llegue el paso 05 de activación (ya sea un C1,C2 o un A3) con el campo "Tipo de Autoconsumo" igual al que viene en el fichero. 

* Para estos contratos hay que desactivar la comprobación al cargar F1s de que el TE coincida con el cierre y que al generar la factura la suma de los F5Ds coincide con el cierre. En estos casos, se cumple que:
TE (F1)     <> Cierre AE(F1)
Cierre AE <> Sum(F5D) (AE + AS)
sin embargo
TE(F1)      ==  Sum(F5D) (AE + AS)

por tanto habría que incluir esta última comprobación al generar la factura de venta.

* Crear un campo desplegable en la ficha de contrato "Autoconsumo Geo" con 3 posibles valores. ("Vacio", "Factura Única" / "Factura Doble"). Este campo se rellenará por defecto en la creación del contrato a vacío y estará en no editable. 

* Cuando se rellene el valor del campo autoconsumo con un valor diferente de "00" el desplegable de "Autoconsumo Geo" se volverá editable y por defecto tomará el valor de "Factura Doble".

* Estos campos se crearán en una nueva pestaña en la ficha de contrato llamada "Autoconsumo".

**Comment by dgarciageo** [comment]
El nº del contrato que está en pre-facturas y con el que nos dimos cuenta de esta casuística es el COM/01200. EL F1 asociado lo puedes encontrar en:

N:\F1\Procesados\ID_GeoAtlanter, S.L._03190208030390562_F1_0119_18.xml

**Comment by PKFEric** [comment]
Control: SI es Autoconsumo es necesario el F5D (en compra)

**Comment by PKFEric** [comment]
Control-> Si es contrato de autoconsumo solo se aceptan F1 tipo N

**Comment by JMunoz17** [comment]
Hemos subido las modificaciones a producción y hemos generado la pre-factura de compra y de venta para el COM/01200, revisad si están bien.
