### ISSUE TITLE
Error carga factura regularizadora ES0022000005124353GD1P

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#394]
Al cargar el F1 de factura regularizadora del contrato COM/00301 da el siguiente error y no se carga la factura

![image](https://user-images.githubusercontent.com/20299071/45495815-541bd680-b774-11e8-9fb2-69cf6fd31402.png)

No sé cómo se hace la comprobación, pero la factura es correcta.

Contadme si queréis la comprobación que se está haciendo y lo revisamos. Envío fichero F1 por mail

**Comment by JMunoz17** [comment]
Contestado vía mail.

**Comment by PKFEric** [comment]
No estan cargadas las medidas F5D. Necesito que esten cargadas para poder probar.

**Comment by PKFEric** [comment]
Hemos revisado el contrato y el peaje, y tras cargar las medidas F5D asociadas a la factura nos da el error siguiente: Error XML, la fecha de medida inicial del F5D 30/06/18 es diferente de la fecha desde CCH 27/04/18 del peaje

Lo hemos hablado y esta factura esta reclamada por que efectivamente no se corresponden las medidas del contador inteligente con las fechas que vienen el el F1.
