### ISSUE TITLE
errata contrato pdf

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#40]
Al generar el pdf del contrato donde tenía que poner "se facturará el importe correspondiente a la aportación al Fondo Nacional de Eficiencia Energética" en vez de "importe" está poniendo el margen.
Por otra parte, donde pone el márgen esta mal, pone literalmente para el COM/00014 "fijada en 0,005 € al mes o €/MWh", no puede poner € al mes o €/MWh, en cada caso tiene que poner lo que corresponda, en función de que sea fijo o variable.

**Comment by PKFEric** [comment]
CORREGIDO WEB-> PROBAR

**Comment by bpesquero** [comment]
Probado y OK
