### ISSUE TITLE
Error facturas de venta regularizadoras

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#401]
En Geo tenemos problema con dos facturas regularizadoras. Da error al hacer la venta de que las medidas del F5D no coinciden con las de cierre
SE trata de:

COM/00692 | ES0031102182892001MP | 18/07/18 | 24/08/18 | Error, Las medidas F5D 44, de la factura FV/201805232 para el contrato COM/00692 no se corresponden con el termino de Energia 87,86
-- | -- | -- | -- | --
COM/00785 | ES0031408221014007EE | 04/09/18 | 13/09/18 | Error, Las medidas F5D 46, de la factura FV/201805232 para el contrato COM/00785 no se corresponden con el termino de Energia 92,018

**Comment by PKFEric** [comment]
Ya estan solucionadas las dos facturas. El problema venia por que el F5D terminaba a mitad del dia facturable, por lo tanto se interpretaba que habia que restarle 1 dia a la fecha desde del TE para compensar la diferencia de dia. No obstante al ser la primera factura de este contrato no era necesario. Y al restarle un dia buscaba los precios de ese dia anterior. Como no existian precios pensaba que habia 2 tarifas para ese contrato y generaba dos lineas de TE por cada periodo.


Ya esta solucionado.
