### ISSUE TITLE
Error carga F1 factura regularizadora con reactiva

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#402]
Al cargar en Hidroeléctrica El Carmen Energía el F1 SCTDE_F1_01_0022_0713_20180919080617353_(697238968).xml

da error "Error XML, la fecha desde de R1 del Cierre 17/07/18 es diferente de la fecha desde TR1 del peaje 16/07/18.”

Lo que yo veo es que es una factura regularizadora que está regularizando también reactiva y se está liando al hacer las comprobaciones.

**Comment by bpesquero** [comment]
Tenemos otro fichero con el mismo problema, si lo necesitáis me lo decís. 

Gracias

**Comment by JMunoz17** [comment]
Hemos implementado la solución y hemos importado el F1 de HECEN
SCTDE_F1_01_0022_0713_20180919080617353_(697238968).xml

Se ha generado la factura de compra y la factura de venta, comprobad si se han generado correctamente.

**Comment by bpesquero** [comment]
Revisada y ok
