### ISSUE TITLE
Problema COM/00213

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#404]
Estamos intentando futura el COM/00213. De manera que hemos cagado el F1 de la factura 03180510030089941 que va del 05/04/18 al 11/04/18 y su P1D correspondiente, pero vemos que le  está asociando medidas desde el 04/04/18 al 10/04 /18. Y no sabemos porque
 
Dejo la compra y la venta abierta en NAV

**Comment by bpesquero** [comment]
Volvemos a intentar facturar este contrato

Factura1: 04/04/2018 a 11/04/2018. Cargada la factura de compra. No tenemos P1D así que para facturar quitamos el check de energia horaria no telemedida. Da error de que no conciden las medidas del perfil con las medidas del término de energia

Factura2: 11/07/2018 a 06/08/2018. La factura de compra ya está registrada ( FCR/20183607), ahora he cargado el fichero P1D, pero claro no lo ha asociado. No me he dado cuenta de pasaroslo antes. Borro las medidas del P1D o las asociáis ahora a posteriori?

**Comment by PKFEric** [comment]
Ya esta correcta la factura.

Había un error en el cálculo del precio del término de potencia con máximetro para facturas de tipo N rectificativas con fechas TP de peaje diferentes de fechas PM de cierre. 

Faltaba multiplicar * 1000.

Las facturas a las que le aplica esta situacion muestran un AVISO: "Aviso, La factura FV/201805363 es de tipo N rectificativa con Maximetro, la fecha del TP del peaje es diferente de la fecha de PM del cierre, revisar."

En agosto nos encontramos con una situacion en la que fallaba por que el precio ya estaba multiplicado por 1000. Por lo tanto se pueden dar los dos casos. Esta es la tarea relacionada #382 . 

Lo he cambiado para que vuelva a multiplicar por mil pero puede que vuelva a venir un peaje en el que no haya que hacerlo como sucedio.

**Comment by bpesquero** [comment]
TEnemos otro problema con el COM/00213. tenemos una factura N que es regularizadora (las fechas de energía no coinciden con las fechas de la factura) y al hacer la venta sólo coge las medidas comprendidas entre las fechas de la factura.

**Comment by PKFEric** [comment]
He creado una nueva tarjeta con el nuevo problema para no liarnos.
