### ISSUE TITLE
Error carga fichero F1 por ausencia de P4

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#409]
ESto es algo que nos viene pasando desde hace tiempo, pero lo estamos arreglando manipulando el fichero F1 antes de cargarlo, y añadiendo el P4 ya teníamos cosas más urgentes
Error de carga F1: “el calendario de Medidas del contrato COM/00581 es 6p y el número de medidas es 5” No carga, y es porque no informan del P4 ni en potencia, medidas ni reactiva, así que modificamos el xml a manos y le añadimos el periodo a cero. Ya que Nav si carga 6p pero no F1 con solo 5p

            Ejemplos: Últimos F1 cargados del COM/00581 y COM/00749

**Comment by PKFEric** [comment]
He corregido el control que impide que se pueda facturar si no coinciden los periodos, solo para el caso en el que sean 3 de facturacion, y 6 de medida y ademas falte el periodo 4. 

hay que problarlo por que no tengo ningun ejemplo para hacerlo

**Comment by bpesquero** [comment]
probado y ok
