### ISSUE TITLE
exportación medidas horarias desde factura

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#41]
en algunos casos aparece vacío el fichero y en otros casos aparecen los registros horarios duplicados. Como ejemplo para el contrato COM/00017, la factura C/20160146 no descarga las medidas, la factura C/20160150 las descarga duplicadas.

**Comment by PKFEric** [comment]
C/20160146 la factura no tiene Medidas Asociadas
C/20160150  pendiente de probar cuando tenga acceso

**Comment by PKFEric** [comment]
ME HE DESCARGADO LAS MEDIDAS Y SALEN BIEN DEL CONTRATO C/20160150 LAS ADJUNTO AQUI

**Comment by PKFEric** [comment]
[Consumo_facturado_06-04-201608-05-2016-R.xlsx](https://github.com/geoatlanter/webProxima/files/377902/Consumo_facturado_06-04-201608-05-2016-R.xlsx)

**Comment by bpesquero** [comment]
Eric no están bien, fijate en el fichero. La suma es correcta, pero para cada hora aparecen dos registros, uno con valor 0 y otro con el valor correcto.

**Comment by PKFEric** [comment]
AHORA YA SI, PRUEBA PORFI

**Comment by bpesquero** [comment]
Probado y OK
