### ISSUE TITLE
Error carga F1 COM/00775

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#412]
Al cargar el F1 

201826164360_13869313_bpf.xml 
me da error de No se puede escribir '000001,000' en Integer.

Se trata de la constante multiplicadora. Lo cambio y le pongo "1" y entonces se carga la factura pero no se carga el cierre.

He dejado la prefactura en este estado para que lo podáis ver

**Comment by PKFEric** [comment]
Venia duplicado el primer periodo como totalizador, se ha corregido el peaje

**Comment by bpesquero** [comment]
REvisado y ok
