### ISSUE TITLE
problema con perfil gestor

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#413]
Dimos de alta el primer gestor y está teniendo probemas. Al entrar con su usuario y contraseña (que previamente había cambiado) se queda la página en blanco.
![image](https://user-images.githubusercontent.com/20299071/47358416-f27f4e00-d6c9-11e8-8f0a-d294cff5c9f6.png)

Envío por mail usuario y pwd del "gestor"

**Comment by jlagunapkf** [comment]
¿Alguien a modificado el código promocional de navision? Porque ese código no tiene la estructura que genera la web.

![imagen](https://user-images.githubusercontent.com/40607175/47370167-6c710080-d6e5-11e8-80e8-4731105b81b4.png)

**Comment by jlagunapkf** [comment]
Ya está cambiado este código, y el usuario se puede loguear. 

Para posteriores ocasiones. Se debe tener claro que el modelo del código es el siguiente

2 Primeras letras del nombre + 2 primeras letras del apellido + un número aleatorio de cinco cifras.

**Comment by bpesquero** [comment]
Lo modificamos manteniendo 4 letras y 5 números. Entendimos q no afectaba.
Hay q cambiarlo tb en la web por lo q veo?

**Comment by jlagunapkf** [comment]
Buenos días!

Exacto, aunque la estructura fuese la misma, este es el campo por el que se relaciona nav con el sql.

No es un campo editable desde la web. No se si es lo más correcto que se pueda editar tanto desde la web como en Navision. Se debería de valorar.

Un saludo
Jorge

**Comment by bpesquero** [comment]
Ok. Lo damos una vuelta. Fue porque el agente pidió que fuera un número que
el pudiera recordar facilmente....

**Comment by PKFEric** [comment]
Esta tarea ya esta revisada. El numero es el que se genera.
