### ISSUE TITLE
Clientes Morosos (Gestion de Cobros)

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#414]
Hay que crear en la ficha de cliente un nuevo campo "Cliente Moroso Recurrente" Este campo sera un booleano que identificara manualmente a los clientes Morosos. 

Hay que crear en la tabla Mov. Cliente el mismo campo y deberá de llevarse del cliente al Mov Cliente en caso de que el cliente lo tenga marcado, al registrar cualquier movimiento de cliente.

En la pantalla de gestión de cobros de NAV se deberá mostrar este campo y se deberá mostrar de color rojo en caso de que este marcado como "Si".

Hay que crear el mismo campo en las tablas "Cartera Doc." , "Posted Cartera Doc." y "Closed Cartera Doc.". Si el cliente tiene marcado el campo en su ficha se deberá de arrastrar en caso de que el movimiento se convierta en "Efecto/s".

Al recibir una devolución, a traves de la N19 de devoluciones. Si el cliente tiene marcado este campo se deberá de enviar directamente el mail de impago. Sin esperar plazo de tiempo y sin enviar el previo e-mail de Aviso.

**Comment by bpesquero** [comment]
¿cómo se marcan los clientes que son morosos recurrentes?

Además, he pensado que sería muy útil, para otras cuestiones, añadir en la pantalla de gestión de cobros el saldo del cliente y que  la línea se pintara de color verde cuando el saldo fuera a favor del cliente.

**Comment by bpesquero** [comment]
Se dice marcar los clientes cada vez que aparezca un movimiento de cliente:

-se consideran clientes morosos, los clientes que pagan por domiciliación y en los últimos 12 meses tienen 3 o más devoluciones
-se consideran morosos los clientes que pagan por transferencia y se les ha enviado la carta amistosa 3 o más veces. Para poder llevar el control se pondrá un acumulador del número de comunicaciones amistosas por cliente pagador

Por otra parte, el campo de cliente moroso será editable, para poder cambiar la condición de un cliente y habra un check "No actualizar morosidad automatica" para aquellos clientes que se quieran marcar como morosos y no se quiera que se actualice en cada movimiento de clietne

**Comment by PKFEric** [comment]
La tarea esta realizada en la BBDD de PREPRODUCCION esta pendiente de subir a produccion.

**Comment by bpesquero** [comment]
EStamos en proceso de pruebas y hemos visto lo siguiente en el caso de clientes morosos recurrentes de más de 10 kW:
1.-el texto de los mails es correcto, sin embargo los pdf desde roles se generan con los modelos de clientes no morosos.
2.- Hay que tener en cuenta en el proceso que los plazos cambian. PAra clientes morosos recurrentes de más de 10 kW la fecha de corte se calcula como la fecha de recepción del aviso de baja + 15 y por tanto la segunda comunicación (la de corte) tiene que salir también en esa fecha.

**Comment by bpesquero** [comment]
Otras dos cuestiones:

- los mails salen con caracteres extraños cuando hay tildes,...
-¿sería posible cambiar el nombre de los pdfs añadiendo por ejemplo detrás de cada uno de ellos el CUPS?

**Comment by JMunoz17** [comment]
Modificaciones realizadas y subidas a PRE.

**Comment by bpesquero** [comment]
Del tema de caracteres extraños, habéis visto algo? Se ha solucionado también?

**Comment by JMunoz17** [comment]
Debería de no suceder de nuevo, el problema era que estábamos controlando el tema de los acentos y la "ñ" solo para las minúsculas y la dirección que aparece en la esquina superior derecha de la comunicación esta en mayúsculas. 

En cualquier caso, si os volvéis a encontrar con alguna comunicación en la que no os aparezca bien algún carácter me reenviáis el mail del que se trate directamente y lo miro.
