### ISSUE TITLE
Certificado Atulado

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#415]
Llamar a Hostalia Para gestionar el Certificado de Atulado y para gestionar el hosting que hay contratado

**Comment by jlagunapkf** [comment]
*****RECORDATORIO*****
Modificación de la siguientes URL cuando se añada el certificado a la web.

-Envió de comunicación de nueva factura
-Imágenes que aparecen en el email (email de comunicación).

**Comment by jlagunapkf** [comment]
https://www.atuladoenergia.com
