### ISSUE TITLE
error modelo 560

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#421]
AL generar el modelo 560 desde Roles salta el siguiente mensaje , varias veces. Si le vas dando a aceptar al final se genera. Parece un warning, pero no sé muy bien de qué

![image](https://user-images.githubusercontent.com/20299071/48584464-111fe000-e92a-11e8-894f-c13f2a47b4df.png)

**Comment by JMunoz17** [comment]
Contesto vía mail.

**Comment by JMunoz17** [comment]
Subido a producción.

**Comment by bpesquero** [comment]
Comprobado y ok
