### ISSUE TITLE
Modificación de las condiciones particulares de Próxima

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#422]
Se han modificadolas condiciones particulares del contrato de próxima. La modificación es muy pequeña, se trata simplemente de una aclaración en la tabla donde se detallan los índices de precios, en la línea de sobrecostes del sistema.
Envío por mail el contrato con control de cambios, para que lo localicéis rápido.

Habría que cambiarlo en la descarga del contrato (tanto durante el proceso de alta como desde el área cliente) así como en el texto de "Cuéntamelo todo".

Necesito que me habiseis de la fecha exacta en que se sube a producción para el contol de cuándo se ha  empezado a firmar cada versión de contrato.
Gracias

**Comment by jlagunapkf** [comment]
Está realizado, falta subirlo a producción. En la siguiente actualización de web se actualizará. Te avisaremos cuando se realice.

**Comment by jlagunapkf** [comment]
Se ha subido a producción la web. A fecha de 22-11-2018.
