### ISSUE TITLE
error formulario de contacto de www.geoatlanter.com

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#423]
EL formulario del footer y el del área de contacto de la web www.geoatlanter.com da error
![image](https://user-images.githubusercontent.com/20299071/48765451-7705c200-ecb2-11e8-9629-51d5a2ed3f86.png)

**Comment by jlagunapkf** [comment]
necesito el usuario con el que accedéis a la bandeja de entrada del correo de contacto@geoatlanter.com

**Comment by jlagunapkf** [comment]
En principio el envío de emails de contacto funciona correctamente desde la web de www.geoatlanter.com el siguiente paso sería modificar el asunto y cuerpo del mensaje que se recibe desde el formulario de contacto.

**Comment by bpesquero** [comment]
Creo que con esto es suficiente, no?
Por qué crees que habría qeu cambiar el formulario? Es un poco cutre, pero no entra practicamente nadie por ahí

**Comment by jlagunapkf** [comment]
No, no me he explicado bien, es decir cambiar el contenido del email. 

Me refiero al contenido del email que se recibe, mas concretamente esto.

![imagen](https://user-images.githubusercontent.com/40607175/48911673-a4e63480-ee73-11e8-9410-d43f1446c98b.png)
