### ISSUE TITLE
asociación cliente bloqueado HECEN

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#424]
Estamos teniendo un problema con algunos de los clientes que ya tenemos en NAV y se dan de alta en yasoycliente para pasar a la ser cliente web.
Cuando asocia el usuario web al cliente NAV busca por CIF/NIF pero no mira que no esté bloqueado, así que se están asociando algunos a clientes bloqueados. Estoy cambiando a mano. Os paso uno que  no le cambiado para que lo veáis. En la asociación habría que tener en cuenta que el cliente no esté bloqueado.

**Comment by JMunoz17** [comment]
Hemos modificado el proceso de asociación para que el cliente tenga que tener el campo Bloqueado diferente a Todos.
