### ISSUE TITLE
clientes con cif duplicado

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#425]
OTra vez me han aparecido clientes con CIFS duplicados, la verdad que no lo entiendo. Podríamos poner un control en la ficha de cliente que al validar el campo mire si hay uno repetido?

**Comment by JMunoz17** [comment]
Una pregunta, esto ha pasado al introducir el cliente de forma manual en Navision o desde la web? Desde la web tenemos un control que verifica que ese CIF no este asignado a ningún cliente. 

Si os ha pasado de forma manual entonces basta con introducir el control al validar el campo en el cliente, pero si ha sido desde la web hay que ver por qué ha pasado.

**Comment by JMunoz17** [comment]
Modificado y subido a PROD.
