### ISSUE TITLE
Incidencias facturas web que no se descargan

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#427]
En el día de ayer se realizaron unas facturas y se subieran correctamente a la web. SE comprobó que se descargaban sin problemas. En el día de hoy no se pueden descargar las facturas y los clientes están protestando por ello. Las facturas están en el ft, desde donde se abren sin pb, pero no se descargan en la web. 
H_2018070406 (HECEN/05844) y H_2018070356 (HECEN/08249)

**Comment by PKFEric** [comment]
Se comenta que estan en el FTP. Ayer se hizo y si y hoy no.

**Comment by jlagunapkf** [comment]
https://www.atuladoenergia.com/DescargaFactura?FacturaID=H/2018070406

https://www.atuladoenergia.com/DescargaFactura?FacturaID=H/2018070356

Desde fuera se pueden descargar. Mediante usuario y contraseña desde local también lo descargo correctamente. ¿Algún posible problema con el servidor del ftp?

**Comment by bpesquero** [comment]
![image](https://user-images.githubusercontent.com/20299071/48837686-47c08500-ed86-11e8-8c04-e2f0ea06b654.png)

**Comment by bpesquero** [comment]
No creo que sea un pb de conexión con el ftp. Está es la única factura que no se descarga. Todas las demás si.

**Comment by jlagunapkf** [comment]
Resuelto y subido a producción.
