### ISSUE TITLE
Estado de factura en web

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#428]
Hemos visto que al crear una factura en la web aparece directamente con estado pagado, cuando aún no está pagada

**Comment by PKFEric** [comment]
Revision de los estados de las facturas.

**Comment by JMunoz17** [comment]
Nos podéis decir un nº de factura para la que os pase.

**Comment by bpesquero** [comment]
H/2018070406 del HECEN/08249
Ahora ya está hecha la remesa, pero sin pasar al banco, ni registrar ni nada.

**Comment by jlagunapkf** [comment]
Solucionado y subido a prod.
