### ISSUE TITLE
Creación de usuario web y asociación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#429]
YA nos ha pasado un par de veces: clientes de Hidroeléctrica El Carmen Energía que entran a yasoycliente para darse de alta en la web. HAcen el proceso completo, no reciben el mail de activación ni el de bienvenida, pero aparen en NAV con el creado web y con el check de factura electrónica.
El usuario no web no está creado. Así que no pueden entrar.

**Comment by bpesquero** [comment]
ej CL00594

**Comment by PKFEric** [comment]
No les llega el correo ni de activación ni de bienvenida. No esta creado el usuario web.

**Comment by jlagunapkf** [comment]
¿Sobre que hora se intento registrar? Porque he estado comprobando todos los campos, he realizado el registro en local en HECEN PRUEBAS y se ha realizado correctamente. ¿Quizás estuviera actualizando la web en ese preciso instante?

**Comment by bpesquero** [comment]
No sé, pero ha pasado con dos clientes ayer y con uno hoy

**Comment by jlagunapkf** [comment]
Esta mañana he estado instalando el certificado. Iniciando, parando y reiniciando la web. Para evitar esto, quizas debería por mi parte hacerlo a unas horas que me indiquéis, tumbo la web y evitamos estos posibles errores. Como me digáis.

**Comment by bpesquero** [comment]
Habéis verificado cuantos clientes marcados con el creado web no tienen usuario web?
PAra ver en qué situación nos encontramos

DEsde luego, para futuras ocasiones hay que tirar la web y poner un cartelito de en mantenimiento

**Comment by jlagunapkf** [comment]
Lo que hemos comentado antes Belén. Podéis comunicar al cliente que puede volver a registrarse en la web.

**Comment by bpesquero** [comment]
Ahora tengo el caso contrario. Se crea el usuario web pero no marca el check enNAV

CL08721
Usuario web: antvictoria@yahoo.es

Podemos mirar a ver si le ha pasado a alguno más?

**Comment by jlagunapkf** [comment]
Estos los tengo controlados, en la comparación que he hecho esta mañana me han salido los siguientes cliente, esto no impide que se vuelvan a registrar.

CL08354
CL08684
CL08721
CL09838
CL09839
CL09840
CL09841

**Comment by jlagunapkf** [comment]
Excepto tres todos los demás eran registros de pruebas.

**Comment by bpesquero** [comment]
Hemos visto que no  se ha actualizado bien en NAV. El  cliente que yo tenía controlado CL08721 si tiene “Creado Web” y está asociado con factura electrónica  el HECEN/07954 pero no el HECEN/08249.

Cuales son los otros dos que se detectaron que estaban mal para comprobar que todos los contratos tienen el check de factura electronica?

**Comment by jlagunapkf** [comment]
Estos tres primeros. 
CL08354
CL08684
CL08721

**Comment by bpesquero** [comment]
REvisdado,  a los tres les faltaban contratos por asociar,
