### ISSUE TITLE
Cambio de pagador en un contrato

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#432]
Realizar un boton en la ficha del contrato que permita crear un nuevo contrato copiando el contrato anterior. 

El contrato desde el que se copia se dara de baja, rellenando la fecha de fin de contrato y dandolo de baja dentro de NAV. El nuevo contrato se dara de alta con la  fecha de Inicio de facturacion como fecha de fin del contrato anterior + 1 dia. 

Para la creacion del nuevo contrato se solicitara el pagador de este ya que el cambio solo aplica por cambio de pagador. Por lo tanto el nuevo contrato creado llevara asociado el nuevo pagador.

Por ultimo en la creacion del nuevo contrato se deberan de rellenar todos los valores necesarios, como por ejemplo la creacion de precios de contrato. El estado del nuevo contrato sera directamente contrato activo.

**Comment by JMunoz17** [comment]
Realizado y subido a producción.

**Comment by bpesquero** [comment]
Hemos hecho la prueba y hemos encontrado lo siguiente:

1.- No lo hace como dijimos cogiendo como fecha de fin la fecha de la última factura y como fecha de inicio del nuevo esa misma + 1. Aparece una ventana emergente con la fecha actual, y además no deja cambiar la fecha
2.- Al pedir el cliente pagador no deja seleccionar de entre los ya existentes, y además tampoco funciona el comando "pegar" hay que teclear el número de cliente con el consecuente riesgo de error

**Comment by JMunoz17** [comment]
1.- Actualmente te propone la fecha del día actual, pero si que deja cambiarla (al menos a mi en producción y con vuestra licencia me ha dejado, es cierto que el fondo sale de color gris como si fuese un campo no editable pero es porque Navision no deja hacerlo de otra forma).

Si quieres podemos hacerlo de manera que en lugar de proponerte la fecha actual te proponga la fecha de la última factura de venta.

Dudas:
- La fecha te refieres a la fecha de registro no?
- Solo de facturas de venta registradas o también de pre-facturas de venta?

Si lo hacemos de esta manera os aparecerá esa fecha y tendréis opción de poder modificarla antes de seleccionar el cliente.

2.- Efectivamente, no permite usar el comando "pegar" y tampoco te deja seleccionar entre los clientes existentes. Para poder hacerlo de esta manera necesitaríamos usar un formulario y no tenemos ninguno libre en licencia, por lo que habría que comprar uno. Entendemos que para esto no merece la pena, pero como digáis. Para evitar ese riesgo de error lo que hicimos fue meter un control para evitar que se introduzca un cliente que no exista o el mismo cliente pagador del contrato actual.

**Comment by bpesquero** [comment]
1.- Si pudiera ser que propusiera la fecha fin de la última factura registrada( no la fecha de registro)
2.- OK

**Comment by JMunoz17** [comment]
Subido a producción.
