### ISSUE TITLE
tipo de contrato alta web

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#433]
Se ha dado de alta el primer cliente a través de la web de a tu lado, y la cuestión es que le ha asignado un tipo de contrato qeu no tiene la marca de web.

HECEN/09004, el ha asignado el tipo 01 y debería ser el 58

**Comment by jlagunapkf** [comment]
Cuando se puso la web en producción te envié un correo electrónico comentando que se debían asignar los tipos de contratos en navision para la web, enviandote la siguiente tabla y avisando que en caso de cambiar el codTipoContrato que se debía de sincronizar con el SQL

![image](https://user-images.githubusercontent.com/40607175/48890214-7f880500-ee38-11e8-8188-7b0f50aab2ce.png)

Aún así, para posteriores ocasiones. En la zona de administración 
![image](https://user-images.githubusercontent.com/40607175/48890115-2fa93e00-ee38-11e8-9c15-6bf344b6d4b9.png)

Se deben de sincronizar las tarifas con navision

![image](https://user-images.githubusercontent.com/40607175/48889926-aeea4200-ee37-11e8-9702-6ee19490b7e8.png)

En esta ocasión como puedes comprobar ya lo he sincronizado yo. Es importante tener esto en cuenta. Ocurre igual en proximaenergia.

**Comment by bpesquero** [comment]
ok. Cambié los contratos pero no me di cuenta de sincronizar
Lo siento. Gracias
