### ISSUE TITLE
mail de activación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#435]
Tenemos varias cuestiones con este tema

1.- Ayer dimos de alta un usuario a mano que se quedó sin crear el usuario web. Se le envío el mail de activación desde la parte de administración. AL clicar en la url que se le envía le lleva directamente a la home, y no le envía el mail de bienvenida. EL usuario web se queda en pendiente de activación, sin embargo el cliente nav tiene marcado el check de creado web

2.- Tenemos una serie de clientes que tienen el usuario web pendiente de activación. Hay de 2 tipos
    2.1-2 clientes a los que no se las he enviado el correo de activación, sin embargo tienen el check de 
   creado web en NAV. Tengo la sensación que el check de creado web se pone "antes de tiempo". 
   Debería marcarse con la activiación. Además, habría que revisar por qué no se les envío el correo
   **2.2- una serie de clientes a los que se le ha enviado. No podemos asegurar si tienen pendiente de 
  gestionar el correo o les ha pasado lo mismo que al del punto 1. La diferencia con el del punto 1, es 
  que el del punto 1 se hizo a mano y estos por el proceso normal. Igualmente, se da la circunstancia de que tienen marcado el check de creado web en NAV**

**Comment by jlagunapkf** [comment]
1. Lo voy a revisar.
2.1 ¿Habéis comprobado en el correo de clientes@atuladoenergia.com en la bandeja de elementos enviados si se han enviado los correos a estos usuarios? El check de creado web se activa en el momento que se da de alta la linea de un nuevo usuario en el sql, considero que esto debe de ser así, por coherencia de datos no? Al igual que el contrato está en estado creado web hasta que se realiza la activación que pasa a un estado de firmado. La idea inicial es esa. Como queráis.

2.2 La pregunta es, ese envío es desde el panel de administración, o desde yasoycliente? Porque si desde ya soy cliente ha funcionado a 150, no entendería que a los demás no les funcionase. Otro tema es desde el panel de administración que quizás no esté bien conformada la URL.

**Comment by bpesquero** [comment]
2.1 - Si, por eso digo que no se les han enviado. Siempre lo miramos, no hago caso de lo que dice el cliente . Respecto a lo que dices, si un cliente que ya es cliente, a través de yasoycliente se da de alta en la parte web y luego se arrepiente y no lo activa, no debería tener asociado nada, no? Si no, para que sirve la activación? En un contrato nuevo puede ser que tenga ya sentido traerse todos los datos, aunque tampoco lo tengo nada claro, la verdad. Yo creo que el check de creado web debe estar cuando el cliente confirma que efectivamente se quiere dar de alta en la parte web, mediante la activación.

2.2 EStos se han hecho desde yasoycliente, por eso digo que puede ser simplemente que no lo hayan getionado, sólo que cuando se vea lo que pasó en el punto 1 veamos si ha podido afectar también a estos o no al ser procesos distintos. Hasta que no sepamos lo que ha pasado en 1, creo que no podemos valorar. Sólo era para tenerlo en cuenta.

**Comment by jlagunapkf** [comment]
2.1 Lo normal, es que la activación de un usuario es la comprobación y verificación de que realmente la persona que se está registrando es quien dice ser. Y de esta manera crear un canal de comunicación con dicho usuario mediante su correo electrónico. Pero aún así, este check lo marcaremos cuando se active el usuario, no hay ningún problema. Aún así, si vieses algún incoveniente en esto, comentamelo. Me pongo con ello ahora mismo.
2.2 Vale. Edito el post principal y lo pongo en negrita para un futuro no se pase por alto.

**Comment by jlagunapkf** [comment]
En principio esta tarea estaría realizada ¿no?

**Comment by bpesquero** [comment]
ok
