### ISSUE TITLE
mail de activación de modificaciones

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#436]
Cuando se procesa una activación de una modificación (M_05) no se envía el mail al cliente tal y como se hace en Próxima.

**Comment by JMunoz17** [comment]
Hemos implementado el desarrollo para que se envíen los mails de activación, baja y cambio contractual en HECEN, tal y como se hace en Próxima.

**Comment by bpesquero** [comment]
Hemos procesado dos activaciones de los contratos HECEN/03772 y HECEN/06576.
EL primero de ellos no tiene usuario web y al procesarlo ha salido una ventana emergente diciendo que no tiene correo electrónico. Esto es ok
El segundo de ellos si tiene usuario web y se ha procesado pero no ha enviado el mail

**Comment by bpesquero** [comment]
Me dice Ainhoa que en Próxima si recibimos copia de los mails enviados de activación de los M

**Comment by JMunoz17** [comment]
En que dirección de correo? clientes@proximaenergia.com? Estoy ahí metido y no veo estos mails ni en enviados ni en bandeja de entrada, solo veo respuestas de clientes a esos mails.

**Comment by JMunoz17** [comment]
He realizado la modificación para que os lleguen estos mails en copia oculta.

**Comment by bpesquero** [comment]
Llegan a Gestion@proximaenergia.com

**Comment by JMunoz17** [comment]
Vale, ya lo he visto. Tenéis un campo en información de empresa para configurar si queréis que llegue un mail en copia oculta a alguna dirección. En GEO esta ese email de gestion@proximaenergia.com, en HECEN esta vacío, de ahí que no os llegara.

Yo ya realicé la modificación por código para que los de HECEN lleguen a clientes@atuladoenergia.com y los de GEO a clientes@proximaenergia.com por lo que no hace falta que rellenéis ese campo. Si queréis que no empiecen a llegar al de próxima me lo decís y lo quito.

**Comment by JMunoz17** [comment]
Veo que habéis movido esta tarea a TO-DO? Hay alguna incidencia?

**Comment by bpesquero** [comment]
No,no se que ha pasado
Lo vuelvo a poner en su sitio, y en cuanto tenga un rato limpio lo de Done


*Síguenos en:  <https://www.facebook.com/proximaenergia/>*
<https://twitter.com/proximaenergia>

*AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener información
*confidencial *sometida a secreto profesional. No está permitida su
reproducción o distribución sin la autorización expresa de *GEOATLANTER SL.*

Si usted no es el destinatario final por favor elimínelo e infórmenos por
esta vía.



De acuerdo con lo establecido por el Reglamento General de Protección de
Datos (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de
2016, le informamos que sus datos serán tratados con la finalidad de
realizar la gestión administrativa, contable y fiscal, así como el envío de
comunicaciones comerciales  sobre nuestros servicios y/o productos.


Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, oposición, supresión, limitación y portabilidad de
sus datos en el domicilio de *GEOATLANTER SL *sito en: Avda de Europa 34B
<https://maps.google.com/?q=Avda+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha 3º,  28023 Madrid o enviando un correo electrónico a la siguiente
dirección : *contacto@geoatlanter.com <contacto@geoatlanter.com>*

Si usted no desea recibir nuestra información, póngase en contacto con
nosotros enviando un correo electrónico a la dirección:
*contacto@geoatlanter.com
<contacto@geoatlanter.com>*
