### ISSUE TITLE
Sacar la imagen de pásate a factura electrónica y ahorra un 1 euro

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#438]
Sacar la imagen de pásate a factura electrónica y ahorra un 1 euro, sólo en el caso de que no estén en factura electrónica? No sé si hay q crear otra plantilla y cuanto tiempo llevaría el desarrollo. En función de eso decidimos.
Gracias

**Comment by JMunoz17** [comment]
La imagen solo aparece si el valor del campo de la factura/abono "Factura Electrónica" es igual a "NO".

Subido a producción.
