### ISSUE TITLE
generación de abonos pdf

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#44]
Al generar el abono en pdf no existe la opción de enviar mail, como en la factura.
Por otra parte, al generarse el abono, el documento pone no sólo el num de abono sino también la descripción del contrato, así que al subirlo al ftp con ese nombre, desde la web no encuentra la factura. He probado a cambiar el nombre y entonces si va bien. Hay que cambiar el nombre con el que se genera.

**Comment by PKFEric** [comment]
CORREGIDAS AMBAS COSAS EN NAV

**Comment by bpesquero** [comment]
Probado y ok
