### ISSUE TITLE
resumen de contratación 2º contrato

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#443]
al realizar un segundo contrato de un mismo titular, en el resumen final del proceso de contratación en el que aceptas condiciones, los decimales desaparecen de la potencia contratada.

![image](https://user-images.githubusercontent.com/20299071/50289661-c4b84a80-0469-11e9-9726-c653e93b03be.png)

**Comment by jlagunapkf** [comment]
Una vez que se cargan en navision o en el resumen? En este caso la potencia contratada en el periodo uno es 2,425 no?

**Comment by bpesquero** [comment]
En NAV está bien, es sólo en el resumen web.

**Comment by jlagunapkf** [comment]
No entiendo, en el resumen se muestra correctamente no?

**Comment by jlagunapkf** [comment]
Solucionado! El problema estaba en una conversión de la potencia introducida, se convertía a entero en vez de a decimal.
