### ISSUE TITLE
Problemas en pantalla de gestión de cobros HECEN

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#444]
No se puede filtrar por email en la pantalla de gestión de cobros

**Comment by bpesquero** [comment]
Además hemos visto que para el caso de devoluciones la fecha de vencimiento que muestra es una "fecha de vencimiento" del movimiento de devolución, que cálculo en base a la fecha de registro de la devolución. 
Necesitaríamos mostrar la fecha de vencimiento de la factura devuelta

**Comment by bpesquero** [comment]
Por otra parte, los movimientos pendientes correspondientes a efectos, no a devoluciones, que se corresponden con facturas no remesadas para clientes con forma de pago "C-DOMIC" no deben tenerse en cuenta en ningún caso en la gestión de cobros.

Ejemplo: Nº movimiento 5253192

Por lo que vemos no lo tiene en cuenta a la hora de calcular en las notificaciones la deuda agregada del cliente--> ok, lo marca en rojo--> ok, desde la pantalla de resumen que se muestra al entrar en NAV lo filtra como los que están pendientes de envío de reclamación formal de deuda.

**Comment by JMunoz17** [comment]
A partir del email no se puede filtrar ya que no es un campo de la tabla de movimientos de cliente, si no que es un dato que sacamos como texto simple a partir del cliente.

Al sacarlo del cliente, filtrar por el email equivale a filtrar por el cliente, que eso si que se puede.

**Comment by bpesquero** [comment]
No podríamos inventarnos algo para hacerlo. El filtro que quiero hacer es que el mail sea <>"", o que el mail sea =""
