### ISSUE TITLE
Proceso para cambiar término de pago

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#445]
Queremos cambiar el término de pago de todos los clientes con forma de pago C-DOMIC, sería pasar un proceso en los clientes y cambiar el término de pago actual (20D) por 3D, cuando 
forma de pago=C-DOMIC

**Comment by JMunoz17** [comment]
Tengo preparado el proceso para pasarlo, cuando me digáis lo hago.
Por confirmar, solo había que pasarlo en HECEN verdad?

En HECEN hay un cliente (CL08394) que tiene forma de pago C-DOMIC y método de pago CONT (Contado). Es el único caso que teniendo forma de pago C-DOMIC tiene un método de pago diferente a 20D, como debería de quedar este caso? También le ponemos método de pago 3D? O esto solo lo hacemos para los que tengan 20D como método de pago actual?

**Comment by bpesquero** [comment]
Se puede pasar el proceso. Efectivamente sólo en HECEN. El cliente que indicas se trata de un cliente que utilizamos para ajustar el saldo inicial en la migración y por tanto tiene caractarísticas especiales. En ppio lo mejor sería dejarlo como está,

**Comment by JMunoz17** [comment]
Proceso pasado en producción en la empresa de HECEN.
