### ISSUE TITLE
Descuento de 1 euro en factura electrónica

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#447]
DEberíamos considerar que es 1 euro mensual y prorratear por el nº de días.

**Comment by PKFEric** [comment]
Esto significaria que:

Cantidad = Fecha Hasta - Fecha Desde +1
Precio = 1/(Fecha Hasta - Fecha Desde +1)

No????

**Comment by PKFEric** [comment]
Precio = "Descuento Fact electronica"/(Fecha Hasta - Fecha Desde +1)

**Comment by bpesquero** [comment]
No, el precio sería de 12/365

**Comment by bpesquero** [comment]
Precio = "Descuento Fact electronica"*12/365

**Comment by PKFEric** [comment]
Tienes Razón

**Comment by PKFEric** [comment]
Ya esta subido a PRODUCCION
