### ISSUE TITLE
modificaciones impresión gestión de cobros

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#448]
Desde la pantalla de impresión de Roles de gestión de cobros sería útil añandir la posibilidad de imprimir sólo algunos tipos de carta. Yo pondría algo así como:

![image](https://user-images.githubusercontent.com/20299071/50905786-de72ff00-1423-11e9-84f8-0257cb68159e.png)

Que por defecto tuviera todo marcado a "Si" pero que se pudiera poner a No la opción que no deseemos imprimir

**Comment by JMunoz17** [comment]
Subido a pre y a producción. Este es el aspecto de la pantalla, la cual se ejecuta desde Roles (desde el mismo sitio desde el que se hacía hasta ahora).
En Departamentos -> Energy -> Hidroelectrica el Carmen -> Gestión de Cobros
![image](https://user-images.githubusercontent.com/26869276/51623496-1e180b80-1f39-11e9-85bd-a5fdd9c37308.png)

Por defecto aparecen marcados.
Solo se crean las cartas de los marcados al dar a ejecutar.

**Comment by bpesquero** [comment]
Ok.Probamos y te decimos
