### ISSUE TITLE
Verificación para ver si están cargados los perfiles o perfiles de usuario

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#450]
perfil y perfil usuario: ¿sería posible que hiciera una verificación de que tiene cargado los perfiles correspondientes y en caso contrario diese un aviso?

**Comment by fmsanudo** [comment]
Ante los cálculos del perfil y del perfil de usuario, siempre debemos disponer de un perfil inicial distinto de cero. Si se perfila sin perfil inicial o con un perfil inicial igual a cero y se insertaran medidas iguales a cero, la facturación derivada no es admisible, por lo que entiendo que el aviso debería ser crítico por lo y detener los procesos de cálculo de medidas y facturación.

Sin embargo, la ausencia de perfil final en meses anteriores al mes en curso sí debería avisarse, pero no tendría porqué parar ningún proceso. Por ejemplo, si se pide perfilar cualquier medida de febrero o antes de 2019 a fecha de 3 de marzo, se daría el aviso. Este aviso no saldría si la petición de perfilado se realiza a 27 de febrero.

En resumen,
- Ausencia de perfil inicial:: en todo momento:: aviso y fin de los proceso.
- Ausencia de perfil final:: para medidas anteriores al mes en curso:: aviso.

**Comment by JMunoz17** [comment]
He subido las modificaciones a PRE tal y como hemos hablado por teléfono de tal manera que:

- A la hora de generar el perfil de usuario:

  - Errores:

      - Si se trata de generar un perfil de usuario de fechas posteriores a la fecha actual.
  
      - Si se trata de generar un perfil de usuario y no tenemos los perfiles iniciales correspondientes cargados o estos tienen valor 0.

  -   Advertencias:
      
       - Si tenemos los perfiles iniciales pero no los finales y no existen medidas, se generará el perfil de usuario usando los perfiles iniciales y se mostrará una advertencia indicando que no existen perfiles finales.

       - Si tenemos los perfiles iniciales pero no los finales y existen medidas generadas con los perfiles iniciales, no se genera el perfil de usuario y se mostrará una advertencia indicando que no existen perfiles finales.

       - Si tenemos los perfiles iniciales y los finales y existen medidas generadas con los perfiles iniciales, se genera el perfil de usuario usando los perfiles finales y no se muestran advertencias.


Las advertencias se muestran en un log (el mismo que se usa para la carga de F5D, por ejemplo) de la siguiente forma: 

![image](https://user-images.githubusercontent.com/26869276/53969392-01a2ed80-40f9-11e9-850e-5f388e050926.png)

![image](https://user-images.githubusercontent.com/26869276/53969413-0c5d8280-40f9-11e9-8684-fe2a57f8c32c.png)

- A la hora de calcular un perfil en el proceso de facturación:

  - Si no tenemos los perfiles iniciales devolvemos un error indicando que no se ha podido calcular el perfil para facturar. 


Quedo a la espera de vuestras pruebas para subirlo a producción.

**Comment by fmsanudo** [comment]
Pruebas exitosas respecto a los supuestos de generación de errores.

Pruebas fallidas en la de advertencia:

Borrados los perfiles finales de la tabla 'Electric Consumption Profile' del mes de enero de 2019,
Ejecutado el proceso 'BorradoMedidasPerfilUsuarioBlo' para el mes de enero de 2019,
Pedido el Perfil de Usuario para el mes de enero de 2019,

No se obtiene ningún registro en el 'Log generación perfilado'

**Comment by PKFEric** [comment]
Solucionado, enviado mail a Fernando

**Comment by fmsanudo** [comment]
Correcto

**Comment by JMunoz17** [comment]
Subido a PROD.
