### ISSUE TITLE
Revision del proceso de traida de medidas desde oracle

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#451]
Oracle: el proceso de traer medidas de Oracle, se ejecuta una vez a la semana para 5 puntos, es decir, se trae medidas de una semana de 5 puntos y tarda del orden de 45minutos. Habría que revisarlo

**Comment by dgarciageo** [comment]
Orac.nhumberof rows hace la consulta, y te devuelve el numero de fila
Y desde 0 al num de filas 

PA_MEDIDAS_CONTADOR_NI
Codeunit: 55000.  
OR_CON en la tabla confug bddd
Orac.number of rows llama al PA con todos los parámetros.
El orac es una dll que hizo attest que lo uncoio que hace es conectarse con el oracle.

Carga Datos ESIOS
Descraga BBDD-Ficheros
Descarga Manual BBDD

**Comment by dgarciageo** [comment]
La vista  V_M_PF_FORMULAS del PA_MEDIDAS_CONTADOR_NI debe ser substituida por una función tabla
