### ISSUE TITLE
Nuevo campo para gestión de cobros

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#454]
Me gustaría añadir un campo en la ficha de cliente que fuese un booleano "acuerdo de pago" y que se arrastrase a los movimientos y se viese desde "Gestión de cobros"

**Comment by JMunoz17** [comment]
Este campo tiene que tener alguna funcionalidad? O solo se va a usar a nivel informativo?

**Comment by bpesquero** [comment]
En ppio con tenerlo a nivel informativo es suficiente

**Comment by JMunoz17** [comment]
Tenemos dos opciones:
   - Hacerlo con un campo calculado de tal manera que el valor actual en la tabla de clientes sea el valor que tenga en todos los movimientos de cliente que vas a ver desde "Gestión de cobros".
   - Que tenga el valor que tuviese este campo en el cliente en el momento en que se genera el movimiento.

Como nos digas.

**Comment by bpesquero** [comment]
La primera opción, con un campo calculado

Gracias

**Comment by bpesquero** [comment]
Perdón, veo que si que debería tener una funcionalidad.
Sería que los movimientos que se generasen de un cliente con "acuerdo de pago"=si, se generasen como "gestionado" en vez de como pendiente.
Al  marcar un cliente como acuerdo de pago, habría que recorrer todos los movmientos y ponerlos como gestionados. O poner un proceso para hacerlo que se lance desde la ficha de clientes

Además, en todos los procesos los movimientos con el estado "gestionados" hay que asimilarlos a los de "Gestión externa" o "no gestionar"

**Comment by bpesquero** [comment]
Por otra parte, lo pongo aquí aunque no sé si preferís una tarea nueva. 
Los pdfs de via amistosa, sólo deberían generarse de aquellos clientes que no tienen mail. Si se les ha enviado el mail, no hay que enviar carta, así que es mejor que no se genere el pdf

**Comment by bpesquero** [comment]
Aprovecho para preguntar una cosa, que no me queda clara. 
Con los morosos recurrentes domiciliados, cuando se registra la devolución en NAV se envía el mail, automaticamente, de reclamación formal de deuda. Y quedan de alguna forma marcados para el envío de carta de reclamación formal de deuda, Si paso el proceso de marcar reclamación formal de deuda no los marca, y si me voy a roles y le doy a imprimir si me los imprime. Hasta aquí, más o menos ok. Aunque no entiendo por qué se quedan como marcados automaticamente

Lo que no entiendo es qué ocurre con los de transferencia que son morosos recurrentes. Parece que se marcan automanticamente también y se envía el mail, pero esto no tiene sentido. SE ha marcado automaticamente una fecha de envío de mail de reclamación formal al superarse la fecha de vencimiento y, al igual que en las domiciladas, no se marcan con el proceso pero se genera el pdf. 
Si no me he explicado, cosa más que probable, llamadme y lo comentamos

**Comment by JMunoz17** [comment]
Para el campo de los movimientos de cliente "Acuerdo de Pago", al ser un campo calculado, no es necesario actualizar el valor al marcar o desmarcar el campo de "Acuerdo de pago" en la tabla de clientes, ya que se realiza de manera automática. 

Como tenemos este campo creo que es mejor que no modifiquemos el estado del contrato y que para descartar estos movimientos en cualquiera de los procesos (incluida la pantalla de gestión de cobros) del desarrollo filtremos por el campo "Acuerdo de pago". El funcionamiento sería el mismo pero el estado de los movimientos no sería "gestionado", no sé si hay algún inconveniente con esto.

El problema que yo veo es que si marcas en un cliente el campo "Acuerdo de pago" y de manera automática marcamos todos los movimientos como "gestionados" funciona todo bien, pero si luego hacemos lo mismo al revés, qué valor le asignaríamos al campo "Situación de recobro" para cada movimiento de cliente (pendiente, gestión externa...). Creo que sería mejor filtrar por el campo "Acuerdo de pago".

**Comment by JMunoz17** [comment]
Al tema de no generar los pdfs de vía amistosa en el caso de que el cliente tenga email, OK.
Por confirmar, tanto para devolución de recibos como para transferencia no?

**Comment by JMunoz17** [comment]
**Respecto al primer párrafo de tu último mensaje:**

El botón de marcar sirve para marcar los movimientos de cara al envío de emails, no para la generación de cartas. 

La carta digamos que esta "marcada" en el momento que la fecha de envío del email correspondiente esta rellena y la ruta de la carta no esta rellena, por eso cuando viene una devolución de un recibo de un cliente moroso se envía el email correspondiente a la reclamación formal de deuda y al no tener rellena la ruta de la carta pero si la fecha de envío del email está queda como "marcada" para la generación de la carta.

**Respecto al segundo parrafo:**

El funcionamiento es similar al anterior.

Le das al botón de "Marcar mail vía amistosa de transferencia" y se marcan todos los movimientos que cumplan las condiciones, independientemente de si corresponden a cliente moroso o no.

Cuando le das a "Enviar mail vía amistosa de transferencia" se procede a enviar los emails de los movimientos marcados previamente. Es en este momento cuando se discrimina entre clientes morosos y no morosos.

- Si no es moroso marcamos que hemos enviado el mail de via amistosa de transferencia y de esta manera queda pendiente para la generación de la carta amistosa de transferencia (Esto último dejará de hacerse con la modificación que nos has pedido en el mensaje anterior).

- Si es moroso, se rellena la fecha de envío de mail de vía amistosa de transferencia (aunque este mail no se ha enviado), se rellena la ruta de la carta amistosa de transferencia (con este texto: "NO GENERADA - CLIENTE MOROSO") y se rellena la fecha de envío de mail de reclamación formal de deuda (este mail si se ha enviado) y queda en blanco la ruta de reclamación formal de duda quedando de este modo "marcada" como pendiente su generación.

**Comment by JMunoz17** [comment]
Si algo no te cuadra dame un toque y lo vemos.

**Comment by bpesquero** [comment]
En cuanto al funcionamiento de acuerdo de pago ok

**Comment by bpesquero** [comment]
En cuanto a no generar el pdf de vía amistosa, efectivamente tanto domiciliación como transferencia

**Comment by bpesquero** [comment]
Ok. Creo que he entendido el funcionamiento

**Comment by JMunoz17** [comment]
Una pregunta, respecto al tratamiento del campo "Acuerdo de pago":
Me dices que tiene que funcionar como los casos de "No gestionar" y "Gestión Externa", esto implicaría que NO pueden ser el movimiento origen de la comunicación, pero SI se puede contabilizar su importe al agrupar.

Lo de que no puede ser el movimiento origen esta claro, pero puede tenerse en cuenta su importe en otras comunicaciones como importe acumulado?

**Comment by bpesquero** [comment]
En realidad como hemos dicho que este campova a tomar en cada momento el
valor que tenga el contrato, que no existe la posibilidad que algún
movimiento sea origen y otros no. No es así?
Gracias

**Comment by JMunoz17** [comment]
No estoy 100% seguro de que se pudiese dar, desde luego no creo que sea un caso habitual.
Pero tienes un cliente 1 (marcado como "Acuerdo de pago") que tiene el contrato 1 con CUPS 1 (dado de baja) y tienes el cliente 2 (NO marcado como "Acuerdo de pago") que tiene el contrato 2 con CUPS 1.

Si se emite una comunicación cuyo movimiento de origen corresponde a este segundo contrato, al buscar por CUPS se pueden encontrar los movimientos del cliente 1 marcados como "Acuerdo de pago", ahí tendría que saber si los acumulo o no.

**Comment by bpesquero** [comment]
Ok. Entonces habría que incluir el movimiento del contrato 1 con acuerdo de pago.

**Comment by JMunoz17** [comment]
Lo acabo de subir a PRE, incluye también la modificación para que los PDFs de vía amistosa solo se generen si alguno de los dos clientes (titular y pagador) no tienen relleno el email.

**Comment by bpesquero** [comment]
No entiendo, los de vía sólo se envían a pagador.

**Comment by bpesquero** [comment]
En la incidencia teníamos tres cosas:
-Campo de acuerdo de pago: campo calculado que se trae el valor que tenga el contrato, no se tiene en cuenta, no puede ser origen de notificaciones aunque si forma parte del importe que se envíe en una comunicación a ese cliente
-Pdf por vía amistosa, no se genera pdf si ya se ha enviado email
-ASimilar el funcionamiento de "Gesitionados" al de "No gestionar", es decir no pueden ser origen de un a notificación pero si forman parte del importe reclamado.

Me puedes decir cómo está cada uno de los puntos y aclararme lo de los pdf?

**Comment by JMunoz17** [comment]
- **"Acuerdo de pago"** - Hecho y subido a PRE.

- **PDF Vía Amistosa: No se genera pdf si ya se ha enviado email** - Yo lo había hecho de manera que se generase la carta en caso de que o el cliente pagador o el titular tuviesen el mail vacío. Efectivamente tal y como dices para estas comunicaciones solo hay una carta (al pagador), así que lo pondré para que solo se genere la carta si el pagador tiene el mail vacío (me he liado porque el envío de mail si que va a pagador y titular, pero la carta no). Modificado y subido a PRE.

-**Funcionamiento gestionados** - De esto no he tocado nada (ahora mismo el valor "gestionado" es como si no tuviese funcionalidad, es decir, como si estuviese pendiente).

Este valor se lo asignáis vosotros manualmente no? Yo lo que entendí es que en vez de usar el valor "Gestionado" del campo "Situación de recobro" de los movimientos de cliente, usamos el campo "Acuerdo de pago" de los mov. cliente que tira del campo con el mismo nombre de la tabla de clientes (es un campo calculado). Es decir, no deberíamos tener movimientos de cliente con el valor "Gestionado". Me dices a ver que te parece.

**Comment by bpesquero** [comment]
En cuanto a los movimientos "Gestionados" no siempre están gestionados porque tengan un acuerdo de pago. Puede que se gestionando de alguna manera y no se quiera enviar nada pero no tenga acuerdo de pago. Es que lo mezclé todo, pero son dos cosas distintas

**Comment by JMunoz17** [comment]
Es decir, lo que falta es dar el mismo trato al valor "Gestionado" que el que tiene el valor "No gestionado" o "Gestión Externa". Lo hago y lo subo a PRE.

**Comment by bpesquero** [comment]
Creo que Gestión externa es un poquito diferente, no? Sería como "no gestionar"

**Comment by JMunoz17** [comment]
Ok

**Comment by JMunoz17** [comment]
Subido a PRE.
