### ISSUE TITLE
Nuevo estado de contrato

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#455]
Añadir un nuevo estado a los contratos que sea "Corte"

**Comment by JMunoz17** [comment]
¿Qué funcionalidad debe tener este campo?

**Comment by bpesquero** [comment]
En principio es sólo informativo nuestro.

**Comment by bpesquero** [comment]
Aunque no sé si es posible mostrar en gestión de cobros el estado del contrato

**Comment by JMunoz17** [comment]
Subido a PRE.

**Comment by JMunoz17** [comment]
Tenéis un botón en la ficha del contrato para poder cambiar el estado a "Corte".
