### ISSUE TITLE
procesamiento ficheros M1

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#460]
al procesar un M_05 he visto que se ha creado un nuevo contrato pero no pone en estado de baja el contrato anterior, aunque si rellena la fecha de baja
al procesar un M1_02 con sólo cambio de titular pone el nuevo contrato en estado aceptado ATR, en vez de activado

Ambas cosas se estaban haciendo bien, ¿qué se ha cambiado de esto?

**Comment by JMunoz17** [comment]
Solicitada información de los contratos vía mail.

**Comment by bpesquero** [comment]
Para el caso del contrato M1_02 HECEN/09165, he cambiado yo el estado y por eso lo verás ya como activado
Para el M1_05 el contrato  COM/01121

**Comment by JMunoz17** [comment]
- Para el contrato HECEN/09165 no veo que el histórico de acciones tenga marcado que hay cambio de titular tal y como dices, por eso en el contrato se puso Estado = "Aceptado ATR", que es la funcionalidad que hay contemplada para esta situación en la que no hay cambio de titular (esto es algo que ya comentaste en su día con Eric, porque en realidad el contrato esta activado pero debe tener este estado de "Aceptado ATR"). El campo status es no editable en la tabla, como lo has modificado?

- Para el contrato COM/01121 he visto que lo único que tienen es un cambio de tarifa ATR y para ese caso lo que esta contemplado es que ponga el contrato antiguo en estado de baja y actualice fecha de fin del contrato. He visto que el COM/01121 tiene estado = "Baja" y este campo no es editable, por lo que entiendo que o esta bien o que lo has cambiado tu también.

**Comment by bpesquero** [comment]
Con respecto al primer tema lo miramos
Con respecto al segundo, he cambiado yo el estado, porque no estaba en estado de baja

**Comment by bpesquero** [comment]
Para el contrato HECEN/09165 no hagáis caso, error nuestro.
Para el contrato   COM/01121 como os digo el contrato anterior no se puso en estado de baja.

**Comment by JMunoz17** [comment]
Ok.

Para el caso del contrato COM/01121, tal y como te dije solo había cambio de tarifa ATR, lo cual implica que se cree un nuevo contrato (se ha hecho) y que el contrato antiguo se ponga en estado de baja y se rellene la ficha de fin del contrato (se ha hecho).

Lo único que no se ha hecho es lo del estado...viendo el código es difícil de concebir que se modifique la fecha y no el estado, si queréis con el próximo M1_05 que tengáis con cambio de tarifa ATR nos lo decís para cargarlo nosotros y ver por que sucede esto.

**Comment by bpesquero** [comment]
Se han procesados más M1_05 ok. Cerramos la incidencia.
