### ISSUE TITLE
Creación contrato desde la web

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#462]
AL crearse un contrato desde la web no se rellenan los siguientes campos en la ficha del cliente:

- Término de pago--> 3D
- Forma de pago--> C-Domic
- Dirección de envio genérica

**Comment by jlagunapkf** [comment]
Para que se rellene el término y método de pago es necesario marcar el check de término web y método web en sus respectivas page.

**Comment by bpesquero** [comment]
Tienes razón. No me acordaba
