### ISSUE TITLE
Personalizar menú Roles - según la empresa abierta

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#471]
Cuando accedes desde roles a los procesos de lanzar facturas / Lanzar abonos necesitamos que en el menú de energy sólo sean accesibles las opciones correspondientes a la empresa que tengas abierta en ese momento. i.e., si  tengo abierto Geoatlanter que no se puedan lanzar los procesos de HECEN ( y viceversa).

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

No es posible ocultar los botones, por lo que al ejecutar se mostrará un error en caso de no estar en la empresa correcta. La comprobación se realiza en función de los checks de Empresa Web (GEO) y HECEN que tenemos en la tabla Company.
