### ISSUE TITLE
Subir a producción campaña Amigo

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#474]
Subir pre-producción campaña amigo y realizar pruebas.
Relacionado con la issue #282

**Comment by PKFEric** [comment]
Se ha montado el entorno de PRE y ahi esta la campaña amigo para ser probada.

**Comment by dgarciageo** [comment]
En el listado de contratos debería aparecer una columna con el código promocional asociado a cada contrato asi como el saldo promocional pendiente para cada contrato

![image](https://user-images.githubusercontent.com/47117960/56606307-2d752680-6606-11e9-8e73-9415dfc85b20.png)

**Comment by dgarciageo** [comment]
Buenas eric,

- Al darse de alta un amigo en la tabla lista de campaña los códigos de los contratos se están almacenando al revés

![image](https://user-images.githubusercontent.com/47117960/57233792-9d7ca700-701f-11e9-98b4-475a12140cdd.png)

-  falta el icono de la pestaña amigo, si es problemático en términos de estilos o formato responsive podemos pasar sin  él

![image](https://user-images.githubusercontent.com/47117960/56960085-f5af3700-6b4f-11e9-8981-0b97bdaf20c2.png)


- Al borrar una factura de venta no registrada (para restaurar el importe promocional de inicio) no se restaura el importe inicial si dicho importe fue mayor que la factura de venta

![image](https://user-images.githubusercontent.com/47117960/57234233-7e324980-7020-11e9-9dad-fa2f8ddeeabb.png)


la linea de 10€ debería desaparecer
![image](https://user-images.githubusercontent.com/47117960/57234565-3829b580-7021-11e9-8b77-c468388bd5ae.png)
