### ISSUE TITLE
Correos Altas Representación

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#475]
Cuando se da de alta un cliente nuevo en la web de representación no se envían los correos de bienvenida.

**Comment by jorgereal** [comment]
El envío del mail solo es efectivo desde la ventana de modificar planta. Si el titular de la planta está relleno se envía un mail a este al pulsar en grabar, el contenido dependerá de si se trata de un nuevo usuario o no.
Desde la ventana de usuarios planta no esta implementada esta funcionalidad.
Ya nos decís si queréis que lo añadamos a esta ventana y el contenido del mail.

**Comment by dgarciageo** [comment]
Tenéis razón, el problema es que desde ahi tampoco se envía el email. El funcionamiento es el siguiente:

1) Se da de alta un usuario en la web con un email
![image](https://user-images.githubusercontent.com/47117960/56899763-93453080-6a94-11e9-98f9-c70ead379ce7.png)

2) Se da del alta un titular cuya persona de contacto sea ese titular
![image](https://user-images.githubusercontent.com/47117960/56899840-bff94800-6a94-11e9-8910-d30b7db8016a.png)

3) Finalmente se asigna a un planta el titular y le debería llegar el correo a la persona de contacto, pero no les llega
![image](https://user-images.githubusercontent.com/47117960/56899915-e9b26f00-6a94-11e9-87e3-7b34c0858563.png)

He hecho la prueba con mi usuario que tiene mi correo pero no me ha llegado nada. 

Me comenta Mónica que cuando se rellena la fecha de alta en el negocio debería enviarse otro correo
![image](https://user-images.githubusercontent.com/47117960/56900788-f768f400-6a96-11e9-93b9-c4b449dfd64f.png)

**Comment by jorgereal** [comment]
Existían errores de encoding y del envío SMTP en el módulo.
Se han corregido tanto para los mails que se deben enviar al asignar el titular como al rellenar la fecha de alta en negocio.

Después de observar el código cabe destacar que el mail al asignar el titular tan solo se envía si la ficha de la planta se ha abierto desde el botón de insertar registro en el listado de plantas, es decir al dar de alta una nueva planta y rellenar el titular. Si se modifica una planta ya existente, ya sea un cambio de titular o cualquier otro cambio este mail no se enviará.

El mail correspondiente a la fecha de alta en negocio tan solo se envía si el valor de este campo es vacío y se rellena. Por ejemplo para probar con la planta de prueba habría que vaciar esta fecha, grabar, rellenarla y grabar para que se realice el envío.

Para controlar estos dos tipos de mails se puede consultar la tabla Mailings del MYSQL, filtrando por Title = "NUEVA PLANTA DISPONIBLE" ó "ALTA EN SERVICIO DE SU PLANTA", donde se recogen todos los mails enviados .
