### ISSUE TITLE
Error Carga F1 - ES0031101842594005HF

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#477]
* Fichero: N:\F1\20190218-Endesa (24).xml
* Error: Los acumulados de la factura regularizada en peaje son diferentes del cierre.* 
* Desc: el xml a además de ser una G, en la parte de la medidas tiene el concepto: “Ajuste” “Ajuste por Integrador -000119978.00” y en comentarios: “CARGO/ABONO A PRORRATEAR”

**Comment by PKFEric** [comment]
Se han modificado las fechas del cierre y del peaje del TE para que corrigiera correctamente la factura anterior.

Se ha añadido un nuevo criterio de calculo del TP al generar la Fac de compra para potencia dividida en 2 fechas y potencia en W y precio en KW

**Comment by dgarciageo** [comment]
Buenas Erick,

Sale mal la venta, tiene cambiados los puntos y la comas y nos sale una factura de 42.677,40€
Dejo la factura de venta en prefecturas para que podáis echarle un ojo

**Comment by dgarciageo** [comment]
Buenas Erick,



Sale mal la venta, tiene cambiados los puntos y la comas y nos sale una
factura de 42.677,40€
Dejo la factura de venta en prefecturas para que podáis echarle un ojo



*De:* Eric <notifications@github.com>
*Enviado el:* viernes, 8 de marzo de 2019 14:07
*Para:* PKFEric/webProxima <webProxima@noreply.github.com>
*CC:* dgarciageo <dgarcia@geoatlanter.com>; Assign <
assign@noreply.github.com>
*Asunto:* Re: [PKFEric/webProxima] Error Carga F1 - ES0031101842594005HF
(#477)



Se han modificado las fechas del cierre y del peaje del TE para que
corrigiera correctamente la factura anterior.

Se ha añadido un nuevo criterio de calculo del TP al generar la Fac de
compra para potencia dividida en 2 fechas y potencia en W y precio en KW

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/PKFEric/webProxima/issues/477#issuecomment-470922121>,
or mute the thread
