### ISSUE TITLE
Desarrollo pistola impagos

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#478]
* Tenemos un alto número de impagos que generan un número considerable de envíos de cartas certificadas. 
* Cuando la carta certificada no ha podido ser entregada se hace registro del evento y se envía una segunda carta certificada. El problema es que cuando un certificado viene devuelto resulta muy difícil identificar el impago que generó dicha carta certificada para dejar registro.

* La única forma de facilitar la búsqueda sería almacenar en un campo adicional de la tabla Gestión de Cobros el código de barras de la carta certificada asociada a dicho impago (cada carta certificada se identifica unívoca-mente mediante un código de barras). Así, si la carta certificada es devuelta, resultará sencillo el identificar el impago. La lectura del código de barras se realizará mediante un lector usb de código de barras. 

* Cuando una carta certificada es devuelta se tiene que enviar una segunda carta certificada con un segundo código de barras. El proceso será el mismo al de la primera lectura y se almacenará el código en un segundo campo de la tabla gestión de impagos.

* Se creará un campo de "Fecha devolución reclamación formal de deuda" con la misma lógica que el campo "Fecha de recepción de reclamación formal de deuda", esto es, que calcule automáticamente al ser informado el valor del campo "Fecha de corte".

* El usuario al recibir la primera devolución no rellenará la "fecha de devolución de reclamación formal de deuda" en la pantalla de gestión de cobros. Sin embargo, si es el segundo intento si se rellenará esta fecha, asumiendo 2 intentos infructuosos, y por tanto, conforme a normativa, la carta se da por entregada.

**Comment by JMunoz17** [comment]
Necesito saber que tipo de código de barras es el utilizado por correos para conocer la longitud de este y si es numérico o alfanumérico.

**Comment by JMunoz17** [comment]
Y no vais a necesitar otros tres campos para hacer lo mismo pero en vez de con la reclamación formal de deuda con la comunicación de resolución de contrato? O si os devuelven esas cartas lo gestionáis de otra forma?

**Comment by bpesquero** [comment]
Hemos estado dando una vuelta al tema y creemos que quizá interese hacer un cambio en el planteamiento inicial

**PROCESO DE RECLAMACIÓN DE DEUDA**
Pueden existir dos envíos asociados a este proceso, así que entendemos que serían necesarios los siguientes campos

-Código de barras del primer envío
-Fecha de recepción del primer envío (este campo ya existe)
-Fecha de devolución del primer envío (sólo informativo, no calcula la fecha de corte)
-Código de barras del segundo envío
-Fecha de recepción del segundo envío (tendría la misma lógica que el campo fecha de recepción del primer envío, es decir, tiene que implicar un cálculo de la fecha de corte)
-Fecha de devolución del segundo envío (misma lógica que la fecha de recepción del primer envío)

**PROCESO DE RESOLUCIÓN DE CONTRATO**
Aunque la notificación sea devuelta no se realiza un segundo envío. Sería interesante añadir los siguientes campos:

-Código de barras de resolución de contrato  (sólo informativo)
-Fecha de devolución de resolución de contrato  (sólo informativo)

**Comment by JMunoz17** [comment]
Para que sería necesario dos fechas de recepción dentro del proceso de reclamación de deuda? 
Al fin y al cabo la carta solo se puede recibir una vez como máximo, creo que no es necesario tener dos campos, yo diría que lo mejor es dejar solo uno (el que ya existía) y que siga funcionando como hasta ahora, ok?

**Comment by dgarciageo** [comment]
Perfecto Jaime, muchas gracias!

**Comment by JMunoz17** [comment]
Subido a PRE.

**Comment by dgarciageo** [comment]
Buenas Jaime, los códigos de barras resultan en un código alfanumérico de 23 caracteres. ¿Podéis ampliar por favor el campo de 20 a 23 caracteres? Muchas gracias

**Comment by JMunoz17** [comment]
Al final lo hice con longitud 30 caracteres así que no hace falta modificarlo.

**Comment by JMunoz17** [comment]
Subido a PROD.
