### ISSUE TITLE
Error Carga F1 - ES0031408054018001JR

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#479]
* Fichero: NI\F1\WAIT\MMONICA\Fichero 20190212-Endesa (16).xml
* El error que nos da es: Error XML, no se ha encontrado contrato ni por CUPS NI POR ACCESO NI POR MEDIDA

**Comment by dgarciageo** [comment]
Nos acaban de comunicar hoy que este F1 se va a re facturar por un problema en su emisión.  Dejamos la incidencia en OnHold

**Comment by dgarciageo** [comment]
Nos han mandado de nuevo el F1 pero nos sigue saliendo el mismo error:

-----------------------------------Correo de Mónica:--------------------------
Os acordáis de esto? Os dije que esperarais porque nos había dicho la distribuidora que nos iba a re-públicar
Pero al final sigo teniendo el mismo problema y que no encuentra contrato ni por CUPS ni por medida. Es más cuando intento cargar el F5D me sale también el mismo error: El CUPS ES0031408054018001JR0F no tiene contrato asociado o está fuera de fecha 27/11/18.
Ahora ya tengo todos los F1 siguientes pendientes de cargar porque el primero no carga.
Os adjunto los F1 que tengo pendientes y el F5D a ver si me podéis echar una mano

**Comment by PKFEric** [comment]
YA esta solucionado esta incidencia y generada la factura de compra y de venta.
