### ISSUE TITLE
Tarifa de acceso en contrato pdf

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#48]
Al imprimir el contrato en pdf no aparece la tarifa de acceso en los contratos migrados desde NAV, si en los nuevos

**Comment by PKFEric** [comment]
ESTO QUEDA SOLUCIONADO, HE SINCRONIZADO LAS 6x PARA QUE SALGAN PARA LOS CLIENTES CON ESA TARIFA

**Comment by bpesquero** [comment]
Probado y ok
