### ISSUE TITLE
El Nro de Fra. de acceso sólo se rellena en medidas con tipo magnitud EE

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#486]
- Al cargar un P1D sólo se rellena la el nº de fra de acceso en las medidas con tipo magnitud 'EE'
- Necesitamos que se rellene en todas las medidas asociadas a la factura y no sólo las 'EE' por el tema del autoconsumo (magnitud ES)
- Pasar un proceso sobre los registros de la tabla Hour measure y Hour measure line para rellenar el número de fra de acceso en aquellos registros de magnitud <>'EE' que hayan pasado por algún ciclo de facturación.

**Comment by fmsanudo** [comment]
Donde no se rellena la factura de acceso es en los ficheros P1D de magnitud distinta de 'EE'
Véase la consulta con los datos desde el 2019-01-01:
Contract No_	DataSource	count
COM/00906	3	4488
COM/00606	3	14347
COM/00732	3	14611
COM/00616	3	14611
COM/00618	3	14467
COM/00212	3	4672
COM/00583	3	14755
COM/00791	3	14731
COM/00888	3	14421
COM/00199	3	14611
COM/00661	3	4669
COM/00214	3	4768

**Comment by fmsanudo** [comment]
SELECT [Contract No_], DataSource, count(1)
FROM [GEOATLANTER$Hour Measure Line] Lin
WHERE Lin.Date >= cast('2019-01-01' as date)
and [CCH Access Invoice No_] = ''
GROUP BY [Contract No_], DataSource

**Comment by PKFEric** [comment]
Ya esta solucionado, falta pasar un proceso para arrelgar las medidas ya importadas, hemos importado esta mañana un P1D y ha funcionado correctamente.
