### ISSUE TITLE
Aplicación del Perfil usuario en Contrato HECEN/03007

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#488]
Para las medidas de julio de 2018 este punto tiene un consumo calculado de 0 pero sí que tiene pérdidas con valor.
Al pedir el Perfil Usuario éste no se ejecuta, cuando debía haber tenido en cuenta las pérdidas.

Se modificó el cierre en HECEN PRUEBAS asignándole una energía de 10000 y sí que perfila incluyendo las pérdidas.

¿Cuál es la comprobación que se realiza para determinar si un punto debe perfilarse? ¿Sólo considera que el Consumo Calculado sea distinto de cero? Tendríamos también que considerar las pérdidas

**Comment by JMunoz17** [comment]
Hemos detectado la incidencia y queda pendiente de ser realizada.
Hay que modificar el proceso de generación del perfil de usuario para que este se genere si la suma del consumo calculado y las perdidas es mayor que 0. Actualmente solo se comprobaba que el consumo calculado fuese mayor que 0.

**Comment by JMunoz17** [comment]
Subido a PRE.

**Comment by fmsanudo** [comment]
Correcto. Pruebas realizadas

**Comment by JMunoz17** [comment]
Subido a PROD.
