### ISSUE TITLE
Campo toll en Header a 0

### ISSUE THREAD

**Issue by fmsanudo** [PKFEric/webProxima#490]
Hemos detectado que en las cargas de las medidas de Oracle el toll se rellena con 0 en la tabla Cabecera.
Debería rellenarse el id de la tarifa correspondiente

**Comment by JMunoz17** [comment]
Detectada la incidencia, queda pendiente de ser solucionada.
Hay que revisar el proceso de carga de medidas de Oracle para que rellene el campo "Toll" en la cabecera y el campo "Coef. Perdidas" en las líneas.

**Comment by JMunoz17** [comment]
Subido a PRE.

Para rellenar en todas las medidas existentes estos dos campos tenéis el siguiente proceso:
![image](https://user-images.githubusercontent.com/26869276/54595504-09388f80-4a33-11e9-8333-0e4b197bee52.png)

**Comment by fmsanudo** [comment]
Ok. El proceso es lento, pero funciona correctamente.

**Comment by JMunoz17** [comment]
Subido a producción.
