### ISSUE TITLE
Revisar letras que identifican a un NIE en NAV

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#491]
Buenas Erick,

Cuando nos llega un NIE con letra “Y“ Navision lo identifica como NIF cuando debería ser NIE. Según la wiki los NIW pueden empezar por las letras X, Y o Z. Tenemos que revisar las letras que NAV identifica como NIE cuando nos llega un nuevo cliente.

**Comment by PKFEric** [comment]
Se ha modificado para que si el NIF empieza por XYZ se considere NIE

**Comment by PKFEric** [comment]
Subido a pre y pro

**Comment by dgarciageo** [comment]
El COM/01358  el cliente  tiene  NIE y no se ha marcado en la ficha OCSUM del contrato NAV de forma automática el tipo identificador NE (NIE), sino que se ha puesto NI.
 
•	COM/01358   X9999999H

![image](https://user-images.githubusercontent.com/47117960/55961533-5f35d700-5c6f-11e9-898c-ee3d27f69870.png)


 
Ya lo he modificado yo en el xml pero en la ficha lo dejo sin tocar.
 
Gracias,

**Comment by dgarciageo** [comment]
Hemos dado de alta en PRE el siguiente cliente con NIE X2057894S

![image](https://user-images.githubusercontent.com/47117960/56606680-16830400-6607-11e9-9fa8-35889cfc3f76.png)

Con el siguiente contrato 
![image](https://user-images.githubusercontent.com/47117960/56606792-4cc08380-6607-11e9-885e-3226f455ea2b.png)

Peor en la pestaña ocsum sigue apareciendo NI en lugar de NE

![image](https://user-images.githubusercontent.com/47117960/56606833-619d1700-6607-11e9-93e5-66c94c4a5004.png)
