### ISSUE TITLE
Pdf facturas representación

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#494]
Hemos detectado que algunas facturas de representación de las realizadas ayer (parecen coincidir con las que no tienen retrobución y por tanto tienen pocas líneas) el pdf sale mal.  No sale el logo, y sale una especie de barra de desplazamiento a la derecha

Ejemplos: GIRAS/20190003, ENSOL/20190003

**Comment by jorgereal** [comment]
Efectivamente el problema era debido a que esas facturas tenían menos líneas.
Para que se imprima correctamente debe tener un mínimo de 4 líneas. Hemos modificado el proceso para que en la impresión se añadan líneas en blanco si no se llega a 4 filas.

Se ha reimpreso la factura ENSOL_2019003 y ya se visualiza correctamente.
La de GIRAS/20190003 se veía bien.

Si encontráis más facturas con este problema en el pdf pasadnos un listado y las regeneramos.

Las nuevos pdfs se generarán bien.
