### ISSUE TITLE
Gestión de cobros HECEN- resolución de contratos

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#496]
No sé si me estoy volviendo loca con este tema...

Ahora mismo si me voy a la pantalla de resumen de tareas de gestión de cobros me aparecen 56 facturas para enviar el email de resolución.
Cuando accedo a esas 56 y le doy a marcar hay dos que se quedan fuera. Hay que tener en cuenta que los 15 días son hábiles.
Yo tenía en la cabeza que en realidad hay muchas más para cortar. Así que voy a gestión de cobros,  me desfiltro todo y filtro por : fecha de corte < 06/04/19 (para tener 15 días) y fecha de recepción de reclamación formal de deuda <>"", acuerdo de pago "NO". De esta forma me salen 197 registros, no 56.
Con estos 197 registros seleccionados le doy a marcar envío resolución de contrato y sólo me marca 53.

¿Me podéis indicar que criterios se siguen para marcar?O me estoy liando o no me cuadra

**Comment by JMunoz17** [comment]
En primer lugar, enumero los criterios que se siguen a la hora de marcar los movimientos como pendientes de enviar el mail de resolución de contrato (Botón en la pantalla principal de gestión de cobros):
- Filtros que estén aplicados en ese momento en la pantalla.
- Situación de recobro diferente a: No gestionar, gestionado y gestión externa.
- Acuerdo de pago a NO.
- Fecha envío mail reclamación formal de deuda rellena.
- Fecha prevista de corte rellena.
- Fecha envío mail resolución contrato vacía.
A partir de aquí por cada movimiento de cliente que encontramos hacemos lo siguiente:
- Buscamos la factura a partir del número de documento.
- Buscamos el contrato a partir de la factura.
- Buscamos el cliente titular a partir del contrato.
    - Si el cliente es persona física y la tarifa es igual a 2.0A, 2.0DHA o 2.0DHS entonces:
        - Si la fecha actual es mayor o igual que la fecha prevista de corte menos 15 días hábiles lo marcamos.
    - En caso contrario:
        - Si la fecha actual es mayor o igual que la fecha prevista de corte lo marcamos.

Los problemas que tenemos son los siguientes:
- En la pantalla de resumen aparecen 56 movimientos y al darle a marcar solo se marcan 54. Esto es incorrecto, deberían aparecer los 54 que se marcan. El motivo por el que aparecen 2 más es porque el otro día cuando hice la modificación usé el cliente que tenemos en los movimientos de cliente en lugar del cliente titular a la hora de consultar si es persona física o jurídica. Los dos movimientos que no nos cuadran corresponden al contrato HECEN/02627, que tiene el cliente titular como persona jurídica y el cliente pagador como persona física. He modificado el código y lo he subido a PRE y PROD.

- Se marcan 54 movimientos de clientes después de los filtros aplicados por la pantalla de resumen y 53 después de los filtros aplicados por Belén. El motivo es que Belén ha filtrado por "Fecha de recepción de reclamación formal de deuda" <>"" y nosotros no usamos ese campo sino el de "Fecha prevista de corte". Hay un movimiento (5506898) que tiene la "Fecha prevista de corte" rellena pero no la "Fecha de recepción de reclamación formal de deuda". Entiendo que esto es porque habéis rellenado la "Fecha prevista de corte" a mano (no se me ocurre ningún otro motivo y he visto que es el único caso que tenemos). Esta fecha debe rellenarse a partir de rellenar otros campos ("Fecha de recepción de reclamación formal de deuda" o "Fecha de 2º devolución de reclamación formal de deuda"). 

 - La diferencia entre los 197 que aparecen después de aplicar vuestros filtros a los 54 que deberían de aparecer es porque faltan filtros por aplicar, principalmente el filtro de situación de recobro.

Ya me decís si os cuadra todo o hay algo que os chirría.

**Comment by bpesquero** [comment]
ok. Ahora me cuadra.
