### ISSUE TITLE
La dirección postal en las facturas de HECEN salen sin número

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#497]
Las factura de HECEN salen sin el número de la calle ni el piso en la dirección postal pese a que en la fiche cliente si aparece dicha información. Las facturas de GEO salen bien

**Comment by jorgereal** [comment]
El problema está en la configuración de la información de empresa.
La dirección que se muestra en las facturas se corresponde con el campo: 'Envío a-Dirección' de la pestaña 'Envíos' de la ficha de información de empresa y no al campo 'Dirección' de la pestaña 'General' de esa misma ficha.

Bastaría con añadir el número de calle y piso correspondientes a esa dirección.

**Comment by bpesquero** [comment]
jorge, creo que hay una confusión, no estamos hablando de la dirección de la empresa, si no de la dirección del cliente

![image](https://user-images.githubusercontent.com/20299071/55893087-e0319780-5bb7-11e9-826d-d8a7591d1bb9.png)

**Comment by bpesquero** [comment]
En Geo, siguiendo con el ejemplo de las facturas mostradas antes está de la misma manera

![image](https://user-images.githubusercontent.com/20299071/55893158-06573780-5bb8-11e9-9d52-69f3b6165f1b.png)

**Comment by dgarciageo** [comment]
Factura impresa el 04/05/2019

Hemos eliminado nombre por LOPD. La dirección sale incompleta

![image](https://user-images.githubusercontent.com/47117960/57296283-e9395a00-70cc-11e9-86e1-e78d66034a04.png)

**Comment by jorgereal** [comment]
Faltaba hacer el cambio en el formato de facturas de enganche. Subido a PRE y PRO.

**Comment by dgarciageo** [comment]
Solucionado
