### ISSUE TITLE
Cambiar informe de tiempos medios TM_CODAGE

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#499]
Tenemos que incluir un pequeño cambio en el informe de tiempos medios de switching TM_CODAGE.
El tiempo medio de activación se está computando ahora mismo como la diferencia entre la fecha de activación (paso 05) –fecha de solicitud (paso 01).
Hay que modificarlo y que pase a ser: a diferencia entre la fecha de activación (paso 05) –fecha  de inicio del contrato.

En los informes relativos al SI_CODAGE que informan de los cambios, se manterndrá el criterio que tenemos actualmente, no habrá que realizar ningún cambio

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
