### ISSUE TITLE
Tarifa MILENIAL

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#500]
Cambios identificados a realizar para poner en marcha la tarifa MILENIAL en HECEN

Para el lunes 1/04/2019

1.-Cambios de imagen en la web
1.1.- En la home añadir este texto encima de más de cien años:

Toma la puerta de entrada y participa en la nueva energía que ya está cambiando el mundo.
                                              ¡PÁSATE A LA TARIFA MILENIAL!
Con nuestra tarifa MILENIAL tendrás el mejor precio fijo, con las ventajas de tu tarifa actual, sin cambiar tus hábitos de consumo.
Si ya eres cliente, accede a tu área privada y selecciona un cambio de tarifa, si no lo eres, apúntate aquí
                                              Quiero ser MILENIAL

Al pinchar en quiero ser MILENIAL se abre un pop up con el siguiente texto:

"Toma la puerta de entrada y participa en la nueva energía que ya está cambiando el mundo.
Con nuestra tarifa MILENIAL tendrás un precio fijo trimestral, pero en tu factura te mostraremos el consumo dividido en dos tramos: valle (barato) y punta (caro). En cuanto te acostumbres a ella te darás cuenta de por qué recomendamos a todos nuestros clientes pasarse a la discriminación horaria, que tiene dos precios distintos en lugar de uno. Si te animas, podrás cambiarte a ella en el momento y sin coste.
Los paneles solares y el coche eléctrico se irán integrando en tu vida con total normalidad. Nosotros te acompañaremos en el proceso y nos encargaremos de facilitártelo.
El cambio a la tarifa MILENIAL no tiene condiciones específicas y es válido tanto para clientes existentes como para nuevos. Supone un cambio contractual al peaje de discriminación horaria cuyo coste asumimos íntegramente. Como siempre, sin permanencias ni prepagos y con energía renovable certificada."

Al pinchar en esta ventana emergente le conduce al usuario a la página de alta de usuario.

** de la primera parte, intentaremos enviaros mañana una imagen para no poner el texto a pelo, y poder incluir algún dibujito.

1.2.- En la página de tarifas para tu hogar:
         a) donde pone TARIFA NORMAL poner TARIFA MILENIAL
         b) donde pone tarifa de acceso 20A, tarifa de acceso 20DHA y tarifa de acceso 20DHS, 
             poner tarifa en 1 periodo, tarifa en 2 periodos, tarifa en 3 periodos.

2.- Relacionar el contrato de alta en la web con el contrato NAV. Hay que tener en cuenta que la tarifa MILENIAL tiene en NAV una 20DHA y por tanto ya no se puede asignar el tipo de contrato en NAV buscando únicamente por tarifa de acceso y web=True

3.- En la pantalla de alta de contrato correspondiente a datos de suministro cambiar peaje de acceso a contratar por tarifa a contratar y añadir en el desplegable tarifa MILENIAL

4.- Quitar campaña de 1 euros de descuento
4.1- Eliminar imagen de la página de hogar  y de negocio
4.2. Eliminar imagen de la página de yasoycliente
4.3 Cambiar el código para que antes de añadir la línea de descuento verifique además de que factura electrónica=true, que el min de las fechas de inicio de contrato del CUPS es <=31/03/2019

5.- En la parte privada, en cambio de tarifa
5.1 Donde pone peaje de acceso actual y nuevo peaje de acceso poner tarifa actual y nueva tarifa
5.2 En el desplegable de nueva tarifa añadir tarifa MILENIAL

Para el lunes 8/04/2019

1.- Bloquear F1 de derechos de enganche para no realizar la venta. Quedo pendiente de revisar los códigos que se corresponde con los derechos de cambio de tarifa, para tener claro cómo realizamos el bloqueo y controlar que sólo se bloqueen los cambios correspondientes a este tipo de cambio.

Para cuando se pueda

1.- Cuando el cliente, desde el área privada realiza un cambio de tarifa, generar el fichero M automáticamente. Mantener el envío de correo.

**Comment by JMunoz17** [comment]
Hemos subido a PRE y PROD lo relativo al día 01/04/2019.
Debéis marcar en NAV la tarifa 2.0DHA correspondiente, marcando el campo "Supply No" (Tarifa suministro) con el valor MILENIAL.
En la web hay que sincronizar las tarifas con NAV desde el panel de administración.

**Comment by bpesquero** [comment]
En la web:

El texto "Hidroeléctrica El Carmen Energía" va debajo de la imagen de MILENIAL. Va junto con el texto de "Cien Años a tu Lado"

La imagen de MILENIAL no está centrada

Al pinchar en la imagen la ventana emergente es ilegible.

**Comment by bpesquero** [comment]
¿De qué forma marco en NAV cual es el tipo de contrato asociado a esta tarifa web? Antes lo hacía marcando el campo web. Pero si lo hago tendríamos dos campos con la marca web y tarifa 20DH

**Comment by bpesquero** [comment]
No puedo entrar a la zona de administrador de la web para sincronizar las tarifas

**Comment by bpesquero** [comment]
Hemos realizado las pruebas y hemos detectado las siguientes cosas

1,. Al hacer un contrato nuevo (como nuevo usuario y desde un usuario existente), poniendo tarifa actual 20A y tarifa a contratar milenial, se genera el contrato sin el check de C2, así que se tramita como un C1. Hemos verificado que al  parecer es un error ya existente, ya que si hacemos lo mismo pero escogiendo la tarifa a contratar la 20DH tampoco lo hace. Si lo que hacemos es indicar otra potencia, entonces sí se marca como C2
2.- En relación al texto que aparece cuando se realiza desde la parte privada un cambio de tarifa, que pone : "le informamos que cualquier modificación técnica...". Habría que añadir al final "En el caso en que pases a la tarifa MILENIAL nosotros asumiremos el coste asociado al mencionado cambio."
3.- En relación a este mensaje, hemos detectado que sale correctamente cuando se solicita un cambio de tarifa, pero no en el alta de un nuevo contrato (como nuevo usuario o desde un usuario existente), que no muestra el mencionado mensaje.

**Comment by jlagunapkf** [comment]
Tanto en el alta de usuario como en el alta de un nuevo contrato. ¿Dónde coloco la frase?

**Comment by bpesquero** [comment]
Yo creo que debajo del código promocional para que sea sencillo

**Comment by jlagunapkf** [comment]
El texto está modificado en el cambio de tarifa.

Este mismo texto lo he incluido en la parte inferior de la selección de la tarifa tanto en un nuevo contrato desde la parte privada, como desde la parte pública.

También se marca el check de generar C2 cuando se selecciona una tarifa diferente.

**Comment by bpesquero** [comment]
En relación con los F1 a bloquear para no repercutir al cliente los derechos de enganche asociados al cambio de tarifa, es necesario bloquear  las líneas que tengan tipo de concepto=04
Hay que tener en cuenta que solamente habría que bloquear el primer "derecho de enganche" que aparezca una vez se realiza el cambio a tarifa milenial.

**Comment by PKFEric** [comment]
Si el contrato tiene Tarifa Milenial, en la venta no se facturara el concepto de Energia.

**Comment by bpesquero** [comment]
Eric, no entiendo bien la frase que has puesto. ¿Qué es concepto de Energía?
