### ISSUE TITLE
error facturación reganecu C4 - 201807

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#502]
Al facturar el REGANECU de la C4 de 201807 se genera una factura de venta y una de compra que coinciden exactamente con los valores del reganecu sin restar las correspodientes facturas del periodo 201807 (C1-C2-C3)
La excepción que encontramos en este caso es que no existe factura de la C3, ya que la suma del reganecu - las facturas de C1 y C2 es 0.
Podéis ver las facturas generadas de la C4 en prefacturas de compra y venta respectivamente. 
Os adjunto una tabla con los cálculos por si puede ayudar.

Suma de Importe reganecu |   |   | Factura calculada   check | Factura NAV
-- | -- | -- | -- | --
Etiquetas   de fila | Compra | Venta | Compra | Venta | Compra | Venta
C1 | -2332,85 | 193,82 | -2332,85 | 193,82 | 2.332,85 | 193,82
C2 | -1618,4 | 886,93 | 714,45 | 693,11 | 714,45 | 693,11
C3 | -1618,4 | 886,93 | 0,00 | 0,00 | 0 | 0
C4 | -1618,39 | 886,93 | 0,01 | 0,00 | -1618,39 | 886,93

Os  envío excel por email

**Comment by bpesquero** [comment]
![image](https://user-images.githubusercontent.com/20299071/55475437-40529780-5614-11e9-9332-a099797916ce.png)

**Comment by dgarciageo** [comment]
Sale mal de nuevo:

Factura de venta que no debería salir
![image](https://user-images.githubusercontent.com/47117960/58649678-06003080-830d-11e9-925a-b2bc7b7a198d.png)


Factura de compra que si esta OK

![image](https://user-images.githubusercontent.com/47117960/58649905-a9514580-830d-11e9-8637-a69729432b79.png)

**Comment by dgarciageo** [comment]
Hemos comprobado la liquidación C4 y sigue arrastrándose el error. La factura de compra para el C4 sale bien, pero sale una factura de venta de 1656€ cuando no debería salir ninguna. Mismo error que pasó con el C3.

![image](https://user-images.githubusercontent.com/47117960/58654125-83c93980-8317-11e9-908e-58f729c6e978.png)

**Comment by jorgereal** [comment]
El error se debía a que para la liquidación C3 no se realizó factura dado que el importe era 0, por lo tanto, aunque las líneas de Reganecu se marcaron como facturadas, no se rellenó ningún número de documento en éstas.
Al facturar la liquidación C4 se busca la diferencia respecto a la C3, pero se filtra para que los campos de "No. factura" o "No. abono" estén rellenos.  Al no haber registros de la C3 con estos campos rellenos no se realizaba la diferencia y se facturaba el importe completo que marcaba esa liquidación.

Para solucionarlo, en el caso de que la diferencia entre dos liquidaciones sea 0, rellenamos el no. documento (factura o abono según corresponda) con el no. documento generado en la liquidación anterior concatenando '_V1'. De esta forma estos registros entraran en los filtros de la siguiente liquidación.

Se ha realizado tanto para la facturación de la compra como de la venta.

Se ha replicado el ejemplo de la liquidación C4 para el periodo 010918..300918, no generándose factura de venta pero marcando los registros.

Si lo veis correcto lo subimos a PROD.

**Comment by jorgereal** [comment]
Subido a PROD.

**Comment by dgarciageo** [comment]
Aparte de informar los campos de .... cuando no se genera un FC/FV por ser de importe 0
* Nº preasignado fact. venta / Nº preasignado fact. venta
* Nº preasignado abono venta / Nº preasignado abono compra

Hay que informar con algún valor los campos de... porque si no da error "tiene facturas pendientes sin registrar"

* Nº de factura de venta reg / Nº factura compra reg
* Nº abono venta reg/ Nº abono compra reg

![image](https://user-images.githubusercontent.com/47117960/59625777-72b36180-913a-11e9-8127-3d1afb216113.png)
