### ISSUE TITLE
Modificación del mail de "Ya te estamos suminsitrando energía" para A3

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#503]
Cuando se trate de un alta nueva en mercado, es decir, cuando se tramite con A2 habría que eliminar del mail la frase

"Recibirás una última factura hasta dicha fecha de tu suministrador anterior. A partir de entonces, la facturación pasará a ser de nuestra responsabilidad."
 
que si debe aparecer en el caso de cambio de comercializador (C1 y C2)

**Comment by bpesquero** [comment]
Tanto en Geo como en HECEN

**Comment by jorgereal** [comment]
Se ha creado una plantilla de mail nueva, tanto para GEO como para HECEN sin la frase indicada para los mails de activación al tramitar los A3.

Subido a PRE y PRO.

**Comment by dgarciageo** [comment]
Para HECEN funciona correctamente, falta probar para GEO pero damos por resuelta la incidencia
