### ISSUE TITLE
Problema en generación fichero A3 de alta HECEN

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#505]
Al generar el A3 para un alta nueva en HECEN no se esta generando correctamente el fichero .xml de ocsum. No se está incluyendo la información contenida en el campo "Dirección URL" de la pestaña ocsum de la ficha contrato (Sombreado en amarillo)

 
 
![image](https://user-images.githubusercontent.com/47117960/55572044-0e6e2d80-5707-11e9-901b-7d3c21ff3ab0.png)

Por el momento lo estamos haciendo a mano incluyendo en el fichero XML la siguiente entrada
![image](https://user-images.githubusercontent.com/47117960/55572116-3362a080-5707-11e9-9fd3-1040eb26a1d3.png)

**Comment by jorgereal** [comment]
El problema se debe al campo TipoDocAportado, este tiene que estar relleno para que se exporte en el xml la entrada de 'RegistroDocumento'.

El xml se genera con los datos del histórico de acciones y, para el contrato 'HECEN/09346', en la entrada '8390' no estaba relleno.

A pesar de que en el contrato ya está informado el tipo de documento aportado, en el momento en el que se envió el A3 a acciones no lo estaría, de ahí que el xml no se exportara completo.
