### ISSUE TITLE
Generación automática de ficheros M1

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#506]
Generar ficheros M1 de switching de forma automática cuando el cliente selecciona un cambio de tarifa desde la web

**Comment by jorgereal** [comment]
Se ha añadido la funcionalidad de generación automática de ficheros M1 en la web de a tu lado.

Subida a producción la parte de NAV y WEB.

**Comment by bpesquero** [comment]
Hemos hecho la prueba desde la web, pero en NAV no vemos la opción de generar M masivo (por seguir con la misma idea de los C1 y C2), ni nada parecido. Ni en el contrato se ha generado el fichero M.
Hemos probado con el contrato HECEN/05844
Gracias

**Comment by dgarciageo** [comment]
Acaba de entrar un cliente que se quiere cambiar de tarifa pero ha dado una excepción al generar el M1

-------------------------------------------------------------------------------------------
Excepcion controlada web: ERROR: Generar M1 en Parte Privada contratoHECEN/03097 12/04/2019 9:16:38 </br>

-------------------------------------------------------------------------------------------
Excepcion controlada web: ERROR: Al generar fichero M1:HECEN/03097, EXCEPCION->Indicador Tipo Dirección Cliente sólo acepta valores "F" y "S" STACK->   en System.Web.Services.Protocols.SoapHttpClientProtocol.ReadResponse(SoapClientMessage message, WebResponse response, Stream responseStream, Boolean asyncCall)
   en System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String methodName, Object[] parameters)
   en webATuLado.WS.CodeWeb_Binding.GenerateM1_01(String pContractCode, String pSupplyNo, Decimal pNewPower1, Decimal pNewPower2, Decimal pNewPower3, Decimal pNewPower4, Decimal pNewPower5, Decimal pNewPower6)
   en webATuLado.clsNavision.generaM1(String tarifa, Decimal[] potencias, String codigoContrato) 12/04/2019 9:16:38 </br>
