### ISSUE TITLE
Error impresión de facturas

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#509]
Para imprimir en roles las facturas de HECEN y tratamos de filtrar por el campo 
"código tipo de contrato" y sale el siguiente error

![image](https://user-images.githubusercontent.com/20299071/55726683-aeca9780-5a10-11e9-8910-2a7d80a2bea1.png)

**Comment by jorgereal** [comment]
No existía ninguna page para visualizar la lista de "códigos tipo de contrato" desde el cliente de roles, tan solo el formulario para classic.

Se ha creado la page y se ha subido a PRE y PRO.
