### ISSUE TITLE
Errata en cuentamelo todo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#51]
En vez de adicionalmente pone Adicionlmente, en el apartado de cuentamelo todo tanto en hogar como en empresa.

**Comment by PKFEric** [comment]
MODIFICADO PROBAR ->WEB

**Comment by bpesquero** [comment]
Creo que no has subido las modificaciones, porque lo veo igual

**Comment by PKFEric** [comment]
SUBIDO

**Comment by bpesquero** [comment]
probad y ok
