### ISSUE TITLE
Cambiar condiciones generales del contrato web atulado (MUY IMP. 30/04/19)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#510]
Tenemos que cambiar las condiciones generales del contrato web atulado a fecha 01/05/19. ES MUY IMPORTANTE QUE SEA EN ESA FECHA CUANDO SE CAMBIEN LAS CONDICIONES. No antes ni después. Se trata de actualizar la plantilla. El word se enviará por email.

**Comment by jlagunapkf** [comment]
Subido el nuevo contrato a PRO y a PRE.
