### ISSUE TITLE
Error Descarga ESIOS&OMIE desde ZETA

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#511]
No se pueden realizar descargas esios OMIE desde el servidor de terminal server desde que se reinstaló la maquina.

![image](https://user-images.githubusercontent.com/47117960/55897545-07409700-5bc1-11e9-8322-3bbd4346e729.png)

**Comment by dgarciageo** [comment]
Ahora le sale a fernando la siguiente excepción

![image](https://user-images.githubusercontent.com/47117960/56601153-bb4b1480-65fa-11e9-91ff-3c1909e9c84e.png)

**Comment by fmsanudo** [comment]
Solucionado. Cierro
