### ISSUE TITLE
Desde la web se esta trayendo el CUPS de 22 caracteres

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#515]
Se tiene que registrar el CUPS de 20 caracteres tal y como se hace en próxima.
ahora cada vez que se da de alta un nuevo cliente Ainhoa tiene que cambiar a mano el CUPS en NAV.

**Comment by dgarciageo** [comment]
Hemos dado de alta en PRE un nuevo contrato con un CUPS de 22 caracteres:

**ES0031101370751001RW0F**

 y en NAV se ha propagado el CUPS con 22 caracteres

![image](https://user-images.githubusercontent.com/47117960/56606905-914c1f00-6607-11e9-9434-fd2bc6d8a226.png)

**Comment by PKFEric** [comment]
No estaba subido a PRE, ahora ya si que lo esta y lo he probado creandome el contrato
