### ISSUE TITLE
WEB - Informar las Condiciones Económicas de la plantilla contrato en la creación y no en la activación

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#516]
Las condiciones económicas MILENIAL no salen bien informadas en la plantilla del contrato

![image](https://user-images.githubusercontent.com/47117960/56570575-81a6e900-65bb-11e9-96ff-fe4fa8cfafda.png)

**Comment by PKFEric** [comment]
No aparece la informacion por que no tiene generados los precios aun,

**Comment by dgarciageo** [comment]
El contrato sólo coge precios cuando el alta se hace efectiva con el distribuidor (Importación del A3)
Damos por cerrada la incidencia.

**Comment by dgarciageo** [comment]
Queremos revisar el momento cuando se rellenan los precios en las condiciones económicas de un contrato de reciente creación- 2 opciones:

a) Bien revisar la fuente de información de donde se leen las condiciones económicas del contrato. 
    El cliente, al descargarse su contrato desde la web, la plantilla se rellena con la información disponible en la tabla contrato, la cual se rellena una vez que llega el C2_05. Bien, pues la idea sería que la plantilla de contrato leyese de la tabla tarifas electricas donde la información si esta disponible cuando se crea el contrato.

![image](https://user-images.githubusercontent.com/47117960/56886971-8c0c2b80-6a70-11e9-9bbb-3fad066a1fd7.png)


b) Modificar momento de generación de precios del contrato. i.e. Los precios se generan en la creación del contrato y con el paso C1/C2 _05 se actualiza la fecha de inicio del contrato

**Comment by dgarciageo** [comment]
La tarifa milenial va a desaparecer por lo que cerramos la incidencia
