### ISSUE TITLE
Mandar copia email de contacto al cliente (Web Proxima y Atulado)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#520]
Mandar una copia del email del formulario de contacto al cliente

**Comment by dgarciageo** [comment]
Cuando se produce un error durante el proceso de alta no queda claro si el proceso de alta se ha concluido correctamente ya que después del error se muestra el siguiente mensaje
![image](https://user-images.githubusercontent.com/47117960/56672943-99639780-66b7-11e9-8350-6c86268f675e.png)

Mandar un correo al cliente con el mismo mensaje de error que se muestra en la web para que se ponga en contacto con nosotros

![image](https://user-images.githubusercontent.com/47117960/56672760-4558b300-66b7-11e9-8ba1-98e82ac91557.png)

**Comment by dgarciageo** [comment]
El asunto del email que se envía desde clientes@atuladoenergia.com hace referencia a "Proxima energia".

![image](https://user-images.githubusercontent.com/47117960/59293698-0a6b0880-8c80-11e9-8438-b146312d9661.png)

**Comment by PKFEric** [comment]
He modificado todos los asuntos de todos los mails para que siempre ponga A tu lado energía.
