### ISSUE TITLE
Check Generar C2 para tarifa MILENIAL

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#521]
No entendemos por qué pero para las altas con cambios C2 no se marca correctamente el check de generar C2 de la ficha contrato aunque luego si se genera el fichero XML cuando el usuario lo solicita

![image](https://user-images.githubusercontent.com/47117960/57368532-9c688880-718b-11e9-8b17-fa556b4f3422.png)

![image](https://user-images.githubusercontent.com/47117960/57368568-b5713980-718b-11e9-9e79-6ae91da7660f.png)

**Comment by PKFEric** [comment]
Cuando llega un contrato desde la web recien dado de alta si hay cambio para generar C2 se marca el Check, posteriomente Ainhoa lanza el proceso de generar C2 y se desmarca este check.

Si despues de que Ainhoa pase el proceso llega otro contrato. Este ultimo tendra marcado el check minetras que el anterior ya no.

**Comment by dgarciageo** [comment]
Cerramos esta incidencia por estar relacionado con la #523 en fase de pruebas

**Comment by dgarciageo** [comment]
Entendido entonces. No obstante me comenta Ainhoa que hay algunos contratos para los que ya se generó el C2 y aun tienen el check marcado,

eg. HECEN/09375, HECEN/09403, HECEN/09371
