### ISSUE TITLE
Error C2 "atulado" tras modificar contrato a mano

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#523]
Los C2 que se generan de forma automática desde la web, por cambios técnicos, y que luego están siendo rechazados por la distribuidora (en este caso porque el titular no coincide), al intentar volver a generar un nuevo C2 pero esta vez, con los campos de la ficha de contrato cambiados a mano, ya que ahora ya no sólo son cambios técnicos (N) sino también administrativos (S) por tanto ambos (A),  con cambio de titularidad con subrogación (S), cuando le doy a volver a generar tras modificar dichos campos en la ficha del contrato de NAV,  el xml sale mal, es decir, no se modifican .

 **Ejemplo Contrato NAV (ficha Ocsum) cambiada a mano HECEN/09440**

![image](https://user-images.githubusercontent.com/47117960/56794238-fc674280-680d-11e9-96e5-a27dd6b3e725.png)

![image](https://user-images.githubusercontent.com/47117960/56796098-21f64b00-6812-11e9-9e8a-5c39e9fabc05.png)

**Comment by jorgereal** [comment]
El problema se debía al flag "Generar C2" que se activa desde la Web. Este hace que el xml del C2_01 se genere con unos valores por defecto en lugar de tomar los del contrato.
Hemos desmarcado el check  del contrato HECEN/09440 y hemos generado la entrada en el histórico de acciones, esta vez sí con los datos del contrato.

También hemos modificado el proceso de generación del C2 para que se desmarque este flag, por la tanto un contrato dado de alta desde la web tomara los valores por defecto en la primera generación del C2 y los valores del contrato en las sucesivas ejecuciones.

**Comment by dgarciageo** [comment]
Solucionado
