### ISSUE TITLE
Modificar el control "No puede hacerse un cálculo de fechas en base a una fecha indefinida"

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#525]
Estos contratos tienen el siguiente problema:

COM/00331 | ES0021000005262277SN
COM/00418 | ES0021000009219237VY
COM/00689 | ES0021000004058596YJ
COM/00727 | ES0021000002539712RA

**No puede hacerse un  cálculo de fechas en base a una fecha indefinida.  Fecha: 0D Fórmula: 1D**

Las tres primeras tienen la misma casuistica. No tienen facturación del término de energía pero si tienen cierre con consumo calculado=0. Para solucionarlo rápido quizá vale con borrar el cierre de energía. **Yo creo que cuando hace la validación de que las fechas del cierre coincidan con las del término de energía da error por no tener término de energía. Quizá lo que hay que hacer es realizar el control sólo cuando el consumo calculado del cierre sea mayor a cero**.
El último caso no veo lo que le pasa....

**Comment by dgarciageo** [comment]
Modificar el control de:

**No puede hacerse un cálculo de fechas en base a una fecha indefinida.  Fecha: 0D Fórmula: 1D**

Para que sólo se realice cuando el consumo calculado del cierre sea mayor que cero

**Comment by PKFEric** [comment]
Facturacion de Venta
