### ISSUE TITLE
M1 Administrativos (Tipo S-C) Paso 05 de forma automática

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#528]
Tipos de M1 - Siendo una solicitud tipo S 
![image](https://user-images.githubusercontent.com/47117960/57371320-ba85b700-7192-11e9-82b1-901e8156a899.png)

Tipos de cambio de titular - Y un cambio de titular tipo C
![image](https://user-images.githubusercontent.com/47117960/57379216-bebbcf80-71a6-11e9-8cad-d76018b79584.png)

Cuando se recibe el paso 02 de la distribuidora el contrato pasa a tramitación ATR  y tenemos que activarlo por BBDD ya que no hay un paso 05. 

Cuando nos llega un M1 Tipo S-S, i.e, cambio de titular por subrogación el proceso se completa correctamente. La idea es replicar este mismo comportamiento para los tipo S-C.

**Comment by bpesquero** [comment]
Cuando el tipo de solicitud administrativa contractual es S tiene que funcionar siempre de la misma manera, asimilando el  paso 02 a un 05, independientemente del tipo de solicitud adminitrativa.

Ahora mismo funciona bien cuando el tipo de solicitud administrativa es S o T, pero no cuando es C.

**Comment by JMunoz17** [comment]
No había visto tu comentario que no estaba asignado a la tarea y no me había llegado al correo.
Acabo de modificarlo, subido a PRE.

**Comment by bpesquero** [comment]
Probado y ok

**Comment by JMunoz17** [comment]
Subido a PROD.
