### ISSUE TITLE
Condiciones generales del contrato

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#53]
Tanto desde la pantalla donde confirmas las condiciones de contratacion, como desde la parte privada cuando te descargar el contrato, hay que descargar tanto las condiciones generales como las particulares. Puede ir en un único documento. Primero las condiciones generales y luego las particulares. Las condiciones generales también son parte del contrato.

**Comment by PKFEric** [comment]
Estas son las condiciones que se pueden descargar, pasame porfa las que quieres que ponga.

[condicionesContractuales.pdf](https://github.com/geoatlanter/webProxima/files/383696/condicionesContractuales.pdf)

**Comment by bpesquero** [comment]
Si me voy a la parte privada y me exporto el contrato pdf no me aparecen las condiciones que tu me adjuntas. Se descargan las condiciones particulares. Sería descargar las que tu me adjuntas y las particulares. Todo en un único documento. 

Idem cuando aceptas las condiciones de contratación,

**Comment by bpesquero** [comment]
y también desde Ver detalles del contrato--> descargar contrato

**Comment by PKFEric** [comment]
Ese es el contrato que me enviaste.
[PlantillaContrato.docx](https://github.com/geoatlanter/webProxima/files/383711/PlantillaContrato.docx)

Que ha sido el que he transformado a html para luego convertirlo a PDF.

**Comment by bpesquero** [comment]
Lo que te digo es que hay que mostrar en todos los sitios el archivo que tienes como condiciones contractuales y el de plantilla contrato

**Comment by bpesquero** [comment]
probado y ok
