### ISSUE TITLE
Corregir icono Hecen footer plantilla Factura HECEN

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#531]
Cambiar el logo de Hidroelectrica El Carmen S.L. por Hidroelectrica El Carmen Energia SL
![image](https://user-images.githubusercontent.com/47117960/57390186-0ac53f00-71bc-11e9-8e19-de310ea3d67d.png)

**Comment by PKFEric** [comment]
Ya esta modificado.
