### ISSUE TITLE
"Plantilla factura de derechos de enganche HECEN"

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#535]
Se requiere corregir plantilla usada para la facturación de derechos de enganche de Hecen. Utilizad la de próxima como referencia.

Plantilla usada para **factura de derechos de enganche Proxima**:   **CORRECTO**
 Nº FACTURA: C/20185456

![image](https://user-images.githubusercontent.com/47117960/58628604-717cda80-82da-11e9-926d-69f5a13d1c61.png)

Plantilla usada para **factura de derechos de enganche atulado**:   **INCORRECTO**
Nº FACTURA: H/2019028112

![image](https://user-images.githubusercontent.com/47117960/58552674-4a0f0a80-8213-11e9-9ac6-3bddbad4ddcd.png)

Os dejo los pdf en la siguiente ruta por si necesitáis consultarlos:
\\ni\EsiosPre\#535 - plantilla Errónea

**Comment by JMunoz17** [comment]
Modificado y subido a TEST y PROD.
