### ISSUE TITLE
Link a web de GeoAtlanter

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#54]
El log de GeoAtlanter debe ser en realidad un link a la web de GeoAtlanter

**Comment by PKFEric** [comment]
MODIFICADO PROBAR-> WEB

**Comment by bpesquero** [comment]
Creo que no has subido las modificaciones, porque lo veo igual

**Comment by PKFEric** [comment]
SUBIDO

**Comment by bpesquero** [comment]
probado y ok
