### ISSUE TITLE
WEBS - Revisar emails "Ya tiene una nueva factura ...." - ERROR 404

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#542]
1) Al pinchar sobre las imágenes de los correos se lleva a vínculos antiguos de las webs

proximaenergia/indice
atuladoenergia/indice

----------------------------------------------------
2) Varios ficheros .dat adjuntos en el correo de próxima de "Tienes disponible en nuestro portal una nueva factura.... "que no se usan

![image](https://user-images.githubusercontent.com/47117960/58702084-17951700-83a5-11e9-9bbb-3df9cbecb859.png)

Son estas y otras imágenes

![image](https://user-images.githubusercontent.com/47117960/58702186-588d2b80-83a5-11e9-8439-a7bc96e47a73.png)

![image](https://user-images.githubusercontent.com/47117960/58702195-6347c080-83a5-11e9-9316-4220b94433c2.png)

**Comment by JMunoz17** [comment]
Modificado y subido a TEST y PROD.

Hemos modificado todas las plantillas HTML que utilizamos ahora mismo ya que estaba sucediendo en todas las comunicaciones.
