### ISSUE TITLE
Envío de mail con nueva factura

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#55]
No se envía el mail. Esto ya lo habíamos comentado, pero creo que no tenía una incidencia específica

**Comment by PKFEric** [comment]
SE ENVIA EL MAIL, el problema fue que se envío a las direcciones de correo de Alumitran. 
Hay que tener ojo con esto. Si das de alta a un usuario en la web que ya existe en NAV, el correo electrónico con el que le das de alta no es el correo electrónico de notificaciones. El correo electrónico de Notificaciones es el que aparece en la ficha del cliente. Así que se envió a ese correo, ayer lo cambie y probé con mi correo y me llegó correctamente.

**Comment by bpesquero** [comment]
Al enviar el mail informando de nueva factura, al principio del mail pone "???"

**Comment by PKFEric** [comment]
Ya esta solucionado, probar.

**Comment by bpesquero** [comment]
En algunas facturas, en el mail, no aparece ni el nombre ni el importe de la factura,... Adjunto pantallazo. 
Por otra parte he viso que hay una errata en el texto y pone "cuenta bancaria de que nos comunicaste. ", tiene que ser "cuenta bancaria de que nos comunicaste. "
![pantallazo mail](https://cloud.githubusercontent.com/assets/20299071/17886667/30e5f3cc-6923-11e6-8edb-424022c46669.png)

**Comment by bpesquero** [comment]
Por otra parte, he impreso 5 facturas y un abono al mismo tiempo para un contrato, y sólo ha salido un mail.
