### ISSUE TITLE
WEB - Error Campaña Amigo - No existe código promocional

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#554]
Accediendo desde Nuevo Contrato del área cliente

![image](https://user-images.githubusercontent.com/47117960/58883377-9c9e6a00-86de-11e9-8f5c-8c9800df62c5.png)

No funciona lo del código promocional

![image](https://user-images.githubusercontent.com/47117960/58883459-c3f53700-86de-11e9-85a3-fd944cd2e1ad.png)

Hemos hecho la prueba con el contrato de Ainhoa COM/01460 y su código promocional: AMIGOABEGA

**Comment by dgarciageo** [comment]
Cuando un cliente intenta dar de alta el contrato a través de su portal da un error al final del proceso:

![image](https://user-images.githubusercontent.com/47117960/63504022-eeca7c80-c4d0-11e9-8d9f-4ef897859412.png)

**Comment by jorgereal** [comment]
El problema se debe a que cuando se crea un nuevo contrato desde la WEB y se introduce un código amigo éste baja a NAVISION con el campo SalesPersoncode del contrato formado por la primera y tercera letra del código amigo (en este caso AI).

No sé si antes el vendedor 'AMIGO' que existe tanto en PRE como en PRO tenía el código 'AI' en lugar al actual 'AMIGO'.

Se podría cambiar la web para que baje como vendedor el código 'AMIGO' o cambiar en NAV el código de éste a 'AI'.

Quedo a la espera de vuestra respuesta.

**Comment by dgarciageo** [comment]
Buenas jorge,

Ni idea dw por qué estaba así? Puedes poner que busque AMIGO que es como
llamamos a la campaña? Avisamos por favor cuando lo tengas ok?

Muchas gracias!!!
Dani

**Comment by dgarciageo** [comment]
¿Pudiste arreglarnos esto? El cliente nos está preguntando de nuevo

**Comment by dgarciageo** [comment]
Buenas, hemos hecho la prueba de nuevo en PRE con el mismo usuario y ahora da el siguiente error:

![image](https://user-images.githubusercontent.com/47117960/63591495-42ab9300-c5af-11e9-979c-5f529fdeb568.png)

**Comment by jorgereal** [comment]
¿Puedes volver a probar ahora? Yo ya he conseguido hacer una prueba correcta.

**Comment by dgarciageo** [comment]
Buenas Jorge,

He creado yo uno nuevo y aunque el proceso finaliza ok hemos recibido el siguiente error:

![image](https://user-images.githubusercontent.com/47117960/63593199-cf585000-c5b3-11e9-9ba6-12962fb6f87f.png)

**Comment by dgarciageo** [comment]
incidencia resuelta y subida a PROD
