### ISSUE TITLE
FACTURA HECEN - Dirección completa en los datos del contrato

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#555]
No sale la dirección completa en los datos del contrato Ejemplo 

![image](https://user-images.githubusercontent.com/47117960/58954901-bbfacd00-879a-11e9-9f88-d60cac5ba225.png)

Ejemplo Cliente 10078 contrato HECEN/09429

![image](https://user-images.githubusercontent.com/47117960/58955106-4cd1a880-879b-11e9-93e7-8ed31f75a525.png)

**Comment by JMunoz17** [comment]
Subido a PRE y a PROD.
