### ISSUE TITLE
WEB - Nuevo diseño email factura

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#559]
Se enviará word con los detalles del nuevo formato

**Comment by jlagunapkf** [comment]
Esta subido a test y a producción.

**Comment by jlagunapkf** [comment]
Dani, ya está subido a test y pro, comprueba la configuración de los mails. Te hemos dejado la configuración como me has comentado esta mañana, aún así echa un ojo a la redirección de "¿Quieres saber por qué?"

**Comment by jlagunapkf** [comment]
Dani, ya está subido a test y pro, comprueba la configuración de los mails. Te hemos dejado la configuración como me has comentado esta mañana, aún así echa un ojo a la redirección de "¿Quieres saber por qué?"

**Comment by dgarciageo** [comment]
Buenas Jaime,



Dónde está la tabla que me comentabas de los comentarios?

Que no la encuentro



Muchas gracias,
Daniel



*De:* jlagunapkf <notifications@github.com>
*Enviado el:* martes, 18 de junio de 2019 16:03
*Para:* PKFEric/webProxima <webProxima@noreply.github.com>
*CC:* dgarciageo <dgarcia@geoatlanter.com>; Assign <
assign@noreply.github.com>
*Asunto:* Re: [PKFEric/webProxima] WEB - Nuevo diseño email factura (#559)



Dani, ya está subido a test y pro, comprueba la configuración de los mails.
Te hemos dejado la configuración como me has comentado esta mañana, aún así
echa un ojo a la redirección de "¿Quieres saber por qué?"

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/PKFEric/webProxima/issues/559?email_source=notifications&email_token=ALHPNCCZSZIK24OJC37VFSDP3DTITA5CNFSM4HWHBOL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODX6XH3Y#issuecomment-503149551>,
or mute the thread

**Comment by jlagunapkf** [comment]
Buenas Dani. 

Me comenta Jaime que es en la tabla de Informanción de Empresa.

**Comment by dgarciageo** [comment]
Hemos debido de machacar algo porque esta saliendo la foto cabecera antigua en los emails de nueva factura:
![image](https://user-images.githubusercontent.com/47117960/60573600-40c80f00-9d78-11e9-8aab-5c22efc7a9ea.png)

En lugar de la nueva
![Cabecera factura Próxima](https://user-images.githubusercontent.com/47117960/60574002-fe530200-9d78-11e9-878d-8a01b0839698.png)

**Comment by jlagunapkf** [comment]
Ya está solucionado.
