### ISSUE TITLE
NAV - Revisar plantilla factura Proxima Energia

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#561]
1) RESUMEN DE LA FACTURA:

El descuento de la campaña amigo tiene que aparecer al final de todos los conceptos:

![image](https://user-images.githubusercontent.com/47117960/59209943-c1964f80-8bac-11e9-9d2a-95c4ebcd9247.png)

2) DETALLE DE LA FACTURA:
El descuento no debe salir tabulado, debe salir a la izquierda como el resto de conceptos.
![image](https://user-images.githubusercontent.com/47117960/59209978-d541b600-8bac-11e9-8931-fe02b18211e1.png)

3) BANNER CAMPAÑA AMIGO
Sustituir la pegatina del banner de campaña amigo por la pegatina de los -5€

![image](https://user-images.githubusercontent.com/47117960/59211255-babd0c00-8baf-11e9-9f31-a492cb684510.png)

**Comment by jorgereal** [comment]
Se han realizado las tres modificaciones solicitadas en el formato de factura de GEO.

Subido a PRE.
