### ISSUE TITLE
WEB - Sacar log Campaña Amigo en zona administración valores Web

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#562]
¿Podemos añadir una columna [TimeStamps] en la tabla Campaings  con default value getdate() sin romper algo de NAV?

**Comment by dgarciageo** [comment]
descartado!

**Comment by PKFEric** [comment]
Subido a pre

**Comment by dgarciageo** [comment]
Creo que falta subir un SP al mySql de J

![image](https://user-images.githubusercontent.com/47117960/60268141-05e35880-98ec-11e9-8fc0-d8c691ffba8b.png)

**Comment by PKFEric** [comment]
Ya esta subido el proc almacenado a PRE ahora deberia funcionar

**Comment by PKFEric** [comment]
Cuando lo  pruebes todo avisa para subirlo a PRO

**Comment by dgarciageo** [comment]
La tabla en la web de PRE sale vacía pero entiendo que es porque la tabla geo_administracion_pre.campaniaamigo esta vacía. Puedes subirlo a Producción cuando quieras. Muchas gracias!

**Comment by PKFEric** [comment]
Ya esta en PRO , y sale con los datos
