### ISSUE TITLE
Web Proxima - Cambio titular / Cambio pagador

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#564]
1. CAMBIO DE TITULAR:
Migrar la funcionalidad de atulado a proxima incluyendo el correo que se envía con los datos cliente, mismo campos y mismo formato que en el caso de atulado.

2. CAMBIO DE PAGADOR:
No sale el campo población en el correo que se le manda a Ainhoa.
Además falta formatear en negrita el email como en atulado

Cambio pagador proxima
![image](https://user-images.githubusercontent.com/47117960/59287607-4b5c2080-8c72-11e9-90e1-16ef49d72cfb.png)

Cambio pagador en atulado
![image](https://user-images.githubusercontent.com/47117960/59287669-67f85880-8c72-11e9-98a9-bba1c5766ec5.png)

**Comment by PKFEric** [comment]
subido a pre

**Comment by dgarciageo** [comment]
Cambio de titular da error al subir fichero:

![image](https://user-images.githubusercontent.com/47117960/60268900-c453ad00-98ed-11e9-8426-774a569b6d5b.png)

**Comment by dgarciageo** [comment]
Test OK. Podéis subir a PRO.
