### ISSUE TITLE
ERROR RECOBROS - No se rellena el campo de Ruta carta pagador Formal de deuda

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#565]
En la ventana de gestión de impagos salen 211 cartas pendientes de envio

![image](https://user-images.githubusercontent.com/47117960/59359650-0518c700-8d2f-11e9-8a9d-339662ffd8d1.png)

Abres el desplegable y salen las 211 porque no tienen el campo de ruta carta forma de deuda relleno
![image](https://user-images.githubusercontent.com/47117960/59359628-f92d0500-8d2e-11e9-908d-96d67c0a2a28.png)

Pero buscando cualquiera de los documentos en red sí que aparecen generados los pdf
La ruta donde se generan los pdfs es en: \\ni\Esios\Mail Baja HECEN
 
![image](https://user-images.githubusercontent.com/47117960/59359773-3d200a00-8d2f-11e9-866e-fcbb3f1be23b.png)

**Comment by dgarciageo** [comment]
También sale este error

![image](https://user-images.githubusercontent.com/47117960/59598784-4d543280-90fd-11e9-8a9a-dfe717bab20b.png)

**Comment by JMunoz17** [comment]
Subido a TEST y PROD.
