### ISSUE TITLE
WEB proxima - https://www.proximaenergia.com/Index + Pagina NO ENCONTADA

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#567]
la pagina de error 404 sale PAGINA NO ENCONTADA (ver imagen adjunta)
![image](https://user-images.githubusercontent.com/47117960/59696663-bb2b5780-91ec-11e9-9d28-a1ded691bc45.png)

**Comment by PKFEric** [comment]
Esta tarea la estais gestionando vostros ??

**Comment by dgarciageo** [comment]
Sólo necesitamos que nos cambiéis lo de NO ENCONTADA por NO ENCONTRADA
Lo de que no se encuentre la página en google lo vamos a trabajar dentro del proyecto de la nueva web que incluye revisión de Google Analytics y SEO

**Comment by dgarciageo** [comment]
se ha creado un re.direccion en el ISS y ahora parece que google indexa correctamente el domino
