### ISSUE TITLE
NAV - Meter campo Nº de movimiento en la pantalla de gestión de cobros 

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#568]
![image](https://user-images.githubusercontent.com/47117960/59768641-0012c500-92a5-11e9-817e-410ca8e985d3.png)

Cuando intento meter el campo recibo el siguiente error:
![image](https://user-images.githubusercontent.com/47117960/59768724-246ea180-92a5-11e9-9647-f63b9dd8eca2.png)

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
