### ISSUE TITLE
WEB atulado - Cambio de tarifa (Tarifa actual MILENIAL)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#569]
Cuando un cliente tiene tarifa MILENIAL (como en el caso de la imagen) y quiere cambiarse a otra en el cuadro de tarifa actual le aparece 2.0DHA en lugar de MILENIAL

![image](https://user-images.githubusercontent.com/47117960/59840861-8980d080-9353-11e9-87f2-90a8529bdc7f.png)

**Comment by dgarciageo** [comment]
He hecho la prueba en PRO con el contrato HECEN/09818 y en la web sigue apareciendo DHA
![image](https://user-images.githubusercontent.com/47117960/61224569-1a628600-a71f-11e9-8ea4-22c1ff4fa219.png)

**Comment by jlagunapkf** [comment]
Buenas Dani. 
Haz la prueba en PRE, porque no está subido a PRO.

**Comment by dgarciageo** [comment]
Test en PRE ok

![image](https://user-images.githubusercontent.com/47117960/61290069-420f2800-a7cb-11e9-86e0-270482360e78.png)

**Comment by JMunoz17** [comment]
Subido a PROD.
