### ISSUE TITLE
Migrar repositorio Attest a Geo (Azure DevOps) + Entorno local desarrollo

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#570]
Migrar repositorios de Azure Dev Ops de Attest a la cuenta de Geo

![image](https://user-images.githubusercontent.com/47117960/63292714-94f66680-c2c6-11e9-935c-e46167b77b62.png)

Crear un manual de configuración para crear un entorno local de desarrollo que tire contra la BBDD de PRE de Navision

**Comment by JMunoz17** [comment]
Hemos traspasado los proyectos de la web de atulado y la web de geoatlanter a los repositorios que creasteis. 

Como nosotros no podemos crear mas repositorios necesitamos que creéis los siguientes para incluir el resto de proyectos que tenemos:
- Cargas Mic Mic.
- WS Catastro.
- Split F5D.
- Descarga Esios.

También si es posible que añadáis al repositorio a los usuarios:
jreal@pkf-attest.es
jorge.laguna@pkf-attest.es
Para tener todos acceso.

**Comment by bpesquero** [comment]
ESto lo vamos a tener que dejar pendiente para la vuelta de Dani, ok?

**Comment by dgarciageo** [comment]
Chicos,

Os lo creo, que no tardo nada en hacerlo no os preocupéis, os aviso en
cuanto esté
No lo postpongais. Muchas gracias

Dani

**Comment by dgarciageo** [comment]
Buenas chicos,



Ye tenemos los nuevos proyectos creados en DevOps y os he dado los
privilegios necesarios.

También hemos incluido a Jorge real y Jorge laguna en los 6 proyectos

Si necesitáis cualquier otra cosa me decís sin problema que leo el correo
de vez en cuando



Muchas gracias,

Dani







*De:* JMunoz17 <notifications@github.com>
*Enviado el:* lunes, 23 de septiembre de 2019 11:17
*Para:* PKFEric/webProxima <webProxima@noreply.github.com>
*CC:* dgarciageo <dgarcia@geoatlanter.com>; Assign <
assign@noreply.github.com>
*Asunto:* Re: [PKFEric/webProxima] Migrar repositorio Attest a Geo (Azure
DevOps) + Entorno local desarrollo (#570)



Hemos traspasado los proyectos de la web de atulado y la web de geoatlanter
a los repositorios que creasteis.

Como nosotros no podemos crear mas repositorios necesitamos que creéis los
siguientes para incluir el resto de proyectos que tenemos:

   - Cargas Mic Mic.
   - WS Catastro.
   - Split F5D.
   - Descarga Esios.

También si es posible que añadáis al repositorio a los usuarios:
jreal@pkf-attest.es
jorge.laguna@pkf-attest.es
Para tener todos acceso.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/PKFEric/webProxima/issues/570?email_source=notifications&email_token=ALHPNCHDQRMB6NGZUGAR5A3QLCCQVA5CNFSM4HZRNOZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7KIBFI#issuecomment-534020245>,
or mute the thread

**Comment by PKFEric** [comment]
Ya estan subidos todos
