### ISSUE TITLE
WEB - Migrar "Alta Nuevo Contrato" (Paso 1)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#571]
Migrar la funcionalidad de alta nuevo contrato de atulado a próxima, 3 tareas:

- [x] Cerrar tarea Potencia y tarifa actuales en un C2 / Histórico de Acciones #527

- [x]  Incluir en la web la sección de tarifa actual y potencia actual

![image](https://user-images.githubusercontent.com/47117960/60023194-996f1c00-9695-11e9-8ca2-ab730ff5484c.png)

- [x]  Implementar en NAV la funcionalidad de "Generar solictud  de cambio" gracias al cual se generan de forma masiva C1s o C2s dependiendo del cambio que se haya requerido desde la web. 

![image](https://user-images.githubusercontent.com/47117960/60024628-637f6700-9698-11e9-946b-a30ff67596d3.png)

Será necesario rellenar el check de "Generar C2" de la pestaña general como en HECEN
![Uploading image.png…]()

**Comment by bpesquero** [comment]
Hemos hecho las pruebas y hemos viso

1.- DEbería poner peaje a contratar en vez de peaje de acceso
2.- Debería poner potencia actual en vez de potencia

**Comment by bpesquero** [comment]
Habría que añadir en la parte de puntos suministro un texto similar al que aparece en la web de HECEN
El texto sería este



![image](https://user-images.githubusercontent.com/20299071/70050537-7c892e00-15cf-11ea-87be-894667e99951.png)
Te informamos que cualquier modificación técnica, implica un coste por parte de la distribuidora de 9,04 €+IVA, en concepto de derechos de enganche, que te repercutiremos sin ningún margen ni comisión por nuestra parte. Adicionalmente, te informamos de que cualquier aumento de potencia, además de los 9,04 €+IVA de derechos de enganche, implica también el cobro de otros derechos por parte de la distribuidora. Si quieres conocerlos, llámanos y te informamos de todo.

**Comment by PKFEric** [comment]
Subido a PRO

**Comment by dgarciageo** [comment]
Test ok

![image](https://user-images.githubusercontent.com/47117960/71479973-2dfa3880-27f7-11ea-9103-83745c4339ce.png)
