### ISSUE TITLE
Web atulado - Generar M1 con cambio de potencia e integración con Signaturit(Paso 2)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#572]
En atulado se generan de manera automática los M1 cuando se da un cambio de tarifa y cambio de potencia, pero si se trata de un cambio de potencia sin cambio de tarifa no se genera M1.

La idea es que se generen los M1  con:
- Cambio de tarifa
- Cambio de potencia
- O cambio de tarifa y potencia

Integración con signaturit. Se tiene que enviar el contrato por Signaturit con las nuevas condiciones contractuales para que las firme el cliente. El documento se codificará como **COM_01894_M1** para distinguirlos de los C1s o C2s

![image](https://user-images.githubusercontent.com/47117960/70164342-44faae80-16c1-11ea-8d63-e105afbb6c2d.png)

**Comment by dgarciageo** [comment]
Vamos a esperar al 01 de Enero a que salga la nueva normativa de tarificación horaria con la que todo el mundo tendrá 6 periodos y ya no habrá tarifas (a excepción de que se cambien de baja a alta tensión)

**Comment by jorgereal** [comment]
Se ha realizado las modificaciones solicitadas y se han subido a PROD.
