### ISSUE TITLE
Web próxima - Migrar "Generar M1 de forma automática e integración con Signaturit"  (Paso 3)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#573]
Migrar funcionalidad de la web de atulado de "Generar M1 de forma automática" a partir una petición de cambio de tarifa y/o cambio de potencia.

Esta incidencia depende del Issue:

**Web atulado - Generar M1 con cambio de potencia #572**

Se debe terminar la #572 antes de realizar la migración

**Comment by dgarciageo** [comment]
Vamos a esperar al 01 de Enero a que salga la nueva normativa de tarificación horaria con la que todo el mundo tendrá 6 periodos y ya no habrá tarifas (a excepción de que se cambien de baja a alta tensión)

**Comment by PKFEric** [comment]
Entonces esta tarea la ponemos en on HOLD?

**Comment by jorgereal** [comment]
Se ha añadido la funcionalidad de generación de M1 en los cambios de tarifa y/o potencia además de la integración con signaturit. Subido a PROD.
