### ISSUE TITLE
WEB atulado - Timeout por elevado número de facturas

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#574]
El cliente tiene 'CL06340' en su área cliente 175 facturas 

![image](https://user-images.githubusercontent.com/47117960/60111101-9b0c1300-976d-11e9-9b8f-6e45d55dc360.png)

Cuando hacemos clic sobre "Mis Facturas" pasa un buen rato hasta que devuelve el resultado, dando en ocasiones un timeout.

La query que esta ralentizando el proceso es la que ataca la tabla "Hidroeléctrica El Carmen Energ$Cust_ Ledger Entry" para comprobar el estado de impago de cada factura:

SELECT TOP 1 * FROM "GEOATLANTER_SQL"."dbo"."Hidroeléctrica El Carmen Energ$Cust_ Ledger Entry"  WHERE (("Document No_" LIKE @P1)) AND (("Open"=@P2)) ORDER BY "Document No_","Entry No_" OPTION (OPTIMIZE FOR UNKNOWN)

![image](https://user-images.githubusercontent.com/47117960/60111428-343b2980-976e-11e9-8b46-18fb2a5f7e41.png)

Conviene limitar el número de campos que trae esta query para poder crear un indice por los campos:  "Document No_" y "Open"

**Comment by JMunoz17** [comment]
Realizada la parte de NAV, queda pendiente parte WEB.

**Comment by PKFEric** [comment]
Subido a pre la web

**Comment by JMunoz17** [comment]
Subido a PROD.
