### ISSUE TITLE
Control carga F1s de Conceptos re-percutibles

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#577]
Hemos cargado por error un F1 de HECEN en GEO 

\\NI\Esios\F1 Hecen\WAIT MONICA\Issue577\SCTDE_F1_01_0022_0713_20190616080350233_(774252520).xml

![image](https://user-images.githubusercontent.com/47117960/60279601-a98b3380-9901-11e9-8e18-5e2a78848b0c.png)

Pero no ha dado ningún tipo de error al cargarse en GEO. Se ha cargado sin problemas en NAV

![image](https://user-images.githubusercontent.com/47117960/60279145-d4c15300-9900-11e9-9288-9f78c21ccafe.png)

Se ha asignado a un COM con un CUPS totalmente diferente

![image](https://user-images.githubusercontent.com/47117960/60279706-d93a3b80-9901-11e9-8545-028cb7cbe5e1.png)

Incluso hemos podido generar una factura de venta.

Hemos hecho la prueba con otros F1s de conceptos repercutibles y pasa lo mismo.

Se requiere aplicar un control sobre los F1s de conceptos repercutibles que evite la carga al igual que sucede con los F1s normales.

**Comment by JMunoz17** [comment]
Subido a PRE.

**Comment by JMunoz17** [comment]
Subido a PROD.
