### ISSUE TITLE
NAV- Control carga F5s repetidos (Refacturación)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#578]
Cuando refacturamos tenemos que cargar F5s que ya han sido cargados en bbdd borrando previamente la vesion de las medidas anteriores

Si no nos damos cuenta de que el F5 que han publicado es una refacturación el fichero se procesa pero en realidad no se carga en la tabla medidas y no da ningún error en la tabla de logs

Añadir un control que compruebe  si el nº de factura de acceso de ese F5 ya existe en BDDD, y en tal caso informar del error y que no se cargue el F5

**Comment by JMunoz17** [comment]
Subido a PRE.

**Comment by JMunoz17** [comment]
Subido a PROD.
