### ISSUE TITLE
WEBS - Cambiar mail "Confirmación alta usuario"

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#579]
Cambiar texto  del email que recibe el cliente al finalizar la contratación de atulado y de proxima :

Proxima:
![image](https://user-images.githubusercontent.com/47117960/61617452-fe08a100-ac6a-11e9-8ff8-df5b1f78d698.png)

A tu lado:
![image](https://user-images.githubusercontent.com/47117960/61617468-05c84580-ac6b-11e9-998f-e5d17982fa2b.png)

**Comment by JMunoz17** [comment]
Subida a PROD en atulado, pendiente de subir en próxima.

**Comment by PKFEric** [comment]
subido a prod en proxima

**Comment by dgarciageo** [comment]
Falta lo de [domicilio|empresa] y el plural de las siguiente(s), potencia(s) contratada(s) tiene que ser dinámico. Habrá que corregirlo en proxima y atulado.

![image](https://user-images.githubusercontent.com/47117960/61949613-b60bb600-afab-11e9-9c10-4dd5fed2e6ad.png)
