### ISSUE TITLE
asignacion incorrecta de codigo tarifa en ficha de contrato

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#58]
Se asigna incorrectamente el cod de tarifa ATR en la ficha del contrato, lo que provoca que no se puedan cargar los ficheros de activación ni las facturas.

**Comment by PKFEric** [comment]
CORREGIDO TANTO EN NAVISION COMO EN LA WEB-> Y PROBADO CON DOS CONTRATOS. HA RELLENADO BIEN EL CODIGO DE OCSUM DE AMBOS
