### ISSUE TITLE
NAV Roles - Contador de mail enviados al lanzar facturas

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#580]
Hay veces que al lanzar facturas no se manda el correo de aviso de disponibilidad de factura y no se marca el check de visible web

Necesitamos que se genere un log  con el conteo de veces que se ha pasado por el código de enviar mail y de check de Cliente web

**Comment by JMunoz17** [comment]
Tal y como comentamos el otro día por teléfono añadir un contador no tiene sentido ya que nos devolvería siempre el mismo nº, que coincidiría con el número total de facturas dentro del filtro al ejecutar el proceso.

Hemos revisado el proceso a fondo y no debería de suceder el caso que nos comentáis (factura marcada como "visible web" pero que no se ve desde la web). Si la subida al FTP fallase (intento de copiar un fichero abierto, fallo de conexión con la ruta del ftp u otros problemas) debería de devolvernos el error en Navision (y lo normal (depende el error) es que fallase para todas, no para una en concreto).

Vamos a dejar el código tal y como esta y necesitaremos que si os vuelve a suceder nos proporcionéis toda la información posible. Para solucionarlo, como ya sabéis, basta con volver a lanzar el proceso marcando el check de subir al FTP.

**Comment by dgarciageo** [comment]
Conformes con lo propuesto
