### ISSUE TITLE
Plantilla email- Nueva factura

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#581]
![image](https://user-images.githubusercontent.com/47117960/60649898-49d1e280-9e43-11e9-8994-858dea6e6592.png)

**Comment by dgarciageo** [comment]
Factura de agosto:

![image](https://user-images.githubusercontent.com/47117960/63762899-f371a500-c8c3-11e9-890b-548e64ecc237.png)

------------------------------

![image](https://user-images.githubusercontent.com/47117960/63763069-477c8980-c8c4-11e9-852e-35d6cddf9635.png)

**Comment by JMunoz17** [comment]
Actualmente el mes que mostramos lo sacamos del campo "Fecha Hasta" de la cabecera de la factura. En este caso es el mes 4, de ahí que ponga Abril.

De que campo debemos cogerlo? 
Fecha Registro? Fecha Pedido? Fecha Envío? Fecha Emisión Documento?

**Comment by dgarciageo** [comment]
Buenas Jaime,

Entonces esta bien tal y como esta.
Cerramos la incidencia, perdona
