### ISSUE TITLE
WEB atulado - Incidencia plantilla contrato

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#582]
En la plantilla del contrato de A TU LADO, un cliente ha visto que el precio de la MILENIAL no le aparece en P1 y P2 sino en P2 y P3

![image](https://user-images.githubusercontent.com/47117960/61226407-a629e180-a722-11e9-9cd1-ab205a75a0d1.png)

Por otro lado, en las condiciones generales aparece PRÓXIMA (en lugar de ATULADO) en algún párrafo. 
Os dejamos la plantilla que se ha descargado el cliente con los problemas en la siguiente ruta:
\\NI\Esios\F1\WAIT ERIC\HECEN_09833.pdf

Os dejamos las condiciones generales corregidas en la siguiente ruta:
Z:\Proyectos\Hidroelectrica El Carmen\Comercializacion\A tu lado\Contratos HECEN\20190501\201905 Condiciones generales del contrato de suministro de energía electrica_v2.doc

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
