### ISSUE TITLE
WEB GEO - Actualizar clausula para el formulario web de contacto GEO

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#583]
Se debe implementar en la sección de contacto de la web corporativa la misma validación de política de privacidad que ya en las webs de proxima y atulado 

![image](https://user-images.githubusercontent.com/47117960/61436740-ba94f680-a93b-11e9-81f3-1ae34a6c4df3.png)

El mensaje de la web y la política de privacidad que se debe mostrar al hacer click sobre el enlace se enviará por correo

**Comment by jlagunapkf** [comment]
Ya se ha añadido la aceptación de la política de privacidad al formulario de contacto.
