### ISSUE TITLE
WEB - atulado/proxima - Sincronizacion con Nav /Signaturit (URGENTE)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#584]
Incluir varios botones en la sección de administración\gestion de valores que permita realizar los siguientes procesos seleccionando de la tabla de Log una entrada en concreto: 

1) Crear cliente NAV. Se comprueba que el cliente exista en NAV (Si no existe lo crea)
2) Crear contrato NAV. Se comprueba que el contrato exista en NAV (Si no existe lo crea)
3) Crear contrato en signaturit. Se comprueba que el contrato exista en Signaturit (Si no existe lo crea)

Si se puede que la cabecera de la tabla logs permanezca visible al hacer scroll vertical en la página
![image](https://user-images.githubusercontent.com/47117960/70704273-fa38f200-1cd1-11ea-8e6b-ed210f17ad4a.png)

**Comment by bpesquero** [comment]
Lo dejamos pendiente de nueva definición de proceso de contratación web.

**Comment by dgarciageo** [comment]
No aplica con el nuevo proceso de contratación y modificaciones a través de la nueva web.
