### ISSUE TITLE
WEB atulado - Descarga contrato (Precios contrato)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#585]
Suelen llamar clientes comentando que al descargarse el contrato no aparecen los precios,. 
El problema es que el contrato está en "firmado cliente" y los precios no se rellenan hasta que no recibimos la activación. Cambiar el proceso de activación del cliente en NAV es complicado por lo que se opta por des-habilitar la opción de descarga del contrato hasta que el contrato no esté en estado activado.  

Al pulsar sobre el botón de descarga del contrato se mostrará el siguiente mensaje:

El contrato aún no está disponible, necesitamos la aceptación del distribuidor. Tan pronto éste nos confirme te mandaremos un email informándote de que “Ya te estamos suministrando energía”. Si tienes cualquier duda, estaremos encantados de atenderte en el correo electrónico clientes@atuladoenergia.com o, en horario laboral, a través de nuestro número de teléfono gratuito 900818852

**Comment by jlagunapkf** [comment]
Subido a PRO y a PRE
