### ISSUE TITLE
WEB atulado/proxima - Email ya te estamos suministrando energia

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#586]
Añadir en el cuerpo del mensaje el CUPS al que se hace referencia.

... y celebramos confirmarte que desde el días 24/06/19 ya te estamos suministrando electricidad para el contrato con CUPS **[CUPS]**

![image](https://user-images.githubusercontent.com/47117960/61791809-4cf53880-ae1b-11e9-8aa2-b9048b1d232e.png)

**Comment by JMunoz17** [comment]
Subido a PRE.

**Comment by dgarciageo** [comment]
Test ok
![image](https://user-images.githubusercontent.com/47117960/62292741-5f005800-b467-11e9-8a76-45d6bcb2a1d3.png)

**Comment by JMunoz17** [comment]
Subido a PROD.
