### ISSUE TITLE
NAV - MILENIAL: C2's + DHA (No se actualiza Cod Tipo Contrato a 96)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#587]
Tenemos un problema con los clientes que tienen DHA y solicitan un cambio de tarifa a MILENIAL.
Al ser ambas tarifas DHA se tramita el cambio con un C1 y Navision no se entera de que tiene que cambiar el código de tipo de contrato a MILENIAL

**Comment by JMunoz17** [comment]
Modificado y subido a PRE.
