### ISSUE TITLE
WEB atulado - Añadir campos al email de "Tienes una nueva factura"

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#589]
![image](https://user-images.githubusercontent.com/47117960/62043976-23188900-b202-11e9-8f36-d7c2d8320da1.png)
siguiente punto de suministro: 

Dirección: CALLE COLEGIO UNIVERSITARIO , 26 , 04120, LA CAÑADA, ALMERIA 
Titular: NOMBRE APELLIDO1 APELLIDO2 
CUPS: ES0031104276039999ZZ 
Número de Factura: C/20197276 

De acuerdo con tus indicaciones, te será cargada en la cuenta bancaria que nos comunicaste. 

![image](https://user-images.githubusercontent.com/47117960/62044069-53f8be00-b202-11e9-926e-7c5eacd0f76d.png)

**Comment by JMunoz17** [comment]
Subido a PRE.

**Comment by dgarciageo** [comment]
Test correcto

![image](https://user-images.githubusercontent.com/47117960/62128218-3d229c00-b2d4-11e9-828e-60b3f04dc2c9.png)

**Comment by JMunoz17** [comment]
Subido a PROD.
