### ISSUE TITLE
NAV - Problema carga de F1_0599_201900003926_37205273_av.xml

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#590]
No conseguimos cargar el siguiente F1
\\NI\Esios\F1 Hecen\WAIT MONICA\Task_590

Nos devuelve el siguiente error pero la las fechas del TE en principio son correctas. No entendemos qué puede pasar
![image](https://user-images.githubusercontent.com/47117960/62051913-aba02500-b214-11e9-9d1a-2f7637b0e85e.png)

**Comment by JMunoz17** [comment]
Hemos detectado que el contrato HECEN/09374 (ES0599000000000691MZ) ya tiene una facturación anterior: FCR/2019035695 | H/2019035232.

Estas facturas no tienen asociados peajes, lo que provoca que al procesar el F1 se detecte esta factura como la primera asociada al contrato y de error al no coincidir la fecha de inicio de facturación del contrato con la fecha desde de la factura que estamos importando.

Por qué no tenemos los peajes correspondientes a la anterior factura?

**Comment by dgarciageo** [comment]
Cuando dicen que no tiene los peajes asociados es que desde histórico facturas de compra del contrato HECEN/09374, yendo a Factura\Ficha de la única FC registrada,  Factura\Peajes la pantalla sale vacía. 
Es posible que se haya borrado por error. El F1 para volver a cargarlo esta en:

\\NI\Esios\F1 Hecen\Procesados\F1_0599_201900003525_36768920_av.xml

El problema es que la factura de venta anterior ya esta registra. la solución creo que pasaría por cargar en la tabla de peajes las entradas necesarias para que cuando se cargue el F1 nuevo no se vaya a la factura anterior.
