### ISSUE TITLE
NAV - Error Venta HECEN/08249

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#591]
No podemos generar la FV para el contrato en HECEN (HECEN/08249) porque nos da el siguiente error: “El índice 0 de la matriz queda fuera del rango permisible”. 

Cuando cargo el F1 el único log que me da es el “Error Factura, no coinciden los datos de cierre 1.298 y peaje -1.241 en Energía Activa”. Esto siempre me da con la G a los que les está regularizando energía.

Os dejamos el F1 asociado (ya cargado en el contrato) en la siguiente ruta:
\\NI\Esios\F1 Hecen\WAIT MONICA\Task_591

**Comment by JMunoz17** [comment]
El problema es que la factura que nos viene refactura el ultimo año entero englobando de esta manera 12 facturas, caso con el que nos encontramos por primera vez.

Hasta ahora no habíamos tenido un caso con mas de 10. El código usaba arrays limitados a 10 posiciones, de ahí el desbordamiento que se ha producido. Hemos modificado el código aumentando los arrays de 10 a 20 posiciones para que funcione.

La factura de venta se ha generado -> FV/2019042861

En el log tenemos el siguiente error:
![image](https://user-images.githubusercontent.com/26869276/62215017-70356000-b3a6-11e9-8964-0548d8240bd3.png)

Revisad la factura de venta y nos decís.
