### ISSUE TITLE
WEBs - Filtrar códigos postales extrapeninsulares

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#592]
En próxima creo que ya tenemos algo implementado. Filtrar o informar al usuario al seleccionar un CP extra-peninsular que no damos servicio en ese código

**Comment by bpesquero** [comment]
habría que dar un mensaje diciendo "Próxima Energía no comercializa luz fuera de la Península, disculpa las molestias"  y "A tu lado Energía no comercializa luz fuera de la Península, disculpa las molestias"

**Comment by PKFEric** [comment]
![image](https://user-images.githubusercontent.com/20229934/68294546-c1817980-0090-11ea-8a1b-d6fb997affd4.png)

Entonces solo cambio el mensaje??

**Comment by bpesquero** [comment]
Me dice Ainhoa que a ella no le aparece mensaje. Ese mensaje es correcta el problema es que ella me dice que no apare mensaje

**Comment by bpesquero** [comment]
Mensaje que sale cuando escribes el CP ( mientras que vas tecleando cada nº) :“Código Postal incorrecto. Sólo comercializamos puntos de suministro peninsulares.”

 

Cuando terminas de escribir el CP desaparece el mensaje y pone en verde CP verificado, con el municipio y provincia en blanco.

 

Pero ahora sí que me ha aparecido el mensaje al darle a SIGUIENTE  (:“Código Postal incorrecto. Sólo comercializamos puntos de suministro peninsulares.”) de nuevo (ayer no salió con ninguno de los tres códigos postales ni Baleares, ni Canarias ni Ceuta y Melilla al darle a siguiente).

 Lo dejamos de momento así, aunque es cierto que es algo confuso
