### ISSUE TITLE
Problema promoción AMIGO (Entrada manual)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#594]
Tenemos 2 contratos para los que tuvimos que crear manualmente una entrada en la tabla "Campaings" para la campaña AMIGO
COM/01486
COM/01183

![image](https://user-images.githubusercontent.com/47117960/63415001-4a2b3a80-c3fd-11e9-9405-8ae1f82cda8b.png)

Pero al generar la factura para ambos contratos no conseguimos que nos coja el descuento:
![image](https://user-images.githubusercontent.com/47117960/63415070-69c26300-c3fd-11e9-9a02-257075af8c95.png)

Ambos contratos tienen las 2 últimas facturas sin registrar por lo que se pueden borrar y volver a generar para intentar reproducir el error en producción.

![image](https://user-images.githubusercontent.com/47117960/63504730-6cdb5300-c4d2-11e9-9387-83b2deae8729.png)

**Comment by jorgereal** [comment]
El problema estaba en el código de campaña de las entradas creadas manualmente, en lugar de 'AMIGO' ponía 'AMIGO    ', seguramente se copió desde algún otro sitio.
Se ha corregido y se ha vuelto a generar la prefactura de venta para el contrato COM/01486, cogiendo ahora sí el descuento.
Para el contrato COM/01183 no había ninguna prefactura, la última registrada es la de julio, el descuento se aplicará en la próxima factura.
