### ISSUE TITLE
¿Cómo configurar la tabla configuración de energía para la carga de F5s, A5s y B5s?

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#595]

**Comment by bpesquero** [comment]
Entiendo que es en la tabla de configuración de BBDD, verdad?
Puedo poner el código que quiera, verdad?

**Comment by JMunoz17** [comment]
Efectivamente es en la tabla de configuración de BBDD.
Tenéis que rellenar los siguientes campos:
   - Tipo Registro: BBDD.
   - Código: El que queráis.
   - BBDD - Tipo Configuración: A5D_CCH | B5D_CCH.
   - BBDD - Origen ficheros: la ruta de origen de los ficheros a procesar.
   - BBDD - Archivado ficheros: la ruta de destino de los ficheros procesados.

Una linea para A5D y otra para B5D. Podéis tomar como referencia como están configurados el F5D o el P1D,
