### ISSUE TITLE
ERROR WEB - Razón social > 45 caracteres

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#597]
Se requiere ampliar el campo nombre de empresa de ambas webs

![image](https://user-images.githubusercontent.com/47117960/63675660-96a1bc00-c7e9-11e9-975e-006a2332795a.png)

**Comment by JMunoz17** [comment]
El error da al validar el valor que viene de la web contra el campo Nombre que utilizamos en Ocsum (este tiene longitud 45).

El campo Nombre estándar en el que también guardamos este valor tiene longitud 50, por lo que en caso de ampliar el campo Nombre de Ocsum solo podríamos aumentarlo hasta 50, creo que es mejor solución limitar en la web la entrada del dato a 45 caracteres, es decir no permitir que bajen de la web valores mayores a 45, os parece?

**Comment by bpesquero** [comment]
ok. Perfecto

**Comment by bpesquero** [comment]
Probado y ok
