### ISSUE TITLE
WEB - Pestaña plan amigo cabecera tabla

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#598]
Aparecen los iconos de paginación pese a que no temnemos más registros que los mostrados en la tabla.

Cuando se hace click sobre ellos se produce un comportamiento anómalo sobre la cabecera de la tabla

![image](https://user-images.githubusercontent.com/47117960/63678129-d4edaa00-c7ee-11e9-8023-463ab2e07169.png)

**Comment by JMunoz17** [comment]
Subidas las webs a PRE.

**Comment by bpesquero** [comment]
Ahora sólo sale un registro por página. 
![image](https://user-images.githubusercontent.com/20299071/64952041-8ed0b700-d87f-11e9-80f9-058537f19e1a.png)

**Comment by jlagunapkf** [comment]
Ahora debería de mostrarse correctamente @bpesquero
