### ISSUE TITLE
Incidencias Abonos por calidad de suministro. Nueva incidencia?

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#601]
Hay que ver con Mónica si se tata de una incidencia nueva o si es una revisión de las que ya hemos cerrado:

ENDESA - Abonos por calidad de suministro #537
Factura por abono de calidad de suministro #334

**Comment by bpesquero** [comment]
Son temas recuerrentes de la incidencia  #334.
Cerramos esta incidencia y reabrimos la  #334

**Comment by dgarciageo** [comment]
Ok perfecto



*De:* bpesquero <notifications@github.com>
*Enviado el:* lunes, 2 de septiembre de 2019 14:25
*Para:* PKFEric/webProxima <webProxima@noreply.github.com>
*CC:* dgarciageo <dgarcia@geoatlanter.com>; Assign <
assign@noreply.github.com>
*Asunto:* Re: [PKFEric/webProxima] Incidencias Abonos por calidad de
suministro. Nueva incidencia? (#601)



Son temas recuerrentes de la incidencia #334
<https://github.com/PKFEric/webProxima/issues/334>.
Cerramos esta incidencia y reabrimos la #334
<https://github.com/PKFEric/webProxima/issues/334>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/PKFEric/webProxima/issues/601?email_source=notifications&email_token=ALHPNCGIOZTBYHY2ARIBWUDQHUAYZA5CNFSM4IQ4Y6O2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5VVQUY#issuecomment-527128659>,
or mute the thread
