### ISSUE TITLE
Incidencia aplicación Perfil Usuario

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#602]
Hemos detectado que para el contrato HECEN/09070 se ha aplicado erróneamente el perfil de usuario para el mes de diciembre de 2018.
El punto recibe tres medidas de cierre.
El 04/01/2019 se facturan 148kWh que se abonan el día 04/04/2019. El mismo día del abono se recibe un cierre de 528kWh.
Tanto para la medida de 148kWh como en la medida final de 528kWh están procesados los correspondientes ficheros F5D.
Teniendo ya medidas horarias completas y correctas, ¿por qué se realiza el perfil de usuario y se obtiene una medida de la suma de ambos cierres?

--------- 
select cab.[CCH Access Invoice No_], cab.datasource, sum(value)
from [Hidroeléctrica El Carmen Energ$Hour Measure Header] Cab, [Hidroeléctrica El Carmen Energ$Hour Measure Line] lin
where cab.[Contract No_]  = lin.[Contract No_]
and cab.CUPS = lin.CUPS
and cab.[CCH Access Invoice No_] = lin.[CCH Access Invoice No_]
and cab.DataSource = lin.DataSource
and cab.Date = lin.Date
and lin.Magnitude = 'EE'
and cab.[Contract No_] = 'HECEN/09070'
and cab.[Date] between cast('2018-12-01' as date) and cast('2018-12-31' as date)
group by cab.[CCH Access Invoice No_],cab.datasource

**Comment by JMunoz17** [comment]
Tenemos 3 cierres, cada uno con un número de factura diferente.
![image](https://user-images.githubusercontent.com/26869276/65161052-30e6cf80-da37-11e9-99dd-fd665ae10beb.png)

Tenemos medidas horarias de dos facturas diferentes:
![image](https://user-images.githubusercontent.com/26869276/65161335-ac488100-da37-11e9-8b81-acb4fc76848e.png)

Se genera un perfil de usuario:
![image](https://user-images.githubusercontent.com/26869276/65161401-cda96d00-da37-11e9-8d6c-544db449a55d.png)

Este perfil de usuario corresponde al cierre del abono. Actualmente en el proceso de generación del perfil de usuario al buscar los cierres no filtramos por tipo factura, entiendo que la solución pasa por esto, correcto?

**Comment by bpesquero** [comment]
Correcto. La solución pasa porque sólo se perfilen los documentos tipo "factura"

**Comment by JMunoz17** [comment]
Subido a PRE y PROD. He eliminado el perfil de usuario que estaba mal.

**Comment by fmsanudo** [comment]
Correcto. Entiendo que también aplica para Geo.
Cierro la incidencia.
