### ISSUE TITLE
Problemas formatos emails de comunicaciones

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#607]
Con esta incidencia cerramos las incidencias #606 y la incidencia #599 y agrupamos todas las incidencias de envíos de email en una única incidencia

1.- Las potencias en el email de activación manual no están bien informadas, ni en Próxima ni en A tu lado
![image](https://user-images.githubusercontent.com/20299071/64167661-1b27b680-ce4a-11e9-8e9c-fc79ddd955cf.png)

2.- Cuando un cliente  da de alta el usuario web en a tu lado desde "ya soy cliente" no sale el email

3.- Vamos a introducir en el email de activación de contrato ("Ya te estamos suministrando energía") a continuación del CUPS la dirección de suministro.

4.- Cuando se proceso un fichero C_02 si el tipo de cambio es S hay que enviar el email que se envía con el paso 05.

5.- Cuando se procesa un C_06 se envía un email al cliente, hay que controlar que el caso particular de que exista un B_02 anterior no se envíe email.

6.- AL procesar un B_05 se envía un email de baja, hay que controlar que ese correo sólo salga con el motivo 01.

7.- Cuando se da de alta en segundo contrato se envía el email de bienvenida, habría que cambiar el texto para este caso

**Comment by JMunoz17** [comment]
Pregunta: Puntos 4 y 5, donde ponéis C_02 y C_06 aplica tanto a C1 como a C2? Entiendo que si pero confirmadme que es así.

**Comment by JMunoz17** [comment]
Para el punto 4, solo se envía el mail si es C_02 de aceptación no? Con tipo de cambio S os referís a Cambio de titular con subrogación no?

**Comment by JMunoz17** [comment]
Para el punto 3 pasadme el texto tal cual queréis que salga por favor.

**Comment by dgarciageo** [comment]
![image](https://user-images.githubusercontent.com/47117960/64707595-81987e80-d4b3-11e9-8471-ae9e3e586372.png)

**Comment by JMunoz17** [comment]
Puntos 4,5 y 6 subidos a PRE.

**Comment by bpesquero** [comment]
Para el punto 3

Bienvenid@ a Próxima Energía
Hola Daniel:   Ya eres cliente de   Próxima Energía, marca comercial de GeoAtlanter, SL., para tu [domicilio/empresa]   en [dirección de suministro] con Código Unificado de Punto de   Suministro [CUPS]. Te damos la bienvenida.   Nos ponemos en marcha   para poder pasar a ser tu suministrador lo antes posible. Se trata sólo de un   proceso administrativo que no requiere ningún cambio en tu instalación, por   lo que no existe riesgo de interrupción del suministro.   Cuando hayamos   terminado los trámites correspondientes recibirás un correo de confirmación   indicándote la fecha exacta del cambio. Hasta entonces, seguirás recibiendo   las facturas de tu suministrador actual. Es probable que éste te llame para   evitar el cambio. Estaremos encantados de atender todas las dudas que pudiera   suscitarte la llamada. Si se trata de comparar, eso sí, te recomendamos que   pidas la oferta por escrito para poder enfrentarla a la nuestra que, como   sabes, es pública.   Si tienes cualquier   duda, estaremos encantados de atenderte en el correo electrónico clientes@proximaenergia.com o, en   horario laboral, a través de nuestro número de teléfono gratuito 900818852.   Muchas gracias por   contar con nosotros. Trabajaremos para no defraudar tu confianza.   www.proximaenergia.com
--
Bienvenid@ a la web de A tu lado Energía
Hola Ainhoa :
Ya eres cliente de A tu Lado Energía, marca comercial de Hidroeléctrica El Carmen Energía, SL., para tu [domicilio/empresa] en [dirección de suministro] con Código Unificado de Punto de Suministro [CUPS]. Te damos la bienvenida.
Nos ponemos en marcha para poder pasar a ser tu suministrador lo antes posible. Se trata sólo de un proceso administrativo que no requiere ningún cambio en tu instalación, por lo que no existe riesgo de interrupción del suministro.
Cuando hayamos terminado los trámites correspondientes recibirás un correo de confirmación indicándote la fecha exacta del cambio. Hasta entonces, seguirás recibiendo las facturas de tu suministrador actual. Es probable que éste te llame para evitar el cambio. Estaremos encantados de atender todas las dudas que pudiera suscitarte la llamada. Si se trata de comparar, eso sí, te recomendamos que pidas la oferta por escrito para poder enfrentarla a la nuestra que, como sabes, es pública.
Si tienes cualquier duda, estaremos encantados de atenderte en el correo electrónico clientes@atuladoenergia.com o, en horario laboral, a través de nuestro número de teléfono gratuito 900264267.
Muchas gracias por contar con nosotros. Trabajaremos para no defraudar tu confianza.
www.atuladoenergia.com

**Comment by bpesquero** [comment]
EL punto 7 lo podemos obviar, Yo creo que ahora al dar la bienvenida para un punto concreto no queda tan mal,

Gracias

**Comment by JMunoz17** [comment]
Puntos 1,2 y 3 realizados. Subidas las webs a PRE.
Ahora mismo todos los puntos de esta tarea están en PRE, tanto las webs como la parte de NAV.

**Comment by bpesquero** [comment]
1,. Próxima está ok, A tu lado sigue informando mal las potencias
2.-SAle el email pero con las potencias mal informadas
3.-ok
4.-En Próxima no sale. En A tu lado no se ha probado entendiendo que tampoco saldrá
5.- OK
6.-En próxima no sale el email independientemente del tipo de motivo, por tanto es incorrecto. En A tu lado no se ha probado entendiendo que también estaría mal
7.- OK

**Comment by JMunoz17** [comment]
He estado ojeando las líneas generadas en el histórico de acciones con vuestras pruebas (las que tienen fecha hora de creación 16/09/19 12:13 y posterior):

**Para el punto 4:**
No veo ninguna línea del histórico de acciones que sea el paso C1-02 o C2-02 y que tenga Solicitud Administrativa Contractual = 'S', que son los requisitos para que se envíe el email.

**Para el punto 6:**
No veo ninguna línea del histórico de acciones que sea el paso B1-05 y que tenga Motivo de Baja = '01', que son los requisitos para que se envíe el email.

No son correctos estos requisitos? Si no llamadme y lo vemos.

**Comment by bpesquero** [comment]
AL parecer el pto 4 lo definimos mal y el problema no era con un C sino con un M


·         Para el punto 4:
No veo ninguna línea del histórico de acciones que sea el paso C1-02 o C2-02 y que tenga Solicitud Administrativa Contractual = 'S', que son los requisitos para que se envíe el email.

No se trata de un C, sino de un M con cambio de titularidad (M-tipo S –admin-o A -ambos, técnico y administrativo con cambio titularidad-). El orden es, se genera un M tipo S o A con cambio titularidad , con subrogación,  en la solicitud M_01 y luego se importa la aceptación (paso 02) que es el que genera la baja del contrato actual y la creación del nuevo a nombre del nuevo titular (no habría para el caso de subrogación paso 05 de activación como tal. Aquí es donde debería enviar el email al nuevo titular.


Histórico de acciones donde puede verlo:

GEOATLANTER PRE: COM/00705
![image](https://user-images.githubusercontent.com/20299071/64972732-1501f300-d8aa-11e9-8cfe-8aa6fa3d9672.png) 

·         Para el punto 6:
No veo ninguna línea del histórico de acciones que sea el paso B1-01 y que tenga Motivo de Baja = '01', que son los requisitos para que se envíe el email.

6.- AL procesar un B_05 se envía un email de baja, hay que controlar que ese correo sólo salga con el motivo 01.

·          Próxima:

o    He probado con dos contratos distintos,  a procesar un B_05 con motivo 02 (fin de contrato) y  no sale correo, por tanto éste sería correcto.

o    Sin embargo, al tratar de hacerlo con un B_05 motivo 01 (cese de actividad), por ejemplo con el COM/01253,  que es con el que sí tiene que salir, tampoco lo ha hecho.



Si se va al contrato COM/01253 puede verlo:

![image](https://user-images.githubusercontent.com/20299071/64972676-f996e800-d8a9-11e9-9443-52436f3cbfa7.png)
![image](https://user-images.githubusercontent.com/20299071/64972690-fe5b9c00-d8a9-11e9-8050-7037ec452b8c.png)

**Comment by JMunoz17** [comment]
Ok, entonces el primer punto lo hacemos así.

El segundo punto el problema es que estaba consultando el motivo de baja en el histórico de acciones y donde lo tenemos relleno es en el contrato, lo consulto de ahí y solucionado.

Os aviso cuando este.

**Comment by jlagunapkf** [comment]
En el punto 2

Este es el resultado que obtengo yo, podrías mostrarme cual es el email que recibes @bpesquero ?
![image](https://user-images.githubusercontent.com/40607175/65023758-cef17180-d933-11e9-8ec5-76227397cebf.png)

**Comment by jlagunapkf** [comment]
Y para el punto número 1. Ocurre le mismo, el email que recibo informa correctamente de las potencias.

**Comment by JMunoz17** [comment]
Puntos 4 y 6 modificados y subidos a PRE.

**Comment by bpesquero** [comment]
Probador y correcto
Subir a PRO

**Comment by JMunoz17** [comment]
Subido a PROD, tanto la parte de NAV como los webs.

**Comment by bpesquero** [comment]
Volvemos al punto 1. Sigue saliendo mal en A tu lado

![image](https://user-images.githubusercontent.com/20299071/65596513-4f008280-df97-11e9-9607-2b8ca9e5081b.png)

**Comment by PKFEric** [comment]
El problema era desde los mails de activacion que se envian desde la zona de administracion. Ya esta corregido.

**Comment by bpesquero** [comment]
Volvemos al punto 1, sigue sin estar bien. Por cierto, en el punto 1 se explica la casuísitca:
"1.- Las potencias en el email de activación manual no están bien informadas, ni en Próxima ni en A tu lado"

Lo que ocurre ahora

En el envío del email del enlace de activación manual (cuando creo yo por detrás el cliente web de Próxima), sigue saliendo mal la potencia del suministro. Ahora no sale -1kW pero sí que se informan otros dos periodos de potencia a 0kW.

Ejemplo del COM/01686 

 
![image](https://user-images.githubusercontent.com/20299071/66566084-59f50e80-eb64-11e9-91b8-586182cc67f9.png)

Hola TERESA:

Bienvenid@ a Próxima Energí­a.

Has contratado con nosotros el suministro de energía eléctrica en la modalidad de Tarifa Cristalina para tu domicilio en Avenida Salvador de Madariaga 79 1-E CORUÑA (A) con Código Unificado de Punto de Suministro ES0022000008365555MM y las siguientes potencias contratadas 3,45 kW 0 kW 0 kW .

Para activar tu cuenta de usuario pulsa sobre el siguiente enlace.

Activación

Si tienes cualquier duda, estaremos encantados de atenderte en el correo electrónico clientes@proximaenergia.com o, en horario laboral, a través de nuestro número de teléfono gratuito 900818852

Bienvenido a nuestra gran familia.
--




 
--
