### ISSUE TITLE
Cambio en el funcionamiento de aplicación de fechas de la tabla de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#608]
Hay que tener en cuenta lo siguientes,
el cliente comienza a pagar cuotas de renting desde el día de la puesta en servicio. EL cliente comienza a cobrar los excedentes desde la fecha de activación por parte del distribuidor. Por tanto:

-la fecha de inicio de vigor del contrato de autoconsumo debiera coincidir con la fecha de puesta en marcha. Quizá no tiene sentido tener dos campos.
-Deberíamos tener una segunda fecha (se puede reutilizar el campo de fecha de puesta en marcha) con la fecha de activación, que es la que marca que se vayan a facturar el resto de conceptos.

**Comment by JMunoz17** [comment]
Subido a PRE.

**Comment by bpesquero** [comment]
Hemos probado algo, pero no todo.
Subimos a PRO directamente. como afecta a muy pocos clientes y es un proceso que controlamos nosotros lo probamos en real.

**Comment by JMunoz17** [comment]
Subido a PROD.

**Comment by bpesquero** [comment]
Hemos estado probando  el alta de fichas de contrato y demás funciona bien, con excepción de que al replicar la cabecera de autoconsumo no se copian los datos de duración del renting ni tipo de interés, si intentas cambiarlos a mano, da un error.

**Comment by JMunoz17** [comment]
He probado esto de nuevo y lo que veo es que si que se traspasan estos datos de una cabecera a otra, realmente traspasamos todos los datos menos las fechas de vigencia. Probad de nuevo y me dejáis en PRE un ejemplo de como os pasa.

**Comment by bpesquero** [comment]
Contrato | Ficha AUTO | Tipo Auto | Algoritmo | Cod serie financiación | Financiación desde
-- | -- | -- | -- | -- | --
COM/00916 | AUT00077 | 00 | F | FINAN/00002 | 24/05/2019
  | AUT00078 | 51 | NF | FINAN/00002 | 13/08/2019

PASOS:

 

1)      Creo una ficha AUT00077 con tipo autoconsumo 00 en la ficha, y algoritmo F de fecha inicio=fecha conexión.

2)     Simulo que me llega el M_05, a fecha activación 13/08, doy de baja la ficha de autoconsumo AUT00077  a fecha 12/08 y  replico la ficha, ya con la fecha del M_05 . Aquí aparece la nueva ficha AUT00078 con el mismo tipo de autoconsumo 00 y algoritmo, pero cuando lo voy a cambiar a  tipo 51 Y algoritmo NF se quitan los campos de duración del renting y tipo de interés.

3)      Al intentar introducirlos, a mano me aparece el siguiente error (pantallazo de abajo)  y me obliga a cerrar. Luego se restablece el tipo de autoconsumo como 00 y algoritmo a F.

 

He de decir, que previamente en la pestaña OCSUM del contrato, he cambiado al tipo autoconsumo 51 desde el principio a mano,  para tenerlo en cuenta, ya que por defecto cuando he creado la primera ficha de autoconsumo tipo 00 Algoritmo F, se cambia automáticamente a tipo 00 ( es lo que hablamos Belén que podíamos editar para luego la carga del D/M). Ya me dices si tiene algo que ver.

![image](https://user-images.githubusercontent.com/20299071/65611314-ec1ce480-dfb2-11e9-81c2-6642e448a316.png)

**Comment by JMunoz17** [comment]
Ok, perfectamente explicado.

Lo que he hecho es pediros confirmación al validar el tipo de autoconsumo mediante el siguiente mensaje:
![image](https://user-images.githubusercontent.com/26869276/65613888-f9d46900-dfb6-11e9-9d2f-66b9d5477b11.png)
De esta manera no se modificarán los campos de duración de renting y tipo de interés anual.

Si veis alguna cosilla mas de estás me vais diciendo.

Subido a PRE y PROD.

**Comment by bpesquero** [comment]
Probado y ok
