### ISSUE TITLE
Error carga fichero F1 de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#610]
nos está dando error la carga de dos ficheros F1, creo que el problema viene precisamente por el control de cuando hay que empezar a facturar y hacer los controles. Relacionado con la incidencia de incluir dos fechas diferentes en el autoconsumo.

**Comment by bpesquero** [comment]
AL cargar los ficheros F1 estamos encontrando lo siguiente:

1.- Contrato con ficha de autoconsumo con algoritmo F--> al cargar el F1 dice que para esa fecha existe un contrato de autonconsumo  y que el F1 tiene tipo de autoconsumo 00--> Hay que validar, no sólo que tenga ficha de autoconsumo, si no también el tipo de autoconsumo que tiene, porque en este caso es correcto

2.- Contrato con ficha de autoconsumo con algoritmo F-->EStamos cargando una factura tipo "C" y da error de que no está implementado. Efectivamente, pero realmente para las facturas que tengan tipo F creo que si podríamos hacerlo de forma sencilla, no?

**Comment by JMunoz17** [comment]
1 - He modificado el control para que no aplique si el algoritmo de autoconsumo es F, debería de cargaros ya.

2 - Para este caso no identifico bien donde os salta el control, al cargar el F1 o al generar la factura de venta? Si me puedes indicar cual es el F1/FV para verlo mejor.

**Comment by bpesquero** [comment]
1.- Ok. Probamos
2.- El control salta al cargar el F1 y ver que el tipo de factura no es "N". lo hicimos así para no meternos en el lío de las rectificativas.  En este caso en concreto además el algoritmo de facturación de autoconusmo es F, así que igual hay que controlar esto al verificar si es N o no, y así de momento tiramos con lo que tenemos.

**Comment by JMunoz17** [comment]
Ok, este control se produce siempre que el contrato esta marcado como autoconsumo. Lo que hecho es saltarme tanto el control del tipo de factura como el control de que existan medidas F5D en caso de que algoritmo de autoconsumo sea F. Os lo he subido a PRE y PROD.

**Comment by bpesquero** [comment]
como el control de que existan medidas F5D en caso de que algoritmo de autoconsumo sea F

¿este por qué?

**Comment by JMunoz17** [comment]
Antes, cuando importamos un F1 si el contrato tenia el check de autoconsumo se realizaban dos controles:
1 - Tipo factura debe ser 'N'.
2 - Deben existir medidas F5D asociadas al número de factura del F1.

Lo que he hecho es que si existe un contrato de autoconsumo vigente en las fechas de la factura y es F entonces estos controles no se producirán.

Ahora mi pregunta es: puede venir un F1 con Tipo de factura 'N' y algoritmo de autoconsumo diferente de F?

**Comment by bpesquero** [comment]
1 Con respecto al control del F5D entiendo que en este caso se sigue haciendo el control de que si la factura está informada como  que tiene medidas horarias se busca que haya F5D, verdad?

2.- Si claro, la factura N es la factura "normal" que no es ni rectificativa ni complementaria ni regularizadora, esto no tiene nada que ver con el algoritmo de cálculo. Lo que ocurre es que como no tuvimos tiempo de desarrollarlo lo capamos a aceptar sólo las N para el caso de autoconsumo. Lo que digo es que como el caso de algoritmo de autoconsumo F es equivalente en la práctica a no tener autoconsumo, podemos funcionar con las regularizadoras, rectificativas y demás como un caso normal.

**Comment by JMunoz17** [comment]
Ok, así lo hacemos, te lo resumo para asegurarnos que estamos entendiendo lo mismo:

Si el contrato es de autoconsumo:

  - Si tipo factura 'N' -> Hacemos el control de los F5D independientemente de cual se el algoritmo de autoconsumo.

  - Si tipo factura <> 'N' -> Si existe un contrato de autoconsumo vigente para las fechas de la factura y es F, continua y no se hace el control de los F5D. En caso contrato error.

**Comment by bpesquero** [comment]
Insisto, en el segundo caso independientemente si el fichero F1 informa de que existe curva de carga hay que verificar que existe F5D como se hace con todas las facturas, aunque no tengan autoconsumo

**Comment by JMunoz17** [comment]
Ok, ya esta modificado.

**Comment by bpesquero** [comment]
Al cargar una factura de tipo C con algoritmo de autoconsumo F está dando error de que no encuentra F5D
SCTDE_F1_01_0022_0587_20190913080156344_(799293570) (autoconsumo).xml

**Comment by bpesquero** [comment]
Más problemas que estamos teniendo

1.-Existen contratos que aún no tiene autoconsumo activado (ficha de autoconsumo vigente) pero en el F5D el distribuidor nos envía la energía saliente, Al hacer el control de que la energía. DA el siguiente error

Error XML, excedentes del F1: 0 no coincide con la ES de las medidas F5D: 296,366 para el contrato: COM/01200 y Nº factura acceso: 03190816030288583

2.- Cuando tenemos un autoconsumo no gestionado por nosotros, no tiene ficha de autoconsumo, sin embargo está marcado el check de autoconsumo, habría que hacer la comprobación que se hacía antes del saldo neto para poder validar los cierres. Ahora está dando el error

Error XML, excedentes del F1: 0 no coincide con la ES de las medidas F5D: 198,694 para el contrato: COM/00293 y Nº factura acceso: 03190829030306381.

En general creo que procede revisar los controles que tenemos. Habría que hacer un pequeño documento y revisarlo para estar seguros de que estamos haciendo todo bien

**Comment by PKFEric** [comment]
1.-Existen contratos que aún no tiene autoconsumo activado (ficha de autoconsumo vigente) pero en el F5D el distribuidor nos envía la energía saliente, Al hacer el control de que la energía. DA el siguiente error

Error XML, excedentes del F1: 0 no coincide con la ES de las medidas F5D: 296,366 para el contrato: COM/01200 y Nº factura acceso: 03190816030288583

 **Como hemos comentado los contratos que tengan autoconsumo pero no sea gestionado por geoatlanter no deberan llevar marcado el check de autoconsumo, sino que en la ficha del contrato, en el campo Tipo Autoconsumo debera venir informado el codigo correspondiente de autoconsumo.**

2.- Cuando tenemos un autoconsumo no gestionado por nosotros, no tiene ficha de autoconsumo, sin embargo está marcado el check de autoconsumo, habría que hacer la comprobación que se hacía antes del saldo neto para poder validar los cierres. Ahora está dando el error

Error XML, excedentes del F1: 0 no coincide con la ES de las medidas F5D: 198,694 para el contrato: COM/00293 y Nº factura acceso: 03190829030306381.

**La ultima funcion del documento hace exactamente lo que solicitas par aquellos contratos que comentas. Entiendo que esto tendra mas implicaciones de otros controles que tengamos en la facturacion de venta que habra que cambiar.**

En general creo que procede revisar los controles que tenemos. Habría que hacer un pequeño documento y revisarlo para estar seguros de que estamos haciendo todo bien

**Documento enviado por correo**

**Comment by bpesquero** [comment]
Probado y ok

**Comment by dgarciageo** [comment]
El documento está en:

\\alfa\datos\Publica\Aplicacion suministro\NAVISION\NAV - Autoconsumo
