### ISSUE TITLE
Error F1 HECEN/09475 (ES0031102021406001SK)

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#611]
AL cargar el F1 da error 
![image](https://user-images.githubusercontent.com/20299071/64317384-d6ba2900-cfb7-11e9-86b7-d17cbcee75df.png)

Se trata de una factura regularizadora que regulariza dos facturas anteriores. Al hacer la comprobación sólo esta sumando en el acumulado una de ellas.

**Comment by JMunoz17** [comment]
Para la distribuidora 0031 (Endesa) tenemos +1D como formula fecha inicio factura.

La "Fecha Desde" del termino de energía es 25/04/19, a la cual la sumamos un día, lo que impide que se tengan en cuenta los datos de los peajes correspondientes a la factura H/2019028156, que tienen como "Fecha Desde" 25/04/19.

![image](https://user-images.githubusercontent.com/26869276/64607518-f2af3780-d3c8-11e9-93af-32b54b950bdc.png)

Tenemos mal configurado el +1D o viene mal la fecha en el fichero?

**Comment by bpesquero** [comment]
Cuando te refieres a peaje  te refieres al cierre informado en el F1?
TAmbién habría que sumarle un día, asi está en la configuración.

**Comment by JMunoz17** [comment]
Yo creo que el problema es que o bien en este F1 o en el primer F1 que regulariza (20190527-Endesa (3).xml) la Fecha Desde viene mal informada ya que el +1D de la configuración lo hemos aplicado bien en ambos casos.

En este F1 el término de energía activa tiene fecha desde = 2019-04-25. A esta fecha le sumamos un día, por lo que la fecha desde de sus peajes en NAV es 2019-04-26.

En el F1 20190527-Endesa (3).xml el término de energía activa tiene fecha desde = 2019-04-24. A esta fecha le sumamos un día, por lo que la fecha desde de sus peajes en NAV es 2019-04-25.

Al calcular el acumulado de los peajes para compararlo con los cierres se utiliza la fecha desde del término de energía activa que viene en el F1 (en este caso 2019-04-25 + 1D), por lo que no se acumulan los datos del F1 20190527-Endesa (3).xml ya que estos tienen una fecha desde anterior (2019-04-24 + 1D).

**Comment by bpesquero** [comment]
Ok. Reclamamos a la distribuidora.
