### ISSUE TITLE
Error facturación suplementos territoriales

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#614]
AL cargar unos F1 con suplementos territoriales no se facturan en la factura de compra

COM/00695 | No está considerando en el F1 los suplementos territoriales
-- | --
COM/01575 | No está considerando en el F1 los suplementos territoriales
COM/01209 | No está considerando en el F1 los suplementos territoriales
COM/01207 | No está considerando en el F1 los suplementos territoriales

**Comment by JMunoz17** [comment]
Modificado y subido a PRE y PROD, ya os debe funcionar correctamente.
Efectivamente esta tarea entra dentro del proyecto cerrado de modificaciones relacionadas con el switching.

**Comment by bpesquero** [comment]
Se calcula bien la factura de venta ya la factura de compra, sin embargo la factura de venta no queda asociada al peaje.
Ejemplo:

Empresa:Hidroeléctrica 
FActura de venta : FV/2019057329

**Comment by JMunoz17** [comment]
Hemos subido la modificación tanto a PRE como a PROD. Hay que volver a importar el F1 para probarlo, no he querido hacerlo porque esta Mónica con la facturación.

**Comment by JMunoz17** [comment]
Ya os la he regenerado.

**Comment by bpesquero** [comment]
Probado y ok
