### ISSUE TITLE
Problema facturación término de potencia

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#615]
Se factura mal el P1 del término de potencia
COM/00581 y COM/00749

**Comment by JMunoz17** [comment]
Tanto esta tarea como la #528 necesito comentarlas contigo, cuando tengas un rato dame un toque.

**Comment by PKFEric** [comment]
Ya esta solucionado, estan sacadas las dos facturas en prefactura.

Era por que el periodo 4 tenia procedencia de medida en potencia 99

**Comment by bpesquero** [comment]
Probado y ok
