### ISSUE TITLE
Insertar provincia en histórico de acciones

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#628]
Mostrar en histórico de acciones la provincia.

**Comment by JMunoz17** [comment]
Os he sacado en la lista de histórico de acciones el campo Provincia Suministro. Tenemos otro que es Cód. Provincia, pero entiendo que no es el que necesitáis. De lo contrario me decís.

**Comment by bpesquero** [comment]
Probado y ok

**Comment by dgarciageo** [comment]
Lo que estamos viendo en el histórico de acciones es la provincia del titular y no la provincia de suministro

**Comment by JMunoz17** [comment]
El campo "Provincia Suministro" del Histórico de acciones estaba tomando su valor del campo "Provincia" del contrato. Lo hemos modificado para que lo tome del campo "Provincia Suministro" del contrato.

Subido a PRE y PROD. 
Hemos pasado un proceso para arreglar los datos tanto en GEO como en HECEN.

**Comment by bpesquero** [comment]
Probado y ok
