### ISSUE TITLE
WEB - Desarrollar la parte de ACSM en la web (Importes IRPF deben ser acumulados)

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#629]

**Comment by PKFEric** [comment]
Ya esta subida a pro la parte de la web.

Queda pendiente la parte de :

"En el área de cliente, la funcionalidad de descargar detalle de la factura debe descargar un Excel similar al actual, pero incluyendo una pestaña adicional donde aparezca el detalle de cálculo de la valoración de la energía excedentaria vertida a la red."

Te comente que habia un campo en el que salia la energia excedentaria. Y me dijiste que ibas a reestructurar la informacion que salia con una columna en medio del CSV para dividir la parte de Autoconsumo. 

Me mandaste un mail muy raro que no entendi:

a)      En el área de cliente, la funcionalidad de descargar detalle de la factura debe descargar un Excel similar al actual, pero incluyendo una pestaña adicional donde aparezca el detalle de cálculo horario de la valoración de la energía excedentaria vertida a la red.
Yo entiendo que la información para hacer la valoración de la energía excedentaria vertida a red es basicamente la energía saliente del F5D y el precio de mercado diario

**Comment by bpesquero** [comment]
TE envío un excel de ejemplo por mail
Si, la energía excedentaria es la saliente del F5D, la que hayamos utilizado nosotros para el calculo de l factura.

**Comment by bpesquero** [comment]
Sigue pendiente, hay algún problema con esto o está claro lo que hay que hacer?

**Comment by bpesquero** [comment]
He vuelto a probar y en el detalle de la factura sigo sin ver la parte de energía excedentaria. 

Además no veo los informes de IVA e IRPF- ¿Dónde están?¿No los veo porque sale sólo en NC? Si es así, no lo puedo probar porque no tenemos ninguna factura todavía en esta situación.
En cualquier caso, hay que hacer alguna modificación en estos informes, estuve ayer hablando con la asesoría, modifico el Word de especificaciones y os lo envío.

**Comment by bpesquero** [comment]
Enviado el documento. La modificación se refiere a qué facturas forman parte del informe

OJO: las facturas a considerar serán aquellas que cumplan el criterio del filtro y que tengan energía facturada posterior a la fecha de inicio de vigencia de la primera ficha de autoconsumo que tenga asociada el contrato con modalidad NC.

**Comment by PKFEric** [comment]
Ya sale correcto.

**Comment by bpesquero** [comment]
Devuelvo la tarea a este estado, ya que consultado con Agecia tributaria he visto que los importes de IRPF deben ser acumulados desde principio de año, por tanto, para el informe de IRPF las facturas mostradas en cada caso se corresponderán con todas las facutras recibidas desde el primer día del año y el último día del periodo seleccionado (1T, 2T,3T y 4T)

**Comment by bpesquero** [comment]
Hemos dado una vuelta a estos informes y necesitamos que incluyan
-facturas de mantenimiento: deben incluirse tanto en los informes de IVA como de IRPF. PAra localizarlas se hará a través de la dimensión cod_proyecto y sabiendo que la serie de facturación es MANT/
-facturas de inversión inicial: deben incluirse en la cabecera de los informes de IVA, pero no forman parte del listado ni de la suma totalizadora. Se indicará la fecha,la BI y el IVA. PAra localizarlas se hará a través de la dimensión cod_proyecto y sabiendo que la serie de facturación es AUT/

**Comment by jorgereal** [comment]
Se han corregido los informes y se han subido a PROD.

**Comment by bpesquero** [comment]
REvisados los informes. 
He detectado que se listan las facturas independientemente de que estén abonadas o no. Se trata de informes de IVA e IRPF al no listar los abonos hay que tener en cuenta que sólo se pueden listar las facturas no abonadas.
