### ISSUE TITLE
Fichero M con Milenial

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#630]
si un contrato que tiene la tarifa 96 (MILENIAL) y quiere cambiarse a una nocturna 59…como ya tiene la DH no implica un cambio técnico ni gestión con la distribuidora, pero se sigue generando un M de forma automática desde NAVSERVICE en histórico de acciones . En este caso, debería cambiar la tarifa sólo en el contrato actualizando precios (salvo que aprovechen a hacer un cambio de potencia, para lo cual si procedería un M con tramitación técnica).

**Comment by bpesquero** [comment]
ESto sigue mal.
el pasado 08 de octubre (este martes) nos entró una solicitud de cambio de tarifa MILENIAL a tarifa NOCTURNA para el HECEN/09673 . Esta solicitud generó un M en el histórico, pero no hizo nada de actualización de precios ni cambio de tarifa en el contrato. De hecho , fui yo la que a mano cambié la tarifa de la 96 a la 59 y actualicé precios desde el 01/10 y lo apunté en comentarios.

 

De: Clientes Hidroeléctrica El Carmen Energía [mailto:clientes@atuladoenergia.com]
Enviado el: martes, 8 de octubre de 2019 19:46
Para: jorge.laguna@pkf-attest.es; efernandez@pkf-attest.es; agalindez@geoatlanter.com; dgarcia@geoatlanter.com
Asunto: Cambio de tarifa A tu lado Energía del contrato HECEN/09673

 

Cambio de tarifa del contrato HECEN/09673 Datos de cliente que solicita el cambio de tarifa: Nombre: CESAR Apellido 1: BALDOMINOS Apellido 2: SANZ E-Mail: cesarbaldominossanz@gmail.com NIF/CIF: 03088671R Telefono: 618047149 Peaje: 2.0DHA Potencia del periodo 1: 3,3 kW Potencia del periodo 2: 0 kW Potencia del periodo 3: 0 kW

**Comment by PKFEric** [comment]
Ya esta hecha la modificacion, ahora deberia de modificar el tipo de contrato en nav automaticamente si pasa de milenial a 20dha o de milenial +10 a 21dha o de 20dha a milenial o de 21dha a milenial +10

**Comment by bpesquero** [comment]
No hace nada. Te indico lo que he hecho: he cambiado el contrato HECEN/05844 (GEOATLANTER)  a MILENIAL 96  a mano, actualizando precios a 01/10/2019, porque teníamos una 58. Luego he solicitado desde nuestro área de cliente el cambio a nocturna y ha salido bien el correo, pero no ha cambiado nada en NAV. Además, hay que tener en cuenta que no es  ólo el cambio de tarifa como tal sino que además debe actualizar precios.

**Comment by PKFEric** [comment]
Ya esta lo he probado con el contrato que me comentas y lo va pasando de milenial a 20dha y vicecersa y ya esta incluida tambien la parte de los precios, he visto que los genera tambien.
