### ISSUE TITLE
COM/00604 - FC/20199864 - FV/201909951

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#631]
La FC es una factura de compra con consmo calculado 0 y con pérdidas. El distribuidor no está facturando las pérdidas en la FC (debería hacerlo) y NAV no está sacando tampoco las pérdidas en la FV, ¿por qué?

**Comment by PKFEric** [comment]
Este contrato no tiene medidas. F5D y en el cierre no viene energia. Entonces si no se puede perfilar y no se pueden usar las medidas. En base solo a perdidas no tenemos hecho nada para que calcule la energia.

**Comment by bpesquero** [comment]
Ok. Lo dejamos asi.
