### ISSUE TITLE
Problema código amigo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#632]
Tenemos un nuevo caso de un cliente que se ha dado de alta con el código amigo de otro cliente, y no aparece en ninguna de las dos fichas el saldo.

COM/01134 - CL00978- Código: AMIGOABBDE
Cliente nuevo : COM/01634 - CL01333

**Comment by PKFEric** [comment]
Este tema lo gensionamos con dani en su momento, me acabo de crear un contrato de prueba, con ese codigo y en NAV y en WEB aparece el saldo amigo en los dos contratos en el que he creado y en el 1134. Esto ya esta solucionado. 

Entonces quieres que le meta saldo amigo a estos 2 contratos??

**Comment by bpesquero** [comment]
SI, por favor


*Síguenos en:*[image: Facebook pequeño]
<https://www.facebook.com/proximaenergia/>[image: Twitter pequeño]
<https://twitter.com/proximaenergia?lang=es>[image: Google+pequeñito]
<https://plus.google.com/114547235710296874519>

*AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener información
*confidencial *sometida a secreto profesional. No está permitida su
reproducción o distribución sin la autorización expresa de *GEOATLANTER SL.*

Si usted no es el destinatario final por favor elimínelo e infórmenos por
esta vía.



De acuerdo con lo establecido por el Reglamento General de Protección de
Datos (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de
2016, le informamos que sus datos serán tratados con la finalidad de
realizar la gestión administrativa, contable y fiscal, así como el envío de
comunicaciones comerciales  sobre nuestros servicios y/o productos.


Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, oposición, supresión, limitación y portabilidad de
sus datos en el domicilio de *GEOATLANTER SL *sito en: Avda de Europa 34B
<https://maps.google.com/?q=Avda+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha 3º,  28023 Madrid o enviando un correo electrónico a la siguiente
dirección : *contacto@geoatlanter.com <contacto@geoatlanter.com>*

Si usted no desea recibir nuestra información, póngase en contacto con
nosotros enviando un correo electrónico a la dirección:
*contacto@geoatlanter.com
<contacto@geoatlanter.com>*

**Comment by PKFEric** [comment]
Ya esta para esos dos contratos la linea de campaña amigo

**Comment by bpesquero** [comment]
Probado y ok
