### ISSUE TITLE
Facturación REGANECU extrapeninsular

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#633]
Se trata de cargar y facturar los reganecus de Baleares y Canarias. Habrá que identificar en la tabla de reganecu y a la hora de facturar si se tata de peninsular, BAleares o Canarias.
Por lo demás el proceso de facturación es idéntico al peninsular.

**Comment by bpesquero** [comment]
Para identificar el origen:

- el nombre del fichero es diferente
- la unidad de programación identificada en el fichero es diferente

**Comment by PKFEric** [comment]
Envianos o dejanos en una carpeta del servidor el Fichero de Reganecu de Canarias y de Baleares por favor

**Comment by JMunoz17** [comment]
Quereés que marquemos la cabecera de las facturas de venta/compra con el tipo de origen Península/Baleares/Canarias o solo que este dato aparezca en la tabla de Reganecu?

**Comment by bpesquero** [comment]
Lo ideal es que aparezca en la cabecera de la factura.
Incluso en el texto de registro. Ayuda a localizarlas de forma rápida

**Comment by JMunoz17** [comment]
Subido a PRE.
Echadle un ojo y me decís con cualquier cosa. 
Recordad revisar la configuración de Reganecu antes de facturar.

**Comment by bpesquero** [comment]
REvisado. EL problema es que no se diferencia en la tabla de configuracion entre Baleares y Canarias. Es necesario ya que los productos de Baleares y Canarias no pueden estar configurados de la misma manera, unos llevan IVA y otros GIC.

Es por ello que comenté que para saber el origen había que obtenerlo del nombre.

gracias

**Comment by JMunoz17** [comment]
Hemos añadido el campo origen a la tabla de configuración de reganecu y lo hemos incluido en la clave.
Lo tenéis en PRE.

**Comment by bpesquero** [comment]
Configurado en PRE y probado y ok.
Subir a PRO

**Comment by JMunoz17** [comment]
Subido a PRO.

**Comment by bpesquero** [comment]
Probado y ok.

TEnemos forma de "meter" el histórico para que cuando nos llegue una C3, C4, C5 de un periodo en el que la versión anterior se metió  a mano nos haga el cálculo de la factura por diferencias?

**Comment by JMunoz17** [comment]
Pues hay que cargar los ficheros anteriores (para eso nos serviría el proceso de carga tal cual) y luego marcar esas líneas de la tabla **Reganecu Entry (55025)** con el check de facturadas y asociarlas a las   facturas/abonos de venta/compra que les correspondan (tanto pre-fact/abo como fact/abo registrado).

Existe alguna posibilidad de haciendo nosotros un proceso poder identificar para cada línea de la tabla Reganecu Entry que carguemos cual es la factura/abono que le corresponde? En ese caso lo podríamos hacer con un proceso.
