### ISSUE TITLE
Cálculo perfil erróneo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#635]
| Fecha | Fecha Ini | Fecha Fin | Total
-- | -- | -- | -- | --
Cierre 1 | 23/01/2019 | 01/12/2018 | 18/01/2019 | 1352
Cierre 2 | 22/03/2019 | 14/07/2018 | 22/03/2019 | 21002

**Comment by PKFEric** [comment]
Pasame el contrato al que aplica esto.

**Comment by bpesquero** [comment]
COM/00589

**Comment by PKFEric** [comment]
Yo por lo que veo los dos perfiles de usuario que hay estan bien. Le paso el excel a Fernando.

**Comment by JMunoz17** [comment]
Revisado con Fernando vía mail.

**Comment by fmsanudo** [comment]
Se mantienen los dos cierres perfilados en la tabla.
Se ha corregido informe de medidas en el que aparecía la duplicidad.
Las comprobaciones sobre la aplicación del perfil de usuario a estos cierres no ha revelado una aplicación incorrecta de los mismos.
Se cierra la incidencia.
