### ISSUE TITLE
Modificación de comprobaciones carga F1 - autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#637]
Nos llega la primera factura y probamos con la carga del F5 y F1.
Se añade un nuevo control:

-la diferencia entre AE y AS del cierre, coincide con la diferencia entre energía importada y exportada para cada periodo.

**Comment by bpesquero** [comment]
Probamos con el contrato COM/00575

Comentarios a la prefactura de venta

- tasas e impuestos no puede ser negativo, si es así tiene que ser 0

**Comment by bpesquero** [comment]
Hemos visto que al hacer este control no redondea adecuadamente y salta el log y no carga el fichero

**Comment by bpesquero** [comment]
Problemas con la facturación de autoconsumo
Error XML, excedentes del F1: 0 no coincide con la ES de las medidas F5D: 198,694 para el contrato: COM/00293 y Nº factura acceso: 03190829030306381.

En general creo que proceder revisar los controles, hacer un pequeño documento, para revisar que esté todo ok.

**Comment by bpesquero** [comment]
La solución del problema de redondeo pasa por redondear por periodos la energia importada y exportada del F5D, sin embargo comenta Eric que es algo complicado, para darle una solucion rápida decidimos insertar una tolerancia de 1 kWh.

**Comment by PKFEric** [comment]
Se ha modificado el control para que tenga un margen de 1Kwh

**Comment by PKFEric** [comment]
Se ha modificado el calculo de las tasas para que si es negativo ponga 0

**Comment by bpesquero** [comment]
Probado y ok
