### ISSUE TITLE
Alta automática de fichas de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#638]
Nav tendrá un proceso que ejecuta una vista desarrollada en  la BBDD SQL de Autonconsumo gestionada por Geo y da de alta automática las fichas de autoconsumo-

**Comment by bpesquero** [comment]
El PA está en Tau en la BBDD ACSM
EL nombre del PA es [PA_FichaAutoconsumoNAV]
El PA devolverá la información de todos los proyectos conectados. Desde NAV se seleccionaran para importar y crear la correspondiente ficha de autoconsumo aquellos que no tengan una ficha previa.
Cada proyecto en la BBDD ACSM tiene un id. ESte id se está registrando en NAV a través de la dimensión global 3 (Cod Proyecto). Por tanto, para buscar si existe ficha de autoconsumo en NAV para un determinado proyecto lo más cómodo será buscar a través de este idenficador.

El PA devuelve los siguientes campos:


Salida PA | Campo de Navision
-- | --
id | Shortcut Dimension 3 Code
CUPS | CUPS
fecha_inicio | Fecha Inicio Vigencia
% financiación | % financiación
algoritmo | Algoritmo de Autoconsumo
tipo_autoconsumo | Tipo Autoconsumo Contrato
potencia_pico | Potencia Pico
potencia_instalacion | Potencia Instalación
fecha_revision | Fecha Proxima Revisión Pot.
fecha_puesta_marcha | Fecha puesta en marcha
duracion_renting | Duración de Renting (Años)
tipo_interes | Tipo de Interés Anual %
inversion | Coste Total
porcentaje_financiacion | % Financiacion
mantenimiento | Precio prod. mant. anual
seguro | Precio prod. seguro anual
tramitacion | Campo nuevo

El campo tramitación es un campo nuevo que se necesita en la ficha de autoconsumo que puede tomar los siguientes valores

0- No tramitar
1- Sólo representación
2-tramitar

**Comment by JMunoz17** [comment]
Subido a PRE. Contestado via mail.

**Comment by bpesquero** [comment]
De momento lo que hemos probado va ok,  la única cosa es que no se genera la financiación. ¿sería posible incluirlo?

**Comment by bpesquero** [comment]
1.-¿Qué criterio se sigue para asociar cuando hay dos contratos con el mismo número de proyecto? Se están asignando a fichas dadas de baja
2.-Cuando es NC rellena en cabecera los datos como si tuviera financiación (ejemplo COM/00038)
3.-La financiación no está bien calculada. Ejemplo COM/01377, la cuota debería ser de 1,40€.
Alguna mejora
 1.-Añadir dimensión 3 a ficha de autoconsumo
2.-Log de fichas no creadas por error
3.-Log de fichas no creadas por no encontrar proyecto

**Comment by bpesquero** [comment]
Punto 1 (contrato asociado) y punto 3 (financiación) solucionado
