### ISSUE TITLE
Productos de mantenimiento y seguro autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#639]
Se necesita una solución que permita asignar diferentes tarifas a diferentes contratos. En algunos casos (los menos) el contrato no se rige por una tarifa estándar si no que tiene un precio particular (tipicamente en instalaciones de gran potencia)

Además de forma periódica se actualizaran las tarifas y habría que propagar esa actualización a la tabla de detalle de autoconsumo de cada contrato.

La factura de venta no debería leer de cabecera el precio de mantenimiento y seguro si no de la tabla de detalle.

**Comment by JMunoz17** [comment]
Hemos subido las modificaciones a PRE.

Por un lado tenéis que rellenar en configuración de energía el IPC (%).

En la ficha de contrato de autoconsumo tendréis que rellenar de forma manual el precio de mantenimiento/seguro anual a partir del cual se valida el precio diario.

También en esta ficha tenéis un proceso os permite:
- Actualizar con el IPC los precios de seguro y mantenimiento en las líneas de todos los contratos de autoconsumo.
- Actualizar con el IPC los precios de seguro y mantenimiento solo en las líneas asignadas al contrato de autoconsumo desde el que se ejecuta dicho proceso.

Con esto vais a tener que ir con cuidado de no actualizar mas de una vez los contratos de autoconsumo porque los precios de las lineas se irian acumulando, requerimos confirmación en el proceso para tratar de evitar esto.

**Comment by bpesquero** [comment]
Probado y ok. 
Subir a PRO
