### ISSUE TITLE
Consulta campaña WEB18 A tu lado

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#642]
Tengo duda de cómo se configuró finalmente la campaña de 1€ de descuento para clientes de factura electrónica de A tu lado.
A los contratos se les añadió en el campo "Contract Web Code" el código "WEB18" y realmente no sé si se usa para algo.

**Comment by PKFEric** [comment]
Hemos estado revisando y en la web hay una funcion que no se utiliza que se regia por este campo, asi que parece que es un campo que al final no utilizamos para el traspaso de los clientes a la web de atulado asi que si quieres lo borro. Y tambien de la web.

**Comment by bpesquero** [comment]
Lo que queráis. Si no se usa, yo creo que da lugar a confusión más que otra. 
Guardar copia de los contratos que lo tenían asignado. por si acaso....

**Comment by PKFEric** [comment]
Ya esta
