### ISSUE TITLE
Error carga F1 suplementos territoriales Endesa

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#643]
EStán dando un error todos los ficheros de Endesa por cómo se informa el concepto repercutible correspondiente a los suplementos territoriales.

No se puede escribir '+0000000001,00' en Decimal

UnidadesConceptoRepercutible>+0000000001.00</UnidadesConceptoRepercutible>

  <PrecioUnidadConceptoRepercutible>+0000000001.51</PrecioUnidadConceptoRepercutible>

  <ImporteTotalConceptoRepercutible>+0000000001.51</ImporteTotalConceptoRepercutible>

  <Comentarios>00000100000000003300 +0000000016514</Comentarios>

  </ConceptoRepercutible>

**Comment by PKFEric** [comment]
Ya esta solucionado.

**Comment by bpesquero** [comment]
Probado y ok
