### ISSUE TITLE
Control autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#644]
Tenemos implementadp que en todos los casos en que tengamos marcado el valor de autoconsumo en el campo de OCSUM se comparará el neto del cierre en valor absoluto con el neto ente la energía entrante y saliente del F5D.
Lo que ocurre es que en los casos en que no hay una ficha activa de autoconsumo para las fechas de la factura, en el caso en que el algoritmo de autoconsumo sea F, es posible que el cierre de AS no venga informado. En esa caso, en caso de que no venga informado el cierre de AS para los supuestos detallados, habrá que cambiar el actual control por el siguiente:

Energía TE del F1= sumatorio de la energía entrante del F5D

**Comment by PKFEric** [comment]
He generado para el F1 20191002_IB_GAC%20(25)_(autoconsumo).xml la factura de compra tambien.

**Comment by PKFEric** [comment]
Ha dado estos errores:

Ruta fichero	Nº contrato	Fecha-Hora	Error/Aviso
20191002_IB_GAC (25)_(autoconsumo).xml	COM/01427	14/10/19 18:36	Error XML, existe una discontinuidad de fechas en el TE para el periodo 1
20191002_IB_GAC (25)_(autoconsumo).xml	COM/01427	14/10/19 18:36	Error XML, existe una discontinuidad de fechas en el TE para el periodo 2
20191002_IB_GAC (25)_(autoconsumo).xml	COM/01427	14/10/19 18:36	Error XML, existe una discontinuidad de fechas en el TE para el periodo 3
20191002_IB_GAC (25)_(autoconsumo).xml	COM/01427	14/10/19 18:36	Error XML, existe una discontinuidad de fechas en el TP para el periodo 1

**Comment by PKFEric** [comment]
Y este

Nº mov.	Nº contrato	CUPS	Error/Aviso	Ruta fichero	Fecha-Hora
13	COM/01427	ES0021000005729727FX	Error Factura, existen huecos en la facturación para el peaje con numero de factura 03191001030404491	20191002_IB_GAC (25)_(autoconsumo).xml	14/10/19 18:37

**Comment by PKFEric** [comment]
El control de Autoconsumo parece que funciona Bien

**Comment by bpesquero** [comment]
Nos está dando error para los siguientes casos:
1- Clientes sin ficha de autoconsumo porque el autoconsumo no lo gestionamos nosotros
COM/01200 - Nº factura acceso: 03190816030288583 - 20190819_IB (28) (pend de Belén).xml
2-Cuando el contrato tiene una ficha de autoconsumo <> algoritmo F pero con activación posterior a la fecha de fin de la factura. Es decir, en las fechas de  la factura no hay autoconsumo
COM/00293 - Nº factura acceso: 03190829030306381 - 20190830_Iberdrola (33) (pend de Belén).xml


Yo creo que el control sólo debería aplicar cuando para las fechas de la factura hay una ficha de autonconsumo activa con algoritmo diferente de F

**Comment by PKFEric** [comment]
Para el caso 1 quedamos que los contratos que tenian autoconsumo no gestionado por Geoatlanter no deberian llevar marcado el check de autoconsumo en su ficha sino que se gestionaria a traves del Codigo de Autoconsumo de OCSUM. Para ese contrato COM/1200 he desmarcado el Check. Ya estan generadas la factura de compra y de venta.

Para el caso del COM/00293 pasa algo similar hay controles que se aplican cuando esta marcado el check de autoconsumo. Si se quiere controlar que este marcado el check y los controles apliquen por que existe contrato de autoconsumo vigente o no vigente. El check solo deberia de estar marcado en caso de que aplicaran los controles establecidos de autoconsumo. Con lo cual, si no aplica autoconsumo, se desmarca el check, se factura y listo. Ya estan generadas las facturas de este contrato tambien.

**Comment by bpesquero** [comment]
PAra el contrato COM/1200 estoy de acuerdo. En el otro caso no. TEndría que estar mirando la factura que se va a hacer en cada caso y andar marcando y desmarcando, lo normal es que se haga por código en función de las fechas

**Comment by bpesquero** [comment]
Nuevo caso.
Fichero: 20190927_Iberdrola_GAC   (51)_autoconsumo.xml
Contrato: COM/01426
Error en la carga: Error, Tenemos un contrato autoconsumo y no viene informada AS en el cierre

Creo que es el control FUNCONTROL_CIERRE_F5D_F1(), en el caso de que no aparece cierre de AS, en este caso no hay ficha activa sin embargo parece que ha entrado en la comprobación de que si hay ficha activa y por eso ha dado ese error.

--

**Comment by bpesquero** [comment]
Otro caso más
Fichero: 20191021_GAC_Iberdrola (48)_COM_00575_bpf
Contrato COM/00575
Error en la carga: Error XML, AS -AE del cierre 240 es diferente de AE del F1 415

ESte error no se corresponde con ninguno de los controles vistos esta mañana. EStá comparando la energía neta del cierre con la energía facturada en el TE.
En realidad esto tendría que haber pasado por el control FUNCONTROL_CIERRE_F5D_F1(), en el caso en que aparece AS, y por tanto tendría que comprar el neto del cierro con el neto del sumatorio horario del F5D.

**Comment by bpesquero** [comment]
El COM/00575 sigue dando el mismo error.

**Comment by PKFEric** [comment]
Se me olvido subir el cambio. :) 

Ya esta he generado la factura de compra y la de venta, no ha dejado ningun error en el log
