### ISSUE TITLE
Cierres mostrados en pdf de factura de venta

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#645]
En el pdf de la factura de venta en la zona de medidas se muestran los cierres de AE, en caso de existir AS sería necesario mostrarlos también. No tengo claro que no sé esté haciendo, habría que revisarlo

**Comment by JMunoz17** [comment]
Tenéis alguna factura registrada con la que poder probarlo?
Y otra pregunta, esto también aplica al formato que usamos para las facturas de Autoconsumo de algoritmo NC no?

**Comment by bpesquero** [comment]
EStamos dando una vuelta al tema y hemos decidido de momento no incluir el cierre de AS. Perdonad que ayer os dijera otra cosa. Lo que habría que revisar ahora es que efectivamente no sale.

**Comment by PKFEric** [comment]
Ya solo sale la AE
