### ISSUE TITLE
Error carga F1 tipo C, no encuentra F5D

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#646]
Retomo el tema planteado en la incidencia #610 

Al cargar una factura de tipo C con algoritmo de autoconsumo F está dando error de que no encuentra F5D
SCTDE_F1_01_0022_0587_20190913080156344_(799293570) (autoconsumo).xml

La obligatoriedad de que exista un F5D independientemente de que lo ponga en el F1 tiene que cuumplirse siempre que exista una ficha de autoconsumo activa para las fechas de la factura con algoritmo de facturación distinto de F.

**Comment by PKFEric** [comment]
Cargada la fctura de compra
