### ISSUE TITLE
Error mail cambio de titular

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#647]
Si filtras por CUPS ES0022000008853937XM verás dos contratos. Primero el COM/01233 para el cual he solicitado un cambio de titularidad, que al procesar el paso M_02 de aceptación, se ha dado de baja, y ha creado el contrato COM/01710. El problema es que a la nueva titular le ha llegado el correo con la fecha de activación del cambio de titularidad erróneo, y en lugar de decirle que ya es la titular desde el 03/10/19, se le ha informado que es desde el 12/02/2019 (fecha activación de un M de cambio de potencia previo del COM/01233  ).

Código Contrato | Estado | Descripción | CUPS
-- | -- | -- | --
COM/01233 | Baja | Lucía (anulada baja pdte cambio tit) | ES0022000008853937XM
COM/01710 | Activado | Noelia Pita López | ES0022000008853937XM

![image](https://user-images.githubusercontent.com/20299071/66552022-e72a6a00-eb48-11e9-8b3b-c9d2733e6270.png)

º contrato | CUPS | HayCambioTitular | Código de Proceso | Código subpaso | Fecha aceptación | Fecha prevista activación | Fecha activación | Solicitud Administrativa Contractual | Tipo Cambio Titular | Indicativo de Activación con Lectura de Ciclo
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
COM/01710 | ES0022000008853937XM1P | No | C1 |   |   |   |   | S |   | A
COM/01710 | ES0022000008853937XM1P | No | C1 | Aceptado | 07/02/19 | 07/02/19 |   |   |   |  
COM/01710 | ES0022000008853937XM1P | No | C1 |   |   |   | 08/02/19 |   |   |  
COM/01710 | ES0022000008853937XM1P | No | M1 |   |   |   |   | N |   | A
COM/01710 | ES0022000008853937XM1P | No | M1 | Aceptado | 11/02/19 | 11/02/19 |   |   |   | C0
COM/01710 | ES0022000008853937XM1P | No | M1 |   |   |   | 12/02/19 |   |   |  
COM/01710 | ES0022000008853937XM1P | Sí | M1 |   |   |   |   | S | S | A
COM/01710 | ES0022000008853937XM1P | No | M1 | Aceptado | 09/10/19 | 03/10/19 |   |   |   | A0

**Comment by PKFEric** [comment]
Estaba buscando siempre el M1 05 ultimo existente, lo he modificado para que si es cambio solo contractual busque el M1 02 Activacion y meta la fecha prevista de activacion.

**Comment by bpesquero** [comment]
probado y ok
