### ISSUE TITLE
Generacion de fichas de autoconsumo automáticas

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#648]
servidor:TAU
BBDD:ACSM
PA de SQL --> PA_FichaAutoconsumoNAV

Salida PA | Campo de Navision
-- | --
id | Shortcut Dimension 3 Code
CUPS | CUPS
fecha_inicio | Fecha Inicio Vigencia
algoritmo | Algoritmo de Autoconsumo
tipo_autoconsumo | Tipo Autoconsumo Contrato
potencia_pico | Potencia Pico
potencia_instalacion | Potencia Instalación
fecha_revision | Fecha Proxima Revisión Pot.
fecha_puesta_marcha | Fecha puesta en marcha
duracion_renting | Duración de Renting (Años)
tipo_interes | Tipo de Interés Anual %
inversion | Coste Total
porcentaje_financiacion | % Financiacion
mantenimiento | Precio prod. mant. anual
seguro | Precio prod. seguro anual
tramitacion | Campo nuevo

EL campo de tramitación es un campo nuevo que habrá que crear en NAV que puede tomar los siguientes valores

0--> No tramitar
1-->Sólo represetanción
2--> Tramitar

El PA devuelve todos los proyectos conectadas. Se creará una ficha de autoconsumo para aquellos proyectos que no tengan una ficha previa. La clave para buscar los proyectos será el ID coincidente con la dimension global 3.

**Comment by PKFEric** [comment]
Belen Creo que has duplicado la tarea esto es lo mismo que pusiste en la #638

**Comment by bpesquero** [comment]
Efectivamente. por eso no encontraba lo que había subido con el detalle del
PA.

Borra la que más rabia te de


*Síguenos en:*[image: Facebook pequeño]
<https://www.facebook.com/proximaenergia/>[image: Twitter pequeño]
<https://twitter.com/proximaenergia?lang=es>[image: Google+pequeñito]
<https://plus.google.com/114547235710296874519>

*AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener información
*confidencial *sometida a secreto profesional. No está permitida su
reproducción o distribución sin la autorización expresa de *GEOATLANTER SL.*

Si usted no es el destinatario final por favor elimínelo e infórmenos por
esta vía.



De acuerdo con lo establecido por el Reglamento General de Protección de
Datos (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de
2016, le informamos que sus datos serán tratados con la finalidad de
realizar la gestión administrativa, contable y fiscal, así como el envío de
comunicaciones comerciales  sobre nuestros servicios y/o productos.


Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, oposición, supresión, limitación y portabilidad de
sus datos en el domicilio de *GEOATLANTER SL *sito en: Avda de Europa 34B
<https://maps.google.com/?q=Avda+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha 3º,  28023 Madrid o enviando un correo electrónico a la siguiente
dirección : *contacto@geoatlanter.com <contacto@geoatlanter.com>*

Si usted no desea recibir nuestra información, póngase en contacto con
nosotros enviando un correo electrónico a la dirección:
*contacto@geoatlanter.com
<contacto@geoatlanter.com>*
