### ISSUE TITLE
WEB - envio de contratos y gestión de firma a través de signaturit

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#649]
En una primera fase queremos enviar de forma automática los contratos desde la web (Próxima y A tu lado). También hay que recoger la información de que el contrato esta firmado para pasarlo a estado firmado cliente en NAV.
Me gustaría que me hicierais una valoración de viabilidad y tiempos.

Os paso alguna información

La API de Signaturit es REST.

Disponemos de un entorno de pruebas que llamamos SANDBOX, en el que te puedes registrar y empezar a trabajar en la integración. Este entorno es un “espejo” del entorno real, con algunas diferencias:

* Se añade una marca de agua en los documentos;
* No se certifican los datos.

Para registrarte en nuestros servidores de pruebas, puedes seguir este enlace: https://app.sandbox.signaturit.com/en/register/developer

Por otra parte, te paso unos enlaces que te ayudarán a comenzar con buen pie:

Empezar con la integración de la API

Lista de SDKs para una integración más sencilla

Utilizar el parámetro "data"

Personalizar tus envíos y comunicaciones

Para pasar a producción, lo principal que hay que hacer es un cambio en los endpoints e indicar tu token de producción:

https://docs.signaturit.com/api/latest#moving_to_production

Cualquier cosa adicional que necesiteis para la valoración, me decís.

La API de Signaturit es REST.

Disponemos de un entorno de pruebas que llamamos SANDBOX, en el que te puedes registrar y empezar a trabajar en la integración. Este entorno es un “espejo” del entorno real, con algunas diferencias:

* Se añade una marca de agua en los documentos;
* No se certifican los datos.

Para registrarte en nuestros servidores de pruebas, puedes seguir este enlace: https://app.sandbox.signaturit.com/en/register/developer

Por otra parte, te paso unos enlaces que te ayudarán a comenzar con buen pie:

Empezar con la integración de la API

Lista de SDKs para una integración más sencilla

Utilizar el parámetro "data"

Personalizar tus envíos y comunicaciones

Para pasar a producción, lo principal que hay que hacer es un cambio en los endpoints e indicar tu token de producción:

https://docs.signaturit.com/api/latest#moving_to_production

**Comment by bpesquero** [comment]
Hemos probado y encontramos los siguientes problemas

1.- el email de signaturit sale en inglés

![image](https://user-images.githubusercontent.com/20299071/69957600-441c1e00-1503-11ea-8d63-344975307cf1.png)

2.- La firma de signaturit hay que colocarla dentro del documento en el sitio adecuado. Se queda en la primera página y ese no es el sitio. Debería estar al final de las condiciones particulares y al final de las condiciones generales

**Comment by bpesquero** [comment]
Me comenta Ainhoa que ha tardado una media hora en cambiar el estado del contrato. No sé si podríamos aumentar la frecuencia de sincronización con NAV

**Comment by bpesquero** [comment]
También sería muy interesante tener la posibilidad de sincronizar manualmente.
Otra cuestión es que para clientes o agentes comerciales que quieren dar de alta un conjunto de ofertas de una vez tienen que esperar a que se ponga en estado firmado el primero para seguir añadiendo contratos. No sé si podríamos dar una vuelta a esto para cambiarlo

**Comment by dgarciageo** [comment]
Creo 2 tareas con el ultimo comentario #702 y #705

**Comment by dgarciageo** [comment]
Con los clientes que son empresa se genera el pdf pero no se envia a signaturit

**Comment by jorgereal** [comment]
Corregida la integración con signaturit para los clientes de tipo empresa.
Subido a PROD.
