### ISSUE TITLE
potencia contratada

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#65]
En la potencia contratada no deja meter tres decimales, es necesario, los suministros trifásicos tienen siempre la potencia con tres decimales.

**Comment by PKFEric** [comment]
CORREGIDO-> PROBAR

**Comment by bpesquero** [comment]
sigo sin poder

**Comment by bpesquero** [comment]
Lo he vuelto a probar y ahora sí, he debido de probarlo antes de que se subiera...

**Comment by bpesquero** [comment]
Perdón, acabo de ver qué es lo que pasa. Se puede si desde la parte de cliente le das a nuevo contrato. Pero si das de alta un contrato desde cero, entonces no.
