### ISSUE TITLE
Suplementos territoriales

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#650]
Hay que cambiar el texto correspondiente a sumplementos territoriales que aparece en el email de nueva factura.

Donde dice
«Suplemento territorial por tributos autonómicos del año 2013 según la Orden ETU/35/2017«

tiene que decir

«Suplemento territorial por tributos económicos del año 2013 según la Orden TEC/271/2019«

**Comment by bpesquero** [comment]
En el detalle de la factura (el que aparece en el anverso del pdf) pasa igual. HAy que cambiar el texto y poner 

Suplemento territorial por tributos económicos del año 2013 según la Orden TEC/271/2019

**Comment by JMunox17** [comment]
Cambiado para GEO y HECEN, tanto en PRE como en PROD.

**Comment by JMunoz17** [comment]
Cambiado para HECEN y GEO, subido tanto a PRE como a PROD.

**Comment by bpesquero** [comment]
Hemos visto que el email que se envió al cliente no se corresponde con la plantilla actual. He presupuesto que se envía ese emal cuando se procedía a enviar la primera factura con suplmento territorial. Pero hoy hemos enviado otra factura con su "primer" suplemento territorial y se ha enviado el email standard. Me podéis indicar qué es lo que se está haciendo?

**Comment by bpesquero** [comment]
![image](https://user-images.githubusercontent.com/20299071/66649942-b8d38a00-ec2f-11e9-9114-187b2e2bb991.png)

**Comment by bpesquero** [comment]
![image](https://user-images.githubusercontent.com/20299071/66649986-cdb01d80-ec2f-11e9-85c5-8ca67c1e8c16.png)

**Comment by bpesquero** [comment]
ok
