### ISSUE TITLE
Problema con factura G ES0031405973012020LA - HECEN/09975

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#652]
![image](https://user-images.githubusercontent.com/20299071/67267867-79206400-f4b3-11e9-94b2-55253587540e.png)

Envío por email F1
Creo que el problema está en que una de las líneas de la factura es negativa, y no se está considerando correctamente.

**Comment by JMunoz17** [comment]
Es un problema de fechas.

El F1 al que regulariza (\\NI\Esios\F1 Hecen\Procesados\20190920_Endesa (6).xml) vino con fecha desde 2019-08-19 para el término de energía. Se le aplico el +1 en función del criterio de fechas inclusive exclusive de la distribuidora por lo que la fecha desde en NAV es 2019-08-20.

El F1 de la regularizadora viene con fecha desde 2019-08-20 para el termino de energía. Al aplicar el +1 la fecha desde en NAV es 2019-08-21. Por eso no encuentra los datos de la anterior factura al hacer los controles y de ahí este error.

Las medidas F5D de la regularizadora comienzan el día 20. Para importarla habría que cambiar el criterio de fechas inclusive exclusive para que no sume el +1 al importar este F1 y luego volver a dejarlo como estaba.

Cualquier cosa me decís.
