### ISSUE TITLE
NAV - Integracion con SQL de pedido y efectos

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#656]
Desde NAV se invocará al siguiente PA para generar un pedido de manera automática con todos los elementos que devuelva la query

**Habrá que crear en NAV un pedido por proveedo**

TAU.ACSM.[dbo].[GetPresupuestoAcsm] (@Nav_PedidoId varchar(50))

Ver la posibilidad de crear por diario un efecto de forma automática. Entendemos que todos los datos necesarios para crear el efecto se pueden sacar de los datos del proveedor.

**Comment by bpesquero** [comment]
La tenía yo abierta en la tarea #655 pendiente de asignarla a alguna semana cuando termináramos lo pendiente.

GESTIÓN DE PEDIDOS
Se acuerda:
-dejar el inventario en NAV. Para ello nos pasa Belén tablas de carga de datos.
-la tabla de categorías pasa a ser categorías
-la tabla de propiedades pasa a ser la de grupo
-la tabla de stock pasa a ser tarifas
-el campo marca de productos se va a llevar a través del campo intrastat, que permite tener las marcas almacenadas en una tabla. Además en esta tabla se marcará las marcas que pertenecen al topten
-El campo materiales de productos se va a poner como un campo con opciones (enviar valores posibles a Attest), en la migración (si se migra) pasarán a ser atributos del producto
-pensar si queremos llevar almacenes(JORGE)
-portes: se pueden llevar cómo cargos de producto, esto carga el precio de existencias y no permite meter las tarifas reales de los proveedores. Se puede llevar como un producto que no forme parte de existencias
-decidir el método de valoración de existencias: FIFO y medio tienen el problema de la valoración negativa de las existencias. A precio estándar parece más razonable para nosotros. Va a mirar Belén, por si optamos por FIFO o medio, si existe la posibilidad de redistribuir dimensión a posteriori, para evitar los movimientos de existencias negativos.

**Comment by dgarciageo** [comment]
Hemos creado un procedimiento almacenado
TAU.ACSM.[dbo].[GetPresupuestoAcsm] (@Nav_PedidoId varchar(50))

**Comment by dgarciageo** [comment]
**Habrá que crear en NAV un pedido por proveedor**
Ver la posibilidad de crear por diario un efecto de forma automática

**Comment by JMunoz17** [comment]
Subido a PRE.
Proceso de importación accesible desde ENERGY -> Carga de datos -> Autoconsumo -> Importar Pedidos ACSM
Setup a instalar en cada uno de los equipos desde los que se vaya a ejecutar este proceso, os lo dejo en:
\\NI\Esios\Setup Importacion Pedidos ACSM

**Comment by bpesquero** [comment]
Pendiente de hacer las pruebas con pedidos que incluyan 2 priyectos.

Hasta ahora lo único que ha surgido es el tema de la generación del efecto automático por diario para meterlo en cartera. ¿Lo habéis considerado?¿Cuando se genera?

**Comment by bpesquero** [comment]
Hemos probado a importar pedidos de dos proyectos y duplica los pedidos. Está haciendo un pedido por proveedor y proyecto cuando realmente sólo debería hacer un pedido por proveedor.
Lo imaginábamos porque ya vimos que estaba asignando la dimensión de proyecto en cabecera cuando sólo debería hacerlo en las líneas.

**Comment by JMunoz17** [comment]
El primer punto os ha mandado Belén Ramirez un email.

El segundo punto lo he modificado y subido a PRE y PROD.

**Comment by bpesquero** [comment]
Probado el segundo y ok
Pendiente de analizar el primer punto de los efectos.

**Comment by JMunoz17** [comment]
Pasamos a done esta tarea y creamos una nueva para el tema de los efectos.
