### ISSUE TITLE
CAMBIAR DURACIÓN Y TIPO DE INTERÉS DE FINANCIACIÓN DE AUTOCONSUMO POR DEFECTO

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#657]
Pasar de la tabla de configuración OCSUM a configuración de energía.  Aparecía en el documento por error. En la última versión del documento funcional aparece ok.

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

**Comment by JMunoz17** [comment]
### En respuesta a esto que nos dijisteis por mail:
_Esta subido a PRO pero falla:
Hemos configurado la tabla de configuración de energía
Hemos creado una nueva cabecera de autoconsumo pero los valores configurados no se rellenan_

**El problema estaba en que este dato lo rellenábamos al validar el Tipo de Autoconsumo (esto antes tenia sentido al estar configurado en Ocsum), pero ya no tiene sentido así que lo he cambiado y estos datos se insertarán al insertar el contrato y al cambiar el tipo de algoritmo (solo para F,SF,NF).**

**También lo he añadido en el proceso de importación de contratos de autoconsumo (primero cogemos los valores configurados en NAV y si viene algún dato desde TAU referente a estos campos actualizamos el valor).**

**Comment by bpesquero** [comment]
Probado y ok
