### ISSUE TITLE
Incluir dimensión 3 en ficha de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#658]

**Comment by JMunoz17** [comment]
Hemos sacado el campo en la ficha y en la lista de contratos.

Aparte, tal y como comentamos por teléfono la semana pasada, he añadido:
- Un commit contra la base de datos para que si el proceso falla con el cuarto proyecto, los tres primeros se importen correctamente.
- Hemos añadido un log que indicará para que ID`s no encuentra proyecto en NAV. El acceso esta junto al proceso de importación. Tal y como hablamos el otro dia, se utiliza el mismo formulario que usamos para los ficheros de medidas y peajes.

**Comment by bpesquero** [comment]
No veo el campo ni en la lista de autoconsumos ni en la ficha de autoconsumo
Por otra parte cuando hay un problema con la carga de un fichero de autoconsumo no vemos que se esté escribiendo en el log (habladlo si queréis con Mónica)

**Comment by bpesquero** [comment]
PArece qeu está filtrando por el log de F1 en vez de el de autoconsumo

**Comment by JMunoz17** [comment]
Habéis cerrado y vuelto a abrir Navision?
En el formulario del log te van a salir tanto lo del F1 como lo de la carga de autoconsumo porque usamos el mismo objeto (no hay formularios libres en licencia).

**Comment by bpesquero** [comment]
Si, hemos salido y entrado y no vemos ni lo del log ni el campo de codigo de proyecto en la lista y ficha de autoconsumo.

**Comment by JMunoz17** [comment]
En la ficha de contratos el campo aparece en la pestaña de autoconsumo:
![image](https://user-images.githubusercontent.com/26869276/68225389-a4956980-fff0-11e9-8108-9028bf4d0d5a.png)

En la lista esta a la derecha del todo:
![image](https://user-images.githubusercontent.com/26869276/68225467-c0007480-fff0-11e9-86f0-40538f7f985a.png)

Si queréis que aparezcan en otra pestaña me decís.

Respecto al log, en Geoatlanter PRE puedes ver como aparecen datos de unas pruebas que hice ayer, si me das el OK lanzo la importación en GEO y debugeo a ver si no se esta haciendolo por algún motivo o es que no hay ningún caso que cumpla las condiciones para que aparezcan datos en el log.

**Comment by bpesquero** [comment]
no se trataba de incluirla en la pestaña de autoconsumo de la ficha del contrato, realmente en la fcha del contrato ya estaba y ponerlo en una pestaña u otra lo puedo hacer yo. Se trataba de ponerlo en la ficha de autoconsumo (en el formulario de autoconsumo) y en la lista. ADemás sería interesante añadir también el nombre del titular.

**Comment by bpesquero** [comment]
Aclarado que en el log no aparece. Lo dejamos de momento así

**Comment by JMunoz17** [comment]
Modificada la ficha y la lista de contratos de autoconsumo. Añadidos Cod. Titular, Nombre Titular y Cod. Proyecto (Dimension 3).
