### ISSUE TITLE
Cálculo financiación para una parte de una factura

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#659]
Cuando la fecha de inicio de vigencia de autoconsumo "cae en mitad" de una factura dijimos que saldría una notificación en el log. Así lo está haciendo.
En el caso en que el algoritmo de cálculo sea F debería incluir la parte correspondiente

**Comment by bpesquero** [comment]
Para el contrato COM/01462 al facturar la factura de venta FV/201911631 que va del 03/09/19 a 02/10/19 no da error en el log cuando la ficha de autoconsumo con algoritmo F comienza el 26/09/19

**Comment by JMunoz17** [comment]
Subido tanto a PRE como a PROD.

He generado la factura para el contrato COM/01462:
FV/201911927

**Comment by bpesquero** [comment]
En relación a esto indicar que el importe diario de financiación, de mantenimiento y de seguro debe ir redondeada a dos decimales

**Comment by JMunoz17** [comment]
He modificado la tabla del detalle de financiación para que, a partir de ahora, los valores de Cuota Renting, Precio Mant. y Precio Seguro tengan máximo 2 decimales. A partir de ahora os debe salir bien.

Voy a pasar un proceso para redondear las líneas de detalle generadas hasta hoy. Navision en la visualización lo estaba mostrando con el redondeo estándar:
Si era 1,868 mostraba 1,87 y si era 1,864 mostraba 1,86.
Confirmadme que es este el redondeo a utilizar para el proceso o si es necesario usar el redondeo hacia abajo en todos los casos.

**Comment by bpesquero** [comment]
EL redondeo estándar es ok

**Comment by JMunoz17** [comment]
Ya he pasado el proceso en producción en la empresa GEOATLANTER.
Os he vuelto a generar la factura del COM/01462 para probar que ahora los importes de estos conceptos llegan a la factura con dos decimales.
Nº Factura: FV/201912234
Echadle un ojo y me decís con cualquier cosa.
