### ISSUE TITLE
formato PDF factura venta con autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#660]
Habría que revisar las plantillas de pdf  de facturas de venta para que al incluir todas las líneas de autoconsumo sigan cabiendo en dos páginas.
Sólo tenemos impresas con algoritmo F y ya se desplaza todo. Ej: C_201900708

Si os podemos ayudar con la parte de formato, decidnos

**Comment by jorgereal** [comment]
Se han modificado los formatos de factura y abono de GEOATLANTER así como el formato para algoritmos NC de Autoconsumo para que siga ocupando dos páginas.

Subido a PRE y PRO.

**Comment by bpesquero** [comment]
He mirado la factura C/201900712
CAbe en una página pero me llama la atención:

-aparece línea de reactiva y no tiene reactiva. 
- aún no se le factura energía exdentaria, En cuanta aparezca la energía excedentaria y nuestra comisión de gestión de esa energía se vuelve a ir a 3. Quizá es mejor que para cuando sea de autoconsumo se haga directamente en 3  páginas pasando la información de origen de la energia a la tercera.

**Comment by JMunoz17** [comment]
Esa es una opción, la otra es tratar de ajustar un poco mas el informe (reducir los pequeños espacios que quedan entre unos cuadros y otros) y sobretodo reducir el tamaño de letra de las lineas del detalle de la factura, creemos que así podría entrar todo en dos páginas.

Nos decís que opción preferís.

**Comment by bpesquero** [comment]
Ok. Mirad para que quepa con la opción uqe tenga más líneas y una tarifa en dos periodos, por favor

**Comment by jorgereal** [comment]
Hemos ajustado al máximo los espacios entre los elementos de la segunda página para los 3 formatos.
Podéis probar en PRE con la factura C/20191868 de autoconsumo y tarifa en dos periodos, en la que queda suficiente espacio como para mostrar hasta 4 líneas más.

Subido a PRE.

**Comment by bpesquero** [comment]
Buenas, tenemos ahora una rectificativa y al tener una línea más en cada concepto se va otra vez a tres páginas. Creo que lo mejor es directamente hacerlas en 3 páginas.
C/201900770

¿Está subido a PRO?

**Comment by jorgereal** [comment]
Hemos subidos la última versión de los formatos a PROD y ya sale la factura C/201900770 en dos páginas.

Si encontráis alguna factura con esta problemática con los nuevos formatos lo cambiamos para que salga en 3 páginas.

**Comment by bpesquero** [comment]
PArece que está solucionado, pero no sé por qué sale una línea de reactiva y además el espacio entre la línea de reactiva y la de suplemento territorial es mayor que entre el resto de conceptos

![image](https://user-images.githubusercontent.com/20299071/68309695-17fdb080-00af-11ea-9341-70220eea6e1e.png)

**Comment by JMunoz17** [comment]
Hemos modificado el informe para que no deje el espacio encima de la línea de Supl. Territorial (estaba programado así aposta por lo que no sé si en algún momento lo pedisteis, si queréis que deshagamos el cambio nos avisáis).

Respecto a la línea de "Energía Reactiva" era un problema con la plantilla que estaba mal configurada. Le faltaba el check de "Energía Reactiva" a esa línea.

Os lo he modificado en la Plantilla TIPO V 2P y lo he probado con la factura FV/201912234 de la incidencia #659 donde también estaba pasando, ahora veréis que ya no aparecerá en las nuevas facturas.
Creo que el resto de plantillas están bien configuradas, pero revisadlo por si acaso.
