### ISSUE TITLE
Error carga F1 con autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#661]
AL cargar el fichero 20191021_GAC_Iberdrola (44)_COM_01261_bpf da error
Error XML, la fecha desde de AE del Cierre 04/09/19 es diferente de la fecha desde TE del peaje 03/09/19 y de la fecha desde CCH 03/09/19

Hay un cambio de equipo. He probado a cambiar el nº de serie a mano del cambio de equipo, pero sigue dando el mismo error. 
ESto ya surgió pero yo creo que estaba solucionado

**Comment by PKFEric** [comment]
En este cierre vienen dos medidas por contador para cada periodo, entonces no se si es que esta mal, o una es AE y la otra es AS, en cualquier caso no esta contemplada esta situacion, para arreglarlo si me dices que las dos son AE las sumo por contador ya esta. 

Ejemplo:
Para el Periodo 1:
Contador 1:  AE Consumo 86 y consumo 113
Contador 2: AE Consumo 10 y consumo 0

Entonces si modifico el XML para:

Contador1 : AE Consumo 86+113
Contador2 : AE Consumo 10+0

**Comment by bpesquero** [comment]
probado y ok
