### ISSUE TITLE
error carga F1 con autoconsumo comprobación incorrecta del cierre

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#662]
Para el COM/00916 al cargar el fichero 20191021_GAC_Iberdrola (45)_COM_00916_bpf da el siguiente error:

Error XML, AS -AE del cierre 684 es diferente de AE del F1 151

En realidad el control está mal hecho hay que comprobar que abs(AS-AE) del cierre = abs( entrante -saliente) del F5D

**Comment by PKFEric** [comment]
Esto ya esta corregido, el problema es que con el cambio de contador se cargaba las medidas AS y por eso entraba en el otro control, ya entra en el control correcto por que he arreglado el problema de los dos contadores.
