### ISSUE TITLE
NAV - Carga automática de facturas OMIE

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#664]
La idea es cargar de manera automática las facturas de OMIE que actualmente se están contabilizando de forma manual. Tanto para Geo como para HEC

\\ALFA\Datos\Administracion\OMEL\GAC\FACTURACION\XML

En GEO se duplicarán las líneas para asignar dada una de ellas a un CC diferenbte (COM / REPRE)

![image](https://user-images.githubusercontent.com/47117960/69133871-e1fcfb00-0ab6-11ea-846e-6e11c60a6ca3.png)

En HECEN no es necesario duplicar las lineas por sólo hay un centro de coste de REPRE)

Una vez cargado el XML se tendrá que realizar el reparto de los centros de coste (esto una vez cargadas las lineas)

Tras asignar los centros de coste se tendrá que realizar las comprobaciones de precios y programas (Creación de vista por GEO)

![image](https://user-images.githubusercontent.com/47117960/69233817-e6e0ae00-0b8d-11ea-859b-9608e714291e.png)

**Comment by JMunoz17** [comment]
Subido a PRE.

Configuración a realizar:
- Configuración BBDD: Configurar la ruta con Tipo-Configuración: Factura Venta OMIE. Configurar los campos Origen Ficheros y Archivado Ficheros. No hace falta configurar el tipo Factura Compra OMIE, el sistema recogerá todos los ficheros de la ruta de Venta, independientemente de si son facturas de compra o de venta.

![image](https://user-images.githubusercontent.com/26869276/69349163-9a719d00-0c77-11ea-89c5-ad785b06b2c7.png)

![image](https://user-images.githubusercontent.com/26869276/69349139-9180cb80-0c77-11ea-8b90-284030d3a3fc.png)

- Configuración de Contabilidad: Configurar código proveedor, cliente, productos, centros de coste y números de pre-facturas y pre-abonos.
![image](https://user-images.githubusercontent.com/26869276/69349244-ba08c580-0c77-11ea-81e6-4ad4c6cd702e.png)

![image](https://user-images.githubusercontent.com/26869276/69349283-c55bf100-0c77-11ea-891c-6379bb6ffd24.png)

En el menú tenéis el proceso de importación y el log en Energy -> Carga de datos -> Carga Facturas Omie:
![image](https://user-images.githubusercontent.com/26869276/69349528-326f8680-0c78-11ea-900e-347ee5ee9dd0.png)

Cualquier cosa me vais diciendo.

**Comment by dgarciageo** [comment]
Buenas Jaime,

Test OK. Sólo 2 peticiones.

1) El orden en el que salen las líneas debe ser el siguiente:

- CESP (con el importe y MWh de la factura) y CESP-REP (linea a 0)
![image](https://user-images.githubusercontent.com/47117960/69866867-8c3e0500-12a5-11ea-8ca6-f3e4b4076031.png)

- VESP-REP (con el importe y MWh de la factura) y VESP (linea a 0) - Este ya sale así 

2) Los textos que acompañan las líneas:

CESP - Compra Energía Nacional
CESP-REP - Compra Energía Nacional - Representación

VESP - Venta Energía Nacional
CESP-REP - Venta Energía Nacional - Representación

**Comment by JMunoz17** [comment]
Modificado y subido a PRE y PROD.

**Comment by bpesquero** [comment]
El número de factura de venta no es correcto. Tiene que salir las letras que van delante del nº 

Por otra parte, el nº de factura de compra registrada y de abono de compra registrada pasa a configurarse en configuración de contabilidad en vez de en la ficha de proveedor.

**Comment by JMunoz17** [comment]
Modificado, subido a PRE y PROD.

**Comment by bpesquero** [comment]
En HECEN no estaba en la tabla de configuración de BBDD (códigos OCSUM) la línea corresondiente a OMIE. Cuando intentaba meterla daba este error
![image](https://user-images.githubusercontent.com/20299071/69971078-a71bae00-151f-11ea-8606-addc6cfdd83f.png)

He ido directamente a la tabla y he visto que efectivamente estaba la línea aunque no aparece en el formulario NAV. La he configurado. Pero sigue sin salir. He probado a quitar filtros y demás, pero no aparece.

Para evitar confusión preferiría que ahora la de configurar no hubiese un valor de facturas de compra OMIE que no se usa nunca. Además, el valor facturas de venta OMIE debería cambiarse por facturas OMIE

**Comment by JMunoz17** [comment]
Lo primero es porque en la línea el campo "Tipo Registro" tiene que tener el valor BBDD, de lo contrario no aparece en el formulario. Te lo he marcado yo desde la tabla.

Respecto a lo segundo, no puedo eliminar ese valor porque se trata de un campo de tipo enumerado, pero he cambiado los captions para que te salga uno como "Facturas OMIE" y el otro en blanco, para evitar confusiones.

**Comment by bpesquero** [comment]
PErfecto. GRacias

**Comment by bpesquero** [comment]
Las facturas de Geo se están cargando bien. Pero en las facturas de HECEN no está dando este error
![image](https://user-images.githubusercontent.com/20299071/70049157-5e6dfe80-15cc-11ea-897c-aa35419d8001.png)
Tenéis los ficheros en \\ni\Esios\OMIE\HECEN\Importados

**Comment by JMunoz17** [comment]
Estaban mal configuradas las rutas, faltaba la \ al final.
Ya le he dado yo a importar para asegurarme que fuese por eso, tenéis las 7 facturas de venta generadas.

**Comment by bpesquero** [comment]
Vaya, lo siento. gracias

**Comment by bpesquero** [comment]
Hemos cargado los ficheros y se han generado las prefacturas. Hemos visto que la serie era incorrecta así que hemos borrado las prefacturas, hemos cambiado la configuración de números de serie y hemos vuelto a cargar los ficheros. Nos dan los siguientes errores

Log OMIE
![image](https://user-images.githubusercontent.com/20299071/70163374-a588ec00-16bf-11ea-9ec8-784522572bb5.png)

Hemos visto que estaba en la tabla de facturas. Hemos borrado las líneas (no deberíamos haberlo hecho hasta que no lo vierais vosotros, sorry, pero de momento pensamos que era la tabla de facturas, no la de facturas registradas, además lo que si vimos antes de borrarlas es que no tenía movimientos de proveedor y parece que tampoco de contabilidad)
Ahora están las cabeceras de historico de facturas que no hemos borrado para que lo vierais. Ciertamente desconocemos porque se ha escrito en la tabla de facturas registradas si lo único que se había generado era una prefactura que hemos borrado por ser incorrecta.
Ha sido en la empresa HECEN. Os paso el listado de facturas de venta con las que hemos tenido el problema.
![image](https://user-images.githubusercontent.com/20299071/70163685-2e078c80-16c0-11ea-81cb-73936491020f.png)

**Comment by JMunoz17** [comment]
Os he eliminado esas facturas registradas para que podáis importarlas de nuevo, probad a ver.

Si os pasa esto alguna otra vez lo que teneis que hacer es limpiar el valor del campo Nº Siguiente factura y Nº Doc. Externo de la pre-factura antes de eliminarla, asi no se registrarán facturas en blanco (esto se hace para respetar la numeración).
