### ISSUE TITLE
Error cambio de tarifa web HECEN/01545

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#665]
AL tratar el cliente de hacer un cambio de tarifa desde la web le salta el siguiente error
![image](https://user-images.githubusercontent.com/20299071/67933261-b8426980-fbc5-11e9-8a8f-9729b48947b3.png)

**Comment by PKFEric** [comment]
He arreglado el problema y he hecho la prueba con el contrato, se ha creado el M correspondiente en NAV.
