### ISSUE TITLE
CArga automática de fichas de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#667]
Cuando da un error por dato incorrecto aparece un mensaje muy completo de lo que ocurre sin embargo no lo relaciona con ningún contrato. Al no llegar a generar la ficha de autoconsumo no es posible saber cuál está teniendo el problema
![image](https://user-images.githubusercontent.com/20299071/68142351-992e3980-ff2f-11e9-801c-34f38eb079c5.png)

**Comment by JMunoz17** [comment]
Para la generación del detalle de financiación es obligatorio que una serie de campos tengan valor, de ahí este fallo por ejemplo.

He controlado esto para devolver un error manual antes de que salte el error estándar de NAV, en este error se informará el ID (Dimensión 3) del proyecto. 

He añadido el control para todos los campos obligatorios de cara a la generación del detalle de finanaciación, si os da el error con algún otro campo me avisáis y lo añado.
