### ISSUE TITLE
COM/00916 facturación venta autoconsumo NF

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#668]
SE ha hecho una factura d venta para el contrato COM/00916 que está en prefactura y, salvo error por mi parte, no se ha facturado como un NF ya que tiene una línea de excedentes. En el caso de las NF lo que se hace es minorar en factura la cuota de renting,

**Comment by JMunoz17** [comment]
Contesto vía mail.

**Comment by JMunoz17** [comment]
Tenemos preparados los objetos para subirlos a Producción, necesitaré reiniciar los servicios por lo que el sistema os echará de NAV.

En que rango de horas podemos hacer esto?

**Comment by bpesquero** [comment]
Cuando queráis,Avisad previamente y paramos. Lo mejor sería a primera hora
de la mañana.


*Síguenos en:*[image: Facebook pequeño]
<https://www.facebook.com/proximaenergia/>[image: Twitter pequeño]
<https://twitter.com/proximaenergia?lang=es>[image: Google+pequeñito]
<https://plus.google.com/114547235710296874519>

*AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener información
*confidencial *sometida a secreto profesional. No está permitida su
reproducción o distribución sin la autorización expresa de *GEOATLANTER SL.*

Si usted no es el destinatario final por favor elimínelo e infórmenos por
esta vía.



De acuerdo con lo establecido por el Reglamento General de Protección de
Datos (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de
2016, le informamos que sus datos serán tratados con la finalidad de
realizar la gestión administrativa, contable y fiscal, así como el envío de
comunicaciones comerciales  sobre nuestros servicios y/o productos.


Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, oposición, supresión, limitación y portabilidad de
sus datos en el domicilio de *GEOATLANTER SL *sito en: Avda de Europa 34B
<https://maps.google.com/?q=Avda+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha 3º,  28023 Madrid o enviando un correo electrónico a la siguiente
dirección : *contacto@geoatlanter.com <contacto@geoatlanter.com>*

Si usted no desea recibir nuestra información, póngase en contacto con
nosotros enviando un correo electrónico a la dirección:
*contacto@geoatlanter.com
<contacto@geoatlanter.com>*

**Comment by JMunoz17** [comment]
Subido a PROD.

**Comment by bpesquero** [comment]
Hemos probado la factura. 
No me cuadra la línea de descuento cuota de renting. La energía (cantidad) está bien, pero el precio a mi me sale de 42,78 y por tanto el importe de la línea debería ser 35,72€ en vez de 33,59€. 
¿Cómo puedo ver el cálculo que se ha hecho para ver dónde está la diferencia? ¿Se ha aplicado algún limite? Es que me parece muy raro que no coincida.

**Comment by JMunoz17** [comment]
Contesto vía mail.
