### ISSUE TITLE
WEB - Contabilización de pedidos (Belén Ramirez)

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#679]
En el momento de cierre se realiza un asiento para contabilizar pedidos o facturas proforma en su correspondiente cuenta de ingresos/gastos. El movimiento se deshace con fecha día siguiente.

Hablado directamente con Belén Ramirez

**Comment by JMunoz17** [comment]
Lo paso a DONE que me dijo Belén Ramírez que ya lo revisó ella con vosotros.
