### ISSUE TITLE
Carga A3 paso 05

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#68]
Da error la carga del fichero A3 paso 05 de Geo.

**Comment by bpesquero** [comment]
Supuestamente estaba solucionado para GeoAtlanter, para al tratar de cargar tres ficheros de HECEN vuelve a dar el mismo error
Los ficheros están en el buzón de entrada

**Comment by PKFEric** [comment]
Ya estan importados (que no procesados). El elemento que daba problemas podia aparecer o no asi pues le he puesto que las minimas ocurrencias sean 0.
