### ISSUE TITLE
ACSM - D1. (Entrada en el log NAV)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#682]
Cuando llega un D1 asociado a un contrato **sin** ACSM nos da el siguiente error:

"El contrato no tiene ficha de autoconsumo asociada"

Esto no es del todo correcto ya que el D1 es un fichero de notificación de propósito general ( no sólo de autoconsumo). 

Lo que que necesitamos es que si es el campo ""MotivoCambioATRDesdeDistribuidora" del D1 es un 04 se siga dando de alta como hasta ahora, pero en caso contrario se escriba en el log el código y el mensaje ocsum 

![image](https://user-images.githubusercontent.com/47117960/68782242-59ef9f00-0639-11ea-977e-9fc09f4a3f32.png)
)

![image](https://user-images.githubusercontent.com/47117960/68782838-501a6b80-063a-11ea-8b94-f0d5293b9195.png)

**Comment by JMunoz17** [comment]
He hecho lo siguiente:

Si el contrato **NO** tiene el check de autoconsumo marcado y el **MotivoCambioATRDesdeDistribuidora** es **diferente de '04'** entonces mostramos un mensaje en el log (**Ej: Código 02 - Telegestión No Operativa**) y creamos la linea en el histórico de acciones (¿es correcto esto?).

El resto de situaciones funcionarían igual que hasta ahora.
Lo que no me termina de cuadrar es: Para los códigos de **MotivoCambioATRDesdeDistribuidora** **'05'** o **'08'** no debería funcionar igual que para el **'04'**?

Lo tenéis subido en **PRE**.

**Comment by bpesquero** [comment]
No es exactamente lo que tiene que hacer. 
Tipo distinto de 04-->en cualquier caso, independientemente de si tiene check de autoconsumo o no si el tipo es diferente de 04 debe hacer es mostrar mensaje en el log y no crear línea en histórico de acciones.
Tipo 04--> Lo que hace ahora

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

**Comment by bpesquero** [comment]
He salido y he entrado.
He intentado cargar un fichero con motivo de cambio 08 y me ha dado el siguiente error

ERROR. El contrato COM/00137 no tiene asociado un contrato de autoconsumo vigente para la fecha 18/10/19.

Está mal. Debería haberme indicado "motivo de cambio 08..."

**Comment by JMunoz17** [comment]
La ruta de importación correcta es: \\NI\Esios\OCSUM\GAC\Importados en esa ruta hay un fichero con código '04' por eso te muestra ese error.

He visto que el fichero que tiene '08' esta en \\NI\Esios\OCSUM\GAC tienes que meterlo en la otra ruta y revisa el tipo de fichero porque con ese tipo no lo va a procesar.

**Comment by bpesquero** [comment]
Probado y ok
