### ISSUE TITLE
NAV - Problema al cargar un F1 (URGENTE)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#684]
Cuando lo intento cargar me sale el log de “La fecha no es válida”, pero no consigo dar con ello.

\\NI\Esios\F1\WAIT ERIC\20191021_GAC_Iberdrola (57)_FECHA NO VALIDA

**Comment by JMunoz17** [comment]
Se trataba de un contrato con P1D sin término de energía y sin medidas P1D.
Era el primer caso que nos encontrábamos por lo que hemos tenido que cambiar varias cosas en la importación del F1 y en la facturación.

Hemos generado la compra y la venta:

COM/01300
FC/201902613
FV/201912595

**Comment by bpesquero** [comment]
Probado ok
