### ISSUE TITLE
WEB y NAV  - informe detalle facturación ACSM

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#685]
Me he dado cuenta de que hay que volver a cambiar esto.Se trata del Excel que se baja el cliente con el detalle de facturación desde la página para el caso de autoconsumo. 
Al excel habitual se le han añadido las columnas: energía excedentaria, precio de mercado y valoración de energía excedentaria (multiplicación de los dos anteriores).
En realidad tendría que ser:
-energía excedentaria
-PMD
-Control de factor de potencia
-Peaje a la generación(en la tabla de configuración de energía)-->Solo para NC y NF en caso contrario poner a 0
-Impuesto de generación (en la tabla de configuración de energía)-->Solo para NC y NF en caso contrario poner a 0
-Valoración de energía excedentaria -->Energía excedentaria * (PMD + Control de FActor de potencia)*(1-impuesto de generación)+Energía excedentaria*peaje

**Comment by bpesquero** [comment]
PMD
En el PMD aparece en la cabecera /kWh sin embargo habéis multiplicado por 1000 en vez de dividir entre 1000. 
En cualquier caso creo sería mejor expresarlo en €/MWh tal y como se hace en la columna correspondiente a energía suministrada
Peaje a la generación y %impuseto
Entiendo que aparecen a cero en los contratos que estoy revisando porque tiene algoritmo S, verdad? Si hubiéramos utilizado estos valores para el cálculo de la energía excedentaria (algortimo NF o NC si aparecería, verdad?
Es que no tengo ninguno en esta situación y no lo puedo probar

**Comment by JMunoz17** [comment]
Tienes este de NF para probar en GEOATLANTER:
Contrato -> COM/00916
Factura -> C/201901614
Contrato Autoconsumo -> AUT000066

**Comment by bpesquero** [comment]
Comprobado lo del peaje a la generación y el impuesto  y ok. En cualquier caso insisto con el tema de las unidades

PMD en cabecera pone €/kWh para ellos habría que haber dividido entre 1000 en vez de multiplicar por 1000. En cualquier caso creo que sería mejor dejar los precios en €/MWh como aparecen en el resto de columnas, en todas las correspondientes a suminsitro
Control de factor de potencia--> poner en €/MWh
Reserva de potencia adicional a subir--> poner en €/MWh

**Comment by bpesquero** [comment]
He comprobado que el informe de detalle de facturación accesible desde NAV que debería ser idéntico al colgado en la web no ha incluido los detalles incorporados de la parte de autoconsumo, en particular, las energía excedentaria.

**Comment by JMunoz17** [comment]
Lo correspondiente al informe que descarga el cliente desde la web lo hemos modificado ya y lo hemos incluido en la subida de tareas de web que se esta realizando hoy a producción.

Respecto al informe de detalle de facturación accesible desde NAV si me puedes indicar desde donde lo ejecutas ya que no se a cual te refieres.

**Comment by dgarciageo** [comment]
Buenas Jaime,

El informe es este:

![image](https://user-images.githubusercontent.com/47117960/72274734-fe3b9500-362c-11ea-9b2a-6b215991e776.png)

**Comment by JMunoz17** [comment]
La parte de la web ya se subió ayer.

La parte de NAV acabo de subirla a PRE y PROD, tanto la pantalla que visualizáis desde NAV como la exportación a excel que podéis generar desde dicha pantalla (esto ultimo no he podido probarlo en vuestro servidor con los datos reales porque no esta instalado el excel, revisad que este correcto por favor).

Estos son los valores añadidos:
"Energia exportada a red (kWh)"
"Precios Pool (Euros/MWh bc)"
"Control de Factor de Potencia (MWh bc)"
"Reserva de potencia a subir(MWh bc)"
"Peaje a la Generacion (Euros/kWh)"
"Porcentaje Impuesto de generacion"
"Valoracion de energia excedentaria (Euros)" 	

He puesto cada valor en las unidades que me habéis indicado en los anteriores mensajes, es correcto que saquemos la energía exportada a red y el peaje a la generación en KWH y los demás en MWH? O ponemos estos dos también en MWH? Me vais diciendo.

**Comment by bpesquero** [comment]
EStá probado y está ok, con la salvedad de que me gustaría que todos los precios aparecieran en €/MWh y el peaje permanece en €/kWh

Gracias

**Comment by JMunoz17** [comment]
Y la energía exporta a red? Ahora mismo aparece en KWH, lo cambiamos a MWH tambien no?

Lo modificaremos en el informe que se exporta desde la web, en la pantalla de detalle de facturación y en la exportación de excel que se puede realizar desde dicha pantalla.

**Comment by bpesquero** [comment]
La energía tiene menos importancia. La consumida la mostramos en kWh y en MWh. lo ideal sería hacer lo mismo,  y si no, dejarla en kWh que es la unidad que el cliente maneja.

**Comment by JMunoz17** [comment]
Modificado y subido a PRE y PROD en el formulario de detalle de factura y en la exportación de Excel.

Queda pendiente introducir la modificación en el informe que se saca en la web (lo hacemos con la próxima modificación de la web de geo, probablemente mañana).

**Comment by JMunoz17** [comment]
Ya esta subida la parte de la web.
