### ISSUE TITLE
Control baja de clientes

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#686]
Hay que introducir un control para controlar los clientes que cesan su contrato de comercialización teniendo una ficha de autoconsumo.
1.- En la carga de los ficheros C1 y C2 paso 06 y 011 si el contrato tiene una ficha de autoconsumo en vigor hay que escribir en el log
"El contrato tiene activa una ficha de autoconsumo"

2.- Al introducir una fecha de fin en la ficha de contrato si tiene un autoconsumo activo debe saltar un error: "El contrato tiene activa una ficha de autoconsumo"

**Comment by JMunoz17** [comment]
Subido a PRE.

**Para el punto 1:**
Para buscar el contrato de autoconsumo uso la Fecha de Activación en los pasos 06 y la Fecha Activación Prevista en el paso 011. Solo mostramos aviso en el log, por lo que en el histórico de acciones se creará un nuevo registro.

**Para el punto 2:**
Para buscar el contrato de autoconsumo uso la Fecha Final que esta insertando el usuario.
El control lo hago usando solo la fecha de fin de los contratos de autoconsumo por lo que saltará si existe algún contrato de autoconsumo sin fecha de fin o con fecha de fin superior a la fecha insertada por el usuario.

**Comment by dgarciageo** [comment]
**CHECK PUNTO 1 OK**

![image](https://user-images.githubusercontent.com/47117960/69154193-d40fa000-0adf-11ea-944f-63a90b682863.png)

**CHECK PUNTO 2 OK**

![image](https://user-images.githubusercontent.com/47117960/69154530-76c81e80-0ae0-11ea-8f80-cf5c78ceb70b.png)
