### ISSUE TITLE
WEB - errata contrato - condiciones particulares

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#69]
Al descargar el contrato en el momento de firma o una vez firmado aparece

"en concepto de contraprestación por los servicios de intermediación en el mercado, fijada en 2 € al mes , según el caso."

La coletilla de "según el caso" hay que quitarla.

**Comment by PKFEric** [comment]
CORREGIDO->PROBAR

**Comment by bpesquero** [comment]
Probado y ok
