### ISSUE TITLE
WEB - No funciona reseteo de contraseña en próxima

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#693]
![image](https://user-images.githubusercontent.com/47117960/70727839-ad204480-1d00-11ea-979f-4a256390e99a.png)

Además sería interesante tener la opción de mostrar la contraseña en los formularios de acceso y registro tanto en próxima como en atulado
 
![image](https://user-images.githubusercontent.com/47117960/69640924-82c35b80-105f-11ea-8a42-36c66335a1ee.png)

**Comment by PKFEric** [comment]
Esto ya esta solucionado

**Comment by dgarciageo** [comment]
El problema era otro. Incidencia resuelta
