### ISSUE TITLE
WEB - Cambiar entrada de usuario para el IBAN (Alta nuevo contrato área privada y pública)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#694]
- [ ] Mejora en la contratación web, sería interesante que el IBAN se pudiese copiar y pegar sin tener que ir de 4 en 4 números

- [x] Al añadir contrato, le hace repetir la cuenta de banco, lo suyo sería que le pusiera su cuanta actual y con opción de cambiarla si lo necesita

**Comment by PKFEric** [comment]
SUBIDO A PRO EN PROXIMA

**Comment by PKFEric** [comment]
SUBIDO A PRO EN A TU LADO

**Comment by dgarciageo** [comment]
El punto 1) Mejora en la contratación web, sería interesante que el IBAN se pudiese copiar y pegar sin tener que ir de 4 en 4 números no se ha realizado.  Aún así damos por cerrada la incidencia.

**Comment by dgarciageo** [comment]
El javascript de validación del IBAN en proxima y atulado en Alta de nuevo contrato **(desde la parte privada)** produce un comportamiento extraño cuando se copian y pegan valores en las celdas del IBAN. Lo copiado en la primera celda de machaca con lo introducido en la segunda ?¿

**Más que corregir el script de validación lo que queremos es que el IBAN se pueda copiar y pegar sin tener que ir de 4 en 4 números no se ha realizado** respetando el comportamiento ya implementado del punto:

> Al añadir contrato, le hace repetir la cuenta de banco, lo suyo sería que le pusiera su cuanta actual y con opción de cambiarla si lo necesita

--


--------------------------------------------------------------------------------------------
Copiando 4 primeros caracteres: ES66
![image](https://user-images.githubusercontent.com/47117960/72337918-b156cd80-36c3-11ea-8ac1-61751873df43.png)

copiando 4 siguientes caracteres: 2100
![image](https://user-images.githubusercontent.com/47117960/72338011-d6e3d700-36c3-11ea-9eea-0d1c9ef026a7.png)

**Comment by dgarciageo** [comment]
Descartado por nueva web pero punto 1 sigue pendiente
