### ISSUE TITLE
NAV - Dar de alta proveedor en la carga de ficha NC

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#696]
Al cargar una ficha de autoconsumo NC debe
1.- Dar de alta un proveedor con el mismo CIF que el cliente
2.- Generar un nº de serie al proveedor

ESto se está haciendo ya la parte de representación cuando se sincronizan proveedores.

**Comment by JMunoz17** [comment]
Vamos a crear un nuevo campo en conf. compras para seleccionar un numero de serie para estos proveedores.
Traspasamos datos como: nombre, cif/nif, dirección y similares.

Que mas datos debemos rellenar y que utilizamos como origen de estos?
Grupo contable negocio, grupo registro iva negocio, grupo contable proveedor, ....?
Cod. terminos de pago, cod. forma pago, ...?

**Comment by dgarciageo** [comment]
![image](https://user-images.githubusercontent.com/47117960/70533843-2c274880-1b5a-11ea-9994-980191a40920.png)

**Comment by JMunoz17** [comment]
Subido a PRE.

El cliente a partir del cual se crea el proveedor es el titular del contrato.

Origen de datos (Grupo contable negocio, grupo registro iva negocio, grupo contable proveedor, Cod. terminos de pago, cod. forma pago): De configuración de compras.

Nº Serie Proveedor: Nº serie estándar, como si se crea un proveedor a mano.

Códigos de serie factura/abonos: No los rellenamos. En el proceso al que hacéis referencia de la web de representación recibimos estos códigos y lo único que hacemos es crear el nº de serie en NAV si no existe. En este caso no tenemos forma de saber los códigos de serie.

**Comment by bpesquero** [comment]
He estado probando esto

1.- He hecho una primera prueba y he visto
    - Un proveedor se ha creado correctamente, pero al número de serie le falta el check de "planta"
    - Se ha creado un segundo proveedor para otro proyecto pero no se le ha asignado nº de serie

2.- He borrado los proveedores y las fichas de autoconsumo y he vuelto a importar para hacer otra prueba y me da el siguiente error

![image](https://user-images.githubusercontent.com/20299071/71193266-1ddbd980-228a-11ea-8677-df0db004ea42.png)

**Comment by JMunoz17** [comment]
Respecto a la primera prueba:
- Los códigos de serie de facturas/abonos no los rellenamos. En el proceso de la web de representación donde se crean proveedores nosotros recibimos los códigos de serie de facturas/abonos y en función de estos podemos ver si existe como número de serie en NAV y en caso contrario crearlo. En este proceso no tenemos forma de hacerlo, de esto estaba ya al tanto Dani.
- El primer proveedor que me indicas que se ha creado correctamente realmente no se ha creado mediante este proceso, sino que ya existía en NAV. Por eso este proveedor si que tiene nº de serie asignado. En el log te lo indica:
![image](https://user-images.githubusercontent.com/26869276/71658526-b0797f80-2d44-11ea-9026-54122e463ddb.png)
- El segundo proveedor que me indicas si se ha creado mediante este proceso y tiene sentido que no tenga nº de serie de facturas ni abonos asignado.
![image](https://user-images.githubusercontent.com/26869276/71658607-02baa080-2d45-11ea-8068-c669df673054.png)

Respecto a la segunda prueba:
- No he conseguido replicar el fallo, si te vuelve a suceder avísame y me conecto contigo para verlo.

**Comment by bpesquero** [comment]
NUMEROS SERIE FACTURA Y ABONO
En relación al número de serie de abono y factura, la idea sería crear un código cualquiera a partir del nombre o CIF o NIF del proveedor.
Por ejemplo: dos primeras letras del nombre, dos primeras letras apellido y 2 últimos dígito del NIF/CIF  y dos últimos dígitos del año.
A la serie de abono le añadiríamos una "A" delante.
Este número de serie debe llevar el check de planta.

**Comment by bpesquero** [comment]
Cierro esta incidencia y la fusiono con la #731
