### ISSUE TITLE
WEB - Implementación fichero M en Próxima y A tu lado e integración con Signaturit (Ainhoa)

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#698]
Hay que definir que casos

Que se esta haciendo en HECEn en GEo y hacer propuyeta comun para mabos casos

Codifciacion contrtaos COM + Flag M

**Comment by dgarciageo** [comment]
Esta tarea ya esta contenida en la #572 y la #573. Se cierra para evitar duplicidades
