### ISSUE TITLE
NAV - Reparto automático CC facturas OMIE #664

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#701]

**Comment by dgarciageo** [comment]
Consulta de Fer

COM$Coefs_Facturas_OMIE

 ten cuenta que el coeficiente es, en compras, COM/PRE 
y en ventas PRE/COM

**Comment by dgarciageo** [comment]
my\ORA

![image](https://user-images.githubusercontent.com/47117960/70540332-57636500-1b65-11ea-9624-85e32fc141c1.png)


Con split
![image](https://user-images.githubusercontent.com/47117960/70528412-6ee32380-1b4e-11ea-8b60-91a6d7c7e4cd.png)

Sin split
![image](https://user-images.githubusercontent.com/47117960/70528434-7c98a900-1b4e-11ea-81b6-06193eefaf45.png)

**Comment by JMunoz17** [comment]
Respuesta vía mail.

**Comment by dgarciageo** [comment]
Las facturas sin reparto estan ok. Pero en las facturas con reparto el campo cantidad tiene que ser 1  luego directamente el importe del reparto en el coste unitario e importe linea

![image](https://user-images.githubusercontent.com/47117960/71381001-0413fc80-25d2-11ea-9066-5b2798dc73b3.png)


lo que hemos subido a PRE crea el siguiente tipo de factura con reparto (ej. factura de compra en PRE, **OMIEC00024**)

![image](https://user-images.githubusercontent.com/47117960/71381131-8d2b3380-25d2-11ea-9b67-8bed8285c605.png)

**Comment by JMunoz17** [comment]
![image](https://user-images.githubusercontent.com/47117960/72513887-fd357e00-384d-11ea-9730-1f92b0db932e.png)

Modificado y subido a PRE.

**Comment by dgarciageo** [comment]
Las facturas y los repartos se realizan correctamente, pero Ainhoa necesita que se rellenen algunos campos adicionales para no tener que actualizar las facturas a mano.
Los cambios son tanto para Geo como para Hecen

--------------------------------------------------
Descripción **(tanto en compra como en venta)** tiene que poner : Liquidación OMIE
 
![image](https://user-images.githubusercontent.com/47117960/72669321-afc53680-3a30-11ea-8b60-bf3db18f0e66.png)

--------------------------------------------------

En **venta** (nº de factura) tiene que quedar así (igual en los dos campos), ya que por defecto en el primero aparece sólo el número.

![image](https://user-images.githubusercontent.com/47117960/72669347-e9963d00-3a30-11ea-8e3a-9562362ec86f.png)

--------------------------------------------------

En **compra** sólo en la de nº de doc externo, ya que no hay nº siguiente de factura y el nº serie de registro es C-FACR1.
 
![image](https://user-images.githubusercontent.com/47117960/72669361-1b0f0880-3a31-11ea-804a-ef52c7ff9856.png)

 --------------------------------------------------

Tanto en **compra como en venta** el código periodo de energía será 202002/202002 (año mes) dependiendo del periodo de energía :
 
![image](https://user-images.githubusercontent.com/47117960/72669365-2bbf7e80-3a31-11ea-8d54-890bf7372f98.png)

 
Sería 201912

**Comment by JMunoz17** [comment]
Subido a PRE.

Para rellenar el valor de la dimensión Periodo de Energía utilizamos la **fecha de inicio** del periodo de facturación, Ok? 13/12/19 -> 201912

**Comment by dgarciageo** [comment]
ok, jaime. 

Súbelo a PRO para que lo podamos probar por favor

Muchas gracias

**Comment by JMunoz17** [comment]
Subido a PRO.

**Comment by bpesquero** [comment]
Al cargar las facturas de OMIE da este error
“Este mensaje es para programadores de C/AL:  Ha habido un problema al llamar al miembro getSalesCoef. System.Data ha devuelto el siguiente mensaje: No se puede encontrar la tabla 0. “

**Comment by JMunoz17** [comment]
No tenemos acceso a vuestro servidor, en cuanto podamos entrar lo reviso.

En cualquier caso, tienes instalado en el ordenador donde lo has ejecutado el setup que os pasamos?

**Comment by bpesquero** [comment]
Si, lo tiene instalado.

**Comment by JMunoz17** [comment]
He probado a lanzar el proceso de importación en producción y ha funcionado sin problema, las facturas generadas son estas:
Venta: FV/2020001296..FV/2020001302
Compra: FC/2020001511..FC/2020001517

El problema tiene que ser que el setup que os pase no este instalado en el ordenador desde el cual lo ejecutasteis o que hubiese algun problema en ese momento para conectar con my/ORA.

**Comment by bpesquero** [comment]
Le hemos reinstalado el setup, hemos entrada, salido, reinciado y de todo y sigue dando el problema en el equipo de Ainho. En el equipo de Dani si funciona. Si queréis conectaros a su equipo o lo que queráis para intentar que funcione.

**Comment by JMunoz17** [comment]
El lunes, si a Ainhoa le viene bien, nos conectamos con ella y lo revisamos.

**Comment by JMunoz17** [comment]
He hablado con Dani para que de permisos en my/ORA al usuario de Ainhoa.
Aunque no he llegado a conectarme con ella he replicado el error y el problema no esta en la instalación del automation sino en la conexión con la base de datos donde estan los coeficientes de reparto.

He dejado GEO PRE preparado para que podáis probar la importación desde el pc de Ainhoa, debería de importarse una factura de venta.
Quedo a expensas del resultado de las pruebas.

**Comment by dgarciageo** [comment]
Se subió a PRO y funciona correctamente
