### ISSUE TITLE
WEB - Recuperación contraseña

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#71]
Al recuperar la contraseña no se valida la misma, se puede meter una formada unicamente por números, por ejemplo, pero luego no te deja entrar con esa contraseña.

**Comment by PKFEric** [comment]
En el botón de recuperar contraseña

**Comment by PKFEric** [comment]
MODIFICADO-> PROBAR

**Comment by bpesquero** [comment]
Ok. Pero una vez modificada, cuando sale el mensaje de contraseña modificada debería devolverte a la página de inicio porque si no parece que está dando error.

**Comment by PKFEric** [comment]
MIRA A VER AHORA CREO QUE ASI QUEDA GUAY, Creo que te he sacado del server ya puedes volver a entrar.

**Comment by bpesquero** [comment]
Perfecto!!!
