### ISSUE TITLE
WEB - INCIDENCIA CÓDIGO POSTAL 

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#710]
Desde el área de clientes, al introducir un CP con varias poblaciones (eg. 19141)  no te deja seleccionar ninguna que no sea la de por defecto!

![image](https://user-images.githubusercontent.com/47117960/70236016-61035c00-1764-11ea-835e-be59cb59d106.png)

**Comment by PKFEric** [comment]
ARREGLADO Y SUBIDO A PRO

**Comment by dgarciageo** [comment]
Test ok
