### ISSUE TITLE
WEB - Incluir validación email en formulario de alta

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#711]
Es muy frecuente que los clientes se equivoquen al introducir el correo.
Meter text area de validacion de email en Alta usuario tanto en Proxima como en atulado 

![image](https://user-images.githubusercontent.com/47117960/70240488-99f3fe80-176d-11ea-99b6-2da78031a91b.png)

**Comment by PKFEric** [comment]
Ya comentado por telefono.
Decidimos no hacer nada, ya se hace una validacion en los mails de proxima y a tu lado que controla con una expresion regular que se introduce texto @ texto "." y texto

**Comment by dgarciageo** [comment]
Cerramos incidencia
