### ISSUE TITLE
NAV - Facturas regularizadoras

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#722]
La fecha de comienzo del periodo de regulación no es correcto

![image](https://user-images.githubusercontent.com/47117960/70910373-e5c96200-200f-11ea-9c1b-2782948bcef5.png)

![image](https://user-images.githubusercontent.com/47117960/70910464-0e515c00-2010-11ea-8d1d-e238b63e8115.png)

![image](https://user-images.githubusercontent.com/47117960/70910566-422c8180-2010-11ea-8b0d-48cf67ce6c02.png)

**Comment by JMunoz17** [comment]
El formato mostraba la fecha desde y fecha hasta de la factura, los cuales vienen informados en el F1 como fecha factura desde y fecha factura hasta. Estas fechas no coinciden con las fechas de regularización.

Hemos modificado tanto el formato de GEO como el de HECEN para que si se trata una G busque en las lineas de termino energía y termino potencia la menor y la mayor fecha.

Subido a PRE y PROD.

**Comment by JMunoz17** [comment]
Dani, he dejado la factura generada en la carpeta que has creado.

**Comment by bpesquero** [comment]
Hemos revisado la factura 
\\ni\EsiosPre\Jaime\C_201902533.pdf
y, salvo error por nuestra parte, es idéntica a la anterior y sigue mal.

**Comment by JMunoz17** [comment]
Antigua:
![image](https://user-images.githubusercontent.com/26869276/72156476-f1f9d280-33b5-11ea-8efe-8e0edde9b6a1.png)

Nueva:
![image](https://user-images.githubusercontent.com/26869276/72156490-fa520d80-33b5-11ea-9cfe-2e6d59cd2d45.png)

La modificación es en las fechas de Factura Regularizadora (abajo). 
Entiendo que el periodo de facturación debe seguir con las mismas fechas.

**Comment by bpesquero** [comment]
Tienes razón. Perdona.
