### ISSUE TITLE
NAV - Importar pedidos ACSM en Navisión

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#725]
Tenemos que importar los pedidos de autoconsumo a Navision

hemos creado un procedimiento almacenado 

TAU.ACSM.[dbo].[GetPresupuestoAcsm] (@Nav_PedidoId varchar(50))

Que recibe como parámetro el Id de pedido que se va a crear en NAV y devuelve un listado de Oferta - Proveedor - Productos que aún no se hayan importado en NAV como un pedido

**Comment by JMunoz17** [comment]
Esta tarea es la misma que la #656 ?? Si es así, unifica la información en una sola y elimina la otra por favor. También esta creada la #655 que hace referencia a lo mismo.

Necesitaría también un .bak para ver que datos tenéis y ya después comentamos todo.

**Comment by dgarciageo** [comment]
Unifico esta tarea #725 en  la #656
