### ISSUE TITLE
WEB - Atulado: ERROR Alta nuevo contrato dese Área privada

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#727]
Al intentar hacer click sobre esta check box da error

![image](https://user-images.githubusercontent.com/47117960/71478985-c7731b80-27f2-11ea-8fde-f84b55932302.png)

![image](https://user-images.githubusercontent.com/47117960/71479008-e1acf980-27f2-11ea-9662-84166114578a.png)

**Comment by jorgereal** [comment]
Corregido y subido a PROD.
