### ISSUE TITLE
NAV - dirección de envío y suministro en factura

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#73]
En el pdf de factura en la dirección de envío (en la cabecera) y en la dirección de suministro (en datos de contrato) sólo viene la calle, no aparece el nº ni demás datos.

**Comment by bpesquero** [comment]
En la dirección de envío sale dos veces la escalera. En la dirección de suministro no sale la escalera.

**Comment by PKFEric** [comment]
PROBAR AHORA

**Comment by bpesquero** [comment]
En la dirección de suministro sale esc dcha y en el contrato veo que ya no está puesto...

**Comment by PKFEric** [comment]
Pruebalo otra vez Belen, ya esta modificado.

**Comment by bpesquero** [comment]
probado y ok

**Comment by PKFEric** [comment]
Ya esta modificado y probado al 100%
 1- Sin escalera en ambas direcciones
 2- Con escalera en envio y sin en suministro
 3- Con escalera en suministro y sin en envio
 4- Con escalera en ambas
