### ISSUE TITLE
NAV - Problemas facturación NC

### ISSUE THREAD

**Issue by JMunoz17** [PKFEric/webProxima#731]
1.- Obliga a configurar en configuración de contabilidad-->suministro los no de serie de factura de compra de autoconsumo y de abono, cuando realmente no se usan para nada 
2.- No he podido verificar si al importarlas fichas se crea el nº de serie de abono del proveedor, o sólo el número de serie de facturas
3.- Al actualizar los números de serie (compras--> importación de facturas--> actualiza serie de planta) se actualizan los números de serie de las plantas de representación, entiendo que busca por que tenga el id planta distinto de vacío. NO sé si podríamos, al crear los números de serie de autoconsumo con la importación de fichas, marcar de alguna manera, quizá poniendo un id planta 0 a todoas, para que al ejecutar el proceso se actualicen también estos números de serie.
4.- La factura de compra no rellena el periodo de facturación
5.- Si tenemos una factura sin medidas no debería hacer la factura de compra, la de venta tiene sentido por el TP pero la de compra no.

**Comment by JMunoz17** [comment]
1.	Lo tenemos hecho de tal manera que si se usan, el Nº de la PRE-Factura/PRE-Abono de compra se genera a partir de estos números de serie. Los números de serie configurados en los proveedores se usan para los históricos. 
2.	Esto te lo contesto en la tarea #696. No tenemos forma de crear los números de serie de factura/abono del proveedor en la importación de contratos de autoconsumo. Este tema casi mejor va a ser que cuando vuelvas de vacaciones me des un toque y lo vemos a ver si hay alguna forma de hacerlo.
3.	Filtra por el valor del campo “Planta” a Si. En caso de que encontremos la forma de crear nosotros los números de serie bastaría con marcar este check.
4.	Modificado y subido a PRE y PROD.
5.	Modificado y subido a PRE y PROD. Regeneradas las facturas para el COM/01426 (FV/2020000012 y FV/2020000013, revisad que este todo ok, la de octubre la he generado forzando facturación con fecha desde = 01/10/19 y fecha hasta 31/10/19 y sin marcar ningún check).

**Comment by bpesquero** [comment]
lo hemos vuelto a probar y tenemos esto:
-el periodo de facturación se ha rellenado sólo en cabecera, no en líneas.
-no se rellena el valor de los campos Nº fatura de proveedor y Nº de siguiente factura, con lo cual no se podría registrar la factura.

**Comment by bpesquero** [comment]
RESPUESTA DE JAIME

Modificamos el proceso para que rellene el periodo de facturación en las líneas de la factura de compra.
El campo Nº siguiente factura no es necesario rellenarlo porque ya damos valor al campo Nº Serie Registro.
Para el campo Nº factura proveedor vamos a crear un campo en la configuración de compras donde seleccionar un numero de serie que utilizaremos en este caso, te vale de esta forma?

**Comment by bpesquero** [comment]
El problema fundamental que estamos teniendo es que no se ha replicado el comportamiento de los proveedores y facturación de representación tal y como se pidió.
Con los de representación cuando se importa un proveedor se genera (mediante un código aportado por nosotros) un número de serie de preabono y prefactura. ESte número de serie lleva marcado el check de planta. 
Luego, cuando se factura, en la prefactura o preabono correspondiente se rellena con el número de factura de proveedor y el número de siguiente factura con el número asignado de prefactura, porque los tres campos deben tener obligatoriamente el mismo valor.

![image](https://user-images.githubusercontent.com/20299071/72153004-f4a3fa00-33ac-11ea-84b0-f57e39e406a3.png)

ES por ello que digo que no necesitamos para nada los números de serie que nos habéis metido en configuración, ya que el preabono y prefactura de cada proveedor lleva un número de serie diferente, que es el que debe crearse cuando se genera el proveedor.
Para dar de alta esos números de serie, la idea sería crear un código cualquiera a partir del nombre o CIF o NIF del proveedor.
Por ejemplo: dos primeras letras del nombre, dos primeras letras apellido y 2 últimos dígito del NIF/CIF y dos últimos dígitos del año.
A la serie de abono le añadiríamos una "A" delante.
Este número de serie debe llevar el check de planta.

**Comment by JMunoz17** [comment]
Vamos a crear los números de serie con el siguiente código:
-Facturas: F + CIF/NIF (9 dígitos) -> Ejemplo numeración facturas: F45302345J/20200001 - F45302345J/20209999
-Abonos: A + CIF/NIF (9 dígitos) -> Ejemplo numeración abonos: A45302345J/20200001 - A45302345J/20209999

Mejor hacerlo con el NIF entero que poniendo letras del nombre, apellido, etc.. que aunque es dificil que pase si que es posible que nos encontremos con algún duplicado. 

Esta parte la tenéis subida solo en PRE, he realizado la importación y se han creado dos contratos de autoconsumo: AUT00107 y AUT00108, y dos proveedores: PROV0934 y PROV0935 con sus numeros de serie asociados.

**Comment by JMunoz17** [comment]
Por otro lado he modificado el proceso de facturación para que en aquellos contratos de autoconsumo con algoritmo NC se genere la factura de compra con el periodo de facturación relleno en las líneas (en la línea de la retención no).

También hemos modificado el proceso para que el Nº Siguiente Factura y el Nº Factura Proveedor se rellenen con el nº de la propia pre-factura de compra.

Hemos eliminado los campos creados en su día en la configuración de contabilidad para el nº de pre-factura y el nº de pre-abono que utilizábamos en la facturación de los contratos de autoconsumo con algoritmo NC.

**Comment by bpesquero** [comment]
¿Lo podéis subir a PRO para hacer las pruebas?

**Comment by JMunoz17** [comment]
Lo acabo de subir.
Sal y vuelve a entrar para asegurarnos que refresca.

**Comment by bpesquero** [comment]
Acabamos de probar a importar una ficha NC y, salvo error por mi parte,
1.- No se ha creado el proveedor
2.- No se han creado los números de serie
3.- Teníamos una prefactura de compra RAGAR/20200011 que hemos borrado y ahora nos encontramos como si fuera una factura de compra pero poner documento eliminado.

**Comment by JMunoz17** [comment]
Respuesta vía mail.

**Comment by bpesquero** [comment]
1.- Al crear el proveedor el código término de pago debe ser el que tenga el cliente asociado
2.- Al crear el proveedor el grupo contable de negocio debe ser C ENERG
3.- Necesitaba en la ficha de factura el campo de contrato así que he cambiado yo la ficha. Aviso para que no nos pisemos
4.- Cuando intento registrar una factura de venta si finalmente no puedo porque da error en ese mismo proceso el registro de la factura de compra, en la factura de venta se marca el nº de siguiente factura. No tiene que hacerlo. Acabo de comprobar que se han ido registrando todas. Así que tenemos registrada la misma factura un montón de veces.
![image](https://user-images.githubusercontent.com/20299071/72722915-c928c880-3b7f-11ea-9def-4d2e011c52c8.png)
5.- Al registrar la factura de venta me ha dado el siguiente error pero se han registrado tanto la de compra como la de venta. Ya lo he rellenado.
![image](https://user-images.githubusercontent.com/20299071/72723924-33426d00-3b82-11ea-8be2-3b3386348cc9.png)
6.- Al imprimir el pdf de la factura de venta sale lo siguiente
![image](https://user-images.githubusercontent.com/20299071/72724937-f1ff8c80-3b84-11ea-9842-b189544eda0d.png)

Lo primero, la tabla tiene mal los borde.
Lo segundo los textos no aparecen adecuados para enviarlos al cliente. Tendría que poner algo así como "Importe factura de suministro", "Importe factura de excedentes" y por último el "Importe a pagar". El importe de la factura de excedentes irá en negativo para que se sepa que se minora del coste de la factura de suministro.
EL pdf tiene que incluir también la factura de excedentes. es lo que hablamos, van las dos facturas en el mismo pdf y además en la de suministro aparece el importe de pago.
NO podemos subir la factura por tanto no podemos seguir probando la parte web

**Comment by JMunoz17** [comment]
1- Modificado, subido a PRE y PROD.
2- Modificado, subido a PRE y PROD. Nuevo campo en configuración de compras.
3- OK, objeto actualizado en todas las bases de datos.

4 y 5- Tenemos un problema con estos puntos:
No podemos evitar que si falla el registro de la compra no se haya registrado la venta (punto 4), ni tampoco que si da error en la liquidación (punto 5) no se hayan registrado las facturas de venta y compra, que es lo que ha pasado.
Vamos a modificar el proceso de tal forma que vais a tener que registrar la factura de venta primero y la factura de compra después, pero las dos de forma manual. Trataremos de que la liquidación entre ambas se realice de manera automática al registrar la compra, pero es posible que tenga que ser otro proceso ajeno que tenga que ejecutar el usuario.

6- Lo revisamos una vez solucionemos el punto 4 y 5.

**Comment by bpesquero** [comment]
4 y 5- Se me ocurre para facilitar las cosas en los casos normales de uso que al registrar la de venta se registra también la de compra, tal y como está con la salvedad de que si se ha registrado la de venta se elimine la prefactura de venta y permita registrar manualmente la de compra.
En cuanto a la liquidación lo ideal sería tenerlo en los siguientes procesos:
a) registro de factura de venta: tras la el registro de ambas facturas, si no se realiza el registro de la factura de compra no se realiza la liquidación
b) registro de la factura de compra: tras el registro de la factura de compra se realiza la liquidación
c) proceso independiente por si falla la liquidación en a) o en b)

Digo esto porque con la solución que dabas, para solucionar los casos en que haya problema complicamos mucho la operativa del 90% de las situaciones en que no hay problema.

¿Sería posible?

**Comment by bpesquero** [comment]
En cuanto al punto 6
La factura de compra (excedentes) tiene que tener el mismo formato que la factura de venta (suministro), con la salvedad de que no hay que meter el gráfico de medidas, ni la tabla de medidas (consumos) ni la imagen de origen de energía.
En lugar de la información del consumo pondríamos el detalle de la factura que actualmente aparece en el reverso.

![image](https://user-images.githubusercontent.com/20299071/72788462-4280f380-3c32-11ea-8016-78f4171858e5.png)

![image](https://user-images.githubusercontent.com/20299071/72788574-6b08ed80-3c32-11ea-89c4-e25ad22cad8d.png)

Adicionalmente creo que tanto en la factura de venta (para cualquier tipo de autoconsumo) como en la de compra (para las NC) en el cuadro de detalles del contrato habría que  poner el CAU debajo del CIL.
Debajo de fecha fin de contrato de suministro pondría "Tipo de autoconsumo" que puede tomar los valores:
-"compensación simplificada": para los casos de SC,SF
-"sin compensación simplificada": para los casos NC,NF

Por último a la derecha de tipo de autoconsumo pondría "Pontecia de la instalación de autoconsumo" con el valor de la potencia de la instalación de la ficha de autoconsumo.

Cualquier duda preguntadme y lo vemos
