### ISSUE TITLE
NAV - Filtros en pantalla de "Productos por almacén"

### ISSUE THREAD

**Issue by JMunoz17** [PKFEric/webProxima#732]
Sacar en la pantalla de “Productos por almacén” los filtros de categoría, grupo y marca.

**Comment by JMunoz17** [comment]
Subido a PRE.

Si necesitáis que lo suba directamente a PROD me decís.

**Comment by bpesquero** [comment]
Subir a PRO. En cualquier caso nos haría falta también el proyecto, y de la categoría y grupo necesitaríamos el nombre no el código.

**Comment by JMunoz17** [comment]
Subido a PRE y PROD con las modificaciones incluidas.
