### ISSUE TITLE
NAV - Facturar proyecto desde ficha de contrato de autoconsumo

### ISSUE THREAD

**Issue by JMunoz17** [PKFEric/webProxima#733]
Crear factura de venta desde la ficha del contrato de autoconsumo:

1.- Crearía una factura de venta

2.- Crearía una primera línea con el importe
- si la instalación es no financiada la inversión total (coste total)
- si la instalación es financiada sólo la parte no financiada (coste total - principal financiado)

3.- Crearía, igual que como habíamos dicho, las líneas correspondientes a los productos asociados a ese proyecto.

**Comment by JMunoz17** [comment]
Subido a PRE.

Si necesitáis que lo suba directamente a PROD me decís.

**Comment by bpesquero** [comment]
Estoy intentando probar en PRE
Creo la serie de facturas registradas
![image](https://user-images.githubusercontent.com/20299071/72728011-a6e97780-3b8c-11ea-8f94-c9833856ba19.png)

Lo pongo en configuración de ventas
![image](https://user-images.githubusercontent.com/20299071/72728031-b23ca300-3b8c-11ea-9417-e0e42a007121.png)

Y cuando voy a facturar me dice

![image](https://user-images.githubusercontent.com/20299071/72728054-c2548280-3b8c-11ea-8439-ed76041c813b.png)

**Comment by JMunoz17** [comment]
Te explico por qué era, para poder usar la serie AUT en las facturas de venta registradas tiene que estar relacionada con la serie por defecto de las facturas de venta registras establecida en la configuración de ventas (en este caso, V-FACR).

Para relacionarla, en Administración -> Configuración -> General -> Nos. Serie -> Filtras por V-FACR -> Abajo a la derecha botón relaciones -> Introduces la seria que desees.

En cualquier caso, para este caso esto nos da igual por lo que he modificado el proceso para que salte esta validación, ya te debería dejar .

**Comment by bpesquero** [comment]
Hemos probado y hemos visto lo siguiente:

- pedido recibido y facturado--> se trae las líneas ok a la factura.
- pedido  no facturado ni recibido (abierto o lanzado)--> no se trae las líneas a la factura. ESto es ok, pero sería muy útil que nos avisara de que tenemos pedidos abiertos asociados a ese proyecto
-Si tengo una prefactura hecha y vuelvo a lanzar el proceso de facturar proyecto se genera de nuevo la factura
-Si tengo una factura registrada y vuelvo a lanzar el proceso de facturar proyecto se genera de nuevo la factura

**Comment by PKFEric** [comment]
Crear en la cabecera de Autoconsumo Nº Prefactura Venta Instalacion y Nº Factura Venta Registrada Instalcion. Cuando se crea la prefactura se rellena y cuando se registra se rellenan correspondientemente. Si se borra la prefactura, se ha de borrar el numero de prefactura. Si los campos ya estan rellenos se mostara un mensaje infromando de que ya esta facturarda la instalacion.

Estos campos han de ser editables desde el contato de autoconsumo por si se hace un Abono Manual de la factura de la instalacion.

**Comment by JMunoz17** [comment]
Subido a PRE.

**Comment by bpesquero** [comment]
Algunas cuestiones

1.-Nos hemos dado cuenta que los productos referentes a pedidos asociados al proyecto que tengan grupo contable de producto SERV RECI no deben ser incluidos en las líneas de la factura.

2.-No incluye en la línea correspondiente a la venta de instalación no se rellena el Cod dimensión, pese que la dimensión está informada en el producto utilizado (P0118-->	Instalación Autoconsumo)	

3.-No incluye en la cabecera de la factura el nº de contrato

**Comment by JMunoz17** [comment]
Puntos 1 y 3 modificados.
Punto 2: En todas las pruebas que he hecho las dimensiones del producto se traspasan correctamente a la linea de la factura.  Podéis repetir la prueba y me decís el numero de factura para revisarlo (como hemos restaurado la bbdd de pre ya no tengo acceso a los datos de las pruebas que hicisteis el otro dia).

**Comment by bpesquero** [comment]
Probado y ok

El punto 2 también es ok.

**Comment by JMunoz17** [comment]
Subido a PROD.

**Comment by bpesquero** [comment]
Retomamos esta tarea ya que al probarlo en PRO vemos que al crear las factura de venta de la instalación, en el detalle de las líneas que se insertan a 0 está metiendo las facturas de compra de Energy de peajes

![image](https://user-images.githubusercontent.com/20299071/75240749-276f4980-57c5-11ea-97b7-24e3cee4e03f.png)

**Comment by JMunoz17** [comment]
Vamos a crear un campo en los productos, un check "Producto ACSM" para llevarnos este dato a los movimientos de producto y así poder filtrarlos y evitar que salgan el resto de movimientos asociados al Cód. Proyecto. Os parece?

**Comment by bpesquero** [comment]
Si, otra opción es hacerlo sobre los pedidos no sobre las facturas y menos aún sobre las facturas energy.

Como creáis que es mejor

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

Tenéis un campo nuevo "Producto ACSM" en la ficha del producto que debéis marcar para aquellos productos que se deban tener en cuenta en la facturación. En los movimientos de producto hay un nuevo campo calculado que tira del check de la ficha del producto y que utilizamos para filtrar a la hora de generar la factura.

**Comment by bpesquero** [comment]
Me podéis hacer el campo editable en la lista de productos para que podamos actualizar los valores de todos los productos?

**Comment by JMunoz17** [comment]
Ya lo tenéis.

Tened cuidado al navegar por la lista ya que esta editable por completo, cuando terminéis de configurar los valores avisadme y lo dejo como estaba.

**Comment by bpesquero** [comment]
Marcados los productos. Podemos poner la lista de nuevo como no editable.
Hacemos prueba y os decimos.
