### ISSUE TITLE
NAV - incidencia en la venta del COM/00992 

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#747]
Tengo una incidencia en la venta del COM/00992 que es la siguiente:

![image](https://user-images.githubusercontent.com/47117960/72336922-f548d300-36c1-11ea-805a-49a09936c79e.png)

Ya   existe el/la Hour Measure Header Origen   Datos='Perfil',CUPS='ES0031405299522002HX',Nº   Contrato='COM/00992',Fecha='09/11/18',Nº factura acceso   CCH='F6901Y00019983'.  Campos y valores identificativos:  Origen   Datos='Perfil',CUPS='ES0031405299522002H
--

**Comment by PKFEric** [comment]
Solucionado con moinca.
