### ISSUE TITLE
WEB - Error de validación de CP en cambio de titular (Caso 1 y 2)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#751]
En los 2 casos de uso de cambio de titularidad:

 1. Titular distinto de pagador
 2. Mismo pagador y titular
 
En ambas webs la validación del CP no es correcta.
Si se introduce por ejemplo el CP 19162 se rellena el 2º desplegable con las poblaciones correspondientes pero no se puede cambiar el valor.

![image](https://user-images.githubusercontent.com/47117960/72525453-7f30a180-3864-11ea-94fd-ee5a1cd5bc11.png)

![image](https://user-images.githubusercontent.com/47117960/72522477-19d9b200-385e-11ea-970a-8f74fcacd4ab.png)

Si se introduce el 19162 C.P no te deja cambiar de piblación

![image](https://user-images.githubusercontent.com/47117960/72522448-03335b00-385e-11ea-81f6-f484079b140f.png)

Este problema ya se corrigió en el Alta de un nuevo contrato tanto desde la parte pública como de la parte web privada pero no se revisó el cambio de titularidad en las 2 webs

**Comment by bpesquero** [comment]
Probado y ok
