### ISSUE TITLE
WEB - Error cambio de titularidad al adjuntar documentación (Casos 1 y 2)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#752]
Revisar proceso de cambio de titularidad (ambos casos de uso) porque falla cuando se adjunta documentación si el documento ya se existe en el servidor (la primera vez que se sube el fichero no falla)

![image](https://user-images.githubusercontent.com/47117960/72524788-f6653600-3862-11ea-8732-5f3ed8499822.png)

**Fallan ambos casos tanto en proxima como en atulado y el mensaje es el mismo en ambas webs**
![image](https://user-images.githubusercontent.com/47117960/72535396-c6c12880-3878-11ea-955d-cbd0b4e2dcba.png)

---------------------------------------

![image](https://user-images.githubusercontent.com/47117960/72523453-1cd5a200-3860-11ea-8b08-f83d9fe8feb0.png)

![image](https://user-images.githubusercontent.com/47117960/72523541-59090280-3860-11ea-93d3-602cc7714b22.png)

**Comment by jorgereal** [comment]
Hemos probado este bug y solo hemos conseguido replicar el error en caso de que el fichero estuviese abierto en el servidor.
En el resto de casos sustituye el fichero existente por el nuevo.

¿Se encontraba el fichero abierto durante vuestras pruebas?

Por otra parte hemos pensado concatenar el número de contrato al nombre del fichero, para evitar reemplazos de documentos procedentes de distintos usuarios si el nombre es el mismo.

**Comment by dgarciageo** [comment]
No teníamos el fichero abierto en el servidor. Es una incidencia que nos han pasado desde atención al cliente por lo que sucede sin abrir el fichero en el servidor
Si re nombráis el fichero con el número de contrato no sé si se solventa la incidencia porque esto se suele dar cuando el mismo cliente intenta dar de alta un contrato varias veces porque le da error la pagina o porque se ha equivocado en algún dato y lo vuelve a crear con datos corregidos.
Lo vuelvo a probar y te llamo para verlo juntos

**Comment by jorgereal** [comment]
Hemos optado por añadir fecha/hora en formato "ddMMyyhhmmss" al comienzo del nombre del fichero para imposibilitar que se suban ficheros con el mismo nombre y así evitar los bloqueos.

Se ha hecho en ambas webs y se han subido a PROD.
