### ISSUE TITLE
WEB - Error en cambio de titularidad al Volver a la home  (Caso 1 y Caso 2)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#753]
Al finalizar el proceso de cambio de titularidad (Titular distinto de pagador) se manda el correo a Ainhoa correctamente pero aparece el siguiente mensaje

![image](https://user-images.githubusercontent.com/47117960/72534835-cb391180-3877-11ea-9282-95780f3cc06f.png)

![image](https://user-images.githubusercontent.com/47117960/72533012-b0b16900-3874-11ea-85cb-5694f8f968df.png)

![image](https://user-images.githubusercontent.com/47117960/72533098-dc345380-3874-11ea-8a17-e2c9bba59dfa.png)

**Comment by bpesquero** [comment]
Finalizamos el proceso, pone terminado pero no nos llega el email, en signaturit tampoco ha salido.
AL dar a volver a la home te lleva a un página en blanco.

**Comment by PKFEric** [comment]
A signaturit no se envia un cambio de Titular no??? 

Lo demas ya esta corregido.

**Comment by dgarciageo** [comment]
No se manda signaturit. Probado y ok
