### ISSUE TITLE
WEB Atulado - Problemas M1 / Signaturit

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#756]
**PARTE WEB**

Quitar la validación de las potencias respecto a la tarifa y en su lugar mostrar tabla informativa con los límites de potencia
![image](https://user-images.githubusercontent.com/47117960/72668726-185ce500-3a2a-11ea-9510-f313f92ab32b.png)

- Al hacer click en el botón "Cambiar tarifa" o "Cambiar potencia" mostrar mensaje de:
Estamos realizando tu cambio. No cierres ni refresques la página hasta que se muestre la confirmación.

----------------------------------------------------------------------------------------

**EMAILS DE SIGNATURIT**

Hay que cambiar el asunto y el cuerpo del email que manda signaturit dependiendo del caso.
 - Cambio de potencia
-  Cambio de tarifa
-  Cambio de tarifa + potencia

----------------------------------------------------------------------------------------
**EMAILS**

Cuando se realiza un cambio de tarifa o cambio de tarifa con potencia llega correo informativo y además llega correo de error

![image](https://user-images.githubusercontent.com/47117960/72552451-3219f300-3897-11ea-90c4-a846b20493a3.png)

![image](https://user-images.githubusercontent.com/47117960/72552439-29c1b800-3897-11ea-911b-c3ef661ccfed.png)

----------------------------------------------------------------------------------------
**POTENCIAS**

Se están informando los mismos precios para todas las tarifas en el proceso de  modificación de tarifa y/o potencia

![image](https://user-images.githubusercontent.com/47117960/72668945-51965480-3a2c-11ea-8eef-f2a0084079eb.png)

![image](https://user-images.githubusercontent.com/47117960/72668973-7a1e4e80-3a2c-11ea-9681-f8e4e4fa5ff0.png)

**Comment by dgarciageo** [comment]
CAMBIO DE POTENCIA

![image](https://user-images.githubusercontent.com/47117960/72552524-5a095680-3897-11ea-9edd-400994976df1.png)

![image](https://user-images.githubusercontent.com/47117960/72552550-65f51880-3897-11ea-820a-a1246cb3e5da.png)

**Comment by dgarciageo** [comment]
3) CAMBIO DE TARIFA + POTENCIA

![image](https://user-images.githubusercontent.com/47117960/72552614-8b822200-3897-11ea-8080-bd11c8f589b2.png)

Llega correo informativo
![image](https://user-images.githubusercontent.com/47117960/72552652-9dfc5b80-3897-11ea-9181-631892604d1a.png)

Y además llega correo de error
![image](https://user-images.githubusercontent.com/47117960/72552669-ab194a80-3897-11ea-9dcc-aacab5bc9401.png)

**Comment by bpesquero** [comment]
En cuanto los mails de signaturit

Asunto del mensaje tanto en A tu lado como en Próxima:
-Cambio de potencia de tu contrato de suministro de energía eléctrica
-Cambio de tarifa de tu contrato de suministro de energía eléctrica
-Cambio de potencia y tarifa de tu contrato de suministro de energía eléctrica

El cuerpo de mensaje para A tu lado

Estimado cliente:

Para finalizar el proceso de modificación de tu contrato de suministro de energía eléctrica con A tu lado Energía, deberás firmar el contrato que encontrarás a continuación.

Si tienes cualquier duda, estaremos encatados de atenderte en el correo clientes@atuladoenergia.com o, en horario laboral, a través de nuestro número de teléfono gratuito 900 264 267.

Muchas gracias por contar con nosotros. Trabajaremos para no defraudar tu confianza.

www.atuladoenergia.com


Cuerpo del mensaje desde Próxima Energía:


Estimado cliente:

Para finalizar el proceso de modificación de tu contrato de suministro de energía eléctrica con Próxima Energía, deberás firmar el contrato que encontrarás a continuación.

Si tienes cualquier duda, estaremos encatados de atenderte en el correo clientes@proximaenergia.com o, en horario laboral, a través de nuestro número de teléfono gratuito 900 818 852.

Muchas gracias por contar con nosotros. Trabajaremos para no defraudar tu confianza.

www.proximaenergia.com
