### ISSUE TITLE
WEB Proxima - Problemas M1 / Signaturit

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#757]
**PARTE WEB**

Cuando se informa una nueva potencia no se está teniendo en cuenta la tarifa
- Mostrar tabla informativa con los límites de potencia
![image](https://user-images.githubusercontent.com/47117960/72668726-185ce500-3a2a-11ea-9510-f313f92ab32b.png)

- Al hacer click en el botón "Cambiar tarifa" o "Cambiar potencia" mostrar mensaje de:
Estamos realizando tu cambio. No cierres ni refresques la página hasta que se muestre la confirmación.

-----------------------------------------------------------------
**EMAILS DE SIGNATURIT**

Hay que cambiar el asunto y el cuerpo del email que manda signaturit dependiendo del caso.
 - Cambio de potencia
-  Cambio de tarifa
-  Cambio de tarifa + Potencia
-----------------------------------------------------------------

**CAMBIO DE TARIFA.** 

Tarea: Corregir XML_M1 y signaturit. No se genera potencia el campo sale a cero, y en Signaturit también sale vacío el campo de potencia.

![image](https://user-images.githubusercontent.com/47117960/72668577-9ae4a500-3a28-11ea-97d4-1697916e9b60.png)

El correo que le llega a ainhoa también esta mal
![image](https://user-images.githubusercontent.com/47117960/72727893-5bcf6480-3b8c-11ea-967e-aecb6473c941.png)

-----------------------------------------------------------------

 **CAMBIO DE POTENCIA.** 

Tarea: Corregir XML_M1. Se produce un error al generar el M1 y salen potencias a -1 en el xml

![image](https://user-images.githubusercontent.com/47117960/72668609-09c1fe00-3a29-11ea-81dc-d23218d6f454.png)

![image](https://user-images.githubusercontent.com/47117960/72668601-f6169780-3a28-11ea-814f-123c0326a950.png)
-----------------------------------------------------------------

 **CAMBIO DE TARIFA + POTENCIA.** 

XML y Signaturit ok

**Comment by bpesquero** [comment]
probado y ok  la necesidad de coherencia desde la web de tarifa y potencia
