### ISSUE TITLE
WEB Atulado - Alta nuevo contrato - Potencias en blanco signaturit

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#758]
Las potencias no se están rellenando en el PDF de signaturit

![image](https://user-images.githubusercontent.com/47117960/72668469-8c49be00-3a27-11ea-9d2a-6d4f37b00a18.png)

**Comment by bpesquero** [comment]
Para un ejemplo que tenemos hoy hemos visto que las potencias salen bien pero la tarifa sale mal
![image](https://user-images.githubusercontent.com/20299071/72897315-fad99500-3d21-11ea-985d-2893cbcf1054.png)

**Comment by jorgereal** [comment]
Corregido y subido a PROD
