### ISSUE TITLE
NAV- HECEN/10318 factura G

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#759]
Al cargar el fichero F correspondiente a una factura G da el error
![image](https://user-images.githubusercontent.com/20299071/72884356-4a11cc80-3d06-11ea-8b79-b48b324ab642.png)

Realmente el fichero está bien, parece que no se hace la comprobación adecuada que consiste en restar la energía ya facturada. Me extraña mucho porque esto lleva implementado mucho tiempo funcionando bien.

**Comment by PKFEric** [comment]
El fichero no estaba bien. El termino de Energia empezaba el dia 01-10 y al sumarle 1 dia empezaba el dia 2-10, la factura que regulariza empieza el dia 01-10 por lo tanto no la cogia, he hablado con monica y he modificado el XML para que las fechas de Energia resten 1 dia mientras que las demas fechas sigan el criterio normal. ya esta generada la compra y la venta.
