### ISSUE TITLE
WEB-Instalar aplicación para tracking de mails

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#76]

**Comment by bpesquero** [comment]
Pendiente de enviar en copia a la dirección gestion@proximaenergia.com los mails que salen automáticamente desde NAV

**Comment by PKFEric** [comment]
Ya esta añadido, probar si llegan los mails a la cuenta oculta.

**Comment by bpesquero** [comment]
AL imprimir la factura me da error

Te lo envío por mail
