### ISSUE TITLE
Excepcion controlada web: ERROR No existen direcciones de envio para este cliente

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#760]
Nos están llegando estas 2 excepciones de manera repetida pero no estamos seguros de qué se trata:

**Proxima**

Excepcion controlada web: ERROR: Rellena Cliente Por Customer Code NAV CLIENTE:CL01698, EXCEPCION->No existen direcciones de envio para este clienteCL01698 STACK->   en WebDefinitivaGeoatlanter.clsNavision.rellenaClientePorCustomerCodeNav(clsCliente& cliente) en C:\Users\jreal\Source\Repos\WebProxima\WebDefinitivaGeoatlanter\clsNavision.cs:línea 725 22/01/2020 16:35:01

-------------------
**Atulado**

Excepcion controlada web: ERROR: Rellena Cliente Por Customer Code NAV CLIENTE:CL07786, EXCEPCION->No existen direcciones de envio para este clienteCL07786 STACK->   en webATuLado.clsNavision.rellenaClientePorCustomerCodeNav(clsCliente& cliente) 22/01/2020 16:29:32 </br>

**Comment by jorgereal** [comment]
Estos errores se deben a clientes que no tienen dirección de envío porque no se dieron de alta desde la web.
Independientemente de que estos clientes tengan o no facturación electrónica deberían tener la dirección de envío informada para futuras notificaciones.

**Comment by dgarciageo** [comment]
Buenas Jorge,

Pero cuando se producen estos errores? Tiene algo que ver con la web?

**Comment by PKFEric** [comment]
se ha solucionado introduciendo la direccion de envio?

**Comment by PKFEric** [comment]
Revisada no aplica.

**Comment by bpesquero** [comment]
¿Por qué no aplica?
Yo croe que habría que pasar un proceso para rellenar las direcciones de envío.

**Comment by PKFEric** [comment]
Dijo Dani que ese contrato lo habia creado alguien que no sabian que tenian que crear la direccion de envio para un cliente que luego hay que enlazar en la web. Ya la crearon.

Si hay que pasar un proceso me lo comentais, me decis el criterio a seguir, si poner la direccion fiscal del cliente pagador, la del titular o la direccion de suministro para rellenar los contratos que no tengan direccion de envio.

**Comment by bpesquero** [comment]
Eric, se podría ver cuantos contratos y cuales tenemos en esta situación? ¿Me puedes sacar una consulta?

**Comment by jorgereal** [comment]
Listado de contratos sin dirección de envío adjuntado por mail.
