### ISSUE TITLE
NAV-GEO-Problema facturación F1

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#763]
Tenemos una serie de contratos que al  cargarlos devuelve el error 
Error XML, la fecha inicio facturacion del contrato 05/12/19 no coincide con el minimo de las fechas desde 04/12/19 del TP

Yo lo he revisado y parece todo correcto. 

Envío por mail uno de ejemplo, en particular el correspondiente al contrato COM/01894.
Tenemos 7 en la misma situación.

**Comment by PKFEric** [comment]
El problema de este XML es el orden de la potencia, al leer el XML para el cambio de Año se entiende que viene primero Fecha X de 2019 hasta 31 de enero de 2019 y fecha desde 01 enero 2020 hasta Fecha Y en el XML viene al reves viene primero infomrado el tramo de 2020 y luego el de 2019 si se cambia el orden se carga sin priblema, el del COM/01894 ya esta generada la compra.

**Comment by PKFEric** [comment]
Ejemplo Como tendira que venir.

![PotenciaCorrecto](https://user-images.githubusercontent.com/20229934/73651842-9ef9ff00-4685-11ea-86fd-38d66fde6e3c.JPG)


Como vienen las fechas:

![PotenciaIncorrecto](https://user-images.githubusercontent.com/20229934/73651853-a5887680-4685-11ea-8877-e6edb3c56910.JPG)

**Comment by PKFEric** [comment]
Revisado con Monica.

**Comment by bpesquero** [comment]
¿qué habéis hecho?¿se han modificado a mano o lo hemos implementado?
