### ISSUE TITLE
NAV-Geo y HECEN - Error carga F1 problema con fecha hasta

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#764]
Al cargar F1 nos da el siguiente error

Error XML, la fecha hasta de AE del Cierre 31/12/19 es diferente de la fecha hasta AE del peaje 07/01/20 y de la fecha hasta CCH 07/01/20

Yo lo he mirado y lo veo correcto. Tenemos 2 de Geo y 7 de HECEN en esta situación

Envío ejemplo por email

**Comment by PKFEric** [comment]
Acabo de hablar con Monica sobre esta incidencia, el problema de los de la Distribuidora del Cantabrico es que en el cambio de Año también desglosan el cierre en 2 para antes de que acabe el año y para despues Ejemplo:

 
![CambioCierre](https://user-images.githubusercontent.com/20229934/73530819-85547f80-4419-11ea-92ff-36f9340c19ca.JPG)


Esto no esta implementado, solamente esta implementado para el desglose del peaje por que nunca ninguna distribuidora en el cambio de año ha desglosado además el cierre.

No se si quieres que lo implemente o lo cambiáis a mano o como procedo.

**Comment by bpesquero** [comment]
Lo cambiamos a mano
