### ISSUE TITLE
NAV-GEO-Error carga F1 comparación con F5D sin CCH

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#765]
Al cargar un fichero F1 da el siguiente error

 Error XML, TE de F1 572 es diferente de AE de F5d 0

La factura no tiene F5D. EL F1 no tiene nodo de CCH. Por tanto, nunca debería comparar el cierre con esa medida.
Envío fichero de ejemplo por email

**Comment by PKFEric** [comment]
Este contrato tiene tipo autoconsumo 41, por eso esta entrando en ese control. Llamame para hablarlo

**Comment by bpesquero** [comment]
Toda la razón es un caso que no contemplé.
Vamos a cambiar cuando aplica la función FUNCONTROL_CIERRE_F5D_F1()
que pasará a aplicarse cuando:


El tipo   de autoconsumo OCSUM de la ficha de contrato es <>00 y no tiene ficha de autoconsumo
 o 
el tipo de autoconsumo OCSUM de la ficha de de contrato es   <>00 y tiene ficha de autoconsumo activa para las fechas de la factura.

**Comment by PKFEric** [comment]
vContinua:= false;
vContinua1:= false;
vContinua2:= false;

rLContract.RESET;
rLContract.SETRANGE("Contract Code",vGtxtContrato);
rLContract.SETFILTER("Tipo Autoconsumo",'<>%1','00');
IF rLContract.FINDFIRST THEN BEGIN

    //++#765
    //Vamos a cambiar cuando aplica la función FUNCONTROL_CIERRE_F5D_F1()
    //que pasará a aplicarse cuando:
    //El tipo de autoconsumo OCSUM de la ficha de contrato es <>00 y no tiene ficha de autoconsumo
    rLContratoAutoconsumo.RESET;
    rLContratoAutoconsumo.SETRANGE("Cod. Contrato",rLContract."Contract Code");
    if NOT rLContratoAutoconsumo.FINDFIRST then
      vContinua1:= true;

    //El tipo de autoconsumo OCSUM de la ficha de de contrato es <>00 y tiene ficha
    //de autoconsumo activa para las fechas de la factura.
    rLContratoAutoconsumo.RESET;
    rLContratoAutoconsumo.SETRANGE("Cod. Contrato",rLContract."Contract Code");
    rLContratoAutoconsumo.SETFILTER("Fecha Inicio Vigencia",'..%1',vGFechaDesdeAutoconsumo);
    rLContratoAutoconsumo.SETFILTER("Fecha Fin Vigencia",'%1|%2..',0D,vGFechaHastaAutoconsumo);
    if rLContratoAutoconsumo.FINDFIRST then
      vContinua2:=true;

    if NOT (vContinua1 or vContinua2) then
      exit;
    //--#765

**Comment by PKFEric** [comment]
He añadido el codigo y he cargado el F da este error:

Error Factura, no coinciden los periodos del contrato 3 y del peaje 6 en Potencia demandada.

Se lo voy a comentar a monica no obstante el contrato es :  COM/00962

**Comment by PKFEric** [comment]
Revisado con monica
