### ISSUE TITLE
WEB - A tu lado - CArga de facturas

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#766]
Cuando desde la web de a tu lado das a "Mis facturas" se queda "pillado"  no sale nada

![image](https://user-images.githubusercontent.com/20299071/73075469-488a0500-3ebc-11ea-90f5-c0fc0fc1c887.png)

Ha llegado algún mensaje de error en este sentido

Excepcion controlada web: ERROR: Recuperar Todos los abonos y facturas de
cliente NAV  CLIENTE:CL00824, EXCEPCION->Se excedió el tiempo de espera de
la operación STACK->   en
System.Web.Services.Protocols.WebClientProtocol.GetWebResponse(WebRequest
request)
   en
System.Web.Services.Protocols.HttpWebClientProtocol.GetWebResponse(WebRequest
request)
   en System.Web.Services.Protocols.SoapHttpClientProtocol.Invoke(String
methodName, Object[] parameters)
   en webATuLado.WS.facturas_Binding.ReadMultiple(facturas_Filter[] filter,
String bookmarkKey, Int32 setSize)
   en webATuLado.clsNavision.getAllFacturasAbonosSimpleByCustomerCode(String
customerCode, List`1 listaContratos, String& bookMarkKeyFacturas, String&
bookMarkKeyAbonos, Int32 size) 24/01/2020 14:57:45 </br>

**Comment by jorgereal** [comment]
Hemos vuelto a levantar la WEB de a tu lado y hemos probado a realizar varias consultas de facturas con algunos de los usuarios con los que falló durante el viernes 24 y sábado 25.

No han vuelto a producirse los timeouts y los tiempos de respuesta no superan los 2-3 segundos.
Entendemos que fue un error puntual de rendimiento del sql.

Estaremos pendientes por si vuelven a producirse para buscar el problema.

**Comment by PKFEric** [comment]
Se ha `probado y no pasa, seria un tema de conectividad.
