### ISSUE TITLE
WEB - A tu lado - Problema con CP

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#767]
AL selecconar el CP 28523
salen las siguientes poblaciones
![image](https://user-images.githubusercontent.com/20299071/73075820-1331e700-3ebd-11ea-8284-69bb946bf12f.png)

En realidad las poblaciones de ese código postal son 

![image](https://user-images.githubusercontent.com/20299071/73075847-28a71100-3ebd-11ea-851b-c0e0192ce8f0.png)

Si me decís donde cambiarlo lo puedo hacer yo misma. TEnemos un cliente que no se puede dar de alta por este motivo

**Comment by jorgereal** [comment]
Hemos corregido las poblaciones del código postal 28523 tanto en GEO como en HECEN.

Los pasos a seguir son: 
-Cambiar en mySQL en las bases de datos de hecen_localizaciones y geo_localizaciones, tabla "codigopostal" el nombre de la población.
-Crear en NAV en la tabla "Post Codes" nuevos registros con las nuevas poblaciones y eliminar las existentes para ese código postal. (Importante que se creen como nuevos registros y eliminar los anteriores, en este caso no vale con cambiar los campos de Población, Buscar población y Población 2).

**Comment by bpesquero** [comment]
Probado y ok
