### ISSUE TITLE
Problema reganecu extrap

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#768]
Estamos teniendo problema con el reganecu de Baleares y Canarias de la C2 de noviembre. 
Lo que hemos localizado es que los movimientos del segmento IEED que tienen signo negativo no se tienen en cuenta en la facturación.
Los reganecus están cargados y las prefacturas hechas pendientes de registrar.

**Comment by PKFEric** [comment]
Hemos revisado con monica y fernando el reganecu y el problema en la generacion de las facturas es que el segmento IEED solo para el caso de canarias y baleares hay que aplicarlo solo a la venta tanto si la magnitud es positiva o negativa. De esta manera el importe coincide con la factura de MEFF, estamos implementando esta particularidad.

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
Respuesta vía mail.
