### ISSUE TITLE
NAV-WEB-Geo-Alta de contrato

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#770]
Un cliente se ha dado de alta en la web y se ha creado un contrato en NAV (COM/02173), En el contrato no estaba rellena la tarifa de acceso (al parecer el cliente no la ha rellenado, por lo que nos dice) y estaban rellenas las tres potencias. EL contrato no ha salido desde signaturit.
Es un cliente desde el punto de vista mediático muy  importante para nosotros, y la verdad que ha sido nefasto esto para nosotros. Para darle una salida cuanto antes he asignado la tarifa en NAV y he borrado en la tabla las potencias P1 y P3 que no le correspondían.
A ver si podemos revisar en la web que datos se introdujeron y replicar el caso.

**Comment by PKFEric** [comment]
Aqui hay un problema, Como me comentaste, un cliente desde tu hogar puede dar de alta una 3, el problema esta en que se le esta diciendo desde la web que si contratas para tu hogar pone que para potencias superiores a 10 se le aplica el 0,05 por Kwh, en cambio si contatas para tu hogar y contratas una 3.1A con potencias inferiores a 10 entonces habria que cobrarle 2€. Las tarifas de NAV estan configuradas para que a la 3.1A se le aplique siempre 0,05. Entonces habria que cambiar esto para que si las potencias son inferiores a 10 se le pueda cobrar 2€?

**Comment by bpesquero** [comment]
Teníamos esto pendiente. Efectivamente si la potencia es menor a 10 habría que cobrar 2 €/mes independientemente de la tarifa. Me decís que tengo que hacer en configuración?

Gracias

**Comment by PKFEric** [comment]
Esto tenemos que modificarlo en NAV y web mañana estar solucuionado y te digo como lo hemos planteado.

**Comment by jorgereal** [comment]
Hemos modificado la web y NAV para que a partir de ahora el margen que viaja al contrato dependa de si alguna de las potencias contratadas supera 10kW (variable) o no (fijo).

Para ello es necesario rellenar en el tipo de contrato en NAV ambos márgenes.
Si no queremos que se actualicen los márgenes en los contratos ya existentes deberemos indicarlo en la ventana de diálogo que aparecerá al modificar cualquiera de los dos campos.

Después es necesario entrar en la parte de administración de la web para sincronizar las tarifas con NAV.

A partir de ese momento aplicará la nueva lógica para llevar al contrato un margen u otro.

Nosotros hemos modificado ya en producción la tarifa 3.1A aplicándole un margen fijo de 2€.
