### ISSUE TITLE
NAV-Geo-Hecen-Generación de A3, C1 y C2 con dirección fiscal diferente

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#771]
Si realizas un A3, o un C1/C2 con el indicativo de que el cliente tiene dirección de suministro distinta a la fiscal 
![image](https://user-images.githubusercontent.com/20299071/73359343-ec9af400-42a0-11ea-9edf-d4b9eabcac6c.png)
sale el siguiente mensaje 

![image](https://user-images.githubusercontent.com/20299071/73359425-18b67500-42a1-11ea-90a1-3a618984dad2.png)

Le damos a si

![image](https://user-images.githubusercontent.com/20299071/73359440-1f44ec80-42a1-11ea-87bb-c787a0930111.png)

**Comment by PKFEric** [comment]
Ya esta modificado en el A3 C2 y M1 el C1 no aplicaba.

Hemos añadido el nodo Via y hemos modificado el campo Municipio para que coja como nos comento Ainhoa el "CodigoProvincia+CodigoMunicipioINE" y tambien rellenamos el TipoVia siempre con el valor "CL" de la tabla 12 de Ocsum que se corresponde con "Calle" por que este valor no existe para ser seleccionado en la direccion fiscal del titular. Si quereis otro valor o que esto sea seleccionable me lo comentais. Habria que crear en la ficha del cliente el valor a seleccionar de OCSUM "Un campo mas"

**Comment by PKFEric** [comment]
![Captura](https://user-images.githubusercontent.com/20229934/73824159-f7eaa400-47f9-11ea-884a-481cd25e6431.JPG)

**Comment by PKFEric** [comment]
Ya no da error la validacion contra el Esquema
