### ISSUE TITLE
Web-Próxima-Formulario de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#772]
A modo mejora, para cuando se pueda, lo he estado comentando con Ainhoa, y  no sé si podemos incorporar algún mensaje en la web para que cuando se bajan el formulario de autoconsumo y además;

 

Le diga que tiene que adjuntar la curva de consumo de un año, que en las mayoría de las veces no la adjunta, la factura también es importante para comprobar los datos, pero si viene bien relleno el formulario no es imprescindible y se entiende que algún cliente sea reacio a darla…
Indicarle a que correo tiene que mandarlo, creo que no está claro.
Indicarle que hemos recibido su solicitud correctamente y que en unos días ( se puede establecer un plazo para que no llamen a los dos días, no sé.)  nos pondremos en contacto con ellos…

**Comment by dgarciageo** [comment]
No aplica con el nuevo proceso de contacto ACSM
