### ISSUE TITLE
URL - Problemas de acceso Endesa

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#774]
Desde Endesa nos indican que no pueden acceder a los documentos que les envíamos, ni de forma automática ni a través del método post con usuario y contraseña

¿Se os ocurre qué podríamos hacer?

**Comment by PKFEric** [comment]
Contestado por email

**Comment by PKFEric** [comment]
Esta tarea la paso a Done?? ya la resolvimos via telefono

**Comment by bpesquero** [comment]
ok
