### ISSUE TITLE
Web- próxima - Texto a mostrar en solicitud de cambio desde la web

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#775]
Cuando se solicita un cambio de potencia o un cambio de tarifa que también puede llevar asociado un incremento de potencia, el texto a mostrar, como ya hacemos en A tu lado es

**Te informamos que cualquier modificación técnica, implica un coste por parte de la distribuidora de 9,04 €+IVA, en concepto de derechos de enganche, que te repercutiremos sin ningún margen ni comisión por nuestra parte. Adicionalmente, te informamos de que cualquier aumento de potencia, además de los 9,04 €+IVA de derechos de enganche, implica también el cobro de otros derechos por parte de la distribuidora. Llámanos y te informamos de todo

**Comment by PKFEric** [comment]
Lo hemos añadido en Cambio de Potencia y Cambio de Tarifa, ya existia el texto. Hemos añadido la parte de Adicionalmente, te informamos de que cualquier aumento de potencia, además de los 9,04 €+IVA de derechos de enganche, implica también el cobro de otros derechos por parte de la distribuidora. Llámanos y te informamos de todo
