### ISSUE TITLE
Problema código postal

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#776]
AL tratar de dar de alta un nuevo contrato al introducir el CP está dando error indicando que es extrapeninsular, y no es así.

CP: 12166- Els Ibarsos
Municipio: Serra d'en Garceran
Provincia: Castellón

**Comment by PKFEric** [comment]
Ya esta solucionado, esta pedania no existia en la tabla de codigos postales de NAV. El INE no la tiene registrada como tal, sino que pertenece al municipio de SIERRA-ENGARCERAN, creo que seria necesario revisar la tabla de Codigos Postales de NAV, obtener de algun sitio la relacion de Codigos Postales con codigos INE y cargar los que faltan, seguramente haya mas casos.
