### ISSUE TITLE
Actualizar valores de la tabla 27 de motivos de rechazo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#777]
Nos faltan valores en la tabla 0027 de motivos de rechazo. Hay que cargarla de nuevo. Cuando vayáis a hacerlo solicitarnos los valores para la carga.

**Comment by PKFEric** [comment]
Enviame por favor los valores para poder cargarla.

**Comment by PKFEric** [comment]
Ya estan cargados.
