### ISSUE TITLE
Login área de clientes Próxima

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#778]
Al acceder al área de clientes de Próxima si se introducen usuario y contraseña INCORRECTOS y dice login correcto, pero no entra. El cliente se cree que lo ha introducido bien y no trata de recuperar contraseña, ya que, insisto, sale un mensaje de login correcto.

**Comment by bpesquero** [comment]
Por lo que nos dicen algunos usuarios cuando van a acceder si el usuario no está aún activado no pueden acceder, normal. Así que recuperan contraseña y eso si que les deja hacerlo, aunque posteriormente no pueden entrar, y se vuelven locos porque no saben por qué no acceden.
Creo que cuando el usuario no esté activado debe dar el mensaje de usuario no activado y además no debe dejar hacer un cambio de contraseña.

**Comment by PKFEric** [comment]
De momento lo hemos cambiado para que si introduce mal  el usuario cambie el mensaje. Ahora vamos con lo otro.

**Comment by bpesquero** [comment]
ok con las pruebas remitidas por Eric
