### ISSUE TITLE
WEB - Hacer proceso para borrado de usuarios web

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#78]

**Comment by PKFEric** [comment]
Ya esta creado el Procedimiento almacenado DeleteUserByEmail, falta incluirlo en la web.

Todos los usuarios de prueba han sido eliminados

**Comment by PKFEric** [comment]
Ya he creado en la web el apartado de eliminacion de clientes por email. Esta en la zona de administracion en gestion de usuarios.

**Comment by bpesquero** [comment]
Probado y ok
