### ISSUE TITLE
Web - Próximo - Texto precio

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#780]
Hay que cambiar en la home

*IVA no incluido para clientes acogidos a facturación electrónica

por 

IVA no incluido, para clientes acogidos a facturación electrónica (2,42 euros al mes IVA incluido).

**Comment by PKFEric** [comment]
Esto ya esta.

**Comment by dgarciageo** [comment]
Incidencia repetida. Test ok
