### ISSUE TITLE
NAV-Próxima-Atulado - Comentario automático en contratos

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#781]
Tanto en Próxima como en A tu lado cuando se cree un contrato hay que meter un comentario con el check de mostrar a true. 
El comentario tendrá fecha de inicio 1/1/2020 y el texto se puede copiar del ya introducido con esa fecha en todos los contratos existentes.

Ojo, porque cuando hicimos la importación con el report correspondiente salían mal todas las tildes

**Comment by PKFEric** [comment]
Ya esta añadido en el insert del contrato, lo he probado con un par y he pasado un proceso para rellenar los 2 que se crearon ayer.
