### ISSUE TITLE
NAV-Próxima-Forzar facturación algoritmo VI

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#782]
Tenemos una serie de contratos nuevos que tienen algoritmo de facturación VI y tarifa 61A.
Estos contratos empiezan el 31/12/2019.
A estos contratos no les gestionamos nosotros el peaje, por eso les hemos puesto precio 0. Por error cargamos un peaje que nos envió la distribuidora (estamos al habla con ellos para que nos envíen un abono). Como no tenemos que facturar el peaje, hemos bloqueado estos peajes tanto en la tabla de toll como en la de closing.
Queremos facturar de 31/12/2019 a 31/01/2020 ambos inclusive.

1.- Si facturamos poniendo fecha fin 31/01/2020 da un error por hueco de facturación.
2.- Forzamos facturación de 31/12/2019 a 31/01/2020. De esta forma no da ningún error, saca la factura, pero no considera las medidas del 31/01/2019. 

Hemos dejado en facturas de venta las facturas abiertas para que podáis verlas

Los contratos son

COM/01939 | OR_CON |   | PROFES. DE LA MEDICINA Y EMP. S.A. | ES0021000012404719XB
-- | -- | -- | -- | --
COM/01940 | OR_CON |   | PROFES. DE LA MEDICINA Y EMP. S.A. | ES0021000004111743VF
COM/01941 | OR_CON |   | PROFES. DE LA MEDICINA Y EMP. S.A. | ES0021000011698128VA
COM/01942 | OR_CON |   | PROFES. DE LA MEDICINA Y EMP. S.A. | ES0021000019635054PC

**Comment by PKFEric** [comment]
Ya esta solucionado y generadas las facturas,se pensaba que pasaba a contador inteligente y le sumaba 1 dia a fecha desde. Ya esta arreglado.
