### ISSUE TITLE
Creacion de efectos - ACSM

### ISSUE THREAD

**Issue by JMunoz17** [PKFEric/webProxima#783]
Temas a configurar:
 
Conf. compras-> Sección Autoconsumos
•	Diario efectos: mostrará los diarios 
•	Sección efectos: mostrará las secciones del diario anterior (ojo! Que este diario se deberá generar sin Nº de serie, y sin Nº de serie de registro)
•	% pedido a aplicar en primer hito
•	Banco puente anticipo: tirará de la lista de bancos
•	Forma de pago efecto: tirará de las forma de pago 
•	Fecha vencimiento fin obra
 
En la creación del pedido de compra habría que crear el efecto, con el siguiente criterio
1.	Si el pedido es de materiales -> se creará un efecto por el importe del pedido +  IVA
2.	Si el pedido es de mano de obra -> se crearán dos efectos, uno por un % del importe del pedido y otro por el resto
 
Para identificar si el pedido es de mano de obra serán todos aquellos que en el grupo contable de las líneas sea distinto de “SERV RECI”, y si tiene ese grupo contable serán de mano de obra. 
(Esto lo estamos usando en algún otro sitio, por lo que si está parametrizado, podemos tirar de la misma parametrización)
 
Las líneas que se deben crear en el diario general para crear estos efectos son las siguientes:

Fecha registro | Nº documento | Tipo movimiento | Nº efecto | Tipo | Nº | Importe debe | Importe haber | Cód. forma de   pago | Fecha   vencimiento | Tipo   contrapartida | Cuenta   contrpartida
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Fecha pedido | Nº pedido | Efecto | 1 | Proveedor | Proveedor del   pedido | importe pedido +   IVA |   | De la conf.   Forma de pago efecto | Fecha de pedido | Banco | De la conf.   Banco puente anticipo

Fecha registro | Nº documento | Tipo movimiento | Nº efecto | Tipo | Nº | Importe debe | Importe haber | Cód. forma de pago | Fecha vencimiento | Tipo contrapartida | Cuenta contrpartida
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Fecha pedido | Nº pedido | Efecto | 1 | Proveedor | Proveedor del pedido | (importe pedido + IVA) *   porcentaje de la conf. |   | De la conf. Forma de pago efecto | Fecha de pedido | Banco | De la conf. Banco puente   anticipo
Fecha pedido | Nº pedido | Efecto | 2 | Proveedor | Proveedor del pedido | (importe pedido + IVA) *   (1-porcentaje de la conf.) |   | De la conf. Forma de pago efecto | de la conf. Fecha vencimiento   fin obra | Banco | De la conf. Banco puente   anticipo

El diario se deberá registrar de forma automática. 

Ya de forma manual:

Se creará la OP en la que se incluirán los efectos 1, y seguirá el funcionamiento estándar de pago.

Cuando se reciba la factura, se le deberá indicar en la forma de pago, una forma de pago que esté configurada de tal forma que la cuenta que se le asigne sea el banco puente que hemos empleado para registrar los efectos, dando por liquidada la factura, y compensando la cuenta del banco puente. 
En el caso de que la factura sea de mano de obra, se deberá además, acudir al efecto número 2 y ponerle la fecha de vencimiento que le corresponda.

**Comment by JMunoz17** [comment]
Temas a configurar:
 
Conf. compras-> Sección Autoconsumos
•	Diario efectos: mostrará los diarios 
•	Sección efectos: mostrará las secciones del diario anterior (ojo! Que este diario se deberá generar sin Nº de serie, y sin Nº de serie de registro)
•	% pedido a aplicar en primer hito
•	Banco puente anticipo: tirará de la lista de bancos
•	Forma de pago efecto: tirará de las forma de pago 
•	Fecha vencimiento fin obra
 
En la creación del pedido de compra habría que crear el efecto, con el siguiente criterio
1.	Si el pedido es de materiales -> se creará un efecto por el importe del pedido +  IVA
2.	Si el pedido es de mano de obra -> se crearán dos efectos, uno por un % del importe del pedido y otro por el resto
 
Para identificar si el pedido es de mano de obra serán todos aquellos que en el grupo contable de las líneas sea distinto de “SERV RECI”, y si tiene ese grupo contable serán de mano de obra. 
(Esto lo estamos usando en algún otro sitio, por lo que si está parametrizado, podemos tirar de la misma parametrización)
 
Las líneas que se deben crear en el diario general para crear estos efectos son las siguientes:


Fecha registro | Nº documento | Tipo movimiento | Nº efecto | Tipo | Nº | Importe debe | Importe haber | Cód. forma de   pago | Fecha   vencimiento | Tipo   contrapartida | Cuenta   contrpartida
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Fecha pedido | Nº pedido | Efecto | 1 | Proveedor | Proveedor del   pedido | importe pedido +   IVA |   | De la conf.   Forma de pago efecto | Fecha de pedido | Banco | De la conf.   Banco puente anticipo


Fecha registro | Nº documento | Tipo movimiento | Nº efecto | Tipo | Nº | Importe debe | Importe haber | Cód. forma de pago | Fecha vencimiento | Tipo contrapartida | Cuenta contrpartida
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Fecha pedido | Nº pedido | Efecto | 1 | Proveedor | Proveedor del pedido | (importe pedido + IVA) *   porcentaje de la conf. |   | De la conf. Forma de pago efecto | Fecha de pedido | Banco | De la conf. Banco puente   anticipo
Fecha pedido | Nº pedido | Efecto | 2 | Proveedor | Proveedor del pedido | (importe pedido + IVA) *   (1-porcentaje de la conf.) |   | De la conf. Forma de pago efecto | de la conf. Fecha vencimiento   fin obra | Banco | De la conf. Banco puente   anticipo

El diario se deberá registrar de forma automática. 

Ya de forma manual:

Se creará la OP en la que se incluirán los efectos 1, y seguirá el funcionamiento estándar de pago.

Cuando se reciba la factura, se le deberá indicar en la forma de pago, una forma de pago que esté configurada de tal forma que la cuenta que se le asigne sea el banco puente que hemos empleado para registrar los efectos, dando por liquidada la factura, y compensando la cuenta del banco puente. 
En el caso de que la factura sea de mano de obra, se deberá además, acudir al efecto número 2 y ponerle la fecha de vencimiento que le corresponda.

**Comment by jorgereal** [comment]
Se ha modificado el proceso para crear y registrar el diario tras importar los pedidos.
En caso de que el registro del diario fallase se realiza un rollback, por lo que los pedidos seguirían sin estar importados y no se marcarían con el Nº pedido de NAV en la BBDD de ACSM.

Subido a PRE.

Es necesario rellenar todos los campos indicados en la tarea antes de realizar las pruebas.

**Comment by bpesquero** [comment]
No he podido probar esto, pero me he dado cuenta de que hay un problema. El pedido que se exporta de la BBDD de autoconsumo no siempre es el que finalmente se hace, así que realmente los efectos no deberían crearse hasta que no registre el pedido. Creo que esto fue lo que hablé con Belén. Si entiendo bien lo que me decís aquí es que el efecto se genera cuando se genera el pedido.¿es así?

**Comment by jorgereal** [comment]
Hemos modificado el proceso para que el efecto se genere y registre en el momento del registro del pedido en lugar de en la importación de este.

Para probarlo no es necesario importar los pedidos de ACSM, basta con marcar en la cabecera de un pedido de compra el check 'Generate ACSM Bills'. No está sacado en el formulario pero se puede marcar desde la tabla.

También es necesario rellenar los nuevos campos de la configuración de compras.

Subido a PRE.

**Comment by bpesquero** [comment]
Hemos probado y no genera bien el efecto. 
Lo tenéis en PRE. Ha generado un único efecto y además en negativo.
ES el pedido de compra PC/202000008

**Comment by jorgereal** [comment]
Se ha cambiado el signo del importe y se ha modificado la lógica para detectar si se trata de un pedido de mano de obra, los asientos estaban cruzados.

Subido a PRE.
