### ISSUE TITLE
NAV-GEO-HECEN -Cambio de tarida, no se borran las potencias

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#784]
Cuando se hace un cambio de tarifa, y el nº de periodos de la nueva tarifa es menor que el nº de periodos de la anterior tarifa, no se borran las potencias anteriores, sólo se hacen no editables desde NAV. ESto provoca que el contrato no salga correcto y previsiblemente tampoco saldrá bien el xml de switching.

![image](https://user-images.githubusercontent.com/20299071/75030256-04325a80-54a4-11ea-88d7-49bdc0c7ba1f.png)

**Comment by jorgereal** [comment]
Hemos añadido la limpieza de las potencias de periodos que no aplican cuando se realiza un cambio de tarifa de forma manual.

Los M si se estaban generando correctamente puesto que guardamos las nuevas potencias en otros campos y en el momento de procesar el M1_05 cambiamos la tarifa y sustituimos las antiguas potencias por las 6 nuevas.

Subido a PROD.
