### ISSUE TITLE
Incidencia Registro Fra Autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#786]
Al registrar una factura de autoconsumo de la planta de las que se hacen desde la ficha de autoconsumo.

![image](https://user-images.githubusercontent.com/20299071/75876693-7563fd00-5e16-11ea-98a9-15a39493d83f.png)

**Comment by JMunoz17** [comment]
El problema es que en la cabecera tiene el check "Bloqueada" marcado y por eso no deja registrarla. 

En el proceso de generación de este tipo de facturas no se marca este check, hemos generado de nuevo la factura para comprobarlo (Nº FV/2020003317). 

Puede ser que se haya marcado el check a mano sin querer?

Tenéis dos facturas generadas, registrad la que queráis que tienen fechas de registro diferente y la otra la elimináis.

FV/2020002946 (Si usáis esta desmarcad el check de "Bloqueada" que esta en la ficha y asignad el numerito en la ficha de autoconsumo que ahora mismo tiene el FV/2020003317)
FV/2020003317

**Comment by bpesquero** [comment]
Hemos quitado el check para registrar pero da este error al intentar registrar
![image](https://user-images.githubusercontent.com/20299071/75885010-0d1d1780-5e26-11ea-9981-1d779fe7c383.png)

**Comment by dgarciageo** [comment]
Probado y ok
