### ISSUE TITLE
Alta y eliminación de financiación de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#787]
Quiero añadir un par de funcionalidades:

-alta de financiación--> actualmente ya existe el proceso, sin embargo el alta de la financiación la hace siempre desde la fecha de puesta en marcha, lo ideal sería que al lanzar el proceso nos permitiera elegir la fecha desde la que comenzar la financiación

-borrar financiación--> la idea es insertar un proceso que permita borrar una financiación siempre y cuando no tenga ninguna factura de venta asociada, o todas las facturas de venta estén también abonadas.

**Comment by JMunoz17** [comment]
Subido a PRE.

**Comment by dgarciageo** [comment]
Test ok
