### ISSUE TITLE
NAV - Proceso de importación facturas PRE y sincronización proveedores

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#788]
Hemos añadido un campo al final en el fichero de cabeceras de facturas que se importa desde NAV y que rellena la tabla de Aux facturas Web. Este campo indica el id banco del proveedor que debe ser considerado en la factura. Por tanto, hay que cargarlo en la tabla aux y luego arrastrarlo a la cabecera de factura de compra correspondiente.

Por otra parte, en la importación de tiulares hay que ignorar el campo Cuenta Corriente, ya que a partir de ahora las cuentas corrientes de los proveedores de representación se van a gestionar desde NAV.

Por tanto, se hace necesario:

-cambiar el proceso de importación de cabeceras de facturas, para traer el campo id banco
- añadir un campo a la tabla de Aux facturas Web
- cambiar la generación de facturas desde Aux facturas web para incluir en la cabecera el id banco
- cambiar el proceso de importanción de titulares para no actualizar el campo banco con el que venga desde la web.

**Comment by PKFEric** [comment]
Se ha añadido el campo a la tabla de Aux facturas web y se ha sacado en el Formulario
En el proceso de facturacion se incluye el codigo de banco de ese proveedor
En el proceso de importacion de cabeceras se verifica que efectivamente ese codigo de banco pertenece a ese proveedor
Se quita del proceso de importacion de proveedores todo lo relacionado con el banco, la creacion y la modificacion (se ha comentado el codigo)
