### ISSUE TITLE
WEB - Tiempo excesivo login de usuarios

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#789]
Para algunos usuarios el proceso de login tarda bastante en comparación al resto, haciendo entender al usuario que algo no ha funcionado y a refrescar la página. Os mando los credenciales de acceso por correo de uno de estos usuarios para que hagáis las pruebas. Entiendo que es porque tiene varios contratos.

**Comment by PKFEric** [comment]
El problema de este usuario esta en que tiene un montón de contratos por lo tanto muchas facturas. 

El código esta montado de tal manera que cuando te logeas recupera contratos y facturas por eso tarda tanto. 

Lo podemos cambiar para que loguee rápido y luego al pulsar en contratos o en facturas haga la carga. 

El usuario tardara poco en loguear, y un poco mas en recuperar los contratos y las facturas. Que opinas.

**Comment by dgarciageo** [comment]
No es una solución escalable. Se pospone la resolución de la incidencia por el momento
