### ISSUE TITLE
NAV - proceso cálculo tipo punto de medida

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#79]
Poner un botón desde donde lanzar el proceso, ahora mismo se calcula con el informe

**Comment by PKFEric** [comment]
Ya he añadido el proceso esta en Energy-> DATOS -> Calculo punto medida, he metido para poder Filtrar por contrato. No obstante lo que he visto es que los unicos contratos que no tienen aun relleno el tipo de punto de medida son aquellos que aun no han recibido el C1 05 y por lo tanto no tienen aun precios. 

Esto tanto para GEO como para HECEN.

**Comment by bpesquero** [comment]
Probado y ok. Problema al rellenarlo desde la generación de informes de medidas, esto ocurre porque el informe no selecciona bien los contratos a tener en cuenta, cuando se solucione se solucionará esto.
