### ISSUE TITLE
NAV -WEB - IRPF en instalaciones NC

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#791]
Queremos introducir algunas modificaciones en relación a la retención de IRPF que se realiza en las instalaciones NC

1.- Hay que incluir un campo nuevo en la ficha de autoconsumo con el indicativo aplica retención IRPF (S/N). Este campo sólo será editable cuando el algoritmo de autoconsumo sea NC.
2.- Factura de compra (no de peaje sino de energía excedentaria) asociada a NC. Tendrá la línea de retención y el correspondiente movimiento sólo en el caso en que el check anterior esté a true
3.- En el caso de tener el check de retención a false, y sólo en ese caso, hay que llevar un control del importe facturado en concepto de venta de excedentes (facturas de compra). Las facturas con fecha de emisión dentro de un mismo año natural no pueden superar los 900 euros. Por tanto a la hora de la realizar la factura habrá que buscar el resto de facturas con fecha de emisión de ese mismo año y sumar las bases imponibles para establecer el límite superior de los 900 euros.
Lo ideal es que este límite sea configurable, por si cambia la normativa al respecto.
4.- Los informes de IRPF de la web sólo serán accesibles cuando el cliente tenga el check de retención a true

**Comment by PKFEric** [comment]
1.- Hay que incluir un campo nuevo en la ficha de autoconsumo con el indicativo aplica retención IRPF (S/N). Este campo sólo será editable cuando el algoritmo de autoconsumo sea NC.

_Se ha creado el campo y configurado._

2.- Factura de compra (no de peaje sino de energía excedentaria) asociada a NC. Tendrá la línea de retención y el correspondiente movimiento sólo en el caso en que el check anterior esté a true

_Solo se crea el moviento de retencion si el check esta a true,_


3.- En el caso de tener el check de retención a false, y sólo en ese caso, hay que llevar un control del importe facturado en concepto de venta de excedentes (facturas de compra). Las facturas con fecha de emisión dentro de un mismo año natural no pueden superar los 900 euros. Por tanto a la hora de la realizar la factura habrá que buscar el resto de facturas con fecha de emisión de ese mismo año y sumar las bases imponibles para establecer el límite superior de los 900 euros.
Lo ideal es que este límite sea configurable, por si cambia la normativa al respecto.

_Se suma el campo amount de la linea marcada como ""Excedentes Compra"" de todas las facturas registradas que tengan asociada una factura de venta y NO un abono de venta entre el dia 1 de enero del Año de la factura que se esta emitiendo y el dia 31 de diciembre del mismo año y para el contrato para el que se esta haciendo la factura._

_Ademas se suma la actual linea de "Excedentes Compra" resultando en la base total de todas las facturas del año natural para el contrato._

_Se compara el resultado con el limite configurado en la tabla de "Configuracion de Compras" a través del campo "Limite Facturas IRPF". Este campo se ha sacado en la sección Autoconsumo de la configuración y en el proceso de calculo se valida que sea mayor que 0_

_En caso de que el importe calculado supere el importe limite establecido mostrara el error:
"Error Autoconsumo, el concepto de venta de excedentes %1 supera el limite %2 establecido_



4.- Los informes de IRPF de la web sólo serán accesibles cuando el cliente tenga el check de retención a true

_Modificado._

**Comment by bpesquero** [comment]
Perfecto. Voy a intentar probarlo.
En relación al punto 3.
_**__Se suma el campo amount de la linea marcada como ""Excedentes Compra"" de todas las facturas registradas que tengan asociada una factura de venta y NO un abono de venta entre el dia 1 de enero del Año de la factura que se esta emitiendo y el dia 31 de diciembre del mismo año y para el contrato para el que se esta haciendo la factura._**__
En realidad no es para ese contrato sino para todos los contratos de un mismo titular. Culpa mía, que no lo sabía y me he enterado hoy haciendo la consulta.

_En caso de que el importe calculado supere el importe limite establecido mostrara el error:
"Error Autoconsumo, el concepto de venta de excedentes %1 supera el limite %2 establecido_

En ese caso realmente hay que facturar en concepto de excedente:

max (importe excedentes factura actual - (importe calculado todal - límite);0)

si el max es cero entonces sale el error que comentabas. SI no, hay que facturar hasta llegar a los 900 euros, No sé si me he explicado bien

**Comment by bpesquero** [comment]
¿Vistéis mi último comentario?

Adicionalmente, de la web, del área privada, vamos a quitar el informe de IRPF para todos los casos, y vamos a mantener el informe de IVA, pero llamándolo informe fiscal.

**Comment by PKFEric** [comment]
Yo creo que esta tarde tienes todo subido y modificado

**Comment by bpesquero** [comment]
¿En qué situación está esta incidencia?

**Comment by PKFEric** [comment]
La parte web ya esta hecha y subida a PRO

**Comment by PKFEric** [comment]
La parte de NAV tambien

**Comment by bpesquero** [comment]
Vamos a poner un log como indicabas en todas las facturas de tipo NC para poder ir comprobándolas. Pasado un tiempo lo ideal sería quitar el log

gracias

**Comment by PKFEric** [comment]
He puesto este log.

Aviso, esta factura %1 es de un contrato NC hay que revisar tanto la compra como la venta.
