### ISSUE TITLE
Cambio de titular de persona física a jurídica

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#793]
Cuando se hace un M de cambio de titularidad de empresa a persona física el campo de tipo de persona aparece mal, aparece J y debería ser F.

**Comment by JMunoz17** [comment]
Te refieres al campo "Tipo Persona" de la ficha del contrato verdad?

Cuando viene un M1_02 y se crea un nuevo contrato, se valida en este el cód. cliente titular de tal forma que en el contrato se actualiza el campo "Tipo Persona" en función del valor del campo "Tipo Personalidad" de la ficha del cliente.

Siempre y cuando en la ficha del cliente este OK el valor, esto debería funcionar correctamente.

Tienes algún ejemplo o algo para poder revisarlo?

**Comment by bpesquero** [comment]
PErdona Jaime, aparece mal en el fichero XML el indicativo, por lo que se ve está cogiendo el del anterior, no el del nuevo.
Si necesitas algo más me dices

**Comment by JMunoz17** [comment]
Modificado y subido a PRE y PROD.
