### ISSUE TITLE
NAV- C2 en ficha OCSUM

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#794]
Cuando hay que hacer un C2 que viene desde la web en histórico de acciones se guarda bien el tipo de C2, sin embargo, sin por cualquier motivo hay que relanzarlo hay que cambiar la ficha OCSUM del cliente ya que ahí no se ha guardado el tipo de cambio.
Es decir, parece que el tipo de cambio se lleva bien a histórico de acciones pero no a la pestaña OCSUM del contrato.

**Comment by JMunoz17** [comment]
Cuando viene desde la web lo único que hacemos es marcar en el contrato un check "Generar C2", para que este contrato se tenga en cuenta en el proceso "Envio Masivo C2 a acciones".

Este proceso lo único que hace es, para cada contrato que tenga el check marcado, simular que el usuario entra en la ficha del contrato y le da a "Enviar C2 a acciones".

Los datos con los que se genera el registro del histórico de acciones tienen como origen el contrato en ambos casos, por lo que mientras el usuario no cambie ningún dato en el contrato, estos registros deben ser exactamente iguales.

Si tenéis algún caso concreto donde te haya pasado dímelo y lo reviso.

**Comment by JMunoz17** [comment]
Modificado en función de lo visto con Ainhoa.
Subido a PRE y PROD.
