### ISSUE TITLE
NAV- error procesar ficheros contrato ya existente

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#795]
Cuando se procesan fichero de switching a veces salta es error
 "contrato previo para el mismo CUPS sin fecha final de baja". 
No indica el CUPS ni el contrato y no se sabe que solicitud es.
No carga ninguno y hay que ir por tramos para localizar el que tiene el problema. 
1.- Habría que indicar el nombre del fichero, CUPS o algún dato para localizarlo
2.- En algunos casos el error salta porque había un contrato previo para ese CUPS rechazado, nunca tuvo fecha de activación, con lo cual no debería haber dado error.

**Comment by JMunoz17** [comment]
Modificado el control para que informe en el error el CUPS.
Modificado el control para que no tenga en cuenta los contratos con estado "Rechazado ATR", entiendo que de esta forma controlamos lo que indicas en el punto 2.

Subido a PRE y PROD.
