### ISSUE TITLE
NAV - carga fichero D de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#796]
AL importar el D de autoconsumo dice que no hay contrato en vigor (las fichas de autoconsumo se cargan con fecha 01/01/3000) hay que ir a la ficha de autoconsumo y cambiarlo a mano metiendo la fecha de activación. y tener el check de autoconsumo y el tipo de autoconsumo en la pestaña OCSUM.

Creo que quizá podríamos dejar el control del check de autoconsumo y el tipo de autoconsumo en la pestaña OCSUM pero el tema de tener la ficha autoconsumo vigente es una lata, porque realmente no sabemos cual va a ser la fecha de activación del autoconsumo, así que lo que hacemos es poner una fecha, importar el D, generar la respuesta al D y volver a cambiar la fecha,

**Comment by JMunoz17** [comment]
Suprimido el control y subido a PRE y PROD.

**Comment by bpesquero** [comment]
Jaime, qué es lo que habéis hecho para solucionarlo?

**Comment by JMunoz17** [comment]
Modificar el control existente en el D1 a la hora de buscar el contrato de autoconsumo asociado.
Ya no tenemos en cuenta las fechas de vigencia.

**Comment by bpesquero** [comment]
Probado y ok
