### ISSUE TITLE
Problema código gestor

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#798]
algunos gestores están teniendo problema al tratar de dar de alta contratos con su código de agente,
desde el área de clientes.
El mensaje de error que entra en el correo de clientes@Próxima  es por un lado (no crea el contrato usuario NIF), y por otro , error de <Sales Person :purchaser code does not exist >pero sólo indica “VIVA6” , como si no cogiera el valor completo del código gestor que lleva 4 letras y cinco números: VIVA61837).
![image](https://user-images.githubusercontent.com/20299071/76994726-1f7f7100-694f-11ea-9fe9-f049066a2a21.png)
![image](https://user-images.githubusercontent.com/20299071/76994756-25755200-694f-11ea-8a45-af0b2aa22ba2.png)
![image](https://user-images.githubusercontent.com/20299071/76994769-2b6b3300-694f-11ea-9483-2bbab17ef4ed.png)

**Comment by jorgereal** [comment]
Existía un error en el alta de contratos desde la parte privada con código promocional de un gestor.
Se ha corregido y se ha subido a PRO.

**Comment by bpesquero** [comment]
Probado y ok
