### ISSUE TITLE
Error cambio de potencia HECEN/09433

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#799]
Cuando el cliente intenta cambiar la potencia desde el área privada da el siguiente error

![image](https://user-images.githubusercontent.com/20299071/77148723-65901e00-6a90-11ea-9a86-c0ddd217a482.png)

No llega ni a indicar la potencia. Simplemente con elegir el contrato le sale el mensaje de error.

**Comment by jorgereal** [comment]
Existían errores en el parseo de las tarifas 3.0A en la web de HECEN.
Se han corregido y se han subido a PRO.

![correct](https://user-images.githubusercontent.com/22742905/77414948-0b5dc880-6dc2-11ea-9640-206c5e9960db.png)

Adjunto captura con el cuadro de potencias corregido para el ejemplo indicado.
Ahora mismo ese ejemplo no lo podréis usar porque el contrato está con estado pendiente ATR desde ayer, por lo que no aparece como seleccionable en el listado.

**Comment by bpesquero** [comment]
Probado y ok con otro contrato
