### ISSUE TITLE
NAV - Mail nueva factura

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#80]
En el mail de nueva factura pone, hola Belén Pesquero Fernández, debería poner sólo hola Belén, yo juraría que esto ya estaba cambiado...

**Comment by PKFEric** [comment]
Belen por favor prueba a enviarte,la nueva factura y dime si ahora solo sale tu nombre. Sin apellidos.

**Comment by bpesquero** [comment]
Hay una errata que ya se comunicó en la incidencia 55, y es que pone "en la cuenta bancaria de que nos comunicaste" cuando debe poner "en la cuenta bancaria que nos comunicaste".
