### ISSUE TITLE
NAV - Error XML - M1 tipo S con dirección fiscal distinta  a la de suministro

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#800]
Yo creo que esto ya lo habíamos probado (al menos para A3, c1, etc..)y estaba ok, pero  me parece que faltaba probar los M. Me acaba de pasar Antonio un M que no se ha generado bien, una modificación administrativa S **con subrogación (S)** que ha indicado d**irección fiscal del nuevo titular distinta a la del suministro**, en Indicador tipo dirección de la ficha Nav : tipo F, y no genera la dirección que debe incluir en los nodos del xml. \\192.168.100.105\Esios\GoogleDrive\EnergyCloud\HECEN\OCSUM\Exportados\ES0306000000000250BL_M1_01_20032020.xml
 
Habría que probar también los M tipo A (ambos técnico y administrativo) , con **subrogación S  y contemplar también los de sin subrogación tipo T**, **con dirección fiscal distinta**  a la de suministro que es Indicador tipo dirección de la ficha Nav : tipo F.

**Comment by JMunoz17** [comment]
Modificado y subido a PRE y PROD.

**Comment by dgarciageo** [comment]
Ahora sí se informa el nodo de dirección fiscal pero se están cogiendo los datos de la dirección del anterior titular, en este caso los del CL04417, tendría que leer la dirección fiscal del nuevo titular CL04812

\\192.168.100.105\Esios\GoogleDrive\EnergyCloud\HECEN\OCSUM\Exportados\ES0306000000000250BL_M1__01.xml

**Comment by JMunoz17** [comment]
Prueba de nuevo Dani por favor.
He cambiado también los nodos de correo electrónico y número de teléfono que están justo encima de la dirección y no sacaban el dato correcto en este caso, revisa que este ok.

**Comment by dgarciageo** [comment]
Probado y ok
