### ISSUE TITLE
Pregunta - URGENTE Campo Data de tabla [Comment Line]

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#801]
Hemos metido para el contrato HECEN/07832 unos comentarios con fecha 2020-03-18
Al generar una factura con fecha desde 2020-03-19 entendemos que deberían salir pero no salen. Sólo salen si ponemos fecha de 2020-01-01
¿Que implica exactamente el campo Date de esta tabla? fecha factura desde? fecha energía? Entendemos que es fecha factura pero no entendemos por qué no funciona

**Comment by JMunoz17** [comment]
Hemos modificado los formatos para que aplique el filtro de fecha correctamente.

Para el contrato HECEN/07832 tenemos la factura H/20200014983 con periodo de facturación del 07/02/20  al 05/03/20.

El formato mostrará todos los comentarios anteriores al 05/03/20 (incluido este día).
Os he puesto a los comentarios fecha 04/03/20 y aparecen correctamente.

Revisadlo y configuradlo como consideréis.

**Comment by bpesquero** [comment]
Buenos días, no me ha quedado claro si la fecha se refiere a fecha de energía o fecha de emisión. DEbería ser fecha de emisión.

Nos puedes confirmar Jaime?

Gracias

**Comment by JMunoz17** [comment]
Se utiliza la fecha hasta del periodo de facturación, siempre ha estado así.
Queréis que lo cambiemos y usemos la fecha de emisión para todos los formatos?

**Comment by bpesquero** [comment]
Ahora mismo tiene más sentido..


*Belén Pesquero Fernándezbpesquero@geoatlanter.com
<bpesquero@geoatlanter.com>*
Av. de Europa, 34B Esc. Dcha. 3º 28023, Madrid
 *917 378 443*
 *647 533 013*
<http://www.geoatlanter.com/>


*Síguenos en:*[image: Facebook pequeño]
<https://www.facebook.com/proximaenergia/>[image: Twitter pequeño]
<https://twitter.com/proximaenergia?lang=es>[image: Google+pequeñito]
<https://plus.google.com/114547235710296874519>

*AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener información
*confidencial *sometida a secreto profesional. No está permitida su
reproducción o distribución sin la autorización expresa de *GEOATLANTER SL.*

Si usted no es el destinatario final por favor elimínelo e infórmenos por
esta vía.



De acuerdo con lo establecido por el Reglamento General de Protección de
Datos (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de
2016, le informamos que sus datos serán tratados con la finalidad de
realizar la gestión administrativa, contable y fiscal, así como el envío de
comunicaciones comerciales  sobre nuestros servicios y/o productos.


Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, oposición, supresión, limitación y portabilidad de
sus datos en el domicilio de *GEOATLANTER SL *sito en: Avda de Europa 34B
<https://maps.google.com/?q=Avda+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha 3º,  28023 Madrid o enviando un correo electrónico a la siguiente
dirección : *contacto@geoatlanter.com <contacto@geoatlanter.com>*

Si usted no desea recibir nuestra información, póngase en contacto con
nosotros enviando un correo electrónico a la dirección:
*contacto@geoatlanter.com <contacto@geoatlanter.com>*

**Comment by JMunoz17** [comment]
Modificado, subido a PRE y PROD.

Por favor probad que funciona correctamente que no hay licencias libres y no puedo probarlo en PROD.
