### ISSUE TITLE
NAV - Pregunta API descarga precios ESIOS

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#802]
Tenemos un Bot para descargar ficheros y quiero descargarme manera automática los precios de ESIOS con el bot por las noches
Pero necesitamos que nos paseis el token y la llamada al API de https://www.esios.ree.es/es/pagina/api que hacéis para descargos el liquicomun del periodo del fechas

**Comment by JMunoz17** [comment]
Respuesta via mail.
