### ISSUE TITLE
WEB / Signaturit - Reenvio signaturit desde parte admin web

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#803]
Cuando Ainhoa fuerza el reenvio del contrato signaturit desde la parte de administración web porque el email del usuario ha cambiado (el usuario lo introduce mal en el formulario de alta y Ainhoa tiene que volver a crear todas las entidades de datos en NAV a mano y reenviar signaturit) no se sincroniza el estado del contrato a firmado en NAV una vez que el cliente forma el contrato. Posiblemente porque el usuario se dio de alta con un email y en NAV está con otro.

**Comment by jorgereal** [comment]
En principio el email no influye en este proceso, tan solo se tiene en cuenta el código de contrato.
El programa que cambia el estado de los contratos a firmados solo tiene en cuenta aquellos contratos que tengan como estado 'Creado Web'.
Quizás cuando se dió de alta a mano el contrato en NAV no se fijó ese estado y se dejó el de por defecto 'Pendiente Firma'.
Cambiando este estado entraría en la comprobación del proceso y lo actualizaría a firmado.

**Comment by dgarciageo** [comment]
Buenas jorge

Creo que ese no es el caso. Mira por ejemplo el siguiente contrato:

COM/02205

Esta en creado web en Nav y el cliente ya lo tiene firmado en Signaturit

**Comment by jorgereal** [comment]
El problema estaba en que cuando se consultaba el estado del documento en signaturit se buscaba por el primer id almacenado en MySQL (estos ids son aleatorios, los genera signaturit) de los registros de envíos a signaturit para el contrato.
En este caso había dos registros y solo se consultaba por el más antiguo.

Se ha modificado la API para que realice una consulta por cada registro.
Ya se ha actualizado el contrato citado automáticamente.

Subido a PRO.

**Comment by dgarciageo** [comment]
Probado y ok
