### ISSUE TITLE
Problema Tarifas y Contratos con margen 0

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#804]
Eric, te acuerdas el cambio que hicimos de que los contratos con menos de 10 kW de potencia llevaban comisión fija de 2 euros independientemente de que se tratase de persona física o jurídica?

Pues bien, aunque en su momento lo probamos, vemos que ahora no se está haciendo bien. En estos casos se está poniendo a cero tanto la comisión fija como la variable. Que Ainhoa me corrija pero creo que el contrato lo están firmando a precio 0.
 Por lo que veo tenemos 107 contratos en esta situación. Salvo error por mi parte. 
Me he limitado a filtrar los contratos que tienen a cero ambas comisiones. De estos, creo que sólo 7 están activados.

1.- Habría que corregir la incidencia para nuevos contratos
2.- Pasar un proceso para corregir las comisiones erroneas
3.- Si el contrato lo han firmado a cero habría que volver a firmarlos, tendríamos que enviar de nuevo los contratos por signaurit.  Habría que hacer una comunicación previa
4.- Tenemos que ver si se ha facturado algo a precio cero. Si es así, habría que abonar la factura para volver a emitirla con la correspondiente comisión.

Eric, por favor, echadle un ojo y nos decís,

**Comment by jorgereal** [comment]
Contestado por mail.
