### ISSUE TITLE
Campo nuevo para importacion de medidas desde Oracle

### ISSUE THREAD

**Issue by PKFEric** [PKFEric/webProxima#805]
Crear un nuevo campo para  poder distinguir que contratos requieren de la importacion de medidas de oracle. Se creara un campo en Tipo de COntrato que bajara a contratos.

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

**Comment by JMunoz17** [comment]
Respuesta via mail a Mónica y Fernando.
