### ISSUE TITLE
WEB/NAV - Nuevas comisiones factura en papel

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#806]
Necesitamos actualizar las comisiones de la fcatura en papel

Las nuevas comisiones son:
- 2,5€/mes para comisión fija mensual --> PRECIO FINAL: 4,5 €/mes
- 0,00625 €/kWh para comisión variable --> PRECIO FINAL 0,01125€/kWh

Hemos probado a actualizar en la tabla de Configuración de Energía los campos de plus factura electrónica en NAV

![image](https://user-images.githubusercontent.com/47117960/77686429-3e0fe880-6f9d-11ea-923d-dbb215bd7b49.png)

Pero sigue saliendo mal en la web y signaturit

Web
![image](https://user-images.githubusercontent.com/47117960/77685491-cf7e5b00-6f9b-11ea-8042-df3561250965.png)

Signaturit
![image](https://user-images.githubusercontent.com/47117960/77685546-e1f89480-6f9b-11ea-87f6-c442274c088b.png)

**Comment by jorgereal** [comment]
Hemos modificado la web para mostrar las nuevas comisiones y que se vean reflejadas en el contrato de signaturit.

En NAV hemos actualizado los plus de la factura electrónica a los valores solicitados.

Seguramente sea necesario limpiar la caché del navegador para que se actualice el javascript.

Subido a PROD.

**Comment by dgarciageo** [comment]
web 1: ok
![image](https://user-images.githubusercontent.com/47117960/78129126-5fe2f280-7417-11ea-944d-bf6e7cf50711.png)

web 2: ok para ambos casos  <10kW y > 10kW

![image](https://user-images.githubusercontent.com/47117960/78129322-b3554080-7417-11ea-9d50-d45cc1b2e3a8.png)

Signaturit: ok
![image](https://user-images.githubusercontent.com/47117960/78129560-16df6e00-7418-11ea-8f65-5ce693849347.png)
