### ISSUE TITLE
NAV - Comentarios facturas

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#808]
Me comenta Belén que los comentarios que se incluyen en la tabla Comment Line de NAV, se crean de manera automática cuando se crea un nuevo contrato, y que los comentarios no son con-figurables ya que están hard codeados. ¿Es correcto? Si es así habría que modificarlos.

Cambiando estos
![image](https://user-images.githubusercontent.com/47117960/78116387-7f245480-7404-11ea-98ab-0acbfa57b283.png)

Por estos otros:

Line No_ | Comment

1000 | 'Somos muy conscientes de las dificultades que la pandemia del COVID-19'
2000 | '_está ocasionando a muchas familias   y empresas.'
3000 | '_Queremos recordarte que desde   Próxima Energía estamos, como siempre,'
4000 | '_a tu disposición para ayudarte en caso de que lo necesites.'
5000 | '_Si se te presenta cualquier   problema con el suministro de energía, te rogamos'
6000 | '_nos lo comuniques al correo   electrónico coronavirus@proximaenergia.com.'
7000 | '_No dudes que, si está en nuestra   mano, haremos todo lo posible para ayudarte.'

El _ es espacio

**Comment by JMunoz17** [comment]
Correcto.

Los comentarios a los que haces referencia se asocian al contrato en el momento en el que este se crea. 

Entiendo que necesitáis que a partir de ahora se asocien los comentarios nuevos al crear el contrato y que pasemos un proceso para rellenar esos comentarios en todos los contratos no?

**Comment by dgarciageo** [comment]
Buenas Jaime,

Sólo en los nuevos. El proceso lo puedo pasar yo,

Avísame cuando lo tengas

muchas gracias!!

**Comment by JMunoz17** [comment]
Modificado, subido a PRE y PROD.
