### ISSUE TITLE
Medidas COVID0104

### ISSUE THREAD

**Issue by JMunoz17** [PKFEric/webProxima#809]
**Configuración:**
 - Código grupo registro de iva de negocio covid (asignar en conf. contabilidad) -> COVID0104
 - Configuraciones de IVA para el grupo reg. iva negocio COVID0104.
 - Código método de pago covid (asignar en conf. contabilidad) -> COVID0104
 - Nuevos campos en configuración de contabilidad:
![image](https://user-images.githubusercontent.com/26869276/78579525-5f8c9200-7831-11ea-88f6-f5db3ec3d0b9.png)
 - Nuevo check en términos de pago "Financiacion Covid GEO", debe estar marcado para el término de pago APLAZAMIEN.

**Desde la ficha de contrato:**
- Nuevo campo COVID0104.
- Nuevo campo Suspensión Suministro COVID (únicamente informativo).

- Una vez marquéis este campo (COVID0104), y siempre después de aceptar el mensaje de confirmación, se realizarán los siguientes procesos:
    - Cambiar el grupo registro de IVA de negocio al cliente titular asociado al contrato.
    - Cambiar forma de pago al cliente pagador asociado al contrato.
    - Buscar si hay facturas venta generadas sin registrar de ese contrato que tengan una fecha que esté contenida dentro del periodo de alarma (Fecha inicial >= Fecha inicio alarma COVID), si las hay cambiar el grupo registro de IVA de negocio y la forma de pago.
     - Buscar si hay facturas venta registradas pendientes de ese contrato que tengan una fecha de esté contenida dentro del periodo de alarma, si las hay, pintar un diario general en el que se divida la factura en 6 efectos. El diario generado se registrará automáticamente, tendréis que darle a continuar en dos mensajes de confirmación.
     - Buscar si hay facturas de peaje registradas pendientes asociadas al contrato que tengan una fecha que esté contenida dentro del periodo de alarma, si las hay, marcarlas en el campo esperar de movimientos de proveedor, con el código C14. También se hace lo mismo para posibles pre-facturas de peaje ya generadas pero no registradas.

 - Nuevo botón desde la ficha del contrato que:
   - Marque los movimientos de cliente correspondientes a devoluciones que cumplan las condiciones de fechas (se usa fecha registro de la factura para los clientes con término de pago APLAZAMIE y fecha desde y fecha hasta de la factura para los contratos con covid marcado). Necesario antes de ejecutar el proceso: marcar covid en el contrato o poner término de pago APLAZAMIE en el cliente. Botón: Acciones -> Marcar Devoluciones COVID.

 **Devoluciones:** 
  - Al importar la N19 se genera un diario de cartera que posteriormente registráis. En ese momento, si la devolución y el contrato cumplen con las condiciones establecidas el movimiento de cliente se marca como pendiente de aplicar el protocolo Covid0104. 

  - Nuevo proceso que al ejecutarlo liquida ese efecto devuelto y genera 6 efectos nuevos. Tenéis que lanzarlo una vez hayáis importado las devoluciones y registrado el diario de cartera que se genera.
![image](https://user-images.githubusercontent.com/26869276/78574368-31578400-782a-11ea-847a-e17233d2d0c8.png)

  - La devolución importada no se tendrá en cuenta en la función que determina si un cliente pasa a ser moroso y no se producirá envío de email de impago. En cualquier caso, esta parte habrá que estar pendientes por si se nos ha pasado algo.

  - Se ha replicado el mismo funcionamiento para las devoluciones correspondientes a aquellos clientes que tengan como término de pago asociado APLAZAMIEN, con la salvedad de que se generan 9 efectos en lugar de 6 y se indica la fecha de vencimiento para cada uno de estos. La comprobación de fechas se realiza en función de la fecha de registro de la factura en lugar del periodo de facturación.

  - Se han modificado las plantillas de email de impago tanto en HECEN como en GEO (las plantillas originales están guardadas en \\NI\Esios\Plantillas Mail\Originales Covid). También se ha anulado el envío de este email en caso de que el cliente sea moroso recurrente puesto que se enviaba un aviso de baja.

**Importación Facturas de peaje**
  - En la importación de las facturas de peajes, hay que comprobar si corresponden a una fecha contenida en el periodo de alarma (ojo que de momento no hay fecha de fin) y a un contrato marcado con COVID, en tal caso, marcar el movimiento de proveedor con el campo esperar C14. Se realiza automáticamente.

**Datos Originales de los clientes**
  - Antes de comenzar a trabajar con el desarrollo en PROD tenemos que exportar los datos de los clientes (grupo reg. iva negocio y método de pago), para el día de mañana poder importarlos de nuevo. Tengo un proceso para exportar y otro para importar, eso si los tengo que ejecutar yo porque no están en licencia. Dejaré el excel generado en NI. **_Este punto no se va a automatizar inicialmente porque después de finalizar el estado de alarma se pueden seguir emitiendo facturas correspondientes a periodos de energía de la alarma, por lo que, salvo que se incremente mucho el número de clientes acogidos a este decreto, se controlará de forma manual._**

**Procesos una vez finalice el estado de alarma**
  - Cuando se generen las facturas de venta, si éstas tienen fecha posterior a fecha fin estado de alarma, y el contrato está marcado con COVID0104, hay que recorrer los efectos pendientes del cliente generados por el COVID0104 y cambiar la fecha de vencimiento poniendo la misma que la factura que estamos creando, con el siguiente criterio, los efectos 1 se modificaran con la primera factura que se genere después de la fecha de alarma, los efectos 2 con la 2ª factura, los efectos 3 con la 3ª factura, así hasta el 6º. Para ello obtendremos el número de factura por la diferencia de meses de la fecha de factura y la fecha de fin de alarma. (Pensar el algoritmo despacio)
Esto sólo funcionará con las facturaciones mensuales.  **_El control se va a realizar en el registro de la factura, si hay fecha de fin de alarma y ésta es inferior a la fecha de inicio de periodo de energía, se buscará el mínimo nº de efecto pendiente asociado a ese CUPS,  y si el efecto inmediatamente anterior tiene una fecha de vencimiento de más de 30 días de diferencia con la fecha de vencimiento de la factura actual, modificamos la fecha de vencimiento con la de la factura en cuestión._**  

  -  En las remesas se rescataran las facturas del mes, más los efectos correspondientes. La liquidación de la remesa generará el IVA para los efectos que se vayan incluyendo. Ojo que habrá que revisar que el movimiento de IVA del pago se genere al cliente correcto, porque me temo que no estará modificado el código y el pago generará el mov IVA al cliente pagador y no al titular que es el que debería aparecer. **_La liquidación del efecto generará el devengo del IVA, ya que la configuración será proporcional en los efectos y en el devengo del IVA, porque aunque el decreto nos permite retrasar el IVA hasta el cobro del último efecto, hacer esto en NAV no es estándar y el coste de la modificación no justifica el coste financiero del adelanto del IVA._** 

  - A partir del 6º mes desde la fecha de fin de alarma, hay que devengar el IVA de todos los efectos que nos queden pendientes, por lo que habrá que crear un proceso que pinte un diario general liquidando todos los efectos COVID0104 pendientes con tipo pago, y volviendo a generarlos en el propio cliente, para que se puedan seguir incluyendo en las remesas correspondientes. **_Se creará un proceso que se lanzará de forma manual en el que se liquidarán todos los efectos marcados con COVID0104 con tipo de movimiento pago, para que devenguen el IVA pendiente, y se crearan de nuevo como efectos “prima” de tal manera que lo que se comenta en el primer párrafo de quitar el campo esperar del movimiento de proveedor, se haga, no en la liquidación mediante este proceso del efecto 6, si no cuando el efecto 6’ se liquide. Ojo que puede darse el caso de que el efecto 6 original se liquide antes de que lleguen los 6 meses y hay que tenerlo en cuenta también._** 

**### Esta subido a producción todo a excepción de los puntos correspondientes a los procesos que se han de aplicar una vez finalice el estado de alarma. También queda pendiente por nuestra parte establecer un guión de los pasos a seguir por el usuario una vez conozcamos la fecha de fin del estado de alarma.**

**Comment by JMunoz17** [comment]
Una aclaración; las facturas de compra son las facturas de peaje, no nos referimos a las facturas de compra que se generan en los autoconsumos NC ni a las facturas de derechos de enganches (facturación otros)
Por otra parte, el IVA de las facturas de compra lo vamos a declarar en la fecha de emisión con lo cual

1.- No hay que buscar las prefacturas para marcarles el cambiar el grupo registro IVA lo que sí hay que hacer es marcar el código Esperar que creo que no aparecía

2.- Cuando se importan las facturas de peaje hay que marcar el código esperar pero no cambiar el grupo registro de IVA

**Comment by JMunoz17** [comment]
Hemos subido a pre los siguientes puntos para revisarlo mañana:

1- Código grupo registro de iva de negocio covid (asignar en conf. contabilidad) -> COVID0104

2- Código método de pago covid (asignar en conf. contabilidad) -> COVID0104

3- Nuevos campos en configuración de contabilidad (para registrar los diarios generados en los diferentes procesos es necesario configurar libro (nos vale General) y sección (creamos una nueva sin poner números en el código)).
![image](https://user-images.githubusercontent.com/26869276/78579525-5f8c9200-7831-11ea-88f6-f5db3ec3d0b9.png)

4- Nuevo campo COVID0104 creado en contratos (situado en la parte inferior de la pestaña principal de la ficha de contrato):
![image](https://user-images.githubusercontent.com/26869276/78573026-809cb500-7828-11ea-8bbd-b9b914f1b318.png)
También os he sacado el campo en la lista de contratos y he habilitado la edición de esta, cuidado al navegar no modifiquéis ningún otro dato sin querer. Una vez marquéis la primera remesa de contratos (que será la grande imagino), lo mejor será que solo quede editable en la ficha.

Una vez marquéis este campo, y siempre después de aceptar el mensaje de confirmación, se ejecutarán los 5 puntos (a,b,c,d,e). El diario generado en el punto d se registrará automáticamente, tendréis que darle a continuar en dos mensajes de confirmación.

5- Al importar la N19 se genera un diario de cartera que posteriormente registráis. En ese momento, si la devolución y el contrato cumplen con las condiciones establecidas el movimiento de cliente se marca como pendiente de aplicar el protocolo Covid0104. 

Nuevo proceso que al ejecutarlo liquida ese efecto devuelto y genera 6 efectos nuevos. Tenéis que lanzarlo una vez hayáis importado las devoluciones y registrado el diario de cartera que se genera.
![image](https://user-images.githubusercontent.com/26869276/78574368-31578400-782a-11ea-847a-e17233d2d0c8.png)

La devolución importada no se tendrá en cuenta en la función que determina si un cliente pasa a ser moroso y no se producirá envío de email de impago. En cualquier caso, esta parte habrá que estar pendientes por si se nos ha pasado algo.

6- Se realiza automáticamente al importar la factura de peajes.

7- Antes de comenzar a trabajar con el desarrollo en PROD tenemos que exportar los datos de los clientes (grupo reg. iva negocio y método de pago), para el día de mañana poder importarlos de nuevo. Tengo un proceso para exportar y otro para importar, eso si los tengo que ejecutar yo porque no están en licencia. Dejaré el excel generado en NI.

8 y 9 - En desarrollo.

**Comment by JMunoz17** [comment]
Modificaciones a realizar:
- Nuevo botón desde la ficha del contrato que:
  - Marque los movimientos de cliente correspondientes a devoluciones que cumplan las condiciones de fechas (se usa fecha registro de la factura para los clientes con término de pago APLAZAMIE y fecha desde y fecha hasta de la factura para los contratos con covid marcado).
  - Necesario antes de ejecutar el proceso: marcar covid en el contrato o poner término de pago APLAZAMIE en el cliente.

- Proceso de devoluciones: 
  - Incluir comprobación de fechas para el caso de los clientes con término de pago APLAZAMIE (usando la fecha de registro de la factura).

**Comment by bpesquero** [comment]
Ningún cliente se acogió finalmente a esta opción, se acogieron al aplazamiento propuesto por nosotros. Así que entiendo que no hay que hacer nada con esto, verdad?

**Comment by JMunoz17** [comment]
No, no es necesario hacer nada. Si queréis poner la fecha de fin de estado de alarma en la conf. de contabilidad pero da igual porque ni habéis marcado ni vais a marcar ningún contrato como Covid.

**Comment by JMunoz17** [comment]
Lo único Belén, recuerda que en los mails de devoluciones hicimos lo siguiente:
- Que no se enviase si el cliente se había acogido al tema este del COVID o tenia la forma de pago de APLAZAMIEN.
- Cambiamos los formatos de los mails que se seguían enviando.

Esto si que habrá que dejarlo como estaba, al menos el segundo punto porque el primero una vez cambiéis la forma de pago en los clientes ya volverá a funcionar como antes.

**Comment by bpesquero** [comment]
si, efectivamente estos dos puntos habría que cambiarlos el lunes

**Comment by JMunoz17** [comment]
Pero el lunes ya vais a cambiar la forma de pago de todos los clientes a los que le pusisteis APLAZAMIEN?

**Comment by bpesquero** [comment]
No eso no, tenemos que ir viendo que a cada uno se le hayan aplazado tres facturas, lo iremos comprobando y actualizando.

En cuanto al formato del email si me puedes pasar por emial el texto actual y el anterior te lo agradezco.

**Comment by JMunoz17** [comment]
Ok, entonces mi pregunta es:
- Queréis que a partir de lunes cualquier devolución provoque envío de email? O si el cliente tiene el termino de pago APLAZAMIEN no se debe enviar?

Si todas las devoluciones deben llevar asociado el envío de mail si que habría que cambiarlo en el código. En caso contrario no habría que tocar nada.

Te he mandado las plantillas por mail.

**Comment by bpesquero** [comment]
A partir del lunes debería quedar como estaba antes del estado de alarma. Es decir que cualquier devolución lleve un email con el formato antiguo. YA vi las plantillas.

Gracias

**Comment by JMunoz17** [comment]
Ok, me lo apunto para el lunes a primera hora poner las plantillas antiguas y cambiar esto.

**Comment by JMunoz17** [comment]
Ya hemos dejado el tema de los emails en el proceso de devoluciones tal y como estaba antes del estado de alarma.

**Comment by bpesquero** [comment]
Para Geo y para HECEN, verdad?

**Comment by JMunoz17** [comment]
Paso esto a Done!! O la habías dejado aquí por algo Belén?
