### ISSUE TITLE
NAV - Adjuntar imagen en ficha producto

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#811]
Incluir en la ficha producto la posibilidad de adjuntar una imagen descriptiva del producto. El fichero se almacenará en la ruta especificada igual que cuando se adjunta un documento factura o cualquier otro doc en NAV (\\alfa\datos\Autoconsumo\Productos). Se puede subir directamente a PRO.

![image](https://user-images.githubusercontent.com/47117960/78536727-97beb100-77ee-11ea-8ec5-22f6f83693b0.png)

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

La ruta donde se almacenarán las imágenes importadas debe ser configurada en la configuración de compras, pestaña autoconsumo. La ruta debete tener un formato similar a este: \\NI\EsiosPre\Jaime\

El usuario que realice la importación debe de poder acceder a NI (o a alfa o donde sea).

La imagen se importa desde la ficha de producto, pestaña general (nombre del campo, Imagen).

Cualquier cosa me dices.

**Comment by dgarciageo** [comment]
Test ok

![image](https://user-images.githubusercontent.com/47117960/80358016-15209300-887c-11ea-8fee-9d5142c9b220.png)
