### ISSUE TITLE
NAV - Codificar el campo garantía de la ficha producto

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#812]
El campo garantía tendrá que ser un seleccionable con los siguientes códigos.

**5D** - 5 años de garantía frente a defectos
**10P** - 10 años de garantía de producto
**10P20A** - 10 años de garantía de producto ampliable a 20
**10R** - 10 años de garantía de rendimiento
**12P25T**  - 12 años de garantía de producto y 25 años de garantía de potencia

-------------------------------
Se añaden estos 2 valores a la lista
**5P20A** - 5 años de garantía de producto ampliable a 20
**25P25T** - 25 años de garantía de producto y 25 años de garantía de potencia

**Comment by JMunoz17** [comment]
Subido a PRE.

Antes de subirlo a PROD os aviso que tengo que eliminar los datos de este campo para poder cambiar el tipo del mismo. Por lo tanto luego tendréis que volver a informar este dato en cada uno de los productos (os pondré la lista editable para que os sea mas rápido).

A no ser que queráis que haga un proceso para traspasar el dato, para lo que necesitaría que me indicaseis la relación entre los datos actuales y las nuevas opciones del campo.

Me decís y lo subo a PROD.

**Comment by dgarciageo** [comment]
Buenas Jaime,

Se añaden 2 elementos a la lista de posibles valores. 
Con respecto a los nuevos valores a informar lo metemos nosotros a mano más tarde
Lo único que nos saques en una lista los valores actuales del campo por producto en un excel para hacer nosotros la conversión

Muchas gracias

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

Te mando el excel por email.

**Comment by dgarciageo** [comment]
Test ok

![image](https://user-images.githubusercontent.com/47117960/80358103-33868e80-887c-11ea-9517-75e0be85f537.png)
