### ISSUE TITLE
NAV - Cambio de titular de persona física a física

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#814]
Hemos generado un M1 de cambio de titular con subrogación, es decir, M S S de persona física con NI a física con NIE, y el TipoIdentificador sale mal informado en el xml. El TipoIdentificador debe ser NE en lugar de NI ya que el nuevo titular tiene un NIE

Os adjuntamos pantallazo del M1 generado
![image](https://user-images.githubusercontent.com/47117960/78582410-8351d700-7835-11ea-81b7-3ce26214d372.png)

Y os dejamos fichero en la siguiente ruta
\\ni\esios\OCSUM_Old\WAIT JAIMEºES0306000000000733DL_M1__01.xml

Relacionada con la  Cambio de titular de persona física a jurídica #793

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

Tenéis que volver a enviar el M1 a acciones.
