### ISSUE TITLE
NAV - Error Fichas autoconsumo NC|NF

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#815]
El titular y el propietario se están informando de manera incorrecta en la dicha ACSM. Detalles proporcionados por email.

**Comment by dgarciageo** [comment]
Buenas Jaime,

Creo que puede ser que cuando cambias el código de contrato de autoconsumo, si se cambia el algoritmo  (SF, SC, etc) pero el titular y el propietario no se cambian. (Esto es algo que no lo planteamos en su día pero que sería necesario)



![image](https://user-images.githubusercontent.com/47117960/78648864-e6d31780-78bc-11ea-9042-baeab8d09209.png)

**Comment by JMunoz17** [comment]
Cuando metimos el algoritmo de autoconsumo F hicimos diferentes modificaciones en las validaciones y en una de ella excluimos la actualización de estos valores al cambiar de algoritmo de autoconsumo sin darnos cuenta.

Ya esta modificado, subido a PRE y a PROD.

He pasado un proceso en PROD, en GEO, para arreglar estos datos.

**Comment by JMunoz17** [comment]
En referencia a: _"La última ficha que se ha importado sigue incorrecta.id proyecto 136"._

Quedaba un caso por contemplar en el proceso de importación de contratos de autoconsumo desde TAU. Esta solucionado y subido a producción. 

Lo hemos probado en PRE, ya se realiza la importación correctamente.

En PROD hemos pasado un proceso para arreglar los datos que estuviesen mal (únicamente hemos identificado como erróneo el contrato de autoconsumo asociado al id proyecto 136).
