### ISSUE TITLE
WEB - Error dirección fiscal Nuevo contrato área privada

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#816]
Cuando un cliente da de alta un nuevo contrato desde el área privada con una dirección fiscal distinta (por cambio de domicilio). A Signaturit le llega la anterior que había en NAV. Ejemplo:

* Registro 1238 de la tabla de log_contratos de hecen
* Contrato HECEN/11167

Creo que el problema es que no se actualiza la dirección fiscal del cliente existente en NAV

**Comment by PKFEric** [comment]
Ya esta en ATULADO SUBDO EN PRO

**Comment by dgarciageo** [comment]
Probado y ok
