### ISSUE TITLE
NAV - Problema facturación semanal valera

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#818]
Estoy intentando facturar el semanal del COM/00012 de Valera y  me  da el siguiente error que no entiendo:

COM/00012 | ES0022000007158941YV | 06/04/2020 | 12/04/2020 | No puede hacerse un cálculo de   fechas en base a una fecha indefinida.       Fecha: 0D   Fórmula: -PM

No se.. es posible que sea porque lo último que tiene  facturado es una de derechos de enganche?

**Comment by JMunoz17** [comment]
Si, era por la factura de derechos de enganche. 
No estaba contemplada esa casuística.

Facturas generadas: FV/2020006059 y FV/2020006060

Revisad que estén ok.
