### ISSUE TITLE
NAV - control potencia facturada

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#82]
Poner control al generar factura de compra de que la potencia contratada en NAV coincide con la potencia contratada obtenida de la tabla de toll measures del campo potencia contratada

**Comment by PKFEric** [comment]
SUBIDO->PROBAR

**Comment by bpesquero** [comment]
Probado y ok

**Comment by bpesquero** [comment]
Me ha dado error al cargar un fichero de Hidroeléctrica El Carmen, se trata de un contrato que tuvo cambio de potencia y no está cogiendo de histórico de precios el valor de la potencia que corresponde al periodo de tiempo facturado

**Comment by bpesquero** [comment]
Solucionado
