### ISSUE TITLE
WEB Atulado - Meter enlace para descarga de condiciones generales de contratación

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#820]
Necesitamos incluir en la web de atulado un vínculo desde donde se descargue las condiciones generales de contratación de atulado. El pdf es el siguiente:

\\ALFA\Datos\Proyectos\Hidroelectrica El Carmen\Comercializacion\A tu lado\Contratos HECEN\20190501\201905 Condiciones Generales del contrato de suministro de energía eléctrica_v2.pdf

Lo podemos incluir aquí por ejemplo. Son las mismas condiciones para todas las tarifas:
![image](https://user-images.githubusercontent.com/47117960/79466077-615a1080-7ffc-11ea-8de3-58cd40c6254d.png)

**Comment by dgarciageo** [comment]
No sale centrado

![image](https://user-images.githubusercontent.com/47117960/80354597-3cc12c80-8877-11ea-925d-b3aa777ca335.png)

**Comment by PKFEric** [comment]
CTRL + F5 Borra la cache o pruebalo en una ventana de incognito

![image](https://user-images.githubusercontent.com/20229934/80355030-d4bf1600-8877-11ea-810e-e5b8fb5b225f.png)

**Comment by dgarciageo** [comment]
Perfecto
