### ISSUE TITLE
WEB - Error al forzar re-envío signaturit para COM/02717

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#822]
Al forzar el reenvío signaturit para el COM/02717 se queda la página en blanco y no se realiza el envío.

**Comment by dgarciageo** [comment]
Se cancela el renvio de signturit pero es posible que haya una incidencia

**Comment by PKFEric** [comment]
Se volvia loca la pagina al mostrar los GRIDS de logs, los estamos sacando a otra pagina No obstante esto ya esta solucionado y probado con Ainhoa.
