### ISSUE TITLE
WEB - Error web al bajar potencia 3.1

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#823]
Nos avisa un cliente que les está dando un error al solicitar bajada de potencia de la 3.1 A tal y como puedes ver en el pantallazo que indican. (más info en correo adjunto)

![image](https://user-images.githubusercontent.com/47117960/79841794-3a169100-83b8-11ea-9c7d-832e5ff5c344.png)

**Comment by PKFEric** [comment]
En HECEN no pasa.

**Comment by PKFEric** [comment]
En HECEN se envia el mail
Cambio de potencia del contrato HECEN/08513 
Datos de cliente que solicita el cambio de potencia: 
Nombre: MOHAMMED 
Apellido 1: I.S. 
Apellido 2: HAMDAN 
E-Mail: 
NIF/CIF: Y3919928Y 
Telefono: 607700700 
Potencia Actual periodo 1: 5,75 kW y se desa cambiar por 125 kW. 
Potencia Actual periodo 2: 5,75 kW y se desa cambiar por 175 kW. 
Potencia Actual periodo 3: 5,75 kW y se desa cambiar por 175 kW.

**Comment by PKFEric** [comment]
Pasaba en próxima por que el tipo de contrato del contrato COM/00881 que es el 015 no es un tipo de contrato web. Entonces no encontraba el peaje, ya esta solucionado.
 Ahora lo subo con las demas tareas

**Comment by bpesquero** [comment]
EL cliente se bajó la potencia ok, pero el contrato salía sin peaje
