### ISSUE TITLE
NAV- COM/00012- FActura rectificativa

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#824]
Tenemos el cotnrato COM/00012 que es de los de facturación semanal. 
Se facturó con normalidad el mes de enero, cuando llegó el peaje se abonó con normalidad la factura que contenía el último día del mes y se refacturó con los datos del peaje.

Después llegó una factura de peaje rectificativa y en vez de abonar la factura que contenía le último día del mes, abono la primera factura de mes.
Entiendo que no teníamos previsto la refacturación para las semanales.

Le podéis echar un vistazo?

 
COM/00012
 
 
Factura de Compra FCR/20200002022 abona la factura de venta C/20200001486 y genera la nueva factura C/20200002363
Prefactura de Compra FC/2020006262 vuelve a abonar la factura de venta C/20200001486 y genera la nueva factura de venta C/20200005668

**Comment by PKFEric** [comment]
He estado mirandolo con Monica, y he estado revisando el codigo, no soy capaz de entender por que ha cogido la primera y no la ultima. Como no se puede replicar por que las facturas ya estan registradas he metido un error para que salte la proxima vez que esto suceda. Es decir si llega una tipo VI y es R saltara este codigo:

//ATT_ERIC #824 Temporal para poder solucionar la tarea
    if(rLTollMeasure."Invoice Type" = 'R') then
                  ERROR('Contrato Tipo VI con tipo factura R mirar tarea GIT #824');
//ATT_ERIC #824 Temporal para poder solucionar la tarea

Por otro lado ya he hablado con monica de como Resolver el tema.

Habria que:

Desliquidar el Abono AC/2020000057 
Generar una factura para liquidarlo contra el abono AC/2020000057 
y Generar un abono para la factura C/20200002363 de esta menera quedaria cuadrada la contabilidad de este contrato.
