### ISSUE TITLE
NAV-COM/00864- abono calidad de suministro

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#825]
COM/00864
F1 de compra J320005172603
Se compone de:
factura estandar de peaje: 
Abono por calidad de suministro: (importe -25,95€)
Suplementos territoriales 13,75€

ESto debería generar una factura de venta con el peaje y los suplementos territoriales y un abono de venta con el abono por calidad de suministro. ¿qué se ha generado?

VENTA:

C/20200005929:  Factura correcta en cuanto a importe en la que se replican consumos e importe de suplementos territoriales por importe 13,75€. Problema: No se le asocia el peaje
C/20200005930: factura incorrecta que contiene una línea negativa de abono de calidad de suministro y  3 líneas de suplementos territoriales por importe cada una de 171,92 (yo creo que ha metido todo lo que  eran otros conceptos). ESta factura tiene asociada el peaje. Como no dió ningún error esta factura se registró por lotes.

¿le echáis un ojo?

Gracias

**Comment by PKFEric** [comment]
Ya esta solucionado. Habia un error de un filtro en la generacion de otras facturas. 
Ya he generado el abono de calidad de suministro esta abierto en pre abonos en el contrato. Y he enlazado el peaje como tiene que quedar.

Lo que faltaria es hacer un ABONO por esta factura : C/20200005930
