### ISSUE TITLE
WEB - No se debe permitir contratar con potencia 0

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#826]
![image](https://user-images.githubusercontent.com/47117960/80008586-3b36e380-84c8-11ea-85e9-c32628c985f7.png)

**Comment by PKFEric** [comment]
YA ESTA EN ATULADO SUBIDO EN PRO

**Comment by PKFEric** [comment]
Ya esta corregido en proxima ahora lo subo con los demas desarrollos

**Comment by PKFEric** [comment]
![image](https://user-images.githubusercontent.com/20229934/80112039-edca7d00-8580-11ea-80de-9bd8689a27ec.png)

**Comment by dgarciageo** [comment]
Tests ok

![image](https://user-images.githubusercontent.com/47117960/80356474-ceca3480-8879-11ea-9da0-8b6ee24ce0af.png)
