### ISSUE TITLE
NAV - Pregunta / Tabla valores OCSUM

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#827]
Buenas Eric,

Tenemos que actualizar algunos nombres de distribuidores pero no me cuadra lo que veo en NAV en valores OCSUM 

![image](https://user-images.githubusercontent.com/47117960/80359920-d9d39380-887e-11ea-8f0f-0983099e1481.png)

Con lo que hay en la tabla GEOATLANTER$Códigos OCSUM de Navision

select * from NI.GEOATLANTER_SQL.[dbo].[GEOATLANTER$Códigos OCSUM] tb where tb.[Table No_] = 1

Sabes donde se almacena lo que se ve en NAV?

Muchas gracias

**Comment by PKFEric** [comment]
Esa tabla es compartida entre todas las empresas, eso quiere decir que existe en BBDD una tabla que no tiene prefijo de empresa. ESA es la que tienes que usar.

**Comment by dgarciageo** [comment]
Buenas Eric,

Sin prefijo de empresa sólo veo estas, no veo Codigos o valores OCSUM sin empresa

![image](https://user-images.githubusercontent.com/47117960/80382617-c5a18d80-88a2-11ea-9f46-913467b22496.png)

![image](https://user-images.githubusercontent.com/47117960/80382467-9e4ac080-88a2-11ea-9f60-62fbc37990f4.png)

**Comment by dgarciageo** [comment]
SELECT *
from
[Ocsum Value]
