### ISSUE TITLE
NAV- Cálculo Impuesto eléctrico factura de comercialización

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#828]
Hay un caso en que el cliente está exento de impuesto eléctrico, es cuando no se factura energía y además la medida es real,
Para ello hay que revisar los cierres del F1, cuando la suma de consumo calculado de todos los periodos de la magnitud activa entrante sea cero y además el campo la procedencia tanto de la lectura desde como de la lectura hasta de las medidas consideradas es distinta de 40 y de 99.

En estos casos no hay impuesto eléctrico. Hay dos opciones

1.- Directamente no hay línea
2.- El campo cantidad de la línea de impuesto eléctrico es 0 de tal forma que el importe de la línea sea 0

Lo más cómodo para que no afecte a la impresión de facturas

**Comment by JMunoz17** [comment]
He considerado los valores 40 y 99 tanto para la procedencia desde como para procedencia hasta, es correcto?

O debe ser el 40 para procedencia desde y el 99 para procedencia hasta?

**Comment by bpesquero** [comment]
Es correcto, tanto la lectura desde como la lectura hasta deben tener
procedencia diferente de 40 y 99

Gracias


*Belén Pesquero Fernándezbpesquero@geoatlanter.com
<bpesquero@geoatlanter.com>*
Av. de Europa, 34B Esc. Dcha. 3º 28023, Madrid
 *917 378 443*
 *647 533 013*
<http://www.geoatlanter.com/>


*Síguenos en:*[image: Facebook pequeño]
<https://www.facebook.com/proximaenergia/>[image: Twitter pequeño]
<https://twitter.com/proximaenergia?lang=es>[image: Google+pequeñito]
<https://plus.google.com/114547235710296874519>

*AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener información
*confidencial *sometida a secreto profesional. No está permitida su
reproducción o distribución sin la autorización expresa de *GEOATLANTER SL.*

Si usted no es el destinatario final por favor elimínelo e infórmenos por
esta vía.



De acuerdo con lo establecido por el Reglamento General de Protección de
Datos (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de
2016, le informamos que sus datos serán tratados con la finalidad de
realizar la gestión administrativa, contable y fiscal, así como el envío de
comunicaciones comerciales  sobre nuestros servicios y/o productos.


Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, oposición, supresión, limitación y portabilidad de
sus datos en el domicilio de *GEOATLANTER SL *sito en: Avda de Europa 34B
<https://maps.google.com/?q=Avda+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha 3º,  28023 Madrid o enviando un correo electrónico a la siguiente
dirección : *contacto@geoatlanter.com <contacto@geoatlanter.com>*

Si usted no desea recibir nuestra información, póngase en contacto con
nosotros enviando un correo electrónico a la dirección:
*contacto@geoatlanter.com <contacto@geoatlanter.com>*

**Comment by JMunoz17** [comment]
Subido a PRE.

**Comment by JMunoz17** [comment]
Lo hemos hecho de tal forma que aplica tanto a los contratos que tienen marcado el check "Exento impuesto eléctrico" como a los que no. De esta forma si se cumplan las condiciones arriba especificadas la línea de impuesto eléctrico (que es la de las retenciones) tendrá cantidad e importe a 0.

Prueba realizada en PRE, echarle un ojo antes de subirlo a PROD.
 - COM/02148
 - FV/2020002410

Ahora mismo la línea saldría con cantidad e importe a 0. Si queréis que la línea no aparezca tendríais que marcar el check de "no insertar a cero" en las plantillas correspondientes para la línea de tipo Impuesto Eléctrico.

**Comment by bpesquero** [comment]
La factura es correcta pero la procedencia no es la, que habíamos indicado así que no debería salir la línea a cero, no?

**Comment by bpesquero** [comment]
probado y ok

**Comment by JMunoz17** [comment]
Subido a PROD.
