### ISSUE TITLE
NAV - control potencia facturada 2

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#83]
Poner control al realizar la factura de venta de que la potencia facturada coincide con la potencia facturada en el término de potencia de la factura de peaje. Con esto localizamos, entre otros, si por ejemplo el peaje se está facturando con maxímetro y nosotros no lo tenemos como tal.

**Comment by PKFEric** [comment]
SUBIDO->PROBAR

**Comment by bpesquero** [comment]
Lo he probado y no funciona bien, creo que esta comparando dos cosas que no son. Tiene que comparar la potencia a facturar en  la factura de venta con la potencia  facturada en la factura de compra, es decir con el campo potencia a facturar de la tabla toll measures.
Lo que está haciendo es comparar la potencia contratada con la potencia facturada.

**Comment by PKFEric** [comment]
Efectivamente lo estaba comparando con potencia contratada y no con potencia a facturar, pero ya esta corregido.

**Comment by bpesquero** [comment]
probado y ok
