### ISSUE TITLE
NAV - Limpiar campos tabla Contract

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#834]
¿Se pueden borrar los siguientes campos de las tablas de contrato de geo y hecen?
¿Pueden ser campos anteriores a la creación de la tabla Actions Historic?

,[Nombre Cliente Saliente]
      ,[Apellido 1 Cliente Saliente]
      ,[Apellido 2 Cliente Saliente]
      ,[Cod_ Cliente Saliente]
      ,[Pendiente de Aceptacion M1]
      ,[Duration]
      ,[Potencia 1 Nueva]
      ,[Potencia 2 Nueva]
      ,[Potencia 3 Nueva]
      ,[Potencia 4 Nueva]
      ,[Potencia 5 Nueva]
      ,[Potencia 6 Nueva]
      ,[Hay Cambio Titular]
      ,[Hay Cambio Tarifa ATR]
      ,[Hay Cambio Potencia]
      ,[Tarifa ATR Nueva]
      ,[Cod Titular Nuevo]
      ,[IndicadorTitularNuevo]
      ,[IdentificadorTitularNuevo]
      ,[No Serie Contador]
      ,[Cliente Singular]
      ,[Equipo con med_ horaria desde]
      ,[boolTitularNuevoIgualPagador]
      ,[tipoContratoNuevo]

**Comment by dgarciageo** [comment]
Añadimos los siguientes campos también a cero

[Ocsum Status]
,[Reader Locked]
,[Tipo Cambio]

Los siguientes campos tiene información duplicada ya que tenemos la información de dirección de suministro en Supply address:

,[Address]
,[Address 2]
,[City]
,[Phone No_]
,[Telex No_]
,[Post Code]
,[County]

**Comment by dgarciageo** [comment]
Tenemos 
,[Name Customer]
,[Holder Name]

Y aparte estos
,[Name Customer1]
,[Family Name 1]
,[Family Name 2]
,[Portal]
,[Piso]
[Escalera]

**Comment by PKFEric** [comment]
Dani, disponemos de un programa que nos dice el lugar en el que se usa cada campo de una tabla, podemos ver que campos son y decirte los que podemos borrar. Te anticipo que esos que pones ahi se utilizan.

**Comment by dgarciageo** [comment]
Ok, los dejamos entonces.

Muchas gracias
