### ISSUE TITLE
WEB Atulado - Problema  validación de los campos formulario contratar

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#835]
**### IMPORTANTE: ANTES DE EMPEZAR CON LA TAREA DADNOS POR FAVOR UNA ESTIMACIÓN DE HORAS**

--------------------------------------------------------------------

Algunos ejemplos

![image](https://user-images.githubusercontent.com/47117960/81052230-5b50a480-8ec3-11ea-8627-d19c5dfe2041.png)

![image](https://user-images.githubusercontent.com/47117960/81052352-9226ba80-8ec3-11ea-83fb-1a64d78f896f.png)

![image](https://user-images.githubusercontent.com/47117960/81052558-f184ca80-8ec3-11ea-9d74-7eed9a518394.png)

**Comment by PKFEric** [comment]
Solucionado y subido a pro
