### ISSUE TITLE
NAV-Ficha autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#836]
Necesitamos tener en la ficha de autoconsumo un indicativo de si tenemos o no contrato firmado. No sé si lo más fácil es poner un campo booleano o un selector de estado por si quieremos ir añadiendo más cosas, o si podemos reciclar algún campo, qué proponéis?

**Comment by JMunoz17** [comment]
Una duda Belén, cuando dices indicativo de si tenemos o no el contrato firmado, te refieres al estado del Contrato en NAV? 

O no tiene nada que ver y es un nuevo campo a nivel informativo del contrato de autoconsumo?

**Comment by bpesquero** [comment]
SE trata del contrato de gestión de excedentes de la planta de autoconsumo, no del contrato de suministro. En realidad es un anexo que se firma al contrato de suministro. 
Si quieres coméntalo con Eric porque en la nueva versión es algo que se controlará desde la API,
Gracias

**Comment by JMunoz17** [comment]
Hemos creado un nuevo campo a nivel informativo en la ficha de contrato de autoconsumo.

Nombre del campo: Estado.
Valores posibles: " ",En Trámite,Firmado

El valor "En trámite" lo hemos añadido ya que si un contrato ya ha sido firmado y se produce algún cambio que requiera de una nueva firma, mientras esta se produzca la idea es que el estado del contrato pase a "En trámite".

Subido a PRE y PROD.

**Comment by dgarciageo** [comment]
Probado y ok
