### ISSUE TITLE
NAV- Generación de ficheros xml switching-campo NIF/CIF

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#838]
En los ficheros generados  OCSUM M. C1. C2. A3 en el campo NIF/CIF deberíamos hacer un cast para que la letra fuera siempre en mayúsculas, Hay distribuidoras que nos rechazan las solicitudes por este motivo

**Comment by JMunoz17** [comment]
Modificado en:
C1_01
C2_01
A3_01
M1_01

Subido a PRE y PROD.
