### ISSUE TITLE
NAV- errata D1

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#839]
En la documentación de la CNMC relativa a las especificaciones del D1 había un errata, donde debía poner "registro" ponía "registo". Nosotros lo hemos implementado con esa errata así que al importar el D1 del distribuidor da error de campo no existe. Deberíamos corregir esto.

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

**Comment by dgarciageo** [comment]
El correcto es InfoRegistroAutocons aunque hay distribuidoras que siguen poniéndolo mal. 

Sería necesario que admitiese ambas formas:
InfoRegistoAutocons e InfoRegistroAutocons (ya que hay distribuidoras que ya lo ponen bien y otras mal).

**Comment by dgarciageo** [comment]
duplicada en 

NAV- D1 problema con errata nodo #867
