### ISSUE TITLE
NAV - nº de solicitud OCSUM

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#84]
Cambiar nº de solicitud  cuando existe otra anterior a través de un secuencial

**Comment by PKFEric** [comment]
En el caso de que sea un M el usuario puede decir si el secuencial es una nueva solicitud o aumentar el secuencial

**Comment by PKFEric** [comment]
SUBIDO ->PROBAR

**Comment by PKFEric** [comment]
Esta parte hay que configurarla en Configuracion de empresa tanto para Geoatlanter como para Hidroelectrica el Carmen.

**Comment by bpesquero** [comment]
probado y ok
