### ISSUE TITLE
NAV-campos adicionales ficheros xml

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#840]
ESTA TAREA ME GUSTARIA QUE ME LA ESTIMARAIS ANTES DE EJECUTARLA

en la actulidad al generar un xml se rellenan los campos que difinimos como obligatorios. Sin embargo, en muchas ocasiones es necesario rellenar campos adicionales. Esto nos obliga a abrir el xml y meter los campos de forma manual. Sería ideal tener la opción de, desde la pantalla de histórico de acciones, poder completar cualquier campo de los deifnidos en el esquema xml para que el fichero se generara con esos campos.

**Comment by JMunoz17** [comment]
Entendemos que esto aplica a los siguientes pasos:
C1_01
C2_01
M1_01
A3_01
D1_02 Aceptación
D1_02 Rechazo

Corrígeme si me equivoco.

En primer lugar tendríamos que revisar el numero total de campos a crear en la tabla de histórico de acciones, para ello tendríamos que revisar la documentación de la CNMC y cotejarla con los campos ya creados en esta tabla y ver si tenemos espacio suficiente para crear todos los campos necesarios.  Esto nos llevaría 2 horas, no creo que haya problema con el espacio pero hay que revisarlo antes de hacer nada.

Actualmente los datos que exportamos a los ficheros xml tienen diferentes orígenes:
 - Del registro de histórico de acciones correspondiente.
 - Valores que se obtienen de diferentes tablas en función de diversos criterios, por ejemplo, los datos de la dirección del cliente.
 - Valores fijos que insertamos directamente en los xml.

La idea es que podáis modificar cualquier dato que se exporta a estos xmls desde el histórico de acciones antes de darle a generar fichero.

Para ello tendríamos que modificar todos los xmls para cambiar el origen de cada uno de los datos y modificar los procesos en los que generamos los registros del histórico de acciones para que contengan todos los datos que actualmente se exportan al xml.

Estimamos que nos llevaría:
Análisis numero de campos a crear para comprobar si hay espacio en la tabla: 2 horas.
C1_01 -> 1 jornada.
C2_01 -> 1 jornada.
A3_01 -> 1 jornada.
M1_01 -> 2 jornadas.
D1_02 Aceptación y Rechazo -> Media Jornada.

1 jornada = 8 horas.

Total: 46 horas.

**Comment by dgarciageo** [comment]
Adicional mente, tras esta modificación, sería necesario borrar los campos que ya no sean usen de la tabla de contratos. Necesitamos hacer espacio para nuevas funcionalidades de la nueva API/ Web. ¿Nos podéis por favor valorar también esta última tarea?

**Comment by bpesquero** [comment]
Perdonad, no había visto la valoración de horas. Es muy elevada para que lo queremos hacer ahora. 
Para ver si podemos hacer algo más acotado. ¿De donde se obtienen ahora los datos para generar el xml?

Gracias

**Comment by JMunoz17** [comment]
Actualmente los datos que exportamos a los ficheros xml tienen diferentes orígenes:

- Del registro de histórico de acciones correspondiente.
- Valores que se obtienen de diferentes tablas en función de diversos criterios, por ejemplo, los datos de la dirección del cliente.
- Valores fijos que insertamos directamente en los xml.

**Comment by bpesquero** [comment]
Muchas gracias por la info. Vamos a cerrar la incidencia porque ahora mismo es demasiado tiempo.
