### ISSUE TITLE
NAV- nodos de potencia en C2 y M

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#842]
DE ESTA INCIDENCIA ME GUSTARÍA TENER PREVIAMENTE UNA VALORACIÓN DE HORAS

Cuando generamos un C2 o M informamos de todos los nodos de potencia, los que corresponden con su valor correspondiente y el resto con valor 0. Es decir, si es una 20DH se meten dos nodos con el valor de la potencia y el resto a 0.
NOs está provocando rechazos en algunas distribuidoras. DEberíamos informar en cada caso sólo de los periodos que correspondiese

**Comment by JMunoz17** [comment]
1,5 horas

**Comment by bpesquero** [comment]
Adelante. Ojo con mantener el control que tenemos en la tabla de OCSUM de si hay que informar, en el caso de la DH; de un periodo o de dos.

Gracias

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
