### ISSUE TITLE
NAV- cambio de tarifa A tu lado energía HECEN/01134

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#843]
EL cliente ha hecho por la web una modificación de tarifa. HA firmado el contrato, pero no se ha generado en NAV ningún registro en histórico de acciones...

No sé si tendrá relación con la modificación que hemos hecho en los M

**Comment by dgarciageo** [comment]
Creo que está relacionado con la siguiente incidencia

NAV - Error M ATULADO HECEN/11202 Cambio Milenial a MILENIAL +10 #876

**Comment by dgarciageo** [comment]
Adicional-mente Ainhoa me comenta lo siguiente:

HECEN/11202 ha solicitado un cambio de tarifa de una 2.0DHA MILENIAL ( tarifa 96) con 3,3kW a una MILENIAL +10 con 10,392kW. El email del contrato ha salido y lo ha firmado, sin embargo no se ha creado la línea de histórico de acciones del NAVSERVICE.

![image](https://user-images.githubusercontent.com/47117960/84039755-044a5d80-a9a2-11ea-81a2-907b35f39d93.png)

Estamos al habla con el cliente, para que envíe el documento de estar dado de alta como autónomo (ya que fue una bajada por COVID que hizo con su anterior compañía). En cuanto lo envíe, generaré el M de forma manual para no demorarlo.

![image](https://user-images.githubusercontent.com/47117960/84039776-0b716b80-a9a2-11ea-934f-d7d608ae4c08.png)

**Comment by dgarciageo** [comment]
He replicado el fallo con un contrato que tiene la DHA e intentado contratar MILENIAL +10

Se produce el siguiente fallo:
![image](https://user-images.githubusercontent.com/47117960/84257659-f87fa800-ab15-11ea-9c93-47d8d84e53fe.png)

**Comment by JMunoz17** [comment]
Ya tiene que generar el M1.
Subido a PRE y PROD.

**Comment by dgarciageo** [comment]
Probado y ok
