### ISSUE TITLE
NAV- error al procesar C1_05 por redondeo de potencia

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#845]
Al procesar los C1_05 muchas veces da error porque la potencia del contrato no coincide con la potencia del C1.
Realmente en muchos casos se trata de un problema de redondeo. 
El contro debería hacerse con un redondeo de 1 cifra, y en cualquier caso, si la potencia del contrato no idéntica a la del C1 se actualizará la del contrato con la del C1.

**Comment by JMunoz17** [comment]
He añadido el redondeo a un decimal en el control, pero a esto que me dices _"y en cualquier caso, si la potencia del contrato no idéntica a la del C1 se actualizará la del contrato con la del C1"_ no le veo sentido ya que eso significa eliminar el control.

Al no ser que quieras que dejemos un aviso en el log, o que solo lo hagamos si la diferencia no es mayor a x valor.. algo así.

De momento solo he metido el tema del redondeo a 1 decimal (**confirmame si cuando dices redondeo de una cifra te refieres a 1 decimal, entiendo que si, pero por si acaso**) de ambas potencias a la hora de hacer el control, que debería reducir mucho los errores.

Subido a PRE y PROD.

**Comment by bpesquero** [comment]
Perdona Jaime, que me explico fatal.
Efectivamente me refiero a redondear a un decimal.
En cuanto a lo de cambiar el valor del contrato, lo que implica además volver a generar precios y potencia, me refiero que si al redondear a un decimal el valor es el mismo, pero con los decimales informados en cada caso no son iguales, actualicemos el valor del contrato.

Ejemplo:
C1: 3,44
NAV:3,43

El control no da error y actualizamos el valor del contrato a 3,44

**Comment by JMunoz17** [comment]
Ok, entendido.
Subido a PRE y PROD.

**Comment by JMunoz17** [comment]
Esto solo os pasa en el C1_05?
He visto que tenemos el mismo control de potencias en los pasos:
C1_02 Acept
C2_02 Acept
C2_05
A3_02 Acept
A3_05
M1_05 (En este caso el control es algo diferente ya que si encuentra un registro en el hist. de acciones de cambio de potencia compara las potencias del fichero con las de este hist. acciones, si no lo encuentra las compara con las del contrato como en el resto de caso).

Puede ser que tengamos que añadir esta modificación también en todos estos pasos?

**Comment by bpesquero** [comment]
YA lo pensé. Realmente tiene poca ocurrencia, pero quizá lo mejor es igual en todos los puntos

**Comment by JMunoz17** [comment]
Lo hemos modificado en todos los pasos.
Subido a PRE y PROD.
