### ISSUE TITLE
NAV- Problema con ficheros F1 asociados que "desaparecen"

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#847]
TEnemos un problema que está apareciendo cada vez con más frecuencia. En un principio pensamos que era un  problema puntual.

Pongo un ejemplo
En HECEN, contrato que se le ha facturado la venta y no tiene la factura de compra registrada ni pendiente en el proveedor, es el HECEN/09876. La factura de venta si tiene asociado el peaje. Tenemos el F1 tanto en toll measures como en closing measures.
Concretamente le falta la factura de compra asociada a la H/20200015789 que es la factura S7001N08588263.
El fichero F1 correspondiente no está en NI ni en procesados ni en pendientes de procesar.
20200327031632-F1-ES0031104092344041DY0F_0012.xml

**Comment by PKFEric** [comment]
Esto es lo que creo que pasa:

1. Se importa el peaje y se crea la factura de compra y se rellena toll measure y closing measure. 
2. Se ve que todo es correcto y se genera la venta sin haber registrado la compra.
3. Se borra la prefactura de compra. Como el toll y closing ya tienen un numero de venta registrada de la tabla de closing y toll no se borran los registros.

**Comment by PKFEric** [comment]
Que control implementamos?

**Comment by bpesquero** [comment]
ESto es lo mismo que pensamos nosotras en un principio pero Mónica anda con mucho cuidado y no borra ya nada, así que no entiendo...

Pues no sé, deberíamos poner uno al borrar la factura de compra indicando que ya está la hecha la factura de venta (en prefactura o registrada) y asociada a esa factura de compra

Y luego habría que poner otro control por si no está ahí el problema en la factura de compra, pero no sé muy bien cómo, quizá podrían ser dos uno en la generación y otro en el registro de la factura de venta ver que existe la factura de compra asociada.

**Comment by PKFEric** [comment]
Hemos estado mirando esta mañana entre monica y yo a ver si dabamos con el fantasma y ya hemos descubierto cual es. Ella te lo puede contar por no extenderme. Y ya he implementado la solucion que tambien la hemos consensuado para que fuera de la manera que mas se adaptara al trabajo de monica.
