### ISSUE TITLE
NAv- Problema con CP

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#848]
Otro problema con un ´codigo postal. Se trata del 48940 LEIOA. Podríamos darlo de alta. Lo hemos metido "a mano" en NAV, pero si no lo corregimos no sale en los informes de IMU y demás.

**Comment by PKFEric** [comment]
Ya esta en la tabla de codigos postales de HECEN Y GEO

**Comment by dgarciageo** [comment]
Probado y ok

![image](https://user-images.githubusercontent.com/47117960/84015280-e538d500-a97b-11ea-8cfc-fb9d55b7138e.png)
