### ISSUE TITLE
NAV- error carga D1

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#849]
Al cargar un   D1 con motivo 05 Modificación de tipo de autoconsumo aparece un log

![image](https://user-images.githubusercontent.com/20299071/81822110-fcc69e80-9532-11ea-9cde-f26f95d418fa.png)

y no carga el fichero. 
Está bien que dé un log, pero no que no cargue el fichero

**Comment by JMunoz17** [comment]
Modificado y subido a PRE y PROD.

Creo que esta tarea y la #839  son la misma no? Si es así eliminad la #839

**Comment by bpesquero** [comment]
Es sobre el mismo fichero, pero es una incidencia diferente


*Belén Pesquero Fernándezbpesquero@geoatlanter.com
<bpesquero@geoatlanter.com>*
Av. de Europa, 34B Esc. Dcha. 3º 28023, Madrid
 *917 378 443*
 *647 533 013*
<http://www.geoatlanter.com/>


*Síguenos en:*[image: Facebook pequeño]
<https://www.facebook.com/proximaenergia/>[image: Twitter pequeño]
<https://twitter.com/proximaenergia?lang=es>[image: Google+pequeñito]
<https://plus.google.com/114547235710296874519>

*AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener información
*confidencial *sometida a secreto profesional. No está permitida su
reproducción o distribución sin la autorización expresa de *GEOATLANTER SL.*

Si usted no es el destinatario final por favor elimínelo e infórmenos por
esta vía.



De acuerdo con lo establecido por el Reglamento General de Protección de
Datos (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de
2016, le informamos que sus datos serán tratados con la finalidad de
realizar la gestión administrativa, contable y fiscal, así como el envío de
comunicaciones comerciales  sobre nuestros servicios y/o productos.


Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, oposición, supresión, limitación y portabilidad de
sus datos en el domicilio de *GEOATLANTER SL *sito en: Avda de Europa 34B
<https://maps.google.com/?q=Avda+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha 3º,  28023 Madrid o enviando un correo electrónico a la siguiente
dirección : *contacto@geoatlanter.com <contacto@geoatlanter.com>*

Si usted no desea recibir nuestra información, póngase en contacto con
nosotros enviando un correo electrónico a la dirección:
*contacto@geoatlanter.com <contacto@geoatlanter.com>*

**Comment by JMunoz17** [comment]
Ok, lo hemos cambiado para que el primer mensaje en lugar de ser un error sea un aviso en el log. 

Ya están ambas tareas subidas a PRE y PROD. Actualizo la otra tarea.

**Comment by bpesquero** [comment]
Os traslado lo que me dice Ainhoa
He importado un montón de D1 en GAC y HECEN y me salta el siguiente log:


20200522031812-GRCW_0021_0713_D1_01_15.xml | El contrato HECEN/11503 no esta habilitado como contrato de autoconsumo.
-- | --


Esto me haría pensar que hemos recibido muchos D1 de autoconsumo, pero no es así, ya que son todos motivo 01 telegestioón operativa con CCH (tabla 109 Motivo Cambio ATR Desde Distribuidora)
 
Realmente esto estaba bien antes, ya que cuando era un motivo 01 me avisaba de que era un Telegesti¢n Operativa con CCH en el log,  para que pudiera borrarlo sin revisar uno a uno. Pero han cambiado el mensaje, imagino que al corregir el tema del motivo 04 y 05…

**Comment by JMunoz17** [comment]
Te cuento los controles que tenemos y me dices a ver como tiene que ser el criterio que no lo tengo nada claro:

Lo que hacíamos era mostrar un error siempre que el motivo de cambio fuera diferente a 04. Este error os aparecía en el log y la importación no se realizaba. Pero aunque lo vieseis en el log era un error, no un aviso.

Lo que hice el otro día fue cambiar el error por un aviso, que se mostraría en el log. Evidentemente, no entendí bien lo que necesitabais..

Hasta donde yo entiendo, los que tengan motivo 04 deben ser procesados como se hacia hasta ahora. Y habría que añadir también los 05. Para el resto de motivos debemos dejarlo como estaba antes con un error de tal forma que avise en el log y el fichero no se importe. Es correcto esto?

**Comment by bpesquero** [comment]
Me parece bien cambiar en todos los casos el error por aviso, con tener un aviso indicando la situación ese suficiente. DEja libertad al usuario para hacer lo que considere correcto.

**Comment by bpesquero** [comment]
Perdón, no te había entendido bien. Efectivamente, sólo tienes que cargar los que tienen motivo 04 y 05, en el caso de que sea 05 escribimos además en el log. Para el resto de casos damos un error y no se carga el fichero y escribimos el error en el log.

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
