### ISSUE TITLE
NAV-Valor gastos de gestión de excedentes

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#850]
Cuando se carga la ficha de autoconsumo se rellenan los campo de gastos de gestión de excedentes fijos y variables. Ahora mismo no recuerdo muy bien en base a qué se rellenan, Pensé que venía del PA, pero he revisado y he visto que no. La cuestión es que se ha cambiado el criterio. El valor de estos campos depende del máx de la potencia del contrato de comercialización asociado (no de la potencia de la instalación).

Potencia < 10 kW--> 
gastos fijos 2€/mes
gastos variables 0

Potencia >= 10 kW-->
gastos fijos 0
gastos variables 0,002 €/mes

**Comment by JMunoz17** [comment]
Los gastos fijos y variables los tenéis en la configuración de energía, están bien ahora mismo.

Lo único que cambia respecto a como lo teníamos es que solo estábamos comprobando la potencia para los gastos variables y lo hacíamos con la potencia de instalación del propio contrato de autoconsumo.

Subido a PRE y PROD.

Pasamos un proceso para actualizar estos datos en todos los contratos de autoconsumo existentes?? Confirmadme si es necesario.

**Comment by bpesquero** [comment]
Ok. Perfecto. Entonces entiendo que hemos cambiado el procedimiento y ahora se calcula en base a la potencia del contrato de suministro.

Ojo, a tener en cuenta no sé si ya para el nuevo desarrollo (que diga Eric) lo hacemos aquí. Cada vez que cambia la potencia de un contrato, hay que revisar la comisión de gestión de excedentes, cambiarla y en su caso generar un nuevo anexo y enviarlo por signatuit.
Entiendo que esta parte de enviar por signaturut requiere del proyecto que vamos a comenzar, pero quizá de momento podemos actualizar ese valor y escribir en el log o algo por el estilo para saber que tenemos que enviar el contrato a mano.
¿cómo lo veis?

Gracias

**Comment by JMunoz17** [comment]
En el paso M1_05 si hay cambio de potencia comprobamos si el contrato tiene algún contrato de autoconsumo asociado y en caso de que lo tenga actualizamos los valores de gastos fijos y variables. También sacaremos un mensaje el log con el siguiente texto: _Cambio de Potencia -> Contrato: %1 Cont. Autoconsumo: %2 . Enviar Anexo Signaturit._

Esto ya lo hemos subido a pre y prod, pero te dejo la siguiente consulta por si tengo que modificarlo: 

- A la hora de buscar si el contrato para el que hay cambio de potencia tiene contrato de autoconsumo asociado,  tendríamos que tener en cuenta las fechas de vigencia de este? En caso afirmativo, cual seria el criterio?

- Siempre que haya cambio de potencia, mostraremos el mensaje en el log. Debemos hacerlo solo si el cambio de potencia implica que los valores de gastos fijos y variables cambien? Es decir, solo si pasa de tener menos de 10 KW a mas de 10 KW o viceversa?

**Comment by bpesquero** [comment]
Si, hay que tener en cuenta las fechas de vigencia del contrato de autoconsumo

fecha inicio vigencia ficha autoconsumo <= FEcha de cambio de potencia < Fecha de vigencia del contrato de autoconsumo

Sólo se muestra el log sie el campo de potencia in¡mplica cambio de los valores de gastos fijos y variables. ¿el valor límite de 10 kW está por configuración o está metido en código)

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

**Comment by bpesquero** [comment]
Jaime, ahora me surge una duda. Cuando hay por ejemplo un cambio de titular en un contrato que tiene asociado autoconsumo y por tanto damos de baja un contrato y damos de alta otro, el autoconsumo se queda asociado al primero o también se cambia?

**Comment by JMunoz17** [comment]
El contrato de autoconsumo queda asociado al contrato antiguo, por lo que manualmente tenéis que finalizar ese contrato de autoconsumo y crear uno nuevo asociado al nuevo contrato. No tenemos contemplado nada para que lo haga de forma automática.

Se puede ver la posibilidad de automatizarlo, pero necesitaría saber que datos del contrato de autoconsumo se mantienen tal cual y cuales hay que modificar y en base a que.

**Comment by dgarciageo** [comment]
Ainhoa me comenta lo siguiente:

Ainhoa ha creado una ficha de autoconsumo para este contrato y se ha dado cuenta que la comisión que se rellena por defecto no es la correcta.

image
![image](https://user-images.githubusercontent.com/47117960/84041717-7328b600-a9a4-11ea-8e6d-c7ed6d6ddcfd.png)

image
![image](https://user-images.githubusercontent.com/47117960/84041751-7de34b00-a9a4-11ea-89d0-8797d475564d.png)

**Comment by dgarciageo** [comment]
He hecho una prueba en PRE y pasa lo mismo

![image](https://user-images.githubusercontent.com/47117960/84042668-a91a6a00-a9a5-11ea-8227-f94ba730f3ad.png)

**Comment by JMunoz17** [comment]
Ya esta modificado Dani, prueba de nuevo.

Dime si os hace falta que pasemos un procesito en PROD para que se recalculen estos campos en todos los contratos de autoconsumo.

**Comment by dgarciageo** [comment]
Probado y ok. No hace falta Jaime lo pasamos nosotros.  Muchas grcais!!!

![image](https://user-images.githubusercontent.com/47117960/84124826-0660fa80-aa3c-11ea-92b0-b9c43ce75f6e.png)
