### ISSUE TITLE
AMIGO - COM/00106

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#853]
Se están añadiendo saldos amigos sin que los contratos se hayan activado

**Comment by PKFEric** [comment]
El codigo esta en la activacion del usuario no en la activacion del contrato, un contrato no se activa hasta que no ha pasado el C1_05, en unico sitio de la web donde se controla esto es cuando el usuario activa su cuenta, ahi es donde se rellena la fecha de activacion del usuario, se crea la campaña amigo y se envia el mail de bienvenida.

**Comment by dgarciageo** [comment]
De acuerdo. En el nuevo API tendremos que cambiar el criterio porque ya no va a haber correo de activación. Podría ser cuando el amigo firme el contrato por ej.
