### ISSUE TITLE
NAV - Error al imprimir el contrato

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#854]
Antonio me pasa el siguiente error

![image](https://user-images.githubusercontent.com/47117960/82554099-927eb100-9b65-11ea-9726-4493d26af11c.png)

**Comment by JMunoz17** [comment]
En Hecen, en la configuración de contabilidad, pestaña "Suministro", tenéis configurada la siguiente ruta como destino: \\192.168.100.105\Esios\Contratos\

La carpeta Contratos no esta creada, de ahí que falle.
Tenéis que configurar una ruta válida o crear esa carpeta Contratos, probad que así os debería funcionar. Si no, me avisas.
