### ISSUE TITLE
NAV - CAmbio de estado de contrato con la firma en signaturit de un M o un contrato previamente rechazado

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#856]
********
ANTES DE REALIZAR ESTA TAREA ENVIADME POR FAVOR PREVISIÓN DE HORAS
******

Tenemos dos situación parecidas

1.- contrato con un C1 o C2 rechazado. Cambiamos a mano el contrato, lo enviamos al cliente por signaturit y cuando el cliente firma el contrato no cambia de estado, se queda en rechazado, así que no podemos ver qué contratos tenemos que tramitar, lo tenemos que ir comprobando de forma manual en signaturit. La idea sería pasarlo a firmado cliente

2.- Contrato ya activado sobre el que se hace un M, desde la web o manualmente (en función del tipo de modificación). Se genera el M en histórico de acciones, y cuando el cliente firma la modificación enviada por signaturit no se cambia el estado del contrato con lo que no sabemos nuevamente que M tenemos que tramitar. La idea sería la generar el M pasar el contrato a tramitación ATR y al firmarlo pasarlo a firmado cliente, para que supiéramos qué M de históricos de acciones están listos para tramitarse.

**Comment by PKFEric** [comment]
Creo Belen, que aqui la solucion pasaria por hacer para que el flujo de acciones y del contrato sean independientes.

Crear un campo en la ficha del contrato que sea estado Acciones que sea diferente del campo Estado.

El campo estado del contrato seria:
1. Creado
2. Creado Web
3. Firmado
4. Activado
6. Baja

Y el Campo Estado Proceso:
1. Sin Proceso
2. Pendiente tramitar C1, C2, A3, B1, M1 
3.  Tramitando C1,C2, A3, B1, M1
4....  Algo asi.

Igual seria bueno definir bien estos estados de los campos y los flujos que implica cada estado. Esto vendria bien para el futuro.

**Comment by bpesquero** [comment]
Lo que no tengo claro si en el futuro el control del estado de las acciones se va a hacer desde NAV o desde la API. En cualquier caso entiendo que separar el estado de ambas es algo detrás de lo que llevo muchísimo tiempo y que creo que facilitaría las cosas en muchos aspectos.
Antes de definir exactamente los estados por los que debe pasar una acción, podrías hacer una valoración en horas de lo que supondría desdoblar ambas valores. Mucho me temo que afecta a varios procesos, no es asi?

**Comment by dgarciageo** [comment]
¿Necesitaríamos hacer lo mismo con el contrato de ACSM? i.e. un estado para el contrato(este ya está) y otro para las acciones sobre el contrato de ACSM.

**Comment by bpesquero** [comment]
Yo creo que no, realmente las acciones son sobre el contrato, no sobre la ficha de autoconsumo, por tanto quedaría integrado con tener un estado para las acciones sobre el contrato.

**Comment by PKFEric** [comment]
Belen esto actualmente se utliliza en:

- Codeunit de la web para bajar el estado de Creado Web y Firmado cliente
- Codeunit de ocsum para la gestion de los estados por los que pasa el proceso en el historico de cacciones y la consecuencia en el estado del contrato.
- En algun control de los estado de los contratos, en botones y demas.


Yo creo que modificar esto no supone gran cosa. Lo que entiendo que deberíamos de hacer es plantear el nuevo modelo y en base a eso, si que te puedo valorar lo que supondría hacer la modificación.

**Comment by bpesquero** [comment]
Ok, Valoralo con el nuevo modelo

**Comment by JMunoz17** [comment]
Hemos revisado el alcance y estimamos 3 jornadas, pero nos gustaría saber exactamente como tienes pensado plantear el nuevo criterio de estados.
