### ISSUE TITLE
WEB- A tu lado (COTIZACIÓN)

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#857]
******
ANTES DE ACOMETER LA TAREA PASADNOS POR FAVOR UNA ESTIMACIÓN DE TIEMPO
********

en la parte pública publicitamos las tarifas milenial, nocturna y coche eléctrica, sin embargo en el formulario de contratación en el desplegable de tarifa a contratar aparecen milenial, 20DH,20DH, milenial +10,...
El cliente no sabe a que corresponde la noctura ni coche eléctrico.
La idea sería cambiar en el desplegable

20DH--> nocturna
20DHA--> coche eléctrico
21DH--> noctura + 10
21DHS--> coche eléctrico + 10

**Comment by dgarciageo** [comment]
Sobre lo que comenta Belén, a lo mejor es un buen momento para implantar en NAV la nueva estructura de tipos de contratos, haciendo uso de la entidad Tarifa.

**Comment by PKFEric** [comment]
Hacer el 1º Cambio supone meterle un alias a toda la web para cambios de tarifas, en contratacion area publica, contratacion area privada y cambio de tarifa area privada. Es bastante curro igual unas 3 horas.

Acometer lo de las tarifas es mas todavia, por que nos solo habria que hacer eso sino cambiar toda la estructura que existe ahora mismo en la web no creo merezca la pena invertir ahora en esto.

Me decis.

**Comment by bpesquero** [comment]
Para la 1ª parte no podríamos usar el campo nombre de la tabla tarifa?
Para la 2º parte coincido contigo

**Comment by dgarciageo** [comment]
Vamos adelante con lo que comenta Belén (3h)

**Comment by jorgereal** [comment]
Hemos realizado todos los cambios pertinentes tanto en la web de a tu lado como en NAV para mostrar en los desplegables de la web las tarifas con los nombres solicitados.

Subido a prod.

**Comment by dgarciageo** [comment]
Probado y ok

![image](https://user-images.githubusercontent.com/47117960/93865605-d83fb780-fcc6-11ea-884f-395a3df6f91b.png)
