### ISSUE TITLE
NAV - Actualización manual del estado de un contrato

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#858]
Permitir la modificación del estado del contrato desde la ficha contrato con validación previa. 
¿Quieres actualizar el estado del contrato (Aceptar / Cancelar)?

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

Simplemente recordaros que en GEO si asignáis el estado "Firmado Cliente" a un contrato se crean los contactos y se envía un email al vendedor.

**Comment by dgarciageo** [comment]
probado y ok
