### ISSUE TITLE
WEB/NAV - link

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#86]
Incluir en el mail de bienvenida un link a la web
Incluir en el mail de nueva factura un link a  la nueva factura y si no es posible, o es compliocado, al meno un link a la web
Quizá lo suyo es que en todos los mails debajo apareciese un link a la web.

**Comment by PKFEric** [comment]
Esta incluido en todos los mails de la web el enlace a proxima.
Esta hecho que redirija a la factura desde el mail
Falta ver si se puede acceder directamente al PDF.

**Comment by bpesquero** [comment]
Faltaría añadir el link en todos los mails que salen de NAV.

**Comment by bpesquero** [comment]
Aparece el link de GeoAtlanter en todos los mails. Queda pendiente de ver si se puede apuntar directamente a la factura, para ellos revisar si se puede imprimir el pdf en el ftp

**Comment by bpesquero** [comment]
Intento imprimir directamente en el ftp pero no me deja. Me dice : "La ruta de acceso especificada no es válida"
