### ISSUE TITLE
WEB Proxima -  Comisión de gestión inocrrecta

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#861]
Buenas,
 
Un cliente empresa,  se ha dado de alta COM/03005 para una potencia de 4,6 y tarifa 2.0A
 
El pantallazo final del proceso de contratación le ha informado una comisión de gestión de 0,5 c€/kWh, lo cual es incorrecto.

![image](https://user-images.githubusercontent.com/47117960/83397174-726cae80-a3fd-11ea-9f3f-ca9ad9ec295c.png)

 
Sin embargo, la ficha NAV es correcta,  2 euros al mes, y el contrato también, os pongo más abajo pantallazo.
 
Gracias, 
 
![image](https://user-images.githubusercontent.com/47117960/83397002-36394e00-a3fd-11ea-9b00-0eae4e1e33b5.png)

![image](https://user-images.githubusercontent.com/47117960/83396983-27eb3200-a3fd-11ea-9543-bdf4f62669ad.png)

**Comment by PKFEric** [comment]
Corregido

**Comment by dgarciageo** [comment]
Probado y ok

![image](https://user-images.githubusercontent.com/47117960/84023929-40bd8f80-a989-11ea-9f24-dd5ed351c65f.png)
