### ISSUE TITLE
NAV -  Cierre de energía saliente en las facturas de autoconsumo

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#865]
Tendríamos que poner una incidencia porque en las facturas de autoconsumo no estamos mostrando el cierre de energía saliente sólo el de energía entrante.

**Comment by JMunoz17** [comment]
Por confirmar, con esto os referís a que no salen en el formato que utilizamos para las facturas correspondientes a un contrato con algoritmo de autoconsumo NC?

**Comment by bpesquero** [comment]
Por lo que yo he visto en ningún tipo de autoconsumo sale en la parte de cierres la AS. En el caso de la NC sería suficiente con que apareciera en la de compra

**Comment by JMunoz17** [comment]
Modificado y subido a PRE y PROD.

En \\NI\EsiosPre\Jaime\ tenéis unas facturas generadas por si queréis ver rapidamente como sale.

Belén, para las NC lo he sacado en la venta porque es donde estamos sacando la información del consumo eléctrico. Entiendo que es ahí donde debemos meterlo, pero corrígeme si no es así.

**Comment by bpesquero** [comment]
Perfecto
