### ISSUE TITLE
NAV: limitar la comisión por gestión de excedentes

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#866]
Queremos poner un límite en las facturas que incluyen autoconsumo de los tipos SF, SC, NF

SF y SC
- la línea de gastos de gestión de por energía excedentaría no puede ser superior en importe a la línea de valoración de energía excedentaria.

NF

- tenemos una línea de compensación de excedentes que realmente suponer una minoración de la cuota de renting, por tanto esta línea tiene un valor máximo que es el de la propia cuota de renting

Una vez calculada la línea, tendríamos igualmente que limitar el valor de la línea de gestión de energía excedentaria al valor de la  línea de compensación de excedentes.

Por otra parte, revisando todo esto, he visto que esta línea aparece efectivamente como "compensación de excedentes", no me convence mucho, puedo yo cambiarlo directamente en la plantilla de facturas o hay que hacer algo más?

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
