### ISSUE TITLE
NAV- D1 problema con errata nodo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#867]
En relación a la incidencia que habrimos 
NAV- errata D1 #839
hay distribuidores que ponen "registro" y otros "registo" podríamos adaptarlo para que fuera capaz de interpretar ambos?

Gracias

**Comment by JMunoz17** [comment]
Hay dos nodos:
- InfoRegistroAutocons
- SeccionRegistro

Os pasa con los dos? o solo uno? Confirmadmelo porque para el de SeccionRegistro es muy facilito porque no tiene ningún nodo por debajo, pero el otro si que hay que "duplicar" casi todo el esquema.

**Comment by bpesquero** [comment]
Se trata del nodo InfoRegistroAutocons

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

**Comment by dgarciageo** [comment]
necesitamos que se contemplen las 2 posibilidades

InfoRegistro e IngoRegisto

**Comment by JMunoz17** [comment]
Así lo he hecho Dani.
Se contempla:
- InfoRegistroAutocons
- InfoRegistoAutocons

Lo probé en PRE y funcionaba.
Pasame el fichero y lo miro a ver si es que hay alguna diferencia mas.

**Comment by dgarciageo** [comment]
Buenas Jaime,

Perdona, tienes razón. Probado y ok.

![image](https://user-images.githubusercontent.com/47117960/84256427-2bc13780-ab14-11ea-9385-c78a07a9a3e8.png)
