### ISSUE TITLE
NAV- Geo- Pb facturación COM/008864

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#868]
En relación al contrato COM/00864, y factura de acceso J320000552940 ( fichero F1 -->SCTDE_F1_01_0022_0587_20200110080250126_(832081202))

Tenemos un problema, la factura esta dividida en dos tramos para el TP, y al cargar en NAV, además de dar una serie de errores en NAV, no genera de forma correcta la factura de compra, ya que deja un hueco en los tramos del TP.

Envío por email el fichero F1. La factura la hemos dejado en prefactura.

**Comment by JMunoz17** [comment]
Factura generada: FC/2020009485

El problema es que en el fichero venían informados los términos de potencia en orden inverso a la fecha. Es decir, venia primero el de enero y después el de diciembre.

Esto daba muchos problemas por el camino ya que realizamos muchas comprobaciones con la tabla de peajes y la ordenación a la hora de consultar esta tabla habitualmente no es por fecha sino por nº de factura que aumenta la rapidez de la búsqueda. Esto provocaba fallos, por ejemplo, en el calculo de fechas.

Hemos adaptado el proceso para que nos de igual el orden en el que vengan en el fichero, tenéis la factura generada, revisad que este todo ok.

**Comment by bpesquero** [comment]
Si, vi que los periodos venían informados en orden inverso y entendí que era por eso.
Creo que es el momento de solucionar un problema con las facturas que tienen dos tramos. Los criterios de fecha (+1D y 0D) no lo estamos aplicando a los dos tramos, de tal forma que siempre dan un error, los estamos cambiando a mano. Sería el momento de cambiarlo para evitar las actuaciones manuales. 
El fichero que yo os envié ya tenía este cambio hecho a mano. Os envío por email el original para corregir el problema.

**Comment by JMunoz17** [comment]
Belén, entiendo lo que me dices, pero tenemos la certeza que para cualquier F1 hay que aplicar el criterio de fechas tanto a la fecha desde como a la fecha hasta de todos los tramos? Si es así, es mas fácil que como lo estamos haciendo ahora.

Por otro lado, esto aplica tanto al termino de potencia como al resto no? Energía Activa, Exceso Potencia, Reactiva 1?

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
No lo he probado, no debería dar problema, pero me gustaría probarlo en PROD con este contrato. Si importáis algún F1 con varios tramos revisad que este ok.
