### ISSUE TITLE
NAV- GEO- CAmbio control de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#869]
En relación a los controles en la carga del F1 cuando se trata de una instalación de autoconsumo, quiero hacer un cambio en uno de ellos. En particular se trata del control que numeré con el 4.2 en el documento de controles que hicimos y que os envío por correo electrónico.

Se trata del control que compara el cierre de la factura y/o la energía facturada en TE con el F5D (FUNCONTROL_CIERRE_F5D_F1())
El caso particular de que aparezca AS en el cierre  hace dos comprobaciones

1-abs(AS-AE) del cierre= abs( Eimp - Eexp) del F5D               
2-TE=sum(Eimp F5D)

Si no coincide da el error " AS -AE del cierre  es diferente de AS -AE del F5D "

Pues bien, lo único que quiero hacer es quitar la primera de las comprobaciones
1-abs(AS-AE) del cierre= abs( Eimp - Eexp) del F5D 

quiero dejar sólo la segunda
2-TE=sum(Eimp F5D)

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

**Comment by bpesquero** [comment]
Hemos cargado las facturas y efectivamente ya no se hace ese control en la compra, pero he visto que ese control también existe en la venta, así que no podemos facturar


COM/01462 | ES0026000000891589QX | 01/02/2020 | 29/02/2020 | Error Autoconsumo, AS -AE del cierre 1.551 es diferente de AS -AE del F5D 1.859 | MGOMEZ | 10/06/2020 15:58
-- | -- | -- | -- | -- | -- | --


Me podrías qué controles con respecto a la energía se hacen en la venta? Si nuevamente comparamos cierre vs F5D y F5D vs facturación, habría que dejar esta última comparación.

**Comment by JMunoz17** [comment]
Si, están los dos controles. 
Comentamos el control entre cierre y F5D, al igual que hicimos en compra.
Subido a PRE y PROD.
