### ISSUE TITLE
NAV - factura de venta sin CCH

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#87]
SI tenemos un contrato con indicativo de curva de carga horaria para el periodo facturado y no tenemos las medidas no debemos facturarlo.

**Comment by PKFEric** [comment]
Indicativo curva carga-> Fichero F

1- Curva
2- Perfil
3- No tiene.

**Comment by PKFEric** [comment]
Probar para una factura de algoritmo de facturacion V
