### ISSUE TITLE
WEB Atulado- Incidencia Milenial +10 (Dchos de enganche)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#870]
Hemos detectado que los que se dan de alta en la Milenial +10  y que no tenían DH, les estamos cobrado los dchos de enganche, cuando no deberíamos hacerlo (así  se informa en la web)
Te paso ejemplos de contratos facturados:
 
HECEN/11109
HECEN/11573-> este nos ha reclamado que se lo abonemos

**Comment by JMunoz17** [comment]
Lo teníamos hecho para la MILENIAL pero no para la MILENIAL+10.
Modificado y subido a PRE y PROD.
