### ISSUE TITLE
NAV - Dirección fiscal en factura de Próxima Energía

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#872]
NECESITAMOS POR FAVOR COTIZACIÓN ANTES DE EJECUTAR TAREA
--------------------------------------------------------

Incluir la dirección fiscal dónde más fácil resulte en la factura de suministro de Proxima y Atulado.

Debajo de dirección de envío
![image](https://user-images.githubusercontent.com/47117960/83873626-6a31ad80-a734-11ea-8215-8ec9af5d7078.png)

O debajo de la dirección de suministro
![image](https://user-images.githubusercontent.com/47117960/83873803-c0065580-a734-11ea-94ac-aed94f4b477c.png)

**Comment by JMunoz17** [comment]
Creo que va a ser mejor debajo de la dirección de suministro utilizando el siguiente formato: Dirección, C.P., Población, Provincia). 

Por confirmar, los datos los sacamos de la pestaña Pagador de la ficha del contrato no?

Son 6 informes:
- Factura venta GEO.
- Factura venta HECEN.
- Abono venta GEO.
- Abono venta HECEN.
- Factura Autoconsumo.
- Factura Dchos. Enganche.

Estimación: 3 horas.

**Comment by bpesquero** [comment]
Ok. adelante. Pon en el título "Dirección fiscal"

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
