### ISSUE TITLE
NAV- Geo- FActuracion NC - COM/01426

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#874]
AL intentar facturar el contrato COM/01426 con autoconsumo NC no se realiza la factura de venta y deja en el log el siguiente error

El filtro '<>' no es válido.

Falta un valor en el filtro del campo Nº Fact. Venta Autoconsumo de la tabla Histórico cab. factura compra.

**Comment by JMunoz17** [comment]
He generado las facturas:
- Venta: FV/2020009645
- Compra: F01112260A/20200004
- Log:
![image](https://user-images.githubusercontent.com/26869276/84120309-ef1f0e80-aa35-11ea-8278-50f578880941.png)

**Comment by bpesquero** [comment]
compruebo que ahora sale el log que indica Jaime, que es correcto. Cierro la incidencia
