### ISSUE TITLE
NAV -  facturación valoración de excedentes

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#875]
Revisando la factura C/20200007969 he visto que en la valoración de excedentes se está considerando a 0 tanto el ingreso de generación como el peaje de generación.
Como veréis en configuración de energía hay un valor para el peaje a partir de 25 de enero con valor 0. ESte registro lo acabo de insertar, por tanto, la factura debería haber cogido el precio de peaje del regsitro con fecha de inicio 01/01/19.
Habría que revisar a cuantas facturas con valoración de excedentes ha afectado, porque mucho me temos que tendremos que abonar todo y volver a facturar. No sé en que momento se "ha estropeado" esto, ya que hicimos las pruebas correspondientes y salía bien.

Gracias

**Comment by JMunoz17** [comment]
Respuesta vía mail.

**Comment by bpesquero** [comment]
Lamento el error. Las instalaciones con compensación simplificada no tienen peaje de generación ni impuesto de generación
