### ISSUE TITLE
NAV - Error impresión Abonos calidad de suministro

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#879]
Hemos visto que no podemos imprimir los abonos de calidad de suministro en HECEN, el log es el siguiente:
Ejemplo: AC/2020000045

![image](https://user-images.githubusercontent.com/47117960/84140390-d58bc000-aa51-11ea-9264-5e428d971c69.png)

**Comment by JMunoz17** [comment]
He estado revisándolo y el formato del abono en HECEN no esta adaptado como si que lo esta en GEO.

Tengo que realizar una serie de modificaciones para que el formato funcione con estas facturas que si te fijas no tienen Nº factura corregida, de ahí que de ese fallo.

Lo único que para probar esto necesitaré una licencia libre, sobre que hora por la tarde se puede quedar libre alguna?

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.
Revisad que salga todo ok.
