### ISSUE TITLE
NAV- problema con nombre en mails con caracteres extraños

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#88]
He enviado correo electrónico con el ejemplo

**Comment by PKFEric** [comment]
PROBLEMA PARSEO DE CARACTERES EN MAILS ENVIO DESDE NAVISION

**Comment by jorgereal** [comment]
Había un problema con el parseo de las mayúsculas con tilde. Ya está arreglado.
SUBIDO -> PROBAR

**Comment by bpesquero** [comment]
Probado y ok
