### ISSUE TITLE
Facturación NC

### ISSUE THREAD

**Issue by JMunoz17** [PKFEric/webProxima#880]
Problemas facturación NC:
1 - COM/01426 - Importes incorrectos.
2 - Modificar proceso facturación para que en los algoritmos NC y NF utilice los valores de importe generación y precio peaje generación configurados buscando por día y no por la fecha desde de la factura.
3 - Revisar facturas NC y NF desde enero hasta el 08/06/2020. Habrá que abonar la diferencia ya que se facturaron utilizando el valor de precio peaje energía = 0,5 euros/MWH.

**Comment by JMunoz17** [comment]
1. El problema estaba relacionado con la tarea #791 que se subió hace poco y no se pudo probar. Ya están generadas las facturas con los importes correctos.
2. Modificado, probado y subido a PRE y PROD.
3. Belén, esto lo ibas a revisar tu?

**Comment by bpesquero** [comment]
1.- El importe es correcto
¿El punto 2 está modificado?

**Comment by JMunoz17** [comment]
Si
