### ISSUE TITLE
NAV - Control en NAV Potencia > 450 kW  no deje elegir un algoritmo que no sea de Oracle. 

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#881]
Control en NAV para que cuando la potencia sea por encima de 450 kW no deje elegir un algoritmo que no sea de Oracle. 

El criterio sería Algoritmo de Calculo == Tipo VI o Origen_Medidas_Contador == OR_CON

![image](https://user-images.githubusercontent.com/47117960/84173420-8e1b2900-aa7d-11ea-8bcb-f8945411f6e5.png)

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

**Comment by dgarciageo** [comment]
Buenas Jaime, una pregunta. 

Los tipos de contrato necesarios para contratar por encima de 450kW para próxima son los siguientes correcto?

01,02,19 y 24

Para hecen hemos configurado los mismos? Me cometa fer que para hecen el control no aplica, por lo que lo podemos desactivar.

Muchas gracias

**Comment by JMunoz17** [comment]
He seguido este criterio:
Algoritmo de Calculo == Tipo VI o Origen_Medidas_Contador == OR_CON

Ahora mismo funciona en ambas empresas, inhabilito el control para HECEN?

**Comment by dgarciageo** [comment]
Asi está perfecto Jaime. Déjalo como está.
Probado y ok.

muchas gracuas
