### ISSUE TITLE
NAV + WEB - Habilitar campaña AMIGO en Atulado

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#882]
NECESITARÍAMOS 1ERO COTIZACIÓN DE HORAS
---------------------------------------------------------------
Cuanto costaría habilitar la campaña amigo en Atulado?

**Comment by PKFEric** [comment]
La mayoria del trabajo de esto seria en la web, ya que habria que implementar la parte amigo, Con la interfaz y todo eso. La parte de NAV seria poco ya que estria todo paracticamente hecho, habria que configurar y ya esta.

Yo creo que en unas 4 jornadas podria estar.
