### ISSUE TITLE
NAV - Error en check F1 tipo ACSM

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#884]
hemos intentado cargar este F1

\\ni\esios\Buzones\FACTURACION\GAC\00. OK\20200515021634-F1-ES0031300542414001ML0F_000F.xml

NAV nos ha dado este error pero el tipo de ACSM es correcto (41)

Error XML, el tipo de autoconsumo del contrato: 41 no coincide con el tipo de autoconsumo informado en el F1: 0000000041..

**Comment by JMunoz17** [comment]
Dani, ya he visto que lo habéis modificado a mano poniendo 41.

Es habitual que os venga con esa ristra de 0s delante? Yo si queréis lo que puedo hacer es antes de realizar la comprobación quitar los 0s que vengan, como me digáis.

**Comment by dgarciageo** [comment]
Si, habría que quitar los ceros y el signo +

Muchas grcaias!

**Comment by JMunoz17** [comment]
Lo he hecho únicamente para ese control, no puedo hacerlo en la importación. He estado revisando y creo que no hay mas sitios donde afecte pero si hubiese otro sitio habría que cambiarlo ahí también. 

En la importación no puedo hacerlo porque hay otros conceptos repercutibles donde ese campo si que puede venir con 0s.

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

**Comment by dgarciageo** [comment]
Repetida en NAV - Error check F1 ACSM #889
