### ISSUE TITLE
NAV - Error check F1 ACSM

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#889]
Error check al cargar F1

**Error XML, el tipo de autoconsumo del contrato: 41 no coincide con el tipo de autoconsumo informado en el F1: 0000000041..**

\\NI\EsiosPre\F1\WAIT JAIME\20200601021633-F1-ES0031405114423001GH0F_0007.xml

**Comment by JMunoz17** [comment]
Modificado y subido a PRE y PROD.

Creo que esto lo vimos hace poco en otra tarea y al modificar el fichero para probarlo que ya estaba modificado y ponía 41 debí poner +000000041 en lugar de +000000041.00

Ya tiene que funcionar.

**Comment by dgarciageo** [comment]
Probado, sale otro error diferente pero el check de ACSM no salta

Error, Tenemos un contrato autoconsumo y no viene informada AS en el cierre

![image](https://user-images.githubusercontent.com/47117960/86785834-80989500-c063-11ea-8e19-f3684081f109.png)
