### ISSUE TITLE
NAV  - Error en factura precios de Abril

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#890]
Hemos cazado una factura a la que no se le han aplicado bien los precios de abril (solo son dos días, pero no es correcta) y no se muy bien porque… es la factura **H/20200022667** del **HECEN/09464**

**Comment by JMunoz17** [comment]
El término de energía es del 01/03/20 al 24/03/20, no tiene días de Abril. Es el termino de potencia el que viene con fecha hasta 02/04/20. Entiendo que esta ok, no?

**Comment by bpesquero** [comment]
Cierto, disculpad las molestias
