### ISSUE TITLE
NAV - Error letras NIF minúscula en solicitudes baja B1 

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#894]
He tenido un rechazo de una Baja (baja B1_01 cese actividad) por NIF no coincide con el del titular en vigor, y es por la letra en minúscula.
 
Se corrigió esto para las peticiones, pero no se realizó el cambio en las bajas 

Corregido a mano por el momento.

**Comment by JMunoz17** [comment]
Modificado el paso B1_01, subido a PRE y PROD.
