### ISSUE TITLE
NAV - Error F1 tipo R

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#895]
El HECEN/09852 tiene un F1 R del periodo de factura 15/04/20 Al 17/05/20 Y que está refacturando el periodo 14/03/20 al 17/05/20, no me sale el error ni el la compra ni en la venta, pero en cambio la venta FV/2020040062 salen valores de energía disparatados que nada tiene que ver con lo facturado hasta el momento.

\\NI\EsiosPre\F1\WAIT DANI\F1-ES0031103619684002AH0F_S1001Y00202044.xml

**Comment by JMunoz17** [comment]
Entiendo que el fichero F1 esta mal, vienen informados consumos calculados de 0001000248.00 y 0000999843.00, por eso sale un importe tan alto.
