### ISSUE TITLE
NAV - Implementan de facturas complementarias tipo C

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#896]
### PEDIR PRESUPUESTO ANTES D EJECUCIÓN DE TAREA
----------------------------------------------------------------------------

Se proporcionarán detalles por correo

**Comment by JMunoz17** [comment]
Por lo que hemos visto en la documentación estas facturas complementarias vienen únicamente con término de energía, aunque el F1 que nos habéis pasado también trae término de potencia, que imagino también hay que meterlo en la factura.

Por lo que veo cierres no vienen, entonces entiendo que tendremos medidas para facturar no? 

Por otro lado también hemos visto que en el F1 no viene informada la factura a la que complementa, la única forma que tendremos de relacionarlas es buscando por fechas, por lo que si por algún motivo no encontrásemos una factura tipo N del mismo contrato en esas fechas devolveríamos un error.

También hemos visto que no puede haber una Rectificadora sobre una Complementaria, pone esto:
_No se permite emitir una factura rectificadora sobre una complementaria emitida. En estos casos, se anulará la primera complementaria para posteriormente emitir otra factura complementaria corregida._
Entiendo que deberíamos, en caso de que venga una complementaria para unas fechas donde ya existe una factura de tipo C para ese contrato, hacer un abono de la que ya existía y crear la nueva complementaria, no?

Hay algo mas a tener en cuenta? Confirmarme lo de las medidas por favor.

**Comment by bpesquero** [comment]
Perdonad la demora

1.- La factura no puede tener alquiler de equipo de medida ni término de potencia, si el ejemplo lo tiene tendremos que reclamarlo
2.- Efectivamente no viene cierre, y mucho temo que es probable que no tengamos medida horaria. Para no hacer un proceso específico muy diferente en la parte de factura de venta, en estas facturas quizá deberíamos meter un "cierre inventado" sólo para la nagnitud AE  y deberíamos utilizar los valores facturados en el TE. Entiendo que si no hay horaria, que yo creo que no la va a haber, el algoritmo lo que haría sería perfilar este cierre inventado.
3..- No viene informada la factura  a la que regulariza, no te hace falta encontrar las anteriores, ya que en este caso no tienes que restar las medidas ya facturadas
4.-No se permite una rectificadora sobre una C, esto habría que controlarlo en la carga de las Rectificadoras (R)
5.- La factura de venta debería facturar la energía del "cierre inventado" perfilado, en caso de que hubiera medidas debería avisar de que existen medidas horarias para una factura C y es incompatible. ES por cazar alguna circusntancia que ahora se me pueda pasar.

**Comment by bpesquero** [comment]
Buenas, he estado revisando los tres ejemplos que tenemos y es compatible con lo indicado más arriba. Efectivamente el F1 tiene término de potencia pero viene a 0.
EL único error por mi parte, es el punto 5, incomprensiblemente si van acompañadas en muchas casos de medida horaria. En ese caso facturaremos la medida horaria y en caso contrario, como es habitual, perfilaremos el "cierre inventado"

**Comment by bpesquero** [comment]
Los ejemplos que tenemos son
En GAC:
La tienes generada y abierta en el COM/02286 y el COM/01408  

En HECEN
La tienes generada y abierta en el HECEN/09506

**Comment by JMunoz17** [comment]
Belén, he subido el desarrollo a producción (de la forma que esta hecho no debería afectar al resto de tipos de facturas).

Solo he podido probar con la factura del contrato HECEN/09506. Os he dejado la venta generada para que la reviséis:  FV/2020064573

Para GEO, de los dos contratos que me indicas la factura del COM/02286 ya la habíais registrado por lo que no puedo probar con ella y la del COM/01408 no localizo el fichero.

Tienes algún ejemplo para pasarme y poder probarlo?

En cualquier caso en el log seguirá saliendo un aviso de "Factura tipo C revisar", por lo que tendremos que ir afinando las posibles incidencias que surjan sobre la marcha.

**Comment by JMunoz17** [comment]
Quedo a la espera de que si me podéis pasar el fichero del COM/01408.

**Comment by bpesquero** [comment]
La factura del HECEN/09506 es correcta. La próxima vez dejala por favor en abierta, porque si tienen algún problema y está lanzada es muy fácil que se nos registre sin querer

La factura del COM/02286 no sé porque se facturó. Es incorrecta, Abría que abonarla y sacar la nueva. Podríamos problarla a través de forzar facturación?

Para el COM/01408 tienes la compra en NAV abierta, es la factura FC/201901163

**Comment by JMunoz17** [comment]
La del COM/02286 la hemos regenerado con el forzar facturación:
- Pre factura: FV/2020020549
- Pre abono: ABP/202000961

Revisad si son correctas.

La del COM/01408 es de autoconsumo, que hacemos con esto? En un principio autoconsumo lo limitamos a las tipo N, como hacemos con las tipo C? 
En caso de adaptarlo entiendo que seria ignorar todo lo que tenemos de autoconsumo, tanto todas las líneas que se añaden a la factura como no tener en cuenta ninguno de los controles no? Lo que nos digas..

**Comment by bpesquero** [comment]
Con respecto al COM/02286
- En P2 estamos facturando 30,155 en vez de 59,04 ¿por qué?
- No deberíamos incluir financiación del bono social ya que se factura por días y estos días ya fueron facturados previamente
- no deberíamos incluir comisión de gestión cuando esta es fija, es decir, cuando se factura según el nº de días, por la misma razón que el bono social.

La factura de HECEN/09506 era correcta porque en ese tipo de facturas no se dan estas circunstancias.

En cuanto al COM/01408 iba a revisarlo, pero no veo la factura que estaba abierta, ¿habéis hecho algo con ella?

Gracias

**Comment by JMunoz17** [comment]
Respecto al COM/02286:
- El problema era que nos faltaba un fix para las tipo C al buscar el número de factura acceso (al no tener cierres..). Por eso usaba las ultimas medidas que encontraba, cogiendo una parte (solo del periodo 2 en este caso) de las medidas asociadas a otra factura (una tipo G).  De esa forma usaba la última medida para cada día. Ya esta usando las medidas correctas.
- He quitado tanto la financiación del bono social como la comisión de gestión si va por días. Si hay otros conceptos que no haya que meter en las facturas de las tipo C me lo tenéis que decir que yo solo tenía constancia del alquiler del equipo de medida.
- Dime si ya esta ok la factura.

Para el COM/01408 es que no sé ni como la habíais cargado porque da error al ser de autoconsumo y ser tipo C. Imagino que la cargasteis antes de que ese contrato tuviese creado un contrato de autoconsumo con algoritmo de financiación diferente a F.
El fichero es: SCTDE_F1_01_0022_0587_20190913080156344_(799293570) (autoconsumo)
Quedo a la espera de que me digas que hacemos con estas de autoconsumo.. yo creo que seria ignorar todos los controles y todo el código de autoconsumo que inserta líneas en las facturas no? Porque al fin y al cabo las complementarias solo complementan el termino de energía activa ¿¿¿entrante???

**Comment by bpesquero** [comment]
el COM/01408 tiene ficha de autoconsumo, pero no está vigente en las fechas de la factura. El control debería tener en cuenta que exista un contrato de autoconsumo vigente en el periodo facturado, HAbría que cambiar el control

**Comment by JMunoz17** [comment]
Factura de venta generada para el COM/01408: FV/2020020554
En este caso no tiene medidas, por lo que se ha facturado con los cierres creados a partir del peaje.

**Comment by bpesquero** [comment]
Perfecto. Cierro tarea
