### ISSUE TITLE
NAV - Nuevos estados impagados

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#897]
Necesitamos crear 2 estados nuevos en la gestión de deuda

- Con monitorio interpuesto   
- Con reclamación judicial.

2 opciones.

1.- Añadir los 2 nuevos estados de deuda a los actuales. Entendemos que puede resultar complejo al tener que revisar las implicaciones con el resto de estados y acciones asociadas.

2.- Añadir 2 nuevas columnas separadas del resto de estados para evitar interaccionar con la lógica ya implementada

**Comment by JMunoz17** [comment]
Todo depende de si estos campos tienen que tener alguna funcionalidad o simplemente son a nivel informativo.

Si solo son a nivel informativo en hacer la opción 2 tardamos media hora. Sería mejor hacer la opción 1 porque cuantos menos campos creemos mejor, pero tal y como dices eso nos llevaría un buen rato en revisar toda la funcionalidad de la gestión de cobros y adaptarla a la inclusión de estos nuevos estados.

**Comment by bpesquero** [comment]
Decidimos realizar la primera opción, son sólo campos informativos. Idealmente ambos campos serán tipo fecha. 
ESta previsto trasladar el módulo de impagados a Geo y además gestionar los correos por signaturit,. Quizá ese sea el momento de darle una vuelta a lo que sea necesario.

**Comment by JMunoz17** [comment]
Hemos creado los campos de tipo fecha en mov. cliente y mostrado en la pantalla de gestión de impagos.
Subido a PRE y PROD.
