### ISSUE TITLE
WEB - Error al contratar una 30A

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#899]
Al contratar una 30A un cliente ha introducido una potencia de 17250 en lugar de 17,250

El proceso  termina correctamente

![image](https://user-images.githubusercontent.com/47117960/86814519-d1b78180-c081-11ea-80c5-5bba2874607e.png)

Pero el email que llega es el siguiente y en NAV no se rellena potencia. 

Ha sucedido un error al intentar crear el contrato, por favor ponte en contacto con nosotros a través del formulario de contacto o en el teléfono 900 264 267.

Aunque claramente se trata de un malentendido en las potencias introducidas no debería haber fallado. 
¿Tenemos algún control en NAV o en la web que impida este alta?

**Comment by jorgereal** [comment]
Se creó un control en NAV, relacionado con la tarea #881, por el que no se pueden crear contratos con potencia > 450 kW si el algoritmo no es de Oracle.

Este es el error que se produjo al intentar crear el contrato por WS.

¿Añadimos un control en la web?

**Comment by dgarciageo** [comment]
Buenas Jaime, el control en Nav está perfecto entonces. Lo único que habría que poner un control en la web para que en lugar de que le llegue un error, que le llegue un email diciendo al cliente que se ponga en contacto con nosotros para darle una oferta personalizada. Nos puedes por favor estimar las horas que llevaría implementar este control?  Habría que implementarlo en ambas webs. Si es mucho lo dejamos para implementarlo en el nuevo API.

**Comment by jorgereal** [comment]
Buenas Dani, no sería mejor opción meter un control por javascript en los textbox de potencia, al igual que los que ya existen, para controlar que no introduzcan un valor demasiado alto.
En ese caso podríamos mostrar un mensaje de que el valor no es correcto y que si desean contratar esa potencia se pongan en contacto con vosotros.

Habría que añadir el control al crear un contrato desde el área pública, desde el área privada y en los cambios de potencia.
Hacer esto en ambas webs serían unas 3 horas en total.

**Comment by dgarciageo** [comment]
Buenas Jorge, mucho mejor con el javascript tal y como sugieres. Entiendo 3h GAC y HECEN? 
Si es así perfecto, adelante
Muchas gracias

**Comment by jorgereal** [comment]
Si, 1.5h en cada una. Nos ponemos con ello

**Comment by jorgereal** [comment]
Hemos añadido el control de que el máximo de las potencias para una 3.0A deba ser <=450kW en el alta de contratos desde el área pública, privada, cambio de tarifa y cambio de potencia.
El resto de tarifas ya tenían controles para comprobar el mínimo y el máximo.

Subido a los dos webs.

**Comment by dgarciageo** [comment]
Hay un problema con el javascript que valida el CP

![image](https://user-images.githubusercontent.com/47117960/93866172-9bc08b80-fcc7-11ea-89fb-be3f1676a863.png)

**Comment by jorgereal** [comment]
Hemos corregido el bug en el javascript y lo hemos subido a producción.
Es probable que tengáis que limpiar la caché o acceder desde una ventana de incógnito para ver los cambios.

Subido a PRO.

**Comment by dgarciageo** [comment]
Probado y ok
