### ISSUE TITLE
NAV-GAC-COM/00754 factura G

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#903]
Al facturar la venta de una factura G correspondiente al contrato COM/00754, además de que tarda más de una hora en ejecutarse la venta, acaba dando error

El índice 0 de la matriz queda fuera del rango permisible.

**Comment by JMunoz17** [comment]
Este problema ya lo tuvimos en su día ( tarea #591). Es porque esta factura G engloba muchísimas facturas y el arrray permitía 20 como máximo. Hemos aumentado el tamaño de los arrays a 50.

Factura generada:
FV/2020012423

Revisad la factura, este el log:
![image](https://user-images.githubusercontent.com/26869276/86916565-1136aa00-c124-11ea-9af5-79048e0ca2e3.png)
