### ISSUE TITLE
NAV - Error impresión roles con alias de gmail

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#904]
Tenemos un problema a imprimir facturas cuando la dirección de correo electrónica es un [alias ](https://www.digital-nature.com/como-crear-infinitas-cuentas-de-correo-con-gmail#:~:text=Pues%20bien%2C%20solo%20tienes%20que,generar%20tantos%20alias%20como%20necesites) de gmail en el cual se concatenan el email, un signo +, y el alias que sea.

![image](https://user-images.githubusercontent.com/47117960/86904958-b5632580-c111-11ea-9409-5b0eed3f5962.png)

![image](https://user-images.githubusercontent.com/47117960/86904777-77fe9800-c111-11ea-8314-174786a6ace1.png)

Necesitamos, que a la hora de imprimir, NAV coja sólo la raiz del email, para evitar el error C/AL

**Comment by JMunoz17** [comment]
Subido a PRE y PROD.

Soluciona el problema solo con el siguiente formato de mail: pepeperez+atulado@gmail.com -> pepeperez@gmail.com

**Comment by bpesquero** [comment]
Las facturas nuevas registradas en GAC no han arrastrado el alias a la tabla de documentos de pago.
En HECEN no lo he podido comprobar
