### ISSUE TITLE
WEB Atulado - URGENTE. CORREOS CAMBIO CONTRASEÑA

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#908]
Los correo de cambio de contraseña de A Tu Lado, no se están enviando. ¿Podéis echarle un ojo? Gracias. 

![image](https://user-images.githubusercontent.com/47117960/87449372-6a5b7d80-c5fd-11ea-8484-aef3630686c7.png)

**Comment by jorgereal** [comment]
Dani, ¿nos puedes decir con qué correo está fallando? 
El email tan solo se envía si el usuario está creado en el mysql y está activado.

**Comment by bpesquero** [comment]
EL correo que fallaba era 
carmelaforestal04@gmail.com

Cuando dices que está activado, te refieres el contrato, no, verdad?

**Comment by jorgereal** [comment]
Me refería a que hayan activado el usuario web con el email de activación que les llega al darse de alta.

He comprobado ese correo y existe en mysql y está activado, pero la fecha de activación es el 16-07-2020 y esta incidencia se abrió el día 14-07-2020, por lo que el usuario no estaba activado cuando trató de recuperar su contraseña.

Este es el motivo por el que no se envió el email.

Si vuelve a intentarlo debería recibir el correo sin problemas.

**Comment by bpesquero** [comment]
ok. Cierro la incidencia
