### ISSUE TITLE
NAV - Problema al mover A5Ds y B5Ds a la carpeta procesados

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#911]
en lugar de mover a la carpeta de procesados correspondiente 

\\NI\Esios\B5DCCH Geo\Procesados o  \\NI\Esios\A5DCCH Geo\Procesados 

se renombran como en  la imagen:

![image](https://user-images.githubusercontent.com/47117960/87564514-c9ce9180-c6c0-11ea-9937-837598ee1cb7.png)

**Comment by JMunoz17** [comment]
Tenías mal configurada la ruta en la configuración, tiene que tener la \ al final, te lo he cambiado el GEOATLANTER, ya se tienen que mover bien los ficheros al procesarlos.
