### ISSUE TITLE
WEB - Error comision Próxima

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#913]
Nos  informa un cliente que al dar de alta un contrato por la web aparece como cargo de gestión 0,5c€/kWh, cuando debería ser 2€ al mes fijos porque ha contratado una potencia de 4,6kW. 

![image](https://user-images.githubusercontent.com/47117960/87921649-2ba14980-ca7b-11ea-9282-74e8274c36d9.png)

**Comment by jorgereal** [comment]
Buenas Dani,

Actualmente existe el siguiente control:

Si se quiere dar de alta un hogar si comprueba si
- alguna de las potencias supera los 10 kW y factura electronica = Si -> 0,5 c€/KWh
- alguna de las potencias supera los 10 kW y factura electronica = No -> 1,1250 c€/KWh
- ninguna potencia supera los 10 kW y factura electronica = Si -> 2 €/Mes
- ninguna potencia supera los 10 kW y factura electronica = No -> 4,5 €/Mes

Si se quiere dar de alta un negocio se comprueba si
- factura electronica = Si -> 0,5 c€/KWh
- factura electronica = No -> 1,1250 c€/KWh

Entiendo que en el caso que comentas se trataba de dar de alta un negocio con el check de factura electrónica marcado a Si, por eso aparecían los 0,5 c€/KWh.

¿Debe funcionar de la misma manera tanto para el alta de hogares como negocios?

**Comment by bpesquero** [comment]
Esto no es así, Esto ya se cambio hace meses para no distinguir en las
comisiones entre negocio y persona física. Lo estuvimos viendo con Eric,
habla por favor con él

**Comment by dgarciageo** [comment]
Buenas Jorge,

Efectivamente no tenemos que hacer distinción entre hogar y empresa. Sólo por potencia
Recuerdo que estuvimos haciendo pruebas y parecía estar resuelto.
¿Es posible que hayamos perdido algún cambio?

Muchas gracias
Dani

**Comment by jorgereal** [comment]
Respondido por email.

Subido a PROD.

**Comment by bpesquero** [comment]
Habéis revisado si hay algún contrato al que se le haya asignado mal la comisión por este motivo? Podéis mirarlo?

**Comment by jorgereal** [comment]
El error estaba solo en el javascript, que se encargaba de mostrar los datos de resumen al finalizar el alta.
La comisión real asignada al contrato se calcula en NAV y de ahí no se ha tocado nada.

Hemos revisado los contratos creados desde que se ocasionó el problema y las comisiones son correctas.

**Comment by bpesquero** [comment]
Perfecto. Gracias. Cierro entonces la incidencia
