### ISSUE TITLE
NAV - Problema al cargar medidas GEO

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#915]
Estoy recibiendo este error pero salvo error mío no aplica

Error Medidas, el fichero F5D_0021_0587_20200713.0 pertenece a GEO y se esta intentando cargar en HECEN

![image](https://user-images.githubusercontent.com/47117960/88080898-faf70800-cb7f-11ea-8510-e17aee8215d2.png)

**Comment by JMunoz17** [comment]
Dani, confirmame esto por favor:
 F5D_0021_0587_20200713.0 -> 0587 es el identificador de que el fichero es de GEO no? Como el identificador de HECEN es 0713 y  también aparece en el nombre del fichero por eso da el error.

Te pregunto a ti que estarás mas familiarizado con el nombre de los ficheros, puedo buscar por 0587 con barra baja delante y detrás en lugar de solo 0587, así evitaríamos este error. Por cierto, me lo parece a mi o  en el mensaje de error que devuelve NAV los nombres de las empresas están al revés? Lo cambio también.

**Comment by bpesquero** [comment]
El código que indicas es el que se refiere a la empresa que recepciona el fichero. por tanto puedes poner ahí un control. En cualquier caso entiendo que luego hacemos un control de qeu tenemos dado de alta ese Cups, no?

Lo que no termino de entender es si el fichero tiene 0587 (Geo) y se está cargando en Geo ¿por qué da error? ¿y por qué dice que se está intentado cargar en HECEN?
No entiendo

**Comment by JMunoz17** [comment]
Porque el control lo que hace es comprobar si ese 0587 (Geo) o 0713 (Hecen) aparece en el nombre del fichero, independientemente de la posición. En el caso de F5D_0021_**0587**_2020**0713**.0 aparecen ambos, de ahí que de error.

Mi pregunta era si para controlarlo puedo utilizar _ 0587 _ y _ 0713 _,  así controlamos casos como este.
Otra opción sería buscando justo del décimo al decimotercer carácter del nombre del fichero.
Te pregunto porque aunque imagino que la estructura del nombre del fichero es siempre así no tengo la certeza de ello, por si me lo podéis confirmar.

Si no entiendes a lo que me refiero dame un toque y lo vemos en un minuto porque soy consciente de que puede ser que me este explicando como el culo pero realmente es muy sencillo.

**Comment by JMunoz17** [comment]
Modificado el control para controlar este caso, subido a PRE y PROD.
Lo hemos probado en PRE, por lo que el fichero que os daba fallo tenéis que importarlo en PROD.
