### ISSUE TITLE
NAV - GAC - Error carga F1 con calendario

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#917]
Al cargar el F1
Error XML,el calendario de Medidas del contrato COM/00003 es 6p y el numero de medidas es 12.

Lo unico que ocurre es que el cierre está en dos tramos. Esto nos está pasando en varias ocasiones y yo creo que estaba solucionado para todas las magnitudes. Adjunto ficheros por email

**Comment by JMunoz17** [comment]
Ya esta solucionado, factura generada: FC/2020013811

En el mail me pasabas tres ficheros:
20200604021812-GRCW_0021_0587_F1_01_90 -> El que hemos importado.
20200604103312-GRCW_0021_0587_F1_01_98 -> Este es idéntico al anterior, solo cambia el nombre del fichero.
20200619022010-F1_202023723729_17442402 -> Este es de la otra tarea.

Te dejo aquí el log tras generar la factura:
![image](https://user-images.githubusercontent.com/26869276/88262895-5a146400-ccc9-11ea-86b2-86ff0243e340.png)

La última línea es por lo que te comento del segundo fichero.

**Comment by bpesquero** [comment]
Pero no entiendo Jaime, sigue dando error en el log?

**Comment by JMunoz17** [comment]
No, son los avisos de que no coinciden las fechas desde o hasta del término de energía (viene en un tramo) con las del cierre, simplemente porque este viene en dos tramos. La factura se genera y eso no es un problema, simplemente te copio el log para que vieses la ultima línea porque me has pasado dos ficheros iguales pero con distinto nombre.

**Comment by bpesquero** [comment]
Buenos días tengo un fichero con el cierre en dos tramos que sigue dando problema. Lo envío por email

**Comment by JMunoz17** [comment]
Hemos adaptado los controles de fechas para Término Energía Activa, Potencia Máxima, Exceso de Potencia y Reactiva en caso de que los cierres vengan con varios tramos.

Para el fichero que pasaste por mail (20200704022010-F1_202024081883_17532423) se ha generado la factura: FC/2020014502 del COM/02848
