### ISSUE TITLE
web - usuario  titular

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#92]
Tenemos un contrato en Geo que tiene diferente titular y pagador. Hemos creado los dos usuarios en la web. Con el usuario pagador ningún problema, pero con el usuario titular no consigo entrar, se queda pensando y pensando y no entra nunca. Lo hemos estado probando en diferentes equipos y con diferentes navegadores. Con otros usuarios si entramos, pero con ese no.
El usuario es lostesorosdelbebe@gmail.com

**Comment by PKFEric** [comment]
El usuario no tenia dirección de envío en NAV. Por eso no accedía. He creado la direccion de Envio por defecto. Y ya se puede acceder.

**Comment by PKFEric** [comment]
PROBADO-> Puedes probarlo con el usuario de ainhoa, le he borrado la dirección de envío y accede perfectamente.

**Comment by bpesquero** [comment]
Probado y ok
