### ISSUE TITLE
NAV - URGENTE: Problema en el registro de abonos

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#924]
Tengo un montón de abonos de compra que no puedo registrar por dos motivos distintos:
En total tengo 29 abonos que no puedo registrar!!! Y necesito hacerlo cuanto antes por el tema de reclamación de deuda 
 
Unos por el siguiente error:
Ejemplo : ABC/20190006 Esto es simplemente que hay una de las líneas que no tiene informado el CC pero no soy capaz de verlo!!! Debo ser tonta pero no lo veo y no se como lo puedo ver
 
 
![image](https://user-images.githubusercontent.com/47117960/90242684-c0565780-de2d-11ea-95d1-7321153a2005.png)

Y otros por este otro error:
Ejemplo: FC/2020005500. Estos son los de abono de calidad de suministro 

![image](https://user-images.githubusercontent.com/47117960/90242689-c3e9de80-de2d-11ea-8744-0334e6d49d2f.png)

**Comment by jorgereal** [comment]
Hemos corregido y registrado todos los abonos de compra con estado lanzado.

Estamos buscando el error en la carga de los F1 para que no se repita en el futuro.

**Comment by jorgereal** [comment]
Se han corregido también los errores en la importación de los F1 para que los abonos de compra se generen correctamente.

Subido a PRE y PRO.
