### ISSUE TITLE
NAv-GEO- Información facturas de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#925]
En las facturas de autonconsumo tipo NF la línea de descuento debe mostrar entre paréntesis, como es habitual la cantidad expresada en kWh y el precio en €/kWh)
Repasar si en las facturas SF, SC y NC aparece esta información

**Comment by jorgereal** [comment]
Se ha añadido a la línea de descuento el detalle de kWh y precio en  €/kWh, para todos los formatos de autoconsumo.

Subido a PRE.

**Comment by bpesquero** [comment]
Perfecto, lo único es que en vez de dos paréntesis pondría solo uno, es decir

en vez de 
![image](https://user-images.githubusercontent.com/20299071/92516179-1d6ae080-f215-11ea-9e0a-334b7724a11f.png)

pondría 
(compensación de excedentes / -863, 770 kWh x 0,032588 €/kWh)

**Comment by jorgereal** [comment]
Modificados los formatos y subidos a PRE. 
Hemos generado de nuevo los ejemplos C_20200016557_new.pdf y C_20200016558_new.pdf.

**Comment by bpesquero** [comment]
Perfecto. Subid a PRO

**Comment by jorgereal** [comment]
Subido a PRO.
