### ISSUE TITLE
NAV- GAC - Información de cierre en factura

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#926]
En las facturas, en la tabla que aparece en la primera hoja con la información de cierres la energía a mostrar debería ser la energía facturada no la energía del cierre. Esto cobra importancia en las facturas de autoconusmo en que no coinciden ambos valores.

**Comment by jorgereal** [comment]
Hemos modificado los formatos de venta de factura, de abono y de facturas de autoconsumo tipo NC para que en la columna de la energía consumida obtenga el dato de la energía facturada (cantidad en la línea de factura) en lugar de la información del cierre.

Esto aplica a las líneas de energía activa y reactiva, ¿en el caso de las líneas de energía saliente también debemos cambiar el dato? Si es así, ¿de donde debemos obtenerlo?

Subido a PRE.

**Comment by bpesquero** [comment]
¿por qué sólo se ha hecho en las NC?
ESto habría que hacerlo en todas las facturas, de autoconsumo o no.
La energía saliente habría que poner efectivamente la factura facturada, lo ideal sería coger el dato de la curva de carga, y en caso contrario de la propia factura, pero en cada algoritmo ese dato aparece en un sitio diferente.

**Comment by bpesquero** [comment]
ok. Ya he entendido que está hecho para todas las facturas y abonos de venta y las de compra de las NC, verdad

**Comment by jorgereal** [comment]
Sí, está hecho para todos los formatos de venta, incluyendo el de venta/compra de las NC.

Hemos añadido el cambio para mostrar la energía saliente facturada, obteniendo los datos de la tabla pool energy prices al igual que en el proceso de facturación, desglosando por periodo.

Subido a PRE.

**Comment by bpesquero** [comment]
No sé como probar esto en PRE. ¿Podríamos sacar el pdf de alguans de las facturas que tenemos en PROD?

Gracias

**Comment by jorgereal** [comment]
Hemos generado los pdf para las facturas C/20200016558 y C/20200016557. Están en la carpeta de facturas de geo pero añadiendo un "_new", para poder compararlas con los anteriores formatos.

En ellos también se pueden ver los cambios relacionados con la tarea #925

**Comment by bpesquero** [comment]
Viendo ahora, creo que lo mejor sería quitar de la tabla las lectuas y dejar sólo las columnas de consumo, fecha desde y fecha hasta y la información que aparece al pie

![image](https://user-images.githubusercontent.com/20299071/92516085-f2808c80-f214-11ea-961d-ad35f046bc8c.png)

**Comment by jorgereal** [comment]
Modificados los formatos y subidos a PRE. 
Hemos generado de nuevo los ejemplos C_20200016557_new.pdf y C_20200016558_new.pdf.

**Comment by bpesquero** [comment]
Perfecto.Subid a PRO

**Comment by jorgereal** [comment]
Subido a PRO.
