### ISSUE TITLE
NAV- GAC- FActuración NC FCR/20200011528 - COM/01462

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#927]
La factura de referencia se trata de una NF en la que en la parte del descuento por los excedentes no se han facturado todos los excendentes.
La energía saliente es 919 y se ha facturado 12,896

Localizado el error habría que revisar qué ha pasado con el resto de las NF

**Comment by jorgereal** [comment]
Hemos encontrado un error en el cálculo de la energía excedentaria relacionado con la tarea #880 
Solo ha afectado a las facturas de autoconsumo con algoritmo NF con fecha de registro posterior al 09/06/20.

Hemos corregido el código y lo hemos subido a PRE y PRO.

Las facturas afectadas son:

C/20200009429
C/20200009642
C/20200009785
C/20200010573
C/20200010960
C/20200012395
C/20200012520
C/20200015003
C/20200015140
C/20200015254

Por otro lado, tenemos estas cuatro facturas que tienen algoritmo NF pero no tienen energía excentaria asociada por lo que en teoría están bien. Nos ha parecido un poco raro, ¿tiene sentido que estas no tengan energía excedentaria? Son todas del contrato COM/01462, que en la factura de mayo si que tiene energía excedentaria.

C/20200009427
C/20200010593
C/20200010594
C/20200011580

Podemos reutilizar el proceso que hicimos el otro día para generar los abonos que corrijan estas facturas y se generen las nuevas con los importes correctos, ¿Lo hacemos?

**Comment by bpesquero** [comment]
Ok. Hagamos los abonos y las nuevas facturas. En este punto pasadme por favor el listado de abonos y nuevas facturas antes de registrar.
Cuando las revise registramos y en este caso los abonos habrá que liquidaros contra las nuevas facturas, ya que las facturas ya están cobradas excepto tres que tenía previsto pasar en el día de hoy.

**Comment by jorgereal** [comment]
Hemos generado los 10 abonos con sus 10 facturas corregidas.

La relación de documentos es la siguiente:

Factura original | Abono correctivo | Nueva factura
C/20200009429 | ABP/202000934 | FV/2020017450
C/20200009642 | ABP/202000935 | FV/2020017451
C/20200009785 | ABP/202000936 | FV/2020017452
C/20200010573 | ABP/202000937 | FV/2020017453
C/20200010960 | ABP/202000938 | FV/2020017454
C/20200012395 | ABP/202000939 | FV/2020017455
C/20200012520 | ABP/202000940 | FV/2020017456
C/20200015003 | ABP/202000941 | FV/2020017457
C/20200015140 | ABP/202000942 | FV/2020017458
C/20200015254 | ABP/202000943 | FV/2020017459

Tantos los abonos como las nuevas facturas se encuentran sin registrar.

Se deben registrar primero las facturas nuevas, en ese momento se rellenará automáticamente la información en los abonos para que se liquiden contra estas facturas. (Revisar antes de registrar los abonos en las pestaña liquidación que ha viajado bien el campo liquidar por Nº documento).

**Comment by bpesquero** [comment]
He tenido que ir cambiando en la pestaña de liquidación de los abonos y cambiar de factura a efecto y seleccionar el correspondiente. YA está todo ok.
