### ISSUE TITLE
NAV- HECEN- Cambio de contrato

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#928]
![image](https://user-images.githubusercontent.com/20299071/90607945-3974f680-e202-11ea-9308-9363b4fc81cc.png)

Este contrato, tenía una tarifa 59 (nocturna) y a fecha 29/7 solicitó el cambio de tarifa a MILENIAL . Firmó el contrato en Signaturit, tal y como puedes ver adjunto, pero en NAV no se le actualizó la tarifa ni los precios. El cliente ha llamado porque le hemos pasado la factura con precio nocturna.  Esto estaba funcionando, así que no sé qué ha podido ocurrir.

 

Por el momento se la he cambiado a mano a la 96 (MILENIAL) y he actualizado precios desde el 10/8 (última fecha de consumo facturada).

**Comment by jorgereal** [comment]
Existía un error en la web de a tu lado de cuando se hizo el cambio de nombres en las tarifas (#857 ).
Se ha corregido y se ha subido la web.

Hemos comprobado si existen más contratos que solicitaran un cambio de tarifa desde la subida del desarrollo y hemos encontrado los siguientes:

HECEN/11291 -> NOCTURNA 
HECEN/11284 -> NOCTURNA 
HECEN/12093 -> 3.0A
HECEN/11223 -> 3.0A
HECEN/11631 -> NOCTURNA 
HECEN/08737 -> MILENIAL

Para los contratos HECEN/12093 y HECEN/11223 no afectaría puesto que al cambiar el peaje se genera un M1 y un contrato nuevo tras la aceptación.

¿Cambiamos la tarifa a mano y actualizamos los precios para los otros 4 contratos como se hizo con el contrato HECEN/12149?

**Comment by bpesquero** [comment]
Lo hemos revisado nosotros y hemos actualizado lo que correspondía.
Cierro incidencia
