### ISSUE TITLE
NAV-GAC- Error discontinuidad de fechas F1

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#929]
MEDIDA   SUBIDA_GRCW_I-DE ES0021000015847643HL_AVISO DE NO TELEGESTIONADO.xml | COM/00199 | ES0021000015847643HL | Error XML, existe una   discontinuidad de fechas en el TE para el periodo 3
-- | -- | -- | --

Viendo el fichero no se aprecia ningún tipo de discontinuidad.

se envía fichero F1 por email

**Comment by jorgereal** [comment]
El problema se debe a que en los dos F1 del contrato COM/00199 importados previamente al fichero que avisa de la discontinuidad uno de los 3 periodos venía a 0.

En la importación de los F1 si alguno de los periodos viene a 0, este no se importa y se reordenan los siguientes, quedando en este caso el periodo 3 sin término de energía.

Aunque el fichero MEDIDA SUBIDA_GRCW_I-DE ES0021000015847643HL_AVISO DE NO TELEGESTIONADO.xml es correcto, tiene informados los 3 periodos y las fechas están bien, la importación avisa de que existe una discontinuidad de fechas para ese contrato en el término de energía para el periodo 3, porque los dos F1 anteriores, correspondientes a las fechas (01/04/2020 - 30/04/2020) y (01/05/2020 - 31/05/2020), no lo tenían informado, .
