### ISSUE TITLE
NAV-GAC- Error F1 faltan medidas horarias para factura tipo A

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#930]
MEDIDA   SUBIDA_F1_01_ES0264121300920006WE0F.xml |   |   | Error XML, el peaje tiene fecha   desde CCH y fecha hasta CCH pero no tiene medidas F5D cargadas.
-- | -- | -- | --

REalmente se trata de una factura tipo A por tanto no necesita medidas horarias

Adjunto fichero por email

**Comment by jorgereal** [comment]
Se ha añadido un salto para los documentos tipo A en los controles de la discontinuidad de fechas para término de energía y término de potencia (daba el aviso si el documento abonaba una factura que no fuese la última) y el control de que existan medidas F5D.

Subido a PRE y PRO.

El fichero MEDIDA SUBIDA_F1_01_ES0264121300920006WE0F.xml se ha cargado correctamente.
