### ISSUE TITLE
NAV- GAC-HECEN-Alias en documentos a pagar

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#931]
Sería muy util desde doc cartera a pagar y desde doc cartera (cuando insertas doc desde remesa de pagos) mostrar el alias del proveedor.

**Comment by jorgereal** [comment]
Subido a PRE y PRO

**Comment by bpesquero** [comment]
He visto que el campo, sin embargo no se puede filtrar por él, que es lo que realmente se necesitaba.

**Comment by jorgereal** [comment]
Hemos creado el campo físico en la tabla de documentos cartera para que se pueda filtrar por él.

Se ha añadido el código necesario para que se rellene automáticamente a partir de ahora y se ha pasado un proceso para que se rellene en los registros ya existentes.

Subido a PRE y PRO.

**Comment by bpesquero** [comment]
Comprabado y ok

**Comment by bpesquero** [comment]
EL proceso parece que se ha pasado sólo en GAC y no en HECEN.

**Comment by jorgereal** [comment]
Pasado también en HECEN.

**Comment by bpesquero** [comment]
Las facturas nuevas registradas en GAC no han arrastrado el alias a la tabla de documentos de pago.
En HECEN no lo he podido comprobar

**Comment by jorgereal** [comment]
Existía un error por el que en algunos documentos no se estaba rellenando el alias. Lo hemos corregido y hemos vuelto a pasar el proceso para rellenarlo en los que lo tenían vacío, tanto en GEO como en HECEN.

Subido a PRE y PRO.
