### ISSUE TITLE
NAV-GAC- Factura tipo G con error

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#933]
Error   XML, existe una discontinuidad de fechas en el TE para el periodo 1
--

Adjunto fichero por email, yo no le veo ningun problema

**Comment by jorgereal** [comment]
Al tratar de importar el fichero no nos da error de discontinuidad de fechas, nos muestra el siguiente error:

0023_0587_F1_01_S7001N11857741_ES0031104105067001PX0F_FALTA F5D.xml
Error XML, la fecha de medida inicial del F5D 09/07/20 es diferente de la fecha desde CCH 09/05/20 del peaje

A pesar de existir medidas F5D para todo el rango de fechas CCH (08/05/2020- 07/08/2020) solo las de a partir del 09/07/20 tienen el codigo fiscal factura del xml.

¿Es correcta la fecha desde CCH del xml? ¿No debería ser como la FechaDesdeFactura (08/07/2020)?

**Comment by bpesquero** [comment]
La fecha desde CCH debe coincidir con la fecha desde del TE, así que es correcto.
Las medidas que hay para el intervalo 8/05 a 9/07 a qué factura están asociadas?

**Comment by jorgereal** [comment]
Las medidas del 8/05 al 07/06/20 están asociadas a la factura S7001N10417913 y las del 08/06 al 08/07/20 a la factura S7001N11138089.

**Comment by bpesquero** [comment]
Ok. En ese caso hay que reclamar la factura. Me encargo


*Belén Pesquero Fernándezbpesquero@geoatlanter.com
<bpesquero@geoatlanter.com>*
Av. de Europa, 34B Esc. Dcha. 3º 28023, Madrid
 *917 378 443*
 *647 533 013*
<http://www.geoatlanter.com/>


*Síguenos en:*[image: Facebook pequeño]
<https://www.facebook.com/proximaenergia/>[image: Twitter pequeño]
<https://twitter.com/proximaenergia?lang=es>[image: Google+pequeñito]
<https://plus.google.com/114547235710296874519>

*AVISO DE CONFIDENCIALIDAD*: Este mensaje y sus archivos van dirigidos
exclusivamente a su destinatario, pudiendo contener información
*confidencial *sometida a secreto profesional. No está permitida su
reproducción o distribución sin la autorización expresa de *GEOATLANTER SL.*

Si usted no es el destinatario final por favor elimínelo e infórmenos por
esta vía.



De acuerdo con lo establecido por el Reglamento General de Protección de
Datos (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de
2016, le informamos que sus datos serán tratados con la finalidad de
realizar la gestión administrativa, contable y fiscal, así como el envío de
comunicaciones comerciales  sobre nuestros servicios y/o productos.


Asimismo, le informamos de la posibilidad de ejercer los derechos de
acceso, rectificación, oposición, supresión, limitación y portabilidad de
sus datos en el domicilio de *GEOATLANTER SL *sito en: Avda de Europa 34B
<https://maps.google.com/?q=Avda+de+Europa+34B&entry=gmail&source=g>, Esc.
Dcha 3º,  28023 Madrid o enviando un correo electrónico a la siguiente
dirección : *contacto@geoatlanter.com <contacto@geoatlanter.com>*

Si usted no desea recibir nuestra información, póngase en contacto con
nosotros enviando un correo electrónico a la dirección:
*contacto@geoatlanter.com <contacto@geoatlanter.com>*
