### ISSUE TITLE
NAV-HECEN-Contrato duplicado

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#934]
Buenos días, el cliente realizó la contratación dos veces para el mismo punto.
 HECEN/11763
HECEN/12065

la activación se produjo sobre el primero, sin embargo las facturas de peaje (ya registradas) se han asociado al segundo. 
Habría que unificar ambos. Quizá lo más sencillo es pasasr los movimientos OCSUM de histórico de acciones al segundo contrato y ponerle fecha de activación

**Comment by jorgereal** [comment]
Hemos dado de baja el primer contrato y activado el segundo.
Los movimientos de OCSUM del contrato HECEN/11763 se han asociado al contrato HECEN/12065.
Se han generado precios y potencias para el contrato HECEN/12065.

Se ha mantenido el titular del HECEN/12065 a pesar de diferir del de HECEN/11763.
