### ISSUE TITLE
NAV-GAC-FActuración de autoconsumo

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#935]
Al comparar los excedentes del F1 con las medidas del F5D hay que redondear a 0 decimales

Error   XML, excedentes del F1: 909 no coincide con la ES de las medidas F5D: 908,882   para el contrato: COM/01185 y Nº factura acceso: J420009166575.
--

Tenemos 6 facturas en esta situación. Las envío por email

**Comment by jorgereal** [comment]
Se ha modificado el control para permitir diferencias de +-1. con el redondeo a la unidad no era suficiente para el caso del fichero "0022_0587_F1_01_J420009169479_ES0022000007974749XS1P_AUTOCONSUMO.xml -> Error XML, excedentes del F1: 480 no coincide con la ES de las medidas F5D: 479,316. 

Subido a PRE y PRO.

Se han cargado los 6 ficheros.
