### ISSUE TITLE
NAV-GAC-No carga fichero F1

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#936]
TEngo un fichero que no carga pero no da ningún error en el log.
Envío fichero por email

**Comment by jorgereal** [comment]
El motivo por el que el fichero no se detectaba para importar se debía a la longitud del nombre de éste.
El máximo de caracteres que debe tener el nombre del fichero (incluyendo extensión) es de 99.

Ahora el log registra el siguiente error:
Error XML, la fecha de medida inicial del F5D 01/06/20 es diferente de la fecha desde CCH 30/01/20 del peaje.

Hemos dejado el fichero con el nombre acortado en
\\NI\Esios\F1\Pendientes de facturar\incidencia Attest\#936 NAV-GAC-No carga fichero F1

**Comment by bpesquero** [comment]
Doy por cerrado el tema. el error actual se gestiona por otra parte
