### ISSUE TITLE
NAV-HECEN- Problema el cambiar prefactura de venta

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#937]
Tengo una serie de facturas a las que hay que incluir un concepto y cuando trato  de insertar la línea, al meter el precio de venta me da el error "FEcha no valida"

Son las facturas abiertas de los contratos 

HECEN/12047
HECEN/12056
HECEN/12182
HECEN/12234
HECEN/12340

En todas ellas hay que meter una línea de derechos de enganche de 9,04€

**Comment by jorgereal** [comment]
La factura correspondiente al contrato HECEN/12340 no está en prefacturas, estaba ya registrada.

Al resto se les ha añadido la línea de derechos de enganche de 9,04€
