### ISSUE TITLE
WEB/NAV - PROBLEMA URGENTE - Activación del usuario web en procesos M1 de cambio de titularidad

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#939]
Los cambios de titularidad se realizan de forma manual, teniendo Ainhoa que realizar los siguientes pasos:

- Crear cliente NAV a mano
- Crear usuario web a mano (asociándose el cod cliente NAV)
- Activar usuario web a mano (y se le envía email de credenciales)
- Genera el M1 tipo S y sigue el proceso de switching

El problema es que el usuario web se activa antes de que tenga un contrato asociado (Cuando se proceso el paso M1_05 es cuando se asocia el contrato al nuevo titular)

Hemos detecto un problema grave y es que cuando un usuario web que no tiene un contrato asociado accede al portal puede ver todas las facturas en estado pendiente de todos los clientes.

La solución es no activar el usuario web hasta que no se asocie el contrato al nuevo titular, pero es necesario implementar en NAV que se active el usuario web de manera automática cuando se importe un paso M1_02 tipo S (sólo administrativo) o M1_05 tipo A (que es técnico  y administrativo) y se le envíe el email de credenciales.

**Comment by jorgereal** [comment]
Buenas Dani,

Existe una forma mucho más rápida de solucionar este problema y se trata de cambiar el filtro que se utiliza para mostrar facturas/abonos de la web, para que en caso de no tener ningún contrato asociado no se muestre ningún documento.
Esto nos llevaría un par de horas.

En cambio, lo que nos pides es mucho más extenso, puesto que no está desarrollada la conexión a mysql desde NAV para activar el usuario, ni el formato del mail de credenciales...

Con lo que te proponemos al principio solucionamos el problema, vamos a ir haciéndolo para subsanar el error lo antes posible.
¿Queréis una estimación de tiempo de lo que nos pides?

**Comment by dgarciageo** [comment]
Buenas Jorge, mucho mejor tal y como tu lo propones. Si son aprox 2h adelante.
Muchas gracias!

**Comment by jorgereal** [comment]
Se han corregido los filtros en el listado de facturas para no mostrar ninguna en caso de que el cliente no tenga ningún contrato asociado.

Este error solo afectaba a la web de a tu lado, lo hemos revisado en la de próxima y ahí estaba correcto.

Subido a PRO.

**Comment by dgarciageo** [comment]
Perfecto Jorge, el problema de las facturas ha desaparecido
![image](https://user-images.githubusercontent.com/47117960/91867980-8500b900-ec74-11ea-9d50-c09192f55f6e.png)


El único problema que persiste es que al pinchar sobre mis Contratos se prodice un error 500
![image](https://user-images.githubusercontent.com/47117960/91868089-a792d200-ec74-11ea-8b50-1210fc79a51f.png)

**Comment by jorgereal** [comment]
Hemos corregido también el acceso a la pestaña "mis contratos" para que no falle en caso de que no tenga ninguno asociado (no se muestra ningún contrato y los botones de abajo alertan de que no hay ningún contrato seleccionado).

Subido a PRO.
