### ISSUE TITLE
WEB Representación - URGENTE - TimeOut importa_liquidaciones.php

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#940]
Necesitamos ejecutar el script para importar liquidaciones pero da time out desde la web

![image](https://user-images.githubusercontent.com/47117960/91849683-b2da0380-ec5c-11ea-9b94-8676722444fc.png)

He intentado ejecutarlo con wget desde linea de comandos como otrosscripts con este problema 

C:\Users\Administrador>wget -O- --output-file="C:\inetpub\wwwroot\Web Productores\clientes\tareas\log.txt" "http://localhost:8088/clientes/tareas/importa_liquidaciones.php?modo=cron&id=9

pero me sigue dando el timeout

![image](https://user-images.githubusercontent.com/47117960/91849498-78706680-ec5c-11ea-90f4-192d39d2c22e.png)

¿Se os ocurre qué podemos hacer para evitar este problema?

**Comment by jorgereal** [comment]
Hemos cambiado el parámetro max_execution_time de la configuración del php de 300 segundos a ilimitado y hemos ejecutado el script con la misma sentencia que utlizaste del wget, esta vez sin que de timeout.

![image](https://user-images.githubusercontent.com/22742905/91858911-19b1e980-ec6a-11ea-9ee6-5d9daa14d73d.png)

**Comment by dgarciageo** [comment]
Perfecto Jorge, muchas gracias!
