### ISSUE TITLE
NAV-GAC-Facturas NC

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#941]
Nos hemos encontrado con que las cuando estamos haciendo la venta de las facturas de autoconsumo NC si no nos damos cuenta de registrar la compra antes que la venta no se liquidan correctamente 
La cuestión es que esto se hace dentro del proceso habitual de facturación en que se registran primero las ventas y después de las compras. Es por ello que en ocasiones se nos "cuelan" y no registramos la compra antes y eso conlleva a que no liquidamos al cliente la compra contra la venta y por tanto remesamos un importe erroneo. 
?Sería posible durante el proceso de registro para este tipo de facturas verificar si la compra está registrada y si no lo está registrarla en el mismo proceso o va a ralentizar mucho?

**Comment by JMunoz17** [comment]
Belén, corrígeme si me equivoco, pero si no recuerdo mal el procedimiento a seguir era el siguiente:
- Registro manual de la factura de venta.
- Registro manual de la factura de compra.
- Lanzar proceso para liquidar ambas facturas desde la factura de compra registrada.

No nos quedó otra que hacerlo así ya que si lo hacíamos todo automáticamente desde el registro de la factura de venta daba muchos problemas.

**Comment by bpesquero** [comment]
Ok.No lo teníamos nosotras claro.
Podríamos embeber este proceso en el que estáis desarrollando actualmente de liquidar abonos y facturas, se trata de no tener que lanzar manualmente un montón de procesos.

**Comment by bpesquero** [comment]
Cuando lanzo el proceso de liquidación desde compra me da el siguiente errro. ¿Me podéis recordar dónde lo configuro? No lo encuentro..

![image](https://user-images.githubusercontent.com/20299071/92303338-20937180-ef74-11ea-88e1-98ea0122e8fa.png)
