### ISSUE TITLE
NAV-HECEN- FActura G- FV/2020057257-HECEN/11613

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#944]
AL hacer la factura de venta del asunto, se trata de una regularizadora, no resta el consumo facturado en la factura H/20200039496

**Comment by bpesquero** [comment]
IDem con FV/202004854 y FV/2020048575

Parece que hay un problema por diferencia de 1 día entre la factura regularizada y la regularizadora y por eso no coge el consumo de la regularizada.

**Comment by JMunoz17** [comment]
Efectivamente, es porque en los F1s viene mal la fecha desde del término de energía, debería venir un día menos (la fecha desde CCH también viene mal).

He mirado para esta distribuidora y si que he localizado una factura tipo G donde en el F1 se aplicaba correctamente el criterio de fechas, por lo que entiendo que el criterio de +1Dia en la fecha desde esta bien.

Nosotros al buscar las facturas a regularizar buscamos aquellas cuya fecha desde sea mayor o igual a la fecha desde del término de energía. Entiendo que esto esta bien y no debemos cambiarlo no?

**Comment by bpesquero** [comment]
Efectivamente no hay que cambiarlo, pero no sé cómo podemos hacer para cargar estas facturas de una forma sencilla. Con cambiar el criterio de +1D sería suficiente, cargarlas y volver a cambiarlo?

**Comment by JMunoz17** [comment]
Pues al menos para el HECEN/11613 la compra ya esta registrada así que tengo que cambiar yo los datos por detrás en los peajes y volver a generar la venta.

Lo hago y os paso los números de factura para que las reviséis.

**Comment by JMunoz17** [comment]
Facturas generadas:

HECEN/11613 -> FV/2020064032
HECEN/11618 -> FV/2020064033
HECEN/11711 -> FV/2020064035

Revisad que estén ok.

**Comment by bpesquero** [comment]
Comprobado y ok

**Comment by bpesquero** [comment]
ME pasa otra vez con otra por el mismo problema de fechas. Si me indicas cómo hacerlo, trato de arreglarla yo

FV/2020064567- HECEN/12059

**Comment by bpesquero** [comment]
La acabo de arreglar yo cambiando las fechas.
Vuelvo a cerrar la incidencia. Lo siento
