### ISSUE TITLE
NAV- GAC- Relacionar medidas P1D con factura de compra de peaje

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#945]
Actualmente, en relación a las medidas P1D el campo CCH invoice number se rellena cuando se carga la factura f1. Es decir, en la carga de F1 se busca si existen medidas de P1d (data source=3) para ese periodo de tiempo y se rellena el campo.
ESto es ok, pero insuficiente. Habría que tener en cuenta el proceso inversor, es decir, que en la carga de P1D se buscar si existe un peaje para esas fechas para rellenar el nº de factura de acceso.
Habría además que pasar un proceso sobre todas las medidas actuales sin P1D para buscar si existe factura de acceso para esa fecha y ese cUPS y rellenar el campo CCH invoice number

**Comment by jorgereal** [comment]
¿Cuál es el motivo de esta modificación? ¿Puede darse que se cargue antes el F1 que el P1D?
Ahora mismo eso no es posible porque existe un control en la carga de los F1 para contratos no telegestionados para los cuales deben existir medidas P1D en el periodo que se esté facturando.

Si a partir de ahora queréis contemplar esta opción comentamos el control y hacemos el resto de cambios, puesto que para la generación de la factura de compra no influye que no estén cargadas en ese momento las medidas.

**Comment by bpesquero** [comment]
No se exactamente cómo se llega a esta situación, pero la realidad es que en muchos casos tenemos las medidas del P1D cargadas y no tienen relacionada la factura de acceso, que si está en NAV.

De hecho, en ocasiones, carga el P1D y luego no hace la venta porque no tiene medidas suficientes


511177 | COM/01943 | ES0021000012682849MW | 13/06/2020 | 10/07/2020 | El contrato COM/01943 de tipo V con medida no   telegestionada no se puede facturar por que no tiene medidas horarias P1D | BPESQUERO | ##########
-- | -- | -- | -- | -- | -- | -- | --


Y en otras ocasiones la factura sale mal porque no tiene todas las medidas asociadas

FV/2020014088
--



Es fácil ver lo que te digo, si te coges las medidas del P1D por CUPS y ves los huecos que no tienen asignado nº de cch puedes ver con facilidad como muchas de ellas si que tiene realmente el peaje cargado en NAV

select cups, [CCH Access Invoice No_],min([Posting Date]), max([Posting Date]), count(1)
from [GEOATLANTER$Hour Measure]
where DataSource = 3
group by cups, [CCH Access Invoice No_]
order by 1, 3

FV/2020014088
--

**Comment by jorgereal** [comment]
El problema se debe a que se están cargando medidas duplicadas por algún error en la importación de los P1D (en ciertos casos no avisa de que la medida ya existe y la vuelve a insertar). Esto está relacionado con la tarea #907 . La segunda vez que se importan ya se ha importado el F1 y se ha rellenado el Nº factura CCH, por lo tanto las segundas se quedan con el campo vacío.

Vamos a buscar el error en la importación y eliminar las medidas horarias duplicadas con el Nº factura CCH vacío (tanto en las tablas nuevas como en la antigua).
De esta forma no debería existir ninguna medida P1D con el CCH Invoice No. vacío y el F1 cargado.

**Comment by bpesquero** [comment]
jorge creo que no son exactamente medidas duplicadas. Por ejemplo para una factura que cubra el mes de enero entero, Nos publican medidas pero dejan un hueco en el día 13. Las medidas se carga, se carga la factura, se va a facturar y tenemos problema porque falta un día, reclamamos la medida, nos dan la medida de ese día, la cargamos y ya nunca se relaciona con el peaje,
Antes de eliminar los datos investiga y me dices lo que has encontrado

**Comment by jorgereal** [comment]
Después de revisar a fondo los datos hemos encontrado distintos casos por los que las medidas no tienen relleno el Nº Factura CCH:

1.- Medidas duplicadas debido a un error en la importación P1D. Hemos localizado el error, si se intentaba volver a importar un fichero ya importado, duplicaba aquellas medidas que ya estuviesen marcadas con el Nº Factura CCH por haber importado el F1.

2.-Medidas duplicadas con distinto origen. Como ocurre con el contrato COM/00732 y las medidas que van del 18-09-18 al 30-09-18, que existen con origen perfil (las utilizadas para facturar) y posteriormente se importaron las de P1D, las cuales quedaron sin asociar a la factura puesto que ya se había facturado el periodo.

3.-El caso que mencionabas, existen huecos en el periodo a facturar y cuando se importan las medidas que faltaban quedan con el CCH Invoice No. vacío.


Soluciones propuestas:

1.- Corregir el error en la importación P1D para no cargar medidas duplicadas y pasar un proceso que limpie las medidas repetidas con origen P1D, de cada dupla eliminar la que no tenga el Nº Factura CCH relleno.

2.- Hay dos opciones, eliminar las medidas duplicadas dejando solo las que hayan sido utilizadas para facturar o rellenar el número de factura CCH en las que esté vacío, aunque permanezcan en el sistema dos medidas para un mismo contrato, fecha y hora pero distinto origen.

3.- Recientemente se añadió un control para chequear que existen todas las medidas P1D para el periodo a facturar en los contratos con medidas horarias no telegestionadas al cargar los peajes. #878  Por lo tanto no podrá volver a darse el caso de cargar un peaje, que se marquen sus medidas y después cargar medidas en huecos existentes y que queden sin Nº Factura CCH.
Bastaría con pasar un proceso para rellena este campo en las medidas a las que le ocurrió esto.

**Comment by bpesquero** [comment]
1.- Ok. Pero cuidado con lo que consideramos una medida duplicada. Realmente se puede volver a publicar una medida con el mismo origen, mismo valor y misma fecha. Es el caso típico de facturas distintas de N. Lo que hay que tener en cuenta es que si la medida en BBDD tiene Núm de factura de acceso asociado hay que volver a cargar la medida y dejarla pendiente de que aparezca la nueva factura, pero si lo que ocurre es que la medida en BBDD aún no tiene asociada factura de acceso, en ese caso, no hay que cargar la nueva factura. 
¿qué error en la carga es el que habéis detectado a este respecto? Lo digo por si podemos intuir que nos ha afectado a más cosas

2.- Según el procedimiento que comentas el error no puede volver a reporducirse por la lógica actual. Si en algún caso se carga el P1D después del pérfil de facturación (podría ser por rectificativa, regularizardores o complementarias) se carga sin nº CCH. Se dejaría así.

3.- ok

con todo esto no entiendo los siguientes casos

1.- no se factura la venta de esta factura (es posterior a la implementación del check del punto 3)

COM/01943 | ES0021000012682849MW
-- | --
El contrato COM/01943 de tipo V con medida no telegestionada no se puede facturar por que no tiene medidas horarias P1D

2.- Estas dos ventas salen mal, por lo que veo no tiene todas las medidas P1_d (entiendo que el fichero se cargaría antes de la implemantación del punto 3, pero no lo he podido comprobar)


FV/2020014088
--
FV/2020018547


Por último, tenemos muchas facturas que no se cargan. He cogido al azar esta


Error.   Medidas P1D incompletas. Contrato: COM/01926. Fecha: 29/05/20.
--

Veo que realmente si que tenemos medidas completas, lo que pasa es que para algunas horas de un día están duplicadas. Habría que revisar este control.
Te envío el fichero por email

**Comment by bpesquero** [comment]
con respecto a las dos facturas que salen mal tenemos todas las medidas de ese punto ya, pero como ya están las facturas de compra no sé cómo tendremos qué hacer para relacionar todo y que no haya problemas.
Las medidas están en \\ni\esios\F1\REVISAR BELÉN\P1D\Medidas_propuestas\20200910_P1D_COM00881_AÑO2020.txt

Por si las quieres ver para cargarlas. no sé si lo suyo es cargarlas y luego pasar un proceso para rellenar la CCH

Gracias

**Comment by jorgereal** [comment]
1.- A la hora de cargar las medidas P1D en la tabla antigua, para comprobar si ya existía en BBDD, se estaba filtrando por origen F5D.

Además, según el código, es condición necesaria para importar la medida que no exista una ya para ese mismo origen, cups, contrato, fecha y no factura de acceso = '', como indicas. Este es el motivo de la mayoría de medidas sin Nº factura acceso, pues la primera vez que se importa una medida lo hace con el No factura de acceso = '', se carga su F1 y se rellena. Después se vuelve a cargar la medida y se inserta en el sistema al no detectar que exista otra con el No factura de acceso = ''.

¿No tenemos forma de comprobar si la medida que estamos insertando corresponde a una nueva factura o es una replica de una medida ya existente? Si no no puedo detectar cuales deben insertarse en la importación ni cuales borrarse en el proceso de eliminación de duplicados.

2.- Ok, lo dejamos así.

3.- Para pasar el proceso de rellenar el No factura de acceso me ocurre como en el punto 1. ¿Cómo identifico en qué medidas debo rellenarlo? Puede que una medida esté vacía porque pertenezca a una factura distinta de N y yo estoy encontrado un F1 ya importado para ese mismo periodo y le asigno un Nº factura de acceso que no corresponde.


Nos ponemos a revisar los casos concretos que nos has pasado.

**Comment by jorgereal** [comment]
Hemos revisado a fondo el caso del contrato COM/01943.
Las medidas existen, pero están marcadas con otro Nº factura de acceso.
Tras darle muchas vueltas y no encontrar ese número en ningún peaje ni factura de compra cargada hemos visto que ese mismo número de factura está marcado en las medidas de otro contrato. 
Se corresponde al F1:
F1\REVISAR BELÉN\P1D\ARREGLADO FER MEDIDA SUBIDA_HUECO EN VALIDADOS_ES0021000021127716RM_F1_01_9.xml

En teoría ese fichero no ha sido cargado aún, además, no podría haber marcado las medidas del contrato COM/01943 puesto que siempre se filtra por contrato, fechas... y no se corresponde de ninguna manera.

Entendemos que las medidas se deben haber marcado manualmente por error. Vamos a rellenar el No factura CCH correcto para que se pueda facturar la venta.

Seguimos con el resto de casos problemáticos.

**Comment by bpesquero** [comment]
1.- No tenemos forma de saberlo, por tanto si tenemos medidas con nº de factura de acceso y llega la misma medida, de entrada hay que cargarla. Igual ahora, si tenemos medidas duplicadas pero una tiene nº de factura de acceso y otra no hay que mantener ambas.
3.- Creo que lo suyo sería, si para una hora, CUPs, origen 3 y mismo valor de la medida tenemos un registro con CCH ya no se rellena más, si no se rellena con la factura que haya.


Con respecto al contrato COM/01943 me avisas cuando esté arreglado para tratar de facturarlo?

**Comment by jorgereal** [comment]
Ya hemos rellenado el No factura CCH correcto en las medidas del contrato COM/01943.

Efectivamente para la factura FV/2020014088 faltan medidas.
El peaje se cargó el día 03/06/20 y el control se creó el 09/06/20, de ahí que no alertara en la importación del F1.

Revisando la factura FV/2020018547 hemos visto que también faltan medidas, pero en este caso se cargó después de la fecha de la subida del control y debía haber saltado.
Existía un error en el control por el cual si las medidas del primer día de facturación eran correctas daba todas por correctas.

Hemos cargado las medidas que faltaban para esas dos facturas y hemos pasado un proceso para rellenar en ellas el no factura de acceso, tanto en la tabla antigua como en las nuevas.

También hemos modificado el control para corregir el fallo anterior y para que compruebe que exista al menos una medida por hora, no 23 , 24 o 25 horas en un día (según corresponda), de esta forma no fallará si existen medidas duplicadas aunque estén todas.

Se han subido las correcciones a PRE y PRO.

Faltan los dos procesos del último comentario, cuando los tengamos te avisamos.

**Comment by bpesquero** [comment]
AL tratar de volver a facturar las facturas del contrato COM/00881 ( FV/2020014088 y FV/2020018547, que ahora son FV/2020018760 y FV/2020018761) me da el siguiente log, creo que hay un problema con las medidas que se han cargado



Nº mov.	Nº contrato	CUPS	Fecha desde	Fecha hasta	Error/Aviso	Id. usuario	Fecha-Hora
212	COM/00881	ES0022000007273477HJ			Error, Las medidas P1D 2.689.482,  de la factura FV/2020018760 para el contrato COM/00881 no se corresponden con las medidas de cierre 3.175	BPESQUERO	15/09/20 21:34
213	COM/00881	ES0022000007273477HJ			ERROR,La potencia facturada 127,5 del peaje en el periodo 1 es diferente de la potencia facturada 106,25 y el contrato NO permite DIFERENCIA DE POTENCIA	BPESQUERO	15/09/20 21:34
214	COM/00881	ES0022000007273477HJ			ERROR,La potencia facturada 170 del peaje en el periodo 2 es diferente de la potencia facturada 148,75 y el contrato NO permite DIFERENCIA DE POTENCIA	BPESQUERO	15/09/20 21:34
215	COM/00881	ES0022000007273477HJ			ERROR,La potencia facturada 170 del peaje en el periodo 3 es diferente de la potencia facturada 148,75 y el contrato NO permite DIFERENCIA DE POTENCIA	BPESQUERO	15/09/20 21:34
216	COM/00881	ES0022000007273477HJ	01/04/20	28/04/20	Existe un error de solapamiento para la factura de venta FV/2020018760 con fecha inicio 01/04/20 y fecha fin 28/04/20 para el contrato COM/00881	BPESQUERO	15/09/20 21:34
217	COM/00881	ES0022000007273477HJ			Error, Las medidas P1D 3.401.468,  de la factura FV/2020018761 para el contrato COM/00881 no se corresponden con las medidas de cierre 3.802	BPESQUERO	15/09/20 21:36

**Comment by jorgereal** [comment]
El fichero con las medidas que faltaban tenía la energías multiplicadas por 1000.
Hemos vuelto a cargar todas las de los periodos de ambas facturas, modificando el proceso para que se importen correctamente las energías (luego lo hemos dejado como estaba).
Hemos borrado las que existían incorrectas para los periodos de ambas facturas y hemos rellenado en las nuevas el Nº de factura de acceso. Ya se podría volver a facturar.

También pasamos un proceso para rellenar el Nº factura CCH en las medidas de la tabla antigua y de las tablas nuevas para todos aquellos registros que cumplan:
	origen: P1D
	Nº factura CCH: vacío
	exista un peaje cargado para ese contrato y ese periodo
	no exista otra medida para ese origen, contrato, fecha, hora y con No. factura CCH relleno

Tan solo faltaría pasar el proceso de borrar medidas duplicadas con el siguiente criterio:
-Dejar tan solo un registro para aquellas medidas con origen P1D, mismo contrato, misma fecha, misma hora, mismo Nº factura acceso

Esto quiere decir que si existen dos medidas iguales pero una con Nº factura acceso relleno y la otra no, no se borraría ninguna.

¿Es esto correcto?

**Comment by bpesquero** [comment]
Asi es. Correcto

con respecto al contrato COM/00881 está maldito. Ahora las medidas salen bien, pero sin embargo la potencia considerada en la factura del 01/04 al 28/04 es la que aparece en el histórico de precios a partir del 28/04 ya que hubo un cambio de potencia. En este caso se trata de una 31A así que para calcular la potencia la potencia facturada hay que tener en cuenta el máxímetro. me da la sensacion de que hay un error en este caso y no se está teniendo en cuenta el histórico de precios sino directmaente la potencia de la ficha del contrato. Lo podéis echar un ojo?

**Comment by jorgereal** [comment]
Efectivamente el problema se debía al cambio de potencia que se produjo el 28/04.

En la facturación se estaban tomando los precios del 28/04, pues se filtraba para encontrar el último registro anterior o igual a la **fecha hasta** del término de potencia.

Se ha cambiado el cálculo para que se busque el último precio anterior o igual a la **fecha desde** del término de potencia y se ha generado la prefactura FV/2020018768 (hemos dejado la FV/2020018766 por si queréis compararlas).

¿El cambio es correcto? ¿O habría que buscar los precios anteriores pero no iguales a la "**fecha hasta"** del término de potencia?

**Comment by bpesquero** [comment]
YO creí que esto ya lo habíamos corregido, quizá no para las uqe tienen maxímetro. Hay que facturar cada trozo con la potencia que le corresponda

**Comment by jorgereal** [comment]
Hemos corregido el algoritmo de cálculo del término de potencia para los contratos con maxímetro para que se facturen por separado los distintos tramos de precios.
Para los contratos sin maxímetro si estaba contemplado esto.

Hemos subido el cambio a PRE y hemos facturado el mismo periodo para el contrato COM/00881, se ha generado la prefactura de venta FV/2020010875.

Si lo veis ok lo subimos a PROD, aunque este ejemplo ya se encuentra registrado.

Tenemos ya el proceso de borrado de medidas duplicadas, estamos haciendo pruebas en PRE dado que se trata de un tema delicado. Cuando estemos seguros de que es correcto lo lanzamos en PROD.

**Comment by jorgereal** [comment]
Hemos pasado el proceso de eliminación de medidas duplicadas según los criterios definidos en GEO PROD.
Tan solo fue necesario pasarlo en las tablas antiguas (las que se utilizan para facturar), en las nuevas la clave ya cumple las especificaciones, un único registro por Origen (P1D), CUPS, Contrato, Fecha, CCH Access Invoice No.

Se han eliminado 29013 medidas de 434615 existentes con origen P1D.

**Comment by bpesquero** [comment]
Perfecto. VAmos a tratar de facturar todo lo pendiente.
En cuanto al contrato COM/00881, me volví loca, lo siento mucho. no tiene sentido con máximetro facturar por tramos la potencia. De hecho, lo que habría que hacer si nos pasan una factura con maxímetro que incluye un cambio de potencia es reclamarla. En este caso lo que se ve muy claro es que hay un error de un día en la fecha de cambio de potencia, que debería ser el 29 en vez de el 28. Nada más. Lo siento muchísimo.

**Comment by jorgereal** [comment]
Vale, entonces no subimos el cambio y lo deshacemos de PRE.

**Comment by bpesquero** [comment]
Please
