### ISSUE TITLE
NAV - Nos falta Dll reclamación de deuda

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#947]
Nos falta esta Dll en el equipo de sabrina (Dseta)

**Comment by dgarciageo** [comment]
![image](https://user-images.githubusercontent.com/47117960/93868332-9b75bf80-fcca-11ea-9cc4-bfc2db21ab44.png)

**Comment by JMunoz17** [comment]
Respuesta vía mail.

**Comment by JMunoz17** [comment]
Instalada la dll en el equipo de Sabrina.
