### ISSUE TITLE
NAv-GAC-Problema facturación contrato COM/00749

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#949]
EStamos teniendo problemas con este contrato:

al sacar la venta sale vacíos los términos de energía y no tiene detalle adjunto. Además no da error el log.

TEnéis una prefactura de venta para poder verlo,

**Comment by jorgereal** [comment]
El problema se debe a que llegó antes el peaje de las facturas para los periodos: 01/08/20-10/08/20 y 11/08/20-31/08/20 que el del periodo 01/07/20-31/07/20.

Por lo tanto entendemos que se facturó con el proceso de forzar facturación en lugar de con el de facturar normal, ya que éste daría fallo de que existen huecos.

Cuando se fuerza la facturación y no existen medidas para el contrato y el periodo a facturar el proceso no localiza el no de factura de acceso y no se genera bien el perfilado.

Hemos borrado las 3 prefacturas que existían para el contrato y hemos lanzado la facturación normal para el periodo 01/07/20-31/07/20. Se ha generado la prefactura FV/2020020534, esta vez con el término de energía relleno.

No se puede lanzar la facturación normal para los otros dos periodos sin registrar antes esa prefactura.

¿Modificamos el proceso de forzar facturación para localizar el no de factura de acceso correspondiente en el caso de no existir medidas?

**Comment by bpesquero** [comment]
Si,  habría que modificar el proceso de forzar facturación para que perfle correctamente 
Dejo la factura de julio en estado abierto para asegurarme de que no se registra y así probar el proceso de forzar facturación cuando esté modificado

**Comment by jorgereal** [comment]
Hemos añadido al proceso de "forzar facturación" el código necesario para localizar el "No. de factura de acceso" siempre que exista un cierre para el contrato con la misma fecha desde y fecha hasta que se rellenen en el request. De esta forma se perfila correctamente y se calcula el término de energía.

Subido a PRE y PRO.

**Comment by bpesquero** [comment]
Probado y ok
