### ISSUE TITLE
NAV - cambio de estado de firmado cliente a tramitado ATR

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#95]
Cuando tenemos un contrato en estado firmado cliente y generamos el correspondiente fichero paso 01 y lo exportamos, no cambia el estado de contrato a tramitado ATR, como debiera.

**Comment by PKFEric** [comment]
PROBAR

**Comment by PKFEric** [comment]
ARREGLADO

**Comment by bpesquero** [comment]
Probado y ok
