### ISSUE TITLE
NAV-GAC-problema facturacion autoconsumo con energía saliente=0

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#950]
0021_0587_F1_01_03200908030486933_ES0021000005538452VA0P.xml |   |   | Error, Tenemos un contrato   autoconsumo y no viene informada AS en el F5D. | 20/09/2020
-- | -- | -- | -- | --

REalmente lo que ocurre es que la ES es 0. El cierre de la factura de ES es 0 y la energía facturada coincide con la AE.

**Comment by bpesquero** [comment]
EL fichero lo podéis encontrar en 
\\ni\esios\F1\Pendientes de facturar\incidencia Attest\NAV-GAC-problema facturacion autoconsumo con energía saliente=0 #950

**Comment by jorgereal** [comment]
Ahora mismo el control comprueba que si el contrato de autoconsumo tiene un algoritmo <> F y las fechas del peaje están comprendidas en las fechas de vigencia del contrato es obligatorio que la ES sea <> 0.

¿No es correcto este control? ¿Debemos comentarlo o se trata de un error en el fichero y las medidas?

**Comment by bpesquero** [comment]
Hay que diferenciar entre no tener medidas y tener medida a 0. Si le AS viene informada en el cierre como 0,es correcto

**Comment by jorgereal** [comment]
Hemos modificado el control para no marcar error si en el cierre la energia saliente es 0.

Ya se ha importado correctamente el F1.

Subido a PRE y PRO.
