### ISSUE TITLE
WEB/NAV - Cambiar asunto Notificación Web Parte Pública (Cambio de titular)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#951]
Necesitamos cambiar el asunto del correo de cambio de titular y pagador diferente

Notificación Web Parte Pública Proxima/Atulado Energía por **Notificación cambio titular y pagador diferente**

![image](https://user-images.githubusercontent.com/47117960/93900601-e35e0c00-fcf5-11ea-9d02-85bdf69300cb.png)

**Comment by jorgereal** [comment]
Se ha cambiado el asunto del correo de cambio de titular y pagador diferente en las dos webs.

Subido a PRO.
