### ISSUE TITLE
NAV - Error al imprimir facturas (María)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#952]
A maría le esta dando el siguiente error al imprimir facturas

 
![image](https://user-images.githubusercontent.com/47117960/93913830-e8c35280-fd05-11ea-806d-dbaa0d299083.png)

**Comment by JMunoz17** [comment]
Ya debería poder imprimir facturas.
Es el usuario mpiñeiro no? Estaba en el sql solo como data reader, le he puesto db owner para que pueda lanzar también este tipo de procesos.

**Comment by dgarciageo** [comment]
Perfecto Jaime,

Muchas gracias

**Comment by dgarciageo** [comment]
Buenas Jaime,

ahora le sale el siguiente error

![image](https://user-images.githubusercontent.com/47117960/94043735-98172c80-fdcd-11ea-8988-576499c73ab1.png)

**Comment by JMunoz17** [comment]
Hay que instalar en su equipo el automation de envío de mails.
\\NI\Esios\Addins GEO\Envio Mail

Instálaselo tu o si quieres diles que me llame y me conecto con ella, como prefieras.

**Comment by dgarciageo** [comment]
Se lo instalo, muchas gracias
