### ISSUE TITLE
NAV-HECEN-registro de abonos de venta

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#959]
Seguimos teniendo el mismo problema para registrar los abonos por calidad de suministro que ya comunicamos
![image](https://user-images.githubusercontent.com/20299071/94257212-3ec50f80-ff2b-11ea-87d2-9cd4f13bf90f.png)

TEnemos pendientes dos abonos lanzados en HECEN

**Comment by jorgereal** [comment]
Estamos intentando replicar el abono lanzando la facturación para el contrato HECEN/09321 con fecha 22/03/19.
Nos ha generado otro abono con la misma línea pero algunos campos cambiados de signo, el código no se ha tocado posteriormente al 01/09/20, que es la fecha de registro del abono FV/2019021232.

Esos dos abonos que no podéis registrar, ¿los generáis de esta forma? ¿Habéis cambiado el valor de algún campo a mano una vez generado?

**Comment by bpesquero** [comment]
No, no hemos cambiado nada a mano. Solo se me ocurre que sean abonos que se hubieran generada hace tiempo, que se hubieran quedado abiertos por algún motivo y se hayan vuelto a lanzar ahora...

**Comment by jorgereal** [comment]
Hemos corregido el proceso de generación de abonos de venta, en la tarea #924 solo se corrigió en la compra.
Se han generado de nuevo los abonos para los contratos HECEN/09321 y HECEN/07832, dando lugar a los documentos FV/2020065275 y FV/2020065276.

Los abonos antiguos FV/2019021232 y FV/2020065274 aún no se han borrado.

Deberíais poder registrar los nuevos correctamente.

Subido a PRO.

**Comment by bpesquero** [comment]
Hecho.
