### ISSUE TITLE
NAV - problema envío mail con impresión de abonos

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#96]
Al hacer la impresión de los abonos con envío de mail, había 5 abonos y sólo salió el mail de uno de ellos, y además de forma incorrecta, ya que no ha completado ningún dato ni nombre, ni dirección, ni importe,...

**Comment by PKFEric** [comment]
ARREGLADO.->PROBAR

**Comment by bpesquero** [comment]
Al imprimir abonos filtrando por fecha de registro=10/10/2016 y Nº cliente= CL00073 imprime tres abonos pero sólo llega email de uno de ellos, y además el texto del mail es el correspondiente a factura y no a abono.
Reenvío el correo recibido a Eric

**Comment by PKFEric** [comment]
Hola Belén, esto ya esta arreglado, te he dejado los tres abonos sin marcar para que lo puedas probar tu y al cliente CL00073 le he dejado la dirección de correo bpesquero@geoatlanter.com para que llegen a esa.

**Comment by bpesquero** [comment]
Probado y ok
