### ISSUE TITLE
NAV-GAC-Facturación FC/2020020119 - COM/02740

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#964]
AL intentar hacer la venta de esta factura de compra (es una G) da el siguiente error y no hace la factura

Error, Las medidas   F5D 1.359, de la factura FV/2020020836 para el contrato COM/02740 no se   corresponden con el termino de Energia 2.717,212
--

Realmente no lo entiendo. Yo me he descargado el F5D y las curva de carga suma 1562, lo mismo que los cierres asociadas a la factura. Debe haber algo que no estoy viendo.

**Comment by jorgereal** [comment]
Los problemas en la facturación de este contrato se deben a que el rango de fechas que incluye el cierre asociado a la factura tipo G va del 24/02/20-22/09/20, pero hubo un cambio de contrato el 24/03/20. Pasando del COM/02094 al COM/02740.

Esto podríamos arreglarlo cambiando la fecha inicio de los precios del contrato COM/02740 para que sea 24/02/20 en lugar de 25/03/20 y cambiando las medidas del contrato COM/02094 para que pertenezcan al COM/02740 o bien replicando estas.

¿Lo hacemos así?

**Comment by bpesquero** [comment]
Bueno, vamos a solucionarlo así está vez, pero no es la solución a largo plazo, deberíamos dar una vuelta a las facturas G

**Comment by bpesquero** [comment]
Me vas  a perdonar, pero según he escrito me he dado cuenta que realmente lo que hay que hacer es reclamar la factura, no pueden emitir una regularizadora que tenga en el camino un cambio de titular
Olvidate de arreglarla, la voy a dejar como reclamada
