### ISSUE TITLE
NAV -Pregunta: Configuración SMTP de NAV

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#966]
Buenas Jaime,

¿Dónde esta la configuración SMTP de NAV?
Es decir, estos parámetros pero en Navision
Si están hardcodeados, necesitaríamos hacerlos configurables, es esto posible?

![image](https://user-images.githubusercontent.com/47117960/94988898-e3b99b00-0570-11eb-985f-b7c045357a49.png)

Muchas gracias

**Comment by jorgereal** [comment]
Buenas Dani,

La configuración SMTP de NAV la tienes en el departamento Administración/Administración de IT/Configuración General/Configuración Correo SMTP

**Comment by dgarciageo** [comment]
Perfecto Jorge,

Muchas gracias

**Comment by dgarciageo** [comment]
Buenas Jorge,

Podemos ampliar el campo a 200 caracteres por ejemplo? 
![image](https://user-images.githubusercontent.com/47117960/95058678-22c62880-06f8-11eb-8d3b-505a3e121c6e.png)
No cabe más de 30 y la cuenta de atencionalcliente@proximaenergia.com no cabe

Muchas gracias,
Dani

**Comment by jorgereal** [comment]
Hemos ampliado el campo a 200 caracteres.

Subido a PRE y PRO.

**Comment by dgarciageo** [comment]
Perfecto gracias!!
