### ISSUE TITLE
NAV-GAC-facturación P1D

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#967]
Seguimos con problemas con la facturación de los ficheros P1D
COM/00062-> El contrato COM/00062 de tipo V con medida no telegestionada no se puede facturar por que no tiene medidas horarias P1D

 COM/01385 -> El contrato COM/01385 de tipo V con medida no telegestionada no se puede facturar por que no tiene medidas horarias P1D

COM/01961-> El contrato COM/01961 de tipo V con medida no telegestionada no se puede facturar por que no tiene medidas horarias P1D

Realmente yo miro en la BBDD y si veo las medidas

![image](https://user-images.githubusercontent.com/20299071/95098124-9420ce00-072e-11eb-82c5-b376612bf307.png)

**Comment by jorgereal** [comment]
Las medidas de esos contratos no tenían el Nº de factura de acceso relleno.
Esto debería haberse corregido con el proceso que pasamos para ello, pero hemos encontrado un error en los filtros por el que algunas medidas en la tabla antigua no pasaron por el proceso y no se rellenaron.
Lo hemos corregido y hemos vuelto a lanzar el proceso para estos tres contratos.
Ya está relleno el Nº factura de acceso, deberíais poder facturar.

Mañana volvemos a pasar el proceso para todas las medidas del 2020, el fallo en los filtros solo afectaba a algunas medidas de este año.

**Comment by jorgereal** [comment]
Se ha pasado el proceso corregido para todas las medidas de nuevo, ya no deberían volver a darse fallos de este tipo.
