### ISSUE TITLE
NAv-GAC-COM/02845-facturación excedentes

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#968]
AL cargar un fichero F1 del contrato del asunto salta el siguiente error

Error   XML, excedentes del F1: 212,67 no coincide con la ES de las medidas F5D:   222,719 para el contrato: COM/02845 y Nº factura acceso: FED20097097.

En primer lugar se cargaron unas medidas cuyo excedente sumaba 222,719. Al intentar cargar la factura y dar este error se reclamaron las medidas al distribuidor y nos publicó otro fichero cuyas medidas sumaban 212,67. ESte fichero ha sido cargado hoy u a continuación hemos cargado el fichero F1 y ha dado el error que menciono.¿ No debería considarar las últimas medidas cargadas? ¿Deberíamos tener un proceso de eliminación de medidas que nos permitiera en estos casos eliminarlas siempre que no estén asociadas a una factura? No sé cual es la mejor forma para gestionar estos casos
Envío factura F1 por email

**Comment by jorgereal** [comment]
Ahora mismo para el contrato COM/02845 y periodo 01/07/20..31/07/20 solo se encuentran cargadas las medidas que suman 222,719.

No hemos encontrado el fichero con las medidas corregidas que suman 212,67. Solo hemos encontrado el fichero F5D_0112_0587_20201006.0 que se cargó el 06/10/20 que contiene medidas de agosto.

De todas formas, en la carga de ficheros F5D, si se va a importar una medida que ya existe esta se salta.
Podemos añadir un check al proceso de importación de F5D de "Sustituir medidas existentes" para que en caso de que existan medidas para el mismo contrato, fecha, hora, Nº factura de acceso y origen F5D estas se sustituyan por las nuevas.
Si ya estuviesen asociadas a alguna factura se mostraría un error en log y no se sustituirían.

¿Os parece bien esta opción?

Pasadnos por mail el fichero con las medidas corregidas que suman 212,67.

**Comment by bpesquero** [comment]
Ok. Te envío fichero por email. Me podrías dar una estimación de horas?
Gracias

**Comment by jorgereal** [comment]
Realizar esa adaptación nos llevaría 2h.

**Comment by bpesquero** [comment]
Adelante

**Comment by jorgereal** [comment]
Se ha añadido la adaptación para sustituir medidas en la carga de los F5D.
Se han vuelto a cargar las medidas para el contrato COM/02845 (01/07/20-31/07/20) y se ha importado el F1 que daba problemas.

Subido a PRE y PRO.

**Comment by bpesquero** [comment]
probado y ok
