### ISSUE TITLE
NAv-GAC- Facturación COM/01924

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#969]
Se trata de un contrato que se factura con medidas Oracle. Al forzar la facturación para el periodo 010920..300920 da el siguiente error
División por cero.0 / 0

Normalmente pasa esto si no tenemos precios para ese periodo o cosas similares. Seguro qeu es algo que se me está escapando, peor no doy con ello. A ver si me podéis indicar que es lo que le pasa...

**Comment by jorgereal** [comment]
El problema se debía a la modificación que añadimos en el proceso de forzar facturación de buscar el Nº factura de acceso en el cierre para el periodo seleccionado para que pudiese perfilar #949.

Para el caso de los contratos con medidas de Oracle no aplica, puesto que estas medidas vienen sin Nº factura de acceso, y al no encontrarlas intenta perfilar.
Se ha añadido la condición al proceso de forzar facturación para que si el origen de medidas es Oracle no se busque el Nº de factura de acceso.

Se ha facturado el contrato COM/01924 para el periodo 010920..300920 y se ha generado la prefactura de venta FV/2020021016
