### ISSUE TITLE
NAV-GAC- facturación venta FC/2020020660 - COM/02834

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#971]

**Comment by bpesquero** [comment]
AL forzar la facturación de la factura de compra del asunto da el, siguiente error, cuando la curva de carga está informada como 03
Error, Las medidas F5D 339, de la factura FV/2020021506 para el contrato COM/02834 no se corresponden con el termino de Energia 598,719

**Comment by jorgereal** [comment]
El problema se debía a que al tratarse de una factura tipo G (regularizadora) y traer las líneas con el signo invertido del término de energía de los documentos ya facturados en el periodo implicado, se estaban trayendo las líneas de otra factura tipo G, que ya incluía líneas del término de energía en negativo.

En el control tan solo se tenían en cuenta las líneas positivas (para evitar contabilizar las líneas del término de energía de las facturas anteriores), pero en este caso existían líneas positivas del término de energía traídas de documentos anteriores.

Se ha creado un nuevo campo "regularizadas" en las líneas de factura, para marcar aquellas líneas que se traen de otros documentos al facturar una tipo G y se ha modificado el control para no tener en cuenta estas líneas en la suma del término de energía.

Se ha facturado correctamente el contrato generando la prefactura de venta: FV/2020021507

Subido a PRE y PRO.

**Comment by bpesquero** [comment]
La factura no es correcta. Realmente no entiendo el cambio de que las líneas marcadas como regularizadas no vuelvan a tenerse en cuenta. Si esto es así, no tendríamos que traer ni las líneas así marcadas ni las líneas a las que regularizaron en la factura origen.
La factura tiene varios problemas.
La línea correspondiente al periodo de la factura debería traer el valor del cierre, para después restar todo lo facturado previamente.
LA primera factura no la está considerando porque no coinciden las fechas, me temo que tenemos que cambiar las fechas en la tabla de toll y closing, ya que la primera factura tiene fecha 8/05 y ahora la reguarlizadora dice que es del 9/05.
No se tiene en cuenta un abono registrado. La idea es que las facturas abonadas no "resten " en las regularizadoras

La factura debería tener en cuenta el siguiente cierre y las siguientes facturas

  |   |   | Energía |   | Energía en factura
-- | -- | -- | -- | -- | --
09/05/20 | 06/09/20 | Cierre P1 | 783 |   | 783
09/05/20 | 06/09/20 | Cierre P2 | 639 |   | 639
08/05/2020 | 07/06/2020 | C/20200010094-P1 | -97,358 |   | -97,358
08/05/2020 | 07/06/2020 | C/20200010094-P2 | -122,42 |   | -122,419
08/06/2020 | 08/07/2020 | C/20200012913-P1 | -114,39 |   | -114,392
08/06/2020 | 08/07/2020 | C/20200012913-P2 | -144,92 |   | -144,92
09/07/2020 | 07/08/2020 | C/20200018156-P1 | -394,58 |   | -394,582
09/07/2020 | 07/08/2020 | C/20200018156-P2 | -208,83 |   | -208,828
09/07/2020 | 07/08/2020 | C/20200020470-P1 | -394,58 | abonado | 0
09/07/2020 | 07/08/2020 | C/20200020470-P1 | 114,392 | abonado | 0
09/07/2020 | 07/08/2020 | C/20200020470-P2 | -208,83 | abonado | 0
09/07/2020 | 07/08/2020 | C/20200020470-P2 | 144,92 | abonado | 0

**Comment by bpesquero** [comment]
La energía total a facturar tiene que ser 176 en P1 y 163 en P2

**Comment by jorgereal** [comment]
Hemos corregido el cálculo del término de energía para no traer las líneas de los documentos abonados.
Se ha cambiado la fecha desde en el peaje de la primera factura para que entre en el rango de fechas y se traigan sus líneas.

Se ha generado la prefactura de venta FV/2020021521.
Las líneas negativas ya coinciden con el cuadro que nos adjuntabas, el problema está en la energía del P1 y P2 que aparece en el cierre.

En el cierre viene P1=783 y P2=639, pero nosotros los cálculos los hacemos con las medidas del F5D, en este caso las correspondientes al número factura de acceso S7001N12613832, las cuales suman P1=176 y P2=163, que debería ser el resultado final de la suma de las líneas del término de energía.

Esto siempre ha funcionado así, por lo que entendemos que las medidas del F5D están incompletas.
Ahora mismo las medidas con número de factura de acceso S7001N12613832 van del 08/08/2020 al 06/09/2020, cuando en el F1 la energía activa indica que va desde 09/05/20 al 06/09/2020.
En otras G hemos comprobado que las medidas del F5D coinciden con el periodo de la energía activa como puede ser la factura de venta registrada C/20200011603 del contrato COM/00958.

No hemos encontrado el fichero F5D en el que venían estas medidas para comprobar si realmente estaban incompletas
¿vosotros lo tenéis identificado?

**Comment by bpesquero** [comment]
Las medidas del F5D efectivamente no son correctas. Por eso marqué el origen de la medida como 03 para que no coja la curva de carga, lo he hecho con otros y me ha funcionado bien.. Me temo que me esté liando.

**Comment by jorgereal** [comment]
Para que no coja la curva de carga además de marcar el origen de la medida como <> 01 no deben existir medidas para el Nº de factura de acceso que se esté facturando.

Hemos renombrado las medidas F5D que tenían número de factura de acceso S7001N12613832 a S7001N12613832_V1.

Ahora si ha realizado el perfilado y se ha generado la prefactura de venta FV/2020021522, esta vez con los importes del cierre.

**Comment by bpesquero** [comment]
Visto y ok
