### ISSUE TITLE
WEB Atulado - URGENTE: Botón de nuevo contrato área privada no funciona

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#972]
El botón de nuevo contrato del área privada no funciona. Se cierra sin opción sin mensaje de error. Por nuestra parte, el único cambio que hemos realizado en  la web es el siguiente:

Hemos añadido el siguiente script en la cabecera de las siguientes páginas de Atulado para cumplir con la nueva normativa europea de la RGDP.

"<script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="46be9f10-0805-4486-a7a6-c94f4fd72a15" data-blockingmode="auto" type="text/javascript"></script>"

AltaUsuario.aspx
Index.aspx
Para-Hogar.aspx
Para-Negocio.aspx

He probado a quitar el script de CookieBot pero tampoco funciona

**Comment by dgarciageo** [comment]
Buenas Jorge,

Este un contrato con titular diferente de pagador. Estos son los datos de los clientes:

Titular: CL11034
Pagador: CL11035

En altas de contrato con titular diferente de pagador, el IBAN del titular no se informa, sólo se informe el del pagador.

Me imagino que el botón de Nuevo contrato del área privada falla porque intenta rescatar el IBAN del titular para informarlo en el formulario de alta y que salga ya con datos por defecto.

Creo que lo único que tenemos que hacer es controlar, que cuando no encuentre el IBAN informado en Nav, en el formulario de lata se deje en blanco para que lo introduzca el usuario.

**Comment by jorgereal** [comment]
Hemos corregido el código para que funcione como indicas, en caso de no encontrar IBAN para el cliente titular se dejará en blanco para que se rellene en el formulario de alta del nuevo contrato.

Subido a PRO.

**Comment by dgarciageo** [comment]
Probado y ok
