### ISSUE TITLE
NAV-GAC- fecha fin renting (autoconsumo)

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#973]
la fecha fin de renting no se actualiza al eliminar o dar de alta una nueva financiación

**Comment by jorgereal** [comment]
Se ha añadido al actualización del campo fecha fin renting al eliminar una financiación (en función del valor del campo fecha puesta en marcha) o dar de alta una nueva (en función de la fecha insertada al lanzar el proceso).

Subido a PRE y PRO.

**Comment by bpesquero** [comment]
Al eliminar una financiación la fecha fin debería ser vacía y al dar de alta una nueva no está haciéndolo en función de la fecha lanzada en el proceso de alta de la financiación sino que coge la fecha de puesta en marcha y la duración

![image](https://user-images.githubusercontent.com/20299071/96452922-0f4baf00-121a-11eb-8c75-41a805bcf20d.png)

**Comment by jorgereal** [comment]
Hemos modificado el proceso para que al eliminar una financiación se vacíe la fecha fin renting.
El cambio para que la fecha fin renting se calcule en función de la fecha lanzada en el alta de financiación ya lo hicimos.
Probad a salir y entrar de NAV.

Si sigue sin cuadraros decidnos una ficha concreta y lo revisamos.

Subido a PRE y PRO.

**Comment by bpesquero** [comment]
Probado y ok
