### ISSUE TITLE
WEB - Inclusión script RGDP en proxima y Atulado

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#976]
Tenemos que meter el siguiente script en la cabecera de todas las páginas aspx de próxima y atulado

<script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="46be9f10-0805-4486-a7a6-c94f4fd72a15" data-blockingmode="auto" type="text/javascript"></script>

¿Nos podéis dar por favor estimación de la tarea?

Muchas gracias

**Comment by jorgereal** [comment]
Añadir el script a la cabecera de todas las páginas sería media hora por cada web.

**Comment by dgarciageo** [comment]
De acuerdo, adelante.

**Comment by jorgereal** [comment]
Se ha añadido el script a todas las paginas aspx de las dos webs.

Subido a PRO.

**Comment by dgarciageo** [comment]
Tras la inclusión del script tenemos el siguiente problema.

Si aceptas todas las cookies se accede sin problema a las webs, pero si aceptas sólo las necesarias no logramos acceder.
¿Le podéis echar un vistazo urgente por favor?

![image](https://user-images.githubusercontent.com/47117960/97176540-60691f00-1795-11eb-99ca-75910622bf23.png)

Gracias

**Comment by jorgereal** [comment]
He vuelto a probar desde distintos PCs y con distintos navegadores y como hemos hablado por teléfono parece ser que funciona correctamente.

Tu navegador no debe estar limpiando las cookies correctamente.
Prueba a limpiarlas, cerrar el navegador completamente y volver a abrirlo.
Si no, puede ser que tengas alguna extensión del chrome que lo esté bloqueando.

**Comment by dgarciageo** [comment]
De acuerdo Jorge, gracias!!
