### ISSUE TITLE
NAV - Crear columnas para info representante legal en NAV (Proyecto ATLAS)

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#983]
La información del representante legal de empresas, nombre y DNI se almacena en la bbdd mysql de las webs. Si no migramos esta info perderíamos los datos

La tarea consiste en crear las columnas necesarias para almacenar la info del representante legal en la tabla customer de NAV:
- dni
- nombre
- apellido1
- apellido 2 

![image](https://user-images.githubusercontent.com/47117960/97552971-2c7c3c80-19d5-11eb-82ca-010fcdd43d79.png)

Yo me encargo de migrar la info desde la web al entorno de PRE (en primer lugar) mediante un UPDATE de la tabla customer.

**Comment by jorgereal** [comment]
Se han creado los cuatro campos en la tabla de cliente y se han sacado en su ficha.

Los nombres son:
-Legal Agent Name
-Legal Agent Surname
-Legal Agent Second Surname
-Legal Agent VAT Reg. No.

Subido a PRE y PRO.

**Comment by dgarciageo** [comment]
Tenemos el siguiente problema URGENTE

![image](https://user-images.githubusercontent.com/47117960/99680859-c9cf0b80-2a7d-11eb-8ae6-8df3170589df.png)

**Comment by jorgereal** [comment]
¿Cómo estáis creando el cliente?
¿Desde la ficha de cliente de NAV, desde el SQL directamente o desde algún proceso?

**Comment by dgarciageo** [comment]
En este caso desde la ficha cliente de NAV, pero me preocupa que falle el alta de clientes desde la web.
Estamos haciendo lago mal?

**Comment by jorgereal** [comment]
A nosotros nos deja crear clientes sin problema desde su ficha, tanto en GEO como en HECEN.
Los campos no están creados como que tengan que tener valor obligatoriamente.

¿Habéis cerrado y vuelto a salir de NAV?
Quizás no está sincronizando bien los cambios.

**Comment by dgarciageo** [comment]
Perdonad, era eso.
Probado y ok

Muchas gracias por vuestra ayuda!!
