### ISSUE TITLE
WEB Proxima - Cambio titular área cliente

### ISSUE THREAD

**Issue by dgarciageo** [PKFEric/webProxima#986]
No se puede cambiar de titular desde el área cliente, He probado con varios usuarios y en todos tengo el mismo problema.

![image](https://user-images.githubusercontent.com/47117960/97698899-949c5280-1aa9-11eb-99bd-879ef71fa614.png)

**Comment by jorgereal** [comment]
Respondida por mail

**Comment by dgarciageo** [comment]
Probado y ok!!
