### ISSUE TITLE
WEB - validación de potencia

### ISSUE THREAD

**Issue by bpesquero** [PKFEric/webProxima#99]
Al dar de alta un contrato, en la parte de datos de punto de suministro, cuando la potencia es incorrecta cambiar el mensaje de "potencia incorrecta" por "potencia incorrecta, el separador decimal debe ser "." (ejemplo: 4.60)"

**Comment by PKFEric** [comment]
CORREGIDO, ahora valida las potencias y verifica que los campos no tengan el caracter ",".

**Comment by bpesquero** [comment]
Ok. Sobra el "." después del último paréntesis, y falta una coma después de "incorrecta"

**Comment by PKFEric** [comment]
Ya esta corregido

**Comment by bpesquero** [comment]
ok
